jellyfin/jellyfin

- CONTRIBUTORS.md
- README.md
Remove the rationale (we don't really need those), adds details on the
goal right now, and mentions the transition to .NET Core and build
facilities.
The Debian build instructions have also been streamlined and organized
to optimize adding further instructions for different platforms.
Modifies the Contributors list to differentiate the (past) Emby contributors from our new contributor list of Jellyfin.
> Rearrange README for new project

- README.md
Adds a link to feathub to the README, letting us separate feature requests and voting from the GitHub issues.
> Add feathub link to README

- debian/postinst
> Remove obsolete jellyfin binary chmod

- MediaBrowser.WebDashboard/dashboard-ui/dashboard.html
- MediaBrowser.WebDashboard/dashboard-ui/strings/ar.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/be-BY.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/bg-BG.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/el.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/en-GB.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/en-US.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/es-AR.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/fa.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/fi.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/fr-CA.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/gsw.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/he.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/hi-IN.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/hr.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/id.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/is-IS.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/ko.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/lt-LT.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/ms.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/nb.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/no.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/pt-PT.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/ro.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/sl-SI.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/tr.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/uk.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/vi.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/zh-HK.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/zh-TW.json
Remove the WAN URL that was removed in #22 and rename the "In-Home" part, and remove the "thanks for supporting" button.
> Dashboard cleanup

- .gitignore
- MediaBrowser.sln
Added these 3rd party projects to the solution, otherwise JetBrains Rider won't find the source dependencies and the solution fails to build and ReSharper falls over.
> Add taglib-sharp and ImageMagick to MediaBrowser solution

- MediaBrowser.sln
If Emby.XmlTv isn't included in the solution, references to it aren't found by JetBrains Rider, and the solution can't be worked with under this IDE.
> Added required projects to the MediaBrowser solution

- README.md
Add a section on upgrading Debian installs from Emby to Jellyfin,
and reformat some other elements to make the list clearer.
Fixes remaining item in #77
> Reorganize README and add section on upgrades

- BDInfo/BDInfo.csproj
- DvdLib/DvdLib.csproj
- Emby.Dlna/Emby.Dlna.csproj
- Emby.Drawing.ImageMagick/Emby.Drawing.ImageMagick.csproj
- Emby.Drawing.Skia/Emby.Drawing.Skia.csproj
- Emby.Drawing/Emby.Drawing.csproj
- Emby.IsoMounting/IsoMounter/IsoMounter.csproj
- Emby.Naming/Emby.Naming.csproj
- Emby.Notifications/Emby.Notifications.csproj
- Emby.Photos/Emby.Photos.csproj
- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Emby.XmlTv/Emby.XmlTv.Test/Emby.XmlTv.Test.csproj
- Emby.XmlTv/Emby.XmlTv/Emby.XmlTv.csproj
- MediaBrowser.Api/MediaBrowser.Api.csproj
- MediaBrowser.Common/MediaBrowser.Common.csproj
- MediaBrowser.Controller/MediaBrowser.Controller.csproj
- MediaBrowser.LocalMetadata/MediaBrowser.LocalMetadata.csproj
- MediaBrowser.Model/MediaBrowser.Model.csproj
- MediaBrowser.Providers/MediaBrowser.Providers.csproj
- MediaBrowser.WebDashboard/MediaBrowser.WebDashboard.csproj
- MediaBrowser.XbmcMetadata/MediaBrowser.XbmcMetadata.csproj
- Mono.Nat/Mono.Nat.csproj
- OpenSubtitlesHandler/OpenSubtitlesHandler.csproj
- RSSDP/RSSDP.csproj
- SocketHttpListener/SocketHttpListener.csproj
I assumed that EmbyServer is the only executable in this solution, if this isn't the case tell me so I can revert it for that project.
For those that don't know why, what or how:
Ref: https://dotnetcoretutorials.com/2017/01/13/net-standard-vs-net-core-whats-difference/
> Change libraries from netcoreapp to netstandard

- debian/rules
Fixes #120 as per https://github.com/dotnet/sdk/issues/2526
Confirmed that this allows the `dotnet clean`
> Add maxcpucount to dotnet clean

- build-deb.sh
Adds a build script to automate the building of Debian packages using Docker. It fully cleans up after itself and puts the resulting `.deb` in the same place that a normal `dpkg-buildpackage` would (the directory directly above the repository).
> Add build script for Debian packages via Docker

- MediaBrowser.Api/ApiEntryPoint.cs
As this was, ffmpeg would continue to transcode video for timerDuration
seconds after stopping playback (i.e. returning to the menu). However,
this 60s timeout was a little obnoxious. Tested a 100ms timeout but
this ended up causing playback to constantly terminate. 2s seems like
the sweet spot where playback works normally, but terminating quickly
on stop.
Hotfixing to `master` for quick release as this was a blocking release bug
for 3.5.2-2.
> Lower the ffmpeg stop timeout duration

- MediaBrowser.WebDashboard/dashboard-ui/strings/en-US.json
This is required as preparation for weblate as the language file started with an UTF-8 BOM header, which broke python json
> Fixed encoding to make it compatible with Weblate

- debian/changelog
- debian/control
- debian/preinst
Fixes #176 and issues reported in Riot with the latest Debian build.
1. Remove the old Emby `/etc/sudoers.d/emby` cruft which can cause major system breakage on an update from `emby-server` if it is not `purge`'d first.
2. Remove the automated shlib deps and misc deps, as these were creating bad values.
3. Add the explicit libssl1.0.X dependency which is all that seems to really be required.
4. Make the maintainer the team rather than just one of us.
5. Bump up the Debian build version.
> Debian packaging improvements

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Profile was forced to constrained baseline which is really bad quality, especially with 3s keyframes interval.
Use the specified profile as with other encoders, but force constrained baseline if baseline is specified, since baseline is not supported by vaapi.
> Fix encoding profile handling for vaapi

- Dockerfile
**This is a breaking change for those currently using the `PUID` and `PGID` environment variables.**
The new method is to use Docker's built-in `user` option instead. This will *not* change the permissions of anything.
Ex. `docker run --user 1000:1000 -v /your/dir:/config jellyfin/jellyfin`. 
Resolves https://github.com/jellyfin/jellyfin/issues/220
> Remove PUID and PGUID env vars, stop chowning

- MediaBrowser.WebDashboard/dashboard-ui/manifest.json
Reenables support for most client apps that were broken by this rename change.
> Restore the name Emby in manifest.json

- Dockerfile.aarch64
There is no 2 version of the dotnet image for aarch64. Need to use a 3 image for now.
> Add aarch64 image

- MediaBrowser.Model/Configuration/ServerConfiguration.cs
The default preferred language in the startup wizard now defaults to English (United States).
> Fix default language

- RSSDP/LICENSE
Technically, we can import this as GPL'd into the project directly, but the changes might be useful to upstream, so preserving the sublicense is preferable and compatible. Eventual goal is to try to send the changes upstream and remove from the repo to a submodule.
Addresses #350
> Add license from upstream RSSDP project

- Emby.Server.Implementations/EnvironmentInfo/EnvironmentInfo.cs
- Jellyfin.Server/Program.cs
Small change, but ensures `EnvironmentInfo` doesn't get created without an OS
> Clean up EnvironmentInfo

- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Don't write each codec on a new line.
Use a regex to match codecs in the ffmpeg output.
ex: https://regex101.com/r/bn9IOy/12/
> Reduce log spam and clean up EncoderValidator

- Emby.Server.Implementations/Devices/DeviceManager.cs
- MediaBrowser.Model/Devices/DeviceQuery.cs
Fixes #352
Crash caused by uninstantiated UserId, which for a string defaults to the value `null`. Default value for Guid is Guid.Empty, which is a bunch of zeros but it still has a `.Equals` method.
> DeviceQuery: change UserId to GUID

- MediaBrowser.sln
Project uses manual versioning. This breaks very annoyingly with my global settings.
It would be a great QoL addition. And it doesn't really break anything for anyone.
> Stop version addins on solution from messing with the AssemblyVersions

- Dockerfile
This fixes the issue with chromecasts (#307 ) in docker scenarios also allows the androidtv app to work.
This is a stop-gap solution until we have our own ffmpeg builds.
> Change Dockerfile to use ffmpeg 4.0.3 rather than a distro one.

- .dockerignore
- CONTRIBUTORS.md
Right now making any changes to the Dockerfile or any of the Markdown files causes subsequent Docker builds to repeat step 5 (`COPY . .`) and all the following ones, including rebuilding jellyfin even when this may not be required.
By adding a .dockerignore file, the `COPY`-step ignores all matching files and thus does not trigger rebuilds on changes to those.
> Add Markdown and Docker files to .dockerignore

- .drone.yml
Only ensure Jellyfin builds and avoid the extra stuff included in the Dockerfile and Debian build scripts.
> Speed up CI

- Emby.Server.Implementations/ApplicationHost.cs
A function that has been "NotImplemented" since ever. Why? Geez.
> Remove RegisterServerWithAdministratorAccess

- Emby.Server.Implementations/Udp/UdpServer.cs
use "who is JellyfinServer?" and "who is Jellyfin?" instead of emby specific ones.
Resolves #395
> Change "who is EmbyServer?" and other udp responders to jellyfin alternatives.

- Jellyfin.Server/Jellyfin.Server.csproj
- Jellyfin.Server/Program.cs
- Jellyfin.Server/Resources/Configuration/logging.json
Perform logging to file on a background thread.
This means logging won't be bottlenecked by IO.
> Improve logging performance

- MediaBrowser.Api/Playback/BaseStreamingService.cs
The chromecast Emby app will request streams with only 2 audio channel. Jellyfin will correctly respond with the following media URL:
```
http://server-ip:8096/emby/videos/<item-id>/stream.mkv?DeviceId=<chromecast-id>&MediaSourceId=<item-id>&VideoCodec=h264,vp8&AudioCodec=aac,mp3,opus,flac,vorbis&AudioStreamIndex=1&VideoBitrate=30000000&AudioBitrate=437308&PlaySessionId=55c6303fb0444e958c05265e6eec08d5&api_key=<auth-token>&TranscodingMaxAudioChannels=6&CopyTimestamps=true&RequireAvc=false&Tag=f5be0495a3fe3ea4947070698c1a5889&h264-profile=high,main,baseline,constrainedbaseline&h264-level=42&aac-audiochannels=2&TranscodeReasons=AudioChannelsNotSupported
```
However, in the `StreamRequest` object, the `aac-audiochannels` will not be added to the `StreamOptions` property, which is later …
> Fix transcoding of AAC from 5.1 to stereo to support Chromecast

- debian/postinst
Without this, if not importing a previous config, the perms are broken on the config directories. Fixes this.
> Hotfix to postinst to correct permissions

- README.md
1. Replace all Wiki references to Readthedocs.io references
2. Clean up the layout a bit, remove some redundant bits and make
"about" bits consistent between Docs and README
> Update readme to use readthedocs and clean up

- .editorconfig
Let the debates begin!
Currently based on the default styles shipping with Visual Studio 2017. For .NET these are nice.
For typescript/javascript one might need some discussion.
> Codestyle EditorConfig file added.

- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
We don't need to log 10+ lines to check the ffmpeg version.
> Reduce log spam from ffmpeg info

- Dockerfile
This slightly speeds up rebuilding since the ffmpeg layer cache is used
even when Jellyfin source is changed.
> Download ffmpeg in a separate layer

- MediaBrowser.Model/Net/MimeTypes.cs
Fixes #485
Looks like we regressed and now only the .txt logs would open in the browser when clicked. 
Added in MimeType handler for .log files. Problem solved.
> Support `*.log` files in browser log viewer

- Emby.Server.Implementations/LiveTv/LiveTvManager.cs
- Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteLogFileTask.cs
- MediaBrowser.Controller/Entities/Movies/BoxSet.cs
- MediaBrowser.Controller/Entities/Movies/Movie.cs
- MediaBrowser.Controller/Entities/TV/Episode.cs
- MediaBrowser.Controller/Entities/Trailer.cs
- MediaBrowser.Controller/LiveTv/LiveTvProgram.cs
As discussed right now in the #jellyfin-dev chat, the GPL cleanup made a regression where double division turned into integer division
Fixes #489
> Fix regression in integer divisions in latest movies category

- MediaBrowser.WebDashboard/dashboard-ui/dashboardgeneral.html
Change link text in settings for "Learn how you can contribute" to readthedocs.io contributing entry rather than GitHub repo.
> Change contributing link in settings to readthedocs.io

- MediaBrowser.WebDashboard/dashboard-ui/scripts/myprofile.js
Fixes #483
Crash caused the endless loading circle.
Crash prevented password changes, icon updates, and easy pin code changes.
This pulls the fix from #412. Can Either merge this or reject it and merge the whole of #412.
> Fix userprofile.js crash

- Emby.Drawing/Common/ImageHeader.cs
Added support for progressive DCT-based JPEGs.
By adding a check for the SOF2 marker (C2)
Fixes #490 and #489
> Fix the DecodeJfif function to get proper image sizes

- MediaBrowser.Common/MediaBrowser.Common.csproj
- MediaBrowser.Controller/MediaBrowser.Controller.csproj
- MediaBrowser.Model/MediaBrowser.Model.csproj
This PR will add NuGet package info to the 3 projects needed by plugins.
These projects will get packaged with `dotnet pack` and uploaded to NuGet or Myget.
> Add NuGet package info to plugin projects

- Emby.IsoMounting/IsoMounter/LinuxIsoManager.cs
- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/EnvironmentInfo/EnvironmentInfo.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
- MediaBrowser.Model/System/IEnvironmentInfo.cs
These are easily accessible from the standard lib.
> Remove useless properties from IEnvironmentInfo

- MediaBrowser.Controller/Library/TVUtils.cs
- MediaBrowser.MediaEncoding/Subtitles/OpenSubtitleDownloader.cs
- MediaBrowser.Providers/Movies/FanartMovieImageProvider.cs
- MediaBrowser.Providers/Movies/MovieDbProvider.cs
- MediaBrowser.Providers/Movies/MovieDbSearch.cs
- MediaBrowser.Providers/Music/AudioDbArtistProvider.cs
- MediaBrowser.Providers/Music/FanArtArtistProvider.cs
- MediaBrowser.Providers/Omdb/OmdbImageProvider.cs
- MediaBrowser.Providers/Omdb/OmdbProvider.cs
- MediaBrowser.Providers/TV/FanArt/FanartSeriesProvider.cs
Updates the 5 API keys that I've been able to find, to our own API keys. All of these, where applicable, have been registered using a new account with the name "jellyfin" and the email address "team@jellyfin.org". This removes our dependency on the Emby API keys.
We should probably move these out of the deep-in-code, hardcoded locations they're currently in, but that can be a future project as we make them configurable from the UI.
Fixes #36
> Update Emby API keys to our own

- .github/CODEOWNERS
In conjunction with branch protection rules, this will require
approval from the Org owners (myself or @nvllsvm) before a merge
can be accepted.
> Add Master codeowners

- .github/CODEOWNERS
Reverts jellyfin/jellyfin#559
So there will be no force push to master.
Should ideally be replaced with a branch restriction on master.
Ref: https://help.github.com/articles/enabling-branch-restrictions/
> Revert "Add Master codeowners"

- RSSDP/SsdpCommunicationsServer.cs
**Changes**
Only print stacktrace on unexpected errors.
**Issues**
Fixes #417
> Avoid printing stacktrace when bind to port 1900 fails

- Emby.Drawing/Common/ImageHeader.cs
- Emby.Server.Implementations/IO/FileRefresher.cs
Some small bugs I found while trying to index some pictures. I have tested both fixes successfully.
The file extension bug has the consequence that jellyfin fails to display photos with non-lowercase extensions (Unsupported image type). With this, uppercase extensions will work too :)
> Fix error with uppercase photo extension and fix typo in a log line

- MediaBrowser.Controller/Entities/Photo.cs
Just came across this function. If the image is flipped it would swap the width and height variables but still divide by the original height. For a flipped image this would lead to `return height / height` so this fixes that. I think it will save us some hunting in the future. But to be honest, I would like to evaluate if we need this aspect ratio magic. I would assume that the frontend would handle aspect ratios
> Fix potential bug where aspect ratio would be incorrectly calculated

- Dockerfile
After installing, remove package caches and clean up after installation of stuff.
> Slim down docker image

- Jellyfin.Server/Program.cs
Whilst testing virgin starts, cleared away log and config folders prior to launch, noticed exception being trapped becuase logging.json file could not be created:
```
ploughpuff@vb-deb-jelly:~/jellyfin$ ~/tmp/bin/jellyfin -configdir ~/tmp/config/ -logdir ~/tmp/log/
[13:31:57] [FTL] Failed to create/read logger configuration
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/ploughpuff/tmp/config/logging.json'.
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at …
```
> Ensure config and log folders exist

- Dockerfile
#606 didn't actually run the new commands due to the comments position.
This fixes the comment location.
> Really slim down Docker container

- Emby.Server.Implementations/Services/SwaggerService.cs
Adds Swagger/OpenAPI version 2.0 documentation.
**Changes**
Adds the SwaggerService from https://github.com/jellyfin/Emby/blob/7aa573d4e0fc231932ad3da4cdf15199cf97709a/Emby.Server.Implementations/Services/SwaggerService.cs
**Issues**
The spec is version 2.0 here so it will be a stop-gap for https://github.com/jellyfin/jellyfin/issues/614.
> Add Swagger documentation

- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
**Changes**
Changed a nullable long to a non-nullable.
Problem was that endTimeTicks was always 0 for (at least) direct streams and then it filtered out any timestamps that were not before the endtime...
**Issues**
Fixes #254
> Fix subtitle converter misinterpreting 0 valued endTimeTicks

- MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
**Changes**
segment_time_delta was being set to a large negative number.
**Issues**
Fixes #555
Fixes #165
> Fix segment_time_delta for ffmpeg 4.1

- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
**Changes**
Changed CanExtractSubtitles to return true.
I don't really understand why it's even there. Is there ever a case when it can't be extracted? Maybe live streams?
This PR is really just to create some discussion
**Issues**
Related to #254 
Related to #172
> Allow subtitle extraction and conversion in direct streaming

- MediaBrowser.Api/Playback/StreamState.cs
Correctly overrides the function.
Closes #660
> Fix NullRef from progress report

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
- MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs
Prerequisite of https://github.com/jellyfin/jellyfin-plugin-reports/pull/1
This adds a cast that should have been there before imho. Compiled fine for me but I'd like someone else to test it as well to feel safe about it.
I opted to fix it here instead of casting it in the plugin because the plugin is the wrong place to do that.
There's also some comments added in the SqliteItemRepository.cs file to help people understand what the particular function actually accomplishes.
Lastly, this probably requires an ABI version bump.
> Return Audio objects from MusicAlbum.Tracks

- MediaBrowser.Api/Playback/MediaInfoService.cs
- MediaBrowser.Api/Playback/UniversalAudioService.cs
Pull #600 got the feedback that it would be better to implement logging than to nuke it. I saw that it would be more than a line or two of change, so that's the background for this PR.
I feel like this could be done better with some DI stuff, but I have no idea how it works, so I hope you'll help me out here and I'll fix this PR to be awesome :p
**Changes**
* remove a TODO in MediaInfoService by implementing logging there
* Add logging capability to MediaInfoService
* Add logging capability to UniversalAudioService since it has to pass it down
ALSO, and this is kinda important.
I didn't test how often it will throw, so if it throws a ton of stack traces then we might want to tone it down to debug and see what we can do to fix it properly.
> Do some logging in MediaInfoService

- MediaBrowser.Controller/Entities/Folder.cs
**Changes**
Fixed a faulty change in logic that occurred during the Christmas GPL nightmare.
I stepped through Emby 3.5.2 and stumbled over a difference in the query between Jellyfin and Emby, where in Emby, query.ParentId was set to the item itself. So I did a little digging in the old GPLv2 source and found this https://github.com/MediaBrowser/Emby/blob/3.4.1.8/MediaBrowser.Controller/Entities/Folder.cs#L720
**Issues**
Fixes #673
> Set Parent to current query Item if ParentId is empty

- MediaBrowser.Controller/Entities/BaseItem.cs
- Mono.Nat/Upnp/Searchers/UpnpSearcher.cs
- SocketHttpListener/HttpBase.cs
- SocketHttpListener/HttpResponse.cs
- SocketHttpListener/Net/HttpConnection.cs
- SocketHttpListener/WebSocket.cs
Trying to remove compilation warnings.
Here are some I'm not experienced enough to fix:
* Some of them are classes with public events that are there because they are required by an interface. They may be used from another class somehow, but the compiler still calls them unused.
* async methods running synchronously, probably because they are stubs. Some of the stubs have TODOs on them, so refactoring them away will just create more work. Other stubs may be worth taking a look at.
* Warning about a call that is not awaited (what does this even mean? Wait for it to complete?), recommends adding await but that might break the whole point of launching a process to the background
* exception ex that is only read in debug compiles
If you can help me remove more of the warnings, I will probably …
> Try to eliminate compile warnings

- Jellyfin.Server/Jellyfin.Server.csproj
- jellyfin.ruleset
Ex: `warning SA1101: Prefix local calls with this`
> Disable some StyleCop warnings

- deployment/common.build.sh
- deployment/fedora-package-x64/clean.sh
- deployment/fedora-package-x64/package.sh
**Changes**
The deployment scripts trims of any trailing `0` in the `${VERSION}` variable which breaks rpm packaging, 
since the build script creates a `jellyfin-10.1.tar.gz` source tarball when `rpmbuild` expects a `jellyfin-10.1.0.tar.gz` tarball.
Added a check that prepends `sudo` for  each `docker` command when the user is not in the `docker` group, since RH distros don't have a `docker` group by default.
Fixed GNU tar source tarball creation which had the wrong format (`.tar.xz` instead of `.tar.gz`) and would always fallback to a two part tarball filtering and re-packing to change the directory name.
> Fix RPM package build for fedora

- Emby.Server.Implementations/HttpServer/FileWriter.cs
- Emby.Server.Implementations/HttpServer/HttpResultFactory.cs
**Changes**
I have removed the unconditional caching and the modified headers. It only uses ETags now. The cache duration should probably also be lowered.
> Remove unconditional caching, modified since header and use ETags

- Emby.Drawing/Emby.Drawing.csproj
- Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
- Jellyfin.Drawing.Skia/PercentPlayedDrawer.cs
- Jellyfin.Drawing.Skia/PlayedIndicatorDrawer.cs
- Jellyfin.Drawing.Skia/SkiaEncoder.cs
- Jellyfin.Drawing.Skia/StripCollageBuilder.cs
- Jellyfin.Drawing.Skia/UnplayedCountIndicator.cs
- Jellyfin.Server/Jellyfin.Server.csproj
- Jellyfin.Server/Program.cs
- MediaBrowser.sln
I don't know why it got moved into `Emby.Drawing` but we lost modularity when doing that.
> Move Skia back into it's own project

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
ffmpeg is very picky about the filters to be used when using VA-API,   because most of them are incompatible. This is particularly evident when   burning-in subtitles.
This commit:   
- adds new video filters to the VA-API ffmpeg command;
- ensures `hwmap` is also last in the line.
Tests done:    
- Played a video file with subtitles
- Played a video file without subtitles
Note that far more testing is required to make sure all corner cases are doing OK.
Fixes issue #642.
This is a rebased branch of my previous PR (#694) on the new master branch. I think I already answered the concerns raised there:
- Options for VA-API are there before ffmpeg 4.0
- They're only applied for x264, other cases aren't even covered.
> [VA-API] Fix filter order

- Emby.Naming/Video/VideoListResolver.cs
**Changes**
Changed the multiversion logic for movies to be a little more sane.
What needs to happen is this though:
1. Scan for changes
2. Parse items
3. Perform metadata lookups
4. Group by provider ids, fall back to name
5. Save
But the code for scanning and performing lookups is super convoluted right now, so this PR is just a temporary bandaid fix.
**Issues**
Fixes #718
> Change multi version logic for movies

- Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs
- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs
- Emby.Server.Implementations/Library/LibraryManager.cs
- Emby.Server.Implementations/Library/UserManager.cs
- Emby.Server.Implementations/ScheduledTasks/ChapterImagesTask.cs
- Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs
* Remove code for pre-installed plugins 
* Check if file exists instead of catching exceptions 
Benchmarks show that catching the exceptions is way slower:
```
Method |      Mean |     Error |    StdDev | Rank |
----------------- |----------:|----------:|----------:|-----:|
FileExists |  5.249 us | 0.0417 us | 0.0390 us |    3 |
FileEx |  4.068 us | 0.0278 us | 0.0260 us |    2 |
FileDoesntExists |  1.193 us | 0.0046 us | 0.0041 us |    1 |
FileDoesntEx | 27.005 us | 0.0668 us | 0.0592 us |    4 |
```
> Remove code for pre-installed plugins & properly check if file exists

- Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs
**Changes**
Made it not crash. It tried to deserialize a file that doesn't exist.
**Issues**
Caused by https://github.com/jellyfin/jellyfin/pull/740
> Fix crash when trying to deserialize a non-existing scheduled task

- MediaBrowser.Controller/Drawing/ImageHelper.cs
- MediaBrowser.Controller/Entities/BaseItem.cs
**Changes**
Changed GetDefaultPrimaryImageAspectRatio back to its original behaviour. It used to be a `double?` though but that didn't work for some reason when serializing it.
**Issues**
Fixes #741
> Fix default aspect ratio

- CONTRIBUTORS.md
- MediaBrowser.Api/StartupWizardService.cs
**Issue**
#187 
**Changes**
Adds a field to the Startup service API allowing the user to set a password for the admin account upon setup.
Note that the functionality won't work without a change to the frontend here: https://github.com/jellyfin/jellyfin-web/pull/92
However, this can be safely pulled without affecting anything, as the password field is not necessary.
> Add password field to initial setup

- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Emby.Server.Implementations/EntryPoints/StartupWizard.cs
- Emby.Server.Implementations/FFMpeg/FFMpegLoader.cs
- Emby.Server.Implementations/IStartupOptions.cs
- Emby.Server.Implementations/StartupOptions.cs
- Jellyfin.Server/CoreAppHost.cs
- Jellyfin.Server/Jellyfin.Server.csproj
- Jellyfin.Server/Program.cs
- Jellyfin.Server/StartupOptions.cs
I've been working on this PR to address my issue #693 
It uses package CommandLineParser:
https://github.com/commandlineparser/commandline
I tested out a few parsers and this one appears to be popular and still actively maintained.  It automatically provides a help and versions page, and moves the our CLI switches to be POSIX standard.
Please review and provide your thoughts.
Example output:
```
ploughpuff@vb-deb-jelly:~/jellyfin$ ~/tmp/bin/jellyfin --help
Jellyfin.Server 10.1.0.0
Copyright ©  2019 Jellyfin Contributors. Code released under the GNU General Public License Version 2
-d, --programdata    Path to use for program data (databases files etc.).
-c, --configdir      Path to use for config data (user policies and puctures).
-l, --logdir         Path to use for writing log files. …
```
> Use CommandLineParser package for handling CLI args

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
After the changes in #749 we did not update docker to use the new args. This addresses that.
> Fix docker exec args

- bump_version
- deployment/centos-package-x64/Dockerfile
- deployment/centos-package-x64/clean.sh
- deployment/centos-package-x64/package.sh
- deployment/centos-package-x64/pkg-src
- deployment/fedora-package-x64/pkg-src/jellyfin.env
- deployment/fedora-package-x64/pkg-src/jellyfin.spec
**Changes**
Added CentOS package, integrated the `cachedir`  option into the `.spec` and cleaned the RPM Dependencies (so that the RPM does not claim to provide libraries which it simply does not provide or demand a version of `libc` which is not available on CentOS)
Also removed the `sed -E 's/.0$//'` from the `bump_version` script like in the `common.build.sh` script to prevent the removal of trailing zeros in the version number.
> Add CentOS and update rpm spec for the cachedir option

- MediaBrowser.Api/ApiEntryPoint.cs
- MediaBrowser.Api/BaseApiService.cs
- MediaBrowser.Api/Playback/BaseStreamingService.cs
- MediaBrowser.Api/Playback/Hls/BaseHlsService.cs
- MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
- MediaBrowser.Api/Playback/Hls/HlsSegmentService.cs
- MediaBrowser.Api/Playback/Hls/VideoHlsService.cs
- MediaBrowser.Api/Playback/Progressive/AudioService.cs
- MediaBrowser.Api/Playback/Progressive/BaseProgressiveStreamingService.cs
- MediaBrowser.Api/Playback/Progressive/VideoService.cs
- MediaBrowser.Api/Playback/TranscodingThrottler.cs
- MediaBrowser.Api/Playback/UniversalAudioService.cs
* Made some proper async
* Drop the use of the IProcess wrapper
* Properly dispose
* Remove unused fields
> Cleanup around the api endpoints

- Jellyfin.Server/SocketSharp/RequestMono.cs
- Jellyfin.Server/SocketSharp/WebSocketSharpRequest.cs
Fixes more warnings from the anayzers.
> Fix more warnings

- deployment/debian-package-x64/pkg-src/bin/restart.sh
- deployment/debian-package-x64/pkg-src/conf/jellyfin-sudoers
- deployment/fedora-package-x64/pkg-src/jellyfin.sudoers
**Changes**
The restart script was broken on Debian, and possibly everywhere, by making some bad assumptions about sudoer permissions (assigned on the group level, rather than user level), as well as trying to run `s6-svc` first, which caused the `restart.sh` script to terminate prematurely on `systemd` at least. This PR fixes both issues for both Debian and Fedora/CentOS, i.e. grant `sudo` to the `jellyfin` user specifically rather than the group, and fix the order of the list of restart commands.
**Issues**
References #408
> Fix restart script in OS packages

- Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs
**Changes**
Allows the CLI and envvar `CacheDir` value to be respected and not overwritten by defaults when the UI/`system.xml` is empty.
**Issues**
N/A
> Fix poor handling of cache directories

- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/Updates/InstallationManager.cs
**Changes**
Adds support for ZIP-archived plugin downloads. Required to have a consistent repository for plugins that have multiple component `.dll` files. Also moves each plugin into its own folder under `datadir/plugins/` to avoid `.dll` clobbering.  Also removes the lazy and ill-conceived GUID-
based checksumming, which just died with ZIP archives.
Most code from @cvium.
Considering this an RC bug in the Plugin implementation slated for 10.2.0 release.
**Issues**
N/A
> Add support for ZIP plugin archives

- Emby.Server.Implementations/AppBase/BaseApplicationPaths.cs
- Emby.Server.Implementations/ServerApplicationPaths.cs
- Jellyfin.Server/Program.cs
**Changes**
Rewrite rules for determining dataDir, configDir and logDir locations.  Generally, arguments from command line take precedence, then JELLYFIN env vars, then APPDATA if Windows, otherwise follow XDG standard.
**Issues**
#698
> Rewrite rules for determining app paths and use XDG_CONFIG_HOME for configDir

- Emby.Server.Implementations/HttpServer/HttpResultFactory.cs
- MediaBrowser.Controller/Net/StaticResultOptions.cs
**Changes**
Dropped ETag in favour of Last-Modified since it's very hard to determine proper file type without major changes. Computing ETags is just not very robust or useful in that case.
**Issues**
Fixes #873 
Supercedes #886
> Drop ETag and use Last-Modified header

- Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs
**Changes**
Emby announced this back in July of 2018 (ref.: [https://emby.media/community/index.php?/topic/56691-m3u-channel-numbers/?p=601373](url)). Implemented this and tested it with a playlist.m3u generated from TVHeadend which is using the "tvg-chno"-Tag.
**Issues**
This fixes #820 in my test environment
> Adding support for "tvg-chno"-Tag in M3U Channel Lists

- .editorconfig
**Changes**
Got the editorconfig naming rules from https://github.com/dotnet/roslyn/blob/master/.editorconfig
> Switch to Roslyn naming rules in EditorConfig

- Jellyfin.Server/Jellyfin.Server.csproj
We don't want to introduce new warnings now that we just got rid of them all.
> Treat warnings as errors for release builds

- deployment/debian-package-x64/pkg-src/control
**Changes**
Adds explicit versioning (<4.1) for ffmpeg in the package specs, and the `jellyfin-ffmpeg` optional dependency to provide ffmpeg instead. This facilitates providing a Jellyfin-specific ffmpeg build into our package repositories that provides a version we can use going forward as distros move to 4.1. The version constraint will be removed once ffmpeg 4.1 support is working, or we move to our own build exclusively.
CC @Wuerfelbecher for verifying compatibility of the RPM config (based on https://serverfault.com/a/761187/188250).
**Issues**
N/A
> Add jellyfin-ffmpeg and versioning to package deps

- Dockerfile.arm
- Dockerfile.arm64
- hooks/pre_build
Replaces #908 
**Changes**
Fixes arm and arm64 builld to allow automated builds on docker.
1.  Adds docker post-build hook to setup qemu for docker hub build.
2.  arm and arm64 is built on x86-64 using net core runtime identifiers and copied to arm container
3.  Automated Builds will need to be setup for arm and arm64 in docker hub after merge.
**Issues**
Fixes #665
> Fix docker arm builds

- Emby.Server.Implementations/Channels/RefreshChannelsScheduledTask.cs
- Emby.Server.Implementations/EntryPoints/UserDataChangeNotifier.cs
- Emby.Server.Implementations/Library/Resolvers/SpecialFolderResolver.cs
- Emby.Server.Implementations/ScheduledTasks/Tasks/ChapterImagesTask.cs
- Emby.Server.Implementations/Sorting/AiredEpisodeOrderComparer.cs
- Emby.Server.Implementations/Sorting/SeriesSortNameComparer.cs
- MediaBrowser.Api/Session/SessionInfoWebSocketListener.cs
- MediaBrowser.Api/System/ActivityLogWebSocketListener.cs
- MediaBrowser.LocalMetadata/Providers/PlaylistXmlProvider.cs
- MediaBrowser.Providers/BoxSets/MovieDbBoxSetImageProvider.cs
- MediaBrowser.Providers/Movies/MovieDbImageProvider.cs
- MediaBrowser.Providers/Music/MusicVideoMetadataService.cs
- MediaBrowser.Providers/Photos/PhotoAlbumMetadataService.cs
- MediaBrowser.Providers/Photos/PhotoMetadataService.cs
- MediaBrowser.Providers/Playlists/PlaylistMetadataService.cs
- MediaBrowser.Providers/TV/Omdb/OmdbEpisodeProvider.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbEpisodeProvider.cs
- MediaBrowser.XbmcMetadata/Parsers/MovieNfoParser.cs
**Changes**
Made a lot of classes to Public.
<del>Changed to DefinedTypes.</del>
So the problem was that a lot of classes weren't public, which means they weren't loaded because `ExportedTypes` only retrieves public types.
I think I fixed all of them, but I still think we should use DefinedTypes just to avoid these kind of issues. We can't have any protected, internal or private classes implementing any of these interfaces in the core without this change. Thoughts?
> Fix assembly visibility

- Emby.Dlna/PlayTo/PlayToManager.cs
**Changes**
On device discovery the current code checks if the session contains the discovered device. If it exists, nothing more is done. However, when a device is first discovered, different methods are called to (1) add the device to the session and (2) set the device's name. 
This race condition can occur:
1. Device is discovered (does not exist in sessions).
2. Device is added/updated (GetOrAdd) with null as name. <-- here it's added for the first time
3. Name is set. <-- only called if device was not already added 
4. Device is discovered (again) (still does not exist in sessions)
5. Device is added/updated (GetOrAdd) with null as name. <-- second time. Now it just updates with null as the name
6. Device added to session.
The code is not that easy to fix so the proposed patch simply …
> DLNA: Fix race condition leading to missing device names

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
Adds the /cache volume and set it to writeable by all. This allows for
those using jellyfin to continue using it without modifying their
config. However, retaining cache will require one to mount the /cache
volume.
Also make the /config and /media dirs 777 by default. No permissions on
mounted volumes will be changed.
> Fix cachedir missing from Docker container

- Emby.Naming/Video/VideoListResolver.cs
**Changes**
Removed the dependency on folder name. Because of the grouping, it should be fine to use the movie name.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/921
> Use the movie name instead of folder name

- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/ConfigurationOptions.cs
- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
- Emby.Server.Implementations/IO/ManagedFileSystem.cs
- Jellyfin.Server/CoreAppHost.cs
- Jellyfin.Server/Program.cs
- MediaBrowser.Api/EnvironmentService.cs
- MediaBrowser.Model/IO/IFileSystem.cs
**Description**
Currently, we create all instances of our registered services manually in ApplicationHost. This is very much an anti pattern for Dependency Injection. The correct way is to create the dependency injection container and register services against it with the specified creation policy (singleton, per instance, per scope etc.). This allows the container to manage the lifetime of the objects that it creates and automatically calls Dispose on services that implement IDisposable.
This commit is just a start to removing the primitives from services that are manually created and registered. We need to do this to eventually get to a point where the container can be responsible for the creation of these services. 
I'm following the guidance from the dot net core developer reference …
> Replace primitive injection with IConfiguration

- .dockerignore
- .drone.yml
- .editorconfig
- .gitignore
**Changes**
Adds a whole bunch of stages to the drone-ci (but only for pull-requests)
> Add dotnet-compat ABI testing and Debug configuration building to drone-CI

- .copr/Makefile
- deployment/fedora-package-x64/create_tarball.sh
- deployment/fedora-package-x64/package.sh
- deployment/fedora-package-x64/pkg-src/jellyfin.spec
This adds enhancements so that Fedora/EL packages can be automatically
built in [COPR](https://copr.fedorainfracloud.org/coprs/) when a webhook is received.  A typical webhook could be
for tagging events for example or even in the future when COPR supports it,
a "Release" webhook to only build releases.
> COPR auto building

- CONTRIBUTORS.md
- MediaBrowser.Api/UserLibrary/ItemsService.cs
When accessing `emby/Users/{UserId}/Items` you are able to access Libraries which you arent supposed to be able to access (ticked off in the AdminUI). There might be/are for sure other Endpoints which just blow out data without proper User-Authorization-Checks.
**Changes**
I added a short User-Access-Validation in GetQueryResult. This leads to Issue #837 being fixed (the View just stays empty). Unsuccessful tries to access a library will be logged as a warning.
(added myself to the Contributors.md, which i forgot last time)
**Issues**
#837
> checking user-permission in GetQueryResult

- Dockerfile
**Changes**
Use https://hub.docker.com/r/jellyfin/ffmpeg of https://github.com/jellyfin/ffmpeg-build
**Issues**
First step to resolving https://github.com/jellyfin/jellyfin/issues/926
> Use jellyfin/ffmpeg image

- Emby.Server.Implementations/LiveTv/EmbyTV/ItemDataProvider.cs
- MediaBrowser.Api/ApiEntryPoint.cs
1) Use function to return path to temp transcode path which has benefit of creating temp folder if not exists, thereby avoiding the exception when GetFilePaths is used.
2) Check json files exists before attempting to read from it.  Avoids having to mask FileNotFound exceptions when debugging.
> Avoid exceptions due to folder and file not found

- deployment/fedora-package-x64/pkg-src/jellyfin.spec
**Changes**
dotnet-runtime is needed for the Fedora build now
> dotnet-runtime is needed on Fedora now

- Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs
**Changes**
Removed some duplicate code and in the process the http response stream should be properly disposed.
I did not test this, but nowhere in the calling code is the response stream closed explicitly, so I'm pretty confident it fixes the issue.
**Issues**
Fixes #965
> Close the response stream after fetching temp files

- .copr/Makefile
- deployment/fedora-package-x64/create_tarball.sh
- deployment/fedora-package-x64/package.sh
- deployment/fedora-package-x64/pkg-src/jellyfin.spec
**Changes**
This adds enhancements so that Fedora/EL packages can be automatically
built in COPR when a webhook is received. A typical webhook could be
for tagging events for example or even in the future when COPR supports it,
a "Release" webhook to only build releases.
**Issues**
Backport of #902
> Release 10.2.z copr autobuild

- MediaBrowser.LocalMetadata/Images/LocalImageProvider.cs
- MediaBrowser.Providers/Manager/MetadataService.cs
**Changes**
Added a check for directory existence. Refreshing 240 people just went from ~30 seconds to 0.
Also removed a weird check that swallows exceptions. Let's avoid them instead of handling them silently, eh?
**Issues**
Related to #951 (but doesn't help the issue that scheduled tasks lock up the server)
> Fix slow local image validation

- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
**Changes**
Set EnableRaisingEvents to true for a few calls that required it.
Context: Without EnableRaisingEvents=true, calls to `WaitForExitAsync(timeoutMs)` will always wait out the timeout because the Exit event is never triggered.
Maybe it should default to true...
> Set EnableRaisingEvents to true for processes that require it

- MediaBrowser.Controller/MediaEncoding/JobLogger.cs
**Changes**
Added a check to make sure the ffmpeg log is writeable.
When the ffmpeg process exits, the stream state is immediately disposed, which also disposes the ffmpeg log. https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Api/Playback/BaseStreamingService.cs#L369
Not sure if it's the proper solution though.
> Check that ffmpeg log target isn't disposed before writing to it

- CONTRIBUTORS.md
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
Ensure ffmpeg flag `+genpts` is set if target codec is `copy`.
**Issues**
Transcoding fails on video streams that lack PTS data. When ffmpeg is copying a video stream which lacks PTS data or for some other reason PTS is not passed along correctly, the ffmpeg decoder is bypassed and PTS data is not ever generated, resulting in a stream that never plays.
Output of ffmpeg in such a case:
```
[NULL @ 0x5bfc8c0] Failed to parse extradata
[segment @ 0x5c20900] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[mpegts @ 0x5c2b140] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[mpegts @ …
```
> Always set ffmpeg flag +genpts when video stream is being copied

- Emby.Dlna/Configuration/DlnaOptions.cs
- Emby.Dlna/Main/DlnaEntryPoint.cs
- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/Networking/NetworkManager.cs
- MediaBrowser.Common/Net/INetworkManager.cs
- MediaBrowser.Model/Configuration/ServerConfiguration.cs
- MediaBrowser.Model/Net/IpAddressInfo.cs
- RSSDP/ISsdpCommunicationsServer.cs
- RSSDP/RSSDP.csproj
- RSSDP/SsdpCommunicationsServer.cs
- RSSDP/SsdpDeviceLocator.cs
- RSSDP/SsdpDevicePublisher.cs
- RSSDP/SsdpRootDevice.cs
I use minidlna and ZerotierOne P2P VPN before, and the DLNA works fine. But after switch to Emby/Jellyfin, the DLNA just not work for ZerotierOne interface, so I followed the code in minidlna to implement it.
**Changes**
1. Add new option `ServerConfiguration.IgnoreVirtualInterfaces` to toggle if ignore virtual interfaces, for the previous code it ignore my ZerotierOne interface because it owns IP but no gateway.
2. Add new option `DlnaOptions.SendOnlyMatchedHost` to toggle if send DLNA devices message to only the matched interface, I think this is the right behavior and the option could be removed if everything works fine.
3. Enable DLNA multiple sockets binding for linux as default, or DLNA not works for ZerotierOne interface.
BTW: I have no Windows environment, so this PR only tested …
> Fix DLNA for multiple interfaces on linux

- deployment/debian-package-x64/pkg-src/conf/jellyfin
- deployment/debian-package-x64/pkg-src/control
**Changes**
Doing this the other way was just complex and prone to failures with various usecases involving other `ffmpeg`s. No longer try to override the system ffmpeg, just put ours somewhere else and depend on that package entirely for all Debian/Ubuntu releases.
Requires a rebuild of the `jellyfin-ffmpeg` package which is forthcoming.
**Issues**
Fixes #974
> Fix the ffmpeg compatibility

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
Will always ensure containers use correct path.
Resolves https://github.com/jellyfin/jellyfin/issues/478
> Set ffmpeg+ffprobe paths in Docker container

- CONTRIBUTORS.md
- MediaBrowser.Api/Playback/Progressive/VideoService.cs
Or will report "Could not find handler for /videos/xxx/stream.rm" error
in server side.
Test OK with Kodi and gupnp-tools.
> Fix rmvb video can not play under DLNA

- MediaBrowser.Model/Users/UserPolicy.cs
**Changes**
Modify class `UserPolicy` to have property `EnableContentDeletion` set to `false` by default. This affects any newly created users; the initial user created from setup still has the delete option enabled by default (see [`Emby.Server.Implementations/Library/UserManager.cs:514`](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Library/UserManager.cs#L514)).
**Issues**
Fixes #989 and partially addresses #79.
> Do not allow new users to delete content by default

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
**Changes**
Have Dockerfiles download a pinned version of jellyfin-web. This keeps the Dockerfile self-contained thus negating any additional scripts to be run before `docker build`. 
Also avoids version issues encountered with submodules.
> Treat jellyfin-web as just another dependency for Docker builds

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
**Changes**
This PR fixes series type list values that PR #848 accidentally changed.
**Issues**
Incorrect fields were being returned for series, resulting in Jellyfin for Kodi addon not being able to fetch new series (i.e. TV Shows). More information on this can be found in the comments of PR #848.
> Correct the list of series types

- Jellyfin.Drawing.Skia/PercentPlayedDrawer.cs
- Jellyfin.Drawing.Skia/PlayedIndicatorDrawer.cs
- Jellyfin.Drawing.Skia/UnplayedCountIndicator.cs
**Changes**
Replaces instances where "Emby green" was still being used for drawing progress bars and other overlays on images with "Jellyfin blue".
**Issues**
> Update image overlays to use Jellyfin blue

- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
Current implementation looks for year string in the 'ffmpeg -version' output.  This is far from ideal as the search could use either copyright or build date.  We we really want to know if the FFmpeg version, like "4.0" or "4.1" in order to warn user if the version is lacking..
This PR uses two routes for determining FFmpeg version:
1. Search for string 'ffmpeg version x.y' in '-version' output.  This is the best route and quickest.  Should work for all pre-built binaries.  Should work for 99% of people..
1. Try and match the library versions contained with known versions in FFmpeg.  Requires lookup table in our code than needs to me maintained along with FFmpeg releases.  This should catch majority of remaining FFmpeg versions.
Improved logging to inform user about recommended ffmpeg …
> Implement proper FFmpeg version checking

- build
- build.yaml
- deployment/win-x64/package.sh
- deployment/win-x86/package.sh
**Changes**
Makes some minor modifications to better support the wrapping `jellyfin-build` infrastructure. Specifically:
1. Put the output in `../bin` rather than `../jellyfin-build`, which is more generic, cleaner, and easier to grab from.
1. Allow `-b local` to avoid touching the submodule at all. In my usecase, I replace the submodule with a symlink to the `jellyfin-web` repo. This is temporary until we can entirely remove the submodule somehow (either separate packaging for `jellyfin-web`, or something else).
1. Add a `build.yaml` configuration listing the available package types. `build` within the repo doesn't use this (yet).
**Issues**
N/A
> Build improvements for wrapping infrastructure

- .ci/azure-pipelines.yml
**Changes**
Changed DownloadGitHubReleases to DownloadGitHubRelease as it's renamed by Microsoft/azure-pipelines-tasks#9481
> Update to renamed DownloadGitHubRelease task (Microsoft/azure-pipelines-tasks#9481)

- Jellyfin.Drawing.Skia/StripCollageBuilder.cs
At some point it might be better to cycle through several images with a fade animation but at least the gradient will be gone.
> Remove mirror images from library thumbnail

- Jellyfin.Server/Program.cs
- deployment/debian-package-x64/pkg-src/conf/jellyfin
- deployment/debian-package-x64/pkg-src/jellyfin.service
- deployment/fedora-package-x64/pkg-src/jellyfin.env
- deployment/fedora-package-x64/pkg-src/jellyfin.service
**Changes**
We (read: I) were configuring the paths in the packages in a very convoluted way. Simplify this to use use the envvars for configuration. Also fixes two small bugs related to this:
1. The name of the datadir envvar was PATH rather than DIR; updated it to match the others.
1. The dataDir creation was happening outside the try block of the others; move it in there.
**Issues**
N/A
> Use better path configuration for packages

- Emby.Drawing/ImageProcessor.cs
**Changes**
Added an early exit. It would generate a lot of errors if an image didn't exist (try removing the metadata folder...)
> Skip processing of images that don't exist

- Emby.Server.Implementations/AppBase/BaseApplicationPaths.cs
- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/ServerApplicationPaths.cs
- Jellyfin.Server/Program.cs
- Jellyfin.Server/StartupOptions.cs
- MediaBrowser.Common/Configuration/IApplicationPaths.cs
- MediaBrowser.Model/System/SystemInfo.cs
- MediaBrowser.WebDashboard/Api/DashboardService.cs
**Changes**
Another step towards a total separation of Jellyfin and Jellyfin Web. Allows the configuration of the WebPath variable via a CLI flag or environment variable (similar to the other configurable paths). Defaults to the same location that was originally hardcoded. Will allow the Jellyfin Web repository to be packaged separately on some systems (e.g. Debian) and the server pointed to the right place.
**Issues**
N/A
> Add configurable webdir option

- Emby.Server.Implementations/ApplicationHost.cs
- MediaBrowser.Common/IApplicationHost.cs
- MediaBrowser.Providers/Music/MusicBrainzAlbumProvider.cs
- MediaBrowser.Providers/Music/MusicBrainzArtistProvider.cs
When requesting data from MusicBrainz, only delay the request if previous request was less than rate limit ago, instead of always delaying for one second at start.  In addition, removed redundant input params to function GetMusicBrainzResponse() named isSearch and forceMusicBrainzProper.
**Performance evidence**
During testing, this change indicated a 25-40% reduction in time take to complete music scan.  Two test runs were made, as follows:
1) 59 albums, 703 songs.
Original code: 3 minute(s) and 3 seconds:
[run1_old.txt](https://github.com/jellyfin/jellyfin/files/2963624/run1_old.txt)
With this PR: 1 minute(s) and 48 seconds:
[run1_new.txt](https://github.com/jellyfin/jellyfin/files/2963627/run1_new.txt)
2) 141 albums, 2790 songs.
Original code: 17 minute(s) and 32 seconds: …
> Only delay making MusicBrainz request if necessary

- Dockerfile
**Changes**
Only remove files in /var/lib/apt/lists/* suggested by Docker best practices.
In the current form we can't update or install any packages.
````
Reading package lists... Error!
root@e38e07db2279:/# apt update
.......
E: flAbsPath on /var/lib/dpkg/status failed - realpath (2: No such file or directory)
E: Could not open file  - open (2: No such file or directory)
E: Problem opening
E: The package lists or status file could not be parsed or opened.
````
````
root@e38e07db2279:/# apt install nano
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (2: No such file or directory)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
````
> Only remove /var/lib/apt/lists/* in Dockerfile

- Emby.Server.Implementations/Library/UserManager.cs
**Changes**
The username regex was hard to parse because of the double \\ and the unescaped -
Even though it worked this minor fix makes it clearer what it is doing
> Update username regex to string literal with escaped -

- .github/ISSUE_TEMPLATE/bug_report.md
**Changes**
Inspired by https://github.com/jellyfin/jellyfin/issues/1085#issuecomment-473833591
It seems that the issue with "setup wizard" described there is only prominent when reverse-proxied, not when accessed directly. So this type of information should be gathered in the bug report as well.
Thus I'm adding another field to the bug report template to gather such information.
> Require access type to be included in bug report

- deployment/debian-package-x64/pkg-src/jellyfin.init
**Changes**
Changed the script for /etc/init.d/jellyfin to use `start-stop-daemon` instead of the old mechanism using `nohup` and `su`. This makes it work on Debian and Devuan and mimics the behaviour of other init scripts
**Issues**
Fixes #1131
> Update init scripts for compatibility with Devuan

- Emby.Server.Implementations/HttpServer/HttpResultFactory.cs
**Changes**
Changes the default value of the `Expires` HTTP header to be `"0"` instead of `"-1"`. The [RFC](https://tools.ietf.org/html/rfc7234#section-5.3) specifically mentions using `"0"` to represent values that have already expired.
The Java apiclient uses Gson for serializing the response and it logs warnings for the use of `"-1"`.
**Issues**
N/A
> Fix default value for Expires header

- Emby.Server.Implementations/ApplicationHost.cs
See [this comment](https://github.com/jellyfin/jellyfin/issues/601#issuecomment-475941080)
**Changes**
Adds switch for https ports for local configuration depending on whether https is used.
Uses public ports for WAN address instead of local ports. Also switches to https if enabled. 
If configuration has a DNS WAN name, use this name instead: This might break clients such as jellyfin for kodi and/or the android app. The clients need to change accordingly. 
**Issues**
https://github.com/jellyfin/jellyfin/issues/1152
> WAN Address should use public ports instead of local ports. Advertise DNS WAN if available

- deployment/debian-package-x64/pkg-src/conf/jellyfin
Update the location of the jellyfin-ffmpeg binaries as changed in commit d6bb1f3c in jellyfin-ffmpeg. The binaries are now located in `/usr/lib` instead of `/usr/share` to better comply with the specification for these directories.
References https://github.com/jellyfin/jellyfin-ffmpeg/issues/2
> Use new libexecdir location for jellyfin-ffmpeg

- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/Library/DefaultPasswordResetProvider.cs
- Emby.Server.Implementations/Library/UserManager.cs
- MediaBrowser.Api/Session/SessionsService.cs
- MediaBrowser.Controller/Authentication/IPasswordResetProvider.cs
- MediaBrowser.Controller/Library/IUserManager.cs
- MediaBrowser.Model/Users/UserPolicy.cs
**Changes**
Creates an Interface for password reset providers to implement that is configurable per user.
Creates a default provider for that interface that allows a user to reset their password by creating a JSON file in the filesystem, and extracting a pin which will then become their password. There is a halfhour timeout on this to hopefully discourage problems.
Password resets no longer require the name of an admin user
Password resets are no longer local network restricted
**Issues**
Fixes: #1086 #1076 #1057 #423 
Possibly resolves: #187  - this should be resolved in 10.3 with this last pr IMO.
> Adds per user password reset

- bump_version
- deployment/common.build.sh
**Changes**
1. Remove the auto-changelogs in `bump_version` and simplify it a bit, including updating `build.yaml` too. Instead of full changelogs in the packages, link to the release page instead, making them reasonably short and consistent even through the RC cycle.
2. Modify `common.build.sh` to get the version string out of `build.yaml` (where we can have suffixes like `-rcX`) rather than `SharedVersion.cs` (where we cannot). The net result is properly-versioned outputs for the non-package builds that save doing a rename later. Seems to have no adverse effects from my testing.
**Issues**
N/A
> Minor improvements to release build setup

- deployment/windows/build-jellyfin.ps1
Fixed -InstallNSSM command line option
**Changes**
The NSSM website now requires a newer version of TLS to download its files.  TLS 1.2 is now used. I also added the displaying of the variables passed to the dotnet command line.
> Use TLS 1.2 to download NSSM

- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/Updates/InstallationManager.cs
Fixes several breaking bugs around the installation, loading, and management of plugins.
1. Restore previous functionality to load plugins from subfolders of the PluginDir, which was potentially broken in #801 (or previously, not sure).
1. Use a directory name based only on the `Name` of the plugin, not the source filename, which contains the version and would be really confusing.
1. Use the new directory name for the deletes if it's present, so that installation and removal happen at that directory level and we don't leave empty folders laying around. Ensures we properly remove additional resources in plugins too, not just the main `.dll` file.
1. Ignore the incoming `target` when installing, and always set it ourself to the proper directory, which would matter when upgrading since the …
> Fix problems with plugin installation

- deployment/unraid/docker-templates/jellyfin.xml
Logo was set to use emby, but binhex has since added the jellyfin logo.
> Update Unraid Docker icon

- .ci/azure-pipelines.yml
**Changes**
Disables dotnet_compat portion of Azure Pipelines CI, until #1111 can be resolved.
> Disable dotnet_compat part of pipeline

- README.md
This PR fixes a dead documentation link in the README.
> Fix README documentation link

- Emby.Server.Implementations/SocketSharp/WebSocketSharpRequest.cs
Hi, new dev here. I chose #1047 to start contributing because of the "good first issue" flag.
Issue was requesting a replacement of ad hoc URL parsing code in `WebSocketSharpRequest.PathInfo` by standard .NET Core methods.
This ad hoc parsing was dependent on a never-initialized (thus always `null`) member `HandlerFactoryPath` and doing nothing when it's null. That led to important simplification of the code.
**Changes**
- Removed ` ResolvePathInfoFromMappedPath(string fullPath, string mappedPathRoot)` method because it is doing nothing (in a inefficient manner) when  `mappedPathRoot` is `null` and it always is.
- Removed `NormalizePathInfo` for the same reason
- Replaced usage of `RawUrl`, which is not a good fit because it contains the query part (`?..=..`) which is ignored, by …
> Clean `WebSocketSharpRequest.PathInfo`

- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/Udp/UdpServer.cs
- MediaBrowser.Model/System/PublicSystemInfo.cs
- MediaBrowser.Model/System/SystemInfo.cs
**Changes**
In `UdpServer.cs`, remove the other UDP responders (embyserver, MediaBrowser_v2), and only keeps Jellyfin.
In `ApplicationHost.cs`, moves the ProductBame entry from the “.../system/info” endpoint to the “…/system/info/public” one instead.
**Issues**
Start of the work for #1222.
> Clean up UDP responders, and move ProductName to Public endpoint

- build
The `./build` help message mentions that the output folder is `../jellyfin-build/<platform>` but the script outputs the archive to `../bin/<platform>`. This PR update the message to mention `../bin/<platform>`. I actually think `../jellyfin-build/<platform>` is better, but I didn't want to disturb your build processes by changing the actual output folder.
Kinda related to https://github.com/jellyfin/jellyfin-docs/pull/66
> Fix help message to indicate the right output folder

- deployment/unraid/docker-templates/jellyfin.xml
Forgive me if i should not have done these in a single pull request, or possibly needed a different title.
- Cache folder was not mounted outside of the Docker image since its separation from the config folder.
Current installations may have an issue with their docker image (VM) filling up as this change will not affect current installations. Unraid defaults to a 20GB docker image & there are reports of the cache folder in emby occasionally bloating to many, many GB in size! (14GB-140GB in one particular case!)
- Config HostDir was updated for consistency, directory is overridden by unraid into the user/appdata/appname folder anyway.
- Name capitalization was corrected as this is only used by new installations & does not affect current installations/updates/re-installs unless the template …
> Fix missing Unraid cache mount and name capitalization

- Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
- MediaBrowser.Api/UserService.cs
- MediaBrowser.Common/Extensions/ResourceNotFoundException.cs
**Changes**
Add a `MethodNotAllowedException` to the HTTP handler. Checks the `/Users/AuthenticateByName` API call to see if a plaintext password has been provided; if not, return the `MethodNotAllowedException` to the client.
**Issues**
Addresses #1222
> Hotfix authapi

- Emby.Server.Implementations/Services/ServiceHandler.cs
**Changes**
Reverted behavior of ServiceHandler.CreateContentTypeRequest to return Task.FromResult(host.CreateInstance(requestType) when deserializer is null. 
Previous change prevented calling Invoke on a null deserializer, but would return null to the caller.
**Issues**
Resolves #1270
> Prevent null reference when request content type is x-www-form-urlencoded

- Emby.Server.Implementations/Services/StringMapTypeDeserializer.cs
Resolves a null reference when Pw is an empty string and the request content type is not json
**Changes**
Removes an isnullorempty check for a string and changes it to only check for null in order to prevent coalescing an empty string to a null object. 
In particular, the Pw parameter carries different connotations when null or empty and when both Pw and password are null, the auth fails with a null reference.
**Issues**
Resolves #1299
> Fix passwordless authentication with non-json content-types

- deployment/debian-package-x64/pkg-src/control
**Changes**
Add an option for libssl1.1 dependency to support Ubuntu Disco (19.04).
**Issues**
Closes #1300
> Support libssl1.1 for Ubuntu Disco

- Emby.Server.Implementations/Library/UserManager.cs
**Changes**
A cleanup inverted the check for hasConfiguredEasyPassword, this resolves that problem.
(see https://github.com/jellyfin/jellyfin/commit/bef665be364ce1477d09ed268f68c19e0099922f#diff-0cad5db83844b175e1fe7dd334e0e705 )
**Issues**
Resolves (part of?) #1329
> Fix incorrect hasPassword flag when easy pin set

- MediaBrowser.Api/Playback/Progressive/BaseProgressiveStreamingService.cs
**Changes**
Alternative solution to ignoring the unreachable code warnings, this simply removes the un-used code.
See #1309
> Remove unreachable code from BaseProgressiveStreamingService

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
> Fix query time logging

- deployment/centos-package-x64/docker-build.sh
- deployment/centos-package-x64/package.sh
- deployment/debian-package-arm64/docker-build.sh
- deployment/debian-package-arm64/package.sh
- deployment/debian-package-armhf/docker-build.sh
- deployment/debian-package-armhf/package.sh
- deployment/debian-package-x64/docker-build.sh
- deployment/debian-package-x64/package.sh
- deployment/fedora-package-x64/docker-build.sh
- deployment/fedora-package-x64/package.sh
- deployment/ubuntu-package-arm64/docker-build.sh
- deployment/ubuntu-package-arm64/package.sh
- deployment/ubuntu-package-armhf/docker-build.sh
- deployment/ubuntu-package-armhf/package.sh
- deployment/ubuntu-package-x64/docker-build.sh
- deployment/ubuntu-package-x64/package.sh
I found the sudo prompt for moving the files into the final location annoying.
> Move artifact chown inside docker to avoid sudo

- MediaBrowser.Controller/Entities/BaseItem.cs
Fixes #1278 
**Caveat**: This change only fixes _newly added_ media
> Enforce a specific folder structure for Extras to avoid misidentification

- Emby.Dlna/Didl/DidlBuilder.cs
**Changes**
This moves the thumbnail (JPG_TN) image element to be provided after the larger elements. Without this change, many DLNA clients will display the thumbnail when trying to view the image.
**Issues**
Fixes #1174
> Improve Photo rendering in DLNA

- Emby.Server.Implementations/IO/ManagedFileSystem.cs
The directory picker in web defaults to this endpoint when no folder is specified but a lot of useless drives were getting returned on my system. I trimmed down the list of valid drives with some filters, don't think it will cause any issues.
> Only return useful drives

- CONTRIBUTORS.md
- MediaBrowser.Api/UserLibrary/ItemsService.cs
**Changes**
This removes user access checking introduced by #930 for `UserRootFolder`.
These folders are all the generated virtual folders that exist outside of libraries (i.e. Actors, Artists, Genres, ...).
It doesn't make sense to check if a user has access to the library in which they exist (`Media Folders`) since it is not even a real library.
**Issues**
Fixes #1436
> Fix issue #1436: media folders appear empty unless user has all libraries access

- Emby.Server.Implementations/Library/InvalidAuthProvider.cs
- Emby.Server.Implementations/Library/UserManager.cs
**Changes**
Implements the InvalidAuthProvider, which acts as a fallback if a
configured authentication provider, e.g. LDAP, is unavailable due
to a load failure or removal. Until the user or the authentication
plugin is corrected, this will cause users with the missing provider
to be locked out, while throwing errors in the logs about the issue.
Thanks to @LogicalPhallacy for the majority of the code.
**Issues**
Fixes #1445 part 2
> Implement InvalidAuthProvider

- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
I am not an expert in this section of code, but I cannot think of a need to do path substitution during
subtitle encoding. The path gets passed to the ffmpeg command.
Fixes jellyfin/jellyfin#1446
> Stop path substitution in SubtitleEncoder - Fix #1446

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
**Enable Exynos MFC encoder and fix transcoding bitrate control**
***Changes:***
- Rebased against master per request.
- The Exynos MFC HW encoder is now enabled when selected in the pulldown menu at the "Transcoding" tab.
- Now Jellyfin selects a bitrate according to the original file, while before it was always fixed to a very high value of 139808000.
> Enable Exynos MFC encoder and fix transcoding bitrate control

- MediaBrowser.Controller/Entities/User.cs
**Changes**
Use the username to construct the UserConfigurationDirectory,
instead of the user ID, and move the old ID-based path to the new 
path if needed when loading (temporary transitional code). Removes
administrator guesswork as to what user each directory belongs to, 
which I found very annoying when investigating user configs.   
This might not be the "best" or "proper" place for this migration, but
it seems simplest to just move it when looking up the dir. Remove this
migration in a future release.
**Issues**
N/A
> Use the username for the user config path

- CONTRIBUTORS.md
- Jellyfin.Drawing.Skia/SkiaEncoder.cs
**Changes**
According to https://github.com/jellyfin/jellyfin/issues/1298, skia was segfaulting the server when trying to reach an image that didn't exist. This should prevent that problem.
**Issues**
It might close https://github.com/jellyfin/jellyfin/issues/1298 but I'm unsure since I wasn't able to reproduce.
@cvium 	you might be able to test it to see if it fixed your issue.
> Fix skia segfault

- CONTRIBUTORS.md
- MediaBrowser.Api/UserLibrary/ItemsService.cs
**Changes**
In GetQueryResult:
`user.Policy.EnabledFolders.Any(i => new Guid(i) == item.Id)`
returns only true if the item is the media folder.
So now it checks if an item is a child of a EnabledFolder.
Fixes issue #1347 
Introduced in #930
Feel free to criticise everything you want, i am open for improvements :)
> Check if an item is a child of an EnabledFolder

- deployment/debian-package-x64/pkg-src/bin/restart.sh
- deployment/fedora-package-x64/pkg-src/restart.sh
**Changes**
The old restart script was buggy, as reported in #1320. This updated
script seems to work far more reliably and conforms to the existing
jellyfin-sudoers packages sudo configuration.
**Issues**
Fixes #1320
> Add nicer restart script

- Emby.Server.Implementations/Library/CoreResolutionIgnoreRule.cs
- Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
**Changes**
This changes the string comparison (with a list of potential boundary characters) into a regular expression search for "sample" surrounded by any regex-recognized boundaries. This allows ignorance of files with e.g. (Sample), [sample] or `~sample~`.
> Adjust detection of 'sample' in filenames to use regex boundaries

- Emby.Server.Implementations/Data/BaseSqliteRepository.cs
**Changes**
Each database will be vacuumed when Jellyfin is started. Right now databases aren't fully vacuumed, which leads to fragmentation and potentially bigger query times. The database is also taking useless space after removing bigger libraries
**Issues**
I'm not sure if the implementation is the best one. Perhaps it should be inside a try/catch block instead? I can think (for example) that vacuuming needs extra space to accomodate the database while it's being vacuumed, among other exceptions that vacuuming can raise (and setting PRAGMA variables doesn't).
I think that the best implementation of this should also include an Scheduled Tasks to do it, so the user is aware that the database is being optimised automatically, as well as triggering the process on demand. However, I think …
> Vacuum databases at startup

- Emby.Dlna/PlayTo/SsdpHttpClient.cs
- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs
- Emby.Server.Implementations/LiveTv/EmbyTV/DirectRecorder.cs
- Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
- Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs
- Jellyfin.Server/Program.cs
- MediaBrowser.Common/Net/HttpRequestOptions.cs
- MediaBrowser.Common/Net/HttpResponseInfo.cs
Fixes a crash when using the `Post` method with content that isn't a `byte` array.
Replaces #1460
> Fix issues with HttpClientManager

- .ci/azure-pipelines.yml
To avoid this error: 
```
The pipeline is not valid. Job Job: Step DownloadGitHubRelease input connection expects a service connection of type github with authentication scheme OAuth,PersonalAccessToken but the provided service connection jellyfin is of type GitHub using authentication scheme InstallationToken.
```
> Update the GitHub token to a Grant Auth token

- deployment/centos-package-x64/pkg-src
- deployment/debian-package-armhf/pkg-src
- deployment/ubuntu-package-x64/pkg-src
**Changes**
These were removed somehow in defc5f1cf9b486357b379c610663e1bad48428ad;
restore them to their proper link state.
**Issues**
N/A
> Fix broken symlinks in deployment

- deployment/debian-package-x64/pkg-src/rules
**Changes**
Without this, when building the `jellyfin-nightly` package, it attempts
to find service/init files with the name `jellyfin-nightly` instead of
the proper name. This override prevents this by forcing the name to
`jellyfin`. Required for nightly builds.
**Issues**
N/A
> Override the Debian installinit name

- Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs
This is the same fix as #1551, but it simply restores the old HttpWebRequest behaviour. It might be more suitable for 10.3.7.
- Fixes #1520 
- `HttpWebRequest.BeginGetResponse` (old implementation) returns immediately after headers have been received. 
- Non-buffered content needs the unmodified stream to function properly (eg. Live TV).
- HttpClient always buffers by default, but can be disabled with `HttpCompletionOption.ResponseHeadersRead`.
- This PR makes HttpClient behave the same way as the previous HttpWebRequest implementation by allowing the response to be "completed" after the headers have been received.
> Disable buffering in HttpClient as it causes big requests to timeout

- CONTRIBUTORS.md
- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
**Changes**
* Disabled `-sub_charenc` flag for `*.smi` and `*.sami` subtitles when it is determined as UTF-16.
If we specify character encoding to sami subtitles, FFmpeg rejects it with "do not specify a character encoding" and "Unable to recode subtitle event" error.
It is because ffmpeg converts UTF-16 into UTF-8 in `ff_text_r8`. `ff_text_r8` is called from `ff_text_read` and `samidec.c` uses `ff_text_read`.
When I tested with UTF-16LE, UTF-16BE, CP949, UTF-8 the FFmpeg automatically did the conversion without the `-sub_charenc` flag.
**Issues**
Fixes #1539
> Fixed SMI Encoding Bug

- .github/stale.yml
**Changes**
Adds a config file for the Stale App, to help keep the issues list fresh, I think 60 days is fair as a starting point. I added most tags I think should be exempt.
Link: https://github.com/apps/stale
EDIT Message proposal:
```
Issues go stale after 60d of inactivity.
Mark the issue as fresh by adding a comment or commit.
Stale issues close after an additional 7d of inactivity.
If this issue is safe to close now please do so.
If you have any questions you can reach us on [Matrix or Social Media](https://jellyfin.readthedocs.io/en/latest/getting-help/).
```
> Add Stale app configuration starting point

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
This allows for building against jellyfin-web master. Ex.
```
docker build . --no-cache --build-arg JELLYFIN_WEB_VERSION=master
```
**Changes**
Update the `JELLYFIN_WEB_VERSION` build argument to be the full part in the GitHub repository archive URL (`https://github.com/jellyfin/jellyfin-web/archive/${JELLYFIN_WEB_VERSION}.tar.gz`)
> Docker - make web version more configurable

- .github/stale.yml
**Changes**
Updates the Stale bot to mark an issue after 90 days, and allows 14 days before closing the issue.
> Update the Stale-bot config

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
**Changes**
While https://github.com/jellyfin/jellyfin/pull/1593 made the build work with a version of `master`, it broke a tag-specific version. The extracted directory will *not* always match the version argument.
> Fix Docker build

- Emby.Server.Implementations/Networking/NetworkManager.cs
Previously it only ignore IPv4 link-local addresses.
> Ignore Ipv6 link-local addresses

- MediaBrowser.Providers/TV/TheTVDB/TvDbClientManager.cs
This PR fixes #1477 for both DVD and absolute ordering.
Episode indexnumber, parentIndexNumber, and providerIDs should be cleared on Series display order change. Otherwise, metadata will still be pulled using tvdbid already saved for episodes. Work around is to change series display order, remove episodes from JF, scan, re-add episodes to JF. Metadata is correct.
It does break TMDB metadata and image pulling when not using air date, because that service only uses air date order for the default query. TMDB supports episode groups, but I have not noticed a way to query by that yet.
> Update TVDB provider to search based on series display order

- Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteTranscodingTempTask.cs
**Changes**
Adds a scheduled task that will delete files older than 24h in the transcoding-temp folder. The task is disabled by default, but can be enabled to run on any of the possible triggers.
(This is pretty much a straight copy of the delete cache task, just modified for the transcoding-temp folder.)
**Issues**
Partial fix for #1277.
> Add a task to clean up transcode cache

- Emby.Server.Implementations/Data/BaseSqliteRepository.cs
- Jellyfin.Server/Jellyfin.Server.csproj
Can't upgrade to SQLitePCLRaw.bundle_e_sqlite3 v2 until we release a
compatible SQLitePCLRaw.provider.sqlite3.netstandard11
PR: https://github.com/jellyfin/SQLitePCL.pretty.netstandard/pull/5
> Fix instant crash.

- BDInfo/BDInfo.csproj
- DvdLib/DvdLib.csproj
- Emby.Dlna/Emby.Dlna.csproj
- Emby.Drawing/Emby.Drawing.csproj
- Emby.Drawing/ImageProcessor.cs
- Emby.Drawing/NullImageEncoder.cs
- Emby.IsoMounting/IsoMounter/IsoMounter.csproj
- Emby.Notifications/Emby.Notifications.csproj
- Emby.Photos/Emby.Photos.csproj
- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/Dto/DtoService.cs
- Emby.XmlTv/Emby.XmlTv/Emby.XmlTv.csproj
- Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
- MediaBrowser.Api/Images/ImageService.cs
- MediaBrowser.Api/MediaBrowser.Api.csproj
- MediaBrowser.Common/IApplicationHost.cs
- MediaBrowser.Common/MediaBrowser.Common.csproj
- MediaBrowser.Controller/Drawing/IImageEncoder.cs
- MediaBrowser.Controller/Drawing/IImageProcessor.cs
- MediaBrowser.Controller/Drawing/ImageProcessingOptions.cs
- MediaBrowser.Controller/MediaBrowser.Controller.csproj
- MediaBrowser.LocalMetadata/MediaBrowser.LocalMetadata.csproj
- MediaBrowser.MediaEncoding/MediaBrowser.MediaEncoding.csproj
- MediaBrowser.Model/MediaBrowser.Model.csproj
- MediaBrowser.Providers/MediaBrowser.Providers.csproj
- MediaBrowser.WebDashboard/MediaBrowser.WebDashboard.csproj
- MediaBrowser.XbmcMetadata/MediaBrowser.XbmcMetadata.csproj
Forces all new public/internal members to be documented.
Enables TreatWarningsAsErrors for Emby.Drawing.
Generate doc files for all projects.
> Document all public/internal members of Emby.Drawing

- Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
- MediaBrowser.Model/Configuration/ServerConfiguration.cs
I have the work done for android, apiclient-java, and web but Android TV and Kodi might need some UI changes. The easiest way to not break any setups would be to update all the clients to drop the `emby` prefix on API requests. The server always accepts connections with no base URL so any existing setups should work fine.
> Add base url option to server configuration

- MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeImageProvider.cs
- MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs
**Changes**
Apparently, EpisodeInfo.ProviderIds == EpisodeInfo.SeriesProviderIds because who doesn't love duplicated data...
Credit goes to @marius-luca-87
**Issues**
Fixes #1467
> Always fetch episode id as EpisodeInfo does not contain it

- MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs
**Changes**
I'm not sure if it's TvdbSharper or the v2 api, but guest stars don't follow the pipe delimited format that the rest of the "persons" objects do.
**Issues**
Fixes #1586
> Fix tvdb guest stars with multiple roles

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
**Changes**
Call ToString() instead of ToBlob() and deserialize the string. Most queries are basically instant (as verified in SQLiteBrowser), but deserializing them to POCO is what made requests so slow.
> Speed up BaseItem deserialization

- MediaBrowser.Api/Playback/BaseStreamingService.cs
This fixes minor a issue were the second argument passed to substring was the end position instead of the length.
`
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
at System.String.Substring(Int32 startIndex, Int32 length)
at MediaBrowser.Api.Playback.BaseStreamingService.ParseTimeSeekHeader(String value) in d:\OpenSource\jellyfin\MediaBrowser.Api\Playback\BaseStreamingService.cs:line 637
at MediaBrowser.Api.Playback.BaseStreamingService.ParseDlnaHeaders(StreamRequest request) in d:\OpenSource\jellyfin\MediaBrowser.Api\Playback\BaseStreamingService.cs:line 611
at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken) in …
> Fix ArgumentOutOfRangeException in ParseTimeSeekHeader 

- Emby.Dlna/Didl/DidlBuilder.cs
During DLNA video playback on a Samsung Q6FN any usage of the pause+play/seek functions will restart the video.
The issue with the restart happens in both Transcoding and DirectPlay.
By providing streamInfo.StartPositionTicks to the AddSamsungBookmarkInfo function we fix the DirectPlay scenario but the Transcoded videos will continue to manifest the same issue.
As I do not have other Samsung devices these changes should be further tested.
> Fix q6fn dlna seek for direct play

- MediaBrowser.Model/Net/MimeTypes.cs
**Changes**
Restores the flac mime type to fix flac playback in Safari on macOS and iOS.
**Issues**
N/A
> Restore flac mime type

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Enable VAAPI command arguments to ffmpeg if VAAPI is selected
regardless of hardware encoding being enabled. To support hardware
decoding with software encoding, add the "hwdownload" filter.
Also support transforming 10 bit colourspace to 8-bit in hardware to
software transcoding, consistent with other hardware encoding 
behaviours, until client pixel formats are configurable.
Fixes #1675
> Enable VAAPI decoding without hardware encoding

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
- SharedVersion.cs
- build.yaml
- bump_version
- deployment/debian-package-x64/pkg-src/changelog
- deployment/fedora-package-x64/pkg-src/jellyfin.spec
**Changes**
Bump the version to 10.4.0 in prep for release, so that nightly builds have the correct version and we can begin updating plugins that don't work.
Also includes a bump of the jellyfin-web repo as of today, which is still not quite there, but this can be updated again closer to release (ideally at the time of the release branch creations). Nightly builds just check out the latest master branch anyways automatically.
Finally, includes a few fixes to the bump_version script to handle the above jellyfin-web branch config as well as the Docker versions.
**Issues**
N/A
> Bump version to 10.4.0

- deployment/debian-package-arm64/Dockerfile.amd64
- deployment/debian-package-arm64/Dockerfile.arm64
- deployment/debian-package-armhf/Dockerfile.amd64
- deployment/debian-package-armhf/Dockerfile.armhf
- deployment/debian-package-x64/Dockerfile
- deployment/debian-package-x64/pkg-src/control
**Changes**
With Debian Buster being the stable release for nearly two months now, update the Debian builds to use it instead of Stretch.
For the amd64 build, move from using the official Microsoft docker image (which is just Debian anyways) to the main Debian 10 image, since Microsoft is taking their sweet time in releasing for Buster. I think this is better anyways as this way all the build images are consistent, even if it uses a bit more space.
Update the LibSSL dependencies to be only 1.1. ~I will backport the stable version from Buster into Stretch for inclusion in our repos, which should just be installed automatically on an upgrade, in order to preserve full functionality for Stretch.~ In combination with the new DotNET version, this will enable full support for LibSSL 1.1. …
> Update Debian build to Buster and LibSSL 1.1

- CONTRIBUTORS.md
- Dockerfile
**Changes**
Add mesa-va-drivers to the docker image Dockerfile, which is needed for some AMD hardware to use VAAPI hardware transcoding
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/1587
Partially fixes https://github.com/jellyfin/jellyfin/issues/1609
> Add mesa-va-drivers to main Dockerfile for AMD VAAPI transcoding

- .ci/publish-nightly.yml
- .ci/publish-release.yml
For some reason the exported YAML for the release pipelines resulted in parser errors.
> Fix publish CI YAML parse error

- .ci/azure-pipelines.yml
**Changes**
This will run any xUnit tests available using the VSTest runner.
`xunit.runner.visualstudio` Nuget dependency is required for at least one test project.
@Bond-009 Please review if this is what you need. There are also some old MSTest based tests in the project right now, this might clash.
EDIT: seems like #1677 takes care of most of this.
> Add VSTest support to CI

- Emby.Server.Implementations/HttpServer/FileWriter.cs
This removes some spam when a DLNA renderer uses byte seeking.
**Changes**
Use debug log level as this will easily spam the log.
Playing a simple 1G file on my TV produced 68 lines of "Setting range response values..."
> Set log level to debug for HTTP range requests

- MediaBrowser.Model/Users/UserPolicy.cs
Right now, when a new user is created they are exposed on a public API that can potentially lead to dangerous information leaks.
This PR makes it so by default new users are hidden. Existing users will not be effected and you can always unhide newly created users.
This improves security because usernames and if a password has been set are no longer exposed to the world by default. This does *not* address the underlying problem (it's just a massive issue that requires a ton of client side work and API breakage, so its a post 11.x thing).
> Hide new users from public API by default

- deployment/windows/jellyfin.nsi
**Changes**
This adds backslashes to escape the `--datadir` path in the Windows Installer. Without this, the path would be dropped at the first space (e.g. `C:\Test Area\Jellyfin` would become `C:\Test`).
**Issues**
Fixes #1773.
> Add escapes for path quotes in the NSIS Installer

- deployment/ubuntu-package-arm64/Dockerfile.amd64
- deployment/ubuntu-package-arm64/Dockerfile.arm64
- deployment/ubuntu-package-armhf/Dockerfile.amd64
- deployment/ubuntu-package-armhf/Dockerfile.armhf
- deployment/ubuntu-package-x64/Dockerfile
**Changes**
Includes libssl-dev as a dependency in the Ubuntu build containers. Needed to make builds work for them. Related to #1693 which did the same thing for Debian and had these unintended effects on Ubuntu builds too.
**Issues**
N/A
> Include libssl-dev dep in Ubuntu build containers

- MediaBrowser.Controller/Entities/BaseItem.cs
**Changes**
Changes two lines in `...Controller/Entities/BaseItem.cs` to avoid an OutOfRangeException when scanning for new images, and to return the image info.
> Fix SetImage to avoid out of range exception

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
**Changes**
The common.build.sh script was removed in #1793 but the Dockerfiles still used this to perform the dotnet publish. Remove that call and do the publish explicitly.
**Issues**
N/A
> Do explicit dotnet publish in Dockerfiles

- MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
Current implementation uses `segment` muxer which cannot produce chunks of requested duration _and_ with correct timestamps at the same time if segmenting was not from the beginning of the video. It instead produced chunks cut on each keyframe if segmenting started from far enough in the video, so initial chunks description HLS.js was relying on became invalid. 
`ffmpeg` has a special `hls` muxer for making HLS streams which can generate proper chunks.
**Changes**
This pull request replaces `segment` muxer with `hls` one. 
**Issues**
Fixes #1694
> Fix premature stop when streaming

- Emby.Server.Implementations/Updates/InstallationManager.cs
Fixes this error:
```
[2019-09-28 15:35:39.677 +00:00] [ERR] Package installation failed
System.IO.IOException: Directory not empty
at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(PackageVersionInfo package, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(PackageVersionInfo package, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(PackageVersionInfo package, CancellationToken cancellationToken)
[2019-09-28 …
```
> Fix plugin installation

- Emby.Server.Implementations/ApplicationHost.cs
- MediaBrowser.Model/System/PublicSystemInfo.cs
Removes WAN IP detection since no client requires it. Kodi must have a release before this PR can be merged to avoid breaking nightly users.
There appears to be no need for a companion web PR as web currently does not have code that handles the WAN address. Must've been removed by someone else before this...
Fixes #679
> Remove WAN IP Detection

- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
- MediaBrowser.MediaEncoding/Properties/AssemblyInfo.cs
- MediaBrowser.sln
- tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTests.cs
- tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTestsData.cs
- tests/Jellyfin.MediaEncoding.Tests/Jellyfin.MediaEncoding.Tests.csproj
* Add support for ffmpeg 4.2
* Parse the complete ffmpeg version instead of only the first 2 digits
* Make max and min version optional
* Remove max limitation (for now)
* Style improvements
> Add tests for EncoderValidator and add support for ffmpeg 4.2

- deployment/win-x64/docker-build.sh
- deployment/win-x86/docker-build.sh
**Changes**
Recursively zip the data in the Windows packages. Without -r the directory is not properly zipped up.
**Issues**
Fixes #1784 (for real this time)
> Recursively zip Windows packages

- Emby.Server.Implementations/Data/BaseSqliteRepository.cs
**Changes**
As-is, the WAL mode for SQLite3 has problems where the WAL isn't flushed properly, resulting in the file ballooning to massive sizes and filling up disks. Instead, we change to TRUNCATE mode. This mode (as per https://www.sqlite.org/pragma.html#pragma_journal_mode) uses a traditional journal which is flushed via a truncation (rather than file delete), which removes the WAL problems, preserving write journaling, while also not having any overhead for file deletion/creation to the system.
**Issues**
Fixes #1655
> Change PRAGMA mode from WAL to TRUNCATE

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
Use DirectX 11 hardware acceleration for AMF on Windows 8 or newer.
**Issues**
Fixes #1807
> Change Win32 AMF flag to d3d11va

- Emby.Server.Implementations/ApplicationHost.cs
**Changes**
Our Kestrel configuration used `ListenAnyIP`, probably a testing/initial configuration holdover. This resulted in Kestrel always binding to a wildcard instead of the configured addresses.
This PR implements a per-IP listener, based on https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0#bind-to-a-tcp-socket. It will loop through all configured IPs and listen on all of them, or listen on all interfaces as was the default if no explicit IPs are are specified.
Explicitly works with `0.0.0.0` as well to force IPv4-only wildcard binding.
**Issues**
Fixes #1810
> Configure Kestrel listener to use configured IPs

- MediaBrowser.Api/ApiEntryPoint.cs
**Changes**
A race condition where this code attempts to kill an already exited
ffmpeg process is possible. This results in unnecessary error logging.
This change replaces the generic exception handling with the above
mentioned exception. No log output is produced. Ignoring this exception seems safe per the docs https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=netframework-4.8#System_Diagnostics_Process_Kill
> Ignore exception when attempting to kill ffmpeg that has exited

- MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
Reverts jellyfin/jellyfin#1802
Reverting this for now. It caused #1816 as well as a major (~60s) delay when starting new videos. Current plan is to release 10.4.0 with this bug still in it, as it's less severe than the delays, and then take our time to fix it properly in a 10.4.1.
> Revert "Fix premature stop when streaming"

- MediaBrowser.Api/LiveTv/LiveTvService.cs
**Changes**
Restores the SHA1 hashing of SchedulesDirect passwords.
Refs: https://github.com/SchedulesDirect/JSON-Service/wiki/API-20141201#obtain-a-token
**Issues**
Fixes https://github.com/jellyfin/jellyfin-web/issues/495
> Fix SchedulesDirect authentication

- .github/pull_request_template.md
- .github/stale.yml
- README.md
**Changes**
As per discussions on Riot, pull docs out of main site and create a separate site for them. This just updates the URL for now, work required on the infra side to actually support this.
**Issues**
N/A
> Update Docs to docs.jellyfin.org URL

- Dockerfile
**Changes**
Reported on Reddit. The `mesa-va-drivers` package isn't getting installed in the final container for amd64, and thus VAAPI playback fails. I believe this is the optimal solution since the place added in #1727 doesn't seem to get copied into the final image. This might be suboptimal so suggestions welcome.
**Issues**
N/A
> Correct missing mesa-va-drivers package

- Emby.Server.Implementations/Dto/DtoService.cs
@thornbill let me know [this change](https://github.com/jellyfin/jellyfin/pull/1665/files#diff-d49e134bc3b3dfd158111f2a66b9e6fcR1105) might have been responsible for the missing images. I tested this branch and it fixed the issue for me. I'd like to get this in 10.4.0 and then we can find a more permanent fix later.
> Fix missing image on seasons without posters

- deployment/windows/build-jellyfin.ps1
**Changes**
Now will download an ffmpeg for windows with the following header:
```
ffmpeg version N-95234-g35a63a9127 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9.2.0 (Rev2, Built by MSYS2 project)
configuration:  --disable-static --enable-shared --enable-amf --enable-bzlib --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopenjpeg --enable-libsnappy --enable-libspeex …
```
> Switch to custom patched build for ffmpeg for the Windows installer

- bump_version
**Changes**
Removes all the submodule tasks from bump_version, as this is no longer required with the dedicated jellyfin-web build steps.
**Issues**
N/A
> Fix bump_version for submodule removal

- .gitattributes
- Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
**Changes**
Set correct content type and length when reporting an issue - this should prevent exceptions like
```
[ERR] Error this.ProcessRequest(context)(Exception while writing error to the response)
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (89 of 0).
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowTooManyBytesWritten(Int32 count)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.InitializeResponseAsync(Int32 firstWriteByteCount)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
at …
```
> Fix exception when handling error, log errors better

- Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
- MediaBrowser.Model/Configuration/ServerConfiguration.cs
**Changes**
Fixes the inconsistent BaseUrl behaviour to better match standard behaviour for this sort of feature. This will now always append a configured BaseUrl to the default redirects, which should then work for all other URLs as well. Also includes a normalization of the static URLs (`/emby` and `/mediabrowser`) with the BaseUrl, such that the expected path scheme will continue to work.
To complement this, the default BaseUrl is now set to an empty string rather than `jellyfin`.
**Issues**
Fixes #1851
> Fix inconsistent BaseUrl behavior

- deployment/centos-package-x64/Dockerfile
- deployment/centos-package-x64/docker-build.sh
**Changes**
Prevents failure of the installation of jellyfin-web dependencies due to the NodeJS version in EPEL being too old. v8 might be a little conservative but is the earliest compatible version. Instead of using their repo to install Yarn, use the new nvm binary to install Yarn, thus forcing it to use the updated NodeJS version.
**Issues**
N/A (failing release builds for CentOS)
> Use NVM to install nodejs v8 and yarn for CentOS

- jellyfin.ruleset
CA1308: This doesn't matter for our use case since we never convert them back to upper case.
SA1108: Rule about comments :man_shrugging:
> Ignore warning CA1308 and SA1108

- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/Data/SqliteDisplayPreferencesRepository.cs
- Emby.Server.Implementations/Data/SqliteItemRepository.cs
- Emby.Server.Implementations/Data/SqliteUserRepository.cs
- MediaBrowser.Common/Json/Converters/GuidConverter.cs
- MediaBrowser.Common/Json/JsonDefaults.cs
- MediaBrowser.Common/MediaBrowser.Common.csproj
`System.Text.Json` and is faster in my tests than the current json serializer. Mostly because doesn't need to convert to UTF-16 and can operate directly on the `ReadonlySpan<byte>` returned by the SQlite wrapper.
> Use System.Text.Json api for databases

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
- SharedVersion.cs
- build.yaml
- deployment/debian-package-x64/pkg-src/changelog
- deployment/fedora-package-x64/pkg-src/jellyfin.spec
**Changes**
Bump `master` to 10.5.0 for next stable release.
**Issues**
N/A
> Bump version to 10.5.0 for next stable release

- Emby.Photos/Emby.Photos.csproj
- Emby.Photos/PhotoProvider.cs
- Emby.Server.Implementations/AppBase/BaseApplicationPaths.cs
- Emby.Server.Implementations/ApplicationHost.cs
- MediaBrowser.Common/Configuration/ConfigurationUpdateEventArgs.cs
- MediaBrowser.Common/Configuration/IApplicationPaths.cs
- MediaBrowser.Common/Configuration/IConfigurationFactory.cs
- MediaBrowser.Common/Configuration/IConfigurationManager.cs
- MediaBrowser.Common/Cryptography/PasswordHash.cs
- MediaBrowser.Common/Events/EventHelper.cs
- MediaBrowser.Common/Extensions/CollectionExtensions.cs
- MediaBrowser.Common/Extensions/ResourceNotFoundException.cs
- MediaBrowser.Common/HexHelper.cs
- MediaBrowser.Common/IApplicationHost.cs
- MediaBrowser.Common/MediaBrowser.Common.csproj
- MediaBrowser.Common/Net/CustomHeaderNames.cs
- MediaBrowser.Common/Net/HttpRequestOptions.cs
- MediaBrowser.Common/Net/HttpResponseInfo.cs
- MediaBrowser.Common/Net/IHttpClient.cs
- MediaBrowser.Common/Net/INetworkManager.cs
- MediaBrowser.Common/Plugins/BasePlugin.cs
- MediaBrowser.Common/Plugins/IPlugin.cs
- MediaBrowser.Common/Progress/ActionableProgress.cs
- MediaBrowser.Common/Providers/SubtitleConfigurationFactory.cs
- MediaBrowser.Common/System/OperatingSystem.cs
- MediaBrowser.Common/Updates/IInstallationManager.cs
- MediaBrowser.Common/Updates/InstallationEventArgs.cs
- MediaBrowser.Common/Updates/InstallationFailedEventArgs.cs
Adds `#pragma warning disable CS1591` to all files in
MediaBrowser.Common containing undocumented members.
> Enable `TreatWarningsAsErrors` for MediaBrowser.Common and Emby.Photos

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
The self contained packages already contains the dotnet runtime
No need to use the dotnet runtime base image.
This should decrease the size of the image.
> Use the correct dotnet runtime in Docker images 

- Emby.Naming/Emby.Naming.csproj
- Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs
- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Emby.Server.Implementations/EntryPoints/ExternalPortForwarding.cs
- Emby.Server.Implementations/Networking/NetworkManager.cs
- Emby.Server.Implementations/Updates/InstallationManager.cs
- Jellyfin.Server/Jellyfin.Server.csproj
- MediaBrowser.Common/MediaBrowser.Common.csproj
- MediaBrowser.MediaEncoding/MediaBrowser.MediaEncoding.csproj
- MediaBrowser.Model/MediaBrowser.Model.csproj
- MediaBrowser.Providers/MediaBrowser.Providers.csproj
- jellyfin.ruleset
`SmartAnalyzers.MultithreadingAnalyzer` prevents potential issues related to multithreading.
Ref: - [Avoid multithreading traps with Roslyn: Lock object selection](https://cezarypiatek.github.io/post/avoid-multithreading-traps-p1/)
- [Avoid thread synchronization problems with Roslyn: Synchronization primitives traps](https://cezarypiatek.github.io/post/avoid-multithreading-traps-p2/)
> Update deps and add MultiThreading analyzer

- .github/stale.yml
Adds an exemption we can use to keep issues open when they are confirmed/real.
> Add an exemption for the confirmed label

- Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
- MediaBrowser.Api/Playback/BaseStreamingService.cs
- MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- deployment/debian-package-x64/docker-build.sh
**Changes**
* Change ffmpeg muxer used in HLS streaming from `segment` to `hls` (`segment` muxer has a bug patch for which is not yet accepted upstream)
* Add more options to enforce keyframes in full transcoding (it should help having segment lengths to be much closer to requested "segment length")
* Add even more debug logging - used for making this happen, but won't hurt to keep it there IMHO
* Fix the condition on "enable break on non-keyframes" - this might be a potentially breaking change, but its previous state (before my fix) didn't make _any sense_ to me whatsoever.
**Issues**
It should really fix https://github.com/jellyfin/jellyfin/issues/1694 without relying to use a patched ffmpeg
> Switch ffmpeg to hls muxer (from segment) to fix premature stop on non-patched ffmpeg

- Emby.Naming/Common/NamingOptions.cs
- Emby.Server.Implementations/Library/LibraryManager.cs
- MediaBrowser.sln
- tests/Jellyfin.Naming.Tests/EpisodePathParserTest.cs
- tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj
This patch fixed some parsing errors for files found in the anime community.
This pull request includes the test cases from my previous pull request (https://github.com/jellyfin/jellyfin/pull/1877).
I tested this patch and it now parses quite a few more files on my system, however, the tests do not seem to work. If somebody could help out with figuring out why the test cases do not work, I would be very happy.
> [Draft][Help wanted] Fix parsing of certain names and adds a default season if no season was found

- MediaBrowser.sln
- tests/Jellyfin.Naming.Tests/EpisodePathParserTest.cs
- tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj
This should in the future help to detect working and non working name matchings
**Changes**
Adding tests for Emby.Naming/TV/EpisodePathParser.cs and working tests cases.
There are still a lot of common file names not covered by this test because I prioritized successful tests over tests that are supposed to work.
This should hopefully help in the future to improve the parser.
> add tests for Emby.Naming/TV/EpisodePathParser.cs

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
**Changes**
This causes the dotnet process to be pid 1 in the container.  It can receive signals like SIGTERM (from "docker stop", for example) and shut down properly.
**Issues**
None
> use exec form for Dockerfile entrypoint

- Emby.Dlna/Api/DlnaServerService.cs
- MediaBrowser.Api/BaseApiService.cs
`BaseUrl` always starts with a leading `/` (unless empty), remove it before comparing.
This is a quick hotfix as I'm currently rewriting all the logic surrounding this to allow multi segment base urls.
> Remove leading / from baseurl

- .github/stale.yml
**Changes**
1. Bump up the timings, since the project releases have slowed down a
fair bit. 120 days stale with 21 days for a response still gets us
the desired effect while loosening the timeline for issue submitters.
2. Revamp the wording to better explain what the author (or others) need
to do, and why this bot exists.
**Issues**
N/A - addressing some feedback from Reddit https://old.reddit.com/r/jellyfin/comments/dxm4u8/please_dont_use_autoclose_bots_on_issues/ in the hopes that the message stalebot leaves can better explain its purpose.
> Update stalebot timings and message

- deployment/debian-package-arm64/Dockerfile.amd64
- deployment/debian-package-arm64/Dockerfile.arm64
- deployment/debian-package-arm64/docker-build.sh
- deployment/debian-package-armhf/Dockerfile.amd64
- deployment/debian-package-armhf/Dockerfile.armhf
- deployment/debian-package-armhf/docker-build.sh
- deployment/debian-package-x64/Dockerfile
- deployment/debian-package-x64/docker-build.sh
- deployment/debian-package-x64/pkg-src/control
- deployment/debian-package-x64/pkg-src/rules
- deployment/ubuntu-package-arm64/Dockerfile.amd64
- deployment/ubuntu-package-arm64/Dockerfile.arm64
- deployment/ubuntu-package-arm64/docker-build.sh
- deployment/ubuntu-package-armhf/Dockerfile.amd64
- deployment/ubuntu-package-armhf/Dockerfile.armhf
- deployment/ubuntu-package-armhf/docker-build.sh
- deployment/ubuntu-package-x64/Dockerfile
- deployment/ubuntu-package-x64/docker-build.sh
**Changes**
Integrates the web build steps into the debuild framework, rather than performing them externally in the the `docker-build.sh` scripts. This allows for non-Dockerized builds to succeed.
This shouldn't need to be backported, but that might be a good QoL fix for anyone wanting this functionality. It won't affect our official releases though.
**Issues**
N/A
> Integrate web build into Debuntu package build steps

- jellyfin.ruleset
Ref: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1720?view=vs-2019
> Disable CA1720: Identifiers should not contain type names

- MediaBrowser.Api/UserLibrary/PersonsService.cs
Before it would be evaluated as `query.IsFavorite ?? (false && query.User != null)`
> Fix always false condition

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
Although support to the Broadcom Multimedia Abstraction Layer [has been added to jellyfin-ffmpeg](https://github.com/jellyfin/jellyfin-ffmpeg/pull/14) and h264_mmal [was already handled in the logic of the server](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L2530), it seems that it wasn't registered as a valid one in the validator and it's simply skipped.
This quick PR aims to add full support for all the hardware accelerated codecs that the Pi and MMAL-capable devices provides. Although it can be instantly merged, it should be considered as a WIP, as I'm still testing in my environment all the filetypes and bitrates possible.
> Add full Raspberry Pi hardware accelerated decoding support

- Jellyfin.Server/Resources/Configuration/logging.json
**Changes**
Adds default values to logger config by using the loggers configuration arguments.
**Issues**
Fixes #2056 
Fixes #2069 
**Detailed description**
This PR adds the following default values to the shipped logging configuration:
- 100MB filesize limit
- activates filesize based logrotation
- sets the number of retained logfiles to three
The number of the retained logfiles is derived from the default value of the logfile cleanup task that sets the age of logfiles to three days. Since the time based  logfile rotation is set to "Days" interval this would result in three logfiles to keep.
The default logfile size was chosen to ensure that limited memory devices like a raspberry can handle the logfile size with still sufficient ressources left for other processes.
Looking at personal …
> add filesize limit for logfiles and a maximum logfile count

- Jellyfin.Server/Jellyfin.Server.csproj
**Changes**
- added the nuget package to enable Serilog's GELF logging.
**Issues**
none
**feature requests**
[Add support for centralized logging](https://features.jellyfin.org/posts/343/add-support-for-centralized-logging)
**example configuration**
/config/logging.json
```
{
"Serilog": {
"MinimumLevel": "Information",
"WriteTo": [
{
"Name": "Console",
"Args": {
"outputTemplate": "[{Timestamp:HH:mm:ss}] [{Level:u3}] {Message:lj}{NewLine}{Exception}"
}
},
{
"Name": "Graylog",
"Args": {
"HostnameOrAddress": "localhost",
"Port": "12202",
"TransportType": "Udp"
}
}
]
}
}
```
***alternative valid values:***
HostnameOrAddress can also be an IP Address like:
`"192.0.0.1"`
TransportType can also be one of these:
`"Tcp", "Http"`
**background**
The logging in Jellyfin is quite messy (read: …
> added required nuget package to enable serilog based centralized logging in gelf format

- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Emby.Server.Implementations/ScheduledTasks/Tasks/PluginUpdateTask.cs
- Emby.Server.Implementations/Updates/InstallationManager.cs
- MediaBrowser.Common/Updates/IInstallationManager.cs
```cs
Value cannot be null. (Parameter 'source') at
System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument) at
System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable'1 source, Func'2 predicate, Boolean& found) at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable'1 source, Func'2 predicate) at Emby.Server.Implementations.Updates.InstallationManager.<>c__DisplayClass39_0.b__0(IPlugin x) in /home/pi/dev/jellyfin/Emby.Server.Implementations/Updates/InstallationManager.cs:line 203 at
System.Linq.Enumerable.SelectArrayIterator'2.MoveNext() at
System.Linq.Enumerable.WhereEnumerableIterator'1.ToList() at
System.Linq.Enumerable.ToList[TSource](IEnumerable'1 source) at
Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken …
```
> Fix possible nullref when updating packages

- Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs
- MediaBrowser.Common/Configuration/EncodingConfigurationExtensions.cs
* GetTranscodePath returned an empty string after the option was left
blank in the web UI
* Unified the log style for all paths
> Fix GetTranscodePath function and cache path update logline

- Emby.Naming/Common/NamingOptions.cs
The regex used was performing very poorly because of excessive backtracking. Example: https://regex101.com/r/DkpDYz/5
**Issues**
Hopefully fixes:
- #2090
- #2092 (maybe)
- #2059
> Simplify regex to avoid catastrophic backtracking

- Emby.Server.Implementations/Updates/InstallationManager.cs
- MediaBrowser.Api/PackageService.cs
The `/Packages/{Name}` endpoint would return a package that had either
the corrent name or the correct guid. In reality it should check if both
are correct.
> Fix plugin installation and correct api behaviour

- deployment/ubuntu-package-x64/Dockerfile
**Changes**
This was not working; for some reason the Microsoft .NET Docker image
for 3.0 still had a 2.1 binary which was wreaking havoc. Replace it with
the manual download that all the other .deb packages use.
**Issues**
N/A
Fixes the Ubuntu nightly builds that have been failing since mid-October.
> Remove broken Microsoft SDK image

- Emby.Server.Implementations/Session/SessionManager.cs
`AuthenticateUser()` errors if `user` is `null` so the checks should be before that
> Fix invalid username handling

- Emby.Server.Implementations/Library/LibraryManager.cs
- Emby.Server.Implementations/Playlists/PlaylistManager.cs
- MediaBrowser.Api/Library/LibraryService.cs
Playlists are stored in directories, but there was a check for `File.Exists()` which doesn't return true for folders. @Bond-009 I tracked the issue back to a [commit](https://github.com/jellyfin/jellyfin/commit/ffe79c89829fb232e8ccb4ae4caf4b732ce51600) you made in January. I'm guessing this is the source of most of our deletion issues so we might need to go through and fix all the other changes from that commit and any similar changes.
> Fix playlist deletion and a few warning fixes

- CONTRIBUTORS.md
- MediaBrowser.Providers/Tmdb/TV/TmdbSeasonImageProvider.cs
- MediaBrowser.Providers/Tmdb/TV/TmdbSeasonProvider.cs
**Changes**
Adds TheMovieDb as a provider for the TV Season Posters. As I am very new to this project, I looked up how things are done in the Series Provider and added the Provider for Seasons accordingly.
**Issues**
Fixes #1034
> Add Tmdb as a Provider for Season Images

- deployment/centos-package-x64/Dockerfile
- deployment/debian-package-arm64/Dockerfile.amd64
- deployment/debian-package-arm64/Dockerfile.arm64
- deployment/debian-package-arm64/docker-build.sh
- deployment/debian-package-armhf/Dockerfile.amd64
- deployment/debian-package-armhf/Dockerfile.armhf
- deployment/debian-package-armhf/docker-build.sh
- deployment/debian-package-x64/Dockerfile
- deployment/debian-package-x64/docker-build.sh
- deployment/debian-package-x64/pkg-src/control
- deployment/fedora-package-x64/Dockerfile
- deployment/fedora-package-x64/pkg-src/jellyfin.spec
- deployment/linux-x64/Dockerfile
- deployment/macos/Dockerfile
- deployment/portable/Dockerfile
- deployment/ubuntu-package-arm64/Dockerfile.amd64
- deployment/ubuntu-package-arm64/Dockerfile.arm64
- deployment/ubuntu-package-arm64/docker-build.sh
- deployment/ubuntu-package-armhf/Dockerfile.amd64
- deployment/ubuntu-package-armhf/Dockerfile.armhf
- deployment/ubuntu-package-armhf/docker-build.sh
- deployment/ubuntu-package-x64/Dockerfile
- deployment/ubuntu-package-x64/docker-build.sh
- deployment/win-x64/Dockerfile
- deployment/win-x86/Dockerfile
**Changes**
Switch the .NET SDK urls to updated ones, and change the build args and docker-build.sh to also reflect the update.
> Update the build script to use .NET core SDK 3.1

- Emby.Server.Implementations/IO/ManagedFileSystem.cs
**Changes**
Re-orders the path statement to achieve the correct result.
Assuming:
```c#
string folderPath = "/Volumes/Library/Sample/Music/Playlists/";
string filePath = "../Beethoven/Misc/Moonlight Sonata.mp3";
```
The result before:
`/Volumes/Library/Sample/Music/Playlists/../Beethoven/Misc/Moonlight Sonata.mp3`
The new result:
`/Volumes/Library/Sample/Music/Beethoven/Misc/Moonlight Sonata.mp3`
This returns the output to what it was in 10.3.7 and older, prior to #1168.
**Issues**
Fixes #1874.
> Re-order the path statement to avoid file issues

- MediaBrowser.Api/Playback/UniversalAudioService.cs
**Changes**
This PR will fallback the segment container to `mpegts` if the device reports a invalid container format. This fixes transcoded music playback on some devices (particularly Apple devices).  For more details please refer to the issue below.
**Issues**
Fixes #2214
> Let HLS fallback to mpegts in case device reports unsupported container

- .github/ISSUE_TEMPLATE/media_playback.md
gimme yo ffmpeg logs, yo
**Changes**
**Issues**
> Explicitly ask for ffmpeg logs

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
**Changes**
1) Add support for AMD AMF hardware encoding on Windows and Linux which can reduce cpu usage instead of using default libx264 in ffmpeg.
2) h264_amf is [now supported on linux](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/4#issuecomment-572301302) with ['amdgpu-pro'](https://amdgpu-install.readthedocs.io/en/latest/) installed and '--enable-amf' when compiling [ffmpeg](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/f8ad2ddd7a51df5d6e768ba2a6f65ee64b94e29b).
3) Using vaapi decode and h264_amf encode on linux platform can avoid some weird transcoding [errors in h264_vaapi with amd gpu](https://github.com/jellyfin/jellyfin/issues/1527).
It works like [this](https://imgur.com/Q3GrwkS) on windows now.
ffmpeg h264_amf on linux encoding succeed …
> add support for AMD AMF hardware encoding on Windows & Linux

- Dockerfile
The current dockerfile in the root directory does not work on linux with systemd>=227.
It aborts with some errors about not being able to get nuget packages.
The solution is to either allow more tasks to run by systemd or disable parallel building as given in these two resources.
- https://success.docker.com/article/how-to-reserve-resource-temporarily-unavailable-errors-due-to-tasksmax-setting
- https://stackoverflow.com/questions/59476800/resource-temporarily-unavailable-when-building-dotnet-core-3-0-dependency-on-ubu
> fixes dockerfile building on recent linux installations

- Dockerfile.arm
- Dockerfile.arm64
Updated image base.
There was an error for libssl missing. I attempted to add libssl1.0.0 but it wasn't found so I fell back to libssl-dev.
Much more work needs to be done. ffmpeg is still debian based. I attempted to add jellyfin-ffmpeg but I was having too many issues so I'm saving it for another day, but it at least builds out successfully.
**Changes**
**Issues**
> Fix Docker Arm Nightly

- Dockerfile.arm
- Dockerfile.arm64
Allow for native building of Docker images. Use buildx if cross-compilation is needed.
> Consolidate arm images

- CONTRIBUTORS.md
- Emby.Dlna/ContentDirectory/ControlHandler.cs
Previously, when responding to a DLNA "Browse" request, the `StartingIndex` was not respected and all of the root items were returned each time. This caused infinite loops with in DLNA clients that ignored the `TotalMatches` data in the response and just continued asking for the next page until they got an empty response.
This fix makes the root folder list respect the `StartingIndex` and `RequestedCount` parameters like all other responses.
Fixes issue #2303
> Fix pagination for DLNA root folder list

- MediaBrowser.Api/Playback/MediaInfoService.cs
For some reason paths not mapped on that endpoint, but it will be nice to have for enabling native paths in [jellyfin-mpv-shim](https://github.com/iwalton3/jellyfin-mpv-shim).
**Changes**
**Issues**
> Enable path mapping in `PlaybackInfo` endpoint

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
The "mkv" container apparently does not support the "global_header" flag. This PR adds a small check if the container supports the flag and does not add it if it's not supported. This is mostly relevant when using the Live TV feature on Android.
**Issues**
Fix #1945
> Add check if output container supports "global_header" flag

- MediaBrowser.Api/Playback/StreamState.cs
- MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
- MediaBrowser.Controller/MediaEncoding/JobLogger.cs
**Changes**
Include transcoding framerate information in session playback data transcoding info.
In my opinion it's quite useful to see the conversion framerate of the transcoding progress to quickly determine a possible bottleneck.
> Add transcoding framerate info

- MediaBrowser.Controller/Entities/UserRootFolder.cs
The `UserRootFolder.GetItemsInternal` method now applies any sorting and
pagination requested by the `InternalItemsQuery` that was passed to it.
Previous pagination fix: #2304
Original issue #2303
> Fix another issue with DLNA responses not properly paginating

- deployment/linux-x64/docker-build.sh
- deployment/macos/docker-build.sh
- deployment/portable/docker-build.sh
- deployment/win-x64/docker-build.sh
- deployment/win-x86/docker-build.sh
This should be considered a temp fix, as it fixes the symptom and not
the actual root cause of the issue. Why this works? I *feel like* this is
a dependency issue and this change forces it to evaluate dependency's in a
different order, avoiding the bug.
> Fix broken webserver caused by dotnet publish. Temp Fix for #2255

- MediaBrowser.Controller/MediaEncoding/JobLogger.cs
**Changes**
Fixed an issue that when the media source is in H264 format and the frame rate info is not displayed due to missing space characters in ffmpeg log.
> Fix framerate info not showing when mediasource is in H264 format.

- deployment/fedora-package-x64/Dockerfile
**Changes**
Fedora builds were broken due to dotnet-sdk-3.1 and dotnet-runtime-3.1 not being available on the @dotnet-sig/dotnet repo as well as a lack of the git package (needed for yarn when installing jellyfin/jellyfin-noto per https://github.com/jellyfin/jellyfin-web/pull/735). Replaces the outdated repo with the official repo found in Microsoft's documentation.
**Issues**
Not applicable.
> Fix Fedora build

- MediaBrowser.Common/Configuration/IConfigurationFactory.cs
- MediaBrowser.Controller/Plugins/IServerEntryPoint.cs
- MediaBrowser.Model/Services/ApiMemberAttribute.cs
Some small additions to XML documentation. I documented these classes while working on a separate task for the auto-organize plugin.
**Changes**
Adds\updates XML documentation for `IConfigurationFactory`, `IServerEntryPoint ` and `ApiMemberAttribute `
**Issues**
Not related to any issue
> Add Some XML Documentation

- Emby.Server.Implementations/ApplicationHost.cs
- MediaBrowser.Model/Configuration/ServerConfiguration.cs
Baseurl always starts with a '/' (unless it's empty)
Fixes the error from #2380 (Don't know if it fixes the issue)
> Another baseurl related fix

- Emby.Naming/Common/NamingOptions.cs
- tests/Jellyfin.Naming.Tests/TV/EpisodeNumberTests.cs
- tests/Jellyfin.Naming.Tests/TV/SeasonNumberTests.cs
> Fix episode parsing

- tests/Jellyfin.Naming.Tests/TV/AbsoluteEpisodeNumberTests.cs
- tests/Jellyfin.Naming.Tests/TV/DailyEpisodeTests.cs
- tests/Jellyfin.Naming.Tests/TV/EpisodeNumberWithoutSeasonTests.cs
- tests/Jellyfin.Naming.Tests/TV/EpisodePathParserTest.cs
- tests/Jellyfin.Naming.Tests/TV/EpisodeWithoutSeasonTests.cs
- tests/Jellyfin.Naming.Tests/TV/MultiEpisodeTests.cs
- tests/Jellyfin.Naming.Tests/TV/SeasonFolderTests.cs
- tests/Jellyfin.Naming.Tests/TV/SeasonNumberTests.cs
- tests/Jellyfin.Naming.Tests/TV/SimpleEpisodeTests.cs
This moves all current tests in tests/Jellyfin.Naming.Tests/TV to the [Theory] and [InlineData] format.
This makes the files much shorter and clearer imho. I also added a couple more testcases from issues I saw around my files and github issues.
All testcases included are passing, tests that would not pass are commented out and with a // TODO:
> moves shows tests to Theory and InlineData format

- Emby.Server.Implementations/Library/Resolvers/PlaylistResolver.cs
- MediaBrowser.LocalMetadata/Savers/PlaylistXmlSaver.cs
This fixes the issue with playlists being removed from the library during library scans.
**Changes**
Updated the `PlaylistResolver` to correctly resolve playlist items that are stored in the library using a directory.
**Issues**
Fixes #2425
> Fix Playlist Deletion

- MediaBrowser.Api/Library/LibraryService.cs
.Net Regex doesn't support Posix character classes. It will throw the following exception when the filename contains non-ASCII character:
```
Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x6E2C
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(StringValues headerValues)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.AddValueFast(String key, StringValues value)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.System.Collections.Generic.IDictionary<System.String,Micro …
```
> Fix download file with non-ASCII filename

- Emby.Server.Implementations/ApplicationHost.cs
- Jellyfin.Server/Program.cs
- Jellyfin.Server/Resources/Configuration/logging.json
Register logging services correctly with the DI container so they are resolved correctly.
**Changes**
* Replace existing DI type registrations with a call to [`UseSerilog()`](https://github.com/dotnet/extensions/blob/master/src/Logging/Logging/src/LoggingServiceCollectionExtensions.cs#L42) which registers `ILoggerFactory` and `ILogger<T>`
* Keep a registration for `ILogger` but add a TODO note to deprecate it in favour of `ILogger<T>`
* Reduce logging output from `Microsoft` and `System` namespaces to a min level of `Warning`, which is [recommended in the Serilog documentation](https://github.com/serilog/serilog-settings-configuration#level-overrides). If we don't to make this change, we need to at least reduce the output for `Microsoft.AspNetCore` which clogs up the logs with every …
> Register Logging Services Correctly

- Jellyfin.Server/CoreAppHost.cs
- Jellyfin.Server/Migrations.cs
- Jellyfin.Server/Program.cs
- MediaBrowser.Model/Configuration/BaseApplicationConfiguration.cs
**Changes**
* Implement running generic Jellyfin update routines.
* Set `EnableThrottling` to `false` on pre-10.5.0 migration to 10.5.0 or newer, as this option wasn't used before and in 10.5.0 there are reports it's causing issues. Users could still enable it after installation in the admin dashboard.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/2516
> Implement ability to run migration routines when updating Jellyfin

- deployment/windows/jellyfin.nsi
You really need to pay attention to notice that there are icons there:
Without choosing Jellyfin is even worse:
Now, the same icon of the installer is used, as it's far more visible, and probably users will recognixe it better as it's the same that it's in the tray:
> Replaces NSIS uninstaller icon so it's more visible

- MediaBrowser.Api/Playback/MediaInfoService.cs
**Changes**
Adds the baseURL to the URL returning attachments. Prevents the case of attachments returning a 302 when using a baseURL.
**Issues**
> Add baseURL to attachments API url

- MediaBrowser.Model/Configuration/ServerConfiguration.cs
Prevents issues on first setup when behind a reverse proxy. Also
prevents issues saving the Networking page by default if SSL is not
fully configured.
> Set EnableHttps disabled by default

- Dockerfile.arm
This curl command seems to fail inexplicably with an "unable to get
local issuer" error. Use `-k` instead so it doesn't complain.
The full error:
```
root@820864ddf7c3:/# curl https://repo.jellyfin.org/debian/jellyfin_team.gpg.key
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
> Fix curl for Jellyfin GPG key

- deployment/centos-package-x64/Dockerfile
- deployment/fedora-package-x64/pkg-src/jellyfin.spec
**Changes**
Fixes the build issues for Fedora and CentOS on 10.5.0.
**Issues**
Addresses #2550 short-term
Fixes #2563
> Correct BuildRequires and NodeJS for Fedora/CentOS

- Emby.Server.Implementations/ApplicationHost.cs
Update startup logging to also include `JELLYFIN_` prefixed environment variables. These variables are [loaded into the configuration framework](https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Server/Program.cs#L488), so we should be logging them.
> Log 'JELLYFIN_' environment variables at application start

- .ci/azure-pipelines-main.yml
- .ci/azure-pipelines-windows.yml
- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
Use `yarn install` on its own instead of `yarn:build` in Azure build scripts and Docker files.
This brings the build scripts up to date with changes made in jellyfin-web: https://github.com/jellyfin/jellyfin-web/pull/953/files
> Fix Client Build Scripts

- .github/ISSUE_TEMPLATE/feature_request.md
Add a template for feature request issues, instructing user to not create them on GitHub and directing to the Fider instance instead. The template also provides direction for users who are willing to contribute code for new features themselves.
Definitely open to feedback on this, I'm opening this PR as a proposal for discussion as well.
~~This template can be previewed on my fork: https://github.com/mark-monteiro/jellyfin/issues/new?template=feature_request.md~~
> Feature Request Issue Template

- MediaBrowser.Controller/Entities/BaseItem.cs
Exception was being thrown if `ExtraType` has a null value
**Issues**
Fixes #2484
> Add missing null check when retrieving extras

- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Jellyfin.Api/Jellyfin.Api.csproj
- Jellyfin.Server/Jellyfin.Server.csproj
- MediaBrowser.Common/MediaBrowser.Common.csproj
- MediaBrowser.Controller/MediaBrowser.Controller.csproj
- MediaBrowser.Model/MediaBrowser.Model.csproj
- MediaBrowser.Providers/MediaBrowser.Providers.csproj
- benches/Jellyfin.Common.Benches/Jellyfin.Common.Benches.csproj
- tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
Update all packages in the main repository to .NET Core 3.1.2. 
Known issues with the 3.1.2 release are listed here: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md
There are two issues listed for the 3.1.2 release, but neither seems to be relevant to this project.
> Update .NET Core to 3.1.2

- README.md
Add 2 RSS feed badges to the README.
Looks like this. The commits one is a feed that sends info on all commits merged into master. Might be possible to have it on latest stable, but not sure anyone would want that.
> Add RSS feed badges to README

- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
This PR fixes embedded MKV subtitles. There was a problem where the stream that needed to be send was closed before the stream could be served to the client. It retains the fix that enables UTF-8 subtitles in srt format to be streamed.
I have tested this with:
- Embedded MKV subtitles in SRT and ASS format.
- External UTF-8 ASS and SRT subtitles without BOM.
Tests were performed in MPV Shim and the web client.
**Changes**
Change GetSubtitleStream to return a file stream instead of a stream that will be closed by the using block.
**Issues**
Fixes #2650
> Fix embedded mkv subtitles.

- MediaBrowser.Model/Extensions/StringHelper.cs
- MediaBrowser.Model/MediaBrowser.Model.csproj
**Changes**
Added netstandard 2.0 as TargetFramework to allow usage from UWP (netstandard 2.1 not available in UWP until .net 5)
**Issues**
N/A
> Add netstandard2.0 as TargetFramework

- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Jellyfin.Api/Jellyfin.Api.csproj
- Jellyfin.Server/Jellyfin.Server.csproj
- MediaBrowser.Common/MediaBrowser.Common.csproj
- MediaBrowser.Controller/MediaBrowser.Controller.csproj
- MediaBrowser.Model/MediaBrowser.Model.csproj
- MediaBrowser.Providers/MediaBrowser.Providers.csproj
- tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
Update all packages in the main repository to .NET Core 3.1.3 
Known issues with the 3.1.x releases are listed here, but no new issues are raised for this release: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md
> Update .NET Core to 3.1.3

- Emby.Server.Implementations/ApplicationHost.cs
There is a missing null check in the `ApplicationHost.Dispose()` method that throws a `NullReferenceException` if `_displayPreferencesRepository` has not been initialized.
An example of this happening: https://github.com/jellyfin/jellyfin-plugin-autoorganize/issues/29#issuecomment-603984114
> Fix ApplicationHost Dispose() method

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
**Changes**
When building a SQL statement, variables being bound must correspond to placeholder names.
The insert query was using `_mediaAttachmentSaveColumns` for names, so I'm fixing bindings to use same names.
**Issues**
Without this patch saving scanned attachments for me are completely broken erroring out with
```
[ERR] [22] App: Error in ffprobe
System.ArgumentException: Invalid param name: @FileName0 (Parameter 'name')
at Emby.Server.Implementations.Data.SqliteExtensions.CheckName(String name) in jf-src\jellyfin\Emby.Server.Implementations\Data\SqliteExtensions.cs:line 184
at Emby.Server.Implementations.Data.SqliteExtensions.TryBind(IStatement statement, String name, String value) in jf-src\jellyfin\Emby.Server.Implementations\Data\SqliteExtensions.cs:line 215
at …
```
> Make variables binding correspond with column names

- Emby.Server.Implementations/Session/SessionManager.cs
**Changes**
Reverts the ordering change from #2146 which caused user creation in the LDAP plugin to fail.
The underlying CORS issue #1794 ("connection failed" for invalid users) is still present, but that is outside scope right now.
**Issues**
Fixes #2540
> Revert #2146 ordering change

- MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
**Changes**
-  Fix the incorrect HLS time while using some HW encoders. Optimize video loading time.
**VAAPI**
- Fix an issue where some text subtitles could not be burned. (for Intel and AMD gfx)
- Fix an issue where some graphical subtitles could not be burned. (especially for AMD gfx)
- Fix an issue that some external PGSSUB graphical subtitles are not synchronized after burning.
- You can enable VAAPI HW acceleration partially without issues now.
**QSV**
- Fix an issue where some text subtitles could not be burned.
**NVENC**
- Fixed an issue where graphics subtitles were not scaled correctly.
- h264 10-bit is not decodable by NVDEC, so fallback to SW dec.
**Possible related issues**
- #2261
`No usable encoding profile found.`
- #2238 #2344
`Impossible to convert between the formats …
> Fix various bugs in HWA subtitle burn-in

- Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
Arm binaries were outdated leading to crashes on Arm platforms.
Fixes #2471
> Update Jellyfin.SkiaSharp.NativeAssets.LinuxArm to version 1.68.1

- Jellyfin.Server/Program.cs
Enable HTTP/2 support in Kestrel for HTTPS ports.
**Changes**
All that was required is to set `listenOptions.Protocols = HttpProtocols.Http1AndHttp2` when binding to the port.
Note that there are certain [documented conditions](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#http2-support) that must be met for Kestrel to enable HTTP/2. In particuar:
> †HTTP/2 will be supported on macOS in a future release. ‡Kestrel has limited support for HTTP/2 on Windows Server 2012 R2 and Windows 8.1.
**I am assuming that Kestrel gracefully falls back to HTTP1 in these scenarios, but I do not have the hardware to test that for sure.**
**Issues**
Fixes #403
> Enable HTTP/2 support

- Emby.Dlna/Didl/DidlBuilder.cs
**Changes**
When browsing TV episodes in Next Up, etc via DLNA a more descriptive title should be used to easier identify the right episode.
Checks if it's an episode that's not in a season directory/context, if it isn't, then add series name, season and episode numbers to the title
**Issues**
Fixes #295
> Add descriptive TV episode titles for DLNA browsing

- Emby.Dlna/Api/DlnaServerService.cs
- Emby.Dlna/Api/DlnaService.cs
- Emby.Dlna/ContentDirectory/ControlHandler.cs
- Emby.Dlna/Didl/DidlBuilder.cs
- Emby.Dlna/Didl/StringWriterWithEncoding.cs
- Emby.Dlna/Emby.Dlna.csproj
- Emby.Dlna/PlayTo/Device.cs
- Emby.Dlna/PlayTo/PlayToController.cs
- Emby.Dlna/PlayTo/PlayToManager.cs
- Emby.Dlna/PlayTo/SsdpHttpClient.cs
- Emby.Notifications/Api/NotificationsService.cs
- Emby.Server.Implementations/Data/SqliteItemRepository.cs
- MediaBrowser.Controller/Entities/InternalPeopleQuery.cs
Also adds the `AddPeople` method back in `DidlBuilder`, it was commented out in the .net core port
> Fix some warnings

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
Change the default locale from `POSIX` to `make Jellyfin support  non-ASCII characters.
**Issues**
before:
```
'['$'\351\223\266\347\277\274\346\235\200\346\211\213''].Blade.Runner.1982.FiNAL.CUT.720p.HDDVD.x264-SiNNERS.mkv'
'['$'\351\223\266\347\277\274\346\235\200\346\211\213''].Blade.Runner.1982.FiNAL.CUT.720p.HDDVD.x264-SiNNERS.nfo'
```
after apply patch:
```
'[银翼杀手].Blade.Runner.1982.FiNAL.CUT.720p.HDDVD.x264-SiNNERS.mkv'
'[银翼杀手].Blade.Runner.1982.FiNAL.CUT.720p.HDDVD.x264-SiNNERS.nfo'
```
> Dockerfile: support for non-ASCII characters

- deployment/debian-package-x64/pkg-src/control
Lower versions cause #2126 in Jellyfin >= 10.4.3.  This adds in a guardrail against building yourself a broken environment via the .deb installation
> Specify a minimum version for jellyfin-ffmpeg dependency in .deb dependencies

- MediaBrowser.Model/Dlna/DirectPlayProfile.cs
**Changes**
Fix check for profile supporting a codec - it should first check profile media type
For example, audio-only profiles have "VideoCodec" set to "null" which translates to "any codec", which breaks some logic later on.
Before this change in some conditions a stream being transcoded because video codec was unsupported had `ContainerExceedsLimit` as a transcode reason (example: `h265` video + `aac` 5.1 audio packed in `.mkv` and played back in mobile browser).
After the fix the reason is proper `audio codec not supported` and `video codec not supported`.
**Issues**
Don't know if we have some open.
> Make codec check in profile examine profile type first

- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Emby.Server.Implementations/ScheduledTasks/Tasks/PluginUpdateTask.cs
- Emby.Server.Implementations/Updates/InstallationManager.cs
- MediaBrowser.Common/Updates/IInstallationManager.cs
This package is only used in one place and is used in a way that is incorrect, so I propose we remove it.
**Changes**
* Remove incorrect use of `IAsyncEnumerable`
* Remove `System.Interactive.Async` NuGet package
> Remove Ix.NET

- MediaBrowser.Api/UserLibrary/ItemsService.cs
Currently, permission settings on Channels are not taken into account prior to returning `{UserName} is not permitted to access Library {ItemName}.`.  Whether or not a user can see items within the Channel is solely dependent on `EnableAllFolders`, so you cannot view a plugin's Channels unless you can also see ALL libraries.
**Changes**
This PR enables does two things for Channel-providing Plugins:
1. Fixes functionality of "EnableAllChannels"
2. Allows users with Channel permissions to access all folders within that Channel
I'm not 100% sure on 2 but I wasn't able to see an obvious way to propagate permissions downward into specific Folders inside a Channel.
I tested on a fairly simple library with two channel-providing plugins (ServerWMC, LazyMan) and it seems to work, but this behavior …
> Separate Channels permissions from All Libraries

- .gitignore
This is the correct directory that the `jellyfin-web` content should be copied to before building the server. You can see it is copied to the output directory in the [.csproj configuration](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.WebDashboard/MediaBrowser.WebDashboard.csproj#L14) and is also used in the Docker [build script](https://github.com/jellyfin/jellyfin/blob/master/deployment/portable/docker-build.sh#L13).
I've added it to the .gitignore since it wasn't there before.
> Add MediaBrowser.WebDashboard\jellyfin-web to .gitignore

- Emby.Naming/Common/NamingOptions.cs
- Emby.Naming/Video/ExtraResolver.cs
- Emby.Naming/Video/ExtraRule.cs
- Emby.Naming/Video/ExtraRuleType.cs
- Emby.Server.Implementations/Dto/DtoService.cs
- Emby.Server.Implementations/Library/LibraryManager.cs
- MediaBrowser.Api/UserLibrary/UserLibraryService.cs
- MediaBrowser.Controller/Entities/BaseItem.cs
- MediaBrowser.Model/Entities/ExtraType.cs
The existing behavior for extras is to not display any extras where the `ExtraType` property could not be determined (i.e. is `null`). This changes that behavior to display those extras with unknown type.
There should likely be additional changes to improve/change how the extra type is parsed, but I think that should be in a separate PR and would be out of scope here.
**Changes**
* Include extras with an unknown type in the `SpecialFeatureCount` DTO property 
* Include extras with an unknown type in response to a `GetSpecialFeatures` request
* Fix an issue where the `ExtraType` is saved as `0` (an invalid enumeration value) instead of `null`
**Issues**
Fixes #2665 
Fixes #2484
> Display Extras With Unknown Types

- deployment/debian-package-x64/pkg-src/control
Reverts jellyfin/jellyfin#2749
We have to revert this because changing this file totally breaks my PR #2656 and I don't know how to fix it (I deleted/renamed the file, but even cherry-picking this commit didn't help).
So revert for now, this change is included in the aforementioned PR now.
> Revert "Specify a minimum version for jellyfin-ffmpeg dependency in .deb dependencies"

- Emby.Server.Implementations/ConfigurationOptions.cs
- Emby.Server.Implementations/IStartupOptions.cs
- Emby.Server.Implementations/Updates/InstallationManager.cs
- Jellyfin.Server/StartupOptions.cs
Add a command line switch and configuration setting for the plugin repository.
**Changes**
- Add `--plugin-manifest-url` command line option and `InstallationManager:PluginManifestUrl` configuration option and connect them to the `IConfiguration` framework
- Set `https://repo.jellyfin.org/releases/plugin/manifest.json` as the default value
- Add some extra logging in case the URL specified is not valid
> Make Plugin Repo URL Configurable

- MediaBrowser.Controller/Entities/InternalPeopleQuery.cs
Very small change to fix a mis-formed comment. This change is needed to get jellyfin/jellyfin-docs#299 working
> Fix misformed xml doc comment

- tests/Jellyfin.Naming.Tests/Video/ExtraTests.cs
Add unit tests for the extra directories detection added by PR #2696 that addressed #2665 and #2484 in order to catch any regressions as the capability matures.  It's parameterized, so should be easy to add more once more combinations come in via something like 231ef22 or if changes to supported directories change.
Btw, excuse the branch name.  Old habits and all.
> Add Unit Tests for the Extras Directories

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
**Changes**
This PR was proposed by @PeterCxy.
> Currently, Jellyfin always tries to use the default aac encoder in ffmpeg when transcoding audio (for both video files and standalone music files). This encoder is fine for most purposes, but sometimes it produces some really jarring distortion at higher frequencies. It would be nice to be able to use a better aac encoder, however even if ffmpeg is built with libfdk_aac enabled, Jellyfin still uses the default aac encoder.
The library is also incompatible with GPL. Users would still need to supply their own build of FFmpeg to make this work, as libfdk_aac could not be redistributed.
https://ffmpeg.org/ffmpeg-all.html#libfdk_005faac
**Issues**
Fixes: https://github.com/jellyfin/jellyfin/issues/2705
> Prefer to use libfdk_aac encoder for better audio quality when it is available

- MediaBrowser.Api/Playback/MediaInfoService.cs
Noticing some sync issues when transcoding livetv, the only thing I was able to do to fix it was to force the audio stream to be transcoded as well. This was how I originally wrote the code and we changed it during the review process. I am reverting it back to the original code. This only impacts the Force LiveTV Transcoding option. 
**Changes**
**Issues**
> Force Audio Transcoding for LiveTV Transcoding

- Emby.Server.Implementations/EntryPoints/ExternalPortForwarding.cs
- MediaBrowser.Model/Configuration/ServerConfiguration.cs
* Disable UPnP by default (seems like at least a few people wanted this change, but can easily revert if we decide to keep it: https://github.com/jellyfin/jellyfin/issues/2589#issuecomment-608802553)
* Do not forward HTTPS port when it is not enabled
* Fix a few bugs with restarting port forwarding when the networking config is changed
* Cleanup UPnP service code
**Issues**
* Possibly helps with #2589
> Port Forwarding Improvements

- Jellyfin.Api/Controllers/StartupController.cs
- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
**Changes**
Fixes responses from the Jellyfin API being automatically camel cased. Currently only affects the startup wizard endpoints.
**Issues**
Fixes #2812 
Replaces jellyfin/jellyfin-web#1050
> Fix casing of JSON in Jellyfin API

- MediaBrowser.Model/Net/MimeTypes.cs
**Changes**
Adds mime types for ape, wv and mpegts files so that they can be displayed in VLC Player.
**Issues**
#1181
> Additional mime types for DLNA (VLC)

- Emby.Server.Implementations/HttpServer/HttpResultFactory.cs
**Changes**
We shouldn't be using a simple `.ToString()` because it violates the RFC.
Also on non-US locale it wasn't parsed correctly back, so caching seemed to be broken.
**Issues**
Not that I know of.
But it fixed not using a cache whatsoever for me, as before all resources were always retrieved from the server, and now static files are properly served as `304 Not Modified` when appropriate.
> Make Last-Modified and If-Modified-Since headers follow the spec

- MediaBrowser.Api/Playback/BaseStreamingService.cs
**Changes**
Handle outputFileExtension  == null in GetOutputFilePath by setting it to "".
**Issues**
Fixes #2737
> Handle null outputFileExtension in GetOutputFilePath

- MediaBrowser.Controller/Entities/BaseItem.cs
**Changes**
Removes `[JsonIgnore]` from above `DateLastSaved` in BaseItem.cs. This allows the property to be properly read and updated whenever media is added, or edited.
**Issues**
Fixes #2881, allowing clients to use the property reliably for detecting content updates.
> Fix eTags DateLastSaved

- Dockerfile
**Changes**
This PR is part of https://github.com/jellyfin/jellyfin-ffmpeg/pull/33
- Use `jellyfin-ffmpeg` deb package with integrated free drivers to avoid intel non-free drivers.
> Switch to jellyfin-ffmpeg with integrated driver in docker build

- MediaBrowser.Controller/Entities/BaseItem.cs
**Changes**
Removes `[JsonIgnore]` from above `DateLastSaved` in BaseItem.cs. This allows the property to be properly read and updated whenever media is added, or edited.
**Issues**
Fixes #2881, allowing clients to use the property reliably for detecting content updates.
> Remove JsonIgnore from the DateLastSaved property of BaseItem

- Emby.Dlna/Didl/DidlBuilder.cs
This addresses an issue where DLNA clients (VLC, Foobar) display incorrect album art for some music albums. Specifically albums that don't have folder/cover image file (i.e. a folder of mp3's) "steal" cover image from a different album, typically whichever appears first in the list.
For example, in the below folder structure, the first folder contains a folder.jpg file, but second doesn't. When viewed in VLC both albums show the image from the first folder.
Music/jazz
├── Bill Evans - Bill Evans Trio with Symphony Orchestra
│   ├── 01 - Granadas.flac
│   ├── 02 - Valse.flac
│   └── **folder.jpg**
└── David Chesky - Jazz In The New Harmonic
├── 01-Jazz in the New Harmonic.flac
└── 08-Transcendental Tripping.flac
> Fix DLNA clients displaying wrong album art.

- .vscode/extensions.json
- README.md
Add additional documentation to the project README with detailed instructions for developers on how to run the project from source code.
**Changes**
- Add [recommended extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) to VS Code configuration
- Update README with additional development documentation
**Issues**
The additional README instructions include details on new configuration introduced in #2601, so this should probably wait for that to be merged first
> Add Development Documentation To README

- Emby.Server.Implementations/EntryPoints/StartupWizard.cs
Fixes an issue where the web browser is automatically launched even if `AutoRunWebApp = false` or `NoAutoRunWebApp = true` when the server is not hosting web content.
The existing behavior was to always launch the swagger API page when `HostWebClient` was false, ignoring `AutoRunWebApp` and `NoAutoRunWebApp`
> Respect AutoRunWebApp and NoAutoRunWebApp settings when HostWebClient is false

- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
- Jellyfin.Server/Formatters/CamelCaseJsonProfileFormatter.cs
- Jellyfin.Server/Formatters/PascalCaseJsonProfileFormatter.cs
- Jellyfin.Server/Models/JsonOptions.cs
With `Accept: application/json;profile="CamelCase"`
Response:
```
{
"key1": "Value 1",
"key2": "vAlUe 2"
}
```
With `Accept: application/json` or `Accept: application/json;profile="PascalCase"`
Response:
```
{
"Key1": "Value 1",
"Key2": "vAlUe 2"
}
```
**Issues**
Fixes #2930
> Add optional camelCase formatter

- Jellyfin.Api/BaseJellyfinApiController.cs
**Changes**
Adds a `Produces` annotation to the base controller so that all endpoints are marked as returning `application/json`
**Issues**
Part of #2872
> Adds annotation for content-type of ASP.NET Web API endpoints

- Emby.Dlna/Didl/DidlBuilder.cs
**Changes**
Opening TV Shows/Next Up was throwing 'InvalidOperationException: Nullable object must have a value.'; from line 466 because IndexNumber was null. This change fixes that. I was going to add a simple null check at first, but ended up refactoring that section of the code. 
**Issues**
> Fix InvalidOperationException while browsing via DLNA client.

- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunUdpStream.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs
- Jellyfin.Server/Program.cs
- MediaBrowser.Controller/IServerApplicationHost.cs
**Changes**
This is a follow up for https://github.com/jellyfin/jellyfin/pull/2740. This change makes LiveTV restream be accessed by ffmpeg via plain HTTP regardless of secure mode settings. Without the change, when secure mode is set to "Handled by reverse proxy" and neither reverse proxy is running on same host where Jellyfin runs nor Jellyfin having a certificate set it would still fail.
Also I've made Jellyfin to always listen on `localhost` so LiveTV which needs this connection works regardless of what addresses Jellyfin is told to listen in settings.
Note that due to changing the API this would probably break plugins, so I'm not sure if it's eligible for backporting to 10.5.z releases. Maybe someone from @jellyfin/backend can tell.
**Issues**
Hopefully fixes …
> Make localhost LiveTV restreams always use plain HTTP port

- Emby.Dlna/Profiles/DefaultProfile.cs
- Emby.Dlna/Profiles/Xml/Default.xml
- Emby.Dlna/Profiles/Xml/Denon AVR.xml
- Emby.Dlna/Profiles/Xml/DirecTV HD-DVR.xml
- Emby.Dlna/Profiles/Xml/LG Smart TV.xml
- Emby.Dlna/Profiles/Xml/Linksys DMA2100.xml
- Emby.Dlna/Profiles/Xml/Marantz.xml
- Emby.Dlna/Profiles/Xml/MediaMonkey.xml
- Emby.Dlna/Profiles/Xml/Panasonic Viera.xml
- Emby.Dlna/Profiles/Xml/Popcorn Hour.xml
- Emby.Dlna/Profiles/Xml/Samsung Smart TV.xml
- Emby.Dlna/Profiles/Xml/Sharp Smart TV.xml
- Emby.Dlna/Profiles/Xml/Sony Bravia (2011).xml
- Emby.Dlna/Profiles/Xml/Sony Bravia (2012).xml
- Emby.Dlna/Profiles/Xml/Sony Bravia (2013).xml
- Emby.Dlna/Profiles/Xml/Sony Bravia (2014).xml
- Emby.Dlna/Profiles/Xml/Sony PlayStation 3.xml
- Emby.Dlna/Profiles/Xml/Sony PlayStation 4.xml
- Emby.Dlna/Profiles/Xml/WDTV Live.xml
- Emby.Dlna/Profiles/Xml/Xbox One.xml
- Emby.Dlna/Profiles/Xml/foobar2000.xml
**Changes**
Added missing colons to the default profile's ProtocolInfo string and any other profile that inherits it.
> Fix missing colons

- Emby.Server.Implementations/Configuration/ServerConfigurationManager.cs
- Emby.Server.Implementations/ServerApplicationPaths.cs
- MediaBrowser.Common/Configuration/EncodingConfigurationExtensions.cs
- MediaBrowser.Controller/IServerApplicationPaths.cs
Ensure the 'metadata' and 'transcodes' folders are created before using them.
**Changes**
The metadata folder is created at application startup and also each time the configured path is updated. The 'transcodes' folder is created each time it's value is retrieved. In the future it would be good to consolidate this logic somewhere into a single config management class, but for now this PR aims to be less disruptive by just updating existing behavior.
**Issues**
Fixes #2854
> Create Missing Data Folders

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
After the hardware decoders, final ffmpeg arguments have two spaces instead of one.
**Before**:
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -c:v h264_mmal  -i file: (etc)
```
**After**:
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -c:v h264_mmal -i file: (etc)
```
> Remove unnecessary space in hardware decoders argument for ffmpeg

- MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
- MediaBrowser.Api/Playback/Hls/HlsCodecStringFactory.cs
According to the HLS spec, these are all recommended fields a `EXT-X-STREAM-INF` should have.
[Spec](https://tools.ietf.org/html/rfc8216#section-4.3.4.2)
**Changes**
Adds CODECS field specifying what codecs the stream contains
Adds RESOLUTION field specifying what resolution the stream contains
Adds FRAME-RATE field specifying what framerate the video in the stream has
EDIT:
Move BANDWIDTH and AVERAGE-BANDWIDTH field generation to its own method
Move SUBTITLES field generation to its own method
**Issues**
#2505
> Add codecs, resolution and frame-rate fields to HLS master playlist

- Emby.Server.Implementations/Data/SqliteUserDataRepository.cs
The write lock and connection for the item repository are shared with the user data repository since they point to the same database. The item repo has responsibility for disposing these two objects, so the user data repo should not attempt to dispose them as well (which causes an exception in some scenarios). 
This is the correct way to implement the fix proposed in #2989
**Changes**
Overwrite the `Dispose()` method in the `UserDataRepository` so that is does not dispose the `WriteLock` or `WriteConnection`
**Issues**
Fix the integration tests in #2945
> Do not double dispose item repository resources

- MediaBrowser.sln
Signed-off-by: Christoph Potas <christoph286@googlemail.com>
set the correct startup project so a clean clone can be started with F5 ( as readme descripe )
**Changes**
set Jellyfin.Server as first project in sln (startup project)
**Issues**
https://github.com/jellyfin/jellyfin/issues/3042
> Jellyfin.Server as startup project

- Emby.Server.Implementations/Library/UserManager.cs
- MediaBrowser.Api/UserService.cs
- MediaBrowser.Controller/Library/IUserManager.cs
- MediaBrowser.Model/Dto/PublicUserDto.cs
**Changes**
As described in the commit message, these are the changes: this commit fixes the emby/user/public API that was returning more data than necessary. Now only the following information are returned:
- the account name
- the primary image tag
- the field hasPassword
- the field hasConfiguredPassword, useful for the first wizard only (see https://github.com/jellyfin/jellyfin/issues/880#issuecomment-465370051)
- the primary image aspect ratio
A new DTO class, PrivateUserDTO has been created, and the route has been modified in order to return that data object.
Finally, I tested it locally and nothing seems to be broken, but please check it out as I'm not a C# developer and I could have missed something!
**Issues**
Fixes #880
> Fix emby/user/public API leaking sensitive data

- Jellyfin.Server/Migrations/IMigrationRoutine.cs
- Jellyfin.Server/Migrations/MigrationRunner.cs
- Jellyfin.Server/Migrations/Routines/CreateUserLoggingConfigFile.cs
- Jellyfin.Server/Migrations/Routines/DisableTranscodingThrottling.cs
Use dependency injection to construct migration routines. This gives migration routines the flexibility to request whatever dependencies they require to execute without needing to pass the entire application host object. A migration-specific logger can also be used this way instead of re-using the one from the migration runner.
**Issues**
Addresses one issue tracked in #2538
> Use dependency injection to construct migration routines

- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/Library/Resolvers/Audio/MusicAlbumResolver.cs
- Emby.Server.Implementations/Library/Resolvers/Audio/MusicArtistResolver.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/M3UTunerHost.cs
- MediaBrowser.Api/Movies/TrailersService.cs
- MediaBrowser.Api/UserLibrary/ItemsService.cs
- MediaBrowser.Providers/Plugins/Omdb/OmdbEpisodeProvider.cs
- MediaBrowser.Providers/Plugins/Omdb/OmdbItemProvider.cs
**Changes**
Remove the functionality for injecting ILogger directly, replaces all usages with generic versions or `LoggerFactory`
> Remove Support for Injecting ILogger Directly

- MediaBrowser.MediaEncoding/Subtitles/VttWriter.cs
**Changes**
Adds a Region to the VttWriter to instruct clients where to render the subtitles.
Based on the W3C specs found here: https://www.w3.org/TR/webvtt1/#region-settings
**Issues**
Goes in tandem with https://github.com/jellyfin/jellyfin-web/pull/1209 to provide a decent display region for clients that support WebVTT.
> Add positionning cues to WebVTT writer

- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Part of #2872 
Note: This uses the API method name to generate the operationId, so the method name must be descriptive (ie: `GetById` -> `GetTaskById`)
Docs for change: https://github.com/domaindrivendev/Swashbuckle.AspNetCore#assign-explicit-operationids
> Add OperationId to SwaggerGen

- MediaBrowser.MediaEncoding/Probing/MediaStreamInfo.cs
- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
- MediaBrowser.Model/Entities/MediaStream.cs
**Changes**
* Adds `color_transfer` and `color_primaries` from ffprobe to the stream data.
* Adds the necessary `color_transfer` to detect Hybrid Log-Gamma
This effectively fixes the `video_range` detection.
**Issues**
Fixes #3110
> Parse color transfer and color primaries from ffprobe, and fix video range

- Jellyfin.Api/Auth/CustomAuthenticationHandler.cs
On a fresh setup of Jellyfin & Jellyfin Web, the setup wizard hangs and it's impossible to continue. This is caused by the request to `/Startup/User` returning an HTTP 500.
This was introduced in 53380689a. Changing the exceptions throw changed how `CustomAuthenticationHandler` processed failures.
**Changes**
Catch `AuthenticationException`s in `CustomAuthenticationHandler`.
**Issues**
~~I think this resolves #3132~~ I don't think there's an open issue for this
> Fix 500 error causing first-time setup wizard to hang

- Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
**Changes**
Do not use the developer exception page to handle server errors when the exception stack trace should be ignored. The `DeveloperExceptionPageMiddleware` logs the stack trace as part of handling the error, filling up the log with junk (i.e. stack traces for task cancelled exceptions).
> Reduce Excessive Logging From DeveloperExceptionPageMiddleware

- MediaBrowser.Providers/Tmdb/Movies/TmdbSearch.cs
**Changes**
Previosly TMDB would be queried with the raw name and always fail,
then retry with the cleaned name. Now non-word chars are always
cleaned out first.
If first query fails, retry with more aggressive cleaning.
**Issues**
> Reduce number of TMDB lookups if filenames have punctuation chars

- Dockerfile.arm
**Changes**
This command seems to inexplicably fail in Docker builds, despite working on the CLI, similar to what happened with the command directly above it in c257d6071c3a8dd141d1191062e892d912177d9a. Fix it in the same way by adding `-k`.
**Issues**
Fix nightly Docker builds.
> Add -k to keyserver curl command

- Emby.Server.Implementations/EntryPoints/UdpServerEntryPoint.cs
- Emby.Server.Implementations/IStartupOptions.cs
- Emby.Server.Implementations/Udp/UdpServer.cs
- Jellyfin.Server/StartupOptions.cs
Required when using the Docker Container in bridge mode, as currently the internal docker IP is used, which is generally not routable from other LAN devices.
**Changes**
Added configuration value to allow setting of the Address Url (returned in the Auto Discover response) from a command line parameter or environment variable.   If not set, behaviour remains unchanged.
> Allow override of address published by auto discovery

- MediaBrowser.Api/VideosService.cs
As said in https://github.com/jellyfin/jellyfin/issues/3176, merging 1 with 2 and then 2 with 1 cause a stack overflow. sorting ids first fix the problem
**Changes**
Now the list of ids to merge is sort before merging
> Order ids to merge to avoid stack overflow

- Jellyfin.Server/Middleware/ExceptionMiddleware.cs
**Changes**
Because of security reasons, exception messages should no longer get sent to the Clients, unless the server is running in Development mode. This PR adds this change only to the new ASP API endpoint.
**Issues**
Fixes #2965 (in combination with #3185 )
> Don't send Exception message in Production Environment

- MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
For reference: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.2
```
FRAME-RATE
The value is a decimal-floating-point describing the maximum frame
rate for all the video in the Variant Stream, rounded to 3 decimal
places.
```
```
RESOLUTION
The value is a decimal-resolution describing the optimal pixel
resolution at which to display all the video in the Variant
Stream.
```
**Changes**
Change `RESOLUTION` and `FRAME-RATE` field values to be represented as a number rather than a string
**Issues**
#3224
> Fix incorrect HLS master playlist fields

- Emby.Server.Implementations/Library/UserDataManager.cs
- MediaBrowser.Controller/Entities/Book.cs
**Changes**
This PR introduces the necessary changes to make jellyfin-web be able to resume books since https://github.com/jellyfin/jellyfin-web/pull/1263 is merged.
* Sets `SupportsPlayedStatus` and `SupportsPositionTicksResume` to true for books. These properties have to be true for an item to be able to store position ticks.
* Sets book's runtime ticks to 1 second. There is no cross-device way to determine the amount of pages a book has as it depends on screen resolution, font etc. Essentially jellyfin-web just reports a percentage progress through the book tied to [CFI](http://idpf.org/epub/linking/cfi/epub-cfi.html) locations.
* Excludes books from minimum resumable duration check as books don't really have a time duration and 1 second is just a mock value.
> Make books resumable

- MediaBrowser.Providers/MediaBrowser.Providers.csproj
- MediaBrowser.Providers/Plugins/TheTvdb/TvdbSeasonImageProvider.cs
**Changes**
After https://github.com/HristoKolev/TvDbSharper/issues/20 was fixed in TvDbSharper we can now ignore languages that have a null id, which is currently causing images to **not** be fetched for tvdb show meta data (currently its failing to retrieve all languages regardless if they are valid or not).
I am assuming ignoring _invalid_ languages is the right approach since why consider a language record with no id value. 
I'm unaware if this minor change warrants a test case, please let me know, and I will add one.
**Issues**
https://github.com/jellyfin/jellyfin/issues/3201
> Ignore languages with null ids when fetching images from tvdb

- Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
**Changes**
Because of security reasons, exception messages should no longer get sent to the Clients, unless the server is running in Development mode. This PR adds this change only to the old API endpoint.
**Issues**
Fixes #2965 (in combination with #3186  )
> Don't Send Exception Messages (Old API)

- Jellyfin.Api/Controllers/StartupController.cs
As requested in https://github.com/jellyfin/jellyfin/pull/3153#discussion_r433910589
Note- This makes Swagger / Redoc always point to `User` instead of `FirstUser` when `FirstUser` is expanded.
> Add second endpoint for Startup/User

- Jellyfin.Server/Migrations/Routines/MigrateActivityLogDb.cs
**Changes**
In very old versions of Emby's schema, the `UserId` field is the internal id of a user, and not a guid. This PR fixes the activity log migration for such cases, and any other unforeseen problems migrating the `UserId` field.
> Fix Activity Log Migrations for Very Old Databases

- tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
- tests/Jellyfin.Common.Tests/Jellyfin.Common.Tests.csproj
- tests/Jellyfin.Common.Tests/PasswordHashTests.cs
- tests/Jellyfin.Controller.Tests/Jellyfin.Controller.Tests.csproj
- tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTests.cs
- tests/Jellyfin.MediaEncoding.Tests/Jellyfin.MediaEncoding.Tests.csproj
- tests/Jellyfin.Model.Tests/Jellyfin.Model.Tests.csproj
- tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj
- tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj
- tests/MediaBrowser.Api.Tests/MediaBrowser.Api.Tests.csproj
**Changes**
- Enables all code analyzers mentioned in #2149 with the exception of `StyleCop` in `Jellyfin.MediaEncoding.Tests`
- Enables `TreatWarningsAsErrors` for `Jellyfin.Naming.Tests` (rest are already enabled)
**Issues**
#2149 
---
On a side note, could the markdown for the table within that issue be provided? I'd like to go through and update it. Cheers
> Enable code analyzers for tests

- Emby.Server.Implementations/HttpServer/WebSocketConnection.cs
- MediaBrowser.Common/Json/Converters/JsonNonStringKeyDictionaryConverter.cs
- MediaBrowser.Common/Json/Converters/JsonNonStringKeyDictionaryConverterFactory.cs
- MediaBrowser.Common/Json/JsonDefaults.cs
- MediaBrowser.Controller/Net/BasePeriodicWebSocketListener.cs
**Changes**
Add MessageId to all WebSocket senders.
Add JsonNonStringKeyDictionaryConverter + Factory to handle WS exceptions. Copied from api-migration branch.
**Issues**
Fixes #3251
> Add MessageId to websocket message, fix ws exception

- Jellyfin.Server/Program.cs
and return exit code 1 when argument parsing fails
> Remove code for handling single hyphen arguments

- Jellyfin.Api/Auth/BaseAuthorizationHandler.cs
- Jellyfin.Api/Auth/CustomAuthenticationHandler.cs
- Jellyfin.Api/Helpers/ClaimHelpers.cs
`#nullable enable` is not needed in every file in Jellyfin.Api as it is enabled on project level.
> Remove #nullable enable in Jellyfin.Api

- Emby.Server.Implementations/Updates/InstallationManager.cs
- MediaBrowser.Common/Plugins/BasePlugin.cs
- MediaBrowser.Common/Plugins/IPlugin.cs
- MediaBrowser.Model/Plugins/PluginInfo.cs
**Changes**
Added `CanUninstall` property to Plugin to indicate whether a plugin can be uninstalled.  If an attempt is made to uninstall a plugin with this property set to `False`, it is logged and the uninstallation does not proceed.
Current `CanUninstall` is simply a check if the Plugin Assembly path is the same as the main Jellyfin path.  This could can be changed in the future to add additional/different logic if required.
Related Web PR:   jellyfin/jellyfin-web#1464
**Issues**
Fixes #2555
> Prevent system plugins from being uninstalled

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
**Changes**
Captures a symlink for MediaBrowser.WebDashboard/jellyfin-web & removes duplicate entry.
Adds dotnet telemetry optout environment variable for vscode tasks
> .gitignore: ignore jellyfin-web symlink & .vscode: dotnet telemetry optout

- MediaBrowser.Controller/Entities/BaseItem.cs
- MediaBrowser.Controller/Entities/UserView.cs
- MediaBrowser.Controller/Entities/UserViewBuilder.cs
Fixes 
```
[2020-06-20 11:24:30.354 +03:00] [ERR] Error processing request. URL: "http://IP/jellyfin/Users/19049592d87b4ea7a149a747070f233d/Items?Fields=PrimaryImageAspectRatio%2CSortName%2CPath%2CPrimaryImageAspectRatio&ImageTypeLimit=1&ParentId=c00310d49d01f5352278e06b1b96160a&SortBy=IsFolder%2CSortName&SortOrder=Ascending"
System.ArgumentNullException: Value cannot be null. (Parameter 'factory')
at Microsoft.Extensions.Logging.LoggerFactoryExtensions.CreateLogger[T](ILoggerFactory factory)
at MediaBrowser.Controller.Entities.UserView.GetItemsInternal(InternalItemsQuery query)
at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)
at MediaBrowser.Api.UserLibrary.ItemsService.GetQueryResult(GetItems request, DtoOptions dtoOptions, User user)
at …
```
> Revert ILoggerFactory usage in BaseItem.cs

- .ci/azure-pipelines-package.yml
- .ci/azure-pipelines.yml
- deployment/Dockerfile.docker.amd64
- deployment/Dockerfile.docker.arm64
- deployment/Dockerfile.docker.armhf
- deployment/build.centos.amd64
- deployment/build.debian.amd64
- deployment/build.debian.arm64
- deployment/build.debian.armhf
- deployment/build.fedora.amd64
- deployment/build.linux.amd64
- deployment/build.macos
- deployment/build.portable
- deployment/build.ubuntu.amd64
- deployment/build.ubuntu.arm64
- deployment/build.ubuntu.armhf
- deployment/build.windows.amd64
**Changes**
Adds configuration to build packages with Azure DevOps. Identical in setup to Web, though with the server-specific tweaks applied.
Right now is configured to build off of this branch; like Web, it will be switched to `refs/heads/master` once tested.
**Issues**
N/A
>  Add Azure DevOps package builds

- Emby.Server.Implementations/Library/LibraryManager.cs
Fixes #3432
This still causes a white image, but at least scanning completes.
> catch skia errors when getting image dimensions

- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Before:
After:
Not sure why the docs say to have ordering as the former, but the new order makes more sense to me.
> Fix docs endpoint order

- Emby.Server.Implementations/Library/IgnorePatterns.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/IgnorePatternsTests.cs
Fixes #3391
Dotnet.Glob doesn't ignore if there is a trailing path in the pattern but not the test string.
> Add more ignorepatterns and tests

- Jellyfin.Api/Controllers/MediaInfoController.cs
- MediaBrowser.Api/Playback/MediaInfoService.cs
Thanks for multiple methods with identical names.
`MediaInfoService` can't be remove from `MediaBrowser.Api` until `UniversalAudioService` is migrated.
> Move MediaInfoService to Jellyfin.Api

- tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
- tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj
AutoFixture.AutoMoq and AutoFixture.Xunit2 must be updated at the same time.
> bump autofixture

- Emby.Server.Implementations/ApplicationHost.cs
- Jellyfin.Server/StartupOptions.cs
- MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Fix issue whereby `JELLYFIN_FFMPEG`  environment variable was ignored.
**Changes**
- Added ffmpeg commandline param into IConfiguration
- Updated MediaEncoder constructor to take IConfiguration instead ffmpeg path string 
- Removed custom activation for MediaEncoder
> Respect FFMpeg path passed via Environment Variable

- Emby.Dlna/Profiles/DefaultProfile.cs
- Emby.Dlna/Profiles/DenonAvrProfile.cs
- Emby.Dlna/Profiles/DirectTvProfile.cs
- Emby.Dlna/Profiles/Foobar2000Profile.cs
- Emby.Dlna/Profiles/MarantzProfile.cs
- Emby.Dlna/Profiles/MediaMonkeyProfile.cs
- Emby.Dlna/Profiles/SonyBlurayPlayer2013.cs
- Emby.Dlna/Profiles/SonyBlurayPlayer2014.cs
- Emby.Dlna/Profiles/SonyBlurayPlayer2015.cs
- Emby.Dlna/Profiles/SonyBlurayPlayer2016.cs
- MediaBrowser.Api/FilterService.cs
- MediaBrowser.Controller/Entities/BaseItem.cs
- MediaBrowser.Controller/Entities/Movies/BoxSet.cs
- MediaBrowser.Controller/Library/TVUtils.cs
- MediaBrowser.MediaEncoding/BdInfo/BdInfoExaminer.cs
- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
- MediaBrowser.Model/Dlna/MediaFormatProfileResolver.cs
- MediaBrowser.Model/Dlna/StreamInfo.cs
- MediaBrowser.Model/Querying/UpcomingEpisodesQuery.cs
- MediaBrowser.Providers/Manager/MetadataService.cs
**Changes**
Uses Array.Empty where applicable to reduce unnecessary allocations. Intentionally does not change ProviderManager, as I have another PR for that class.
> Use Array.Empty

- .ci/azure-pipelines-package.yml
- .ci/azure-pipelines.yml
**Changes**
Prevents running builds (that get skipped) in PR CI, and prevents running tests (which are irrelevant) in Merge CI. Also removes unneeded conditionals in the package stage due to this previous change.
**Issues**
N/A
> Add conditionals to root YAML definition

- MediaBrowser.Api/SyncPlay/SyncPlayService.cs
Apparently the function name matters for ServiceStack.
> Fix syncplay function name

- Emby.Server.Implementations/Session/SessionManager.cs
- Jellyfin.Server.Implementations/Users/UserManager.cs
**Changes**
Ignore case when authenticating users. This is a band-aid until collations are supported in EF Core 5.0. Also reduces log spam from EF core.
> Make User Authentication Case-insensitive and remove EF Core Log spam

- Jellyfin.Data/Jellyfin.Data.csproj
- Jellyfin.Server.Implementations/Users/UserManager.cs
- Jellyfin.Server/CoreAppHost.cs
**Changes**
Disposes of DbContexts and no longer uses lazy loading. Requires #3533 
**Issues**
Fixes #3368
> Fix EF Core Memory Leak

- Emby.Server.Implementations/EntryPoints/UdpServerEntryPoint.cs
Presently if the server cannot bind to the AutoDiscovery port (udp 7359) then the server start up will exit with a fatal error.   Since this port cannot be overridden (which would not make sense) or disabled via config, this would prevent users from running Jellyfin on a server where this port is not available or already in use (e.g. Emby running).
**Changes**
Handle exception trying to bind to udp 7359 and log as warning.
> Prevent failure to bind to Auto Discover port being a fatal error

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Transcoding of audio files crashes with a nullpointer exception in GetHardwareAcceleratedVideoDecoder because there's no videostream available.
This pr moves the videostream null check to the start of GetHardwareAcceleratedVideoDecoder and reorganizes the logic in the beginning of the method a little.    
The audio file transcoding works fine is 10.5.5. The bug is a regression
> Fix audio file transcoding.

- Jellyfin.Server/Middleware/ResponseTimeMiddleware.cs
- Jellyfin.Server/Startup.cs
- MediaBrowser.Model/Configuration/ServerConfiguration.cs
Adds `X-Response-Time-ms` header with the response time of the server in ms and log a warning if the response was slower than a configurable threshold (default: 500ms)
> Add X-Response-Time-ms header and log slow server response time (Jellyfin.Api)

- MediaBrowser.Providers/Plugins/TheTvdb/TvdbClientManager.cs
- MediaBrowser.Providers/Plugins/TheTvdb/TvdbSeasonImageProvider.cs
- MediaBrowser.Providers/Plugins/TheTvdb/TvdbSeriesImageProvider.cs
- MediaBrowser.Providers/Plugins/TheTvdb/TvdbSeriesProvider.cs
- MediaBrowser.Providers/Plugins/TheTvdb/TvdbUtils.cs
**Changes**
Use the `/series/{id}/images` endpoint to get the available image types eg. poster, banners to avoid making a lot of unnecessary requests that result in exceptions being thrown.
Also fix the bad banner url in the series provider.
> TVDB: Fetch image keytypes before querying images

- Emby.Server.Implementations/TV/TVSeriesManager.cs
For reasons unknown, an episode can be matched to a series but `SeriesPresentationUniqueKey` can still be `null` if it isn't completely finished.
When fetching Next Up episodes it uses the unique key to fetch episodes, but it doesn't filter null values, so it will sometimes fetch something random as shown below...
> Only fetch Next Up for episodes that have been fully matched

- MediaBrowser.Api/System/ActivityLogService.cs
Fixes Dashboard Activity / Alerts
The UserId field is now `Guid.Empty` instead of null
Previously:
```c#
if (hasUserId.HasValue)
{
if (hasUserId.Value)
{
whereClauses.Add("UserId not null");
}
else
{
whereClauses.Add("UserId is null");
}
}
```
> Add UserId filter to ActivityLog Entries endpoint

- .ci/azure-pipelines-package.yml
**Changes**
Add NuGet publishing step to the tag branch CI to automatically push these. Untested with no way to test until release; if it borks, I'll do it manually and we can revisit, but it seems quite simple.
**Issues**
N/A
> Add NuGet publish step to tag CI

- debian/control
- deployment/build.windows.amd64
- windows/build-jellyfin.ps1
**Changes**
- ~Bump the minimun required `jellyfin-ffmpeg` version to [4.3.1-1](https://github.com/jellyfin/jellyfin-ffmpeg/pull/46) since the `vpp_qsv` filter in ffmpeg 4.2.x is buggy~
~and VP8/VP9 decoders in QSV/NVDEC is avaliable since ffmpeg 4.3.~
- Utilize jellyfin-ffmpeg for portable x64.
> Bump the minimun required jellyfin-ffmpeg version

- debian/changelog
- debian/control
**Changes**
Fix the bad dependencies in Debuntu that caused `apt -f install` to be required while upgrading from <10.6.0 to 10.6.0-1. This was used to build the 10.6.0-2 packages which are now live, so the change is moot now, but I've also included a removal of the legacy Emby `Conflicts` entries too since we're well past that now.
**Issues**
N/A
> Fix bad Debuntu dependencies

- Jellyfin.Api/Controllers/ConfigurationController.cs
- Jellyfin.Api/Controllers/PluginsController.cs
- MediaBrowser.Common/Json/Converters/JsonDoubleConverter.cs
- MediaBrowser.Common/Json/JsonDefaults.cs
- MediaBrowser.Model/Configuration/BaseApplicationConfiguration.cs
**Changes**
During a shot test of the new Api endpoints, I discovered some minor parsing errors:
- The web client returns doubles quoted as a string (eg. "2.1") which `System.Text.Json` can't parse:
▶ This PR adds a custom Json converter for `double` like the ones already existing for `int` and `long`.
- If the web client doesn't return a value for `PreviousVersionStr`, parsing `null` to `Version` would fail:
▶ This PR adds handling for null values.
- Some controllers deserialize the request body in the functions. The conversion of quoted numbers would fail because the converters mentioned above are missing:
▶ This PR adds the converters as JsonOptions
> Fix value parsing in Jellyfin.Api

- MediaBrowser.Providers/Manager/ProviderManager.cs
- MediaBrowser.Providers/TV/SeriesMetadataService.cs
**Changes**
If the (tvdb) lookup fails (due to a bad id in an nfo file for example), then
we have no indication of which directory failed, so the user can not
fix the problem.
Now we include the path in the logger error message such as:
```
MediaBrowser.Providers.TV.SeriesMetadataService: Error in
DummySeasonProvider for /media/x/y/z
```
and
```
MediaBrowser.Providers.Manager.ProviderManager:
TvdbSeriesImageProvider failed in GetImageInfos for type Series for
/media/x/y/z
```
**Issues**
I did not raise an issue (or add to Contributors) since the change is minor.
The problem occurred for me since my nfo file had been written referencing
a series that had later been removed from tvdb.
> tvdb: Log path on lookup errors

- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
**Changes**
When determining the protocol of a subtitle track during encoding, determine the subtitle's protocol from its path instead of using the protocol of the main file. This fixes playback of subtitles with a different protocol than the main media file, e.g. locally stored SRT subtitles with the File protocol and STRM main media files with the HTTP protocol.
**Issues**
Fixes #2543
> Fix support for mixed-protocol subtitles

- debian/conf/jellyfin
fixes a typo in the args passed to the jellyfin executable and adds the correct flag to the variable that disables the web client.
> fix typo in debian's config file

- Emby.Server.Implementations/ApplicationHost.cs
- Jellyfin.Server.Implementations/Users/DefaultPasswordResetProvider.cs
- Jellyfin.Server.Implementations/Users/UserManager.cs
- MediaBrowser.Controller/Library/IUserManager.cs
**Changes**
Remove the (I)UserManager.AddParts method. This method is an anti-pattern, as the class's state should be initialized entirely through Dependency Injection when possible. This also is necessary to allow hot-loading of plugins in the future.
> Remove UserManager.AddParts

- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
**Changes**
When it is UTF-16BE or UTF-16LE, we must not specify character encoding.
Previously, the jellyfin didn't specify when it is in UPPERCASE (by Pull-Request #1540) but we should not specify it even when it is lowercase, too.
This patch fixes the issue coming from the behaviour by making it not to specify even it is in lowercase.
**Issues**
Fixes #2859
> Fix SAMI UTF-16 Encoding Bug

- MediaBrowser.Model/Entities/MediaStream.cs
`string.Join(Char, String[])` was added in .NET Standard 2.1. `MediaBrowser.Model` also targets 2.0 so it can't use this method.
> Fixed compilation error on master.

- MediaBrowser.Providers/Plugins/AudioDb/Plugin.cs
- MediaBrowser.Providers/Plugins/MusicBrainz/Plugin.cs
- MediaBrowser.Providers/Plugins/Omdb/Plugin.cs
- MediaBrowser.Providers/Plugins/TheTvdb/Plugin.cs
Fixes #3653
Sets the plugin configuration file to be the future namespace
Note: Plugins won't save correctly until #3634 is merged
> Force plugin config location

- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
**Changes**
Fixes regression introduced by #3521
**Issues**
```csharp
[2020-07-25 09:34:12.790 +00:00] [ERR] [71] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://10.79.0.125:8096/Videos/b886d888-2eac-d1cb-732d-dfde121feb39/b886d8882eacd1cb732ddfde121feb39/Subtitles/2/0/Stream.ass"
System.NullReferenceException: Object reference not set to an instance of an object.
at Emby.Server.Implementations.Library.MediaSourceManager.GetPathProtocol(String path)
at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken)
at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseIt …
```
> Fix embedded subtitles

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
I am a macOS user and I am glad that **Jellyfin** supports **videotoolbox** in version 10.6.
But I found that **Jellyfin** cannot use **videotoolbox** for hardware decoding.
This is caused by a missing parameter **-hwaccel**  in **ffmpeg**.
I tried to fix this problem and tested it. 
It works now.
> Fix the problem that hardware decoding cannot be used on macOS.

- .ci/azure-pipelines-package.yml
**Changes**
The quoting as-is was broken and would result in a junk output. This way, the proper value is obtained.
**Issues**
Fixes #3723
> Flip quoting in variable set command

- Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
- Jellyfin.Drawing.Skia/SkiaEncoder.cs
**Changes**
PERFORMANCE: Updates BlurHashSharp to 1.1.0 and forces a max size of the image pre-hash to be 128x128 (aspect ratio preserved).
With this change encoding a 4K image takes ~0.05s as opposed to the previous 1.6s. See https://github.com/Bond-009/BlurHashSharp/pull/2 for benchmarks.
> Update BlurHashSharp and set max size to 128x128

- Jellyfin.Server.Implementations/JellyfinDbProvider.cs
- Jellyfin.Server/CoreAppHost.cs
**Changes**
Removed `JellyfinDb` from the DI container for now. Registering Transient instances that implement IDisposable and then using them in the root scope is a big no-no. They will never be GC'd until the container or scope is disposed, which will only happen on shutdown.
An alternative solution is to create a Scope whenever we need the context, but the factory pattern is cleaner.
**DISCLAIMER**: I haven't actually been able to reproduce the leak, but based on memory snapshots and research it seems like the most likely scenario.
Sources:
- https://github.com/aspnet/DependencyInjection/issues/456
- https://github.com/dotnet/runtime/issues/36491
- https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#idisposable-guidance-for-transient-and-sh …
> Fix DI memory leak

- README.md
Small change to the readme, the `--nowebcontent` flag does not work, the correct flag seems to be `--nowebclient`
> Change 'nowebcontent' flag to 'nowebclient' flag in readme

- MediaBrowser.Providers/Plugins/Tmdb/Models/Movies/MovieResult.cs
**Changes**
Avengers: Endgame made too much money!!! When deserializing the response, the revenue was too large for an int. Changed it (and Budget) too a long instead.
> TMDb: Change Budget and Revenue to long to avoid overflow

- Emby.Server.Implementations/Emby.Server.Implementations.csproj
**Changes**
Updates to a newer version of Jellyfin.XMLTV. 
**Issues**
To be honest, I'm not sure, but there were reasons here:
https://github.com/jellyfin/Jellyfin.XmlTv/pull/5
Edit: Fixes https://github.com/jellyfin/jellyfin-web/issues/1621
> Update to newer Jellyfin.XMLTV

- Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
- Jellyfin.Drawing.Skia/SkiaEncoder.cs
- Jellyfin.Drawing.Skia/StripCollageBuilder.cs
**Changes**
Updates SkiaSharp to the latest version and replaces the resizing code.
Clearly the EncodeImage function needs to be rewritten to do all it's work on one target surface, instead of all the magic with tons of different bitmaps. And there is some copying of images going on in the current code.
> Updated SkiaSharp to 2.80.1 and replace resize code to fix bad quality

- MediaBrowser.Providers/Manager/ProviderManager.cs
**Changes**
Changed the logging level for the refresh events to Debug. It's very spammy when scanning and ultimately useless information since it's just logging GUIDs.
Example:
[logspam.txt](https://github.com/jellyfin/jellyfin/files/5020645/logspam.txt)
> Change OnRefreshStart and OnRefreshComplete logging levels to debug

- Jellyfin.Server.Implementations/Activity/ActivityManager.cs
**Changes**
Uses synchronous Add() and asynchronous context creation.
> Minor fixes to ActivityManager

- Jellyfin.Api/Controllers/LibraryController.cs
- Jellyfin.Api/Controllers/RemoteImageController.cs
- MediaBrowser.Common/Json/Converters/JsonDoubleConverter.cs
**RemoteImageController**
- Fix routes
- Fix authentication
**JsonDoubleConverter**
- Fix double -> json serialization (don't quote double; web client doesn't parse quoted doubles because the old api returned the number without quotes)
**LibraryController**
- Use different method to return a physical file
> Small fix to api-migration

- deployment/Dockerfile.debian.amd64
- deployment/Dockerfile.debian.arm64
- deployment/Dockerfile.debian.armhf
- deployment/Dockerfile.linux.amd64
- deployment/Dockerfile.macos
- deployment/Dockerfile.portable
- deployment/Dockerfile.ubuntu.amd64
- deployment/Dockerfile.ubuntu.arm64
- deployment/Dockerfile.ubuntu.armhf
- deployment/Dockerfile.windows.amd64
**Changes**
Bump the manually-downloaded .NET Core SDK version from 3.1.100 to 3.1.302. This includes numerous bugfixes to the .NET SDK.
**Issues**
Fixes #3558
> Bump to .NET Core SDK 3.1.302

- MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
**Changes**
> As of December 16, 2019, we have disabled the API rate limiting.
https://developers.themoviedb.org/3/getting-started/request-rate-limiting
We could keep it just to be nice, but I am assuming they will let us know if it becomes too much. They removed it for a reason, so why limit ourselves. It's unlikely we will do that many requests since we are still very limited by the speed of FFProbe.
> Remove rate limit from TMDb provider

- Emby.Server.Implementations/Library/LibraryManager.cs
**Changes**
Changed to MemoryCache.Set since SetValue does not flush automatically. An entry is only added to the MemoryCache when the entry is disposed, which Set does for us. No BaseItems were ever cached 🤣 
I scanned my TV shows with "Refresh all metadata" for 19 minutes and got the following results:
Memory allocations _before_ the change:
Memory allocations _after_ the change
> Fix BaseItems not being cached in-memory

- Jellyfin.Api/Controllers/VideosController.cs
The split function does only works correctly if the id given is the one of the primary version, this causes that splitting through the web ends with the blue bubble in the top left of the poster showing how many versions are, even if they are not grouped. As can be seen here
Forcing to split always the primary version fix the problem
Changes
Force to split always the primary version
@cvium
> Fix Split versions

- Jellyfin.Api/Controllers/DynamicHlsController.cs
**Changes**
Avoid including stray comma when only audio is streamed. Previously Chromecast and possibly other strict HLS clients treat audio only streams as video.
> Avoid including stray commas in HLS codecs field

- .vscode/launch.json
- README.md
Some links linking to jellyfin-web builds in the README are not working, so I fixed those. I also added a note about
how the setup wizard can only run if the web client is hosted with with the server
> Fix README links and note about setup wizard

- Emby.Server.Implementations/LiveTv/TunerHosts/BaseTunerHost.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/M3UTunerHost.cs
**Changes**
Replaces IJsonSerializer with System.Text.Json and uses MemoryCache in BaseTunerHost.
> Clean up TunerHost Classes

- MediaBrowser.Common/Json/Converters/JsonInt64Converter.cs
Old api returned int64 not stringified, return to previous implementation.
> Return int64 in json as number

- Jellyfin.Api/Controllers/AudioController.cs
- Jellyfin.Api/Controllers/LiveTvController.cs
- Jellyfin.Api/Controllers/RemoteImageController.cs
- Jellyfin.Api/Controllers/VideosController.cs
IHttpClient -> IHttpClientFactory
unsure if `using var client = _httpClientFactory.CreateClient();`  is correct with new IHttpClientFactory.
> Remove IHttpClient from Jellyfin.Api

- Jellyfin.Api/Controllers/DynamicHlsController.cs
**Changes**
- Increase the max muxing queue size to 2048 for ffmpeg.
This can alleviate the situation that the default value of 128 is not enough.
**Issues**
https://github.com/jellyfin/jellyfin/issues/3960
https://github.com/jellyfin/jellyfin/issues/3780
https://github.com/jellyfin/jellyfin/issues/3640
https://github.com/jellyfin/jellyfin/issues/3335
https://github.com/jellyfin/jellyfin/issues/3090
> Increase the max muxing queue size for ffmpeg

- .ci/azure-pipelines-package.yml
- Emby.Naming/Emby.Naming.csproj
- Jellyfin.Data/Jellyfin.Data.csproj
- MediaBrowser.Common/MediaBrowser.Common.csproj
- MediaBrowser.Controller/MediaBrowser.Controller.csproj
- MediaBrowser.Model/MediaBrowser.Model.csproj
- bump_version
**Changes**
With this PR merged, every commit to master builds unstable nuget packages. They don't get pushed to any Nuget feeds. To achive this, I added the `VersionPrefix` property to every .csproj file which outputs Nuget packages and integrated the version number into the bump_version script.
I changed the Nuget pack CI task to the .Net Core pack Task because of this note in the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml#package-versioning)
> Please note that DotNetCore and DotNetStandard packages should be packaged with the DotNetCoreCLI@2 task to avoid System.InvalidCastExceptions. See the .NET Core CLI task for more details.
**Issues**
This allows for easier plugin development before we publish the stable version …
> Build Unstable NuGet packages

- Jellyfin.Server.Implementations/Users/UserManager.cs
- Jellyfin.Server/Migrations/Routines/MigrateUserDb.cs
- MediaBrowser.Model/Users/UserPolicy.cs
Fixes #4000
Previously we were storing the ID however the API received it as.
This will require re-saving access permissions, which shouldn't be an issue as they don't currently work on unstable
> Fix partial library and channel access

- fedora/jellyfin.spec
**Changes**
In order for the jellyfin meta-package to exist, there has to be an empty
%files section for it.
**Issues**
Fixes: #3701
> Add an empty %files section to main package

- Jellyfin.Api/Controllers/ItemsController.cs
**Changes**
This change makes it so that items inside an enabled channel plugin (dashboard->user->access) are also enabled and will be visible by the user.
Without this change, the only Channel (plugin, not Live TV) permission that works is "Enable All Channels", so individual channel plugin selections have no effect.
Must be tested at the individual item level, as top-level folders still show but are not populated with any items.
**Issues**
Fixes #2858
> [Permissions] Fix for individual channel plugins #2858

- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
**Changes**
Changed `X-Emby-Token` header to `X-Emby-Authorization` because the former prevents calling the auth endpoint from generated clients and Swagger UI (due to no token being available)
**Issues**
> Fix wrong OpenAPI auth header value

- Emby.Server.Implementations/ApplicationHost.cs
- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
- Jellyfin.Server/Startup.cs
- MediaBrowser.Common/IApplicationHost.cs
**Changes**
To allow plugins to register their own ASP.NET Web Api endpoints, we need to register each assembly in the `MvcBuilder`.
~~However, this is currently not possible, as `applicationHost.Plugins` doesn't contain the plugins. They get loaded after `Startup.ConfigureServices` ran.
Can we load the plugins earlier? I tried to move some things around (calling [this line](https://github.com/Ullmie02/jellyfin/blob/98d1d2325d515ef0e6bd0a59c961967e9b5224be/Jellyfin.Server/Program.cs#L188) before calling [this line](https://github.com/Ullmie02/jellyfin/blob/98d1d2325d515ef0e6bd0a59c961967e9b5224be/Jellyfin.Server/Program.cs#L184)) but `InitializeServices` needs the `appHost.ServiceProvider` which we get from the WebHostBuilder.~~
> Allow plugins to define their own api endpoints

- MediaBrowser.Controller/Entities/BaseItem.cs
- MediaBrowser.Controller/Providers/ItemLookupInfo.cs
This is important for the Shoko Anime Metadata provider plugin. (Since it's API give metadata based on filename/path).
**Changes**
Adds the Path field from BaseItem to the ItemLookupInfo class.
Helps with this: https://features.jellyfin.org/posts/244/shoko-anime-support
> Add the item path to the ItemLookupInfo class

- .ci/azure-pipelines-abi.yml
- .ci/azure-pipelines-package.yml
This is for the time being the way to go I think. it should start producing successful builds and so the compat checks should start working again.
@joshuaboniface Thoughts?
> Add nohup and continueOnError to the Collect Artifacts task

- .ci/azure-pipelines-package.yml
- .ci/azure-pipelines.yml
- Emby.Naming/Emby.Naming.csproj
- Jellyfin.Data/Jellyfin.Data.csproj
- MediaBrowser.Common/MediaBrowser.Common.csproj
- MediaBrowser.Controller/MediaBrowser.Controller.csproj
- MediaBrowser.Model/MediaBrowser.Model.csproj
Also adds SourceLink support and symbols that are pushed to Nuget.
Add symbols to main nuget packages for unstable builds (Azure Artifacts does not support symbols outside of the main package)
SourceLink will enable stepping during debugging.
> Fixes for CI Nuget package pushing and CI triggers

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
- debian/rules
- deployment/Dockerfile.docker.amd64
- deployment/Dockerfile.docker.arm64
- deployment/Dockerfile.docker.armhf
- deployment/build.linux.amd64
- deployment/build.macos
- deployment/build.portable
- deployment/build.windows.amd64
- fedora/jellyfin.spec
- windows/build-jellyfin.ps1
I left `GenerateDocumentationFile=False`  in `.ci/azure-pipelines-test.yml`
Needed because the openapi docs use the xml docs.
> Include xml docs when publishing

- CONTRIBUTORS.md
- MediaBrowser.Providers/Plugins/TheTvdb/TvdbEpisodeProvider.cs
**Changes**
Add check for "absolute" order and set IndexNumber to TVDBs AbsoluteNumber.
From what I've seen AbsoluteNumber can be either null or 0 on TVDB, both should be considered invalid (there are some shows where all episodes have their absolute number set to 0). I think in that case the best action is to leave it at the default id.IndexNumber that Jellyfin presumably got from parsing the filename.
**Issues**
addresses #3062
> Fix TVDB plugin not handling absolute display order

- Jellyfin.Api/Helpers/StreamingHelpers.cs
The Dlna PlayTo device controller includes the flag DlnaHeaders = true.
However, dlna headers are only included if params are passed, or the header GetContentFeatures.DLNA.ORG is included from the device.
> Fix for #4059

- Emby.Dlna/DlnaManager.cs
The web interface states under dlna profile identification:- "A case-insensitive substring or regex expression."
However, only a case sensitive reg expression test is only performed.
This pr corrects this, allowing case sensitive regex expressions or case-insensitive substring.
> Fix for #4060

- Emby.Dlna/DlnaManager.cs
- MediaBrowser.Model/Dlna/DeviceIdentification.cs
Removed DeviceIdentification.DeviceDescription property - as the field is never populated.
The is no property allocation in DeviceInfo.ToDeviceIdentification() - but were still checking its contents for a valid value in dlnamanager.
I have checked that it isn't a bug in deviceInfo - but there is nothing that could be allocated to this property.
> Simplified Code: Removed code which was never used.

- Emby.Dlna/DlnaManager.cs
Bug : If you are running under a matching dlna profile and connect to the dlna server - it uses your profile for the device description - changing the dlna's server's name to your profile's friendly one.
> Bug Fix : DLNA Server advertising

- Emby.Server.Implementations/HttpServer/Security/SessionContext.cs
- Jellyfin.Api/Auth/BaseAuthorizationHandler.cs
- Jellyfin.Api/Controllers/MediaInfoController.cs
- Jellyfin.Api/Controllers/SystemController.cs
- Jellyfin.Api/Controllers/UniversalAudioController.cs
- Jellyfin.Api/Controllers/UserController.cs
- Jellyfin.Api/Helpers/DynamicHlsHelper.cs
- Jellyfin.Api/Helpers/MediaInfoHelper.cs
- Jellyfin.Api/Helpers/RequestHelpers.cs
- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
- Jellyfin.Server/Middleware/IpBasedAccessValidationMiddleware.cs
- Jellyfin.Server/Middleware/ResponseTimeMiddleware.cs
- Jellyfin.Server/Startup.cs
- MediaBrowser.Common/Extensions/HttpContextExtensions.cs
- MediaBrowser.Model/Configuration/ServerConfiguration.cs
For X-Forwarded-For to make sense it must be configured with a list of known proxies.
> Add Known Proxies to system configuration

- Emby.Server.Implementations/ConfigurationOptions.cs
Change the default value for the configuration option PlaylistsAllowDuplicatesKey to False so that playlists do not allow duplicates by default.
**Changes**
Toggled default value in ConfigurationOptions.cs for this setting to False
**Issues**
N/A
> Change default value for allow duplicates in playlist option to False

- Jellyfin.Server/Program.cs
Users are dumb (read: me dumb) and dotnet is very lenient at times. On Windows `/tmp/test` becomes `C:\tmp\test` and either path is apparently working just fine in `System.IO.Path`, but when you start using `Path.Combine` it becomes a jumbled mess of path formatting.
> Normalize application paths

- CONTRIBUTORS.md
- Emby.Drawing/ImageProcessor.cs
This PR fixes a small copy-paste issue.
> Fix parameters validation in ImageProcessor.GetCachePath

- Jellyfin.Api/Controllers/VideosController.cs
**Changes**
`GetVideoStream_2` and `HeadVideoStream_2` didn't seem really fitting, so I gave them more descriptive names
> More expressive names for the VideoStream API

- CONTRIBUTORS.md
- Emby.Dlna/PlayTo/PlayToController.cs
- Emby.Server.Implementations/Session/SessionManager.cs
- Jellyfin.Api/Controllers/SessionController.cs
- MediaBrowser.Model/Session/GeneralCommand.cs
**Changes**
The GeneralCommand adds the type of the send command in the "Name" field. This PR changes that field to use the GeneralCommandType instead of a string. This will result in the GeneralCommandType being included in the OpenAPI JSON so the apiclients can use that information.
**Issues**
- Mentioned in #4029
> Use GeneralCommandType enum in GeneralCommand

- Jellyfin.Api/Controllers/ItemLookupController.cs
Route parameter names must match function arg name.
> Fix Identify by renaming route parameter to match function argument

- Emby.Server.Implementations/Dto/DtoService.cs
**Changes**
Added the series primary image aspect ratio when using it as a placeholder for episodes and seasons.
**BEFORE**
**AFTER**
> Add series image aspect ratio when ep/season is missing an image

- Emby.Dlna/Server/DescriptionXmlBuilder.cs
The dlna server used the DLNA base url functionality within its descriptions, enabling shorter url's to be used within it xml description.
However, it looks like this shorting of service urls is not supported (at least in UPnP Tools - which I have to assume is correct).
The result is that services cannot be parsed. eg, **Look at the serviceUrl** - BaseUrl is set to Jellyfin/
Before fix:
After fix: (DescriptionXMLBuilder.cs BuildUrl (270))
> Fix for #4161: BaseUrl in DLNA

- Emby.Dlna/PlayTo/PlayToController.cs
It is possible for _mediaSourceManager to have a null value. (ParseFromUrl creates new streams and only assigns an ItemId.)
The calling code can handle a null response.
> Null Pointer Fix : PlayToController.cs

- Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
When we can determine that the number of live streams will exceed the number of tuners available, prior to attempting to connect to the device, then throw a LiveTvConflictException to expedite the transfer to another host.
**Changes**
Copied logic from M3UTunerHost.GetChannelStream; the same logic applies here.
**Issues**
Unsure if this resolves an outstanding reported issue.
> HDHomeRun: Preemptively throw a LiveTvConflictException

- MediaBrowser.Providers/Plugins/TheTvdb/TvdbEpisodeImageProvider.cs
Depending on the TVDB data for a series / episode, this fixes the following error during library scans:
```
[2020-09-27 15:54:47.517 -07:00] [ERR] [10] MediaBrowser.Providers.Manager.ProviderManager: "TvdbEpisodeImageProvider" failed in GetImageInfos for type "Episode" at "%xyz%"
System.InvalidOperationException: Nullable object must have a value.
at System.Nullable`1.get_Value()
at MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken) in C:\Programming\jellyfin\MediaBrowser.Providers\Plugins\TheTvdb\TvdbEpisodeImageProvider.cs:line 60
at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, …
```
> Fix invalid operation exception in TvdbEpisodeImageProvider.GetImages

- MediaBrowser.Controller/Providers/DirectoryService.cs
I'm working on making the scanner / metadata refresh run multiple at once. One issue I ran into is `DirectoryService`'s cache dictionaries. Errors like this would show up since it's not thread safe:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
at MediaBrowser.Controller.Providers.DirectoryService.GetFile(String path) in C:\Programming\jellyfin\MediaBrowser.Controller\Providers\DirectoryService.cs:line 60
at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService) in …
```
> Use ConcurrentDictionary's in DirectoryService

- MediaBrowser.Common/Json/Converters/JsonNullableStructConverter.cs
- MediaBrowser.Common/Json/Converters/JsonNullableStructConverterFactory.cs
- MediaBrowser.Common/Json/JsonDefaults.cs
Use factory instead of manually adding
Call JsonSerializer instead of passing serializer through constructor
> Properly handle null structs in json

- .ci/azure-pipelines-package.yml
- .ci/azure-pipelines.yml
This makes sure to run a limited Test run for master commits and tagged released.
Alright so this publishes the file to the repository server.
This will have the file end up in `/srv/repository/incoming/azure/$(Build.BuildNumber)/openapi.json`
> Publish OpenAPI spec for master and tagged releases

- Jellyfin.Server.Implementations/Users/InvalidAuthProvider.cs
The invalid auth provider shouldn't be enabled and judging by this line https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Server.Implementations/Users/UserManager.cs#L784, it should be fine to disable it.
**Issues**
- Fixes https://github.com/jellyfin/jellyfin/issues/4099
> Disable invalid auth provider

- MediaBrowser.Model/Dlna/StreamBuilder.cs
Some more logging in the stream builder, makes it easier for me to debug profile/codec issues on the Android side in the future.
> Log stream type and codec for missing direct play profile

- CONTRIBUTORS.md
- Emby.Dlna/PlayTo/PlayToManager.cs
- Jellyfin.Api/Controllers/SessionController.cs
- Jellyfin.Api/ModelBinders/CommaDelimitedArrayModelBinder.cs
- Jellyfin.Api/ModelBinders/CommaDelimitedArrayModelBinderProvider.cs
- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
- MediaBrowser.Controller/Session/SessionInfo.cs
- MediaBrowser.Model/Session/ClientCapabilities.cs
- tests/Jellyfin.Api.Tests/ModelBinders/CommaDelimitedArrayModelBinderTests.cs
- tests/Jellyfin.Api.Tests/ModelBinders/TestType.cs
This PR converts `supportedCommands` strings to enums as part of #4214.
There is a **breaking change**: Before my changes one could pass a comma separated list of `supportedCommands` to the `PostCapabilities()` function in the `SessionController`. Because the `supportedCommands` is an array of enums this is no longer possible. See below how ASP.NET Core handles an array of enums as a query parameter:
- Example request URL before: `https://example.com/Sessions/Capabilities?supportedCommands=Mute,Unmute`
- Example request URL 1 after: `https://example.com/Sessions/Capabilities?supportedCommands=Mute&supportedCommands=Unmute`
- Example request URL 2 after: `https://example.com/Sessions/Capabilities?supportedCommands[0]=Mute&supportedCommands[1]=Unmute`
There are ways to retain the old …
> Convert supportedCommands strings to enums

- Jellyfin.Server/Middleware/ExceptionMiddleware.cs
Pre-API migration it was changed in 10.6 to return 403, but this was lost in translation...
> SecurityException should return 403

- MediaBrowser.Providers/Manager/ProviderManager.cs
At some point jellyfin downloaded a "poster" that is actually an xml file and ran into trouble getting the image dimensions:
```
[2020-09-27 14:40:58.006 -07:00] [ERR] [47] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "C:\Users\Gary\AppData\Local\jellyfin\metadata\library\ba\ba96d5eae180f07a89aee79d69c228f0\poster.xml"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
at Jellyfin.Drawing.Skia.SkiaHelper.EnsureSuccess(SKCodecResult result) in C:\Programming\jellyfin\Jellyfin.Drawing.Skia\SkiaHelper.cs:line 21
at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path) in C:\Programming\jellyfin\Jellyfin.Drawing.Skia\SkiaEncoder.cs:line 184
at …
```
> Check response status code before saving images

- Emby.Dlna/PlayTo/PlayToController.cs
- Emby.Server.Implementations/EntryPoints/LibraryChangedNotifier.cs
- Emby.Server.Implementations/EntryPoints/RecordingNotifier.cs
- Emby.Server.Implementations/EntryPoints/UserDataChangeNotifier.cs
- Emby.Server.Implementations/HttpServer/WebSocketConnection.cs
- Emby.Server.Implementations/Session/SessionManager.cs
- Emby.Server.Implementations/Session/SessionWebSocketListener.cs
- Emby.Server.Implementations/Session/WebSocketController.cs
- Jellyfin.Api/WebSocketListeners/ActivityLogWebSocketListener.cs
- Jellyfin.Api/WebSocketListeners/ScheduledTasksWebSocketListener.cs
- Jellyfin.Api/WebSocketListeners/SessionInfoWebSocketListener.cs
- Jellyfin.Server.Implementations/Events/Consumers/System/TaskCompletedNotifier.cs
- Jellyfin.Server.Implementations/Events/Consumers/Updates/PluginInstallationCancelledNotifier.cs
- Jellyfin.Server.Implementations/Events/Consumers/Updates/PluginInstallationFailedNotifier.cs
- Jellyfin.Server.Implementations/Events/Consumers/Updates/PluginInstalledNotifier.cs
- Jellyfin.Server.Implementations/Events/Consumers/Updates/PluginInstallingNotifier.cs
- Jellyfin.Server.Implementations/Events/Consumers/Updates/PluginUninstalledNotifier.cs
- Jellyfin.Server.Implementations/Events/Consumers/Users/UserDeletedNotifier.cs
- Jellyfin.Server.Implementations/Events/Consumers/Users/UserUpdatedNotifier.cs
- MediaBrowser.Controller/Net/BasePeriodicWebSocketListener.cs
- MediaBrowser.Controller/Session/ISessionController.cs
- MediaBrowser.Controller/Session/ISessionManager.cs
- MediaBrowser.Model/Net/WebSocketMessage.cs
- MediaBrowser.Model/Session/SessionMessageType.cs
While working on the apiclient I needed a list of all websocket message types and found out the server uses strings for those everywhere. I changed it to use an enum to make it easier to see all used types.
**Changes**
- Added `SessionMessageType` enum for incoming and outgoing websocket message types
- Fixed an issue where sometimes the `PlayState` command would use `Playstate`
- Fixed PluginUninstalledNotifier using the wrong type (`PluginUninstalled` instead of `PackageUninstalled`)
Changes should be backwards compatible and confirmed working by running web:master in 2 browsers and using the "play to" feature to connect them. Inspecting all WebSocket messages everything worked fine.
**Issues**
I guess it's part of #4029
> Use enum for WebSocket message types

- .ci/azure-pipelines-api-client.yml
- apiclient/templates/typescript/axios/generate.sh
- apiclient/templates/typescript/axios/stable.sh
- apiclient/templates/typescript/axios/unstable.sh
**Changes**
1. Replace the separate stable/unstable scripts with a single script and
handle the difference with argument parsing.
2. Unify the calls and pass the Azure arguments in on the CLI.
**Issues**
Fixes bug from #4070
> Improve handling of apiclient generator

- Jellyfin.Server.Implementations/Migrations/20201004171403_AddMaxActiveSessions.cs
- Jellyfin.Server.Implementations/Migrations/JellyfinDbModelSnapshot.cs
**Changes**
Fixes a bad assumption with the previous migration.
WARNING: THIS WILL BREAK THE DB FOR ANYONE WHO DEPLOYED THE LAST FEW UNSTABLE RELEASES THAT APPLIED THE MIGRATION, i.e. any since #4269. To fix it, because of sqlite's stupidity, you have to drop the whole table and recreate it. Annoying, I know. Here's how to fix it:
1. Go to wherever `jellyfin.db` is located (e.g. `/var/lib/jellyfin/data`).
2. Stop Jellyfin processes.
3. Open the database in sqlite3 (mind your permissions!): `sudo -u jellyfin sqlite3 jellyfin.db`
4. Run the following to dump the `Users` table:
```
.output jellyfin-users.tmp.sql
.dump Users
.quit
```
5. Edit the line (33 is the line number):
```
33 , "MaxActiveSessions" INTEGER NULL);
```
to
```
33 , "MaxActiveSessions" INTEGER NOT NULL);
```
6. Re-enter …
> Make MaxActiveSessions not nullable

- fedora/jellyfin.spec
**Changes**
Just make everything under libdir/jf a wildcard. I don't know if this will actually work but maybe it will.
**Issues**
CI failures
> Fix RPM spec again

- Jellyfin.Api/Helpers/MediaInfoHelper.cs
- Jellyfin.Api/Helpers/TranscodingJobHelper.cs
- Jellyfin.Server.Implementations/Users/UserManager.cs
Hello!
I made a small PR to understand how that approach fits the project.
Now nullable data types are used widely inside the project, but it leads to warnings, which can be resolved (obviously, we cannot fix it in public methods, because have no guarantees about its usage, but can inspect private methods properly).
**Changes**
1) GetPasswordResetProviders is called from StartForgotPasswordProcess only and that place already check user against null, so conditional access is not required
2) OnFfMpegProcessExited is called only from StartFfMpeg, where it created from OnTranscodeBeginning, which guaranteed that it is not null, so conditional access here is not required
3) GetMaxBitrate is called from two places, but if code passed to it, the user variable cannot be null (if it is not true, …
> Remove unnecessary null checks in some places

- Jellyfin.Api/Controllers/ImageController.cs
This PR is part of #4214, and replaces all instances in `ImageController` where an image format is passed to the API as a string with the `ImageFormat` enum.
I have verified that the new code functions with `curl -s "http://127.0.0.1:8096/Items/UUID/Images/Primary?maxHeight=700&format=FORMAT" -o /tmp/file; file /tmp/file` for the following formats:
* WebP
* JPG
* PNG
> Accept ImageFormat as API parameter

- Emby.Server.Implementations/Session/SessionManager.cs
**Changes**
Changed an event to playbackstart since the consumer is only listening to that
> Fix playbackstart not triggering in the new eventmanager

- Emby.Dlna/Server/DescriptionXmlBuilder.cs
- Emby.Dlna/Service/BaseControlHandler.cs
The first instance in within a try/catch block in ProcessControlRequestAsync. It calls ProcessControlRequestInternalAsync, which in turn calls ParseRequestAsync.
ParseRequestAsync searches for a body tag - but returns an empty ControlRequestInfo object if none is found.
ProcessControlRequestInternalAsync proceeds to try and output settings from this object that aren't initialised (hence null pointer).
As the code is in an exception block, this won't currently crash, however, putting in the exception is a cleaner solution - and goes towards making the function nullable.
The second instance is in ParseBodyTagAsync where under certain circumstances it is possible to get an empty ControlRequestInfo object.
The final change is creating a constructor for ControlRequestInfo, which makes it …
> Null Pointer fix: BaseControlHandler.cs

- MediaBrowser.Providers/Plugins/TheTvdb/TvdbSeriesProvider.cs
Fixes the following error:
```
[2020-09-27 15:27:01.483 -07:00] [ERR] [77] MediaBrowser.Providers.TV.SeriesMetadataService: Error in "TheTVDB"
System.InvalidOperationException: Sequence contains no elements
at System.Linq.ThrowHelper.ThrowNoElementsException()
at System.Linq.Enumerable.Max(IEnumerable`1 source)
at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider.MapSeriesToResult(MetadataResult`1 result, Series tvdbSeries, String metadataLanguage) in C:\Programming\jellyfin\MediaBrowser.Providers\Plugins\TheTvdb\TvdbSeriesProvider.cs:line 345
at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken) in …
```
> Fix InvalidOperationException in TvdbSeriesProvider.MapSeriesToResult

- Emby.Server.Implementations/Library/Resolvers/Audio/MusicAlbumResolver.cs
- Emby.Server.Implementations/Library/Resolvers/Audio/MusicArtistResolver.cs
The scan for my 78 thousand track music library on an rclone mount is pretty slow. I looked into the code and found it is partly due to the directory enumeration. 
When scanning, each io operation hits the rclone mount, which does some request to the backend cloud storage. 
The first part of the scan checks to see if something is a music album. If you have 1 folder with 1,000 subfolders, where each one represents an artist, it enumerates each of those subfolders one by one, which is very slow. Changing the scan logic to be more parallel results in a faster scan.
**Changes**
- Rearrange some the logic so it can bail out faster.
- Use `Parallel.ForEach` loops during directory enumeration calls for music scans.
**Issues**
Nothing specific that I saw.
**Future work**
There's additional …
> Increase initial scan speed for music libraries

- Jellyfin.Api/ModelBinders/CommaDelimitedArrayModelBinder.cs
- tests/Jellyfin.Api.Tests/ModelBinders/CommaDelimitedArrayModelBinderTests.cs
Default in aspnetcore is to return an array when no parameters are included.
Note- in both default aspnetcore and with this binder `[Required]` doesn't work on array parameters.
> Fix comma delimited array model binder

- MediaBrowser.Model/System/PublicSystemInfo.cs
**Changes**
This PR makes the StartupWizardCompleted field that is new in 10.7 nullable. This way apiclients won't fail because they're missing a value in the PublicSystemInfo response.
**Issues**
jellyfin/jellyfin-apiclient-java#124
> Make StartupWizardCompleted nullable in PublicSystemInfo

- debian/postrm
**Changes**
After removal of the symlink target file "/usr/lib/jellyfin/bin/jellyfin", file existence check on the symlink "[[ -f /usr/bin/jellyfin ]]" returns false. As a result the symlink is left in place on package purge. The correct check would be "[[ -L /usr/bin/jellyfin ]]", but since it could be a file in cases, e.g. manual fix on file systems with no symlink support or for any other reason, it is easiest to use "rm -f" to assure that it is removed in both cases and not return false even if it does not exist at all.
Additionally this fixes a typo on upstart script check.
> Fix left /usr/bin/jellyfin symlink on removal and typo

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- HDR Tonemapping is also available on AMD GPU now.
Tested on RX 580 and Vega 64.
- Drop the redundant video filter slice in graphical sub burn-in.
**Notes**
Since the AMD [AMF decoder has not yet been implemented in FFmpeg](https://github.com/jellyfin/jellyfin/pull/3442#issuecomment-649963180), we have used the D3D11VA decoder as an alternative. But this will bring greater performance loss compared to NVDEC/NVENC.
It is recommended to use a multi-core CPU and a discrete graphics card for better performance. And turn off AMF hardware decoding during tonemapping.
If you want to promote the implementation of AMD AMF decoder in FFmpeg, please let their staff know at the link below.
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/199
> Add tonemapping for AMD AMF

- MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzAlbumProvider.cs
Related to #4242, and similar to #4223. 
Fixes issues when refreshing multiple items at the same time for musicbrainz. Unfortunately due to musicbrainz api limits, it seems like we need to keep this running sequentially.
Also fixes the retry logic - it's currently broken and throws this error whenever it tries the same request again:
```
System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
at System.Net.Http.HttpClient.CheckRequestMessage(HttpRequestMessage request)
at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)
at …
```
> Make MusicBrainzAlbumProvider thread safe and fix retry logic

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
**Changes**
Currently Matroska (MKV) files containing interlaced video report the frame rate at the field rate instead of the expected frame rate. As a result the stored and displayed frame rate is double what it should be (e.g. 50 instead of 25). This also has the unintended effect of disabling double rate (bob) deinterlacing for those that have it switched on.
This change halves the average and real frame rate when it is probed for interlaced video streams in an Matroska container, so that the correct frame rate is stored.
**Issues**
Fixes #4314
**Additional Context**
The Matroska container doesn't have a header for the frame rate to be stored in. Instead it stores a display duration for each block containing a frame of video.
As FFprobe (and other apps) don't have a stored framerate in …
> Fix frame rate probing for interlaced MKV files

- Jellyfin.Api/Helpers/DynamicHlsHelper.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Default the output audio bitrate to 128000 as per ffmpeg docs if it is not being requested.
**Issues**
- `BANDWIDTH` area in master playlist is not allow to be empty on iOS, otherwise the playback won't begin.
Only happens when transcoding music and streaming in HLS to iOS devices.
Fixes: https://github.com/jellyfin/jellyfin/issues/3957
> Fix HLS music playback on iOS

- Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs
Fixes 
```c#
[2020-10-26 18:31:10.489 -04:00] [ERR] [110] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/{userId}".
System.ArgumentException: An item with the same key has already been added. Key: Device
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at Emby.Server.Implementations.HttpServer.Security.AuthorizationContext.GetAuthorization(String authorizationHeader)
at Emby.Server.Implementations.HttpServer.Security.AuthorizationContext.GetAuthorizationDictionary(HttpRequest httpReq)
at Emby.Server.Implementations.HttpServer.Security.AuthorizationContext.GetAuthorizationInfo(HttpRequest requestContext)
at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest …
```
> Fix setting duplicate keys from auth header

- debian/control
**Changes**
Remove the jellyfin-ffmpeg dependency from jellyfin-server itself. It is being added to the metapackage instead.
This allows working around the dependency if required, while still preserving the same clean install for normal users.
**Issues**
N/A
> Remove jellyfin-ffmpeg dep from server package

- Jellyfin.Api/Controllers/CollectionController.cs
jf-web uses `ids`, not `itemIds`.
> Rename itemIds to ids

- Emby.Server.Implementations/Localization/Core/en-US.json
- Emby.Server.Implementations/ScheduledTasks/Tasks/CleanActivityLogTask.cs
- Jellyfin.Server.Implementations/Activity/ActivityManager.cs
- MediaBrowser.Model/Activity/IActivityManager.cs
- MediaBrowser.Model/Configuration/ServerConfiguration.cs
Fixes #4294 
Note: the scheduled task does not have any triggers by default.
`ActivityLogRetentionDays` is nullable for API compatibility.
> Automatically clean activity log database

- Jellyfin.Api/Controllers/UniversalAudioController.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
**Changes**
Part 1: Correct the supportedAudioCodecs.
Part 2: https://github.com/jellyfin/jellyfin-web/pull/2026
**Issues**
Safari doesn't support MKV container. Both video stream(H264) and audio stream(AAC) need to be remuxed for playing.
Fixes: https://github.com/jellyfin/jellyfin-web/issues/368
> Fix AAC direct streaming

- .ci/azure-pipelines-package.yml
**Changes**
`nohup` does not support a `-n` argument on Debian Buster.
**Issues**
N/A
> Remove spurious argument to nohup

- Jellyfin.Api/Controllers/DynamicHlsController.cs
- Jellyfin.Api/Controllers/MediaInfoController.cs
- Jellyfin.Api/Controllers/UniversalAudioController.cs
- Jellyfin.Api/Helpers/MediaInfoHelper.cs
- MediaBrowser.Model/Dlna/AudioOptions.cs
- MediaBrowser.Model/Dlna/DeviceProfile.cs
- MediaBrowser.Model/MediaInfo/LiveStreamRequest.cs
**Changes**
- respect music quality settings when transcoding and audioBitrate is unspecified.
**Issues**
The bitrate of transcoded music have always been the default 128k as the music quality settings was not passed to ffmpeg.
> Respect music quality settings when transcoding

- Jellyfin.Api/Controllers/DisplayPreferencesController.cs
- MediaBrowser.Controller/IDisplayPreferencesManager.cs
GetDisplayPreferences and GetItemDisplayPreferences creates the entity if it doesn't exist already, but due to WAL it will not be flushed immediately and cause a unique constraint error at the first SaveChanges call (I am guessing).
```
[ERR] [49] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/DisplayPreferences/usersettings".
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: DisplayPreferences.UserId, DisplayPreferences.Client'.
at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
at …
```
> Save new display preferences

- Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
Change required for jellyfin/jellyfin-web#2044
**Changes**
Instead of receiving sha1 hash of password from client in API call, receive plain text password and perform hashing on the server.
> Perform hashing of Password for Schedules Direct on server

- Emby.Naming/Video/CleanDateTimeParser.cs
Fixes 
```
[2020-11-09 08:08:26.740 -05:00] [ERR] [63] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
at System.Text.RegularExpressions.Regex.Match(String input)
at Emby.Naming.Video.CleanDateTimeParser.TryClean(String name, Regex expression, CleanDateTimeResult& result)
at Emby.Naming.Video.CleanDateTimeParser.Clean(String name, IReadOnlyList`1 cleanDateTimeRegexes)
at Emby.Server.Implementations.Library.LibraryManager.ParseName(String name)
at MediaBrowser.Controller.Entities.Trailer.BeforeMetadataRefresh(Boolean replaceAllMetdata)
at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
at …
```
> Don't throw exception if name is null

- Jellyfin.Api/Controllers/LibraryController.cs
Duplicate names aren't very nice in openapi
> Semi-revert removal of Name for /Similar in openapi

- Jellyfin.Api/Controllers/VideoAttachmentsController.cs
**Changes**
* fix return type for GetAttachment
**Issues**
It throws a type error that make SubtitlesOctopus to fail when fetching embedded subtitles or fonts.
> Fix return type for GetAttachment

- Dockerfile
Moved fast, broke stuff
Step 5/23 : FROM mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}-buster as builder                             
manifest for mcr.microsoft.com/dotnet/sdk:5.0-buster not found: manifest unknown: manifest tagged by "5.0-buster" is not found
arm not tested
> update dotnet 5.0 buster image

- deployment/Dockerfile.docker.amd64
- deployment/Dockerfile.docker.arm64
- deployment/Dockerfile.docker.armhf
User buster-slim instead of non existent buster
CentOS and Fedora are still broken
> Fix dockerfiles

- deployment/Dockerfile.fedora.amd64
Fedora 33 is out so Fedora 31 is unmaintened so its time to migrate the build to Fedora 33 !
> Bump dependencies to Fedora 33

- Jellyfin.Api/Controllers/EnvironmentController.cs
In 10.6 policy was `[Authenticated(Roles = "Admin", AllowBeforeStartupWizard = true)]`
> Fix Environment authorization policy

- Emby.Server.Implementations/ApplicationHost.cs
Not repeatedly deleting the version we want is a good start :smile: 
```csharp
Nov 19 15:07:41 1070L jellyfin[11185]: [15:07:41] [INF] Loading assemblies
Nov 19 15:07:41 1070L jellyfin[11185]: [15:07:41] [DBG] Anime 11.2020.1119.1145 /var/lib/jellyfin/plugins/Anime_11.2020.1119.1145
Nov 19 15:07:41 1070L jellyfin[11185]: [15:07:41] [DBG] Anime 11.2020.1119.1152 /var/lib/jellyfin/plugins/Anime_11.2020.1119.1152
Nov 19 15:07:41 1070L jellyfin[11185]: [15:07:41] [DBG] Anime 11.2020.1119.1246 /var/lib/jellyfin/plugins/Anime_11.2020.1119.1246
Nov 19 15:07:41 1070L jellyfin[11185]: [15:07:41] [DBG] Anime 11.2020.1119.1306 /var/lib/jellyfin/plugins/Anime_11.2020.1119.1306
Nov 19 15:07:41 1070L jellyfin[11185]: [15:07:41] [DBG] Playback Reporting 9.2020.1119.705 /var/lib/jellyfin/plugins/Playback …
```
> Fix plugin old version cleanup

- MediaBrowser.Common/Json/Converters/JsonDateTimeIso8601Converter.cs
- MediaBrowser.Common/Json/JsonDefaults.cs
Python doesn't like the default format 😢
> Write DateTimes in ISO8601 format for backwards compatibility.

- Jellyfin.Api/Controllers/HlsSegmentController.cs
LiveTV was being transcoded with a `.ts` extension instead of the hardcoded `.m3u8`.
> Fix live tv hls playback

- Jellyfin.Api/Controllers/ImageController.cs
Should fix this exception:
```
jellyfin-edge_1  | System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin-edge_1  |    at Jellyfin.Api.Controllers.ImageController.GetUserImage(Guid userId, ImageType imageType, String tag, Nullable`1 format, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 cropWhitespace, Nullable`1 addPlayedIndicator, Nullable`1 blur, String backgroundColor, String foregroundLayer, Nullable`1 imageIndex)
jellyfin-edge_1  |    at lambda_method1262(Closure , Object )
jellyfin-edge_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, …
```
> Fix nullref

- Jellyfin.Api/ModelBinders/NullableEnumModelBinder.cs
- Jellyfin.Api/ModelBinders/NullableEnumModelBinderProvider.cs
- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Enum values that are unknown are now set to `null` if the value doesn't exist and the enum is nullable instead of failing validation.
> Add NullableEnumModelBinder and NullableEnumModelBinderProvider

- Jellyfin.Api/Controllers/SessionController.cs
- Jellyfin.Api/Models/SessionDtos/ClientCapabilitiesDto.cs
- MediaBrowser.Controller/Session/SessionInfo.cs
- MediaBrowser.Model/Session/ClientCapabilities.cs
The original `ClientCapabilities` couldn't access the converter so I copied it to a Dto.
> Convert ClientCapabilities to a Dto with JsonConverters

- Jellyfin.Server/Startup.cs
Sets the default `Accept` header to `application/json, */*`
By default there is no `Accept` header.
`*/*` is needed for endpoints that would return an image instead of json.
This can be overridden locally as follows
```c#
var client = _httpClientFactory.CreateClient(NamedClient.Default);
using var request = new HttpRequestMessage(HttpMethod.Get, url);
request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(MediaTypeNames.Application.Xml));
using var response = await client.SendAsync(request).ConfigureAwait(false);
```
> Set default request accept headers

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
**Changes**
This reverts the change I made in #4369.
On further testing I've descovered that while the fix corrected the displayed frame rate for some interlaced MKV files (mainly recorded from broadcast TV), it also incorrectly halfed the displayed frame rate for some others (mainly encoded by FFmpeg/x264).
I also discovered that for the "fixed" files, with double rate deinterlacing enabled FFmpeg is really dumb and will double the rate based on the it's incorrectly reported frame rate. So for example a 50i file is deinterlaced to 100fps, not 50fps as intended. Reverting this fix prevents that and results in a deinterlaced file at a sensible/correct frame rate, just with double rate disabled.
As the first fix creates more bugs than it fixes, I feel it's best to revert it for now until …
> Revert "Fix frame rate probing for interlaced MKV files"

- fedora/jellyfin.spec
**Changes**
On a fresh install (`%pre $1` of exactly 1), enable the `jellyfin.service` systemd unit.
Ref: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_syntax
**Issues**
Fixes #4552
> Enable jellyfin.service unit on Fedora fresh install

- debian/bin/restart.sh
- fedora/jellyfin.spec
- fedora/restart.sh
**Changes**
Should solve the occasional bugs with the restart in the WebUI.
Sometimes the service stops and then doesn't start again; this will run
an explicit start action afterwards. If this doesn't fix it I'm certain
there would be more tweaking that can be done.
Also remove the `at now` hackery; whether this works or not I'm
not certain, but is worth a test. I shall do so.
**Issues**
Fixes #4016
> Run explicit service start if restart failed

- Jellyfin.Server.Implementations/Events/Consumers/Session/PlaybackStopLogger.cs
Fixes 
```
Nov 23 03:41:15 1070L jellyfin[5399]: [03:41:15] [ERR] Jellyfin.Server.Implementations.Events.EventManager: Uncaught exception in EventConsumer Jellyfin.Server.Implementations.Events.Consumers.Session.PlaybackStopLogger:
Nov 23 03:41:15 1070L jellyfin[5399]: System.ArgumentNullException: Value cannot be null. (Parameter 'type')
Nov 23 03:41:15 1070L jellyfin[5399]:    at Jellyfin.Data.Entities.ActivityLog..ctor(String name, String type, Guid userId)
Nov 23 03:41:15 1070L jellyfin[5399]:    at Jellyfin.Server.Implementations.Events.Consumers.Session.PlaybackStopLogger.OnEvent(PlaybackStopEventArgs eventArgs)
Nov 23 03:41:15 1070L jellyfin[5399]:    at Jellyfin.Server.Implementations.Events.EventManager.PublishInternal[T](T eventArgs)
```
> Don't send activity event if notification type is null

- fedora/jellyfin.spec
Reverts jellyfin/jellyfin#4553
Apparently this is bad form in the Fedora ecosystem.
> Revert "Enable jellyfin.service unit on Fedora fresh install"

- Jellyfin.Server/Program.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Web side changes: https://github.com/jellyfin/jellyfin-web/pull/2119
**Changes**
* Depends:
Kaby Lake chips or newer. 10-bit hw decoding is required.
iHD VAAPI driver: `intel-media-va-driver-non-free`
OpenCL runtime: https://github.com/intel/compute-runtime/releases
* Works:
hwdec -> scale -> tonemap -> hwenc
hwdec -> scale -> tonemap -> textsubs -> hwenc
* Not works: (need overlay_vaapi filter that haven't been merged into ffmpeg master)
hwdec -> scale -> tonemap -> overlay(graphicalsubs) -> hwenc
> Add Tonemapping for Intel VAAPI

- Emby.Server.Implementations/TV/TVSeriesManager.cs
**Changes**
This removes the weird behavior where GetNextUp will return first episodes of shows if there is no series in progress.
The rationale is that we shouldn't assume something is next up in queue if it hasn't been started yet.
No changes needed in jellyfin-web, since the section will hide if empty.
**Issues**
> Don't return first episodes in next up

- MediaBrowser.Common/Json/Converters/JsonGuidConverter.cs
Apparently, the JsonGuidSerializer now writes nulls instead of 0000-0000 style Guids. Only it still can't read them.
See c4925ad70bd84477bd1e8df59de3db1196432fc2. Merged in https://github.com/jellyfin/jellyfin/pull/4568
**Changes**
I like the idea, so I made the reader able to read them as well.
**Issues**
Fixes #4602
> Allow JsonGuidConverter to read null

- Emby.Dlna/Eventing/DlnaEventManager.cs
This is required by the internal DLNA event subscription sub-system.
> [Fix] NotificationType was never set in dlna event manager

- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
**Changes**
- Fix the wrong I-frame image extraction filter string introduced in #4501
- Increase `DefaultImageExtractionTimeout` since the default scale width 600 have been removed.
Otherwise the ffmpeg process will be stopped prematurely when extracting image for high resolution videos.
- Allow to extract music bitrate info from formatInfo.
**Issues**
```
-f mov,mp4,m4a,3gp,3g2,mj2 -ss 00:00:30.025 -i file:"h264High10.mp4" -threads 0 -v quiet -vframes 1 ,thumbnail=24 -f image2 "69b6b099-dad0-4e98-b043-9c92a23fe2e8.jpg"
```
Fixes https://github.com/jellyfin/jellyfin/issues/4617
> Fix the I-frame image extraction filter string

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
**Changes**
- Do not extract audio stream bitrate info for videos from formatInfo
**Issues**
Fix a bug I introduced in #4607
> Do not extract audio stream bitrate info for videos from formatInfo

- Emby.Server.Implementations/TV/TVSeriesManager.cs
**Changes**
GetUpNext was returning episodes that are in progress, leading to this:
Its purpose should be to only return future episodes of a show that is already started, but not in progress episodes.
To achieve this, this gets the user data of the episode to be added to the list, checks if it's in progress and just returns null if it is.
**Issues**
> Prevent GetUpNext from returning episodes in progress

- Emby.Server.Implementations/HttpServer/Security/AuthService.cs
- Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs
- Jellyfin.Api/Auth/CustomAuthenticationHandler.cs
- MediaBrowser.Controller/Net/AuthorizationInfo.cs
- tests/Jellyfin.Api.Tests/Auth/CustomAuthenticationHandlerTests.cs
The ASP.NET framework automatically logs when an AuthenticationHandler fails, so return `AuthenticateResult.NoResult()` instead. Authorization is still failed by the AuthorizationHandler(s)
Fixes https://github.com/jellyfin/jellyfin/issues/4627
> Provide NoResult instead of Fail in CustomAuthenticationHandler

- Dockerfile
**Changes**
- add [intel-compute-runtime](https://github.com/intel/compute-runtime) to Dockerfile
> Add NEO OpenCL runtime for Intel Tone mapping

- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
**Changes**
- Extract tone mapped thumbnails for HDR videos.
> Extract tone mapped thumbnails for HDR videos

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
**Changes**
`GetWhereClauses()` only checked if several query values were present, instead of their values.
**Issues**
Fixes #4578
> [Fix] Test query value

- Jellyfin.Api/Controllers/FilterController.cs
Fixes
```
[08:27:32] [ERR] [43] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Items/Filters.
System.NullReferenceException: Object reference not set to an instance of an object.
at Jellyfin.Api.Controllers.FilterController.GetQueryFiltersLegacy(Nullable`1 userId, String parentId, String[] includeItemTypes, String[] mediaTypes)
at lambda_method808(Closure , Object , Object[] )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& …
```
> Fix null reference when getting filters of an empty library

- Emby.Server.Implementations/Localization/countries.json
**Changes**
Localization: add *Palestine* to list of countries between *Oman* and *Panama*
The alpha-2 and alpha-3 codes can be verified at: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
**Screenshots of this change**
**Issues**
Fixes #4646
> fix: add Palestine to supported countries

- Jellyfin.Server/Startup.cs
RequireHttps was moved across to NetworkConfiguration.cs.
Missed this one.
> [Fix for 10.7] Missed a config move

- Jellyfin.Server/Startup.cs
As per @dmitrylyzo 
```
subtitles-octopus-worker-legacy.js.mem is for old browsers
```
> Add support for web serving .mem files

- .ci/azure-pipelines-api-client.yml
Without this, the publish will fail.
https://docs.npmjs.com/creating-and-publishing-an-organization-scoped-package
> Fix the NPM publish scope to public

- Jellyfin.Api/Controllers/UserController.cs
Adds the required attribute to necessary API parameters
> Add required attributes to parameters

- Jellyfin.Networking/Manager/NetworkManager.cs
Changed logging message and type - as this shouldn't be a warning.
[2020-12-05 06:40:10.223 +00:00] [WRN] [65] Jellyfin.Networking.Manager.NetworkManager: "meh IP/32": External request received, however, no WAN interface found.
> Change logging level and message in NetworkManager

- Jellyfin.Api/Controllers/ImageController.cs
- Jellyfin.Api/Controllers/QuickConnectController.cs
- Jellyfin.Api/Controllers/UserController.cs
The `Forbid()` constructor is used to pass authentication schemes, so it would return a `500` error stating there is no authentication scheme with the name [...]
> Fix API forbidden response

- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
**Changes**
- Use larger batch size on mpegts to avoid corrupted thumbnails
> Use larger batch size on mpegts to avoid corrupted thumbnails

- Jellyfin.Server/Filters/FileResponseFilter.cs
I must have looked at swagger2 docs when making this filter.
Taken from https://swagger.io/docs/specification/describing-responses/
> Response That Returns a File
> An API operation can return a file, such as an image or PDF. OpenAPI 3.0 defines file input/output content as type: string with format: binary or format: base64. This is in contrast with OpenAPI 2.0, which uses type: file to describe file input/output content. If the response returns the file alone, you would typically use a binary string schema and specify the appropriate media type for the response content: 
```yaml
paths:
/report:
get:
summary: Returns the report in the PDF format
responses:
'200':
description: A PDF file
content:
application/pdf:
schema:
type: string
format: binary
```
> Fix openapi file schema

- Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
- Emby.Server.Implementations/Updates/InstallationManager.cs
Added to where `HttpRequestException` is caught.
Note: `IHttpClient` always ran `EnsureSuccessStatusCode`
Fixes https://github.com/jellyfin/jellyfin/issues/4732
> Add missing EnsureSuccessStatusCode

- MediaBrowser.Model/Configuration/EncodingOptions.cs
**Changes**
- Set recommand algorithm to Hable. It has better color and contrast.
- Set recommand tone mapping peak to 100. Avoid incorrect brightness information.
Web side changes:
https://github.com/jellyfin/jellyfin-web/pull/2222
> Fine tune some tone mapping params

- Jellyfin.Api/Controllers/MediaInfoController.cs
- Jellyfin.Api/Controllers/PlaylistsController.cs
- Jellyfin.Api/Models/PlaylistDtos/CreatePlaylistDto.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4760
Note- the client still needs to add a `Content-Type` header.
> Convert CreatePlaylist to use query params instead of body
