jellyfin/jellyfin

.gitmodules
Move the submodules to our namespace and update `.gitmodules`.
Closes #13
=> Update submodule paths

README.md
- Added note about new feature priorities
- Fix invisible FeatHub link
=> Fix invisible FeatHub link

README.md
We need to crosslink our presences on different websites and services.
=> Mention subreddit in README

README.md
=> Add Debian repo instructions and link to AUR

unRaid/docker-templates/README.md, unRaid/docker-templates/jellyfin.xml
Add into the Docker tab
https://github.com/jellyfin/jellyfin/unRaid/docker-templates
save
click add container and choose jellyfin
=> Test Template for unraid - should work

unRaid/docker-templates/jellyfin.xml
changed networking mode from bridge to host
=> Updated mode setting

Dockerfile
Resolves https://github.com/jellyfin/jellyfin/issues/50
=> Opt out of .NET telemetry

unRaid/docker-templates/README.md
Updated Template repository link
=> Template link

Dockerfile.debian_package, README.md, debian/control, debian/rules
Resolves https://github.com/jellyfin/jellyfin/issues/17
=> Add Dockerfile for building Debian package

Build-JellyFin.ps1
I need someone with Linux and powershell core to test for me, but this should allow us to at least have a zipfile compiled up for windows users. If we get that hosted somewhere (I.e. GitHub releases) I can package with chocolatey for the time being.
=> build script can generate zip, maybe be run from linux

Emby.Dlna/Emby.Dlna.csproj, Emby.Drawing.Skia/Emby.Drawing.Skia.csproj, Emby.Server.Implementations/Emby.Server.Implementations.csproj, MediaBrowser.Server.Mono/EmbyServer.csproj
=> Change name from EmbyServer.dll to jellyfin.dll

.gitignore
Ignore artifacts generated by `dpkg-buildpackage`
=> Ignore debian build artifacts

MediaBrowser.sln
Closes #194 
Adds de-blobbed MediaEncoding into the solution
=> Add MediaBrowser.MediaEncoding project reference into solution

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Specified bitrate was ignored.
=> Fix transcoding bitrate

debian/changelog
Preparation for release 3.5.2-4
=> Bump Debian packaging version

README.md
- Fix the shields.io badge call for matrix
=> Correct the badge for Matrix

MediaBrowser.WebDashboard/dashboard-ui/components/apphost.js
I love this project and hope i can help a bit!
I have changed the following to Jellyfin Mobile instead of Emby Mobile.
=> renames webapp to Jellyfin Mobile

MediaBrowser.WebDashboard/dashboard-ui/components/apphost.js
=> Rename web UI to "Jellyfin Web"

new-file-header.txt
It is very useful to indicate the license in every file, to ensure the license is always explicit should the code be rearranged later.
=> Add new file header to use as a base for new files

MediaBrowser.MediaEncoding/MediaBrowser.MediaEncoding.csproj
=> MediaBrowser.MediaEncoding use same layout/style as other csprojs

.gitattributes
Will prevent merge conflicts for `CONTRIBUTORS.md`
=> Add merge=union for CONTRIBUTORS.md

Emby.Notifications/Notifications.cs, MediaBrowser.Providers/Movies/MovieDbProvider.cs, MediaBrowser.WebDashboard/dashboard-ui/scripts/connectlogin.js, MediaBrowser.WebDashboard/dashboard-ui/scripts/dashboardpage.js, MediaBrowser.WebDashboard/dashboard-ui/scripts/site.js, MediaBrowser.WebDashboard/dashboard-ui/scripts/supporterkeypage.js, MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs
Does what it says on the title.
Resolves third item in #25
=> Replace all emby.media links with jellyfin.media links

MediaBrowser.Server.Mono/Program.cs
from $appdata to $appdata/config
=> Change location of logging.json

Emby.Server.Implementations/EntryPoints/UdpServerEntryPoint.cs
Not sure why it was disabled. It seems to work just fine now at least.
=> Re-enable UDP server

MediaBrowser.Model/Configuration/ServerConfiguration.cs
=> set EnableAnonymousUsageReporting to false to avoid log spam

Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs, Emby.Server.Implementations/Serialization/JsonSerializer.cs, MediaBrowser.Common/Updates/GithubUpdater.cs, MediaBrowser.Controller/Entities/Game.cs, MediaBrowser.Controller/MediaEncoding/EncodingJobOptions.cs, MediaBrowser.MediaEncoding/Encoder/EncodingJob.cs, MediaBrowser.MediaEncoding/Encoder/FontConfigLoader.cs, MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs, MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs, MediaBrowser.Providers/Manager/ProviderManager.cs, MediaBrowser.XbmcMetadata/Providers/BaseNfoProvider.cs
Remove another batch of warnings
=> Remove some warnings

Emby.Server.Implementations/Channels/ChannelManager.cs, Emby.Server.Implementations/IO/SharpCifs/Smb/SmbFile.cs, Emby.Server.Implementations/Networking/IPNetwork/IPNetwork.cs, MediaBrowser.Common/Extensions/BaseExtensions.cs
All of these function except for 1 wern't used.
=> Remove obsolete code

Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteLogFileTask.cs
Maybe document this somewhere?
=> DeleteLogFileTask: only delete the .txt log files

Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs, Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs, Emby.Server.Implementations/LiveTv/LiveTvManager.cs, Emby.Server.Implementations/Updates/InstallationManager.cs, MediaBrowser.Common/Net/IHttpClient.cs, MediaBrowser.Providers/Movies/MovieDbProvider.cs
Fixes spelling mistake, warnings, condenses verbose code, etc.
=> Clean up HttpClientManager, LiveTvManager and InstallationManager

MediaBrowser.Api/Playback/BaseStreamingService.cs
Fixes the crash in https://gist.github.com/LeoVerto/98f6fd9f2a187e60a0a458c9f50bb507
Not sure if it's enough.
=> Fix ArgumentNullException in DLNA streams

Emby.Drawing.Skia/SkiaEncoder.cs, Emby.Drawing.Skia/StripCollageBuilder.cs
Cleaned up some other declarations along the way.
=> Emby.Drawing.Skia remove deprecated functions.

Emby.Server.Implementations/ApplicationHost.cs
This code won't ever be needed again.
=> Remove remaining part old logging code

Emby.Server.Implementations/Library/MediaSourceManager.cs, MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
=> [Fix #254] Fix nullrefexception in SubtitleEncoder

Emby.Server.Implementations/AppBase/BaseApplicationPaths.cs, Emby.Server.Implementations/ServerApplicationPaths.cs, Jellyfin.Server/Program.cs
Adds -configdir and -logdir flags and envvars.
=> Make config path configurable

SharedVersion.cs
Update the shared version (the only place I could find that had the program version in it) to 10.0.0 in preparation for release.
=> Update shared version to 10.0.0

debian/source/options
title says it all.. oh and it
Fixes #429
=> Stop including .git in dpkg source tarball

.gitignore, debian/changelog, debian/conf/jellyfin, debian/conf/logging.json, debian/control, debian/install, debian/jellyfin.service, debian/postinst, debian/postrm, debian/preinst, debian/prerm
1. Bump version to 10.0.0-1.
2. Add VCS entries so source packages link back to GitHub.
3. Make use of the new -logdir and -configdir flags from #428.
4. Add a migration element for the above to Debianized places if they exist.
Requires #430 as well for cleanliness.
=> Debian packaging for 10.0.0

MediaBrowser.WebDashboard/dashboard-ui/css/site.css
=> Shrink bottom padding

MediaBrowser.WebDashboard/dashboard-ui/bower_components/emby-apiclient/apiclient.js
=> Disable unimplemented updates

MediaBrowser.WebDashboard/dashboard-ui/scripts/dashboardpage.js
Also stop disable the loading indicator at the end of execution
=> Remove unused

Emby.Server.Implementations/Emby.Server.Implementations.csproj
Looks like I forgot to remove these in #383.
=> Remove unused resource

SharedVersion.cs, debian/changelog
Bumps SharedVersion and Debian changelog to 10.0.1.
=> Bump version for 10.0.1

MediaBrowser.Controller/Providers/RemoteSearchQuery.cs, MediaBrowser.Providers/Manager/ProviderManager.cs
It looks like it should be a Guid, but I can't test this change.
=> Change ItemId to Guid in ProviderManager

CONTRIBUTORS.md, Emby.Server.Implementations/Library/UserManager.cs
=> Fix "Password Reset by PIN" page

Jellyfin.Server/Jellyfin.Server.csproj
Should help keep code clean and lower the amount of stupid bugs like #562.
=> Add code analysers for debug builds

Jellyfin.Server/Program.cs
**Changes**
Graceful shutdown on SIGTERM and Ctrl+C
**Issues**
Fixes #218
Fixes #422 
Fixes #454
=> Shutdown gracefully when recieving a termination signal

Emby.Naming/Emby.Naming.csproj
This package is also needed by some plugins
=> Add nuget info to Emby.Naming

.editorconfig
XML files should have an indentation of 2 spaces, not 4.
=> Fix indentation for xml files

Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs
**Changes**
Removed type name. Added `out` keyword.
=> Fix extra type name in parameter, add out keyword

Emby.Dlna/PlayTo/PlayToManager.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs, MediaBrowser.Api/PackageService.cs, MediaBrowser.Api/Session/SessionsService.cs, MediaBrowser.Common/IApplicationHost.cs, MediaBrowser.WebDashboard/Api/DashboardService.cs
Addresses my feedback to https://github.com/jellyfin/jellyfin/pull/508
=> Use string for ApplicationVersion

MediaBrowser.Controller/Library/TVUtils.cs
**Changes**
Replaces our Key, which is v2-only, with @drakus72's v1 legacy key. Required until we can rebuild the API interface to support their v2.
**Issues**
Fixes #595
=> Replace our TVDB key with @drakus72's which is V1

Emby.Naming/TV/EpisodeResolver.cs, Emby.Naming/Video/StubResolver.cs, Emby.Naming/Video/StubResult.cs, Emby.Naming/Video/VideoResolver.cs, Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs, Emby.Server.Implementations/IO/ManagedFileSystem.cs, Emby.Server.Implementations/Library/Resolvers/TV/SeriesResolver.cs, MediaBrowser.Controller/Entities/BaseItem.cs, MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs
Brushed trough some hot functions.
* Removed unneeded checks
* Removed unneeded copies
* Removed unneeded instances
This won't make any big difference in perf, but all bits help.
=> Minor improvements to library scan code

CONTRIBUTORS.md, MediaBrowser.Api/Subtitles/SubtitleService.cs
=> Fix infinite loop bug on subtitle.m3u8 request

.gitmodules, Emby.Photos/Emby.Photos.csproj, MediaBrowser.sln
Replaces submodule with package.
Resolves https://github.com/jellyfin/jellyfin/issues/87
=> Use TagLibSharp Nuget package

MediaBrowser.Model/Dlna/AudioOptions.cs, MediaBrowser.Model/Dlna/ConditionProcessor.cs, MediaBrowser.Model/Dlna/DeviceProfile.cs, MediaBrowser.Model/Dlna/StreamBuilder.cs
* Reworked some verbose code.
* Made ConditionProcessor static.
=> Clean up streambuilder

Dockerfile.arm
=> Fix arm32 Docker

Jellyfin.Server/Program.cs, Jellyfin.Server/SocketSharp/RequestMono.cs, Jellyfin.Server/SocketSharp/WebSocketSharpListener.cs, Jellyfin.Server/SocketSharp/WebSocketSharpRequest.cs
Some changes:
* Don't omit braces
* Fix culture sensitive string compare
* Define accessibility functions
I restricted myself to these 5 files, for now :p
=> Fix some analyzer warnings

Emby.Dlna/Didl/DidlBuilder.cs, Emby.Drawing/SkiaEncoder.cs, Emby.Naming/AudioBook/AudioBookResolver.cs, Emby.Server.Implementations/Channels/ChannelManager.cs, Emby.Server.Implementations/Library/MediaSourceManager.cs, Emby.Server.Implementations/Library/Resolvers/Audio/AudioResolver.cs, Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs, Emby.Server.Implementations/Library/Resolvers/TV/SeriesResolver.cs, Emby.Server.Implementations/Library/UserManager.cs, Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs, Emby.Server.Implementations/LiveTv/EmbyTV/EncodedRecorder.cs, Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
=> Remove conditions that are always true/false

Emby.Server.Implementations/Activity/ActivityLogEntryPoint.cs, Emby.Server.Implementations/Activity/ActivityManager.cs, Emby.Server.Implementations/Activity/ActivityRepository.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Emby.Server.Implementations.csproj, Jellyfin.Server/Program.cs, MediaBrowser.Api/Library/LibraryService.cs, MediaBrowser.Common/IApplicationHost.cs, MediaBrowser.Model/Activity/IActivityManager.cs, MediaBrowser.Model/Activity/IActivityRepository.cs
Start moving databases to Entity Framework core.
=> Use EF Core for Activity database

Jellyfin.Server/Jellyfin.Server.csproj
=> Fix debug build on windows

Emby.Server.Implementations/Activity/ActivityLogEntryPoint.cs, Emby.Server.Implementations/Activity/ActivityManager.cs, Emby.Server.Implementations/Activity/ActivityRepository.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Emby.Server.Implementations.csproj, Jellyfin.Server/Program.cs, MediaBrowser.Api/Library/LibraryService.cs, MediaBrowser.Common/IApplicationHost.cs, MediaBrowser.Model/Activity/IActivityManager.cs, MediaBrowser.Model/Activity/IActivityRepository.cs
This reverts commit 48ad18d12baeeb42ec0ec7df9473330dcbc76754, reversing
changes made to fe197415cac19c0e4005c52761c5e7a37b8a4557.
**Changes**
Reverts all changes to activity database.
=> Revert "Merge pull request #452 from Bond-009/activitydb"

Emby.Dlna/Didl/DidlBuilder.cs, Emby.Drawing/ImageProcessor.cs, Emby.Drawing/NullImageEncoder.cs, Emby.Drawing/PercentPlayedDrawer.cs, Emby.Drawing/PlayedIndicatorDrawer.cs, Emby.Drawing/SkiaEncoder.cs, Emby.Drawing/UnplayedCountIndicator.cs, Emby.Photos/PhotoProvider.cs, Emby.Server.Implementations/Dto/DtoService.cs, MediaBrowser.Api/Images/ImageService.cs, MediaBrowser.Controller/Drawing/IImageEncoder.cs, MediaBrowser.Controller/Drawing/IImageProcessor.cs, MediaBrowser.Controller/Drawing/ImageHelper.cs, MediaBrowser.Controller/Drawing/ImageProcessingOptions.cs, MediaBrowser.Controller/Entities/BaseItem.cs, MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs, MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs, MediaBrowser.Controller/Providers/IImageEnhancer.cs, MediaBrowser.Model/Dlna/StreamInfo.cs, MediaBrowser.Model/Drawing/DrawingUtils.cs, MediaBrowser.Model/Drawing/ImageSize.cs
* Change dimensions from double to int
* Rename ImageSize -> ImageDimensions
=> Change image dimentions from double to int

Emby.Dlna/ContentDirectory/ContentDirectory.cs, Emby.Dlna/PlayTo/PlayToManager.cs, Emby.Naming/AudioBook/AudioBookResolver.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.XmlTv/Emby.XmlTv/Classes/XmlTvReader.cs, MediaBrowser.Controller/Entities/UserViewBuilder.cs, MediaBrowser.Providers/Music/MusicBrainzAlbumProvider.cs
**Changes**
Also removes a static regex object in favor of a cached static regex.
**Issues**
Fixes #707
=> Fix always null expressions

Emby.Dlna/ContentDirectory/ControlHandler.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Data/SqliteItemRepository.cs
I made some minor changes to the db code that *could* marginally increase performance.
=> Minor improvements to db code

Emby.Server.Implementations/Data/SqliteItemRepository.cs, MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
**Changes**
Added Size to the DB. UI elements already existed.
**Issues**
https://github.com/jellyfin/jellyfin/issues/704
=> Add Size to TypedBaseItem

Jellyfin.Drawing.Skia/Properties/AssemblyInfo.cs
**Changes**
Add AssemblyInfo for Jellyfin.Drawing.Skia
=> Add AssemblyInfo for Jellyfin.Drawing.Skia

Dockerfile
Eventually would like to move to his 4.0-vaapi image. Also provides an alpine variant.
https://github.com/jrottenberg/ffmpeg
=> Use ffmpeg from jrottenberg/ffmpeg 

Emby.Server.Implementations/Activity/ActivityLogEntryPoint.cs, Emby.Server.Implementations/ApplicationHost.cs, MediaBrowser.Api/PluginService.cs, MediaBrowser.Api/UserLibrary/PlaystateService.cs, MediaBrowser.Controller/Subtitles/ISubtitleManager.cs, MediaBrowser.Providers/Subtitles/SubtitleManager.cs
=> Remove more compile time warnings

MediaBrowser.Api/EnvironmentService.cs, MediaBrowser.Api/Library/LibraryStructureService.cs
**Changes**
Fix three conditions that were inverted in #726 
**Issues**
Closes #767
=> Fix conditions where the ! was swallowed in #726

Emby.Dlna/Didl/DidlBuilder.cs
**Changes**
This removes an empty statement. No functional changes.
=> Fix empty statement in DidlBuilder.cs

Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs, Emby.Server.Implementations/ScheduledTasks/TaskManager.cs
RunStartupTasks never executes because "startuptasks.txt" is never created
=> Remove unused function

Emby.Server.Implementations/IO/LibraryMonitor.cs, Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs, Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs, Emby.Server.Implementations/Updates/InstallationManager.cs, Jellyfin.Server/Program.cs, MediaBrowser.Api/PackageService.cs, MediaBrowser.Api/UserLibrary/PlaystateService.cs
Fixes almost all remaining warnings (excluding analyzer warnings)
The last few are "unused" events, so a closer look at those is required.
=> Fix more warnings

Emby.Server.Implementations/Updates/InstallationManager.cs
=> Fix build error

MediaBrowser.Api/LocalizationService.cs
**Changes**
Made the API function async
**Issues**
Fixes https://github.com/jellyfin/jellyfin-web/issues/123
=> Add await to GetCountries in LocalizationService

README.md
**Changes**
Add the OpenCollective badge to the README and :shipit:.
**Issues**
N/A
=> Add donation badge and reorganize badges

Jellyfin.Server/SocketSharp/WebSocketSharpRequest.cs
Fix style issues and removed an unneeded `ToLowerInvariant()`
=> Quick style fix

Emby.Drawing/ImageProcessor.cs, Emby.Drawing/NullImageEncoder.cs, Emby.Server.Implementations/IO/LibraryMonitor.cs, Emby.Server.Implementations/Library/Resolvers/PhotoResolver.cs, Emby.Server.Implementations/Services/ResponseHelper.cs, Emby.Server.Implementations/Services/ServiceExec.cs, Jellyfin.Drawing.Skia/SkiaEncoder.cs, MediaBrowser.Controller/Drawing/IImageEncoder.cs, MediaBrowser.Controller/Drawing/IImageProcessor.cs
This way the implemention can change the type, in this case I changed to `HashSet` for faster lookups.
=> Move some arrays to generics

README.md
**Changes**
Thanks to our wonderful contributors, I noticed we had the wrong category selected to show donors. Also finally adds a forum badge to the Discourse.
**Issues**
N/A
=> Fix OC badge to all and add forum badge

Emby.Dlna/ContentDirectory/ControlHandler.cs, Emby.Dlna/Didl/DidlBuilder.cs, Emby.Dlna/PlayTo/Device.cs, Emby.Dlna/PlayTo/PlayToController.cs
Device.cs:
* Improve dispose function
* Style fixes
* Remove unused field
DidlBuilder.cs:
* Remove unused field
* Replace giant if chain with a switch statement
=> Some small changes in Device.cs and DidlBuilder.cs

Emby.Drawing/ImageProcessor.cs, Emby.Photos/PhotoProvider.cs, Emby.Server.Implementations/Dto/DtoService.cs, MediaBrowser.Api/Images/ImageService.cs, MediaBrowser.Controller/Drawing/IImageProcessor.cs, MediaBrowser.Model/Drawing/ImageDimensions.cs
Also documents the other functions
=> Complete rename ImageSize -> ImageDimensions

Dockerfile
**Changes**
Changed Docker image to use VAAPI variant of ffmpeg image.
=> Use VAAPI-enabled ffmpeg

deployment/win-x64/package.sh
**Changes**
Fix syntax error in Windows x64 build script.
**Issues**
N/A
=> Fix syntax error of additional brace

Emby.Server.Implementations/Updates/InstallationManager.cs
**Changes**
Removed DLL support in the manifest
=> Remove DLL support and require all packages/plugins to be zip archives

CONTRIBUTORS.md, MediaBrowser.Model/Dlna/StreamBuilder.cs
**Changes**
Added in a missing null-conditional operator (?) to prevent a NullReferenceException from being thrown.
**Issues**
Fixes #871
=> Fix potential NullReferenceException

Emby.Dlna/DlnaManager.cs, Emby.Dlna/MediaReceiverRegistrar/ControlHandler.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Emby.Server.Implementations.csproj, Jellyfin.Server/CoreAppHost.cs, Jellyfin.Server/Program.cs, MediaBrowser.Common/IApplicationHost.cs, MediaBrowser.Common/MediaBrowser.Common.csproj, MediaBrowser.Model/System/PublicSystemInfo.cs, MediaBrowser.Model/System/SystemInfo.cs
This PR replaces SimpleInjector with Microsoft.Extensions.DependencyInjection.
=> Move to Microsoft.Extensions.DependencyInjection

Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs
**Changes**
Added a using statement to properly close the webresponse in GetException.
Fix has been verified with `netstat`. Before the change there were a lot of open connections in CLOSE_WAIT state, which means the server closed the connection, but the client hasn't.
```
TCP    <redacted>  104.20.134.15:https    CLOSE_WAIT
TCP    <redacted>  104.20.134.15:https    CLOSE_WAIT
TCP    <redacted>  104.20.134.15:https    CLOSE_WAIT
```
**Issues**
Fixes https://www.reddit.com/r/jellyfin/comments/aqtlzb/jellyfin_has_become_unstable_in_the_past_few_days/?st=JS5PCHBX&sh=c4119f79
=> Properly dispose HttpWebResponse when the request failed to avoid 'too many open files'

hooks/pre_build
**Changes**
Loads submodules during Docker Hub builds.
=> Checkout submodules in Docker Hub hook

Dockerfile, Dockerfile.arm, Dockerfile.arm64
**Changes**
* Prevent failure when obj exists from host compile
* Enhance readability of disposed stages
* Formatting
**Issues**
https://github.com/jellyfin/jellyfin/pull/909
=> Enhance Dockerfiles

Emby.Server.Implementations/ApplicationHost.cs
This line was used to debug my DI PR, it isn't needed anymore, and only clutters the log.
=> Reduce log spam

Emby.Naming/Video/VideoListResolver.cs
**Changes**
Re-introduced the old grouping behaviour without the weird limits.
**Issues**
Fixes #921 hopefully
=> Semi-revert to prefer old movie grouping behaviour

.drone.yml
**Changes**
The Jellyfin.*.dll files do not exist.
=> Fixed the assemblynames for compatibility check in drone.

Emby.Naming/Video/VideoListResolver.cs
**Changes**
Reverted #933, #924 and #739
**Issues**
Fixes #921
=> Revert movie matching

Emby.Notifications/CoreNotificationTypes.cs, Emby.Notifications/Notifications.cs, Emby.Server.Implementations/AppBase/BaseApplicationPaths.cs, Emby.Server.Implementations/ApplicationHost.cs, MediaBrowser.Api/ScheduledTasks/ScheduledTaskService.cs, MediaBrowser.Common/Configuration/IApplicationPaths.cs, MediaBrowser.Common/IApplicationHost.cs, MediaBrowser.Model/Configuration/BaseApplicationConfiguration.cs, MediaBrowser.Model/System/SystemInfo.cs
As we aren't currently planning on supporting self-updating.
=> Removed remaining self-update code

Emby.Server.Implementations/Data/BaseSqliteRepository.cs, Emby.Server.Implementations/Data/SqliteItemRepository.cs, Emby.Server.Implementations/HttpServer/HttpResultFactory.cs, Emby.Server.Implementations/HttpServer/StreamWriter.cs, Emby.Server.Implementations/Library/LibraryManager.cs, Emby.Server.Implementations/Library/UserManager.cs, Emby.Server.Implementations/LiveTv/LiveTvManager.cs, Emby.Server.Implementations/Serialization/JsonSerializer.cs, Jellyfin.Server/Jellyfin.Server.csproj, Jellyfin.Server/SocketSharp/WebSocketSharpRequest.cs, MediaBrowser.Api/BaseApiService.cs, MediaBrowser.Api/UserLibrary/ArtistsService.cs, MediaBrowser.Api/UserLibrary/BaseItemsByNameService.cs, MediaBrowser.Api/UserLibrary/BaseItemsRequest.cs, MediaBrowser.Api/UserLibrary/GenresService.cs, MediaBrowser.Api/UserLibrary/ItemsService.cs, MediaBrowser.Api/UserLibrary/MusicGenresService.cs, MediaBrowser.Api/UserLibrary/PersonsService.cs, MediaBrowser.Api/UserLibrary/StudiosService.cs, MediaBrowser.Controller/Library/ILibraryManager.cs, MediaBrowser.Controller/Persistence/IItemRepository.cs, MediaBrowser.Model/Serialization/IJsonSerializer.cs
=> Minor changes to reduce allocations

Emby.Dlna/PlayTo/Device.cs
**Changes**
Try to manipulate the xml in various ways before giving up.
**Issues**
Fixes #789
=> Fix uncaught xml error

Jellyfin.Server/SocketSharp/HttpFile.cs, Jellyfin.Server/SocketSharp/HttpPostedFile.cs, Jellyfin.Server/SocketSharp/RequestMono.cs, Jellyfin.Server/SocketSharp/WebSocketSharpResponse.cs
While I was there I also fixed some more warnings.
=> Separate HttpPostedFile into it's own file

Jellyfin.Server/Program.cs
Ref: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Environment.Unix.cs#L138
**This ignores existing installs on windows**
=> Simplify code to get data dir

.gitmodules
This is essentially a copy of #975, but for `master` branch.
=> Backmerge submodule updating strategy

Dockerfile, Dockerfile.arm, Dockerfile.arm64, deployment/common.build.sh, deployment/debian-package-x64/pkg-src/rules, deployment/fedora-package-x64/pkg-src/jellyfin.spec
**Changes**
Build Package releases without Debugging turned on as mentioned in #940.
Needs #964 as Fedora packaging is broken until then.
**Issues**
N/A
**Blocked by**
#964
=> Build Package releases without debug turned on

Jellyfin.Server/SocketSharp/WebSocketSharpListener.cs
**Changes**
Removed an unnecessary function and changed the caller to not close the response multiple times.
=> Don't close the socket response multiple times

Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Data/SqliteItemRepository.cs, Emby.Server.Implementations/HttpServer/HttpListenerHost.cs, Emby.Server.Implementations/ScheduledTasks/Triggers/DailyTrigger.cs
My last PR #1003 didn't log properly. This will also make it easier to read for `TimeSpan`s longer than 1sec.
=> Log time in a standardized way

MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
Re-implements the reverted fix for ffmpeg 4.1.
=> Start with ffmpeg 4.1 support

Jellyfin.Server/SocketSharp/RequestMono.cs, Jellyfin.Server/SocketSharp/WebSocketSharpRequest.cs
Wanted to take the new `Span` for a spin :p
=> Less string allocations

Emby.Server.Implementations/Channels/ChannelPostScanTask.cs
=> Reduce the amount of db calls during the post scan event

Emby.Server.Implementations/Services/ServicePath.cs, Emby.Server.Implementations/Services/StringMapTypeDeserializer.cs
Did some cleanup while I was there.
=> Reduce string allocations at startup

Emby.Server.Implementations/Dto/DtoService.cs, Emby.Server.Implementations/Session/SessionManager.cs, MediaBrowser.Api/BaseApiService.cs, MediaBrowser.Api/FilterService.cs, MediaBrowser.Api/UserLibrary/ItemsService.cs, MediaBrowser.Controller/Dto/DtoOptions.cs, MediaBrowser.Controller/Dto/IDtoService.cs, MediaBrowser.Controller/Entities/Folder.cs
* Don't try and return the items in the same order as they were requested, this is guarantied nowhere and only add complexity and takes time.
* Remove some unneeded checks.
EDIT: just tested on my pi, the request time went down from 10sec to 230ms
=> Don't try to order the response the same as the request

SharedVersion.cs, deployment/debian-package-x64/pkg-src/changelog, deployment/fedora-package-x64/pkg-src/jellyfin.spec
The last PR for Docker fixes to backmerge.
=> Backmerge for 10.2.2

Emby.XmlTv/Emby.XmlTv/Classes/XmlTvReader.cs
**Changes**
Implement and use SxxExx Episode numbering system from guide data if available.
**Issues**
Fixes #1008
=> Implement SxxExx EpisodeNum Processing

DvdLib/Ifo/Dvd.cs, Emby.Dlna/ContentDirectory/ControlHandler.cs, Emby.Dlna/Didl/DidlBuilder.cs, Emby.Dlna/DlnaManager.cs, Emby.Dlna/Main/DlnaEntryPoint.cs, Emby.Dlna/PlayTo/TransportCommands.cs, Emby.Naming/TV/EpisodePathParser.cs, Emby.Server.Implementations/Activity/ActivityManager.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Channels/ChannelManager.cs, Emby.Server.Implementations/Data/SqliteUserDataRepository.cs
Some loops iterated multiple times over the same data for no good reason.
=> Readability changes

Jellyfin.Server/Program.cs
These slipped in with the kestrel PR.
=> Fix the 2 new warnings

Emby.Dlna/PlayTo/Device.cs, Emby.Server.Implementations/Diagnostics/CommonProcess.cs, Emby.Server.Implementations/Library/LibraryManager.cs, Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs, Emby.Server.Implementations/LiveTv/EmbyTV/ItemDataProvider.cs, Emby.Server.Implementations/MediaEncoder/EncodingManager.cs, MediaBrowser.Api/ApiEntryPoint.cs, MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs, MediaBrowser.LocalMetadata/Images/InternalMetadataFolderImageProvider.cs, MediaBrowser.MediaEncoding/Encoder/EncodingUtils.cs, MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs, MediaBrowser.Providers/MediaInfo/SubtitleResolver.cs, SocketHttpListener/Net/HttpConnection.cs
Removing a library is instant now.
=> Reduce the amount of exceptions thrown

Emby.Server.Implementations/HttpServer/HttpListenerHost.cs, Emby.Server.Implementations/Services/ServiceExec.cs, Emby.Server.Implementations/SocketSharp/WebSocketSharpListener.cs, Emby.Server.Implementations/SocketSharp/WebSocketSharpRequest.cs, Emby.Server.Implementations/SocketSharp/WebSocketSharpResponse.cs, MediaBrowser.Model/Services/IRequest.cs
**Changes**
Check if headers have already been sent with `HasStarted`.
Also did some minor cleanup that should help getting rid of websocket-sharp eventually.
=> Don't set status code if response is closed

Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/HttpServer/HttpListenerHost.cs, MediaBrowser.Controller/Net/IHttpServer.cs
**Changes**
Add urlprefixes to the 'http server' to avoid crashing when saving certain dashboard settings
=> Add urlprefixes during init

Emby.Server.Implementations/ApplicationHost.cs
**Changes**
Title
At least until we can create some saner options
=> Disable HTTPS in Kestrel if Certificate is null

Emby.Server.Implementations/ConfigurationOptions.cs, MediaBrowser.Providers/MediaBrowser.Providers.csproj, MediaBrowser.Providers/Music/MusicBrainzAlbumProvider.cs
We should really overhaul the current configuration code.
=> Make MusicBrainz base url configurable

Emby.Server.Implementations/Activity/ActivityLogEntryPoint.cs, Emby.Server.Implementations/Emby.Server.Implementations.csproj, Emby.Server.Implementations/SocketSharp/HttpPostedFile.cs, Jellyfin.Server/Jellyfin.Server.csproj, jellyfin.ruleset
CI will now fail on style issues inside of the `Jellyfin.Server` project
Time to start on `Emby.Serer.Implementations` ;)
=> Fail on warnings for Jellyfin.Server

Emby.Server.Implementations/ApplicationHost.cs
For some reason this wasn't added yet...
=> Add AppConfig to the DI service collection

MediaBrowser.Providers/Music/MusicBrainzAlbumProvider.cs
Looks like a wrong auto merge. (We really should fix CI)
=> Fix build by removing non existent namespace

Dockerfile, Dockerfile.arm, Dockerfile.arm64, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/IStartupOptions.cs, Jellyfin.Server/StartupOptions.cs, MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs, deployment/debian-package-x64/pkg-src/conf/jellyfin, deployment/debian-package-x64/pkg-src/jellyfin.service, deployment/fedora-package-x64/pkg-src/jellyfin.env, deployment/fedora-package-x64/pkg-src/jellyfin.service
Removed --ffprobe from src files and server/docker scripts.
Fixes:
#1068
=> Finalise removal of --ffprobe switch

.ci/azure-pipelines.yml
**Changes**
Instead of using the nuget packages for the comparison, use the latest passing master build.
=> Do not use the nuget packages for comparison, but the last master build

Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Diagnostics/CommonProcess.cs, Emby.Server.Implementations/Library/LibraryManager.cs, Emby.Server.Implementations/Localization/LocalizationManager.cs, Emby.Server.Implementations/Session/SessionManager.cs, Emby.Server.Implementations/Sorting/AlbumArtistComparer.cs, Emby.Server.Implementations/Sorting/SeriesSortNameComparer.cs, MediaBrowser.Api/BaseApiService.cs, MediaBrowser.Api/UserLibrary/ArtistsService.cs, MediaBrowser.Providers/Manager/ProviderManager.cs, MediaBrowser.Providers/Music/MusicBrainzAlbumProvider.cs, MediaBrowser.Providers/Music/MusicBrainzArtistProvider.cs
=> More warning fixes

BDInfo/Properties/AssemblyInfo.cs, DvdLib/Properties/AssemblyInfo.cs, Emby.Dlna/Properties/AssemblyInfo.cs, Emby.Drawing/Properties/AssemblyInfo.cs, Emby.IsoMounting/IsoMounter/Properties/AssemblyInfo.cs, Emby.Naming/Properties/AssemblyInfo.cs, Emby.Notifications/Properties/AssemblyInfo.cs, Emby.Photos/Properties/AssemblyInfo.cs, Emby.Server.Implementations/Properties/AssemblyInfo.cs, Emby.XmlTv/Emby.XmlTv/Properties/AssemblyInfo.cs, Jellyfin.Drawing.Skia/Properties/AssemblyInfo.cs, Jellyfin.Server/Properties/AssemblyInfo.cs, MediaBrowser.Api/Properties/AssemblyInfo.cs, MediaBrowser.Common/Properties/AssemblyInfo.cs, MediaBrowser.Controller/Properties/AssemblyInfo.cs, MediaBrowser.LocalMetadata/Properties/AssemblyInfo.cs, MediaBrowser.MediaEncoding/Properties/AssemblyInfo.cs, MediaBrowser.Model/Properties/AssemblyInfo.cs, MediaBrowser.Providers/Properties/AssemblyInfo.cs, MediaBrowser.Tests/Properties/AssemblyInfo.cs, MediaBrowser.WebDashboard/Properties/AssemblyInfo.cs, MediaBrowser.XbmcMetadata/Properties/AssemblyInfo.cs, Mono.Nat/Properties/AssemblyInfo.cs, RSSDP/Properties/AssemblyInfo.cs
**Changes**
Changes all `AssemblyProduct` values to `Jellyfin Server`
=> Adjusted the Product Name so the User Agent is correct/better.

Dockerfile.arm, Dockerfile.arm64
**Changes**
Clean the apt lists in the arm Dockerfiles, too
=> Clean apt lists in arm Dockerfiles

MediaBrowser.Common/Providers/SubtitleConfigurationFactory.cs
#1096 removed a file required by `FFProbeVideoInfo`, resulting in a `ResourceNotFoundException`
```cs
MediaBrowser.Common.Extensions.ResourceNotFoundException: Configuration
with key subtitles not found.
at
Emby.Server.Implementations.AppBase.BaseConfigurationManager.<>c__DisplayClass42_0.<GetConfiguration>b__0(String
k) in
/home/pi/dev/jellyfin/Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs:line
247
at
System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey
key, Func`2 valueFactory)
at
Emby.Server.Implementations.AppBase.BaseConfigurationManager.GetConfiguration(String
key) in
/home/pi/dev/jellyfin/Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs:line
238
at
MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.AddExternalSubtitles(Video
video, …
```
=> Fix exception caused by #1096

MediaBrowser.Providers/Music/MusicBrainzAlbumProvider.cs
Upon receiving back a 503 Service Unavailable from MusicBrainz (indicating throttling), retry the same request a number of times before giving up.
Fixes:
#1113
=> MusicBrainz 503 Retry Strategy

MediaBrowser.Controller/MediaEncoding/JobLogger.cs
The stream could have been disposed while writing.
Prevents exception like this:
```cs
System.ObjectDisposedException: Safe handle has been closed
at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
at Interop.Sys.FSync(SafeFileHandle fd)
at System.IO.FileStream.FlushOSBuffer()
at System.IO.FileStream.<>c.<FlushAsyncInternal>b__100_0(Object state)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at …
```
=> Check before flushing ffmpeg log

Emby.Dlna/PlayTo/PlayToController.cs
**Changes**
Reorder some checks and properly dispose the object.
**Issues**
(Should) Fix #1078
=> Check if disposed first

Emby.Server.Implementations/ApplicationHost.cs
This whole process should be overhauled, this just moves the line to another place.
**Issues**
Fixes #1162
=> Fix exception on startup

Emby.Server.Implementations/Library/DefaultPasswordResetProvider.cs
These caused build failures.
Fixes #1162.
=> Correct bad quote characters

deployment/windows/install-jellyfin.ps1
You can use the emby import to move an existing library this way.
=> Updates windows installer default lib location

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
**Changes**
Makes the default "Exists on System Path" check also check the Jellyfin dir for better windows compat
**Issues**
Fixes #1185
=> Make Jellyfin search its base dir for ffmpeg

Emby.Server.Implementations/Library/UserManager.cs
**Changes**
Pass back the Username directive returned by an AuthenticationProvider
to the calling code, so we may override the user-provided Username
value if the authentication provider passes this back. Useful for
instance in an LDAP scenario where what the user types may not
necessarily be the "username" that is mapped in the system, e.g.
the user providing 'mail' while 'uid' is the "username" value.
Could also then be extensible to other authentication providers
as well, should they wish to do a similar thing.
~~We might extend this to other fields too, specifically isAdmin.~~ This is not likely to ever be needed, since the user doesn't enter this anywhere like they do with the "username".
Also enforces that AuthProvider plugins must do the user creation for non-default AuthProviders, …
=> Override username with AuthenticationProvider

Emby.Server.Implementations/Configuration/ServerConfigurationManager.cs
=> Fix metadata path save

MediaBrowser.Controller/Entities/BaseItemExtensions.cs
```cs
|    Method |      Mean |     Error |    StdDev | Rank | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|---------- |----------:|----------:|----------:|-----:|------------:|------------:|------------:|--------------------:|
|  DeepCopy | 183.98 us | 1.2403 us | 1.0995 us |    2 |     10.7422 |           - |           - |            33.37 KB |
| DeepCopy2 |  66.64 us | 0.1954 us | 0.1632 us |    1 |      5.9814 |           - |           - |            18.39 KB |
```
This change speeds up DeepCopy by a factor of 2.76x while reducing memory
allocation by 1.8x
EDIT: after more improvements
```cs
|    Method |      Mean |     Error |    StdDev | Rank | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|---------- …
```
=> Speed up DeepCopy

Emby.Server.Implementations/Activity/ActivityLogEntryPoint.cs, Emby.Server.Implementations/ApplicationHost.cs, MediaBrowser.Common/IApplicationHost.cs
Release builds were failing because of this unused event.
=> Remove unused event

Emby.Server.Implementations/Data/SqliteUserRepository.cs
Untested, but it should fix the empty pw migration issues
=> Fix comparison for empty password migration

Emby.Server.Implementations/ApplicationHost.cs
=> Handle exception when loading unsupported assembly

Emby.Server.Implementations/HttpServer/FileWriter.cs, Emby.Server.Implementations/HttpServer/HttpListenerHost.cs, Emby.Server.Implementations/HttpServer/HttpResultFactory.cs, Emby.Server.Implementations/HttpServer/RangeRequestWriter.cs, Emby.Server.Implementations/HttpServer/ResponseFilter.cs, Emby.Server.Implementations/HttpServer/StreamWriter.cs, Emby.Server.Implementations/Services/HttpResult.cs, Emby.Server.Implementations/Services/ResponseHelper.cs, MediaBrowser.Api/Playback/Progressive/BaseProgressiveStreamingService.cs
=> Re-add content length, semi revert of changes in #1010

MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs
=> Make the TvdbEpisodeProvider class Public

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
=> Limit amount of ffmpeg processes extracting images at once

MediaBrowser.Api/Library/LibraryService.cs
**Changes**
The issue is caused by the fact that kestrel currently doesn't accept non-ASCII characters in headers. It might be fixed in .NET Core 3.0 https://github.com/aspnet/AspNetCore/issues/4727. But for now, this PR manually follows https://tools.ietf.org/html/rfc5987#section-3.2.2 to encode UTF-8 filenames.
I decided to only encode that specific header and only the instances with UTF-8 characters to limit the impact if there's an issue with the PR. 
Was tested on Mac with Chrome, Firefox and Safari.
**Issues**
Closes https://github.com/jellyfin/jellyfin/issues/1289
=> Fix non-ascii filename downloads

README.md
**Changes**
The link was bad with respect to the changes in jellyfin/jellyfin-docs#67.
**Issues**
N/A
=> Update getting-help link in README

Emby.Photos/PhotoProvider.cs, Emby.Server.Implementations/Library/Resolvers/PhotoResolver.cs
=> Ignore casing photo extensions

Emby.Server.Implementations/Library/DefaultAuthenticationProvider.cs, Emby.Server.Implementations/Library/UserManager.cs
**Changes**
The new `EasyPassword` format contains the hash and the hashing function. This PR uses the `PasswordHash` to extract the actual hash.
**Issues**
Closes https://github.com/jellyfin/jellyfin/issues/1326
Maybe helps https://github.com/jellyfin/jellyfin/issues/1329 but not 100% sure.
=> Fix broken pin in 10.3.z

Emby.Server.Implementations/Library/DefaultAuthenticationProvider.cs, Emby.Server.Implementations/Library/UserManager.cs, MediaBrowser.Controller/Authentication/IAuthenticationProvider.cs
I forgot to format the PIN (`$SHA1$...`) when updating it. This PR ensures that the PIN has the right format.
I would appreciate a review from @LogicalPhallacy 	
Closes https://github.com/jellyfin/jellyfin/issues/1386
Was introduced by https://github.com/jellyfin/jellyfin/pull/1372
=> Format the PIN when updating it

MediaBrowser.Providers/TV/TheTVDB/TvDbClientManager.cs
=> Fix inverted comparison in the tvdb token refresh logic

MediaBrowser.Api/ApiEntryPoint.cs, MediaBrowser.Api/Playback/BaseStreamingService.cs, MediaBrowser.Api/Playback/StreamState.cs, MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs, MediaBrowser.Controller/MediaEncoding/JobLogger.cs, MediaBrowser.Model/Dlna/ContentFeatureBuilder.cs
Mostly small changes as I was looking through the code.
* async void -> async Task
* Properly implemented dispose methods
* Pass the logstream directly to the JobLogger
* Style fixes
=> Trying to make sense of the streaming code

MediaBrowser.Api/Playback/Hls/BaseHlsService.cs, MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs, MediaBrowser.Api/Playback/Hls/VideoHlsService.cs
Fixes the build broken by #1159
=> Change UsCulture to InvariantCulture

Dockerfile.arm, Dockerfile.arm64
**Changes**
Update arm* Dockerfiles for latest multiarch images
Relates to this change https://github.com/multiarch/qemu-user-static/commit/7bdafb96ee59fde53d07a291f9446d2b8957d372
=> Docker - Update arm* Dockerfiles for latest multiarch

Emby.Server.Implementations/Activity/ActivityLogEntryPoint.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Channels/ChannelManager.cs, Emby.Server.Implementations/Dto/DtoService.cs, Emby.Server.Implementations/Security/AuthenticationRepository.cs, Emby.Server.Implementations/Services/StringMapTypeDeserializer.cs, Emby.Server.Implementations/Session/SessionManager.cs, MediaBrowser.Controller/Entities/UserView.cs, MediaBrowser.Controller/Entities/UserViewBuilder.cs
The unrelated changes from #1023 (and more)
=> Small cleanups here and there

.github/ISSUE_TEMPLATE/media_playback.md
**Changes**
Added media playback issue template. We might want to add some more information requests in there.
=> Create Media Playback issue template

MediaBrowser.Providers/TV/TheTVDB/TvDbClientManager.cs
**Changes**
The authentication calls were async but never awaited...
**Issues**
Fixes #1356
=> Wait for the async authentication to finish when the JTW token expires

Emby.Server.Implementations/IO/ManagedFileSystem.cs, Jellyfin.Drawing.Skia/SkiaEncoder.cs, Jellyfin.Drawing.Skia/StripCollageBuilder.cs, Jellyfin.Server/Program.cs
Improved the way how some parts of the code depend on each other.
Fixed some style issues
=> Improve main code flow

MediaBrowser.Api/UserService.cs
related to jellyfin/jellyfin-web#378
=> Add optional password field on user creation

deployment/windows/install-jellyfin.ps1
Qualified Namespace of pscredential, otherwise script fails in Powershell builds <3.0.
**Changes**
**Issues**
=> Qualified Namespace of pscredential

.ci/azure-pipelines.yml
**Changes**
Many tries to get it working, it works from the UI designer.
UPDATE: now switched to next gen artifacts
=> Azure Pipelines DownloadBuildArtifacts@0 Experiment

Emby.Server.Implementations/Data/BaseSqliteRepository.cs
=> Move VACUUM command to fix merge error

.ci/azure-pipelines.yml
**Changes**
Update the GitHub connection name to use the GitHub App token
=> Update the GitHub connection name to use the GitHub App token

deployment/debian-package-arm64/docker-build.sh, deployment/debian-package-armhf/docker-build.sh, deployment/debian-package-x64/docker-build.sh, deployment/ubuntu-package-arm64/docker-build.sh, deployment/ubuntu-package-armhf/docker-build.sh, deployment/ubuntu-package-x64/docker-build.sh
**Changes**
Required for nightlies, which would not match this file format with the
underscore then wildcard.
**Issues**
N/A
=> Use dash or underscore on mv command

Emby.Dlna/PlayTo/SsdpHttpClient.cs, Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs, MediaBrowser.Common/Net/HttpRequestOptions.cs, Mono.Nat/Upnp/Messages/UpnpMessage.cs
**Changes**
Port of #1522 to 10.3.X release branch.
The third commit (903e7607b85f4060086b42bc17cf5d95f400cbe8) was unnecessary on the release branch.
**Issues**
Fixes https://github.com/jellyfin/jellyfin-plugin-gotify/issues/2
Fixes https://github.com/jellyfin/jellyfin-plugin-trakt/issues/20
Fixes https://github.com/jellyfin/jellyfin-plugin-trakt/issues/22
Fixes https://github.com/jellyfin/jellyfin/issues/1532
Fixes https://github.com/jellyfin/jellyfin/issues/1493
=> Properly set content type

Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs, Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs, MediaBrowser.Common/Net/HttpResponseInfo.cs
**Changes**
Port of #1528 to 10.3.X release branch.
**Issues**
Fixes #1525
=> Try to fix XmlTvListingsProvider

Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs
The stream is already buffered when using `ResponseContentRead`, so we don't need to do it our self.
=> Don't copy the complete response stream

.ci/azure-pipelines.yml
**Changes**
Adds the Azure Pipeline logging support flag to the CI command line.
=> Add the --azure-pipelines switch to the compat checker

Emby.Server.Implementations/Library/CoreResolutionIgnoreRule.cs, Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs, MediaBrowser.Controller/Resolvers/IResolverIgnoreRule.cs
Fix some style issues, some were introduced in #1247
=> Fix style issues

README.md
**Changes**
Adds (static) shield for Fider to README
=> Add Fider to README

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Issues**
Fixes #1388
Fixes #1472
=> Fix #1388 and #1472

MediaBrowser.Providers/TV/TheTVDB/TvdbSeriesProvider.cs
**Changes**
Adds a null check for Network name from TVDB data, before it is added in.
**Issues**
Related to #1531
=> Adds null check on studio/network name

Emby.Server.Implementations/HttpServer/FileWriter.cs
**Changes**
Set log level to debug for when a HTTP client does a requests with a range headers
**Issues**
=> Set log level to debug for HTTP range requests

Emby.Server.Implementations/Cryptography/CryptographyProvider.cs, Emby.Server.Implementations/Library/DefaultAuthenticationProvider.cs, Emby.Server.Implementations/Library/DefaultPasswordResetProvider.cs, Emby.Server.Implementations/Library/InvalidAuthProvider.cs, Emby.Server.Implementations/Library/UserManager.cs, MediaBrowser.Api/LiveTv/LiveTvService.cs, MediaBrowser.Controller/Authentication/AuthenticationException.cs, MediaBrowser.Controller/Authentication/IAuthenticationProvider.cs, MediaBrowser.Controller/Authentication/IPasswordResetProvider.cs, MediaBrowser.Model/Cryptography/ICryptoProvider.cs, MediaBrowser.Model/Cryptography/PasswordHash.cs
* Add new exception specifically for authentication
* Store salt and hash only a single time
* Mark useless abstractions as obsolete
* Remove legacy code
* Properly dispose disposable fields
* Break plugins
=> Streamline authentication proccess

Emby.Server.Implementations/Activity/ActivityLogEntryPoint.cs, Emby.Server.Implementations/Emby.Server.Implementations.csproj, Emby.Server.Implementations/ScheduledTasks/Tasks/PluginUpdateTask.cs, Emby.Server.Implementations/Updates/InstallationManager.cs, MediaBrowser.Api/PackageService.cs, MediaBrowser.Common/Updates/IInstallationManager.cs, MediaBrowser.Model/Updates/PackageVersionInfo.cs, MediaBrowser.Providers/Omdb/OmdbProvider.cs
Improve public api (`IInstallationManager`)
=> Improvements to InstallationManager

Emby.Naming/Emby.Naming.csproj, Emby.Photos/Emby.Photos.csproj, Emby.Server.Implementations/Emby.Server.Implementations.csproj, Jellyfin.Server/CoreAppHost.cs, Jellyfin.Server/Jellyfin.Server.csproj, Jellyfin.Server/Program.cs, Jellyfin.Server/StartupOptions.cs, MediaBrowser.MediaEncoding/MediaBrowser.MediaEncoding.csproj
* Fixed the release build
* Documented all public/internal members of Jellyfin.Server
* Enable TreatWarningsAsErrors for debug builds for Jellyfin.Server
* Updated all dependencies
This will ensure that any new public/internal members of Jellyfin.Server
are documented
=> Update deps + document startup project

Emby.Dlna/PlayTo/SsdpHttpClient.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs, Emby.Server.Implementations/ScheduledTasks/Tasks/PluginUpdateTask.cs, Emby.Server.Implementations/Updates/InstallationManager.cs, MediaBrowser.Api/PackageService.cs, MediaBrowser.Common/Extensions/HexHelper.cs, MediaBrowser.Common/Net/HttpRequestOptions.cs, MediaBrowser.Common/Net/IHttpClient.cs, MediaBrowser.Common/Updates/IInstallationManager.cs, MediaBrowser.Model/Cryptography/PasswordHash.cs, MediaBrowser.Model/Updates/InstallationInfo.cs, MediaBrowser.Providers/Studios/StudiosImageProvider.cs, Mono.Nat/Upnp/Messages/GetServicesMessage.cs, Mono.Nat/Upnp/Messages/UpnpMessage.cs, Mono.Nat/Upnp/UpnpNatDevice.cs, jellyfin.ruleset
* Compare the MD5 checksum when downloading plugins
* Reduced log spam due to http requests
* Removed 'GetTempFileResponse' function from HttpClientManager
* Fixed caching for HttpClientManager
=> Check checksum for plugin downloads

Emby.Notifications/NotificationManager.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Data/SqliteUserDataRepository.cs, Emby.Server.Implementations/EntryPoints/RefreshUsersMetadata.cs, Emby.Server.Implementations/Library/DefaultPasswordResetProvider.cs, Emby.Server.Implementations/Library/UserManager.cs, Emby.Server.Implementations/Session/SessionManager.cs, MediaBrowser.Api/UserService.cs, MediaBrowser.Controller/Authentication/AuthenticationException.cs, MediaBrowser.Controller/Entities/User.cs, MediaBrowser.Controller/Library/IUserManager.cs
Removed legacy code to save user configs by name instead of by ID.
Replaced the array + lock with a concurrent dictionary.
This should result in faster user creation + deletion and possibly faster lookups by ID and make it easier to work with.
=> Improvements to UserManager

Emby.Dlna/PlayTo/SsdpHttpClient.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs, Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunManager.cs, Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunUdpStream.cs, Emby.Server.Implementations/LiveTv/TunerHosts/LiveStream.cs, Emby.Server.Implementations/LiveTv/TunerHosts/M3UTunerHost.cs, Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs, MediaBrowser.Model/IO/StreamDefaults.cs
Also removed empty `catch` blocks so we log possible errors to diagnose #1520
=> Clean up livestreaming code

Emby.IsoMounting/IsoMounter/Configuration/PluginConfiguration.cs, Emby.IsoMounting/IsoMounter/IsoMounter.csproj, Emby.IsoMounting/IsoMounter/LinuxIsoManager.cs, Emby.IsoMounting/IsoMounter/LinuxMount.cs, Emby.IsoMounting/IsoMounter/Plugin.cs, Emby.Server.Implementations/IO/IsoManager.cs, Emby.Server.Implementations/SocketSharp/WebSocketSharpListener.cs, MediaBrowser.Model/IO/IIsoManager.cs, MediaBrowser.Model/IO/IIsoMounter.cs, MediaBrowser.Model/Plugins/BasePluginConfiguration.cs
Do we even want to keep this "feature"?
=> Add analysers to Emby.IsoMounting and enable TreatWarningsAsErrors

deployment/windows/build-jellyfin.ps1, deployment/windows/jellyfin.nsi
**Changes**
- Updated build file to download and extract nsis binaries
- added nsi script file to compile a windows installer
**Issues**
https://github.com/jellyfin/jellyfin/issues/1506
=> Add NSIS installer build support

Jellyfin.Server/Program.cs
If an error occurred while starting the server which in turn caused an
exception in the dispose method of the apphost, the first exception
wouldn't get logged.
=> Fix possible hidden exceptions

MediaBrowser.Api/UserService.cs
**Changes**
Catch exception and add IP
Changed to 
`[$DateTime] [ERR] [$IP] $Message` from `[$DateTime] [ERR] $Message`
**Issues**
Fixes #1489
=> Log IP address on failed login attempt

MediaBrowser.Api/Playback/BaseStreamingService.cs, MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
**Changes**
See https://github.com/jellyfin/jellyfin/pull/1434#issuecomment-522082156
Since @Verequies seems busy, I am opening this PR. He is free to update his PR (#1434) and we'll close this one 🙂 
**Issues**
Fixes #555
=> Fix segment_time_delta value for ffmpeg 4.1

Dockerfile
**Changes**
Allows changing the ffmpeg version with a build argument. Will be using to test newer versions.
=> Make Docker ffmpeg version configurable

Emby.Server.Implementations/Configuration/ServerConfigurationManager.cs, Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteTranscodeFileTask.cs, Emby.Server.Implementations/ScheduledTasks/Tasks/RefreshMediaLibraryTask.cs, MediaBrowser.Providers/Manager/ProviderManager.cs
This is just some random stuff I changed while I was trying to fix the provider issue.
=> Move the transcode path and other small fixes

MediaBrowser.Providers/TV/TheTVDB/TvdbSeriesProvider.cs
**Changes**
Fixes an issue where TV metadata scanning never completes. See commit message.
=> Fix replace multiple spaces

Dockerfile
**Changes**
Fix the default build arg for ffmpeg version.
=> Fix default build arg

Emby.Server.Implementations/Library/LibraryManager.cs
**Context**
During startup, at some point in the last 2 nightly builds, the following crash can occur, causing Jellyfin startup to fail:
```
Sep 02 23:19:08 jf1.i.net jellyfin[25117]: [23:19:08] [ERR] Error creating recording folders                                                                                                                                           
Sep 02 23:19:08 jf1.i.net jellyfin[25117]: System.ArgumentNullException: Value cannot be null.                                                                                                                                         
Sep 02 23:19:08 jf1.i.net jellyfin[25117]: Parameter name: json …
```
=> Fix crash due to missing userRootFolder data

README.md
Currently links to a broken page
=> Fix translate link

MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
**Changes**
Added InvariantCulture to the string.Format call.
=> Fix culture problem on Windows for segment_time_delta argument.

.ci/publish-nightly.yml, .ci/publish-release.yml
**Changes**
These require the `Version` variable set and the release one also requires `UsedRunId` to be set to a valid run ID.
=> Add two manually triggered pipelines for publishing artifacts.

Emby.Server.Implementations/Library/UserManager.cs, MediaBrowser.Model/Users/UserPolicy.cs
=> Reset invalid login counter on successfull login

Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs, Emby.Server.Implementations/LiveTv/EmbyTV/ItemDataProvider.cs, Emby.Server.Implementations/LiveTv/EmbyTV/TimerManager.cs
* Stop locking 2+ times per operation
* Don't clone the list multiple times
* Keep the lock for the duration of the operation
=> Rewrite `ItemDataProvider` to be more robust

.ci/azure-pipelines.yml
Actually building it is for later, I'm making a diagram with build deps.
=> Add submodule update to CI build.

.ci/azure-pipelines.yml, .gitmodules, Dockerfile, Dockerfile.arm, Dockerfile.arm64, Jellyfin.Server/Program.cs, MediaBrowser.WebDashboard/MediaBrowser.WebDashboard.csproj
**Changes**
Removes submodule and add a build and copy for the web UI.
The `build` and `bump_version` scripts will need to be updated
=> Remove submodule and add clone and build to CI for web UI

Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
=> Add mediabrowser route back for now

Emby.Server.Implementations/ApplicationHost.cs, MediaBrowser.Model/Configuration/ServerConfiguration.cs, MediaBrowser.Model/System/PublicSystemInfo.cs
It's odd that JF still had code lying around for generating a self signed cert. Currently, it does not do this so this code has been removed.
JF also appears to have functions in place to modify provided certs? Warrants deeper investigation. JF should not be attempting modifications of any certs under any circumstance.
=> Remove WAN DDNS

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
=> Avoid editing preferences without user interaction

.ci/azure-pipelines.yml
=> Fix SourceBranch -> SourceBranchName in git clone for Web UI

deployment/portable/docker-build.sh
**Changes**
Fix bad build options for portable builds.
**Issues**
N/A
=> Properly build DLL for porable

README.md
Updates several links in the readme to point to our new docs location.
=> Update README for new docs location

Emby.Server.Implementations/Data/SqliteItemRepository.cs
=> Change slow query time logging to debug

README.md
**Changes**
Update translate badge in README to reflect core status and not all projects status.
**Issues**
N/A
=> Update translate badge in README

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
=> Fix System.NullReferenceException when playing Dvds copied to HDD

Jellyfin.Server/Program.cs
**Changes**
Reload logging.json file without requiring server restart
=> Reload logging.json on changes

Dockerfile, Dockerfile.arm, Dockerfile.arm64
Needs https://github.com/jellyfin/jellyfin-ffmpeg/pull/11
- Needed to resolve https://github.com/jellyfin/jellyfin/issues/1906
- Resolves https://github.com/jellyfin/jellyfin/issues/1911
=> Docker fixes

MediaBrowser.Api/UserLibrary/PersonsService.cs
Add favorite people section to favorite tab https://github.com/jellyfin/jellyfin-web/pull/548
=> update persons service 

MediaBrowser.Api/PackageService.cs, MediaBrowser.Model/Globalization/ILocalizationManager.cs, MediaBrowser.Model/MediaBrowser.Model.csproj, MediaBrowser.Model/Net/SocketReceiveResult.cs, MediaBrowser.Providers/Tmdb/Models/Search/MovieResult.cs
**Changes**
Fixed some casing and other formatting to make all the missing cref warnings go away.
EDIT: it fixes like 2 errors. locally it emits 0 warnings but CI emits many.
=> Fix the last of the docs warnings

Emby.Server.Implementations/Data/SqliteItemRepository.cs, Emby.Server.Implementations/Library/LibraryManager.cs, MediaBrowser.Controller/Entities/ICollectionFolder.cs, MediaBrowser.Controller/Entities/UserView.cs
Alternate solution for #1952
(Should) fix #1952
=> Deserialize with the correct type (and warning fixes)

Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Library/UserManager.cs
Should fix https://github.com/jellyfin/jellyfin/issues/1850
=> Fix easy password

Emby.Server.Implementations/Cryptography/CryptographyProvider.cs, Emby.Server.Implementations/Library/DefaultAuthenticationProvider.cs, Emby.Server.Implementations/Library/UserManager.cs, Emby.Server.Implementations/Library/UserViewManager.cs, Emby.Server.Implementations/Session/SessionManager.cs, MediaBrowser.Api/UserLibrary/UserViewsService.cs, MediaBrowser.Common/Cryptography/PasswordHash.cs, MediaBrowser.Controller/Entities/Folder.cs, MediaBrowser.Controller/Library/IUserManager.cs, MediaBrowser.Model/Cryptography/ICryptoProvider.cs
Also removes 2 unused methods.
=> Add clearer exceptions, warnings and docs

Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs, Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Configuration/ServerConfigurationManager.cs, Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs, Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunUdpStream.cs, Emby.Server.Implementations/LiveTv/TunerHosts/LiveStream.cs, Emby.Server.Implementations/LiveTv/TunerHosts/M3UTunerHost.cs, Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs, Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteTranscodeFileTask.cs, Emby.Server.Implementations/ServerApplicationPaths.cs, MediaBrowser.Api/ApiEntryPoint.cs, MediaBrowser.Api/Playback/BaseStreamingService.cs, MediaBrowser.Api/Playback/Hls/HlsSegmentService.cs, MediaBrowser.Common/Configuration/EncodingConfigurationExtensions.cs, MediaBrowser.Controller/IServerApplicationPaths.cs, MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs, MediaBrowser.MediaEncoding/Configuration/EncodingConfigurationFactory.cs
=> Don't append transcodes to transcoding temp path

Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteTranscodeFileTask.cs
=> Fix master build

Emby.Dlna/Api/DlnaServerService.cs
=> dlna GetPathValue

deployment/debian-package-arm64/Dockerfile.amd64, deployment/debian-package-arm64/Dockerfile.arm64, deployment/debian-package-arm64/docker-build.sh, deployment/debian-package-armhf/Dockerfile.amd64, deployment/debian-package-armhf/Dockerfile.armhf, deployment/debian-package-armhf/docker-build.sh, deployment/debian-package-x64/Dockerfile, deployment/debian-package-x64/docker-build.sh, deployment/debian-package-x64/pkg-src/control, deployment/linux-x64/Dockerfile, deployment/macos/Dockerfile, deployment/portable/Dockerfile, deployment/ubuntu-package-arm64/Dockerfile.amd64, deployment/ubuntu-package-arm64/Dockerfile.arm64, deployment/ubuntu-package-arm64/docker-build.sh, deployment/ubuntu-package-armhf/Dockerfile.amd64, deployment/ubuntu-package-armhf/Dockerfile.armhf, deployment/ubuntu-package-armhf/docker-build.sh, deployment/ubuntu-package-x64/docker-build.sh, deployment/win-x64/Dockerfile, deployment/win-x86/Dockerfile
=> Use .Net Core 3.0 in all docker images

.ci/azure-pipelines.yml
**Changes**
Changes the trigger condition to also trigger on tag builds.
=> Add tag building support to Windows Web build.

deployment/ubuntu-package-x64/Dockerfile
=> Fix ubuntu x64 docker build

MediaBrowser.Api/UserLibrary/ItemsService.cs, MediaBrowser.Model/Querying/QueryResult.cs
**Changes**
Add an API query result to help facilitate infinite scrolling
**Issues**
#2115
=> Add StartIndex result to /Items API query

Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj, Jellyfin.Drawing.Skia/PercentPlayedDrawer.cs, Jellyfin.Drawing.Skia/PlayedIndicatorDrawer.cs, Jellyfin.Drawing.Skia/SkiaCodecException.cs, Jellyfin.Drawing.Skia/SkiaEncoder.cs, Jellyfin.Drawing.Skia/SkiaException.cs, Jellyfin.Drawing.Skia/StripCollageBuilder.cs, Jellyfin.Drawing.Skia/UnplayedCountIndicator.cs, MediaBrowser.Controller/Drawing/IImageEncoder.cs, jellyfin.ruleset
Fix existing warnings in the `Jellyfin.Drawing.Skia` project and enable all analyzers.
**Issues**
Related to #2149
=> Jellyfin.Drawing.Skia Warnings and Analyzers

MediaBrowser.Api/Playback/BaseStreamingService.cs
=> Fix comparison between different types

Emby.Server.Implementations/Data/SqliteItemRepository.cs
**Changes**
Add Excluded Tags to SQLite query using parameters to avoid invalid SQL, or SQL injection type errors.
**Issues**
Fixes #2080
=> Add Excluded Tags to SQLite query using parameters

Emby.Server.Implementations/Library/UserManager.cs, MediaBrowser.Controller/Library/IUserManager.cs
Currently only the 2 files in the dir get deleted.
=> Delete user config dir on user deletion

MediaBrowser.MediaEncoding/Subtitles/JsonWriter.cs
Should fix this issue: https://github.com/jellyfin/jellyfin/pull/1941#issuecomment-570189445
=> Fix JSON subtitle writer

Emby.Server.Implementations/ApplicationHost.cs, MediaBrowser.Controller/IServerApplicationHost.cs
Adds the baseurl to the local api url
Fixes #2035
Fixes #2117
=> Fix baseurl (again)

.ci/azure-pipelines.yml, tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
**Changes**
Added the correct framework settings to the vstest task
=> Fix the VSTest runner

MediaBrowser.Api/Playback/MediaInfoService.cs, MediaBrowser.Api/Playback/UniversalAudioService.cs, MediaBrowser.Model/MediaInfo/PlaybackInfoResponse.cs
=> Minor changes to MediaInfoService

tests/Jellyfin.Api.Tests/Auth/CustomAuthenticationHandlerTests.cs, tests/Jellyfin.Api.Tests/Auth/FirstTimeSetupOrElevatedPolicy/FirstTimeSetupOrElevatedHandlerTests.cs, tests/Jellyfin.Api.Tests/Auth/RequiresElevationPolicy/RequiresElevationHandlerTests.cs, tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
**Changes**
Written tests covering authentication handling in the Jellyfin server
**Issues**
Fixes #2179
=> Test Jellyfin.Api authentication handling

Emby.Server.Implementations/EntryPoints/UdpServerEntryPoint.cs, Emby.Server.Implementations/Net/SocketFactory.cs, Emby.Server.Implementations/Net/UdpSocket.cs, Emby.Server.Implementations/Udp/UdpServer.cs, MediaBrowser.Model/Net/ISocket.cs, MediaBrowser.Model/Net/ISocketFactory.cs
* Use the raw socket directly instead of custom abstractions
* Use newer `async` api
=> Clean up server discovery code

deployment/windows/build-jellyfin.ps1, deployment/windows/jellyfin.nsi
LZMA -> BZIP2
7:45 min~ -> 3:00 min~
83MB -> 106MB
`!verbosity 4` -> `!verbosity 3`
=> Change NSIS log verbosity and use lesser but faster compression.

deployment/win-x64/docker-build.sh, deployment/win-x86/docker-build.sh, deployment/windows/build-jellyfin.ps1
**Changes**
Update ffmpeg x86/x64 to 4.2.1 for windows nightly channel same as `jellyfin-ffmpeg` version.
=> New upstream ffmpeg version 4.2.1 for windows nightly channel

Emby.Server.Implementations/Emby.Server.Implementations.csproj
**Changes**
Updates the SQLitePCL.pretty.netstandard package to the new 2.1.0 version.
=> Update SQLitePCL to new version

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Code adapted from here: https://github.com/chlorm-forks/Emby/blob/2cfeab0c16d6d8c46d2e433cf7e5e18e83b5de53/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs#L660
**Issues**
Fixes #2205
=> Add back support for DVDs copied as folders

Dockerfile.arm, Dockerfile.arm64
Also has the effect of updating ffmpeg to 4.1
=> Update ARM images to debian buster

Emby.Dlna/Api/DlnaServerService.cs, Emby.Dlna/ConnectionManager/ConnectionManager.cs, Emby.Dlna/ContentDirectory/ContentDirectory.cs, Emby.Dlna/ContentDirectory/ControlHandler.cs, Emby.Dlna/IUpnpService.cs, Emby.Dlna/MediaReceiverRegistrar/MediaReceiverRegistrar.cs, Emby.Dlna/Service/BaseControlHandler.cs, Emby.Dlna/Service/ControlErrorHandler.cs
Ref: https://github.com/dotnet/aspnetcore/issues/7644
**Issues**
Should fix #2164
=> Kestrel doesn't like sync IO operations

MediaBrowser.Model/Dto/MediaSourceInfo.cs
**Changes**
fix an issue that could not correctly determine 'IsSecondaryAudio' in some cases.
=> fix an issue that could not correctly determine 'IsSecondaryAudio' in some cases.

Dockerfile
**Changes**
Adds ca-certificates to the docker container.  Possibly needs to be applied to arm as well, but I can't test right now.  Paging @Artiume 
**Issues**
Fixes #2333
=> Add root certificates to docker image

Dockerfile.arm, Dockerfile.arm64
verified arm build on raspbian
**Changes**
**Issues**
=> fix SSL issue in arm and arm64

Emby.Server.Implementations/Library/UserManager.cs
=> Allow changing capitalization of usernames

deployment/ubuntu-package-arm64/Dockerfile.amd64, deployment/ubuntu-package-arm64/Dockerfile.arm64, deployment/ubuntu-package-armhf/Dockerfile.amd64, deployment/ubuntu-package-armhf/Dockerfile.armhf, deployment/ubuntu-package-x64/Dockerfile
**Changes**
Fixes web build failures in nightlies for Ubuntu and Debian.
**Issues**
N/A
=> Use NodeJS 10.X for NPM builds

README.md
**Changes**
The link https://docs.jellyfin.org/general/administration/quick-start.html is not accesible anymore. 
**Issues**
Non created.
=> Fix quick start guide url in readme

Dockerfile, Dockerfile.arm, Dockerfile.arm64
https://github.com/jellyfin/jellyfin-web/pull/735
I had to install git to get it to build ✌️
**Changes**
**Issues**
=> Update dockerfile to install git for new dependency

MediaBrowser.Controller/Net/IAuthService.cs, tests/Jellyfin.Api.Tests/Auth/CustomAuthenticationHandlerTests.cs, tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj, tests/Jellyfin.Common.Tests/Jellyfin.Common.Tests.csproj, tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTests.cs, tests/Jellyfin.MediaEncoding.Tests/Jellyfin.MediaEncoding.Tests.csproj, tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj, tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj
=> Enable TreatWarningsAsErrors and Nullable for test projects

Dockerfile.arm, Dockerfile.arm64
=> Fix arm32 built on amd64 host

.github/ISSUE_TEMPLATE/bug_report.md
Increase priority for system details, constantly have to ask people for their deets. also increased details that should be asked.
**Changes**
**Issues**
=> Update Bug Report for System Details

MediaBrowser.Controller/Entities/Photo.cs
=> Fix photo serialization

MediaBrowser.Api/Playback/BaseStreamingService.cs
=> Switch remux and direct stream

tests/Jellyfin.Naming.Tests/TV/EpisodePathParserTest.cs
Some test cases from the parsing episode number size are also good testcases for the general parser, hence I added them.
=> adds names from the episodenumber tests to path tests

MediaBrowser.Model/Configuration/EncodingOptions.cs
**Changes**
As stated on the tin.
**Issues**
Should help with some of the issues at https://github.com/jellyfin/jellyfin/issues/2273
=> Default transcoding throttling to false for new installs

MediaBrowser.Controller/Entities/Folder.cs
**Changes**
This is partial revert of https://github.com/jellyfin/jellyfin/pull/1011 with minor improvement (don't sort an array of 1 item).
Note: it was originally stated #1011 sped up loading of interface tremendously. I cannot find where this particular method would be called except in "PlayTo" functionality, so here's hoping nothing breaks 🤞 
I've also implemented faster method of sorting.
**Issues**
Fixes #1724
**Notes**
This requires proper testing.
=> Bring back sorting when needed to fix PlayTo

deployment/fedora-package-x64/Dockerfile
=> Update Fedora build container version

MediaBrowser.Common/Extensions/ShuffleExtensions.cs, MediaBrowser.Controller/Sorting/AlphanumComparator.cs, MediaBrowser.sln, tests/Jellyfin.Controller.Tests/AlphanumComparatorTests.cs, tests/Jellyfin.Controller.Tests/Jellyfin.Controller.Tests.csproj
Adds tests and speed
```
| Method |     Mean |    Error |   StdDev |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |---------:|---------:|---------:|--------:|------:|------:|----------:|
| New    | 10.02 us | 0.035 us | 0.031 us |  0.1068 |     - |     - |     336 B |
| Old    | 23.75 us | 0.109 us | 0.097 us | 11.2305 |     - |     - |   35272 B |
```
=> Improve alpha numeric sorting

Dockerfile, Dockerfile.arm, Dockerfile.arm64
https://github.com/jellyfin/jellyfin/issues/1901#issuecomment-593114951
Still need to compile with the packages to verify it builds properly. Arm builds probably need it too.
**Changes**
**Issues**
=> Fix Docker packages

MediaBrowser.Controller/Entities/BaseItem.cs
**Changes**
Speed up equality comparison of BaseItem. Should help in `.Distinct()` calls and so on.
**Issues**
N/A
=> Adds BaseItem.Equals method that compares items by their Id

.ci/azure-pipelines-main.yml, .ci/azure-pipelines-windows.yml
Update AzureCI script to build the web client correctly.
=> Fix Azure Pipelines Build

MediaBrowser.Model/Net/MimeTypes.cs
**Changes**
add wasm mime-type
WebAssembly requires response match `application/wasm` MIME type
=> add wasm mimetype

Dockerfile, Dockerfile.arm, Dockerfile.arm64
=> Fix Release 10.5.z

Dockerfile, Dockerfile.arm, Dockerfile.arm64
**Changes**
Performance improvement and various updates https://github.com/jellyfin/jellyfin-web/pull/862#issuecomment-593440878
**Issues**
=> Update docker dependencies for Gulp

Emby.Server.Implementations/Data/SqliteItemRepository.cs
**Changes**
Try to make search make more sense. At least make it so items which names _start_ with what you searched for are in the front of the list.
It also sorts by `SortName` column, which implementations for audio and episodes are questionable for search, but it's still better than current situation, where search results would end up being in undefined (DB-dependent) order.
**Issues**
Not sure, maybe there are some.
=> Fix ordering of search results

Emby.Server.Implementations/ApplicationHost.cs
Ref: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getexportedtypes?view=netcore-3.1#System_Reflection_Assembly_GetExportedTypes
=> Try to not crash on unsupported plugin load

Emby.Server.Implementations/ApplicationHost.cs
This should fix LiveTV and tuners
**Changes**
**Issues**
Probably fixes https://github.com/jellyfin/jellyfin/issues/2568 (cannot verify as I don't have a tuner)
=> Fix GetLocalApiUrl for cases with https enabled

Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs, Emby.Server.Implementations/LiveTv/EmbyTV/DirectRecorder.cs, Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs, Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs, Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs, MediaBrowser.Common/Cryptography/CryptoExtensions.cs, MediaBrowser.Common/MediaBrowser.Common.csproj, MediaBrowser.Common/Net/HttpRequestOptions.cs, MediaBrowser.Common/Net/HttpResponseInfo.cs
=> Enable Microsoft.CodeAnalysis.FxCopAnalyzers for Jellyfin.Common

Emby.Server.Implementations/ApplicationHost.cs
Fixes this crash: https://github.com/jellyfin/jellyfin-plugin-fanart/issues/12
=> Remove PluginInstalled

MediaBrowser.Api/Playback/MediaInfoService.cs
**Changes**
* Revert "Add baseURL to attachments"
* This is properly handled by https://github.com/jellyfin/jellyfin-web/pull/1020
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/2781
=> Fix support for attachments with baseURL set

CONTRIBUTORS.md, Dockerfile.arm
=> Fix ffmpeg path on ARM docker image

Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
This might help diagnosing stuff like "Operation was cancelled"
**Changes**
Explicitly log a URL being processed (if possible) when logging an error occurred during handling the request.
**Issues**
N/A
=> Add logging of URL being processed when logging an error

Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
Fixes the merge done in https://github.com/jellyfin/jellyfin/commit/67194994f9ed11b6fb0b8defb063c4bc6c7a38de
=> Fix compilation error in HttpListenerHost

Emby.Server.Implementations/Library/UserManager.cs
**Changes**
Added IP to authentication request log
**Issues**
=> Authentication request log with IP

DvdLib/BigEndianBinaryReader.cs, DvdLib/DvdLib.csproj, DvdLib/Ifo/Dvd.cs, Emby.Server.Implementations/Library/LibraryManager.cs, MediaBrowser.Providers/MediaInfo/FFProbeProvider.cs, MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs, MediaBrowser.Providers/MediaInfo/SubtitleResolver.cs
Makes it possible to move it out of the main repo in the future
=> DvdLib: remove dependency on MediaBrowser.Model

build, deployment/centos-package-x64/package.sh, deployment/debian-package-arm64/package.sh, deployment/debian-package-armhf/package.sh, deployment/debian-package-x64/package.sh, deployment/fedora-package-x64/package.sh, deployment/linux-x64/docker-build.sh, deployment/linux-x64/package.sh, deployment/macos/docker-build.sh, deployment/macos/package.sh, deployment/portable/docker-build.sh, deployment/portable/package.sh, deployment/ubuntu-package-arm64/package.sh, deployment/ubuntu-package-armhf/package.sh, deployment/ubuntu-package-x64/package.sh, deployment/win-x64/docker-build.sh, deployment/win-x64/package.sh, deployment/win-x86/docker-build.sh, deployment/win-x86/package.sh
Latest 10.5.4 release pulled in 10.5.3 web in a few packages. This PR aims to fix that, and we should be able to re-build the release using release branch when this is merged, as no code (except packaging) was changed.
**Note**: this pull request explicitly targets `release-10.5.z` branch.
**Changes**
* Compute `web_branch` based on tags first if it's not explicitly specified
* Fix passing variables to underlying docker containers
**Issues**
N/A
=> Fix passing web branch

Emby.Server.Implementations/Library/PathExtensions.cs, MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
**Changes**
Updated regex to allow more than 7 digits in imdb id. 
**Issues**
#2902
=> Fix imdbid regex

MediaBrowser.Api/UserLibrary/ItemsService.cs, MediaBrowser.Controller/Entities/BaseItem.cs, MediaBrowser.Controller/Entities/Folder.cs, MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
My git stash is getting too big to handle ;)
=> Minor improvements

.ci/azure-pipelines-test.yml, DvdLib/DvdLib.csproj, Emby.Dlna/Emby.Dlna.csproj, Emby.Drawing/Emby.Drawing.csproj, Emby.Naming/Emby.Naming.csproj, Emby.Notifications/Emby.Notifications.csproj, Emby.Photos/Emby.Photos.csproj, Emby.Server.Implementations/Emby.Server.Implementations.csproj, Jellyfin.Api/Jellyfin.Api.csproj, Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj, Jellyfin.Server/Jellyfin.Server.csproj, MediaBrowser.Api/MediaBrowser.Api.csproj, MediaBrowser.Common/MediaBrowser.Common.csproj, MediaBrowser.Controller/MediaBrowser.Controller.csproj, MediaBrowser.LocalMetadata/MediaBrowser.LocalMetadata.csproj, MediaBrowser.MediaEncoding/MediaBrowser.MediaEncoding.csproj, MediaBrowser.Model/MediaBrowser.Model.csproj, MediaBrowser.Providers/MediaBrowser.Providers.csproj, MediaBrowser.WebDashboard/MediaBrowser.WebDashboard.csproj, MediaBrowser.XbmcMetadata/MediaBrowser.XbmcMetadata.csproj, RSSDP/RSSDP.csproj, tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj, tests/Jellyfin.Common.Tests/Jellyfin.Common.Tests.csproj, tests/Jellyfin.Controller.Tests/Jellyfin.Controller.Tests.csproj, tests/Jellyfin.MediaEncoding.Tests/Jellyfin.MediaEncoding.Tests.csproj, tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj, tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj
This needs to go in before #2846 gets merged.
=> Add SonarCloud to the Azure Pipeline CI process

MediaBrowser.Controller/Entities/BaseItem.cs
Reverts jellyfin/jellyfin#2928 to fix targeted branch.
=> Revert "Fix eTags DateLastSaved"

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Search recursively for ffmpeg in app directory. This allows the ffmpeg binaries to live in their own directory like netcoreapp3.1/ff/
While here do some cleanup.
=> Try harder to find ffmpeg in app directory. 

Emby.Server.Implementations/HttpServer/HttpResultFactory.cs
**Changes**
Pass flag "store date as UTC" along with "parse date as UTC" so date from header is correct and comparable with "last modified" which is also in UTC.
Follow up for https://github.com/jellyfin/jellyfin/pull/2864
**Issues**
Fix cache becoming stale if local time was ahead of UTC.
=> Now parse date in header correctly as being in UTC

Emby.Server.Implementations/HttpServer/ResponseFilter.cs, Emby.Server.Implementations/Library/MediaStreamSelector.cs, Emby.Server.Implementations/Library/PathExtensions.cs, Emby.Server.Implementations/Library/ResolverHelper.cs, Emby.Server.Implementations/Services/StringMapTypeDeserializer.cs, Emby.Server.Implementations/Services/UrlExtensions.cs, Emby.Server.Implementations/SocketSharp/WebSocketSharpRequest.cs, MediaBrowser.Api/Playback/BaseStreamingService.cs, MediaBrowser.Common/Extensions/BaseExtensions.cs, MediaBrowser.Common/Extensions/CopyToExtensions.cs, MediaBrowser.Common/Extensions/MethodNotAllowedException.cs, MediaBrowser.Common/Extensions/ProcessExtensions.cs, MediaBrowser.Common/Extensions/RateLimitExceededException.cs, MediaBrowser.Common/Extensions/ResourceNotFoundException.cs, MediaBrowser.Common/Extensions/ShuffleExtensions.cs, MediaBrowser.Common/Extensions/StringExtensions.cs, MediaBrowser.Model/Entities/ProviderIdsExtensions.cs, tests/Jellyfin.Common.Tests/Extensions/StringExtensionsTests.cs, tests/Jellyfin.Server.Implementations.Tests/HttpServer/ResponseFilterTests.cs, tests/Jellyfin.Server.Implementations.Tests/Library/PathExtensionsTests.cs
Removed some duplicated code and added tests
=> Add some simple tests

Emby.Naming/Audio/AlbumParser.cs, Emby.Naming/Audio/AudioFileParser.cs, Emby.Naming/Common/EpisodeExpression.cs, Emby.Naming/Subtitles/SubtitleParser.cs, tests/Jellyfin.Model.Tests/Extensions/StringHelperTests.cs, tests/Jellyfin.Model.Tests/Jellyfin.Model.Tests.csproj, tests/Jellyfin.Naming.Tests/Music/MultiDiscAlbumTests.cs, tests/Jellyfin.Naming.Tests/Subtitles/SubtitleParserTests.cs
Covers more branches and should be faster
=> Improved tests

Jellyfin.Api/Controllers/NotificationsController.cs
=> Fix xml docs

.editorconfig, MediaBrowser.sln
Clean up .editorconfig file to fix some mis-named properties and values. Also removed settings for .vb files since we have none in the solution.
Also added the main ruleset file as a solution item so that it appears in visual studio.
=> Fix editorconfig Settings

Jellyfin.Server/Program.cs
Moved  appHost.EnableHttps to encompass certificate checking in dev mode
=> http in development mode crashed -

MediaBrowser.Model/Net/MimeTypes.cs
=> Remove ogg video mimetype

MediaBrowser.Providers/Tmdb/TV/TmdbSeriesProvider.cs, MediaBrowser.Providers/Tmdb/TmdbUtils.cs
**Changes**
Fixes some warnings in TmdbSeriesProvider and adds a few pieces of information (Original title, homepage, and series-level crew).
**Issues**
=> Add more information to TmdbSeriesProvider

MediaBrowser.Api/BaseApiService.cs, MediaBrowser.Api/Library/LibraryService.cs, MediaBrowser.Api/Movies/MoviesService.cs, MediaBrowser.Api/Playback/BaseStreamingService.cs, MediaBrowser.Api/Playback/Hls/BaseHlsService.cs, MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs, MediaBrowser.Api/Playback/MediaInfoService.cs, MediaBrowser.Api/Playback/Progressive/AudioService.cs, MediaBrowser.Api/Playback/Progressive/BaseProgressiveStreamingService.cs, MediaBrowser.Api/Playback/UniversalAudioService.cs, MediaBrowser.Api/UserLibrary/ArtistsService.cs, MediaBrowser.Api/UserLibrary/BaseItemsByNameService.cs
**Changes**
#3098 introduced some regressions, this PR should hopefully fix them
=> Fix regressions introduced by #3098

Emby.Server.Implementations/Library/Resolvers/Books/BookResolver.cs, MediaBrowser.Model/Net/MimeTypes.cs
=> Update Books Resolver File Types and add .opf Mime Type

MediaBrowser.Model/Entities/MediaStream.cs
**Changes**
Web side PR
https://github.com/jellyfin/jellyfin-web/pull/1231
**Issues**
=> Fix Progressive and Interlaced Stream capitalization

Emby.Server.Implementations/Emby.Server.Implementations.csproj, Jellyfin.Api/Jellyfin.Api.csproj, Jellyfin.Data/Jellyfin.Data.csproj, Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj, Jellyfin.Server/Jellyfin.Server.csproj, MediaBrowser.Common/MediaBrowser.Common.csproj, MediaBrowser.Controller/MediaBrowser.Controller.csproj, MediaBrowser.Model/MediaBrowser.Model.csproj, MediaBrowser.Providers/MediaBrowser.Providers.csproj, tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj, tests/MediaBrowser.Api.Tests/MediaBrowser.Api.Tests.csproj
Release notes are here: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.4/3.1.4.md
=> Update to .NET Core 3.1.4

Dockerfile
**Changes**
Install python before building jellyfin-web
**Issues**
=> Fix container image build by installing python

Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs
**Changes**
Make opening a LiveTV stream re-raise the exception if opening it failed.
**Issues**
Hopefully fixes https://github.com/jellyfin/jellyfin/issues/3065.
**Notes**
Requires testing as I cannot reproduce the issue myself.
cc @gled-rs
=> Re-raise the exception that caused LiveTV stream to not open

Emby.Server.Implementations/Emby.Server.Implementations.csproj, Emby.Server.Implementations/IO/LibraryMonitor.cs, Emby.Server.Implementations/Library/CoreResolutionIgnoreRule.cs, Emby.Server.Implementations/Library/IgnorePatterns.cs, tests/Jellyfin.Server.Implementations.Tests/Library/IgnorePatternsTests.cs
**Changes**
Unify the rules for ignoring files into a single set of glob patterns.
**Issues**
Closes #3070 
Closes #3032
Closes #3069
=> Use glob patterns to ignore files

Emby.Server.Implementations/Library/IgnorePatterns.cs
https://forum.jellyfin.org/t/library-not-loading/2086
**Changes**
**Issues**
=> Add lost+found to ignore list

MediaBrowser.Model/Net/MimeTypes.cs
**Changes**
Linky Links
https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst
http://www.mplayerhq.hu/DOCS/HTML/en/edl.html
http://edlmax.com/MAXGUIDE.HTML
https://en.wikipedia.org/wiki/Edit_decision_list
**Issues**
=> Add .edl Mimetype

Jellyfin.Api/Controllers/StartupController.cs
=> Convert StartupController to ActionResult

.vscode/tasks.json, Emby.Drawing/ImageProcessor.cs, Emby.Drawing/NullImageEncoder.cs, Emby.Server.Implementations/Data/SqliteItemRepository.cs, Emby.Server.Implementations/Dto/DtoService.cs, Emby.Server.Implementations/Library/LibraryManager.cs, Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj, Jellyfin.Drawing.Skia/SkiaEncoder.cs, MediaBrowser.Api/Images/ImageService.cs, MediaBrowser.Api/ItemUpdateService.cs, MediaBrowser.Controller/Drawing/IImageEncoder.cs, MediaBrowser.Controller/Drawing/IImageProcessor.cs, MediaBrowser.Controller/Entities/BaseItem.cs, MediaBrowser.Controller/Entities/Folder.cs, MediaBrowser.Controller/Entities/ItemImageInfo.cs, MediaBrowser.Controller/Library/ILibraryManager.cs, MediaBrowser.Model/Dto/BaseItemDto.cs, MediaBrowser.Model/Dto/ImageInfo.cs
**Changes**
This PR adds preliminary support for generating blurhash thumbnails on the backend. I'm not done with it though, and there are a couple of things I'd like to get some feedback on.
**Issues**
Provides backend for #2569
=> Implement Blurhash generation for images

MediaBrowser.Api/ApiEntryPoint.cs, MediaBrowser.Api/Playback/BaseStreamingService.cs, MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs, MediaBrowser.Api/Playback/Hls/VideoHlsService.cs, MediaBrowser.Api/Playback/StreamState.cs, MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs, MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs, MediaBrowser.Model/Configuration/EncodingOptions.cs
**Changes**
Refactor/deduplicate  `copy` codec checks
=> Refactor copy codec checks

Emby.Naming/Common/NamingOptions.cs
Filter "bd" / "BD" from file names to search for the correct name ( get better results for init scan )
**Changes**
+ add "bd" to CleanStrings regex
=> allow bd tag in file names

Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs, MediaBrowser.Common/Json/Converters/JsonNonStringKeyDictionaryConverter.cs, MediaBrowser.Common/Json/Converters/JsonNonStringKeyDictionaryConverterFactory.cs, MediaBrowser.Common/Json/JsonDefaults.cs
Attempt 2, hopefully with fewer commit breakage. 
#2967 Depends on this
=> Add Dictionary with non-string keys to System.Text.Json

Emby.Drawing/ImageProcessor.cs
=> reduce log spam when generating blurhashes

MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbSearch.cs
**Changes**
Clarify comment and log actual search string in TMDB search provider
**Issues**
=> Clarify comment and log actual search string in TMDB search provider

Emby.Server.Implementations/HttpServer/Security/AuthService.cs
**Changes**
Changed the import to the "legacy" Emby AuthenticationException instead of the System one.
**Issues**
Fixes #3290
=> Use the "legacy" AuthenticationException in AuthService

Emby.Server.Implementations/Emby.Server.Implementations.csproj, Jellyfin.Api/Jellyfin.Api.csproj, Jellyfin.Data/Jellyfin.Data.csproj, Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj, Jellyfin.Server/Jellyfin.Server.csproj, MediaBrowser.Common/MediaBrowser.Common.csproj, MediaBrowser.Controller/MediaBrowser.Controller.csproj, MediaBrowser.Model/MediaBrowser.Model.csproj, MediaBrowser.Providers/MediaBrowser.Providers.csproj, tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj, tests/MediaBrowser.Api.Tests/MediaBrowser.Api.Tests.csproj
Release notes: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.5/3.1.5.md
@anthonylavado - there is a change to the way macOS is built, hopefully no changes will be required.
https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.5/3.1.5.md#macos-notarization-change
=> Update to .NET Core 3.1.5

MediaBrowser.Providers/Plugins/TheTvdb/TvdbSeriesProvider.cs
=> Make tvdb name normalizer unicode aware

MediaBrowser.Api/Library/LibraryService.cs
A lot of stuff I want to do to update the Libraries. 
Should music have Music Video metadata types? 
We need to reorder tmdb over tvdb and turn tvdb off. omdb also needs to be turned on. 
HomeVideos, is that Mixed Content?
Can we enable Photos for every Library type and disable displaying Photos as the default?
=> Update Library Service

CONTRIBUTORS.md
**Changes**
Added name to CONTRIBUTORS.md for modifying jellyfin-server-windows to compile against .Net Core 3.1
=> CONTRIBUTORS.md - Updated jellyfin-server-windows to compile against .Net Core 3.1

Emby.Server.Implementations/Dto/DtoService.cs, MediaBrowser.Model/Dto/BaseItemPerson.cs
=> Enable BlurHash for People

Jellyfin.Api/Extensions/DtoExtensions.cs
Migrated from https://github.com/jellyfin/jellyfin/blob/522e44de59a8661a859f6a373e495a9e0e8d13ff/MediaBrowser.Api/BaseApiService.cs#L121
=> Add DtoExtensions

Emby.Server.Implementations/Udp/UdpServer.cs
=> Fix Task that ignores cancellation request

Jellyfin.Api/Controllers/ActivityLogController.cs, Jellyfin.Api/Controllers/FilterController.cs, Jellyfin.Api/Controllers/ItemRefreshController.cs, Jellyfin.Api/Controllers/LibraryStructureController.cs, Jellyfin.Api/Controllers/NotificationsController.cs, Jellyfin.Api/Controllers/PluginsController.cs, Jellyfin.Api/Controllers/SubtitleController.cs
Remove `#pragma` in favor of `SuppressMessage` attribute
=> Convert pragma to SuppressMessage

Emby.Server.Implementations/HttpServer/Security/AuthService.cs, Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs, Jellyfin.Api/Auth/CustomAuthenticationHandler.cs, MediaBrowser.Controller/Net/IAuthService.cs, MediaBrowser.Controller/Net/IAuthorizationContext.cs, tests/Jellyfin.Api.Tests/Auth/CustomAuthenticationHandlerTests.cs
**Changes**
Copies parts of the authorization code from the `api-migration` branch to fix the startup wizard.
**Issues**
Fixes #3328
=> Fix startup wizard in 10.6

Jellyfin.Api/Controllers/ConfigurationController.cs, Jellyfin.Api/Controllers/DevicesController.cs, Jellyfin.Api/Controllers/DisplayPreferencesController.cs, Jellyfin.Api/Controllers/ImageByNameController.cs, Jellyfin.Api/Controllers/ItemRefreshController.cs, Jellyfin.Api/Controllers/NotificationsController.cs, Jellyfin.Api/Controllers/PackageController.cs, Jellyfin.Api/Controllers/PluginsController.cs, Jellyfin.Api/Controllers/RemoteImageController.cs, Jellyfin.Api/Controllers/SessionController.cs, Jellyfin.Api/Controllers/SubtitleController.cs, Jellyfin.Api/Controllers/UserController.cs, Jellyfin.Api/Controllers/VideoAttachmentsController.cs
Route parameters are case sensitive.
Some responses still returned `Ok()`
GetSubtitle has an optional route parameter with a default value of 0
=> Add missing attributes, fix response codes, fix route parameter casing

Emby.Server.Implementations/Library/LibraryManager.cs, MediaBrowser.Providers/Manager/ItemImageProvider.cs
```
[2020-06-22 00:09:19.370 +02:00] [ERR] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
MediaBrowser.Model.Net.HttpException: Forbidden
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options) in /home/loma/dev/jellyfin/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 333
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod) in /home/loma/dev/jellyfin/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 279
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod) in …
```
=> Fix scan crashed

Jellyfin.Api/Controllers/DisplayPreferencesController.cs, Jellyfin.Api/Controllers/FilterController.cs, Jellyfin.Api/Controllers/ImageByNameController.cs, Jellyfin.Api/Controllers/ItemLookupController.cs, Jellyfin.Api/Controllers/ItemRefreshController.cs, Jellyfin.Api/Controllers/PlaylistsController.cs, Jellyfin.Api/Controllers/PluginsController.cs, Jellyfin.Api/Controllers/RemoteImageController.cs, Jellyfin.Api/Controllers/SessionController.cs, Jellyfin.Api/Controllers/UserController.cs, Jellyfin.Api/Controllers/VideosController.cs
Some Controllers were missing the default authorization policy implemented in #3357.
=> Add missing authorization policies (new Web Api)

Emby.Server.Implementations/Updates/InstallationManager.cs, MediaBrowser.Common/Updates/IInstallationManager.cs, MediaBrowser.Model/Configuration/BaseApplicationConfiguration.cs, MediaBrowser.Model/Updates/RepositoryInfo.cs
Minor improvements.
The properties of RepositoryInfo can be set to `null` with the API, this shouldn't be possible. I think we should add a DTO, validate all properties and map to RepositoryInfo.
=> Minor changes

README.md
=> Fix azure badge

Jellyfin.Api/Controllers/LibraryController.cs
=> Add missing route

Emby.Server.Implementations/Library/CoreResolutionIgnoreRule.cs, Emby.Server.Implementations/Library/LibraryManager.cs, MediaBrowser.Controller/Library/ILibraryManager.cs
**Changes**
Moved the "never ignore application/configuration folders" rule down to the bottom level.
**Issues**
Fixes #3406
=> Never ignore application folders

Jellyfin.Server.Implementations/Users/UserManager.cs, MediaBrowser.Api/UserService.cs, MediaBrowser.Controller/Library/IUserManager.cs
=> Fix User Deletion

Emby.Server.Implementations/Session/SessionManager.cs, MediaBrowser.Controller/Session/SessionInfo.cs
=> revert missing session fields

Jellyfin.Api/Controllers/ActivityLogController.cs, Jellyfin.Api/Controllers/DashboardController.cs, Jellyfin.Api/Controllers/FilterController.cs, Jellyfin.Api/Controllers/ItemRefreshController.cs, Jellyfin.Api/Controllers/LibraryController.cs, Jellyfin.Api/Controllers/LibraryStructureController.cs, Jellyfin.Api/Controllers/NotificationsController.cs, Jellyfin.Api/Controllers/PluginsController.cs, Jellyfin.Api/Controllers/TvShowsController.cs, Jellyfin.Api/Controllers/UserController.cs
Note- unused route parameters must stay
=> remove unused query parameters

MediaBrowser.Model/Configuration/ServerConfiguration.cs
Fixes null pointer in installationManager 
see issue #3464
=> 10.6.0.0 Null Pointer fix

MediaBrowser.Api/SyncPlay/SyncPlayService.cs
This also makes `ListGroups` a `GET` request.
=> [SyncPlay] Remove (unused) SessionId route parameter

Emby.Server.Implementations/Emby.Server.Implementations.csproj
**Changes**
Updates to the latest pre-release version of Jellyfin.XmlTv so guide fixes are included in nightly.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/1932.
=> Use newer Jellyfin.XmlTv for Guide Fixes

Emby.Server.Implementations/ApplicationHost.cs
**Changes**
Adds exception handling for `TypeLoadException` during plugin load.
=> Fix TypeLoadException during plugin load

.ci/azure-pipelines-package.yml
... before they changed it on us out of nowhere.
=> Explicitly add what Azure used to do implicitly

Jellyfin.Server.Implementations/Users/UserManager.cs
**Changes**
Use `.ToList()` instead of `.AsEnumerable()` since the latter delays query execution until it is enumerated at which point the context has been disposed.
**Issues**
Fixes #3554
=> Fix disposed database context

Emby.Server.Implementations/Updates/InstallationManager.cs
=> Catch HttpRequestException when requesting plugins

Emby.Server.Implementations/Emby.Server.Implementations.csproj, Jellyfin.Api/Jellyfin.Api.csproj, Jellyfin.Data/Jellyfin.Data.csproj, Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj, Jellyfin.Server/Jellyfin.Server.csproj, MediaBrowser.Common/MediaBrowser.Common.csproj, MediaBrowser.Controller/MediaBrowser.Controller.csproj, MediaBrowser.Model/MediaBrowser.Model.csproj, MediaBrowser.Providers/MediaBrowser.Providers.csproj, tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj, tests/MediaBrowser.Api.Tests/MediaBrowser.Api.Tests.csproj
**Changes**
Updates relevant packages to 3.1.6
=> Update .NET Core to 3.1.6

Emby.Server.Implementations/Library/LibraryManager.cs
**Changes**
Removes obsolete network path handling code.
=> Remove obsolete network path code

MediaBrowser.Providers/Plugins/TheTvdb/TvdbSeriesProvider.cs
=> Fix tvdb actors url

MediaBrowser.Api/Images/ImageService.cs
=> Remove profile image before setting new

.ci/azure-pipelines-package.yml
**Changes**
Fix typo
**Issues**
N/A
=> Fix typo in CI configuration

Jellyfin.Server.Implementations/Users/UserManager.cs
=> Fix username case change

Emby.Server.Implementations/Networking/NetworkManager.cs
Fixes for:
https://github.com/jellyfin/jellyfin/issues/3607
- code could be improved - but I've focused on a minimal change due to limited testing - and that this code will hopefully be gone in the near future. 
Includes fix for breaking change, reverting back the breaking change previously implemented.
- SSDP: Include any address if LAN subnets aren't specified #3515
=> Fix for #3607 and #3515

Jellyfin.Server.Implementations/Users/UserManager.cs
**Changes**
Makes `IncrementInvalidLoginAttemptCount` an async method
=> Make IncrementInvalidLoginAttemptCount async.

Jellyfin.Server/Migrations/MigrationRunner.cs, Jellyfin.Server/Migrations/Routines/ReaddDefaultPluginRepository.cs
Migration to add the plugin repository for all users that missed the original migratio.
=> Try adding plugin repository again

MediaBrowser.Providers/Plugins/AudioDb/Configuration/config.html, MediaBrowser.Providers/Plugins/MusicBrainz/Configuration/config.html, MediaBrowser.Providers/Plugins/Omdb/Configuration/config.html
=> fix built in plugin js

Emby.Server.Implementations/LiveTv/LiveTvManager.cs
=> Use System.Text.Json in LiveTvManager

Emby.Server.Implementations/ApplicationHost.cs, Jellyfin.Server/CoreAppHost.cs
**Changes**
Uses interfaces in ApplicationHost and CoreAppHost constructors.
=> Use interfaces in app host constructors

Jellyfin.Server.Implementations/JellyfinDb.cs, Jellyfin.Server.Implementations/Users/UserManager.cs
Currently under testing on my system, so far it's using less ram.
=> Add missing usings to UserManager

Emby.Server.Implementations/Library/LibraryManager.cs
**Changes**
This addresses an issue where EPG updates for live tv sources takes an _extremely_ long time due to image processing. This is likely due to the number of images involved (number of channels * programs each day * 7 days * 2 image formats). For the ~30 channels I have, EPG updates were taking 5 hours to complete. With this change it is back to less than 1 minute! :tada:
This does have the side effect of blur hashes being unavailable for live tv images, but it seems worth the trade off. Perhaps we could add a task to generate blur hashes for programs airing soon at some point.
**Issues**
N/A
=> Skip image processing for live tv sources

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
HD630 and UHD630 have some differences in ffmpeg commands.
**Issues**
reddit: https://www.reddit.com/r/jellyfin/comments/huct4x/jellyfin_1060_released/fyn30ds
=> Fix QSV device creation on Comet Lake

MediaBrowser.Model/Notifications/NotificationOption.cs
Added a second constructor with no parameters.
=> Fixes #3551 (Notifications Serialization error)

Emby.Dlna/PlayTo/Device.cs, Emby.Dlna/Server/DescriptionXmlBuilder.cs, Emby.Dlna/Service/ServiceXmlBuilder.cs
* Replace XML escape code with SecurityElement.Escape
* Optimize StringBuilder.Append calls
=> Improve DescriptionXmlBuilder

Emby.Naming/Common/NamingOptions.cs, MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
=> Replace \d with [0-9] in ffmpeg detection and scan code

Jellyfin.Api/Controllers/StartupController.cs, Jellyfin.Server.Implementations/Users/UserManager.cs, MediaBrowser.Api/UserService.cs, MediaBrowser.Controller/Library/IUserManager.cs
=> Make CreateUser async

Emby.Dlna/Didl/DidlBuilder.cs, Emby.Dlna/DlnaManager.cs, Emby.Drawing/ImageProcessor.cs, Emby.Naming/TV/SeasonPathParser.cs, Emby.Server.Implementations/Library/LibraryManager.cs, Emby.Server.Implementations/Library/MediaSourceManager.cs, Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs, Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs, Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs, Emby.Server.Implementations/Localization/LocalizationManager.cs, Emby.Server.Implementations/Networking/NetworkManager.cs, Emby.Server.Implementations/Services/ServiceExec.cs, Emby.Server.Implementations/Services/ServiceHandler.cs, Emby.Server.Implementations/Services/ServicePath.cs, MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs, MediaBrowser.Controller/Entities/BaseItem.cs, MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs, MediaBrowser.MediaEncoding/Subtitles/AssParser.cs, MediaBrowser.MediaEncoding/Subtitles/ParserValues.cs, MediaBrowser.MediaEncoding/Subtitles/SrtParser.cs, MediaBrowser.MediaEncoding/Subtitles/SrtWriter.cs, MediaBrowser.MediaEncoding/Subtitles/SsaParser.cs, MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs, MediaBrowser.MediaEncoding/Subtitles/TtmlWriter.cs, MediaBrowser.MediaEncoding/Subtitles/VttWriter.cs
Reduced allocations by replacing string.Substring with ReadOnlySpan<char>.Slice
=> Review usage of string.Substring (part 1)

Jellyfin.Server.Implementations/Users/UserManager.cs
**Changes**
Add space (`\ `) to the username validation regex
**Issues**
Fixes #3694
=> Allow space in username

Jellyfin.Api/Controllers/LibraryStructureController.cs, Jellyfin.Api/Models/LibraryStructureDto/LibraryOptionsDto.cs, Jellyfin.Api/Models/LibraryStructureDto/MediaPathDto.cs
=> Fix LibraryStructure API parameters

Jellyfin.Drawing.Skia/PercentPlayedDrawer.cs, Jellyfin.Drawing.Skia/PlayedIndicatorDrawer.cs, Jellyfin.Drawing.Skia/SkiaCodecException.cs, Jellyfin.Drawing.Skia/SkiaEncoder.cs, Jellyfin.Drawing.Skia/SkiaException.cs, Jellyfin.Drawing.Skia/StripCollageBuilder.cs, Jellyfin.Drawing.Skia/UnplayedCountIndicator.cs
**Changes**
Cleans up code in Jellyfin.Drawing.Skia. Also rewrites a couple of functions for readability/performance.
=> Jellyfin.Drawing.Skia Cleanup

Jellyfin.Server.Implementations/Users/DefaultPasswordResetProvider.cs
Use System.Text.Json in DefaultPasswordResetProvider.
=> Use System.Text.Json in DefaultPasswordResetProvider

.ci/azure-pipelines-package.yml
**Changes**
Ensures that the intermediate Docker images have the proper version in their names for the collect script to handle.
**Issues**
N/A
=> Get and tag with the actual release version in CI

SharedVersion.cs, build.yaml, debian/changelog, debian/metapackage/jellyfin, fedora/jellyfin.spec
**Changes**
Get the version string in Master ready for the next major release.
**Issues**
N/A
=> Bump master version to 10.7.0 for next release

bump_version
**Changes**
Same as the web one, but with fewer changes required.
**Issues**
N/A
=> Fix bump_version so it works properly

Emby.Server.Implementations/Channels/ChannelManager.cs, Emby.Server.Implementations/Devices/DeviceManager.cs, Emby.Server.Implementations/Library/LibraryManager.cs
**Changes**
Uses `IMemoryCache` where appropriate. Comes with innovative new features like *expiration*, and cache eviction™
=> Use Memory Cache

Emby.Server.Implementations/Networking/NetworkManager.cs
**Changes**
Fixes inverted logic in detecting local ip addresses introduced in #3007.
**Issues**
Related to: #3726
=> Fix inverted logic for LAN IP detection

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- adjust priority in outputSizeParam cutter for QSV + overlay.
- add some comments to avoid messing up here again. Orz
=> adjust priority in outputSizeParam cutter

README.md
Fix broken link to Azure DevOps pipeline.
=> Update README.md (fix broken links)

.ci/azure-pipelines-package.yml
**Changes**
Changes the timeout for uploading to the repository from 60 minutes to 10 minutes.
=> Add a much shorter timeout to the CollectArtifacts job

.ci/azure-pipelines-package.yml
This should make them execute with arguments again.
=> Merge the args and commands item for the artifact collection

MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs, MediaBrowser.MediaEncoding/BdInfo/BdInfoDirectoryInfo.cs, MediaBrowser.MediaEncoding/BdInfo/BdInfoExaminer.cs, MediaBrowser.MediaEncoding/BdInfo/BdInfoFileInfo.cs, MediaBrowser.MediaEncoding/Configuration/EncodingConfigurationFactory.cs, MediaBrowser.MediaEncoding/Configuration/EncodingConfigurationStore.cs, MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs, MediaBrowser.MediaEncoding/Encoder/EncodingUtils.cs, MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs, MediaBrowser.MediaEncoding/MediaBrowser.MediaEncoding.csproj, MediaBrowser.MediaEncoding/Probing/FFProbeHelpers.cs, MediaBrowser.MediaEncoding/Probing/MediaChapter.cs, MediaBrowser.MediaEncoding/Probing/MediaStreamInfo.cs, MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs, MediaBrowser.MediaEncoding/Subtitles/AssParser.cs, MediaBrowser.MediaEncoding/Subtitles/ISubtitleParser.cs, MediaBrowser.MediaEncoding/Subtitles/SsaParser.cs, MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
=> Fix some warnings

MediaBrowser.Providers/Plugins/Tmdb/Models/General/ExternalIds.cs, MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeProvider.cs, MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeasonProvider.cs, MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs
**Changes**
tvrage is mostly defunct and the id will sometimes be null, which causes a deserialization error
=> Make external ids nullable in TMDb

Emby.Server.Implementations/Channels/ChannelManager.cs, Emby.Server.Implementations/Devices/DeviceManager.cs
**Changes**
Makes memory cache cache things in memory
=> Fix MemoryCache Usage.

Jellyfin.Api/Controllers/DashboardController.cs
**Changes**
Request.Path only contains the path without query parameters.
=> Fix startup wizard redirect

Jellyfin.Api/Auth/FirstTimeOrIgnoreParentalControlSetupPolicy/FirstTimeOrIgnoreParentalControlSetupHandler.cs
=> Fix Requirement assigned to Handler

Jellyfin.Drawing.Skia/StripCollageBuilder.cs
**Changes**
Resize the source bitmap, not the destination bitmap.
=> Fix collages

MediaBrowser.Providers/Manager/ProviderManager.cs
**Changes**
tvdb will send html instead of a proper 404. This special snowflake case is now being handled like the rest of the 404 by throwing multiple exceptions.
=> Throw HttpException when tvdb sends us crap data

Emby.Server.Implementations/EntryPoints/LibraryChangedNotifier.cs
**Changes**
Fixes some warnings and cleans up code.
=> Clean up LibraryChangedNotifier.

Emby.Server.Implementations/LiveTv/LiveTvMediaSourceProvider.cs
**Changes**
Makes some minor changes to LiveTvMediaSourceProvider.
=> Minor fixes to LiveTvMediaSourceProvider

Emby.Dlna/ControlResponse.cs, Jellyfin.Api/Controllers/DlnaServerController.cs, Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs, Jellyfin.Server/Formatters/XmlOutputFormatter.cs
=> Add xml output formatter

Emby.Server.Implementations/Dto/DtoService.cs, MediaBrowser.Controller/Dto/IDtoService.cs
**Changes**
Removes some unused methods in IDtoService
=> Remove unused methods in IDtoService

Jellyfin.Server/Formatters/XmlOutputFormatter.cs
=> Use proper mediatypename

Jellyfin.Api/Controllers/AudioController.cs, Jellyfin.Api/Controllers/UniversalAudioController.cs
Container is required if using the container routes.
=> Fix conflicting audio routes

Jellyfin.Api/Controllers/LibraryController.cs, Jellyfin.Server.Implementations/Activity/ActivityManager.cs, MediaBrowser.Model/Activity/IActivityManager.cs
**Changes**
Converts `LibraryController.GetDownload` to an async method, and removes the need for a synchronous method in `IActivityManager`.
=> Make LibraryController.GetDownload async

MediaBrowser.Providers/Plugins/MusicBrainz/AlbumProvider.cs, MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
=> Fix incorrect adding of user agent

Jellyfin.Api/Controllers/LibraryStructureController.cs, Jellyfin.Api/Models/LibraryStructureDto/AddVirtualFolderDto.cs, Jellyfin.Api/Models/LibraryStructureDto/UpdateLibraryOptionsDto.cs
`Id` is not a query parameter.
=> Fix model binding in UpdateLibraryOptions

Jellyfin.Api/Helpers/ProgressiveFileCopier.cs
=> Fix incorrect usage of ArrayPool

Jellyfin.Api/Controllers/DynamicHlsController.cs, MediaBrowser.Model/Configuration/EncodingOptions.cs
Part1: this
Part2: https://github.com/jellyfin/jellyfin-web/pull/1842
**Changes**
- Expose max_muxing_queue_size to user. see https://github.com/jellyfin/jellyfin/pull/3975
=> Expose max_muxing_queue_size to user

Jellyfin.Api/Controllers/DlnaServerController.cs
=> Fix DLNA Routes

MediaBrowser.Controller/Entities/BaseItem.cs
**Changes**
Extract theme songs and videos from ExtraIds when requested.
=> Populate ThemeVideoIds and ThemeSongIds

Dockerfile, Dockerfile.arm, Dockerfile.arm64, debian/rules, deployment/Dockerfile.docker.amd64, deployment/Dockerfile.docker.arm64, deployment/Dockerfile.docker.armhf, deployment/build.linux.amd64, deployment/build.macos, deployment/build.portable, deployment/build.windows.amd64, fedora/jellyfin.spec
Didn't realize setting the flag overrode the csproj flag, so remove it from the command.
=> Remove GenerateDocumentationFile

Jellyfin.Api/Helpers/FileStreamResponseHelpers.cs
**Changes**
Enable HTTP Range Processing to fix seeking with direct play.
=> Enable HTTP Range Processing (Fix seeking)

MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeProvider.cs, MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeasonProvider.cs, MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs
=> Fix null exception in tmdb episode provider

Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Udp/UdpServer.cs, MediaBrowser.Controller/IServerApplicationHost.cs
EnableLoopback was a empty virtual function in ApplicationHost.cs.
It is not overridden.
The method was called from the udpServer. 
Looks like left over code.
=> Simplified Code: Removed code which was never used.

Jellyfin.Api/Helpers/FileStreamResponseHelpers.cs, Jellyfin.Api/Helpers/StreamingHelpers.cs
This is a fix for an out of memory error with large files. The solution implmented is how the other streams perform the action.
=> Our of Memory fix when streaming large files

Jellyfin.Server/Middleware/BaseUrlRedirectionMiddleware.cs, Jellyfin.Server/Startup.cs
I must have had pending changes when I tested it last, but now this works with no base url & with a base url, hosting web content or not hosting content.
=> Fix redirection

Jellyfin.Api/Controllers/LiveTvController.cs
=> Add missing FromRoute, Required attribute

Jellyfin.Server/Middleware/ExceptionMiddleware.cs
Return 401 instead of 500 on invalid login.
=> Fix catching authentication exception

Emby.Dlna/PlayTo/PlayToManager.cs
code wasn't removing uuid from the url - which was causing the server controller guid tester to crash.
=> Unstable: PlayTo corruption url fix

Jellyfin.Server/Middleware/ServerStartupMessageMiddleware.cs
During startup, the server pings itself to validate the IP addresses in the configuration `LocalNetworkAddresses` :(
=> Skip startup message for /system/ping

MediaBrowser.Providers/Plugins/TheTvdb/TvdbEpisodeProvider.cs
**Changes**
Content rating is available from thetvdb but not copied into metadata.
**Issues**
=> Update content rating from thetvdb

Emby.Naming/AudioBook/AudioBookFilePathParser.cs, Emby.Naming/AudioBook/AudioBookResolver.cs, tests/Jellyfin.Naming.Tests/AudioBook/AudioBookListResolverTests.cs, tests/Jellyfin.Naming.Tests/AudioBook/AudioBookResolverTests.cs
There still is a bug remaining I found with the text, but I could not find the source of the fault so far: https://github.com/jellyfin/jellyfin/issues/4107
**Changes**
Adds Tests for AudioBookInfo and AudioBookListResolver
Fixes Part Number detection for audiobooks.
**Issues**
=> some testing for AudioBook

fedora/jellyfin.spec
No idea if this will work, just based it on the other lines in the `%files server` block
=> Add new files to rpm build

Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
=> Update SkiaSharp.NativeAssets.Linux to 2.80.2

MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeasonImageProvider.cs
**Changes**
Fix copy/paste mistake in TMDB Season Image Provider which led to Jellyfin using the series poster instead of the season poster
**Issues**
Fixes #3217
=> Fix TMDB Season Images

MediaBrowser.Model/Dlna/ResolutionNormalizer.cs
**Changes**
Add 1440p as an output option.
**Issues**
Partially addresses #3112.
=> Add 1440p to the mix

Emby.Server.Implementations/Dto/DtoService.cs
**Changes**
int / int = int
(double)int / int = double
=> Fix aspect ratio calculation sometimes returning 0 or 1

README.md
**Changes**
1. Make the descriptions more consistent.
2. Link to the webpage first, then docs.
3. Make the Weblate reference similar to the others.
**Issues**
N/A
=> Revamp the main README

Jellyfin.Api/Controllers/UserController.cs, Jellyfin.Api/Models/UserDtos/ForgotPasswordDto.cs
Json deserializer can't extract the "enteredUsername" value. Added a Dto to deserialize to instead.
=> Add Dto to ForgotPassword

.ci/azure-pipelines-test.yml
Allow project to determine if it should produce xml docs
=> Generate document file for openapi spec in CI

Jellyfin.Server/Startup.cs
=> Allow server to return .data files

Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteTranscodeFileTask.cs
**Changes**
Set the default time to midnight, and conform to the same task
scheduling commands that other tasks use.
**Issues**
Hopefully fixes #2075.
=> Fix Transcode Cleanup Schedule

apiclient/templates/typescript/axios/generate.sh
**Changes**
Adds missing additional properties to typescript axios apiclient generator
For more info see [here](https://github.com/OpenAPITools/openapi-generator/issues/5008)
=> Add missing properties to typescript axios generator

tests/Jellyfin.Common.Tests/Json/JsonGuidConverterTests.cs
=> Add tests for deserializing guids

Emby.Server.Implementations/SyncPlay/SyncPlayController.cs, MediaBrowser.Controller/SyncPlay/GroupInfo.cs
* Fixed docs
* Remove extra dictionary lookups
* change property to constant
=> Improve GroupInfo class

.ci/azure-pipelines-api-client.yml, apiclient/templates/typescript/axios/generate.sh
Name and link pulled from 
https://dev.azure.com/jellyfin-project/jellyfin/_packaging?_a=connect&feed=unstable%40Local --> npm
=> Fix registry name and link

Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs, Jellyfin.Server/Filters/WebsocketModelFilter.cs
Part of #4029 
cc @nielsvanvelzen
=> Manually register models used in websocket messages.

Jellyfin.Api/Controllers/ActivityLogController.cs, Jellyfin.Data/Queries/ActivityLogQuery.cs, Jellyfin.Server.Implementations/Activity/ActivityManager.cs, Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj, Jellyfin.Server.Implementations/Users/DisplayPreferencesManager.cs, Jellyfin.Server.Implementations/Users/UserManager.cs, MediaBrowser.Model/Activity/IActivityManager.cs
**Changes**
Rewrites the activity log backend to use a query model and makes the backend async.
=> Rewrite Activity Log Backend

Jellyfin.Api/Controllers/ArtistsController.cs, Jellyfin.Api/Controllers/ChannelsController.cs, Jellyfin.Api/Controllers/GenresController.cs, Jellyfin.Api/Controllers/ItemsController.cs, Jellyfin.Api/Controllers/MusicGenresController.cs, Jellyfin.Api/Controllers/PersonsController.cs, Jellyfin.Api/Controllers/StudiosController.cs, Jellyfin.Api/Controllers/TrailersController.cs, Jellyfin.Api/Helpers/RequestHelpers.cs
=> Convert filters string to enum.

Jellyfin.Api/Controllers/ItemsController.cs, Jellyfin.Api/Controllers/TrailersController.cs
=> Convert exclude location type string to enum.

MediaBrowser.Model/Session/GeneralCommandType.cs
Fixes Web, MPV Shim, Kodi.
Other clients may be sending other command types, they will have to be added when discovered.
=> Add missing general commands

Emby.Server.Implementations/Library/MediaSourceManager.cs
Due to locking, when starting a stream all other live streams are effectively paused. If a live stream takes a long time to start, other live streams will stop until the new live stream has started. This is undesired and existing streams should continue unimpeded.
**Changes**
* Remove use of SemaphoreSlim in MediaResourceManager for functions that are merely inspecting _openStreams rather than adding/removing from it.
* Since the _openStreams dictionary will now be accessed in parallel, use a ConcurrentDictionary to ensure thread safe access of the dictionary.
**Issues**
I don't know if there's an issue for this or not, however I have observed the previous behavior myself on version 10.6.4.
=> Fix stream performance when opening/closing new streams.

Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/HttpServer/WebSocketManager.cs, Jellyfin.Server/CoreAppHost.cs, Jellyfin.Server/Program.cs, MediaBrowser.Controller/Net/IWebSocketManager.cs
The websocketlisteners were moved to a different project that isn't included in `_allConcreteTypes`. I've moved the registration to RegisterServices.
=> Fix IWebSocketListener service registration

.ci/azure-pipelines-api-client.yml, .npmrc
Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm-authenticate?view=azure-devops
Unsure if `.npmrc` is correct, and if more `customEndpoint` need to be added.
=> Add npmAuthenticate task

Jellyfin.Api/Controllers/VideoHlsController.cs
Fixes: https://github.com/jellyfin/jellyfin/issues/4385, https://github.com/jellyfin/jellyfin/issues/4111
=> Add missing slashes in ffmpeg argument.

Jellyfin.Server.Implementations/Users/UserManager.cs
**Changes**
Adds caching to users to improve performance. This can cause some nasty bugs if a user object is modified without calling the `UpdateUser` method. Untested.
=> Add caching to users

Jellyfin.Server.Implementations/Users/UserManager.cs
Fixes a possible NullReferenceException. Depends on #4377
=> Fix possible null reference exception

Jellyfin.Api/Controllers/ImageController.cs, Jellyfin.Api/Controllers/UserController.cs, Jellyfin.Server.Implementations/Users/UserManager.cs, MediaBrowser.Controller/Library/IUserManager.cs
**Changes**
Converts some of the methods in UserManager to async. Allows more scalability and reduces threadpool starvation on larger installs.
=> Convert some code in UserManager to async

Jellyfin.Server/Jellyfin.Server.csproj, MediaBrowser.Providers/MediaBrowser.Providers.csproj, tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj, tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj
Updates all deps that dependabot either couldn't do or we accidentally ignored
=> Dependency catch up

Emby.Server.Implementations/Updates/InstallationManager.cs, MediaBrowser.Common/Updates/IInstallationManager.cs
**Changes**
Adds missing logic to call new event system in InstallationManager.cs and cleans some code up.
=> Fix Plugin Events and Clean Up InstallationManager.cs

Jellyfin.Api/Helpers/FileStreamResponseHelpers.cs, Jellyfin.Api/Helpers/ProgressiveFileStream.cs
**Changes**
Made a stream wrapper based on ProgressiveFileCopier that essentially only implements ReadAsync. It opens the transcoded file as a `FileStream` and continues to read it until the transcode is complete.
No more than the buffer size should be saved in memory, so hopefully no OOM regressions.
**Issues**
Fixes #4105
=> Add ProgressiveFileStream

Jellyfin.Api/Controllers/UserController.cs
Sometimes a client just wants to know what user the token belongs to
=> Add /Users/Me endpoint

Jellyfin.Api/Controllers/DevicesController.cs, Jellyfin.Api/Controllers/SuggestionsController.cs
As far as I could tell the Suggestions endpoint isn't used anywhere.
=> Fix endpoint authorization requirements

Emby.Server.Implementations/LiveTv/TunerHosts/M3UTunerHost.cs, Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4351
Note; if not set the UserAgent will default to `Jellyfin-Server/${Version}`
=> Set UserAgent when getting M3u playlist

.ci/azure-pipelines-package.yml
**Changes**
Otherwise I'm forced to allow `sudo nohup` globally which is bad news bears.
**Issues**
N/A
=> Reverse order of sudo and nohup

Jellyfin.Api/Controllers/DlnaServerController.cs
Framework didn't know it was supposed to return xml.
=> Add missing dlna attributes.

Emby.Server.Implementations/HttpServer/Security/AuthService.cs, Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs, Jellyfin.Api/Auth/CustomAuthenticationHandler.cs, MediaBrowser.Controller/Net/AuthorizationInfo.cs, tests/Jellyfin.Api.Tests/Auth/CustomAuthenticationHandlerTests.cs
OriginalAuthenticationInfo was unused as far as I can tell. Using token or user to check if the token is authenticated is rubbish, so I added IsAuthenticated to the auth info class.
=> Remove OriginalAuthenticationInfo and add IsAuthenticated property

.ci/azure-pipelines-api-client.yml, apiclient/templates/typescript/axios/generate.sh
Package will be generated nightly instead, fixes CI.
=> Remove unstable npm ci task

MediaBrowser.Controller/Entities/BaseItem.cs
**Changes**
Include `shorts` and `featurettes` directories in the BaseItem entity
**Issues**
Fixes #4465
=> Fix #4465 by adding the missing extras folders.

Jellyfin.Server/Migrations/Routines/MigrateDisplayPreferencesDb.cs
=> Skip migration if user doesn't exist

Emby.Server.Implementations/LiveTv/LiveTvManager.cs, Jellyfin.Api/Extensions/DtoExtensions.cs, Jellyfin.Api/Models/LibraryDtos/LibraryOptionsResultDto.cs, Jellyfin.Api/Models/LibraryDtos/LibraryTypeOptionsDto.cs, Jellyfin.Api/Models/LiveTvDtos/ChannelMappingOptionsDto.cs, Jellyfin.Api/Models/LiveTvDtos/GetProgramsDto.cs, Jellyfin.Api/Models/MediaInfoDtos/OpenLiveStreamDto.cs, MediaBrowser.Controller/Dto/DtoOptions.cs, MediaBrowser.Controller/LiveTv/ILiveTvManager.cs, MediaBrowser.Model/MediaInfo/LiveStreamRequest.cs
Removes CA1819 from Jellyfin.Api
=> Convert array property to IReadOnlyList

Emby.Server.Implementations/ApplicationHost.cs
Fixes
```
[11:05:23] [ERR] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.IO.DirectoryNotFoundException: Could not find a part of the path '%localappdata%\jellyfin\plugins'.
at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
at System.IO.Enumeration.FileSystemEnumerator`1.Init()
at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator..ctor(FileSystemEnumerable`1 enumerable, Boolean isNormalized)
at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
at …
```
=> Fix plugin update exception

Jellyfin.Server.Implementations/Users/UserManager.cs
Fixes https://github.com/jellyfin/jellyfin-web/issues/2067
=> Update user cache after updating user.

Emby.Dlna/ContentDirectory/ContentDirectoryService.cs, Emby.Dlna/ContentDirectory/ContentDirectoryXmlBuilder.cs, Emby.Dlna/ContentDirectory/ControlHandler.cs, Emby.Dlna/ContentDirectory/ServerItem.cs, Emby.Dlna/ContentDirectory/ServiceActionListBuilder.cs, Emby.Dlna/ContentDirectory/StubType.cs
Commented code - and statically defined as per intellisense suggestion.
=> DLNA ContentManager - static and commented.

MediaBrowser.Common/Net/DefaultHttpClientHandler.cs
Default to accept ALL compression methods.
=> Use ALL the decompression methods

Jellyfin.Server/CoreAppHost.cs, MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs, MediaBrowser.Controller/BaseItemManager/IBaseItemManager.cs, MediaBrowser.Controller/Entities/BaseItem.cs, MediaBrowser.Providers/Manager/ProviderManager.cs
Also move `IsMetadataFetcherEnabled` and `IsImageFetcherEnabled`
=> Add BaseItemManager

Emby.Dlna/Configuration/DlnaOptions.cs, Emby.Dlna/ConnectionManager/ConnectionManagerService.cs, Emby.Dlna/ConnectionManager/ConnectionManagerXmlBuilder.cs, Emby.Dlna/ConnectionManager/ControlHandler.cs, Emby.Dlna/ConnectionManager/ServiceActionListBuilder.cs
Commented code - and statically defined as per intellisense suggestion.
=> DLNA ConnectionManager - static and commented.

Emby.Server.Implementations/Devices/DeviceManager.cs, Emby.Server.Implementations/Session/SessionManager.cs
**Changes**
Minor cleanup, don't store capabilities on disk
=> Clean up DeviceManager and Don't Store Capabilities on Disk

Jellyfin.Api/Helpers/TranscodingJobHelper.cs
=> Update FFmpeg log

MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs
fixes https://github.com/jellyfin/jellyfin/issues/4495
=> Null pointer fix.

Jellyfin.Server/Startup.cs
This config option has been moved across to network.xml.
=> [Fix] Config option read from wrong place.

MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
=> [Fix] Null Pointer in TmdbMovieProvider

Jellyfin.Api/Models/SessionDtos/ClientCapabilitiesDto.cs
Always check your namespace kids
=> Fix namespace and add attribute for ClientCapabilitiesDto

Emby.Naming/Video/VideoListResolver.cs
Reported via #LinuxUnplugged Bug-a-Thon
Fixes
```
[14:07:07] [ERR] [5] Emby.Server.Implementations.Library.LibraryManager: Error in MovieResolver resolving D:\Media\Movies\Children.of.a.Lesser.God.1986.1080p.WEBRip.x264-RARBG
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
at System.String.Substring(Int32 startIndex, Int32 length)
at System.String.Substring(Int32 startIndex)
at Emby.Naming.Video.VideoListResolver.IsEligibleForMultiVersion(String folderName, String testFilename) in C:\Users\Cody\Code\Jellyfin\jellyfin-master\Emby.Naming\Video\VideoListResolver.cs:line 230
at Emby.Naming.Video.VideoListResolver.<>c__DisplayClass3_0.<GetVideosGroupedByVersion>b__0(VideoInfo i) in …
```
=> Only trim file name if folder name is shorter

MediaBrowser.Common/Json/Converters/JsonGuidConverter.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4566
=> Serialize Guid.Empty to null

MediaBrowser.Common/Json/Converters/JsonVersionConverter.cs, MediaBrowser.Common/Json/JsonDefaults.cs
=> [Fix] Fixed Plugin versioning in browser notifications

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Remove one redundant 'hwaccel vaapi' string
=> Remove one redundant 'hwaccel vaapi' string

Jellyfin.Api/Controllers/AudioController.cs, Jellyfin.Api/Controllers/DynamicHlsController.cs, Jellyfin.Api/Controllers/VideoHlsController.cs, Jellyfin.Api/Controllers/VideosController.cs
**Changes**
- Fix transcoding reasons report
=> Fix transcoding reasons report

Jellyfin.Server/Startup.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4631
Accidentally changed the MusicBrainz respone to JSON, this switches it back to XML.
=> Fix MusicBrainz request Accept header

Emby.Dlna/PlayTo/PlayToManager.cs, Emby.Dlna/Properties/AssemblyInfo.cs, MediaBrowser.sln, tests/Jellyfin.Dlna.Tests/GetUuidTests.cs, tests/Jellyfin.Dlna.Tests/Jellyfin.Dlna.Tests.csproj
Broken in: https://github.com/jellyfin/jellyfin/commit/544db8cc064f445ff58cd6f43610940164cb84fa
Source of test values: https://www.netscout.com/sites/default/files/asert-blog/uploads/2018/06/ssdp_diffraction.pdf
=> Add tests for GetUuid

Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4624
Current output:
```json
"ImageBlurHashes": {
"type": "object",
"properties": {
"Primary": {
"type": "object",
"properties": {
"string": {
"type": "string",
"format": "string"
}
}
},
"Art": {
"type": "object",
"properties": {
"string": {
"type": "string",
"format": "string"
}
}
},
"Backdrop": {
"type": "object",
"properties": {
"string": {
"type": "string",
"format": "string"
}
}
},
"Banner": {
"type": "object",
"properties": {
"string": {
"type": "string",
"format": "string"
}
}
},
"Logo": {
"type": "object",
"properties": {
"string": {
"type": "string",
"format": "string"
}
}
},
"Thumb": {
"type": "object",
"properties": {
"string": {
"type": "string",
"format": "string"
}
}
},
"Disc": {
"type": "object",
"properties": {
"string": { …
```
=> Fix OpenApi generation for BlurHash

Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs, Jellyfin.Server/Filters/SecurityRequirementsOperationFilter.cs
Fixes a TODO and https://github.com/jellyfin/jellyfin/issues/4029#issuecomment-737499007
Attached for easy testing: [openapi.zip](https://github.com/jellyfin/jellyfin/files/5632312/openapi.zip)
=> Move OpenApiSecurityScheme to OperationFilter

Emby.Server.Implementations/ApplicationHost.cs
**Changes**
Before:
```
[INF] [1] Emby.Server.Implementations.ApplicationHost: Plugins: Anime 11.2012.311.1919
OMDb 10.7.0.0
MusicBrainz 10.7.0.0
AudioDB 10.7.0.0
```
After:
```
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded plugin: Anime 11.2012.311.1919
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded plugin: OMDb 10.7.0.0
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded plugin: MusicBrainz 10.7.0.0
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded plugin: AudioDB 10.7.0.0
```
=> Optimize load plugin logs

Jellyfin.Server/Migrations/Routines/RemoveDownloadImagesInAdvance.cs
-- 
Seems to be from a (now) non-existent library path
=> Don't die if folder doesn't have id

Emby.Server.Implementations/Data/SqliteItemRepository.cs, Jellyfin.Server/Migrations/MigrationRunner.cs, Jellyfin.Server/Migrations/Routines/AddPeopleQueryIndex.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4639
=> Optimize FavoritePersons query

Emby.Dlna/PlayTo/PlayToManager.cs
I uncommented it in a previous PR
=> Remove spammy debug line

.github/CODEOWNERS
**Changes**
I need to know when stuff changes.
**Issues**
N/A
=> Make me codeowner of the .ci dir

bump_version
**Changes**
Fix syntax error in bump_version
**Issues**
N/A
=> Fix bad do in bump_version

.ci/azure-pipelines-api-client.yml
=> Fix NPM command in CI

.ci/azure-pipelines-package.yml
**Changes**
This is not required for stable pushes.
**Issues**
N/A
=> Remove obsolete erroring command

Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
=> Clear KnownNetworks and KnownProxies if none are configured explicitly

Emby.Server.Implementations/Dto/DtoService.cs
=> Only apply series image aspect ratio if episode/season has no primary image

Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs, MediaBrowser.Common/Json/Converters/JsonBoolNumberConverter.cs, tests/Jellyfin.Common.Tests/Json/JsonBoolNumberTests.cs
Fixes recursion caused by https://github.com/jellyfin/jellyfin/pull/4715
Source: https://github.com/jellyfin/jellyfin/pull/4715#issuecomment-740528982
=> Fix JsonConverter recursion

Emby.Server.Implementations/LiveTv/LiveTvManager.cs, MediaBrowser.Common/Json/Converters/JsonGuidConverter.cs, MediaBrowser.Model/Dto/BaseItemDto.cs, tests/Jellyfin.Common.Tests/Json/JsonGuidConverterTests.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4029#issuecomment-740209476
Note: this still fixes https://github.com/jellyfin/jellyfin/issues/4566
=> Don't serialize empty GUID to null

Emby.Server.Implementations/Library/UserViewManager.cs
**Changes**
- Fix custom library order
**Issues**
Fixes https://github.com/jellyfin/jellyfin-web/issues/2192
=> Fix custom library order

MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs
Might fix https://github.com/jellyfin/jellyfin-plugin-omdb/issues/1
Note: I wasn't able to reproduce the issue, but this is my best guess.
This is already fixed in the (future) plugin
https://github.com/jellyfin/jellyfin-plugin-omdb/blob/db772ab6cb0c3ad60d79f2658c3f7c52b3bfbf33/Jellyfin.Plugin.Omdb/OmdbProvider.cs#L470
=> Fix potential null reference in OMDB

MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4740
Caused by https://github.com/jellyfin/jellyfin/pull/4342
=> Actually use library options when filtering metadata providers

Emby.Server.Implementations/Updates/InstallationManager.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4688
=> Don't return plugin versions that target newer Jellyfin version

Emby.Server.Implementations/Emby.Server.Implementations.csproj, Jellyfin.Api/Jellyfin.Api.csproj, Jellyfin.Data/Jellyfin.Data.csproj, Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj, Jellyfin.Server/Jellyfin.Server.csproj, deployment/Dockerfile.debian.amd64, deployment/Dockerfile.debian.arm64, deployment/Dockerfile.debian.armhf, deployment/Dockerfile.linux.amd64, deployment/Dockerfile.macos, deployment/Dockerfile.portable, deployment/Dockerfile.ubuntu.amd64, deployment/Dockerfile.ubuntu.arm64, deployment/Dockerfile.ubuntu.armhf, deployment/Dockerfile.windows.amd64, tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
https://devblogs.microsoft.com/dotnet/net-december-2020/
=> Update to dotnet 5.0.1

MediaBrowser.Common/Json/Converters/JsonGuidConverter.cs, tests/Jellyfin.Common.Tests/Json/JsonGuidConverterTests.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4748
=> Serialize GUID without dashes

Emby.Dlna/PlayTo/PlayToController.cs
Fixes: https://github.com/jellyfin/jellyfin/pull/4723
Ensured non nullable parameters contain values.
This enabled the playback to work.
=> Fix null reference error in Dlna PlayTo

Emby.Server.Implementations/Session/SessionManager.cs, Emby.Server.Implementations/Session/SessionWebSocketListener.cs, Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs, MediaBrowser.Controller/Session/ISessionManager.cs
**Changes**
Added an event to SessionManager that notifies about new WebSocket connections.
**Issues**
Related to #4680
=> Restore sessions in SyncPlay groups upon reconnection

Jellyfin.Api/Controllers/UserController.cs, Jellyfin.Server.Implementations/Users/UserManager.cs, MediaBrowser.Controller/Library/IUserManager.cs
**Changes**
Converts UserManager.DeleteUser to async
=> Convert DeleteUser to async

Jellyfin.Server/Migrations/Routines/MigrateDisplayPreferencesDb.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4694
=> Fix CustomItemDisplayPreferences unique key collision in the migration

Jellyfin.Server.Implementations/Activity/ActivityManager.cs, Jellyfin.Server.Implementations/Events/Consumers/Session/PlaybackStartLogger.cs, Jellyfin.Server.Implementations/Events/Consumers/Session/PlaybackStopLogger.cs, Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj, Jellyfin.Server.Implementations/JellyfinDb.cs, Jellyfin.Server.Implementations/Users/DefaultAuthenticationProvider.cs, Jellyfin.Server.Implementations/Users/DefaultPasswordResetProvider.cs, Jellyfin.Server.Implementations/Users/DeviceAccessEntryPoint.cs, Jellyfin.Server.Implementations/Users/InvalidAuthProvider.cs, Jellyfin.Server.Implementations/Users/UserManager.cs, Jellyfin.Server.Implementations/ValueConverters/DateTimeKindValueConverter.cs
**Changes**
Enables nullable for Jellyfin.Server.Implementations
=> Enable Nullable for Jellyfin.Server.Implementations

README.md
Also removed old documentation about placing the built dist into the jellyfin-server directory
=> Modified ReadMe with updated command line command

Emby.Server.Implementations/ApplicationHost.cs, Emby.Server.Implementations/Configuration/ServerConfigurationManager.cs, Jellyfin.Networking/Configuration/NetworkConfiguration.cs
**Changes**
- Fix SSL certificate cannot be saved
**Issues**
Introduced 10.7
=> Fix SSL certificate cannot be saved

Jellyfin.Api/Controllers/DisplayPreferencesController.cs, Jellyfin.Data/Entities/ItemDisplayPreferences.cs, Jellyfin.Data/Enums/ViewType.cs
**Changes**
- Fix landing screen options
- Web side changes https://github.com/jellyfin/jellyfin-web/pull/2217
**Issues**
Introduced in 10.7, this option has been broken since https://github.com/jellyfin/jellyfin/commit/dbeeb7cf4a715580432232c7098e4d86afccb37c
=> Fix landing screen options

Jellyfin.Server/Extensions/ApiApplicationBuilderExtensions.cs, Jellyfin.Server/Middleware/LegacyEmbyRouteRewriteMiddleware.cs, Jellyfin.Server/Middleware/PathTrimMiddleware.cs, Jellyfin.Server/Middleware/RobotsRedirectionMiddleware.cs, Jellyfin.Server/Startup.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4689
Redirects `{baseUrl}/robots.txt` to `{baseUrl}/web/robots.txt`
=> Redirect robots.txt if hosting web content

Emby.Server.Implementations/Library/Resolvers/Books/BookResolver.cs
**Changes**
**Issues**
Fixes #3766
Fixes jellyfin/jellyfin-plugin-bookshelf#22
=> Remove opf extension for book types

Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs, Jellyfin.Api/Auth/SyncPlayAccessPolicy/SyncPlayAccessHandler.cs, Jellyfin.Api/Auth/SyncPlayAccessPolicy/SyncPlayAccessRequirement.cs, Jellyfin.Api/Constants/Policies.cs, Jellyfin.Api/Controllers/SyncPlayController.cs, Jellyfin.Data/Entities/User.cs, Jellyfin.Data/Enums/SyncPlayAccessRequirementType.cs, Jellyfin.Data/Enums/SyncPlayUserAccessType.cs, Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs, MediaBrowser.Controller/SyncPlay/ISyncPlayManager.cs, MediaBrowser.Model/Users/UserPolicy.cs
**Changes**
Add new types of policies for accessing SyncPlay.
Add sessions counter of a user to let them access groups they've joined.
**Issues**
Related to [this](https://github.com/jellyfin/jellyfin/pull/3194#discussion_r536537652).
=> Update authorization policies for SyncPlay

Jellyfin.Api/Controllers/LiveTvController.cs, Jellyfin.Api/Models/LiveTvDtos/SetChannelMappingDto.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4778
=> Use request body for mapping xml channels

Jellyfin.Api/Controllers/ImageController.cs
=> Convert from base64 when saving item images

Jellyfin.Api/Controllers/LibraryController.cs
=> Set filename when downloading file

.ci/azure-pipelines-package.yml, deployment/Dockerfile.linux.amd64-musl, deployment/Dockerfile.linux.arm64, deployment/Dockerfile.linux.armhf, deployment/build.linux.amd64-musl, deployment/build.linux.arm64, deployment/build.linux.armhf
**Changes**
Add static Linux builds for arm[hf], arm64, and MUSL amd64 (for Alpine, etc.)
**Issues**
Fixes #4827
=> Add static Linux builds for arm and musl

Jellyfin.Api/Controllers/LibraryController.cs
**Changes**
This endpoint only worked in e2a7e8d9 after the API migration. 
Haven't tested this fix with a music library yet
**Issues**
Fixes #4831
=> Fix similar items endpoint for movies and TV

Jellyfin.Api/Controllers/DisplayPreferencesController.cs
This was the only missing key.
=> Return dashboardTheme when requesting DisplayPreferences

Jellyfin.Api/Controllers/MediaInfoController.cs, Jellyfin.Api/Models/MediaInfoDtos/OpenLiveStreamDto.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4813
I love consistent API usage.
=> Add request parameters to OpenLiveStreamDto

MediaBrowser.Common/Json/Converters/JsonDateTimeConverter.cs, MediaBrowser.Common/Json/JsonDefaults.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4654
Note that I still get "Indexing failed for Jellyfin" at the top, but everything seems to work fine.
=> Add JsonDateTimeConverter

Jellyfin.Server/Migrations/Routines/MigrateDisplayPreferencesDb.cs
Not sure how this key collision could have happened, but it exists.
Fixes https://github.com/jellyfin/jellyfin/issues/4455#issuecomment-747210914
```
[00:03:15] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'MigrateDisplayPreferencesDatabase'
[00:03:15] [WRN] [1] Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb: User with ID 97324e44-dd17-4ba0-89d4-a82e3df66f49 does not exist in the database, skipping migration.
[00:03:15] [WRN] [1] Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb: User with ID b0749b39-4489-46aa-a445-0ea83fdcffed does not exist in the database, skipping migration.
[00:03:15] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'MigrateDisplayPreferencesDatabase' …
```
=> Fix another key collision in MigrateDisplayPreferencesDatabase

Jellyfin.Api/Controllers/SystemController.cs
https://github.com/jellyfin/jellyfin/issues/4805
May not be the entire fix for above - but is being logged as an error on the startup image.
=> Null reference fix

MediaBrowser.Common/Json/JsonDefaults.cs
https://github.com/dotnet/runtime/issues/40072
=> Initialize JsonSerializerOptions statically

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Fix some profiles for H264 AMF encoder
=> Fix some profiles for H264 AMF encoder

MediaBrowser.Model/Dlna/StreamBuilder.cs
Fixes https://github.com/jellyfin/jellyfin-plugin-nextpvr/issues/15
=> Fix null reference when logging

Jellyfin.Drawing.Skia/StripCollageBuilder.cs
**Changes**
- Fix boxes in library name backdrop
**Issues**
Before
After
=> Fix boxes in library name backdrop

Jellyfin.Networking/Manager/NetworkManager.cs
Fix has been implemented on web.
=> Removed workaround code as web is now fixed.

Emby.Server.Implementations/Library/UserDataManager.cs, MediaBrowser.Model/Configuration/ServerConfiguration.cs
Web PR: https://github.com/jellyfin/jellyfin-web/pull/2286
**Changes**
Split the resume logic for audiobooks from the rest of the media
**Issues**
https://github.com/jellyfin/jellyfin/issues/4897
=> Split resume function for Audiobooks

Emby.Server.Implementations/Library/SearchEngine.cs
**Changes**
Use Math.Min to make sure the limit parameter is never higher then the amount of items.
**Issues**
Closes #4888
=> Fix search hint endpoint error

Jellyfin.Data/Jellyfin.Data.csproj, MediaBrowser.Model/MediaBrowser.Model.csproj, MediaBrowser.Model/Providers/ExternalIdInfo.cs, MediaBrowser.Providers/Manager/ProviderManager.cs, MediaBrowser.XbmcMetadata/EntryPoint.cs, MediaBrowser.XbmcMetadata/MediaBrowser.XbmcMetadata.csproj, MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs, MediaBrowser.XbmcMetadata/Parsers/MovieNfoParser.cs, MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs, MediaBrowser.XbmcMetadata/Providers/BaseNfoProvider.cs, MediaBrowser.XbmcMetadata/Providers/BaseVideoNfoProvider.cs, MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs, MediaBrowser.XbmcMetadata/Savers/MovieNfoSaver.cs
**Changes**
Enable nullable on the project level and reflect changes in code.
**Issues**
Part of issue #2768
=> Enable nullable for MediaBrowser.XbmcMetadata project

MediaBrowser.Common/Net/IPNetAddress.cs
Fixes IsInLocalNetwork returning false due to the wrong subnet of the IPv4 loopback.
=> Fixed loopback subnet

Jellyfin.Api/ModelBinders/CommaDelimitedArrayModelBinder.cs, Jellyfin.Api/ModelBinders/NullableEnumModelBinder.cs, Jellyfin.Api/ModelBinders/PipeDelimitedArrayModelBinder.cs, MediaBrowser.Common/Json/Converters/JsonCommaDelimitedArrayConverter.cs, MediaBrowser.Common/Json/Converters/JsonPipeDelimitedArrayConverter.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4915
The logs aren't really errors, just notifications for the client to update the parameters they're sending.
=> Change converter log level

Emby.Server.Implementations/Dto/DtoService.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4907
=> Attach correct Blurhash to BaseItemPerson

MediaBrowser.Common/Json/Converters/JsonOmdbNotAvailableInt32Converter.cs, MediaBrowser.Common/Json/Converters/JsonOmdbNotAvailableStringConverter.cs, MediaBrowser.Common/Json/Converters/JsonOmdbNotAvailableStructConverter.cs, MediaBrowser.Providers/Plugins/Omdb/OmdbItemProvider.cs, MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs, tests/Jellyfin.Common.Tests/Json/JsonOmdbConverterTests.cs
Fixes #4931
Fixes #4965
Fixes #4950
=> Fix OMDb converter

Emby.Dlna/Main/DlnaEntryPoint.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4949#issuecomment-756205507
Uses external router port and not internal JF port.
=> Fixed DLNA Server on RC2

Emby.Server.Implementations/Dto/DtoService.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4957
I wasn't able to reproduce, but this should still fix the issue.
=> Fix potential null reference

tests/Jellyfin.Common.Tests/Json/JsonNullableGuidConverterTests.cs
https://cov.b0n.dev/jellyfin/MediaBrowser.Common_JsonNullableGuidConverter.html
=> Cover all branches in JsonNullableGuidConverter

Emby.Server.Implementations/Localization/iso6392.txt
**Changes**
Add Chinese Traditional and Chinese Hong Kong as additional metadata languages.
**Issues**
Fixes #4979
=> Add additional chinese languages

MediaBrowser.Controller/Entities/PersonInfo.cs, MediaBrowser.Controller/Providers/IProviderManager.cs, MediaBrowser.LocalMetadata/Parsers/BaseItemXmlParser.cs, MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs, MediaBrowser.XbmcMetadata/Parsers/MovieNfoParser.cs, MediaBrowser.sln, tests/Jellyfin.Server.Implementations.Tests/LiveTv/HdHomerunHostTests.cs, tests/Jellyfin.XbmcMetadata.Tests/Jellyfin.XbmcMetadata.Tests.csproj, tests/Jellyfin.XbmcMetadata.Tests/Parsers/MovieNfoParserTests.cs, tests/Jellyfin.XbmcMetadata.Tests/Test Data/Justice League.nfo
=> Add tests for NFO parsers

Emby.Server.Implementations/TV/TVSeriesManager.cs, Jellyfin.Api/Controllers/TvShowsController.cs, MediaBrowser.Model/Querying/NextUpQuery.cs
Fixes AndroidTV with 10.7, allows Vue to do what they want
https://github.com/jellyfin/jellyfin/pull/5026
=> Add parameter to disable sending first episode as next up

MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs, MediaBrowser.XbmcMetadata/Savers/EpisodeNfoSaver.cs, tests/Jellyfin.XbmcMetadata.Tests/Parsers/EpisodeNfoProviderTests.cs, tests/Jellyfin.XbmcMetadata.Tests/Parsers/MovieNfoParserTests.cs, tests/Jellyfin.XbmcMetadata.Tests/Parsers/MusicAlbumNfoProviderTests.cs, tests/Jellyfin.XbmcMetadata.Tests/Parsers/MusicArtistNfoParserTests.cs, tests/Jellyfin.XbmcMetadata.Tests/Parsers/SeasonNfoProviderTests.cs, tests/Jellyfin.XbmcMetadata.Tests/Parsers/SeriesNfoParserTests.cs, tests/Jellyfin.XbmcMetadata.Tests/Test Data/Season 01.nfo, tests/Jellyfin.XbmcMetadata.Tests/Test Data/The Best of 1980-1990.nfo, tests/Jellyfin.XbmcMetadata.Tests/Test Data/The Bone Orchard.nfo
**Changes**
Add tests for music album, episode and season nfo files
**Issues**
=> Add additional tests for nfo parsing

.github/workflows/codeql-analysis.yml, Jellyfin.Api/Jellyfin.Api.csproj, Jellyfin.Data/Jellyfin.Data.csproj, Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj, Jellyfin.Server/Jellyfin.Server.csproj, MediaBrowser.Model/MediaBrowser.Model.csproj, deployment/Dockerfile.debian.amd64, deployment/Dockerfile.debian.arm64, deployment/Dockerfile.debian.armhf, deployment/Dockerfile.linux.amd64, deployment/Dockerfile.linux.amd64-musl, deployment/Dockerfile.linux.arm64, deployment/Dockerfile.linux.armhf, deployment/Dockerfile.macos, deployment/Dockerfile.portable, deployment/Dockerfile.ubuntu.amd64, deployment/Dockerfile.ubuntu.arm64, deployment/Dockerfile.ubuntu.armhf, deployment/Dockerfile.windows.amd64, tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
https://devblogs.microsoft.com/dotnet/net-january-2021/
Dealers choice if backport.
=> Update to dotnet 5.0.2

Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteLogFileTask.cs
Extension was changed in https://github.com/jellyfin/jellyfin/pull/4514.
=> Fix delete log task

Emby.Server.Implementations/Plugins/PluginManager.cs
Included in https://github.com/jellyfin/jellyfin/pull/4912
Bug fix so that the plugin can be located via API.
=> Plugin bug fixes

Emby.Server.Implementations/Plugins/PluginManager.cs
**Changes**
**Issues**
Fixes server startup with incompatible plugins
=> Catch TypeLoadException during plugin load

Jellyfin.Api/Controllers/PackageController.cs, Jellyfin.Api/Controllers/UserController.cs, Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1589#issuecomment-602602417
Resulting openapi spec: [openapi.zip](https://github.com/jellyfin/jellyfin/files/5863300/openapi.zip)
=> Fix openapi nullable properties

Emby.Server.Implementations/Dto/DtoService.cs
https://www.reddit.com/r/jellyfin/comments/l4pkp9/metadata_manager_doesnt_work/
I wasn't able to reproduce but these lines were the only ones modified in the past ~6 months.
=> Add null check for ImageTags

Jellyfin.Api/Helpers/DynamicHlsHelper.cs
**Changes**
- Make FRAME-RATE field culture invariant
https://github.com/jellyfin/jellyfin/issues/3815#issuecomment-768420953
**Issues**
Should fix:
https://github.com/jellyfin/jellyfin/issues/3815
=> Make FRAME-RATE field culture invariant

Emby.Server.Implementations/IO/ManagedFileSystem.cs
Fixes https://github.com/jellyfin/jellyfin/issues/5135
=> Don't skip hidden / system files when enumerating

MediaBrowser.Common/Extensions/ShuffleExtensions.cs, tests/Jellyfin.Common.Tests/Extensions/ShuffleExtensionsTests.cs
https://cov.b0n.dev/jellyfin/MediaBrowser.Common_ShuffleExtensions.html
Fix coverage regression
=> Add test for ShuffleExtensions

Emby.Dlna/Profiles/SonyBravia2010Profile.cs, Emby.Dlna/Profiles/SonyBravia2011Profile.cs, Emby.Dlna/Profiles/SonyBravia2012Profile.cs, Emby.Dlna/Profiles/SonyBravia2013Profile.cs, Emby.Dlna/Profiles/SonyBravia2014Profile.cs, Emby.Dlna/Profiles/Xml/Sony Bravia (2010).xml, Emby.Dlna/Profiles/Xml/Sony Bravia (2011).xml, Emby.Dlna/Profiles/Xml/Sony Bravia (2012).xml, Emby.Dlna/Profiles/Xml/Sony Bravia (2013).xml, Emby.Dlna/Profiles/Xml/Sony Bravia (2014).xml, Emby.Naming/Common/NamingOptions.cs, Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunManager.cs, MediaBrowser.MediaEncoding/Subtitles/AssParser.cs, MediaBrowser.MediaEncoding/Subtitles/SrtParser.cs
**Changes**
Replaced /d with [0-9] in all jellyfin/jellyfin files
**Issues**
#2923
=> Replaced /d with [0-9], see issue #2923

Emby.Naming/Common/NamingOptions.cs
=> Remove last usage of \d

Emby.Server.Implementations/Plugins/PluginManager.cs, tests/Jellyfin.Server.Implementations.Tests/Plugins/PluginManagerTests.cs
=> Add regression test for PluginManager.SaveManifest

Emby.Naming/Emby.Naming.csproj, Jellyfin.Data/Jellyfin.Data.csproj, MediaBrowser.Common/MediaBrowser.Common.csproj, MediaBrowser.Controller/MediaBrowser.Controller.csproj, MediaBrowser.Model/MediaBrowser.Model.csproj, SharedVersion.cs, build.yaml, debian/changelog, debian/metapackage/jellyfin, fedora/jellyfin.spec
**Changes**
Prep for next major release (and to avoid NuGet headaches).
**Issues**
N/A
=> Bump version to 10.8.0 for next release

.ci/azure-pipelines-abi.yml, .ci/azure-pipelines-api-client.yml, .ci/azure-pipelines-main.yml, .ci/azure-pipelines-test.yml, .ci/azure-pipelines.yml, Jellyfin.Api/Jellyfin.Api.csproj, Jellyfin.Data/Jellyfin.Data.csproj, Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj, Jellyfin.Server/Jellyfin.Server.csproj, deployment/Dockerfile.debian.amd64, deployment/Dockerfile.debian.arm64, deployment/Dockerfile.debian.armhf, deployment/Dockerfile.linux.amd64, deployment/Dockerfile.linux.amd64-musl, deployment/Dockerfile.linux.arm64, deployment/Dockerfile.linux.armhf, deployment/Dockerfile.macos, deployment/Dockerfile.portable, deployment/Dockerfile.ubuntu.amd64, deployment/Dockerfile.ubuntu.arm64, deployment/Dockerfile.ubuntu.armhf, deployment/Dockerfile.windows.amd64, tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0.3/5.0.3.md
Also updated the api-generator to be non-beta. https://github.com/OpenAPITools/openapi-generator/releases/tag/v5.0.1
=> Update to dotnet 5.0.3

Jellyfin.Api/Attributes/AcceptsFileAttribute.cs, Jellyfin.Api/Attributes/AcceptsImageFileAttribute.cs, Jellyfin.Api/Controllers/ImageController.cs, Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs, Jellyfin.Server/Filters/FileRequestFilter.cs
Fixes https://github.com/jellyfin/jellyfin/issues/5197
This has no effect on the API, only changes the generated `openapi.json`
The `[AcceptsImageFile]` attribute was added to all applicable requests that manually reference `Request.Body` 
New `openapi.json` for reference: [openapi.json.txt](https://github.com/jellyfin/jellyfin/files/5962290/openapi.json.txt)
[Swagger.io reference](https://swagger.io/docs/specification/describing-request-body/file-upload/)
Old:
```json
"/Users/{userId}/Images/{imageType}": 
{
"post": {
"tags": [
"Image"
],
"summary": "Sets the user image.",
"operationId": "PostUserImage",
"parameters": [{
"name": "userId",
"in": "path",
"description": "User Id.",
"required": true,
"schema": {
"type": "string",
"description": "User Id.",
"format": "uuid"
}
},
{
"name": …
```
=> Add image file accept to openapi

Emby.Naming/TV/SeasonPathParser.cs
https://cov.b0n.dev/jellyfin/Emby.Naming_SeasonPathParser.html
=> 100% branch coverage for Emby.Naming

tests/Jellyfin.Naming.Tests/Video/VideoListResolverTests.cs
=> Fix broken test

MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
=> TMDB: Include year in search

Jellyfin.sln
https://cov.b0n.dev/jellyfin/MediaBrowser.Model_StringHelper.html
This should be covered now
=> Add Jellyfin.Model.Tests project to the solution

MediaBrowser.Model/Entities/ProviderIdsExtensions.cs, MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs, tests/Jellyfin.Model.Tests/Entities/ProviderIdsExtensionsTests.cs
=> TMDB: Also search with IMDB or TVDB Id if specified

Emby.Dlna/Main/DlnaEntryPoint.cs, Emby.Server.Implementations/ApplicationHost.cs, MediaBrowser.Controller/IServerApplicationHost.cs
Url / ports contained in PublishedServerUrl startup option is now assumed to be correct.
=> Fix for #5280

Jellyfin.Server/Program.cs
Renamed config file name in message.
=> Corrected logging message

MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeProvider.cs, MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs, MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs
**Changes**
**Issues**
Fixes #5161
=> Fix TMDb search name containing year

Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Fixes https://github.com/jellyfin/jellyfin/issues/5320
oops
=> Fix case-sensitive json parsing

Jellyfin.Api/Controllers/LibraryStructureController.cs, Jellyfin.Api/Models/LibraryStructureDto/UpdateMediaPathRequestDto.cs
It's just a request body, no query parameters.
=> Fix UpdateMediaPath model binding

README.md
**Changes**
In checking out and building the code I ran into an issue where ffmpeg wasn't installed and audio file metadata wasn't being loaded. Looking at the README it doesn't mention the ffmpeg requirement so I thought I would add it to help the next person.
**Issues**
=> Update README to include ffmpeg

Emby.Server.Implementations/Library/LibraryManager.cs, Emby.Server.Implementations/Library/PathExtensions.cs, tests/Jellyfin.Server.Implementations.Tests/Library/PathExtensionsTests.cs
=> make sure network path substitution matches correctly

Emby.Server.Implementations/Library/LibraryManager.cs, MediaBrowser.Model/Entities/JsonLowerCaseConverter.cs, MediaBrowser.Model/Entities/VirtualFolderInfo.cs, tests/Jellyfin.Model.Tests/Entities/JsonLowerCaseConverterTests.cs
=> Fix casing CollectionType

CONTRIBUTORS.md, Emby.Server.Implementations/Library/PathExtensions.cs
**Changes**
I changed Length == 0 to string.IsNullOrEmpty to account for null values
**Issues**
https://github.com/jellyfin/jellyfin/issues/5408
=> Changed string.Length == 0 to string.IsNullOrEmpty in case of null

Emby.Naming/Video/CleanStringParser.cs, Emby.Naming/Video/VideoResolver.cs, tests/Jellyfin.Naming.Tests/Video/CleanStringTests.cs
This can occur when an entity doesn't have a Name eg. https://github.com/crobibero/jellyfin-plugin-tmdb-trailers/issues/6
=> do not throw ArgumentNullException in TryCleanString

Emby.Server.Implementations/LiveTv/EmbyTV/EncodedRecorder.cs, Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunUdpStream.cs, Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs, Jellyfin.Api/Helpers/TranscodingJobHelper.cs
**Changes**
Partial rollback of #5402 to potentially fix livetv / HdHomeRun streaming
**Issues**
Fixes #5427 #5438
=> Use FileShare.Read to fix HdHomeRun

MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs, MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs
Includes post-ProviderIdExtensions cleanup
**Issues**
Fixes #5266
=> Use imdbid as fallback in movie provider

Jellyfin.Server/Filters/WebsocketModelFilter.cs
Fixes https://github.com/jellyfin/jellyfin/issues/5478
=> Add SessionMessageType to generated openapi spec

Jellyfin.Api/Controllers/LibraryController.cs, Jellyfin.Api/Controllers/NotificationsController.cs, Jellyfin.Api/Models/LibraryDtos/MediaUpdateInfoDto.cs, Jellyfin.Api/Models/LibraryDtos/MediaUpdateInfoPathDto.cs, Jellyfin.Api/Models/NotificationDtos/AdminNotificationDto.cs
Sometimes API just be like that.
Fixes endpoints that weren't migrated correctly
=> Fix third party integration

Jellyfin.sln, tests/Jellyfin.Server.Integration.Tests/Jellyfin.Server.Integration.Tests.csproj, tests/Jellyfin.Server.Tests/Jellyfin.Server.Tests.csproj
=> Fix integration test project

Jellyfin.Data/Entities/User.cs, Jellyfin.Server.Implementations/Users/UserManager.cs, tests/Jellyfin.Api.Tests/Auth/CustomAuthenticationHandlerTests.cs, tests/Jellyfin.Api.Tests/TestHelpers.cs
**Changes**
Fixes permissions being duplicated as a result of side effects of the user entity constructor.
=> Fix duplicate permissions

MediaBrowser.Common/Json/Converters/JsonStringConverter.cs, MediaBrowser.Common/Json/JsonDefaults.cs, tests/Jellyfin.Common.Tests/Json/JsonStringConverterTests.cs
Fixes https://github.com/jellyfin/jellyfin/issues/5503
=> Add JsonStringConverter

Emby.Server.Implementations/Library/Resolvers/BaseVideoResolver.cs, Emby.Server.Implementations/Library/Resolvers/Books/BookResolver.cs, Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs, Emby.Server.Implementations/Library/Resolvers/TV/EpisodeResolver.cs, MediaBrowser.Controller/Resolvers/BaseItemResolver.cs, tests/Jellyfin.Server.Implementations.Tests/Library/EpisodeResolverTest.cs
Shitty solution to a shitty problem
Fixes #5264
=> do not resolve episode-like files if they are in extras folders

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Disable auto rotation for some HWA methods.
**Issues**
https://www.reddit.com/r/jellyfin/comments/m2p4mg/rotated_videos_cant_be_transcoded_but_if_i/
=> Disable auto rotation for some HWA methods

CONTRIBUTORS.md, Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs, MediaBrowser.Controller/LiveTv/ChannelInfo.cs
**Changes**
Adds 'group-title' parsing for the M3U tuner.
This is the beginning of work to include a 'channel groups' page in the UI. 
**Issues**
=> Add 'group-title' channel parsing

Jellyfin.Api/Controllers/SubtitleController.cs
Fixes https://github.com/jellyfin/jellyfin/issues/5581
=> Allow subtitle format to be set from query parameter.

MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
**Changes**
Added original title...
**Issues**
https://www.reddit.com/r/jellyfin/comments/mhsibn/original_title_no_longer_automatically_added_to/
=> set original title in tmdbmovieprovider

MediaBrowser.Model/Dlna/StreamBuilder.cs
Collection of various tweaks to the StreamBuilder class, mostly logging and code style related.
=> StreamBuilder tweaks

Jellyfin.Server.Implementations/Users/UserManager.cs
=> Clean up UserManager.AuthenticateUser

Emby.Dlna/ConnectionManager/ControlHandler.cs, Emby.Dlna/ContentDirectory/ControlHandler.cs, Emby.Dlna/MediaReceiverRegistrar/ControlHandler.cs, Emby.Dlna/Service/BaseControlHandler.cs, Emby.Server.Implementations/IO/ManagedFileSystem.cs, Emby.Server.Implementations/Library/Resolvers/TV/SeriesResolver.cs, Emby.Server.Implementations/LiveTv/EmbyTV/EpgChannelData.cs, MediaBrowser.Model/IO/IFileSystem.cs
* `GetValueOrDefault` exists in the BCL
* `IsVideoPlaceHolder` wasn't used anywhere
=> Remove useless code

Emby.Server.Implementations/HttpServer/WebSocketManager.cs
**Changes**
Added a call to IAuthService.Authenticate in the websocket handler.
**Issues**
Fixes #5689
=> add simple auth handling to websocketmanager

Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs, Jellyfin.Server/Filters/AdditionalModelFilter.cs
Fixes https://github.com/jellyfin/jellyfin/issues/5686
Backport because it's such a minor change.
=> Add SessionDiscoveryInfo to generated api-docs
