jellyfin/jellyfin

- Emby.Server.Implementations/ApplicationHost.cs
Added X509KeyStorageFlags.UserKeySet option when creating certificate for use by jellyfin. (Needed to test https)
Result under the user account is "Access Denied". It looks like, in order to install/use certs you need to be an admin under windows, so loaded it under the user account.
https://stackoverflow.com/questions/49071730/x509certificate2-access-denied-exception-if-use-ecc-certificate
> Fix - Access Denied on using certificates in windows as user.

- Jellyfin.Data/Entities/ActivityLog.cs
**Changes**
* Changes the default log level for the existing ActivityLog constructor to "Information" instead of "Trace"
Trace is basically the nuclear option, yet currently every activity log entry uses it. This switches the default to Information, so the log level is more sane
* Adds an overloaded constructor to allow specifying the log level. This goes hand in hand with the previous change, in order to allow future PRs to specify better log levels for individual entries
**Issues**
> Add overloaded constructor for ActivityLog levels

- Jellyfin.Drawing.Skia/SkiaEncoder.cs
Should fix https://github.com/jellyfin/jellyfin/issues/4744
cc @anthonylavado as I don't have any way to test this.
--
ImageFilter was added in https://github.com/jellyfin/jellyfin/pull/3772. I'm not sure why it was added but it seems to be the source of the blueberries.
> Fix blueberry

- MediaBrowser.Model/Entities/ProviderIdsExtensions.cs
Search wasn't happening because this function was returning an empty string instead of null
> Fix get provider id extension

- MediaBrowser.Providers/TV/SeriesMetadataService.cs
**Changes**
Added the dummy season provider to SeriesMetadataService and made it a bit prettier
**Issues**
Supercedes #4755
Fixes #4691
> Add missing seasons during AfterMetadataRefresh

- Emby.Dlna/Profiles/SonyPs3Profile.cs
- Emby.Dlna/Profiles/SonyPs4Profile.cs
- Emby.Dlna/Profiles/Xml/Sony PlayStation 3.xml
- Emby.Dlna/Profiles/Xml/Sony PlayStation 4.xml
**Changes**
- MP3 in MPEG-TS is not supported by PS3 and PS4, use AAC instead.
https://manuals.playstation.net/document/en/ps3/current/video/filetypes.html
> MPEG-2 PS (MPEG2 Audio Layer 2, AAC LC, AC3(Dolby Digital), LPCM)
> MPEG-2 TS(MPEG2 Audio Layer 2, AC3(Dolby Digital), AAC LC)
> MPEG-2 TS(H.264/MPEG-4 AVC, AAC LC)
https://manuals.playstation.net/document/gb/ps4/music/mp_format_m.html
> MPEG-2 TS
> Video: H.264/MPEG-4 AVC High Profile Level 4.2, MPEG2 Visual
> Audio: MP2 (MPEG2 Audio Layer 2), AAC LC, AC-3 (Dolby Digital)
**Issues**
Fixes #4806
> Correct DLNA audio codecs for PS3 and PS4

- Emby.Server.Implementations/HttpServer/Security/SessionContext.cs
Currently (in master) it is impossible to schedule a recording, either for a series or an individual showing, due to an invalid cast.
I'm not sure if this changed with .NET 5.0, however this used to work and there doesn't appear to be a code change that would have caused this to break.
**Changes**
Modify SessionContext.GetUser(object) to cast requestContext to HttpRequest, then use the HttpContext property. This is in lieu of casting directly to an HttpContext.
**Issues**
I was unable to find an issue related to this. This likely exists only in the master branch.
> Fix Live TV Recording Scheduling

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Fix constrained high profile for some encoders
- Extended profile is not supported by any known h264 encoders
- Replace HEVC 10-bit profiles with main profile
https://github.com/jellyfin/jellyfin-android/pull/274#discussion_r542541040
> Fix some video profiles for Android client

- Emby.Dlna/Main/DlnaEntryPoint.cs
- Jellyfin.Api/Controllers/DlnaServerController.cs
Fix for https://github.com/jellyfin/jellyfin/issues/4431
The Dlna server class is instantiated whether or not the dlna server is enabled or not. (the attribute only controls the comms).
This change caused http not found to be returned if the dlna server is disabled.
> Fix: Disable dlna server API responses if dlna is disabled.

- Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
SchedulesDirect no longer refreshes channels properly and was introduced in changeset 81ca6cb47cb1df49196f9a961de4698fbc406ec1.
*NOTE:* Please also merge into the 10.7 branch after this is approved as it's broken in that branch too.
**Changes**
new List(int) sets the capacity of the list, however it does not pre-allocate those entries, and thus treating it like a pre-allocated array results in an index out of range exception. .Add() or .AddRange() must be used to add items.
Therefore, this was modified to use a foreach loop to properly utilize an array. The intent of the original change still exists however as the list capacity is still set on creation.
**Issues**
I couldn't find an open issue. This was introduced in the 10.7 branch and master.
**Stack Trace**
```
Dec 22 19:59:42 jenny …
```
> SchedulesDirect no longer refreshes channels properly

- .ci/azure-pipelines-package.yml
**Changes**
Don't build unstable Nuget packages when building stable Nuget packages. Uses the same condition as unstable Docker images.
**Issues**
Possible fix for CI failure on tags since it doesn't try to push the unstable Nuget packages to nuget.org.
> Don't build unstable Nuget packages on tags

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Avoid transcoding to 3ch audio for HLS streaming
**Issues**
Transcoding to 3ch will break the playback.
Fixes https://github.com/jellyfin/jellyfin-web/issues/2249
> Avoid transcoding to 3ch audio for HLS streaming

- Jellyfin.Server/Jellyfin.Server.csproj
- MediaBrowser.Providers/MediaBrowser.Providers.csproj
This should fix master build failures.
I didn't find any usages of `SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_sqlite3());`, so I'm not sure what it was originally used for.
`Newtonsoft.Json` can be removed when all providers are moved to plugins.
> Fix dependencies

- MediaBrowser.Model/Configuration/ServerConfiguration.cs
**Changes**
We should enable these by default. With the recent removal of TVDB, we now have 0 metadata provider enabled by default for TV libraries, which will cause an issue for users on release (I'm expecting a bunch of them to not notice and open issues when there's no metadata).
**Issues**
> Enable TMDB and OMDB by default

- MediaBrowser.Common/Json/Converters/JsonNullableGuidConverter.cs
- MediaBrowser.Common/Json/JsonDefaults.cs
- tests/Jellyfin.Common.Tests/Json/JsonNullableGuidConverterTests.cs
Fixes https://github.com/jellyfin/jellyfin-plugin-nextpvr/issues/16
This causes nullable GUIDs to be serialized to `null` instead of `Guid.Empty`
> Add JsonConverter for Nullable Guids

- Jellyfin.Api/Helpers/StreamingHelpers.cs
Came across it during dlna server debugging last night. Not that clued up with what this code actually does (yet) - but it's something to do with playback.
state.VideoStream is a variable that can be null (definition not nullable yet), but there isn't a null check before the _state.VideoStream.BitRate.HasValue_ check, causing an exception. Checks on state.VideoStream's nullable state seem to appear everywhere else.
```
&& state.VideoStream != null
&& state.VideoRequest.VideoBitRate.HasValue
&& state.VideoStream.BitRate.HasValue
```
adding this check, permits the playback to start.
Admittedly, i am using a codebase which is somewhat modified from 10.7's, but this looks to be possible in the current code base.
> Null exception fix

- Jellyfin.Api/Controllers/TvShowsController.cs
Fixes https://github.com/jellyfin/jellyfin/issues/4932
Confirmed this was the original functionality from 10.6
https://github.com/jellyfin/jellyfin/blob/907695dec7fda152d0e17c1197637bc0e17c9928/MediaBrowser.Api/TvShowsService.cs#L467
> Fix inverted SkipWhile

- CONTRIBUTORS.md
- Emby.Server.Implementations/Library/Resolvers/Audio/AudioResolver.cs
- Emby.Server.Implementations/Library/Resolvers/Audio/MusicAlbumResolver.cs
- Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
- MediaBrowser.Controller/Resolvers/ResolverPriority.cs
Fixes #3169 and #2879
Simply changes ResolverPriority of the resolvers so that MusicArtistResolver runs before MusicAlbumResolver. This makes a folder with albums inside a artist folder, regardless of whether there are audio files directly in the folder.
Previously, the MusicAlbumResolver would see an audio file in the artist folder and consider it an album, breaking the real albums.
> Fix library with music directly under artist folder

- Emby.Dlna/PlayTo/PlayToController.cs
- Emby.Server.Implementations/Session/SessionManager.cs
- MediaBrowser.Model/Session/SessionMessageType.cs
**Changes**
Fixes a change to the capitalization of the "Playstate" command in 10.7 which broke some remote control commands in web
**Issues**
Fixes jellyfin/jellyfin-web#2245
> Fix capitalization of Playstate message

- Emby.Server.Implementations/IO/ManagedFileSystem.cs
- Emby.Server.Implementations/Library/Resolvers/PlaylistResolver.cs
Ignore inaccessible files & folders during library scans.
**Changes**
Library scans enumerate many files and folders. If a single file or folder is inaccessible due to permission issues during one of those enumeration calls, the whole enumeration call would fail. For example if you have a single TV show or movie folder that is inaccessible, the library scan would fail to enumerate any other shows / movies within that same parent folder.
Examples of those errors:
```
[2020-12-31 17:40:25.260 -08:00] [ERR] [13] Emby.Server.Implementations.Library.LibraryManager: Error resolving path "M:\Anime\A_Secret_Folder"
System.UnauthorizedAccessException: Access to the path 'M:\Anime\A_Secret_Folder' is denied.
at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean …
```
> Ignore inaccessible files & folders during library scans

- CONTRIBUTORS.md
- Emby.Server.Implementations/ScheduledTasks/Triggers/DailyTrigger.cs
- MediaBrowser.MediaEncoding/Subtitles/SsaParser.cs
- tests/Jellyfin.Controller.Tests/AlphanumComparatorTests.cs
- tests/Jellyfin.MediaEncoding.Tests/SsaParserTests.cs
Credit to @Bond-009 for having made most of the string culture fixes already.
**Changes**
Fix bug in SsaParser.cs primary color `{\1c}` formatting that would leave
behind the `{\1c}` closing token and instead append `</font>` token
unconditionally to the dialogue text. Add tests.
Change AlphanumComparatorTests.cs complementary test data generation
from an array shuffle to an array reversal. Although it was previously
using a seeded Random, the shuffle itself could result in no
rearrangement of elements if the seed or test data changed over time.
The reversal guarantees reordering of elements and has the added benefit
of simplifying the test code since no special handling is needed for
arrays of 2 elements.
Change DailyTrigger.cs logging of TriggerDate format to
"yyyy-MM-dd HH:mm:ss.fff …
> Fix string culture specificity

- fedora/jellyfin.spec
**Changes**
Fix the version dependencies in the rpm spec. The latest stable rpm for centos is broken because the jellyfin rpm requires `jellyfin-web >= 10.6` and `jellyfin-web < 10.7`. This updates the spec to use the variables for versioning so the dependencies shouldn't need to be maintained going forward (and actually matches the `jellyfin-server` dependency)
**Issues**
https://github.com/jellyfin/jellyfin/issues/4938
> Fix rpm package dependencies

- Jellyfin.Networking/Manager/NetworkManager.cs
- tests/Jellyfin.Networking.Tests/NetworkTesting/NetworkParseTests.cs
Changed mock network split character to | from : so that IPv6 addresses can be included in the mock networks.
> Change split character

- Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs
- MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs
> The OpenWrite method opens a file if one already exists for the file path,
or creates a new file if one does not exist. For an existing file,
it does not append the new text to the existing text. Instead,
it overwrites the existing characters with the new characters.
If you overwrite a longer string
(such as "This is a test of the OpenWrite method") with a shorter string
(such as "Second run"), the file will contain a mix of the strings
("Second runtest of the OpenWrite method").
Ref: https://docs.microsoft.com/en-us/dotnet/api/system.io.file.openwrite?view=net-5.0#remarks
**Issues**
Should fix #5000
Should fix #4965
> Open FileStream with FileMode.Create instead of FileMode.OpenOrCreate

- Emby.Dlna/Didl/DidlBuilder.cs
- Emby.Dlna/PlayTo/PlayToController.cs
- Emby.Dlna/PlayTo/TransportCommands.cs
**Fix 1:** Didl metadata wasn't being populated (all the time???) as flush was absent.
**Fix 2:** Exception caused by non-string GUID being parsed. 
(Raised by the DLNA eventing when the TV was already playing alternative content that contained the word "audios" in the url)
Additional errors still exist in metadata parsing around url encoding, which results in xml parsing errors. This is addressed in the plugin.
> Fix DLNA PlayTo encoding issue

- .ci/azure-pipelines-package.yml
**Changes**
Another try at fixing nuget ci. This time I actually tested it.
- Don't specify `.snupkg` files in push because they get pushed automatically (https://github.com/Microsoft/azure-pipelines-tasks/issues/10140)
- Build Nuget packages with version specified in the git tag name (see Docker images) https://github.com/jellyfin/jellyfin/blob/406ae3e43a20216292c554151fa2d0e2a09edfa3/.ci/azure-pipelines-package.yml#L126-L128
Note: I'm tagging #4859 for backport as well since I forgot that at the time of making the PR
This is the sample output from a build for the tag `v10.7.1-rc4` with package names changed to `Example.*`
**Build task:**
```
...
Successfully created package '/home/vsts/work/1/a/Example.Naming.10.7.1-rc4.nupkg'.
Successfully created package …
```
> Change stable ci nuget build command

- MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs
**Changes**
Don't write `outline` tag for videos. It should only be scraped from IMDB according to the [Kodi wiki](https://kodi.wiki/view/NFO_files/Movies#nfo_Tags)
**Issues**
Fixes #3142
> Don't write tagline in <outline> in nfo files

- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeasonProvider.cs
A copy of: https://github.com/jellyfin/jellyfin-plugin-tmdb/pull/1
Apparently TMDB season provider copies `SeasonInfo.Name` to `MetadataResult` which:
1. Does not really make sense. In this case we should not return name at all.
2. Causes an issue where all season names would be replaced with series name. 
Root cause of this issue is in Jellyfin itself which for some reason sets `SeasonInfo.Name` to series name when sending it to `GetMetadata` but anyways I don't think we should copy anything from `SeasonInfo` to `MetadataResult` even if name was correctly set to 'Season X'.
Probably it was originally set to `Name = seasonResult.Name` but someone did not like whatever TMDbLib returned here so it was changed to `info.Name`. Quote from …
> Remove season name from metadata result

- MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs
Fixes #4826 and bypasses dotnet bug. (https://github.com/dotnet/runtime/issues/42790)
May be other occurrences of this bug in JF.
From Dotnet Documentation
Filemode.Create - Specifies that the operating system should create a new file.
If the file already exists, it will be overwritten. This requires Write permission. 
FileMode.Create is equivalent to requesting that if the file does not exist, use CreateNew;
otherwise, use Truncate. (0 byte file)
If the file already exists but is a hidden file, an UnauthorizedAccessException exception is thrown.
> Fixes zero byte nfo files.

- MediaBrowser.XbmcMetadata/EntryPoint.cs
**Changes**
Remove check for `IsSaveLocalMetadataEnabled` during nfo `OnUserDataSaved`. It doesn't belong there and prevents this event from saving nfo metadata if a user marked an item as watched.
During a normal library scan the method responsible for saving the metadata allows nfo saving if the nfo saver is enabled and `IsSaveLocalMetadataEnabled` is disabled. In my opinion this is the correct way.
During the `OnUserDataSaved` event it only safes the nfo if `IsSaveLocalMetadataEnabled` is enabled. This leads to the confusion why nfo metadata does not get saved if the user data changes but does get saved if a normal library scan is triggered (see issue below). IMO `IsSaveLocalMetadataEnabled` should only be responsible for saving the images in the media folder or not. We don't need 2 …
> Fix nfo saving during UserDataSaved event

- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MovieNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Test Data/Justice League.nfo
**Changes**
Add support for reading `type` tag inside `actor` tag in nfo files. NfoSaver already saves the person type correctly.
Also added it to the movie parser test
**Issues**
Fixes #3686
> Process actor type in nfo files

- Emby.Server.Implementations/Library/MediaSourceManager.cs
- Emby.Server.Implementations/LiveTv/LiveTvManager.cs
- MediaBrowser.Controller/Entities/CollectionFolder.cs
This test uses a very small object (CountryInfo), using a bigger object
would increase the difference in allocated memory.
```
BenchmarkDotNet=v0.12.1, OS=fedora 32
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100
[Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.51904, CoreFX 5.0.20.51904), X64 RyuJIT
DefaultJob : .NET Core 5.0.0 (CoreCLR 5.0.20.51904, CoreFX 5.0.20.51904), X64 RyuJIT
|          Method |       Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------- |-----------:|---------:|---------:|-------:|------:|------:|----------:|
|  RoundTripBytes |   932.0 ns |  5.09 ns |  4.25 ns | 0.1173 |     - |     - |     368 B |
| RoundTripString | 1,114.8 ns | 22.19 ns | 23.74 ns | 0.1469 |     - |     - | …
```
> Use JsonSerializer.SerializeToUtf8Bytes when doing a round trip

- Emby.Naming/Common/NamingOptions.cs
- tests/Jellyfin.Naming.Tests/TV/EpisodeNumberTests.cs
**Changes**
The previous expression was too greedy to consume digits, because the hyphen was optional. This lead to incorrect episode numbers for certain series with digits in their names, in those cases each episode was recognized as the same episode number (the digit from the series name).
The rule, which matches most standard  anime filenames, also had a lower priority than one of the Kodi rules, leading to incorrect recognition for absolute numbered episodes with triple digits and higher (first digit was used as season number, rest of digits as episode number). This also resolves one of the TODO test cases.
Additional test cases were added to ensure that both hyphens in different parts of the filename, as well as names without hyphens, still work correctly. All previous test cases …
> adjust episode path expression to allow digits in series names

- Emby.Server.Implementations/Channels/ChannelManager.cs
- Emby.Server.Implementations/LiveTv/EmbyTV/ItemDataProvider.cs
- Emby.Server.Implementations/Plugins/PluginManager.cs
- Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs
- Jellyfin.Server/Migrations/Routines/MigrateDisplayPreferencesDb.cs
This is faster and uses way less memory
```
BenchmarkDotNet=v0.12.1, OS=fedora 32
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100
[Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.51904, CoreFX 5.0.20.51904), X64 RyuJIT
DefaultJob : .NET Core 5.0.0 (CoreCLR 5.0.20.51904, CoreFX 5.0.20.51904), X64 RyuJIT
| Method |     Mean |   Error |  StdDev |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |---------:|--------:|--------:|--------:|------:|------:|----------:|
|  Bytes | 158.4 us | 2.56 us | 2.14 us | 16.8457 |     - |     - |  52.08 KB |
| String | 172.8 us | 0.78 us | 0.70 us | 41.5039 |     - |     - | 127.82 KB |
| Custom | 155.5 us | 2.95 us | 2.76 us | 10.0098 |     - |     - |  31.27 KB |
```
> JsonSerializer deserialize from bytes where possible

- Jellyfin.Api/Controllers/UserController.cs
- Jellyfin.Api/Models/UserDtos/ForgotPasswordPinDto.cs
**Changes**
Pre api-migration the data was sent like this:
```
{
"Pin": "secret-Pin"
}
```
After the api-migration the data was only accepted like this:
```
"secret-Pin"
```
This PR restores the old behavior.
> Fix forgot password pin request

- Emby.Server.Implementations/Session/SessionManager.cs
After using quick connect to login, two device entries are created in the Devices page: one with the server's name labeled `QuickConnect`, and another for the connecting device. The first entry is used to associate the user id to the login request and the second entry is created by `AuthenticateNewSessionInternal()`.
**Changes**
After authenticating the incoming quick connect request, delete the initial quick connect token from the authentication repository to avoid adding a second device to the list.
> Remove used quick connect tokens

- Emby.Server.Implementations/Plugins/PluginManager.cs
> This method uses UTF-8 encoding without a Byte-Order Mark (BOM), so using the GetPreamble method will return an empty byte array. If it is necessary to include a UTF-8 identifier, such as a byte order mark, at the beginning of a file, use the WriteAllText(String, String, Encoding) method overload with UTF8 encoding.
https://docs.microsoft.com/en-us/dotnet/api/system.io.file.writealltext?view=net-5.0#System_IO_File_WriteAllText_System_String_System_String_
TL;DR: BOM bad. JsonSerializer go boom. https://github.com/dotnet/runtime/issues/29838
Stack trace:
```
[15:10:52] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Error deserializing ?{
"category": "",
"changelog": "",
"description": "",
"guid": "4b9ed42f-5185-48b5-9803-6ff2989014c4",
"name": "Open Subtitles",
"overview": …
```
> Exclude BOM when writing meta.json plugin manifest

- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
- tests/Jellyfin.XbmcMetadata.Tests/Jellyfin.XbmcMetadata.Tests.csproj
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/EpisodeNfoProviderTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MovieNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MusicAlbumNfoProviderTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MusicArtistNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/SeriesNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Test Data/Justice League.nfo
- tests/Jellyfin.XbmcMetadata.Tests/Test Data/The Bone Orchard.nfo
**Changes**
- remove `case "musicBrainzArtistID":` from nfo parser because ids are handled dynamically
- add additional id tags for movies and episodes and test parsing for them
**Issues**
> Add test for generic nfo provider id parsing

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
- MediaBrowser.Model/Configuration/EncodingOptions.cs
Web changes:
https://github.com/jellyfin/jellyfin-web/pull/2350
ffmpeg fix:
https://github.com/jellyfin/jellyfin-ffmpeg/pull/59
**Changes**
- Add enhanced NVDEC decoder and format converter
fix green or corrupted frames when decoding some HDR contents. improve transcoding speed.
- Add VPP tonemapping for VAAPI  and QuickSync on Linux
faster tonemapping speed, **70-120fps 1080p and 30-50fps 4k on HD630** when doing 4k H2S.
Intel opencl runtime is not required by this method. only available on Intel VAAPI and QSV for now.
as for AMD VAAPI see https://gitlab.freedesktop.org/mesa/mesa/-/issues/3865
|     | Prerequisites  |
|  ----  | ----  |
| 1  | Intel KabyLake/GeminiLake chips or newer, such as i3-7100 and J4105 |
| 2  | Intel media-driver(iHD) 20.1 or newer |
| 3  | libva 2.4 or newer |
| …
> Fix for NVDEC decoder and improvements for VAAPI tonemap

- Emby.Server.Implementations/Library/Resolvers/Audio/MusicArtistResolver.cs
- Jellyfin.Api/Controllers/PluginsController.cs
- MediaBrowser.Model/Configuration/ServerConfiguration.cs
One has never been pushed to stable and another has defaulted to false since the last minor version without complaints so we're probably fine removing both.
> remove deprecated settings from server config

- MediaBrowser.Common/Json/JsonDefaults.cs
This should be done by adding `JsonPropertyName` attributes.
> Don't enable case-insensitivity for json by default

- MediaBrowser.Model/Configuration/ServerConfiguration.cs
**Changes**
When on the Preferred Metadata Language page in the setup wizard, the country selection defaults to the United States, but the language option has no default, which is annoying. I'd assume most Jellyfin users are primarily English speakers, so I think that justifies defaulting to English.
> Default to English metadata during the setup wizard.

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
This is a small change that uses the average frame rate reported by FFprobe instead of the real frame rate when determining if double rate deinterlacing should be enabled.
Some TS files containing interlaced H.264 video report the the field rate as the real frame rate (e.g. 50) and the average frame rate at the expected frame rate (e.g. 25). As a result double rate deinterlacing is currently disabled for these files, which this change fixes so it works.
> Fix double rate deinterlacing for some TS files

- Jellyfin.Server.Implementations/Users/UserManager.cs
**Changes**
Fixes an issue where users can be created/renamed to have a username match another user. This can cause behavior where one user "hides" another because getting the user by name always picks one over the other.
> Fix user renaming logic

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Unknown if this needs to be backported, but it's very hard to watch remote content if the check hits a null ref here.
> Fix vpp null reference

- Jellyfin.Server.Implementations/Properties/AssemblyInfo.cs
- Jellyfin.Server.Implementations/Users/UserManager.cs
- tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj
- tests/Jellyfin.Server.Implementations.Tests/Users/UserManagerTests.cs
**Changes**
Copied AssemblyInfo.cs from Emby.Server.Implementations in order to use `InternalsVisibleTo`.
Made a new function that throws if the username is invalid. This is used when creating a new user and when renaming an existing user.
I wanted to create an additional test to verify that creation and renaming actually calls the function but it proved to be very annoying to do... so I didn't.
**Issues**
Fixes #5245
> Validate the new username when renaming

- Emby.Dlna/Main/DlnaEntryPoint.cs
Fixes null exception in https://github.com/jellyfin/jellyfin/issues/5148 caused by uPnP packets being received before the DLNA subsystem is initialised.
> Fixes #5148

- MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/EpisodeNfoProviderTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MovieNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MusicAlbumNfoProviderTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MusicArtistNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/SeasonNfoProviderTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/SeriesNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Test Data/Rising.nfo
**Changes**
This PR allows parsing the end of multiepisode file from XBMC compatible nfo. This is required because the nfo contains each episode in a root block.
For example:
Stargate Atlantis - 1x01-02:
```
<episodedetails>
<title>Rising (1)</title>
<season>1</season>
<episode>1</episode>
...
</episodedetails>
<episodedetails>
<title>Rising (2)</title>
<season>1</season>
<episode>2</episode>
...
</episodedetails>
```
This resulted the file being parsed as episode 1 instead of episode 1-2.
> Get episode range end from XBMC compatible nfo

- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
This method returns true if any version of ffmpeg if located, on a first come basis.
Alternative to https://github.com/jellyfin/jellyfin/pull/4963
> Fix for 4933: Alternative ffmpeg fix

- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
Credit to @rexio8 for identifying the issue.
Move code from line 173 to line 255 to ensure the correct protocol is selected..
Bug caused by stream being accessed remotely (http) and subs being based locally.
Looks like it was fixed at some point in the past, but has crept back in.
Change does include some parameter optimisations. (removing when an object and a property of an object are both passed to internal methods)
> Fix for #5168

- MediaBrowser.Common/Net/IPHost.cs
- tests/Jellyfin.Networking.Tests/NetworkTesting/NetworkParseTests.cs
Credit @Ullmie02 
Fixed: parsing an ipv6 address returned IPAddress.None. Fixed
Fixed: A prefix of /32 was always added to the string representation regardless of IP type.
Updated tests.
> Fixed IPHost.TryParse

- tests/Jellyfin.MediaEncoding.Tests/Subtitles/SsaParserTests.cs
libse (the SSA parser we use) has these same tests now
> Remove tests that are upstreamed

- RSSDP/SsdpDeviceLocator.cs
Sometimes the callback is triggered after the device locator has been disposed. This will sometimes fail an Azure pipeline execution.
> Do nothing in timer callback when device locator is disposed

- Emby.Dlna/PlayTo/PlayToController.cs
- Jellyfin.Api/Helpers/FileStreamResponseHelpers.cs
- Jellyfin.Api/Models/StreamingDtos/StreamState.cs
Play function not working on Panasonic TV: https://github.com/jellyfin/jellyfin/issues/4697
Fix1: Stops a null argument exception (caught) being created in the first place.
Fix2: Adds ContentLength value to video HEAD response. (Code from 6.4)
> Remove Content-Length header from DLNA HEAD request

- MediaBrowser.Model/Entities/ProviderIdsExtensions.cs
- MediaBrowser.Providers/Manager/ProviderManager.cs
- tests/Jellyfin.Model.Tests/Entities/ProviderIdsExtensionsTests.cs
**Changes**
Sometimes the provider id exists but is null or empty. This usually occurs when searching with Identify. We did previously check for this, but it was lost in the refactor.
**Issues**
Fixes #5348
> return false when providerid is null or empty

- Jellyfin.Networking/Manager/NetworkManager.cs
- Jellyfin.Server/Program.cs
Deep in the Kestrel code socket dual mode is enabled if IPAddress.IPv6Any is specified as an address.
This causes an exception on non-windows platforms if ip6 **and** ip4 is enabled.
It also means that Jellyfin can not be run in pure IP6 mode.
This PR  fixes both these issues.
Tested on windows platform.
> Dual IP4 / IP6 server fails on non-windows platforms

- MediaBrowser.Providers/Manager/ProviderManager.cs
- MediaBrowser.Providers/Plugins/Tmdb/BoxSets/TmdbBoxSetImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeasonImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesImageProvider.cs
TMDb API returns all images if languages are excluded, which is needed for the All Languages toggle in Identify.
**Issues**
Fixes #5238
> Do not use language or imagelanguages when searching for images with TMDb

- Jellyfin.Api/Controllers/VideosController.cs
When merging two versions that are already merged (user error, but can happen), the first one would be picked and if it already has the other version as primary this line will cause a stack overflow as it goes into an infinite loop https://github.com/jellyfin/jellyfin/blob/cd4641dca02bae552cc7ea1942b0efbd4b791bcb/MediaBrowser.Controller/Entities/Video.cs#L174
> do not pick a linked item as primary when merging versions

- Emby.Dlna/DlnaManager.cs
- Emby.Server.Implementations/AppBase/ConfigurationHelper.cs
- Emby.Server.Implementations/LiveTv/EmbyTV/DirectRecorder.cs
- Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
- Emby.Server.Implementations/LiveTv/EmbyTV/EncodedRecorder.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunUdpStream.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs
- Jellyfin.Api/Controllers/ItemLookupController.cs
- Jellyfin.Api/Controllers/RemoteImageController.cs
- Jellyfin.Api/Helpers/TranscodingJobHelper.cs
- MediaBrowser.LocalMetadata/Savers/BaseXmlSaver.cs
- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
- MediaBrowser.Providers/Manager/ImageSaver.cs
- MediaBrowser.Providers/Plugins/AudioDb/AlbumProvider.cs
- MediaBrowser.Providers/Plugins/AudioDb/ArtistProvider.cs
- MediaBrowser.Providers/Subtitles/SubtitleManager.cs
**Changes**
Use `FileShare.None` when creating files to avoid CIFS empty files and access denied.
**Issues**
Fixes #5370
Related to
#5106
dotnet/runtime#42790
> Use FileShare.None when creating files

- deployment/Dockerfile.fedora.amd64
**Changes**
Remove Microsoft repo from the Fedora install step. This was breaking Fedora builds due to a mismatch. We can use the .NET SDK 5.0 from the Fedora 33 repos instead and this seems to work.
**Issues**
N/A
> Remove Microsoft repo from install step

- Emby.Dlna/Profiles/DefaultProfile.cs
- Jellyfin.Api/Helpers/StreamingHelpers.cs
Fix: Assigns dynamic profiles a deviceId so that properties retreived via dlna can be used in streaming calcs. #https://github.com/jellyfin/jellyfin/issues/5394
Fix: Implements the redundant code that was part of the profile detection in the stream helper.
> Various DLNA Device Profile fixes

- Emby.Naming/Video/VideoListResolver.cs
- tests/Jellyfin.Naming.Tests/Video/MultiVersionTests.cs
**Changes**
Moved the cleaning to after removing folder name from the filename. Also added a check for the remainder string starting with `[`.
Reasoning behind this change is that the filenames _must_ start with the folder name, so why not remove the folder name _before_ cleaning the string. And normally a file that starts with `[` is anime or whatever, but this does not apply here.
**Issues**
Fixes #5435
> fix multiversion eligibility check for complex folder names

- MediaBrowser.Controller/Entities/Audio/IHasAlbumArtist.cs
- MediaBrowser.Controller/Library/NameExtensions.cs
It's not uncommon for an artist to be tagged as Artist and AlbumArtist in which case this line https://github.com/jellyfin/jellyfin/blob/ee23d06154133ffc506dda3a8ef0e09d20c03c6c/MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs#L202 will refresh the artist twice. This can lead to some weird behaviour.
> Use distinct for AllArtists to avoid double refreshing

- Jellyfin.Api/Controllers/LibraryController.cs
The endpoint was called with `curl -v -d "" -H "X-MediaBrowser-Token: TOKEN" https://jellyfin.tld/library/refresh` in the past and I have mistakenly been thinking it was ASP.NET being less lenient than ServiceStack when it's actually because it was changed from POST to GET 🙃
> fix refresh endpoint

- Jellyfin.Api/Controllers/InstantMixController.cs
Some endpoints were accidentally changed when migrating, so add the old ones back for backwards compatibility.
> Add missing InstantMix endpoints

- Emby.Server.Implementations/Collections/CollectionManager.cs
If "Group movies into collections" is enabled the server returns every version of a movie instead of returning just the default one causing the web to show duplicated movies.
With my changes, the server checks if the version of the movie is already in the results and skips it if it is
This should fix this issue https://github.com/jellyfin/jellyfin/issues/3361
> Fix duplicated movies when group movies into collections is enabled

- Emby.Dlna/DlnaManager.cs
.First crashes the code and returns a `Sequence contains no matching element error.`
Fixes https://github.com/jellyfin/jellyfin/issues/5509
Am still investigating why deviceProfileId isn't being matched, but given the code it looks like it expected ??!?!?!
```
if (!string.IsNullOrWhiteSpace(deviceProfileId))
{
state.DeviceProfile = dlnaManager.GetProfile(deviceProfileId);
if (state.DeviceProfile == null)
{
var caps = deviceManager.GetCapabilities(deviceProfileId);
state.DeviceProfile = caps == null ? dlnaManager.GetProfile(request.Headers) : caps.DeviceProfile;
}
}
```
> Fix: Streaming crashing due to no deviceProfileId match.

- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Fixes https://github.com/jellyfin/jellyfin/issues/5488
I left `x-jellyfin-version` for backwards compat.
> Set openapi version to server version

- Emby.Naming/Video/VideoListResolver.cs
- tests/Jellyfin.Naming.Tests/Video/MultiVersionTests.cs
**Changes**
Looking at the history of the multi-version eligibility check and accompanying unit tests, it seems that underscore was broken/unsupported for a long time and also missing in all documentation. It seems only fair to revert this particular change as it causes some false positives and I don't see any reason to reserve three different naming schemes.
**Issues**
Fixes #5528
> revert underscore as a multiversion separator

- MediaBrowser.Providers/Plugins/Tmdb/BoxSets/TmdbBoxSetProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TmdbUtils.cs
**Changes**
Added non-word cleaning. It used to do a lot more though https://github.com/jellyfin/jellyfin/blob/907695dec7fda152d0e17c1197637bc0e17c9928/MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbSearch.cs#L26-L37, but I it doesn't really belong in tmdb at all, so I'd rather we try without it for now.
I think `ParseName` could use some more work though, but I'm afraid to change it in 10.7 since it's used elsewhere.
**Issues**
Fixes #5224
> Clean the entity name for non-words before searching

- .ci/azure-pipelines-package.yml
**Changes**
Now the Nuget build will always run regardless of the package building results.
> Remove BuildPackage dependency for PublishNuget in CI

- Jellyfin.Api/Helpers/FileStreamResponseHelpers.cs
**Changes**
Changed `HEAD /audio/<id>/stream[.format]` responses to:
* return 200 OK instead of 204 No Content
* not return "Content-Length: 0" header
**Issues**
* Fixes Samsung Soundbar (HW-Q80R) returning "Error: Resource not found (716)" to DLNA playback request (`POST /upnp/control/AVTransport1`)
**Details**
Without this fix my Samsung Soundbar (HW-Q80R) fails to play using DLNA
and returns "Error: Resource not found (716)" instead.
I had a look on tcpdump network logs between Jellyfin and the soundbar
and noticed that the device performs a HEAD request for the media before
responding to the DLNA UPNP control request from Jellyfin (or BubbleUPNP
Android App).
Jellyfin retuns 204 No Content response, which is unusual.  Common web
servers generally return 200 OK if the GET would return …
> Improve responses to HEAD /audio/<id>/stream for Samsung DLNA renderers

- Emby.Server.Implementations/ApplicationHost.cs
- MediaBrowser.Controller/Providers/MetadataResult.cs
- MediaBrowser.Providers/Manager/MetadataService.cs
- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
- MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs
- MediaBrowser.XbmcMetadata/Parsers/MovieNfoParser.cs
- MediaBrowser.XbmcMetadata/Parsers/SeasonNfoParser.cs
- MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs
- MediaBrowser.XbmcMetadata/Providers/AlbumNfoProvider.cs
- MediaBrowser.XbmcMetadata/Providers/ArtistNfoProvider.cs
- MediaBrowser.XbmcMetadata/Providers/BaseVideoNfoProvider.cs
- MediaBrowser.XbmcMetadata/Providers/EpisodeNfoProvider.cs
- MediaBrowser.XbmcMetadata/Providers/MovieNfoProvider.cs
- MediaBrowser.XbmcMetadata/Providers/MusicVideoNfoProvider.cs
- MediaBrowser.XbmcMetadata/Providers/SeasonNfoProvider.cs
- MediaBrowser.XbmcMetadata/Providers/SeriesNfoProvider.cs
- MediaBrowser.XbmcMetadata/Providers/VideoNfoProvider.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/EpisodeNfoProviderTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MovieNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MusicAlbumNfoProviderTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MusicArtistNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MusicVideoNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/SeasonNfoProviderTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/SeriesNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Test Data/Justice League.nfo
**Changes**
Add support for nfo thumb tag including tests.
- Only the first thumb tag for each artwork type is used because only one image for each artwork type is supported.
- Artwork defined in the nfo file takes precedence over local images in the media folder and provider images.
I would like to document this somewhere but don't know where the right place would be.
**Issues**
`<thumb>` part of #5262
> Add nfo thumb tag support

- Emby.Dlna/PlayTo/Device.cs
- Emby.Dlna/PlayTo/PlayToManager.cs
- Emby.Dlna/PlayTo/SsdpHttpClient.cs
- tests/Jellyfin.Networking.Tests/NetworkParseTests.cs
Badly formed XML responses from devices cause exceptions and crashing JF.
This fix wraps the http request in a try/catch handler, and returns null. 
All methods down the line using this function have had addition null checks adding.
Fixes https://github.com/jellyfin/jellyfin/issues/5560
> Implemented DLNA exception handling

- Emby.Server.Implementations/MediaEncoder/EncodingManager.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
**Changes**
We were sending an invalid input format to ffmpeg for every ISO file (`-f ISO`). This adds an exception to `GetInputFormat` to nullify the format for ISO files.
Another issue arose when trying to play DVD ISOs, as we were treating every ISO as a Blu-ray. This fixes said behavior in `GetInputArgument` by using the proper `file:` protocol for ISOs and using `bluray:` only for BDMV folders (Which is what it's for [according to the ffmpeg documentation](https://ffmpeg.org/ffmpeg-all.html#bluray))
**Issues**
Fixes #5617
> Ignore ffmpeg input format for ISO files and fix input path protocol for ISOs

- Jellyfin.Api/Controllers/LibraryController.cs
**Changes**
Enabled range processing for /File and /Download. I could also have enabled it for subtitles and images, but they should be small enough that no one will need it.
**Issues**
Don't know if one exists on GH, but users have reported it... somewhere.
> enable range processing for download endpoints

- Emby.Server.Implementations/Library/LibraryManager.cs
Fixes a null ref when `LibraryManager.IgnoreFile` get called before `LibraryManager.AddParts`
```cs
[17:46:50 ERR] Error retrieving children folder
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
at Emby.Server.Implementations.Library.LibraryManager.IgnoreFile(FileSystemMetadata file, BaseItem parent) in D:\a\1\s\Emby.Server.Implementations\Library\LibraryManager.cs:line 622
at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions) in …
```
> Fix possible null ref exception

- Jellyfin.Api/Controllers/SessionController.cs
When casting to jellyfin-mpv-shim from jellyfin-web in the browser,
jellyfin-web sends data about which version (for grouped items) and
which streams the user selected in the browser to the
"Sessions/{sessionId}/Playing" API endpoint.
The API endpoint currently doesn't forward them to the cast client
through the Play command, which results in the default streams being
played instead of the streams selected in the browser.
PlayRequest already has the properties and they are already sent to the
cast client by SendPlayCommand when present.
jellyfin-mpv-shim will already use them to select the wanted streams
when it receives the Play command.
**Changes**
All that's needed to make it work is to take the parameters and assign
them to PlayRequest.
> Fix stream selection having no effect when casting to jellyfin-mpv-shim

- MediaBrowser.Controller/Providers/DirectoryService.cs
- tests/Jellyfin.Controller.Tests/DirectoryServiceTests.cs
- tests/Jellyfin.Controller.Tests/Jellyfin.Controller.Tests.csproj
**Changes**
Made the cache dictionaries in directoryservice case sensitive. It might be an edge case of sorts as it's a bit weird to have identical paths with different casing?
This change fixes a weird issue where identical paths with different casing would cause the parallelized scanner to crash. If it didn't crash it would take the files from the first case-insensitive matching path, which is incorrect on Linux at least.
Backporting this is debatable I suppose.
**Issues**
Partially fixes #5144?
> make directoryservice cache case sensitive

- Emby.Server.Implementations/Library/PathExtensions.cs
- MediaBrowser.Common/Providers/ProviderIdParsers.cs
- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
- MediaBrowser.XbmcMetadata/Parsers/MovieNfoParser.cs
- MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs
- tests/Jellyfin.Common.Tests/Providers/ProviderIdParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MovieNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Test Data/Justice League.nfo
- tests/Jellyfin.XbmcMetadata.Tests/Test Data/Radarr.nfo
**Changes**
- Check id from `<id>` tag if it contains `tt` for imdb
- Use Helper methods for url files
**Issues**
Fixes #5347
> Nfo id parsing fixes

- MediaBrowser.Providers/Manager/ItemImageProvider.cs
Sometimes an image url returns 404 etc. In 10.6 this would've raised an exception and the url would be skipped...
> ensure only valid images are saved in ItemImageProvider

- Emby.Server.Implementations/HttpServer/Security/SessionContext.cs
- Jellyfin.Api/Controllers/UserController.cs
- Jellyfin.Api/Helpers/DynamicHlsHelper.cs
- Jellyfin.Api/Helpers/MediaInfoHelper.cs
- Jellyfin.Api/Helpers/RequestHelpers.cs
- MediaBrowser.Common/Extensions/HttpContextExtensions.cs
- tests/Jellyfin.Api.Tests/Auth/LocalAccessPolicy/LocalAccessHandlerTests.cs
- tests/Jellyfin.Networking.Tests/NetworkManagerTests.cs
- tests/Jellyfin.Networking.Tests/NetworkParseTests.cs
**Changes**
- Unnecessary change of data type which could lead to the wrong IP address being parsed (IsInNetwork has an overload for string and IPAddress)
- Add log warning if Password Reset is initiated from outside the local network
- Add tests for IsInNetwork
**Issues**
Code from #5180
> Don't convert from IPAddress to string to IPAddress

- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Matches OpenAPI version with the "public" versioning schema, instead of the assembly one.
> Return Major.Minor.Build instead of Major.Minor.Build.Revision for OpenAPI

- MediaBrowser.Model/Dlna/StreamBuilder.cs
_This is only a cosmetic effect_
MKV is treated as `mkv,webm` and video is tested with `webm` audio profiles - we always have `VideoCodecNotSupported` + `AudioCodecNotSupported`.
It still depends on profile order, so we may still have wrong transcode reasons. But we shouldn't have any problem with order `[webm, mkv]`.
**Changes**
Check appropriate profile type
**Issues**
N/A
> Check appropriate profile type

- MediaBrowser.Controller/Providers/IProviderManager.cs
- MediaBrowser.Providers/Manager/ProviderManager.cs
when `ProviderManager.SaveMetadata` gets called before
`ProviderManager.AddParts`
```
Error Message:
System.ArgumentNullException : Value cannot be null. (Parameter 'source')
Stack Trace:
at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers) in D:\a\1\s\MediaBrowser.Providers\Manager\ProviderManager.cs:line 674
at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType) in D:\a\1\s\MediaBrowser.Providers\Manager\ProviderManager.cs:line 655
at Emby.Server.Implementations.Library.LibraryManager.RunMetadataSavers(Bas …
```
> Fix possible nullref

- MediaBrowser.MediaEncoding/Probing/FFProbeHelpers.cs
- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
Currently, dates are parsed according to the local time, which results in potentially wrong data being stored in the database after normalizing to UTC - e.g. 2021-04-04 would be stored as '2021-04-03 22:00:00Z' and displayed in the UI as 03.04.2021. This can be fixed by setting the `AssumeUniversal` flag to `TryParse`.
Also, this adds support for the MKV `DATE_RELEASE` tag as a date tag - see the relevant commit for more info.
If necessary, I can split this PR into multiple.
> Probe result tweaks

- Jellyfin.Api/Controllers/SessionController.cs
- MediaBrowser.Model/Session/MessageCommand.cs
Changed SessionController.SendMessageCommand to bind information to composite object instead query string parameters.
**Changes**
Changes selected parameter binding of SendMessageCommand to a single composite object bound by [FromBody].
**Issues**
Resolves: #5628
> Fix SessionController.SendMessageCommand Body Binding

- Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunManager.cs
- tests/Jellyfin.Server.Implementations.Tests/LiveTv/HdHomerunManagerTests.cs
Faster, less allocations, more robust and with tests
> Rewrite Rewrite HdHomerunManager.ParseReturnMessage and add tests

- MediaBrowser.Controller/Playlists/Playlist.cs
Fixed issue with determining if a directory was a directory or file when it contained a `.` in the directory name.
**Changes**
Checks to see if a path is an existing directory at all as a initial check to determine if a playlist path is a file path, then if it doesn't, attempts a check using System.IO.Path.HasExtension(string path).
//Let me know if that's too much comment there, it's not initially obvious why the change was made, and it seems like the sort of thing that could be easily reverted by accident if a contributor isn't aware of the reason for the change.
**Issues**
Resolves: #2845
> Fixed issue with determining if a directory was a directory or file

- MediaBrowser.Model/Configuration/EncodingOptions.cs
**Changes**
Based on some discussion in chat, it probably only makes sense to have HEVC encoding enabled if HWA has been setup.
**Issues**
N/A
> Disable HEVC encoding by default

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
IsPlayed is a column in UserDatas and does not belong in the inner query. None of the other UserDatas columns are in the innerquery.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/2672
> move IsPlayed to outerquery

- Emby.Server.Implementations/Plugins/PluginManager.cs
- Emby.Server.Implementations/Updates/InstallationManager.cs
- MediaBrowser.Common/Plugins/IPluginManager.cs
Fixes plugin manager issues as described in #5700.
- disabled plugins are not auto upgraded.
- disabled plugins keep their status after upgrading.
> Keep plugin state after update.

- CONTRIBUTORS.md
- Emby.Server.Implementations/Sorting/AiredEpisodeOrderComparer.cs
- Emby.Server.Implementations/TV/TVSeriesManager.cs
**Changes**
I changed the logic that determines the "Up Next" section in the user dashboard to be based on the same logic, that the player uses to determine the next episode to play. This in turn enables it to correctly have a special shown as the next episode, if the corresponding option is enabled by the user, which until now always wer skipped.
**Issues**
Fixes #1479
> Include specials in the calculation for the "Next Up" episode

- Emby.Drawing/ImageProcessor.cs
- Jellyfin.Api/Controllers/ImageController.cs
- Jellyfin.Drawing.Skia/SkiaEncoder.cs
- MediaBrowser.Controller/Drawing/ImageProcessingOptions.cs
> Remove CropWhitespace function

- Jellyfin.Api/Helpers/MediaInfoHelper.cs
**Changes**
Fixes the issue with PlaybackInfo where the audo stream index is not set to the one requested. This does not interfere with playback when no audio stream is specified in PlaybackInfo.
This can be `cherry-pick`'d onto the `release-10.7.z` branch and has been tested.
**Issues**
https://github.com/jellyfin/jellyfin-desktop/issues/203
> Fix setting audio stream in PlaybackInfo for jellyfin-web.

- Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs
**Changes**
Changed unawaited async calls to sync calls
**Issues**
Fixes #5184
> Use sync Serialize when writing scheduled tasks to disk

- Jellyfin.Server/Jellyfin.Server.csproj
- debian/conf/jellyfin
- fedora/jellyfin.env
**Changes**
Default to Workstation GC mode which seems to be what was used in <=10.6. I'm not sure if .NET 5 or the Web API migration is what caused the new default of Server or not, but we've been using ASP.NET for a long time now, so it must be .NET 5.
Workstation uses less RAM than Server and is more suitable for consumer grade hardware. Servers with more RAM might benefit from using Server GC mode, which is run-time overrideable. See https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector#workstation-vs-server
Server GC mode reserves _a lot_ of virtual memory, which some devices seem to handle very poorly. Workstation GC reserves much less at the cost of a few more CPU cycles.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/5554
> Enable Workstation GC mode

- Emby.Drawing/ImageProcessor.cs
- Jellyfin.Api/Controllers/ImageController.cs
- MediaBrowser.Controller/Drawing/ImageHelper.cs
- MediaBrowser.Controller/Drawing/ImageProcessingOptions.cs
- MediaBrowser.Model/Drawing/DrawingUtils.cs
**Changes**
Adds fillHeight and fillWidth optional parameters to all(?) image endpoints.
**Issues**
Server portion for resolving jellyfin/jellyfin-web#2191
Web PR: jellyfin/jellyfin-web#2514
apiClient PR: jellyfin/jellyfin-apiclient-javascript#167
> Add «resize to fill box» alternative for image endpoints

- MediaBrowser.Providers/Manager/ImageSaver.cs
**Changes**
Introduced a basic check on path such that artwork in the item's folder won't be deleted unless "save locally" is enabled.
**Issues**
Fixes #4864
> Do not touch "old" local artwork unless saving locally

- Emby.Server.Implementations/Library/Resolvers/PlaylistResolver.cs
**Changes**
Added mediatype for playlists in a music collectionfolder. A playlist that is created inside a music collectionfolder falls back the Audio mediatype if nothing is specified.
**Issues**
Fixes #4158 with one caveat. I can't force the mediatype on old playlists, only new ones. May have to set the MediaType manually for existing playlists...
> Set mediatype to Audio for playlists in a music library

- Jellyfin.Api/Controllers/ItemsController.cs
**Changes**
CollectionType.Folders seems to be a special type that is only (?) used by the "Folder view" option. Permissions are checked for the individual libraries, so no need to check for "Folders" itself.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/2754
> Do not check permissions for Folders collectiontype

- Emby.Server.Implementations/ApplicationHost.cs
- Jellyfin.Server/Migrations/MigrationRunner.cs
- Jellyfin.Server/Program.cs
- MediaBrowser.Controller/Library/MetadataConfigurationExtensions.cs
- MediaBrowser.Controller/Library/MetadataConfigurationStore.cs
Fully initialize the configuration manager at the init stage
```
Failed Jellyfin.Server.Integration.Tests.Controllers.ActivityLogControllerTests.ActivityLog_GetEntries_Ok [2 s]
Error Message:
MediaBrowser.Common.Extensions.ResourceNotFoundException : Configuration with key metadata not found.
Stack Trace:
at Emby.Server.Implementations.AppBase.BaseConfigurationManager.<>c__DisplayClass43_0.<GetConfiguration>b__0(String k) in D:\a\1\s\Emby.Server.Implementations\AppBase\BaseConfigurationManager.cs:line 309
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at Emby.Server.Implementations.AppBase.BaseConfigurationManager.GetConfiguration(String key) in D:\a\1\s\Emby.Server.Implementations\AppBase\BaseConfigurationManager.cs:line 300
at …
```
> Fix random failing of tests

- Dockerfile
Update image tag to make it coherent with rest of Dockerfile.
- The substring `-buster-slim` isn't useful/correct. 
- .NET 6 (from my team) is based exclusively on bullseye.
- If you update just `DOTNET_VERSION` to `6.0`, `docker build` will fail. 
- If the goal is to force using `buster` throughout the Dockerfile, then making `DOTNET_VERSION` configurable isn't correct.
- Context: https://github.com/dotnet/dotnet-docker/blob/main/src/runtime-deps/6.0/bullseye-slim/amd64/Dockerfile#L1
Just saw this as a drive by look at your code. Is intended as helpful context.
> Remove coupling to distro

- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesImageProvider.cs
```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem
item, IRemoteImageProvider provider, IReadOnlyCollection`1
preferredLanguages, CancellationToken cancellationToken,
Nullable`1 type) in
/home/bond/dev/jellyfin/MediaBrowser.Providers/Manager/ProviderManager.cs:line
280
```
> Fix possible ArgumentNullException

- Jellyfin.Networking/Manager/NetworkManager.cs
- MediaBrowser.Common/Net/NetworkExtensions.cs
- tests/Jellyfin.Networking.Tests/NetworkParseTests.cs
Fixes #5761 - moved around the logic to ensure loopback addresses are added.
Workaround for #5454, by intercepting the exception, and resorting to DNS discovery for interfaces. (Bug is upstream in the dotnet core)
> Enables the ability to bind to loopback address.

- .github/dependabot.yml
- .github/workflows/automation.yml
- .github/workflows/merge-conflicts.yml
- .github/workflows/rebase.yml
* Newly opened PRs will be added to the "Next Release" project.
* If labeled as "stable backport", they will be added to the "Current release" project as well.
* If the "stable backport" is removed, it will be removed from the "Current release" project.
* New issues will be added to "Pending response" in "Issue Triage for Main Repo". As soon as a team member comments on it, the issue will be moved to "Needs triage", so we can manually move it to the low/medium/high priority boards.
Team members can type ``@jellyfin rebase`` on any PR for quickly triggering a rebase on that branch.
⚠️ Only works for members that have their org membership visible.
This PR needs the same ``GH_TOKEN`` that is configured in jellyfin-vue to work properly. It also needs to have created a "Current Release" and …
> Add workflows for rebase and automation

- Emby.Server.Implementations/Library/Resolvers/Audio/AudioResolver.cs
AudioResolver.ResolveMultipleAudio method can attempt to access the first item in a List without checking if the list is empty which throws an ArgumentOutOfRangeException and stops the 'Scan Library' process.
**Changes**
Ignores items where the List of files is empty.
> Fix ArgumentOutOfRangeException scanning AudioBooks

- Jellyfin.Server/Migrations/Routines/AddPeopleQueryIndex.cs
**Changes**
Use `IF NOT EXISTS` to prevent adding the same index multiple times. I have not been able to reproduce the bug, but the only way it can happen is if it fails to write to `migrations.xml` after running the migration.
**Issues**
Fixes #5474
> use IF NOT EXISTS in migration

- Jellyfin.Server/Migrations/Routines/MigrateDisplayPreferencesDb.cs
**Changes**
Some values were empty strings, which causes `int.Parse` to crash
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/5473#issuecomment-817184184
> Check for empty string when migrating displaypreferences

- MediaBrowser.Controller/Entities/BaseItemExtensions.cs
Otherwise a cryptic `System.Reflection.TargetException : Non-static method requires a target.` gets thrown
> DeepCopy: Throw ArgumentNullException if one of the args is null

- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeProvider.cs
When I rewrote tmdb providers I probably forgot about the external links on the episode page...
**Issues**
Fixes #5869
> Add tvrage and imdb ids for episodes

- Emby.Server.Implementations/Library/LibraryManager.cs
- MediaBrowser.Controller/Library/ILibraryManager.cs
- MediaBrowser.Providers/Manager/MetadataService.cs
**Changes**
Another attempt at saving people in an efficient way. `UpdatePeople` is called in 5 places and originally this method only inserted the people into the `People` table. When `AttachPeople` is called in the Dto method (https://github.com/jellyfin/jellyfin/blob/223b42aed3395f7d01ea513bf352cdf4fd3e7002/Emby.Server.Implementations/Dto/DtoService.cs#L188), the people would be created in the `TypedBaseItems` table by way of `LibraryManager.GetPerson(name)`, but I refactored this in 10.7 to _not_ create the person because it was super duper slow in metadata refreshes 
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/5493 (for real)
> add UpdatePeopleAsync and add people to both tables

- Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs
**Changes**
- This causes sessions to leave the SyncPlay group they are attached to when they disconnect.
- If the last SyncPlay session disconnects, the group is removed.
- This prevents the issue where if SyncPlay breaks, users need to delete their Client configuration file to make it usable again.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/4680
Fixes https://github.com/jellyfin/jellyfin-web/issues/2515
**References**
https://www.reddit.com/r/jellyfin/comments/mk3se4/jellyfin_media_player_new_experimental_desktop/gtdtksk/
https://www.reddit.com/r/linux/comments/mv3mx3/introducing_jellyfin_media_player_with_the/gvmcaot/
*This PR can be cherry-picked onto the release-10.7.z branch and has been tested.*
> Leave SyncPlay group on session disconnect.

- Emby.Server.Implementations/IO/ManagedFileSystem.cs
- tests/Jellyfin.Server.Implementations.Tests/IO/ManagedFileSystemTests.cs
```
BenchmarkDotNet=v0.12.1, OS=fedora 32
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.103
[Host]     : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT
DefaultJob : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT
```
|                      Method |          Data |        Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------------------- |-------------- |------------:|---------:|---------:|-------:|------:|------:|----------:|
|       GetValidFilenameBench |    AC/DCKD/A |    48.94 ns | 0.803 ns | 0.751 ns | 0.0255 |     - |     - |      80 B |
|    GetValidFilenameOldBench |    AC/DCKD/A |    85.70 ns | 1.572 ns | 1.393 ns | 0.0587 |     - |     - |     184 B …
> ManagedFileSystem: Rewrite GetValidFilename and more improvements

- Emby.Server.Implementations/IO/ManagedFileSystem.cs
- Emby.Server.Implementations/Library/LibraryManager.cs
- Emby.Server.Implementations/Library/ResolverHelper.cs
- MediaBrowser.Controller/Library/ItemResolveArgs.cs
- MediaBrowser.Model/IO/FileSystemMetadata.cs
DirectoryName was only set for files, just removed it to prevent the same mistake in the future
> Fix scanning

- Jellyfin.Api/Controllers/VideosController.cs
The argument isn't passed to the method but causes the API generator to include an unnecessary parameter.
Also fixes some typos in the documentation comments.
> Remove extraneous 'stream' parameter

- tests/Jellyfin.Server.Integration.Tests/Jellyfin.Server.Integration.Tests.csproj
- tests/Jellyfin.Server.Integration.Tests/xunit.runner.json
* Easier to debug failing tests when the logs aren't scrambled
* Static properties could cause issues
> Don't run integration tests in parallel

- Emby.Dlna/Didl/DidlBuilder.cs
- Jellyfin.Api/Controllers/UniversalAudioController.cs
- MediaBrowser.Model/Dlna/ContainerProfile.cs
- MediaBrowser.Model/Dlna/DeviceProfile.cs
- MediaBrowser.Model/Dlna/DirectPlayProfile.cs
- MediaBrowser.Model/Dlna/TranscodingProfile.cs
Refactored some classes in the device profile model to handle nullability and added `DefaultValue` and `Required` attributes for the generated API.
Some properties (like `MinSegments` in `TranscodingProfile`) couldn't be made nullable as that would break parsing device profile XMLs.
I also moved some initializers directly to the variables, if constructor assignment is preferred I can also move them back.
Also fixed a bug in the `ContainsContainer` method, passing a null/empty `profileContainers` would have caused the method to always return true, which seems to be wrong. Now it properly returns the correct value according to `isNegativeList`.
> Nullability handling for device profile classes

- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
**Changes**
Add support for the `<ratings>` tag in .nfo files.
Because of compatibility reasons I didn't remove support for the `<rating>` tag.
Ratings with names containing `tomato` will be treated as `CriticRatings`, every other rating will get imported as `CommunityRating`
**Issues**
Fixes #4887
> Add .nfo ratings tag

- tests/Jellyfin.Networking.Tests/NetworkParseTests.cs
Test shouldn't now fail in the case of dns resolution failure.
> Fix network test on dns failure

- .github/workflows/label-commenter-config.yml
- .github/workflows/label-commenter.yml
**Changes**
Add label commenter workflow
Right now the main purpose is to handle instructions for stable backports. Can be expanded in the future.
The main thrust of this is to ensure the process for handling stable backports is known to the PR author, and to allow them the opportunity to test the `cherry-pick` before handling by the release manager (i.e. project leader).
This process will help ensure, via a recorded message, that cherry-picks of stable backports have known good fixes before the actual process of cherry-picking begins.
**Issues**
N/A
> Add label commenter workflow

- MediaBrowser.Model/Dlna/ContainerProfile.cs
70771fdcd60ec5d8a9f13713662778c7e57d0633 broke direct play by treating empty container/codec strings as unsupported in `ContainerProfile.ContainsContainer()` (which is also used for video and audio codec checks). Instead, they should be treated as supported, for both the positive and negative list option.
**Changes**
- Reverts one of the changes in 70771fdcd60ec5d8a9f13713662778c7e57d0633.
**Issues**
- None filed.
> Fix direct play for DirectPlayProfiles without any codecs set

- Emby.Server.Implementations/LiveTv/EmbyTV/EncodedRecorder.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs
- Emby.Server.Implementations/Localization/LocalizationManager.cs
- Jellyfin.Api/Helpers/HlsHelpers.cs
- MediaBrowser.Common/Extensions/StreamExtensions.cs
- MediaBrowser.Providers/Studios/StudiosImageProvider.cs
> Use new ReadAllLines extensions

- MediaBrowser.Providers/Manager/ProviderManager.cs
**Changes**
When using tvheadend, no channel icons are provided in EPG because of a missing content type in the response header. This results in a lot of internal errors and NullPointerExceptions (see screenshot below). There was already a workaround implemented, but sadly the is-null check was not implemented correctly (maybe the response of tvheadend has changed since the implementation of the workaround?)
**Issues**
https://github.com/jellyfin/jellyfin-plugin-tvheadend/issues/15
> fixed no channel icons when using tvheadend

- .github/workflows/automation.yml
**Changes**
Disabled the automation CI on issues. It's been annoying me for weeks now. Everytime an issue is made or commented on the author will receive a notification because this CI is failing....
**Issues**
> Disable automation CI on issues

- Emby.Server.Implementations/Library/MediaSourceManager.cs
Clients cannot currently handle it properly.
NOTE: This is only a revert for 10.7. The change is still live in 10.8 and clients will need to be fixed.
> Revert remuxing permission changes from #5859

- debian/postinst
In my setup I configured a different user. But updates keep "stealing" file permissions for my `$PROGRAMDATA $CONFIGDATA $LOGDATA $CACHEDATA` directories.
> Respect configured JELLYFIN_USER in Debian's postinst

- .github/workflows/automation.yml
- .github/workflows/merge-conflicts.yml
- .github/workflows/rebase.yml
``GH_TOKEN`` seems to be used internally by GitHub and it's making some actions we're using in some repos fail ([Source](https://github.com/alex-page/github-project-automation-plus/issues/39))
*(PRs made from users of the org are always successful, but PRs that aren't don't work, like Dependabot PRs. This can be checked by looking at the history of server repos and Jellyfin Vue)*
The org-wide secret should be renamed to something else to avoid confusion and further replacements or messes in GH's side. This PR replaces ``GH_TOKEN`` with ``JF_BOT_TOKEN``, which should be pretty generic.
> Replace GH_TOKEN with JF_BOT_TOKEN

- MediaBrowser.Model/Entities/MediaStream.cs
**Changes**
Some Dolby Vision files use a codec derived from AV1, AVC or HEVC, which is registered by the MP4RA as a different code (See https://mp4ra.org/#/codecs).
This adds a new branch in the video range detection, after the transfer function, to properly mark all these codecs as being HDR.  
**Issues**
> Properly detect Dolby Vision files derived from AV1, AVC and HEVC

- Emby.Server.Implementations/Session/SessionManager.cs
As reported by @nielsvanvelzen 
This fixes an issue that occurs if a client sends an authorization request without a DeviceId set- all tokens are removed. The proper fix would be to set the `[Required]` attribute but I don't want to potentially break existing clients.
```
[2021-05-10 19:55:07.083 +02:00] [INF] [21] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "Demo" has succeeded.
[2021-05-10 19:55:07.084 +02:00] [INF] [21] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "Demo": 3/0
[2021-05-10 19:55:07.086 +02:00] [INF] [21] Emby.Server.Implementations.Session.SessionManager: Logging out access token "[...]"
[2021-05-10 19:55:07.092 +02:00] [INF] [21] Emby.Server.Implementations.Session.SessionManager: Logging out access …
```
> Don't logout if deviceId is null

- Emby.Server.Implementations/Library/UserDataManager.cs
**Changes**
This PR moves the check for if it's a type `Book` when saving the progress to the database. Currently due to the maths the book progress will be below the default configs `MinResumePct` so this will just ignore books and save the progress without resetting it to 0.
**Issues**
Didn't see an issue for this. But it occurs when you have books on your Jellyfin, read through a few pages and then back out the PDF viewer the progress isn't saved and upon refreshing the page the progress is still 0.
> Fixes for Book Progress

- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Emby.Server.Implementations/Localization/Core/en-US.json
- Emby.Server.Implementations/Localization/Core/es.json
- Emby.Server.Implementations/ScheduledTasks/Tasks/OptimizeDatabaseTask.cs
- Jellyfin.Server/Program.cs
Runs ``PRAGMA optimize`` after disposing Jellyfin's application host. According to SQLite docs, this should be run at the end of the connection, when it's most suitable to run the query planner optimizations.
Source https://www.sqlite.org/pragma.html#pragma_optimize and https://sqlite.org/lang_analyze.html
EFCore arbitrarily creates or reuses connections for database contexts (based in EF6, not EFCore documentation I could find, https://docs.microsoft.com/en-us/ef/ef6/fundamentals/connection-management) but I assume that with SQLite provider (given all the concurrency issues it has) the same connection is reused no matter what, so we're taking full advantage of the query planner. **More insights on this are appreciated**.
> Run SQLite query planner optimization at shutdown/restart

- CONTRIBUTORS.md
- MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
**Changes**
Reordered the requested audio checks in encoding job info. Some devices have device specific channel limits for certain audio codecs which they request through the `{codecName}-audiochannels` query parameter. For example chromecasts can only handle up to 2 channels when using AAC audio. These request options should override the normal channel limits. 
**Issues**
Fixes #5795
> Reorder requested audio channels checks

- Emby.Dlna/PlayTo/Device.cs
- Emby.Dlna/PlayTo/PlayToController.cs
**[DLNA] [NextTrack] [Gapless] Fix 5644 and 5294**
Fix 5644 : [DLNA] [Music] Next track command from any DLNA device does not do anything
Fix 5294 : gaps between tracks ... 
**Changes**
Implement the new DLNA message SetNextAVTransport() that permits to the renderer to prefetch the next track to play in the list.
It will have an effect if the renderer implement that feature :
- On my Sonos, it works perfectly.
- On my Marantz, I have to select 'replay once' option for it to work => strange.
- On JRiver Player, it works perfectly.
- On BubbleUPnP Android Player, it does not work at all : Possibly SetNextAVTransport() feature is not supported.
The other positive effect is that it removes the gap between tracks.
Feedbacks on other renderers are welcome !
**Issues**
Fixes #5644
Fixes #5294
> [DLNA] [NextTrack] [Gapless] Fix 5644 and 5294

- Emby.Server.Implementations/TV/TVSeriesManager.cs
- Jellyfin.Api/Controllers/TvShowsController.cs
- MediaBrowser.Model/Querying/NextUpQuery.cs
**Changes**
Attempt number 2 at adding a way to omit shows that havent been watched in x days from the NextUp section. The original pull request was here https://github.com/jellyfin/jellyfin/pull/5814 but I threw out that work and deleted the branch and that closed the request. Im not sure what the protocol is when something like that needs to be done. My apologies if I did it wrong. I am not super confident this was the correct way to implement this based on what cvium commented on the other one but I was having a lot of trouble understanding exactly what should be done. This has some shortfalls including the client needing to pass a date as a string to get it to work which seems a little flaky but Id love some feedback..
**Issues**
#5814
> Add NextUpCutoffDate to NextUpQuery

- MediaBrowser.Providers/Manager/ProviderUtils.cs
**Changes**
Currently Jellyfin prefers community rating received from OMDB metadata provider over all other providers, regardless of the priorities set by the user. Here I remove this unconditional priority, the choice of rating will follow the configured order of the providers, as for the rest of the metadata.
**Issues**
None found
> Don't prefer OMDB rating over all other providers

- .github/label-commenter-config.yml
- .github/workflows/automation.yml
- .github/workflows/check-backport.yml
- .github/workflows/label-commenter.yml
- .github/workflows/rebase.yml
* Don't trigger command-based workflows when the comments are deleted.
* Use ``pull_request_target`` event instead of ``pull_request`` to trigger workflows from forks as explained [here](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/)
> Pull request target

- Emby.Server.Implementations/EntryPoints/ExternalPortForwarding.cs
Remove link between DLNA and upnp.
UPnP does the port forwarding on the router by using SSDP broadcasts. DLNA does similar.
A link was placed between these to subsystems to speed up network device identification. This however, caused a loop whereby DLNA would pick up a device, and pass it to UPNP which would send out a notication, which DLNA would pick up and pass back to UPNP which would send out a notification. (Rinse and repeat) As each notification consists of 2-3 broadcasts, so the result is an exponential network flooding.
> Fix network flooding issue

- Jellyfin.Api/Controllers/DynamicHlsController.cs
- Jellyfin.Api/Controllers/VideoHlsController.cs
- Jellyfin.Api/Controllers/VideosController.cs
- Jellyfin.Api/Helpers/AudioHelper.cs
- Jellyfin.Api/Helpers/DynamicHlsHelper.cs
- Jellyfin.Api/Helpers/TranscodingJobHelper.cs
- Jellyfin.Api/Models/PlaybackDtos/TranscodingJobDto.cs
Fixes an issue reported [here](https://github.com/jellyfin/jellyfin/pull/6013#issuecomment-847272144).
Fixes https://github.com/jellyfin/jellyfin/issues/6141
> Don't dispose managed CancellationTokenSource

- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
- MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
`ffmpeg` is able to play some simple (BluRay) ISO disc images via the `file:` protocol. Other, more complex discs, with multiple playlists, may cause `bluray.iso: Invalid data found when processing input`. Using the `bluray:` protocol and `ffmpeg` compiled with `libbluray`, the disc will properly play the main playlist.
To ensure that there's no regression with DVD playback. The `bluray:` protocol will be used only for `VideoType.BluRay` or `IsoType.BluRay`. To have the ISO file tagged as `IsoType.BluRay`, the file has to be named as e.g.: `NAME.bluray.iso`
**Changes**
* Use `bluray:` protocol for ISO files tagged as BluRay disc.
**Issues**
Fixes the issue described in https://github.com/jellyfin/jellyfin/issues/5617#issuecomment-856557009
> Fix playback of complex BluRay ISOs

- MediaBrowser.Providers/Manager/MetadataService.cs
This one has already caused several issues with season metadata providers over last few years (!). TLDR: When using "Identify" Jellyfin would set series name and providers into `SeasonInfo` when calling GetMetadata on it.
**Changes**
```c#
if (refreshOptions.SearchResult != null && !(itemOfType is Season))
{
ApplySearchResult(id, refreshOptions.SearchResult);
}
```
`refreshOptions.SearchResult` contains series info even when refreshing metadata for seasons. I've just added season type check since I did not have any better ideas and we can't use "Identify" for seasons anyways.
**Issues**
#4948 
#4134 
#1843
P.S. I hate myself for spending so much time debugging this.
EDIT: I've noticed that when reidentifying a series, season and episode metadata is not reset. Shouldn't we do it? I mean if …
> Do not apply search results on seasons

- Jellyfin.Api/Controllers/SubtitleController.cs
**Changes**
Introduced in #5624 this PR fixes an issue with a broken route parameter the Kotlin SDK was complaining about.
**Issues**
> Fix routeMediaSourceId route parameter in SubtitleController GetSubtitle

- Jellyfin.Api/Controllers/ItemsController.cs
- Jellyfin.Api/Controllers/TrailersController.cs
**Changes**
The user is expected to be not-null meaning the userId parameter is required. I'm quite sure a lot of other endpoints require the userId too as they often fallback to `Guid.Empty` which might throw exceptions from somewhere deeper in the code (although not tested)
**Issues**
> Require userId in getItems and getTrailers endpoints

- tests/Jellyfin.Server.Integration.Tests/Controllers/BaseJellyfinTestController.cs
- tests/Jellyfin.Server.Integration.Tests/Controllers/EncoderController.cs
Fixes https://github.com/jellyfin/jellyfin/issues/6179
I tried using `Swashbuckle.Aspnetcore.Cli` but ran into DI issues, so without adding a new webhost this tool can't currently be used.
> Ignore Test Controllers

- .github/workflows/automation.yml
these workflows always fail in forks due to missing tokens etc. so this PR adds a condition so they only run here
* add if check to automation workflow steps to prevent running in forks
* n/a?
> disable project automation workflows in forks

- debian/rules
Found fix here: https://github.com/dotnet/sdk/issues/2526#issuecomment-434718073
Fixes: #5234
> debian: Add maxcpucount option to override_dh_auto_build. Fix #5234

- Jellyfin.Api/Controllers/VideosController.cs
**Changes**
Fixes a regression where the new VideoController does not accept MaxWidth and MaxHeight parameters in 10.7.x.
**Issues**
None that I know of :eyes:
> Restore max width and height params

- Jellyfin.Api/Controllers/MediaInfoController.cs
100MB should be enough for a proper test
ref: https://github.com/jellyfin/jellyfin-androidtv/pull/1010
> BitrateTest: Use ASP validation, increase maximum size.

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
Spelling fix for artist K/DA. Checked the musicbrainz database to make sure "KD/A" is not a valid artist too.
> Fix spelling of artist K/DA in splitting whitelist

- Jellyfin.Api/Controllers/InstantMixController.cs
This endpoint didn't exist in 10.6, and causes conflicts with the already existing endpoint `/MusicGenres/{name}/InstantMix`
This endpoint's functionality already exists as `MusicGenres/InstantMix?id=$id`
> Remove /MusicGenres/{id}/InstantMix endpoint

- Jellyfin.Api/Controllers/MediaInfoController.cs
MediaInfoController.GetPostedPlaybackInfo method attempts to access the first item of the mediaInfo Array without checking if MediaInfoHelper.GetPlaybackInfo returned an ErrorCode
**Changes**
Skip Code that accesses mediaInfo MediaSources Array when an ErrorCode is returned
> Fix ArgumentOutOfRangeException when getting PostedPlaybackInfo

- Emby.Server.Implementations/Collections/CollectionManager.cs
- Emby.Server.Implementations/Playlists/PlaylistManager.cs
- Jellyfin.Api/Controllers/DynamicHlsController.cs
- Jellyfin.Api/Controllers/VideoHlsController.cs
- MediaBrowser.Controller/Entities/Folder.cs
- MediaBrowser.Controller/Entities/UserViewBuilder.cs
- MediaBrowser.Controller/LiveTv/LiveTvChannel.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.Controller/Providers/ItemLookupInfo.cs
- MediaBrowser.Providers/TV/SeriesMetadataService.cs
Fixes:
[SA1629] Documentation text should end with a period
[CA1801] Parameter is never used. Remove the parameter or use it in the method body.
Remaining:
CA1711
CA2227
CA1002
CA1819
SA1201
SA1622
CA1051
SA1401
SA1306
CA1008
CA1721
SA1214
CA2211
SA1203
CA1044
SA1615
SA1611
SA1618
SA1627
CA1707
SA1614
CA1508
SA1617
CA1826
CA1835
CA1033
CA1724
CA1711
SA1629
> Reduce warnings in MediaBrowser.Controller

- .ci/azure-pipelines-abi.yml
- .ci/azure-pipelines-main.yml
- .ci/azure-pipelines-test.yml
- .ci/azure-pipelines.yml
The .NET SDK that Jellyfin is uses is still failing to download on the Microsoft CDN. I don't know when that will be resolved. Seems like a good opportunity to jump to a later product version.
.NET SDK 5.0.302 is the July 2021 release. https://dotnet.microsoft.com/download/dotnet/5.0
Note: Sorry for the force-push. I had some content in my branch from fixing Jellfyfin warnings and had to rebase to remove it.
Interesting. This release archive is also failing to download. I reported that.
> Update to .NET SDK 5.0.302

- MediaBrowser.Controller/Channels/Channel.cs
- MediaBrowser.Controller/Channels/ChannelItemInfo.cs
- MediaBrowser.Controller/Channels/ChannelItemResult.cs
- MediaBrowser.Controller/Channels/IHasFolderAttributes.cs
- MediaBrowser.Controller/Channels/InternalChannelFeatures.cs
Fixed the warnings for this directory.
Supports https://github.com/jellyfin/jellyfin/issues/2149
> Fix warning in MediaBrowser.Controllers/Channels

- README.md
Adds a horizontal line after project description and the rest of the readme, and another at the end before including DO and JB sponsorship links with images.
> Add sponsor links

- Jellyfin.Server/Middleware/BaseUrlRedirectionMiddleware.cs
Fixes server not redirecting when the path is exactly `/basePath` or `/basePath/`
> Fix redirect logic if request path is exactly the base url

- deployment/Dockerfile.centos.amd64
- deployment/Dockerfile.debian.amd64
- deployment/Dockerfile.debian.arm64
- deployment/Dockerfile.debian.armhf
- deployment/Dockerfile.fedora.amd64
- deployment/Dockerfile.linux.amd64
- deployment/Dockerfile.linux.amd64-musl
- deployment/Dockerfile.linux.arm64
- deployment/Dockerfile.linux.armhf
- deployment/Dockerfile.macos
- deployment/Dockerfile.portable
- deployment/Dockerfile.ubuntu.amd64
- deployment/Dockerfile.ubuntu.arm64
- deployment/Dockerfile.ubuntu.armhf
- deployment/Dockerfile.windows.amd64
To lessen the burden of the review for my ci PR i extracted my changes for the OS packaging Images.
This PR quiets down the package manager installs, since their log can be mostly ignored for the package builds.
Additionally, I noticed that we where already using debian 10 as the base but where manually installing dotnet, so I exchanged the base images where that was the case and dropped the explicit download of the dotnet sdk.
* quiet down the OS packaging docker images (mostly setting package managers to be quiet)
* changes to use the dotnet/sdk image where possible (it is debian 10 just like the one it replaces)
* slightly changes the indent in the OS packaging docker files
* extracted from #6364
> ci: change OS packaging images to be quiet

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
I've been spending a lot of time with these Dockerfiles for performance testing. I changed the order of operations to better align the work being done with the Docker build caching mechanism. There are other changes that could still be made, but this is one of the biggest ones. For people doing development and using Docker as a test mechanism, this change should help a lot.
In short, I moved all the operations that are not affected by `.csproj` or `.cs` code changes ahead of the `COPY . .` line. Upon rebuild, docker can jump directly to that line even if .NET related files have been changed. Everything after the `COPY . .` line will need to be rebuilt (in general).
The other key change to make (in a later PR) is to make `dotnet restore` a separate action.
> Optimize Dockerfiles

- deployment/build.portable
**Changes**
This disables `UseAppHost` in portable deployments, which builds an unnecessary `x86_64-linux` binary, which does not work without the .NET Core runtime.
[Per Microsoft](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-framework-dependent):
> You can create an executable for a specific platform by passing the -r <RID> --self-contained false parameters to the dotnet publish command. When the -r parameter is omitted, an executable is created for your current platform. Any NuGet packages that have platform-specific dependencies for the targeted platform are copied to the publish folder. If you don't need a platfrom-specific executable, you can specify <UseAppHost>False</UseAppHost> in the project file.
> Disable UseAppHost in portable deployment

- README.md
LGTM.com is github's static analysis platform. Having a badge pointing to the issues it found in jellyfin's codebase might help newcomers to fix low hanging-fruits to get them started into contributing.
> Add a LGTM.com badge

- Jellyfin.Api/Controllers/LiveTvController.cs
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/6415
I have no means to test this, but I'm guessing the MemoryStream gets disposed after the controller method returns. `ProgressiveFileStream` is better suited for this kind of use anyway.
> Use ProgressiveFileStream for LiveRecordings endpoint

- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/MovieNfoParserTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Test Data/Fanart.nfo
The children of the fanart tag are essentially the same as the standard thumb tags, without the aspect
**Changes**
- Move thumb tag parsing to separate method
- Modify this method to allow parsing of fanart tag children
- Add test for 
**Issues**
Resolves #5262
> Add support for NFO fanart tag

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
Fixes https://github.com/jellyfin/jellyfin/issues/6433
I don't know what else needs to be updated for this, but build & run works.
> Update Dockerfile to use debian:bullseye-slim

- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Emby.Server.Implementations/Library/Resolvers/BaseVideoResolver.cs
The ISO image will be opened and checked for BDMV or VIDEO_TS folders.
Can be overridden using `NAME.dvd.iso` / `NAME.bluray.iso`
**Changes**
* Use https://github.com/DiscUtils/DiscUtils (only the DiscUtils.Udf package) to open ISO files and check for disc-specific folder/files inside.
**Issues**
* N/A
> Better detection of the ISO DVD/BD types

- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
- MediaBrowser.Providers/MediaInfo/VideoImageProvider.cs
**Changes**
The `map` parameter in the arguments passed to FFmpeg in MediaEncoder.ExtractImageInternal currently requires the `imageStreamIndex` to be the index of **video** streams within that file. For video files, we do extra work to figure out the correct index of the passed-in stream, but for audio files, we just use the absolute index of the stream (minus one, for some reason).
Instead of doing that, this change uses no stream specifier in the `map` parameter, and passes the absolute index for both audio and video files.
See here for more details about the `map` parameter syntax:
https://trac.ffmpeg.org/wiki/Map
The bug below goes into more detail.
**Issues**
Fixes #6424
> Fix explicit stream selection in MediaEncoder.ExtractImageInternal

- Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs
**Changes**
Sets the ExtInf display name to have a higher precedence than the `tvg-name` attribute for channel names.
Usually `namInExtInf` is a more descriptive and human readable name if both it and `tvg-name` are available. `tvg-name` is more likely to be an internal identifier such as just the channel number with a prefix in my provider's case.
> Update M3U Channel Name Precedence

- Emby.Server.Implementations/ScheduledTasks/Tasks/CleanActivityLogTask.cs
**Changes**
The error message states that "Activity Log Retention days must be at least 0", but it fails with a value of zero, despite the message. This PR allows a value of 0.
A value of 0 is useful because it allows clearing the entire activity log through the "Clean Activity Log" task.
**Issues**
This is somewhat related to https://features.jellyfin.org/posts/1161/disable-or-anonymize-activity-logs
> Allow zero activity log retention days

- CONTRIBUTORS.md
- Jellyfin.Api/Controllers/AudioController.cs
- Jellyfin.Api/Controllers/DynamicHlsController.cs
- Jellyfin.Api/Controllers/VideoHlsController.cs
- Jellyfin.Api/Controllers/VideosController.cs
- Jellyfin.Api/Helpers/StreamingHelpers.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
Currently, `vpx` is being sent by clients to refer to the VP8/VP9 codecs ambiguously when indicating transcoding jobs. This change disambiguates between them in the server while providing backwards compatibility with codecs set as `vpx`, defaulting to VP8 as the codec. Additionally, as a part of this change, proper encoding support for VP9 is implemented leveraging `libvpx-vp9`.
**Issues**
Progress on #6455
> Disambiguate vpx to vp8 or vp9

- Jellyfin.Drawing.Skia/StripCollageBuilder.cs
- MediaBrowser.Controller/Entities/BaseItem.cs
**Changes**
Use the artist backdrop for music library images, instead of the primary image of the album.
Before
After
Rider also complained about paintColor and textPaint not being properly disposed, so I added that too.
**Issues**
> Use artist backdrop for generated library image

- Dockerfile
**Changes**
Updating the Intel Compute Resources used for Intel VAAPI dependencies. At the time of posting, the latest version was [21.35.20826](https://github.com/intel/compute-runtime/releases/tag/21.35.20826)
**Side Note** 
With these changes I can update the docker container to run with VAAPI on my Intel i3 10100 like so: 
```
// Free Drivers
apt -y update && apt -y install intel-media-va-driver vainfo
// To use Non-Free Drivers
echo 'deb http://ftp.au.debian.org/debian bullseye non-free' >> /etc/apt/sources.list \
&& apt -y update && apt -y install intel-media-va-driver-non-free vainfo
```
Previously I would have issues running `vainfo` with `intel-gmmlib` being too out of date for the latest intel-media-va-driver API
> Update Intel Compute Runtime Resources

- debian/bin/restart.sh
- debian/conf/jellyfin-sudoers
- debian/control
- fedora/jellyfin.spec
- fedora/jellyfin.sudoers
- fedora/restart.sh
**Changes**
Fix `restart.sh` to be more robust. In particular:
* Make sure `sudo` is installed (there is also code in there to handle `sudo` not being installed, for obscure running-as-root configurations - I wrote it before I realized I was being dumb and _wasn't_ actually running as root, but it seemed like since it was already written it might as well stay in the PR)
* Fix init system detection to look at what's actually running, not what's installed
* Misc cleanups
* Remove the `| at now` hack for systemd and fix some race conditions
I've split up the changes into individual commits, all of which have an extended description, so I won't repeat what they already say here.
I _did_ test these changes in my production Debian system. I then copied the changes to the Fedora configs, but I …
> Improve restart.sh

- Jellyfin.Api/Controllers/VideoHlsController.cs
**Changes**
Save CTS.Token to a local variable so that we can continue checking if cancellation was requested or not. CTS is poorly designed in that it throws if it was disposed, but you can never really check if it was disposed.
**Issues**
<details>
<summary>Stacktrace</summary>
```
Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/7e693bfc-251e-018c-f99e-82bb696d72ee/live.m3u8.
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
at System.Threading.CancellationTokenSource.ThrowIfDisposed()
at System.Threading.CancellationTokenSource.get_Token()
at Jellyfin.Api.Controllers.VideoHlsController.GetLiveHlsStream(Guid itemId, String container, …
```
> Fix disposed exception when ffmpeg exits early in GetLiveHlsStream

- MediaBrowser.Model/Extensions/EnumerableExtensions.cs
- MediaBrowser.Providers/Manager/ItemImageProvider.cs
- MediaBrowser.Providers/Manager/ProviderManager.cs
- MediaBrowser.Providers/Plugins/Tmdb/BoxSets/TmdbBoxSetImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/People/TmdbPersonImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeasonImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesImageProvider.cs
**Changes**
This change fixes a bug where images (usually of type `Primary`) seem to "not load" after the user custom identifies and matches the metadata with a particular source. This is due to the fact that search results shown on the UI will show primary covers from another language if those are the only covers available (#6467 shows that it is probably common in anime). However, in the previous internal logic, the image filtering does not allow for images from all languages, leading to a confusing mismatch between UI/UX and internal metadata tagging logic.
The fix enables images from all languages to be included during internal image fetching but adds logic to order results by the preferred languages so that the preferred language settings are still honored. If there are images …
> Fix images "not loading" after manual identification

- MediaBrowser.Providers/MediaBrowser.Providers.csproj
- MediaBrowser.Providers/Plugins/Tmdb/Configuration/PluginConfiguration.cs
- MediaBrowser.Providers/Plugins/Tmdb/Configuration/config.html
- MediaBrowser.Providers/Plugins/Tmdb/Plugin.cs
- MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs
**Changes**
Some TV shows and movies are labeled as 'adult' at TheMovieDb. The TMDbLib uses the 'includeAdult' parameter to show this content in search results. This PR adds a configuration option to support this feature.
> Add 'includeAdult' option for TheMovieDb

- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
**Changes**
- Changed the security scheme in the OpenAPI document to use `Authorization` instead of `X-Emby-Authorization` as the default authorization header.
Multiple clients have already moved to this new header and more are coming. Using HTTP-standards instead of magic is the recommended way of connecting to your Jellyfin server.
**Issues**
> Use standard Authorization header in OpenAPI specification

- Jellyfin.Server/Infrastructure/SymlinkFollowingPhysicalFileResultExecutor.cs
- Jellyfin.Server/Startup.cs
**Changes**
Created a subclass of `PhysicalFileResultExecutor` and replaced it in the DI container. It unfortunately reads the file attributes 1-2 times more than its superclass, but `FileInfo` is called multiple times even outside `PhysicalFileResultExecutor`. Therefore I have copied parts of static extensions methods eg. https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http/src/SendFileFallback.cs to get the desired result.
The new executor is only used for symlinks.
Supersedes #5775 and #5824. And a huge thanks for the research done by both PR authors.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/5521
> Read file length for symlinks,

- Emby.Server.Implementations/Sorting/AiredEpisodeOrderComparer.cs
- tests/Jellyfin.Server.Implementations.Tests/Sorting/AiredEpisodeOrderComparerTests.cs
In cases where two episodes have the same episode and season, comparing the PremiereDate to further sort them.
**Issues**
Fixes #6269
> Comparing PremiereDate when episode comparison would otherwise be equal.

- Emby.Dlna/PlayTo/SsdpHttpClient.cs
Before:
```
[21:37:55] [ERR] [19] Emby.Dlna.Main.DlnaEntryPoint: Error updating device info for XXX
System.Xml.XmlException: Root element is missing.
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
at System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(Boolean needMoreChars)
at System.Xml.Linq.XDocument.LoadAsyncInternal(XmlReader reader, LoadOptions options, CancellationToken cancellationToken)
at System.Xml.Linq.XDocument.LoadAsync(Stream stream, LoadOptions options, CancellationToken cancellationToken)
at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken) in /home/bond/dev/jellyfin/Emby.Dlna/PlayTo/SsdpHttpClient.cs:line 50
at …
```
> SsdpHttpClient: Ensure successful status code before reading response

- Jellyfin.Server/Migrations/Routines/MigrateUserDb.cs
```
[19:31:31] [FTL] [1] Main: Error while starting server.
System.InvalidOperationException: Unable to resolve service for type 'Emby.Server.Implementations.Serialization.MyXmlSerializer' while attempting to activate 'Jellyfin.Server.Migrations.Routines.MigrateUserDb'.
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
at Jellyfin.Server.Migrations.MigrationRunner.<>c__DisplayClass1_0.<Run>b__0(Type m) in /home/loma/dev/jellyfin/Jellyfin.Server/Migrations/MigrationRunner.cs:line 41
at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
at …
```
> Fix user DB migration

- Emby.Server.Implementations/IO/ManagedFileSystem.cs
- Jellyfin.Server/Infrastructure/SymlinkFollowingPhysicalFileResultExecutor.cs
`RandomAccess.GetLength` is used internally in `FileStream.Length`
Using it directly reduces the number of allocated objects
> Use RandomAccess instead of a FileStream where it makes sense

- Emby.Dlna/Didl/DidlBuilder.cs
- Emby.Dlna/Eventing/DlnaEventManager.cs
- Emby.Dlna/PlayTo/Device.cs
- Emby.Dlna/PlayTo/PlayToController.cs
- Emby.Dlna/PlayTo/SsdpHttpClient.cs
- Emby.Dlna/Server/DescriptionXmlBuilder.cs
- Emby.Server.Implementations/MediaEncoder/EncodingManager.cs
- Jellyfin.Api/Controllers/ImageController.cs
- Jellyfin.Api/Controllers/SubtitleController.cs
- MediaBrowser.Controller/Entities/Year.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.Controller/MediaEncoding/JobLogger.cs
- MediaBrowser.LocalMetadata/Images/LocalImageProvider.cs
- MediaBrowser.LocalMetadata/Parsers/BaseItemXmlParser.cs
- MediaBrowser.LocalMetadata/Savers/BaseXmlSaver.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
- MediaBrowser.Model/Globalization/ILocalizationManager.cs
- MediaBrowser.Providers/Manager/ImageSaver.cs
- MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs
- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
- MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs
- MediaBrowser.XbmcMetadata/Savers/EpisodeNfoSaver.cs
The only area that I know differs between Invariant culture an en-US is default Date formatting, and currency sign.
Regex used: `CultureInfo(?!\.InvariantCulture)`
Remaining CultureInfos: 
https://github.com/jellyfin/jellyfin/blob/82cb6851786d4fb24952d77d869f9e9c005a960a/MediaBrowser.Model/Entities/MediaStream.cs#L143-L146
https://github.com/jellyfin/jellyfin/blob/82cb6851786d4fb24952d77d869f9e9c005a960a/MediaBrowser.Model/Entities/MediaStream.cs#L237-L240
> Remove all instances of en-US culture

- Emby.Server.Implementations/Archiving/ZipClient.cs
Fixes https://github.com/jellyfin/jellyfin/issues/6560
Exception was added in https://github.com/adamhathcock/sharpcompress/pull/614
> Create output directory when extracting archive files

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
This is required to get proper subtitle display name until an alternative is properly implemented
> Disable DOTNET_SYSTEM_GLOBALIZATION_INVARIANT in docker images

- README.md
**Changes**
Now that `master` is updated to .NET 6.0, update the `README` documentation as well.
Also, the change updates the link to point to the expanded version select page of the Microsoft .NET downloads, since .NET 6.0 is still an RC.
> Update README for .NET version

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
**Changes**
In the case that a track title isn't set for audio or subtitle tracks this change checks for a "handler_name" field to use as a title.
**Explanation**
Handbrake-produced mp4 files don't have a title set on audio or subtitle tracks, but looking at the handbrake code there's a check for mp4 file type that adds the title to the "handler_name" field: [Audio](https://github.com/HandBrake/HandBrake/blob/004a1ff49ddcbba8326ef6a5f58a1dd203f2f663/libhb/muxavformat.c#L783) [Subtitle](https://github.com/HandBrake/HandBrake/blob/004a1ff49ddcbba8326ef6a5f58a1dd203f2f663/libhb/muxavformat.c#L1062)
Additionally, there's a note in the ffmpeg encoder referencing the use of "handler_name" for track description: [movenc.c](https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/refs/heads/master:/libavform …
> Add mp4 track title fallback

- deployment/unraid/docker-templates/README.md
The link with 'blob' specified in the URL doesn't work for the current version of Unraid. Replacing 'blob' with 'tree' (which is where the 'blob' link resolves to) works fine.
Changes
Changed link referenced: https://github.com/jellyfin/jellyfin/blob/master/deployment/unraid/docker-templates
To this link: https://github.com/jellyfin/jellyfin/tree/master/deployment/unraid/docker-templates
Issues
Fixes template showing up in Unraid with the changes applied.
> Corrected Unraid template link

- Emby.Dlna/DlnaManager.cs
- Jellyfin.Api/Controllers/DlnaController.cs
- MediaBrowser.Controller/Dlna/IDlnaManager.cs
Fixes https://github.com/jellyfin/jellyfin/issues/6738
Not sure how this broke, but this changes the check to match `GetProfile`
https://github.com/jellyfin/jellyfin/blob/master/Emby.Dlna/DlnaManager.cs#L295-L310
> Use correct id when finding existing dlna profile

- .github/workflows/openapi.yml
**Changes**
Add a new workflow called that does the following things:
- Generate OpenAPI spec for master branch
- although already available via azure on repo.jellyfin.org, this adds it the the GitHub interface
- Generate OpenAPI spec for master branch
- Useful when I need to test something with the Kotlin SDK, or to inspect changes in the file
- Calculate difference between PR spec and baseline (target branch) spec using [openapi-diff](https://github.com/OpenAPITools/openapi-diff)
- Diff is rendered using markdown and added as a comment to the PR
- If the PR is updated it will update the existing comment
- Comment uses a `<details>` element to prevent skyscraper tall comments
- For example, when updating BaseItemDto
The comments will help reviewers to determine if a PR contains breaking …
> Add OpenAPI workflow

- MediaBrowser.Providers/Plugins/Tmdb/Configuration/PluginConfiguration.cs
- MediaBrowser.Providers/Plugins/Tmdb/Configuration/config.html
- MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs
Added new settings to disable tags import from TMDB for Movies and Series. Most tags are only available in English, so other languages should be able to disable the import. I don't like the naming of most tags, so I would disable them even with English as language.
**Changes**
Settings have "Exclude" in their name, so default behaviour without a configuration change is to import the tags (act as before)
**Issues**
https://github.com/jellyfin/jellyfin-plugin-tmdb/issues/10
**Hint**
Don't test the same movie/serie again after a configuration change. Providers use an IMemoryCache and if a movie/serie/person/... is in cache, the refresh doesn't trigger a new search, it uses the data from cache. A configuration change for some (all?) settings should clear the cache imho (only a language change …
> Make tags import from TMDB configurable

- Emby.Naming/Common/NamingOptions.cs
- tests/Jellyfin.Naming.Tests/TV/EpisodeNumberTests.cs
**Changes**
**Issues**
Fixes #2839
> Optimize episode parser

- Emby.Naming/Common/NamingOptions.cs
- Emby.Naming/TV/SeriesInfo.cs
- Emby.Naming/TV/SeriesPathParser.cs
- Emby.Naming/TV/SeriesPathParserResult.cs
- Emby.Naming/TV/SeriesResolver.cs
- Emby.Server.Implementations/Library/Resolvers/TV/SeriesResolver.cs
- tests/Jellyfin.Naming.Tests/TV/SeriesPathParserTest.cs
- tests/Jellyfin.Naming.Tests/TV/SeriesResolverTests.cs
Improves series name matching (thus better hit ratio at tmdb) for paths that contain more information that just the series name (ex. show.s01). The output from the SeriesResolver is a "clean" series name.
> Improve series matching

- Emby.Server.Implementations/ApplicationHost.cs
- Jellyfin.Server/CoreAppHost.cs
- Jellyfin.Server/Program.cs
- MediaBrowser.Common/IApplicationHost.cs
- tests/Jellyfin.Server.Integration.Tests/JellyfinApplicationFactory.cs
- tests/Jellyfin.Server.Integration.Tests/TestAppHost.cs
Before without web dir set:
```
[18:58:57] [INF] [1] Main: Jellyfin version: 10.8.0
[18:58:57] [INF] [1] Main: Environment Variables: ["[DOTNET_CLI_TELEMETRY_OPTOUT, 1]", "[DOTNET_ROOT, /home/bond/dotnet]", "[ASPNETCORE_URLS, http://localhost:8096]", "[JELLYFIN_LOG_DIR, /home/bond/.local/share/jellyfin/log]", "[ASPNETCORE_ENVIRONMENT, Development]"]
[18:58:57] [INF] [1] Main: Arguments: ["/home/bond/dev/jellyfin/Jellyfin.Server/bin/Debug/net6.0/jellyfin.dll"]
[18:58:57] [INF] [1] Main: Operating system: Linux
[18:58:57] [INF] [1] Main: Architecture: X64
[18:58:57] [INF] [1] Main: 64-Bit Process: True
[18:58:57] [INF] [1] Main: User Interactive: True
[18:58:57] [INF] [1] Main: Processor count: 16
[18:58:57] [INF] [1] Main: Program data path: /home/bond/.local/share/jellyfin
[18:58:57] …
```
> Streamline startup code

- MediaBrowser.Model/Dlna/StreamBuilder.cs
With log level INFO everytime a DLNA client connects to Jellyfin you have multiple log lines for every library item in jellyfin.log AND syslog. If you have a large library, then you have multiple thousand log lines in jellyfin.log and syslog
**Changes**
Set log level to DEBUG, Ubuntu defaults to INFO or higher in syslog => no more logging
> Prevent log spam in StreamBuilder.cs

- MediaBrowser.Providers/Plugins/Tmdb/BoxSets/TmdbBoxSetImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/People/TmdbPersonImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeasonImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesImageProvider.cs
- MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs
- MediaBrowser.Providers/Plugins/Tmdb/TmdbUtils.cs
- tests/Jellyfin.Providers.Tests/Tmdb/TmdbUtilsTests.cs
**Changes**
- Extract copy-pasted code to convert `ImageData` to `RemoteImageInfo` and add test for new method
- Extract boilerplate GetTypeUrl code into a private helper method.
I was looking at the TMDb plugin to add logo support (next TMDbLib release should support logos) and I noticed there were some copy/paste errors (missing language where the API returns it, using `GetPosterUrl` for a backdrop, etc). Low impact, but seeing as the code showed proof that the duplication was hurting maintainability I figured it was worth cleaning up now.
> Clean up duplicate TmdbImageProvider code

- MediaBrowser.Controller/Entities/IHasScreenshots.cs
- MediaBrowser.LocalMetadata/Images/LocalImageProvider.cs
- MediaBrowser.Providers/Manager/ItemImageProvider.cs
- tests/Jellyfin.Providers.Tests/Manager/ItemImageProviderTests.cs
https://github.com/jellyfin/jellyfin/pull/6752#discussion_r741512495
> Remove unused IHasScreenshots interface

- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
**Changes**
Check ReadToDescendant's return value
**Issues**
Fixes #6773
> Make sure ReadToDescendant was successful before continuing

- .github/workflows/openapi.yml
**Changes**
Changed the workflow to use the `pull_request_target` event instead of `pull_request`. I was not able to test this change.
**Issues**
> Fix OpenAPI workflow not working with pull requests from forks

- .github/workflows/openapi.yml
**Changes**
- Specify repository in actions/checkout to fix cloning of forks
- Change to read-only permissions for GITHUB_TOKEN to prevent h@ckers
**Issues**
> Fix OpenAPI workflow fork cloning

- Emby.Server.Implementations/Plugins/PluginManager.cs
**Changes**
GetExportedTypes only loads public types. GetTypes loads everything that is required.
**Issues**
Fixes #6776
> Load all types when checking plugin DLLs

- Emby.Server.Implementations/Dto/DtoService.cs
- MediaBrowser.Controller/Entities/BaseItem.cs
- MediaBrowser.Model/Entities/ImageType.cs
- MediaBrowser.Model/Querying/ItemFields.cs
- MediaBrowser.Providers/Manager/ImageSaver.cs
- MediaBrowser.Providers/Manager/ItemImageProvider.cs
- tests/Jellyfin.Providers.Tests/Manager/ItemImageProviderTests.cs
Opposite of #6779
**Changes**
- Remove references to `ImageType.Screenshot` and `ItemFields.Screenshot` and deprecate the enum entries.
For reference, the `Game` type that had screenshots was removed in [8985fb8d58c9b968b8e773276d7c3902aa4d55f3](https://github.com/jellyfin/jellyfin/commit/8985fb8d58c9b968b8e773276d7c3902aa4d55f3).
> Deprecate ImageType.Screenshot and ItemFields.Screenshot

- Emby.Server.Implementations/IO/ManagedFileSystem.cs
```
[15:01:24] [ERR] [55] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Environment/Drives.
System.UnauthorizedAccessException: Access to the path is denied.
---> System.IO.IOException: Operation not permitted
--- End of inner exception stack trace ---
at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
at System.IO.DriveInfo.get_TotalSize()
at Emby.Server.Implementations.IO.ManagedFileSystem.<>c.<GetDrives>b__32_0(DriveInfo d) in /home/bond/dev/jellyfin/Emby.Server.Implementations/IO/ManagedFileSystem.cs:line 583
at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToList()
at Emby.Server.Implementations.IO.ManagedFileSystem.GetDrives() in /home/bond/dev/jellyfin/Emby.Server.Implementations/IO/ManagedFileSystem.cs:line 583
at …
```
> Fix UnauthorizedAccessException in GetDrives

- MediaBrowser.Model/Entities/ImageType.cs
https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer?redirectedfrom=MSDN&view=net-5.0#objects-marked-with-the-obsolete-attribute-no-longer-serialized
Fixes loading the LibrarySettings for anyone who has configured the fetcher
> Remove Obsolete attribute on enum

- MediaBrowser.Providers/Manager/ItemImageProvider.cs
Required for remote image providers that don't specify dimensions
Fixes https://github.com/jellyfin/jellyfin-plugin-tvmaze/issues/34
> Fix filtering images without dimensions

- Emby.Server.Implementations/ApplicationHost.cs
- Jellyfin.Api/Controllers/SystemController.cs
- MediaBrowser.Common/IApplicationHost.cs
- MediaBrowser.Controller/IServerApplicationHost.cs
**Changes**
Moved WOL to the controller and deprecated the endpoint. And other small refactors/optimizations.
> Very light cleanup in applicationhost

- .ci/azure-pipelines-package.yml
**Changes**
Sends the `Build.SourceBranch` variable into collect-server.azure.sh. This can be used to determine if a release is a pre-release or not based on the tag append.
**Issues**
N/A
> Send SourceBranch to collect-server.azure.sh

- Emby.Server.Implementations/HttpServer/Security/AuthService.cs
- Emby.Server.Implementations/HttpServer/WebSocketManager.cs
- Jellyfin.Api/Auth/CustomAuthenticationHandler.cs
- tests/Jellyfin.Api.Tests/Auth/CustomAuthenticationHandlerTests.cs
Fixes https://github.com/jellyfin/jellyfin/issues/6832
> Don't throw exception on unauthenticated requests

- Emby.Dlna/ContentDirectory/ControlHandler.cs
During the code cleanup done in https://github.com/jellyfin/jellyfin/pull/6808 the StringBuilder ToString() method call was moved before the destruction of the XmlWriter.
This PR adds a manual call to Flush the XmlWriter in order to have the correct data inside the StringBuilder.
If preferred I can update the PR to have the "builder.ToString()" called outside the scope of the XmlWriter and restore the original behavior with the automatic flush (but would undo the "Reduce indentation" commit).
> Flush the XmlWriter before calling the StringBuilder ToString() method

- Jellyfin.Api/Controllers/VideosController.cs
StreamingHelpers.GetStreamingState populates state.Request.StartTimeTicks based on the startTimeTicks query variable and DLNA headers.
Currently the query variable was used directly losing anything provided by "TimeSeekRange.dlna.org" .
> Ensure the proper StartTimeTicks variable is forwarded to the AddDlnaHeaders function

- MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
- MediaBrowser.Providers/MediaInfo/EmbeddedImageProvider.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/EmbeddedImageProviderTests.cs
**Changes**
- Clean up tests, merge similar tests using theories.
- Switch `IMediaEncoder` to take an enum type instead of string for image format to be less error-prone.
- Merge duplicated codec check in normalizer.
- Check codec for format of embedded image.
> Image provider cleanup

- MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzAlbumProvider.cs
- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
**Changes**
ReadSubtree does not advance the reader, so when the element is empty it will keep reading the empty element forever. I have added some extra IsEmptyElement checks
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/6858
> Read past empty elements

- Emby.Server.Implementations/ApplicationHost.cs
It shouldn't force a scheme and/or port when https is allowed. The call to `GetLocalApiUrl` will decide that.
> Only force scheme and port when HTTPS is disallowed

- tests/Jellyfin.Server.Implementations.Tests/LiveTv/RecordingHelperTests.cs
**Changes**
Sets DateTimeKind to Local. When timezone is negative UTC, the date goes back one day and causes tests to fail.
> Use local time for RecordingHelperTests

- Jellyfin.Api/Helpers/ProgressiveFileStream.cs
- Jellyfin.Api/Models/PlaybackDtos/TranscodingJobDto.cs
- Jellyfin.Api/Models/PlaybackDtos/TranscodingThrottler.cs
**Changes**
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1835
I can't test this properly. Requires some testing with Live tv.
> Use the Memory overload for ReadAsync

- MediaBrowser.Model/Dlna/ContentFeatureBuilder.cs
When direct playing content over DLNA (no transcoding) on a LG CX3 TV the seek functionality is disabled.
Adding the DLNA.ORG_OP and appropriate byte seek flag restores the functionality for direct play.
Adding the DLNA.ORG_OP when transcoding breaks playback and requires further investigation so I haven't touched that particular code path.
> - enable seek function when direct streaming over DLNA

- MediaBrowser.Providers/MediaInfo/SubtitleResolver.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/SubtitleResolverTests.cs
**Changes**
- Add handling for default/forced/foreign tag when no language is set (with tests)
- Address suppressed warnings on `SubtitleResolver`
**Issues**
Fixes #6911
> Subtitle filename parsing fix

- MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs
**Changes**
Use SSL for TMDB image URLs to allow image thumbnails to load for identify and image search
**Issues**
Fixes #6925
> Use SSL for tmdb images

- Jellyfin.Api/Helpers/StreamingHelpers.cs
[DidlBuilder.cs#L84](https://github.com/jellyfin/jellyfin/blob/976e3160b8d558aaa3e944892a3362f004bc93a6/Emby.Dlna/Didl/DidlBuilder.cs#L84) appends the dlnaheaders=true query parameter to all the DLNA urls.
This parameter seems to be ignored when processing the video stream and the DLNA headers are only added in two specific cases:
- "GetContentFeatures.DLNA.ORG" is 1
- streamingRequest.Params is provided
I think it's worth clearing up the intentions of the original code.
> Take into account the streams dlnaheaders query parameter set by the DidlBuilder NormalizeDlnaMediaUrl function

- .ci/azure-pipelines-package.yml
- bump_version
Should prevent strangeness with building these for pre-releases or actual release versions (if the script wasn't manually run before). Whatever the Git tag is, becomes the package version. Could be expanded to avoid needing to manually `bump_version` at all ever if we put in placeholders, though this might break other builds. Would need careful evaluation before expanding that.
With a properly bumped stable release this shouldn't change anything, but for pre-releases it will change the version automatically.
Avoids needing to do #6853 manually (for both Debian and Fedora/CentOS packages).
Basically, adds a run of `bump_version` to the build CI, taking the Git tag as the version to bump to.
> Automatically bump stable versions in build

- Jellyfin.Server/Migrations/MigrationRunner.cs
Fixed crash in MigrationRunner by checking for migration file existance
**Changes**
By checking for the existance of migrationConfigPath before attempting to load it, the server does not throw an unhandled exception or crash.
**Issues**
Fixes #6992
> Fixed crash in MigrationRunner by checking migration for file existance

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
Fixes regression from https://github.com/jellyfin/jellyfin/pull/6979
The following enum values are unmapped:
```
BaseItemKind.ManualPlaylistsFolder
BaseItemKind.ChannelFolderItem
BaseItemKind.Program
BaseItemKind.Recording
```
Also fixes the naming of `_retrieveItemColumns`
> Fix BaseItemKind Querying

- MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs
- MediaBrowser.Model/Configuration/LibraryOptions.cs
**Changes**
Deprecate LibraryOptions.EnableInternetProviders
**Rationale**
1. This is hardcoded to true without exposing to user in [library options page (web)](https://github.com/jellyfin/jellyfin-web/blob/4db454d95e3cc30e7807ca7f7faa252bf0dc9e56/src/components/libraryoptionseditor/libraryoptionseditor.js#L503) so even if you change it in the settings file manually it will be overridden when you next modify the library settings through the interface.
2. Not evaluated unless the library options don't configure providers for a type, but the only types that aren't configured by the library options don't actually tree up to a library to find this setting (People, Trailers, etc)
3. Currently disables `IDynamicImageProvider` (extracted from video file) as well as `IRemoteImageProvider` …
> Deprecate LibraryOptions.EnableInternetProviders

- debian/jellyfin.service
**Changes**
Remove `ProtectClock=true` in jellyfin.service
**Issues**
If enable hardware acceleration, ffmpeg doesn't find the gpu.
It worked fine when I erased that from my environment with NVIDIA GeForce RTX 2070 SUPER.
> Remove ProtectClock for hardware encoding

- MediaBrowser.Controller/Entities/BaseItem.cs
It's not the biggest offender but it performs two closure allocations per call. The `==` (which Guid implements) does not need closure.
> Use == instead of Object.Equals to avoid closure allocation

- src/Jellyfin.Extensions/Json/Converters/JsonDelimitedArrayConverter.cs
- src/Jellyfin.Extensions/Json/Converters/JsonGuidConverter.cs
- src/Jellyfin.Extensions/Json/Converters/JsonNullableGuidConverter.cs
- src/Jellyfin.Extensions/Json/Converters/JsonNullableStructConverter.cs
- src/Jellyfin.Extensions/Json/Converters/JsonStringConverter.cs
* If the type is a reference type we don't have to handle null ourselves
* `reader.ValueSpan` is only valid if `reader.HasValueSequence` is false
> Remove unreachable branches from JsonConverters

- Emby.Server.Implementations/Library/LibraryManager.cs
**Changes**
When a new library is created with a name that already exists:
- if the last character is not a number: a " 2" is appended.
- if the last character is a number: that number is incremented by 1.
**Issues**
Supersedes #5823
> Increment library name number instead of appending

- Emby.Server.Implementations/Archiving/ZipClient.cs
- Emby.Server.Implementations/Updates/InstallationManager.cs
- MediaBrowser.Model/IO/IZipClient.cs
- tests/Jellyfin.Server.Implementations.Tests/Updates/InstallationManagerTests.cs
Also removes unused methods from ZipClient
Tested by installing a plugin
> Use System.IO.Compression instead of SharpCompress for zips

- Emby.Naming/Common/NamingOptions.cs
- Emby.Naming/Video/VideoListResolver.cs
- Emby.Server.Implementations/Library/CoreResolutionIgnoreRule.cs
- Emby.Server.Implementations/Library/LibraryManager.cs
- Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
- MediaBrowser.Controller/Entities/BaseItem.cs
- MediaBrowser.Controller/Entities/IHasSpecialFeatures.cs
- MediaBrowser.Controller/Entities/Movies/Movie.cs
- MediaBrowser.Controller/Library/ILibraryManager.cs
- MediaBrowser.LocalMetadata/Images/LocalImageProvider.cs
- tests/Jellyfin.Naming.Tests/Video/MultiVersionTests.cs
- tests/Jellyfin.Naming.Tests/Video/VideoListResolverTests.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/LibraryManager/FindExtrasTests.cs
Fixed "trailers", theme song and theme videos.
> Fix extras folders

- Jellyfin.Api/Controllers/LibraryController.cs
**Changes**
Passing item's genres to obtain a more accurate list of its related media
> Related media according to genre

- Jellyfin.Api/Helpers/DynamicHlsHelper.cs
- MediaBrowser.Model/Dlna/StreamBuilder.cs
- MediaBrowser.Model/Dlna/SubtitleDeliveryMethod.cs
Currently there is no option to stop DLNA from transcoding when encountering specific subtitle formats.
A new Drop option was added to the SubtitleProfile that should allow us to control when we want avoid transcoding.
For the end user it should be easier to ignore embedded PGSSUB subtitles from the DLNA profile and provide an external subtitle than to modify large video files.
> Add an option for dropping specific subtitle formats using the DLNA SubtitleProfile

- Emby.Server.Implementations/Dto/DtoService.cs
**Changes**
Primary aspect ratio is computed in a prioritized order:
1. From ImageInfo
2. From ImageProcessor
3. BaseItem.DefaultPrimaryImageAspectRatio
**Issues**
Idk
> Try to use Width and Height from ImageInfo to determine aspect ratio

- Emby.Server.Implementations/Library/PathExtensions.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/PathExtensionsTests.cs
By popular request, this adds the ability for the provider id to be found 
`[tvdbid=12345]` or `[tvdbid-12345]`, first in the filename is the winner.
> Add ability to search by -

- MediaBrowser.Model/Net/MimeTypes.cs
- tests/Jellyfin.Model.Tests/Net/MimeTypesTests.cs
Fixes https://github.com/jellyfin/jellyfin/issues/7050
Fixes https://github.com/jellyfin/jellyfin/issues/7097
`image/jpg` may not be a valid mime-type, but it's required for our workflow
> Add image/jpg to extension lookup

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
**Changes**
`true` was `Descending`, `false` was `Ascending`...
https://github.com/jellyfin/jellyfin/blob/ea8f40e84a72ab1eb0bdbe4974cb78f7d1b0f552/Emby.Server.Implementations/Data/SqliteItemRepository.cs#L3050-L3134
**Issues**
Reported in Matrix.
> Reverse all order-by

- Emby.Server.Implementations/HttpServer/WebSocketConnection.cs
- Emby.Server.Implementations/HttpServer/WebSocketManager.cs
- Emby.Server.Implementations/Session/SessionWebSocketListener.cs
- MediaBrowser.Controller/Net/BasePeriodicWebSocketListener.cs
- MediaBrowser.Controller/Net/IWebSocketConnection.cs
- MediaBrowser.Controller/Net/IWebSocketListener.cs
- tests/Jellyfin.Server.Implementations.Tests/HttpServer/WebSocketConnectionTests.cs
**Changes**
Adds the ability to use `ApiKey` instead of `api_key` to authenticate when connecting the websocket.
> Allow ApiKey query parameter for authentication

- MediaBrowser.Providers/TV/SeasonMetadataService.cs
**Changes**
Check the locked state of the item/field when resetting the Specials season name to the library default
**Issues**
Fixes #7096
> Respect lock state when updating season 0 name

- MediaBrowser.Model/Dlna/StreamBuilder.cs
Sometimes the audio stream isn't known, or doesn't exist...
> Add null check for audio stream

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
The two boxes should be independent of each other according to the codec.
**Changes**
- Fix the wrong logic in HEVC VP9 10bit hwdec boxes
**Issues**
Fixes #6606
> Fix the wrong logic in HEVC VP9 10bit hwdec boxes

- MediaBrowser.Controller/Entities/TV/Episode.cs
Implement trakt episode links using the implementation from Series.cs.
The code is the same as `MediaBrowser.Controller/Entities/TV/Series.cs`, using the imdbID to generate Trakt links.
The trakt url for episodes is `https://trakt.tv/episodes/{0}`.
**Changes**
Introduce Trakt links on episode pages.
**Issues**
#7133
> Implement Trakt Episode Links

- MediaBrowser.Controller/Entities/Movies/Movie.cs
_Continuation of #7136_
**Changes**
Add `JsonIgnore` to special features of movie.
**Issues**
When refreshing the metadata of the video with a local trailer, the server gets stuck trying to read the database and save the item at the same time.
> Ignore JSON serialization for special features of movie.

- MediaBrowser.Providers/Plugins/Tmdb/Configuration/PluginConfiguration.cs
- MediaBrowser.Providers/Plugins/Tmdb/Configuration/config.html
- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeasonProvider.cs
**Changes**
Adds a configuration option to TMDB plugin to import season names from TMDB. Defaults to false, so same behavior is maintained.
I tested with a couple series, some with season names, some with out. Worked fine. I was not able to reproduce errors described in #4948 or #4134. Additional testing would be welcomed.
**Issues**
Fixes #2320
> Config option to import season name from TMDB

- Emby.Server.Implementations/Library/Resolvers/ExtraResolver.cs
**Changes**
Fix summary documentation.
**Issues**
`warning SA1642: Constructor summary documentation should begin with standard text`
> Fix SA1642 warning

- Emby.Naming/Common/NamingOptions.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/LibraryManager/FindExtrasTests.cs
Currently an item named "honest trailer.mkv" in the "extras" directory will fail to be attached to the movie as an extra because the suffix naming rule (` trailer`) is matched first by `ExtraRuleResolver` but `ExtraResolver` throws it out because the prefix doesn't match the movie name. Reordering the rules so directories are evaluated first fixes this.
**Changes**
- Moved `ExtraRuleType.DirectoryName` rules to top of list
- Added suffix rule `-extra` for consistency since it was the only directory not supported by a suffix rule
- Added tests for both rule changes
**Issues**
Fixes #7183
Fixes #3422 (indirectly - anything in the "extras" folder will now resolve as `ExtraType.Unknown` so it won't be picked up as a trailer)
> Order extra rules so directory takes precedence over naming

- Jellyfin.Api/Controllers/DynamicHlsController.cs
This is required for video playback from the browser.
_Probably something unnecessary._
**Changes**
Fix maximum video resolution for dynamic HLS controller
**Issues**
The maximum video resolution is not taken into account when playing video from the browser.
**See also**
#6274
> Fix maximum video resolution for dynamic HLS controller

- Emby.Naming/Common/NamingOptions.cs
- Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/MovieResolverTests.cs
**Changes**
- Restore resolver that handles local alternates
- Test resolver
- Generate extra folder names dictionary instead of duplicating hardcoded strings
**Issues**
Fixes #7189
Fixes #7155
> Fix resolving local alternates

- Emby.Server.Implementations/Dto/DtoService.cs
- Jellyfin.Api/Controllers/UserLibraryController.cs
- MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
**Changes**
- Fix duplication (same URL) of remote trailers
- Fix duplication of local trailers
**Issues**
- Wrong iterating over remote trailers causes duplication of remote trailers.
- `/LocalTrailers` endpoint returns doubled local trailers.
- `.LocalTrailerCount` is doubled as well.
> Fix trailers duplication

- Emby.Server.Implementations/Dto/DtoService.cs
- Emby.Server.Implementations/LiveTv/LiveTvDtoService.cs
- MediaBrowser.Model/Dto/BaseItemDto.cs
**Changes**
- Use Guid for BaseItemDto parent ids
- Remove GetDtoId in DtoService
**Issues**
> Use Guid for BaseItemDto parent ids

- MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
**Changes**
- Music Video metadata now checks to see if there is existing metadata before overwriting
- File metadata won't override manually-set metadata unless refreshing metadata with "Replace all metadata" (instead of just full refresh)
**Issues**
Fixes #7231
> Make ffprobe metadata merge consistent with MetadataService.MergeData

- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
**Changes**
Don't return subtitles of one format in a file with the wrong extension.
**Issues**
Fixes #7147
> Fix #7147: Don't return subtitles in mismatched format

- Jellyfin.Server/Program.cs
Prevent an exception from being thrown if startup fails. 
As seen in https://github.com/jellyfin/jellyfin/issues/6776
```
[09:31:18] [FTL] [1] Main: Unhandled Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
at Emby.Server.Implementations.ApplicationHost.Resolve[T]() in /home/crobibero/Code/jellyfin/Emby.Server.Implementations/ApplicationHost.cs:line 408
at Jellyfin.Server.Program.StartApp(StartupOptions options) in /home/crobibero/Code/jellyfin/Jellyfin.Server/Program.cs:line 231
at Jellyfin.Server.Program.<Main>(String[] args)
```
> Prevent additional errors on startup/shutdown

- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
- tests/Jellyfin.XbmcMetadata.Tests/Parsers/EpisodeNfoProviderTests.cs
- tests/Jellyfin.XbmcMetadata.Tests/Test Data/Sonarr-Thumb.nfo
**Changes**
Thumb tags within a fanart tag that have no aspect set are backdrops.
Thumb tags on a root level that have no aspect set are posters.
**Issues**
Fixes #7285
> NFO: fix thumb tags without aspect

- CONTRIBUTORS.md
- MediaBrowser.Model/Configuration/EmbeddedSubtitleOptions.cs
- MediaBrowser.Model/Configuration/LibraryOptions.cs
- MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
Option to disable embedded subs being added to metadata on library scan. This helps with setups that handle embedded subs badly.
Implements https://features.jellyfin.org/posts/985/hide-embedded-subtitles
> Add DisableEmbeddedSubtitles setting

- CONTRIBUTORS.md
- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
**Changes**
Increase timeout value for subtitle extraction operation from 5 minutes to 30 minutes. In some cases, ffmpeg takes over 5 minutes to extract the subtitle even though nothing is wrong with the file and the extraction is possible.
Arguably the fact that some video files take this long might indicate that this extraction step should be (optionally?) done in advance, otherwise there will be 5 to 30 minutes of the file playing without subtitles.
**Issues**
Addresses #6672
> Increase timeout for subtitle extraction to 30min

- .github/workflows/openapi.yml
This should fix pull requests comparing their specification against the latest from the master branch and use the commit the branch was originally created of.
**Changes**
- Use sha hash instead of branch name for OpenAPI workflow head reference
**Issues**
> Use sha hash instead of branch name for OpenAPI workflow head reference

- Jellyfin.Api/Helpers/TranscodingJobHelper.cs
Currently, when transcoding finishes it is not reported - leaving the UI with an incomplete transcode %
**Changes**
Report transcoding progress as empty / complete when the transcoding job finishes
> [Bugfix] Report transcoding complete

- Emby.Server.Implementations/TV/TVSeriesManager.cs
- Jellyfin.Api/Controllers/TvShowsController.cs
- MediaBrowser.Model/Querying/NextUpQuery.cs
If you're watching a watched series again, this will find the watched episode after the most recently watched episode. This is something I've wanted for a while since our family tends to rewatch favorite shows.
I was able to get this functionality with minimal changes to the existing Next Up methods. 
There's a PR in JF-web that depends on this.
> Rewatching next up

- MediaBrowser.Controller/Entities/BaseItem.cs
- MediaBrowser.Providers/MediaInfo/AudioResolver.cs
- MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs
- MediaBrowser.Providers/MediaInfo/SubtitleResolver.cs
- tests/Jellyfin.Naming.Tests/ExternalFiles/ExternalPathParserTests.cs
- tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj
- tests/Jellyfin.Providers.Tests/MediaInfo/AudioResolverTests.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/MediaInfoResolverTests.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/SubtitleResolverTests.cs
I started a rewrite of the `MediaInfoResolver` tests when I was helping with #7255 but didn't want to muddle the pull request by adding my code to a pull request that wasn't mine.
**Changes**
- Require a "." immediately after the matched movie title, to prevent "Iron Man 2.srt" from matching "Iron Man.mkv" in a flat directory structure.
- Merge and rewrite duplicated tests to match merged base class `MediaInfoResolver`, test only differences in `AudioResolverTests` and `SubtitleResolverTests`
- Move extensive flag testing to `ExternalPathParserTests` to minimize the mocking required
- Address minor warnings in Rider
- Revert `BaseItem` change from #7255 now that it's no longer necessary to mock `GetInternalMetadataPath`
> Merge MediaInfoResolver subclass tests

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Fixed by replacing pixel format from NV21 to yuv420p.
Applied the suggestions that @nyanmisaka asked for in #7227 
Error when enabling v4l acceleration in Raspberry Pi 4. I utilized the LinuxServer.io Nightly Container to test:
```
sudo docker run -d \
--name=jellyfin \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=America/Denver \
-e JELLYFIN_PublishedServerUrl=192.168.1.2 \
-p 8096:8096 \
-p 8920:8920 \
-p 7359:7359/udp \
-p 1900:1900/udp \
-v ~/jellyfin_dev/lscrio_nightly_library:/config \
-v ~/jellyfin_dev/media:/media \
--restart unless-stopped \
--device=/dev/video10:/dev/video10 \
--device=/dev/video11:/dev/video11 \
--device=/dev/video12:/dev/video12 \
lscr.io/linuxserver/jellyfin:nightly
```
I attempted to play Big Buck Bunny (Creative Commons Licensed Video); specifically …
> Fix h264_v4l2m2m acceleration in Raspberry Pi 4

- Emby.Server.Implementations/Library/LibraryManager.cs
- Emby.Server.Implementations/Library/Resolvers/BaseVideoResolver.cs
- Emby.Server.Implementations/Library/Resolvers/ExtraResolver.cs
- Emby.Server.Implementations/Library/Resolvers/GenericVideoResolver.cs
- Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
- Emby.Server.Implementations/Library/Resolvers/TV/EpisodeResolver.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/EpisodeResolverTest.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/LibraryManager/FindExtrasTests.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/MovieResolverTests.cs
Attempt to fix #7100 - when UDFReader throws on opening an invalid UDF image. Try/Catch will allow the library scan to continue.
**Changes**
* Attempt to fix #7100
* Catch exceptions thrown by `UdfReader`
* Inject the Logger into the `ExtraResolver` and other `Resolvers`
**Issues**
* Fixes #7100 - when UDFReader throws on opening an invalid UDF stream.
**Testing**
```
[10:42:26] [ERR] [39] Emby.Server.Implementations.Library.Resolvers.Movies.MovieResolver: Error opening UDF/ISO image: X:\Files\Some.Invalid.iso
System.IO.InvalidDataException: Stream is not a recognized UDF format
at DiscUtils.Udf.UdfReader.VfsUdfReader..ctor(Stream data)
at DiscUtils.Udf.UdfReader..ctor(Stream data)
at Emby.Server.Implementations.Library.Resolvers.BaseVideoResolver`1.SetIsoType(Video video) in …
```
> Fix #7100 - when opening invalid UDF images

- Dockerfile
**Issues**
Fixes https://github.com/jellyfin/jellyfin-ffmpeg/issues/94
> Update intel compute runtime to 22.08.22549

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
* dont use -noaccurate_seek for hls
**Issues**
* exoplayer in the Android TV client would get chunks with video that starts earlier than their timestamps. Typically it would be around 4 seconds behind.
when testing with https://github.com/jellyfin/jellyfin/pull/6600 on Android-TV I found segments were still inaccurate (off by the time difference between two keyframes), even though the requested time was keyframe-aligned. I assume this is because even though the requested timestamp is keyframe aligned, ffmpeg still only goes up until the preceding keyframe.
This issue also occurred in the android (mobile) client using the web player backend
The main resulting issue is that subtitles handled externally can't be synced to the video
**Notes**
* with both hls and progressive …
> fix HLS transcoding on android tv -- dont use -noaccurate_seek for hls transcode

- Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs
- Emby.Server.Implementations/Images/DynamicImageProvider.cs
**Changes**
- UserView thumbnail (like when you group multiple libraries of the same type together on the homepage) was using poster images, not backdrop. 
- Image selected would never change, shuffle available items with images.
> UserView Thumbnail fixes

- Emby.Server.Implementations/Session/SessionManager.cs
- MediaBrowser.Controller/Session/SessionInfo.cs
Needed for https://github.com/jellyfin/jellyfin-vue/pull/1040 and should be backwards compatible with any client.
(Not tested)
[openapi.json.txt](https://github.com/jellyfin/jellyfin/files/6489925/openapi.json.txt)
> Add FullNowPlayingQueue property to sessions endpoint

- MediaBrowser.MediaEncoding/Probing/MediaChapter.cs
ffmpeg 5.0 is producing values well outside the range of an int in the chapter id field. From the linked issue:
```
"chapters": [
{
"id": 251446668167383985,
"time_base": "1/1000000000",
"start": 0,
"start_time": "0.000000",
"end": 99766333333,
"end_time": "99.766333"
},
```
The `Id` field only exists in jellyfin to parse the json output: it's not used in any way downstream (see [here](https://github.com/jellyfin/jellyfin/blob/e26446f9c06d23d483d7c3db40888d51d37fdcdc/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L1433) for the use of `MediaChapter`).
**Changes**
- Parse the unused chapter id from ffmpeg output of as a long
**Issues**
Fixes #7355
> Parse the unused chapter id field from ffmpeg output as a long

- CONTRIBUTORS.md
- Jellyfin.Api/Helpers/TranscodingJobHelper.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.Controller/MediaEncoding/IAttachmentExtractor.cs
- MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
**Changes**
When burning in subtitles, attachments to the video file get extracted and the path gets supplied as fontsdir to ffmpeg. This way, ffmpeg can burn in subtitles with the correct fonts, when they are attached to the video and not installed on the system.
**Issues**
Fixes #1589 (subtitles will now render correctly when burning them, like in the Plex screenshot)
Would fix 2. of #7208, but by looking at the mediainfo, I think the font is missing completely there (not on system or media file) 
Theres some commented out code concerning fallbackFontPath with TODO in EncodingHelper. There can only be one fontsdir supplied to ffmpeg, so it wouldn't work together. But also, you shouldn't supply a directory with lots of fonts to ffmpeg, because that can slow the start of the transcoding …
> Add extracting attachments for ffmpeg to burn subtitles with correct fonts

- CONTRIBUTORS.md
- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
Since the introduction of PR https://github.com/jellyfin/jellyfin/pull/6639, `handler_name`s of audio streams are used as track titles, if there is no explicit title metadata.
However, I noticed that the large majority of video files in my collection (2300+ files):
- have no explicit track titles (hence PR 6639 applies to them)
- but they *also* have not set the `handler_name` to anything useful. 
Instead those files are all using the (apparent) [ffmpeg] default value of `SoundHandler` as their track title. This causes confusion in the UI, as users now see most audio tracks as being named something like
`SoundHandler - English - AAC - 5.1 - Default`
which may be confusing for them ("what does SoundHandler mean?"). Having SoundHandler here is not useful and IMHO worse than having no track …
> Remove superfluous "SoundHandler" from audio stream names

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Fix the path to the extracted fonts on Windows
`[subtitles @ 00000242d17da380] Unable to parse option value "C\:/Users/..."`
**Issues**
Fixes #7275
> Fix the path to the extracted fonts on Windows

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Set `-threads 1` to NVDEC decoder explicitly since it doesn't implement threading support. The default number of threads in NVDEC reserves too much VRAM without actually using them.
- Remove the `extra_hw_frames` workaround since it has been fixed by switching to yuv420p instead of nv12(disabling passthrough mode) in cuda pipeline. (save ~100MiB VRAM too)
**Issues**
VRAM usage:
4k 10bit HEVC ->1080p H264
1474 MiB -> **712 MiB**
1080p 10bit HEVC -> 1080p H264
491 MiB -> **293 MiB**
observed by `nvidia-smi 511.79` on GTX 1650
> Lowering the VRAM usage on NVDEC decoder

- Jellyfin.Server/Migrations/Routines/MigrateAuthenticationDb.cs
Fixes https://github.com/jellyfin/jellyfin/issues/7108
The `DateTime` was stored as `TEXT`, and `.ToDateTime()` calls `new DateTime(This.ToInt64())`, which is parsed as `0`
> Fix migration of DateTime to EF

- MediaBrowser.Model/Session/GeneralCommand.cs
This allows `Arguments` to remain without a setter.
> Add JsonConstructor to GeneralCommand

- Emby.Server.Implementations/Sorting/IndexNumberComparer.cs
- Emby.Server.Implementations/Sorting/ParentIndexNumberComparer.cs
- MediaBrowser.Model/Querying/ItemSortBy.cs
Can be used in item queries to sort by ParentIndexNumber and IndexNumber (used for disc and track numbers for example).
Closes #7323.
> Implement Comparers for (Parent)IndexNumber

- Emby.Server.Implementations/IO/ManagedFileSystem.cs
- MediaBrowser.Controller/Entities/BaseItem.cs
- MediaBrowser.Controller/Providers/DirectoryService.cs
- MediaBrowser.Controller/Providers/IDirectoryService.cs
- MediaBrowser.Model/IO/IFileSystem.cs
- MediaBrowser.Providers/MediaInfo/AudioResolver.cs
- MediaBrowser.Providers/MediaInfo/FFProbeProvider.cs
- MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs
- MediaBrowser.Providers/MediaInfo/SubtitleResolver.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/AudioResolverTests.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/MediaInfoResolverTests.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/SubtitleResolverTests.cs
Fixes regression from https://github.com/jellyfin/jellyfin/pull/7255/
> Only add internal files if the internal metadata path exists

- Emby.Naming/Common/NamingOptions.cs
- Emby.Naming/ExternalFiles/ExternalPathParser.cs
- MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/MediaInfoResolverTests.cs
**Changes**
- Remove fuzzy matching for code simplicity
- Add test cases based on linked issue
- Convert `MediaFlagDelimiter` back to char
**Issues**
Fixes #7361
Supersedes #7393
> Strip out external file fuzzy name matching

- Emby.Server.Implementations/TV/TVSeriesManager.cs
- Jellyfin.Api/Controllers/TvShowsController.cs
- MediaBrowser.Model/Querying/NextUpQuery.cs
**Changes**
Updates the new "rewatching" feature of Next Up to be returned with the normal results that is controlled by a user setting in web.
**Issues**
N/A
> Include played and unplayed results in the same next up request

- MediaBrowser.Providers/Plugins/StudioImages/Plugin.cs
- MediaBrowser.Providers/Plugins/StudioImages/StudiosImageProvider.cs
**Changes**
Removes usage of the Emby Resources repository and replaces it with the [jellyfin/emby-artwork](https://github.com/jellyfin/emby-artwork) repository
**Issues**
Fixes #2567
> Update artwork repository urls

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Fix crashes on older intel gfx when both iHD and i965 driver are existed.
**Changes**
- Set the name of intel vaapi driver explicitly
**Issues**
Should fixes https://github.com/jellyfin/jellyfin-ffmpeg/issues/92 and https://github.com/jellyfin/jellyfin-ffmpeg/issues/99
> Set the name of intel vaapi driver explicitly

- MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/MediaInfoResolverTests.cs
Missed a case that the `CompareInfo` prefix check handled automatically...
**Changes**
- Fix `ArgumentOutOfRangeException` on files with shorter names than the movie
**Issues**
Fix for #7394
> Fix external file check for shorter names

- MediaBrowser.Model/Entities/MediaStream.cs
This has bugged me for a while now.
Jellyfin shows the language for audio streams, if it is present in metadata. This is great and correct.
However, there are audio streams that make use of ISO 639-2 special codes. Those then look like this:
"und" is ISO-special for undetermined, which is confusing for users (especially as "und" is also a word in german). Generally I think some of these specials are rarely known, e.g who knows that "zxx" is "no linguistic content; not applicable".
Therefore I believe having these specials displayed prominently in display titles is wrong. I get that there is still value in displaying this information - it's technical data that may be of interest to more technical users. Hence I did **not** remove language codes displaying from metadata - just from the …
> Hide ISO 639-2 special codes in display titles

- Jellyfin.Api/Controllers/DynamicHlsController.cs
- Jellyfin.Api/Controllers/HlsSegmentController.cs
- Jellyfin.Api/Controllers/ImageController.cs
- Jellyfin.Api/Controllers/VideosController.cs
- Jellyfin.Api/Helpers/AudioHelper.cs
- Jellyfin.Api/Helpers/FileStreamResponseHelpers.cs
Removing this allows HTTP 206 Partial Content responses and lets some clients(popcorn hour namely) play static videos from JF.
> Remove special HTTP HEAD processing

- Emby.Server.Implementations/Data/BaseSqliteRepository.cs
- Emby.Server.Implementations/Data/ManagedConnection.cs
This is an atempt to reduce the number of locks reported on #7237 by having a connection that can be shared among the threads without a semaphore
> chore: Add a read only connection for routes like Shows/NextUp

- CONTRIBUTORS.md
- Emby.Naming/Common/NamingOptions.cs
**Changes**
https://github.com/jellyfin/jellyfin/commit/719b707281b078405daeea90811c2b4d7b40d624 removed `.strm` as an allowed extension for videos. As a result, `.strm` files are ignored during a library scan.
I wasn't able to figure out if this was an accident or done on purpose. If it wasn't an accident, please disregard this PR.
> Readd .strm as an allowed extension for videos

- Emby.Server.Implementations/Data/BaseSqliteRepository.cs
- Emby.Server.Implementations/Data/ManagedConnection.cs
Reverts jellyfin/jellyfin#7240
```
[23:15:02] [ERR] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
Locked: SQLitePCL.pretty.SQLiteException: database table is locked: TypedBaseItems
at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
at SQLitePCL.pretty.StatementImpl.MoveNext()
at Emby.Server.Implementations.Data.SqliteItemRepository.<>c__DisplayClass33_0.<SaveImages>b__0(IDatabaseConnection db)
at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.<RunInTransaction>b__0(IDatabaseConnection db)
at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
at …
```
> Revert "chore: Add a read only connection for routes like Shows/NextUp"

- CONTRIBUTORS.md
- MediaBrowser.Model/Entities/MediaStream.cs
**Changes**
There are different profiles for DTS. For example, both DTS and DTS-HD
MA use the same codec, but provide a different profile.
With this PR, the different profiles can be displayed in e.g. Jellyfin Web (with no changes required there).
Below is an example file showing both an audio track with an DTS and an DTS-HD MA profile. Both use the DTS codec. Without this PR, both audio tracks would only show up as "DTS".
> Let the UI show which DTS profile is in use

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
- tests/Jellyfin.MediaEncoding.Tests/Probing/ProbeResultNormalizerTests.cs
**Changes**
The same fixes from https://github.com/jellyfin/jellyfin/pull/7120, but instead this includes some tests to ensure that the logic is correct. Was unsure on how I could push some commits to the existing branch so I made a new PR completely.
I could see why we wanted some tests, as the math conversion did seem quite complex, but after some testing it looks to be functioning correctly.
I broke out the method to make it testable, as the main method this logic sat in would require quite a lot of mocking which I am not too comfortable doing just yet, this stuff is still kinda black magic to me as I haven't ever written anything in C#.
**Issues**
No issues here, just fixing some ffprobe errors I was having previously from https://github.com/jellyfin/jellyfin/pull/7041
> ProbeResultNormalizer: fix framerate compare + tests

- MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
External audio files weren't getting picked up on my test server due to `currentStreams` being reassigned instead of modified.
**Changes**
- Add `Distinct()` call for subtitle external files now that mks containers are supported
- Simplify logic for adding external audio file list
- Revert back to modifying `currentStreams` as expected by the caller of the `AddExternal*Async` methods
> Match external sub/audio stream adding logic

- Jellyfin.Api/Controllers/ItemRefreshController.cs
**Changes**
- Restrict item refreshing to administrators
- This fixes #6815
- jellyfin-web already checks if the user is an administrator for showing the button to refresh items in the item context menu
- Rename the operation for item refreshing to "RefreshItem" (was "Post") - this change is for generated api clients.
**Issues**
Fix #6815
> Restrict item refreshing to administrators

- MediaBrowser.Model/Dlna/StreamBuilder.cs
Fixes edgecase tests.
Reverts change suggested here: https://github.com/jellyfin/jellyfin/pull/7325#discussion_r820286509
> Revert using Math.Clamp

- Jellyfin.Api/Controllers/UserViewsController.cs
**Changes**
Removed a check in the GetUserViews operation that modifies the query based on a client name that we don't use anywhere[^1]
[^1]: https://cs.github.com/?scopeName=All+repos&scope=&q=org%3Ajellyfin+%22emby+rt%22
**Issues**
> Remove check for non-existent "emby rt" client in UserViewsController

- Jellyfin.Api/Controllers/DashboardController.cs
- Jellyfin.Api/Controllers/UserViewsController.cs
- tests/Jellyfin.Server.Integration.Tests/Controllers/DashboardControllerTests.cs
Looking at the openapi file (unstable from march 13th) I noticed a few endpoints that shouldn't be unauthenticated. I'm quite sure the API calls from jf-web are authenticated but if it is not we can always revert the change in a later 10.8 beta.
**Changes**
- Add authorization attribute to GetConfigurationPages
- Add authorization attribute to UserViewsController
**Issues**
> Add missing authorization attributes

- CONTRIBUTORS.md
- Emby.Server.Implementations/Library/MediaSourceManager.cs
When making an API call that requests `MediaSources` with the `fields` field, the `supportsTranscoding` property does not report false even if the user doesn't have permission to transcode (e.g. `/Users/{userId}/Items`). On the contrary other requests like `/Items/{itemId}/PlaybackInfo` give back the expected result.
**Changes**
Always return the expected value by checking the users transcoding permission in `GetStaticMediaSources()` as well.
> Fix supportsTranscoding not reflecting user permissions sometimes

- MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs
Fixes https://github.com/jellyfin/jellyfin/issues/7475
All possible responses aren't documented, but the example in the schema shows "Ended".
I confirmed that "Canceled" is also a valid status using the api.
https://developers.themoviedb.org/3/tv/get-tv-details
> tmdb - update available series end status

- Emby.Dlna/DlnaManager.cs
- Emby.Dlna/Main/DlnaEntryPoint.cs
Changes the DLNA description XML requests to obey profile-specific information rather than using the default profile. Also changes the UUID to be formatted in the correct style, allowing the server to be properly detected by more clients.
> Change DLNA description requests to obey profiles, format UUID correctly

- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
10.7
```c#
"TranscodeReason": {
"enum": [
"ContainerNotSupported",
"VideoCodecNotSupported",
"AudioCodecNotSupported",
"ContainerBitrateExceedsLimit",
"AudioBitrateNotSupported",
"AudioChannelsNotSupported",
"VideoResolutionNotSupported",
"UnknownVideoStreamInfo",
"UnknownAudioStreamInfo",
"AudioProfileNotSupported",
"AudioSampleRateNotSupported",
"AnamorphicVideoNotSupported",
"InterlacedVideoNotSupported",
"SecondaryAudioNotSupported",
"RefFramesNotSupported",
"VideoBitDepthNotSupported",
"VideoBitrateNotSupported",
"VideoFramerateNotSupported",
"VideoLevelNotSupported",
"VideoProfileNotSupported",
"AudioBitDepthNotSupported",
"SubtitleCodecNotSupported",
"DirectPlayError"
],
"type": "string"
},
```
10.8 (current master)
```c#
"TranscodeReason": {
"enum": [
[
"ContainerNotSupported"
], …
```
> Fix OpenAPI spec generation for TranscodeReason

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Improve fps for cuda tonemap in sw decoding, avoid second copy if subtitle is not applied.
AV1 4K HDR -> 1080p SDR:  62fps -> 85fps with Zen2 8c16t+gtx1650
> Improve fps for cuda tonemap in sw decoding

- Jellyfin.Api/Helpers/TranscodingJobHelper.cs
- MediaBrowser.Controller/MediaEncoding/IAttachmentExtractor.cs
- MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
**Changes**
Attachments now also get extracted from external subtitles when burning subtitles.
This means that fonts can be attached to an external .mks file otherwise containing only the subtitles and the subtitles will get burned with the correct fonts from that file or the main media file.
**Issues**
Comment under #7275
> Add extracting attachments from external subs

- MediaBrowser.Model/Dlna/StreamBuilder.cs
- MediaBrowser.Model/Dlna/TranscodingProfile.cs
The idea is to add some control over the transcoding profile separately from the direct profiles.
For example, no resolution limit for DirectPlay, but no more screen size for transcoding.
Ideally, we need global conditions as well.
**Changes**
Add TranscodingProfile conditions
> Add TranscodingProfile conditions

- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
- MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs
**Changes**
don't attempt to run ffprobe on the .strm file itself in MediaInfoResolver,
in MediaEncoder, use a memorystream instead of the basestream because for some reason this is instrumental in ffprobing the remote media successfully
**Issues**
Fixes #7438
> allow strm probe to succeed

- MediaBrowser.Model/Dlna/StreamBuilder.cs
- MediaBrowser.Model/Dlna/StreamInfo.cs
Replaces #7486 by preventing the streambuilder from returning the file path.
That should never ever happen anway.
Also moves some logging to Debug an fixes a typo.
> Fix DLNA DirectPlay

- Jellyfin.Server/Program.cs
- MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs
Using P/Invoke might look scary, but since we're limited to unices and libc, this should work pretty reliably.
**Changes**
When new configuration parameter `kestrel:socketPermissions` is set (e.g. `0777`), try to change the unix socket's permissions to its value.
**Issues**
Fixes #5311
> Add option to change unix socket permissions

- Emby.Server.Implementations/Library/LibraryManager.cs
**Changes**
- Update name so media paths store to correct library
**Issues**
@Shadowghost
> When adding a library with an already existing name on jf-web the library gets created but all folders you assigned to it will be added to the existing one (at least the UI says so). But the existing library edit dialogue does only show the original folder
> The new created library has the counter added (Like Music -> Music 2), so at least that part works as intended
> Fix media path saving to wrong library when name duplicated

- MediaBrowser.Controller/Resolvers/ResolverPriority.cs
With some changes in 10.8 it's not easy to get a plugin defined resolver prioritized anymore. Adding a new level which is not used by the server makes this a lot easier. Technically this is a feature addition and technically we don't support it, but it would make me happy to get this into 10.8... :)
**Changes**
- Add new priority level to ResolverPriority for plugins
**Issues**
> Add new priority level to ResolverPriority for plugins

- MediaBrowser.Model/Dlna/StreamBuilder.cs
- tests/Jellyfin.Model.Tests/Dlna/StreamBuilderTests.cs
- tests/Jellyfin.Model.Tests/Test Data/MediaSourceInfo-no-streams.json
Fixes playback attempts where the source doesn't provide the streams the user is attempting to playback, typically from internet sources.
> Allow media without streams to playback 

- Emby.Server.Implementations/Sorting/IndexNumberComparer.cs
- Emby.Server.Implementations/Sorting/ParentIndexNumberComparer.cs
- tests/Jellyfin.Server.Implementations.Tests/Sorting/IndexNumberComparerTests.cs
- tests/Jellyfin.Server.Implementations.Tests/Sorting/ParentIndexNumberComparerTests.cs
Given an album with over 16 tracks with null disc/track fields the sorters would fail because comparing null values tried to change order differently when called (a,b) vs (b,a).
**Changes**
- Add check so nulls will result in valid sort
**Issues**
Fixes #7533
Fixes jellyfin/jellyfin-web#3532
> Fix album index sorts

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Use a larger frame pool as per https://trac.ffmpeg.org/wiki/Hardware/QuickSync
**Issues**
Fixes https://github.com/jellyfin/jellyfin-ffmpeg/issues/95
> Fix PGS burn-in on certain iGPU such as Iris Plus 655

- Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs
- Jellyfin.Api/Controllers/ConfigurationController.cs
- Jellyfin.Server/Filters/AdditionalModelFilter.cs
- MediaBrowser.Common/Configuration/IConfigurationManager.cs
**Changes**
- Parameterize request body (so it is visible to Swashbuckle)
- Manually add types accepted by configurations to OpenAPI documentation.
Areas that could use some feedback:
- The controller method is no longer async - is this a problem? Is there a better way to accomplish this? I'm a Java EE developer by day, so the C#/dotnet style of handling this is a bit foreign to me. I'm happy to implement suggestions.
- The manual addition of the types to OpenAPI seems a bit shady, but even with @crobibero's suggestion of using Swashbuckle's polymorphism/inheritance features I can't seem to find a solution that allows me to specify an interface as the parameter type for the request body. This step seems to be a prerequisite to actually utilizing the polymorphism/inheritance features …
> Fix NamedConfiguration API Generation

- MediaBrowser.Providers/Manager/ProviderManager.cs
`ImageSaver` uses `contentType` to determine the file extension to use when saving the image.
Some IPTV/EPG providers serve images that report as types that don't map to extensions (such as `binary/octet-stream`), resulting in no channel icon and logged exceptions every time one is downloaded and can't be saved.
This may be a more general fix for the tvheadend workaround on line 177, but I have been unable to reproduce that case on my dev machine to verify.
**Changes**
- Add fallback for image downloads with bad MediaType
> Add fallback for image downloads with bad reported MediaType

- Emby.Naming/Common/NamingOptions.cs
`.mp2` is commonly used for MPEG-1 audio layer 2 audio files and I have never seen it used as a file extension for video.
* [Reddit](https://www.reddit.com/r/jellyfin/comments/u0dytw/1080beta1_might_be_handled_wrong/)
> Remove mp2 from video file extensions

- MediaBrowser.Common/Extensions/BaseExtensions.cs
|                       Method |     Mean |   Error |  StdDev |  Gen 0 | Allocated |
|----------------------------- |---------:|--------:|--------:|-------:|----------:|
|                          Old | 795.1 ns | 5.90 ns | 4.61 ns | 0.0029 |     312 B |
| HashDataInsteadOfComputeHash | 396.1 ns | 1.36 ns | 1.13 ns | 0.0014 |     152 B |
|      StackallocedDestination | 395.8 ns | 1.80 ns | 1.60 ns | 0.0014 |     152 B |
|                   RentBuffer | 498.8 ns | 3.35 ns | 2.97 ns |      - |      40 B |
Tested multiple possible speedups, in the end the simplest of them all won
> Optimize GetMD5 function

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Fix the wrong external audio map index if text subtitle exists
**Issues**
Fixes the `Invalid input file index: 2.` error.
> Fix the wrong external audio map index if text subtitle exists

- Emby.Server.Implementations/Emby.Server.Implementations.csproj
**Changes**
- Update dependency Jellyfin.XmlTv to version 10.8.0
Pulls in jellyfin/Jellyfin.XmlTv#9 so the element following a category element won't be skipped.
> Update Jellyfin.XmlTv to 10.8.0

- Emby.Server.Implementations/Session/SessionManager.cs
It's very helpful to know where the item started playback from.
> Add missing properties to PlaybackStart, PlaybackStop

- MediaBrowser.XbmcMetadata/Savers/ArtistNfoSaver.cs
- MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs
- MediaBrowser.XbmcMetadata/Savers/EpisodeNfoSaver.cs
**Changes**
Writing global date to info files and not local date. In timezones with a negative UTC offset, the call to `.ToLocalTime()` would have resulted in a date one day before the actual date (see issue).
**Issues**
Fixes #7271
> Write UTC Date to .nfo files

- MediaBrowser.Model/Configuration/ServerConfiguration.cs
Quick Connect is a safe way to authenticate new devices, and will be the default authentication method in the next Android TV app version (using a password will require an additional step). This PR enables the functionality by default. AFAIK this only affects new installations?
**Changes**
- Enable Quick Connect by default
**Issues**
> Enable Quick Connect by default

- Emby.Server.Implementations/Dto/DtoService.cs
In 10.8, the `LocalTrailerCount` property is showing the count of local and remote trailers combined.
**Changes**
Ensure `LocalTrailerCount` contains count of local trailers only.
> Correct LocalTrailerCount in API

- tests/Jellyfin.Server.Implementations.Tests/QuickConnect/QuickConnectManagerTests.cs
#7624 broke some unit tests and we missed it (I'm guessing we've gotten too used to ignoring Check Backport failing).
**Changes**
- Set initial state on quick connect disabled tests
> Fix quick connect tests

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
Default h264 level to 5.1.
https://en.wikipedia.org/wiki/Advanced_Video_Coding#Levels
**Issues**
h264 4k 30fps requires at least level 5.1 otherwise it will break on safari fmp4.
> Fix H264 level on safari fmp4

- debian/control
**Changes**
Ubuntu 22.04 has intentionally moved to [`libssl3`](https://packages.ubuntu.com/jammy/libssl3): https://discourse.ubuntu.com/t/openssl-3-0-transition-plans/24453
IIRC dotnet6 should support libssl3.
**Issues**
Should fixes:
https://www.reddit.com/r/jellyfin/comments/u8y3pj/jellyfin_fails_to_start_with_ubuntu_2204_lts/
https://www.reddit.com/r/jellyfin/comments/ua0d30/unable_to_install_jellyfin_from_the_ubuntu_repo/
> Add libssl3 as an alternative dependency for Ubuntu 22.04 LTS

- MediaBrowser.Model/Entities/ProviderIdsExtensions.cs
The key of provider IDs can be set to arbitrary strings from external sources like NFOs.
To properly handle cases where these strings resemble internally available a value in the `MetadataProvider` enum we should use those values and not the string for best compatibility.
> Prefer MetadataProvider enum as provider id key over arbitrary strings

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
- Emby.Server.Implementations/Library/MediaSourceManager.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
- MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
Strm files are special:
* preserve non-external streams between scans
* add external streams before adding internal streams
* always recalculate the stream index of the selected stream within its source file 
* fix transcoding if external subtitle or audio isn't a single stream but a a stream in a container
We need to add the external streams before adding the internals because otherwise the index submitted by e.g. stream selection on jf-web would be wrong if the initial scan of the file did not already populate the internal streams or if the file changed. For strm files that's always the case if the file was never played before since probe on scan is skipped for linked remote files.
> Properly handle stream addition and removal for strm use cases

- Jellyfin.Api/Controllers/DynamicHlsController.cs
**Changes**
- Fix the disordered color in Dolby Vision remuxing on Safari
https://github.com/jellyfin/jellyfin-ffmpeg/pull/144
If the patched `jellyfin-ffmpeg` is not used, it will automatically fall back to `hev1`.
> Fix the disordered color in Dolby Vision remuxing on Safari

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Opus only supports specific sampling rates, so we need to translate the requested sampling rate to a supported one.
This PR upsamples to the next higher available sampling rate
Fixes #7635
> Respect limited opus sampling rates when building trancoding command

- MediaBrowser.Model/Dlna/StreamBuilder.cs
- tests/Jellyfin.Model.Tests/Dlna/StreamBuilderTests.cs
- tests/Jellyfin.Model.Tests/Test Data/DeviceProfile-Tizen3-stereo.json
- tests/Jellyfin.Model.Tests/Test Data/DeviceProfile-Tizen4-4K-5.1.json
The checks currently always returned the reason of the first failed DirectPlayProfile but that can be irritating because there may be other profiles which had reasons less resource intense to fix.
This PR fixes that behaviour by actually using the calculated `Rank` property.
I also renamed some variables and methods to properly reflect what they do.
> Fix streambuilder reasons for direct playback checks

- Emby.Naming/Common/NamingOptions.cs
- tests/Jellyfin.Naming.Tests/TV/EpisodeNumberTests.cs
**Changes**
The capture group would only take up to 3 digits. When the episode count would get to 1000, it would only take out 100. I've increased the capture group to 4 digits and verified that it fixed the issue by adding some inline data to `GetEpisodeNumberFromFileTest` and also verifying that it worked on my local.
**Issues**
#7656
> Fix to allow for episode numbering over 999 in certain scenarios

- Emby.Server.Implementations/IO/ManagedFileSystem.cs
**Changes**
I have a single `./Movies` directory that contains symlinks to many
other directories, some of which are in shared paths. Other daemons
sometimes overwrite permissions on these paths and prevent Jellyfin from
being able to scan. Because this exception is unhandled within a LINQ
statement it non-deterministically kills metadata refresh for my entire Movies
library.
Running with this patch has allowed me to at least add + scan for
movies in directories that Jellyfin can currently access and gives me
some notification of the symlinks failing due to permissions errors.
**Issues**
May be related to #7130
> Don't let permission denied kill library scans

- README.md
**Changes**
Use the space in the Matrix chat link instead of the old community one as communities are deprecated and Jellyfin has an official space (see https://jellyfin.org/contact/).
> Fix Matrix badge link to space instead of community

- Jellyfin.Api/Controllers/ItemsController.cs
- Jellyfin.Api/Controllers/TrailersController.cs
I'm assuming this is in scope for a bugfix, if not I can rebase it to master.
**Changes**
- Add bindings for tv program flags (isMovie, isKids, etc)
- Fix misspelling of "delimited"
**Issues**
Fixes #7204
> Support searching with tv program filters

- Emby.Server.Implementations/Session/SessionManager.cs
Copy-paste from https://github.com/jellyfin/jellyfin/blob/ff4f624850bc7d5024feaee93ffe52c07c27d172/Emby.Server.Implementations/Session/SessionManager.cs#L676-L679
**Changes**
Clear `TranscodingInfo` if method changed
**Issues**
`TranscodingInfo` in the session isn't cleared when switching from `Transcoding` to `DirectPlay`.
> Clear TranscodingInfo if play method changed

- MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/AudioResolverTests.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/MediaInfoResolverTests.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/SubtitleResolverTests.cs
**Changes**
- Exclude streams with mismatched types in external files
**Issues**
PGS subtitles in Mka container were incorrectly marked as audio.
They should exist in Mks, so exclude them during scanning.
> Exclude streams with mismatched types in external files

- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Jellyfin.Api/Jellyfin.Api.csproj
- Jellyfin.Server/Jellyfin.Server.csproj
- MediaBrowser.Model/MediaBrowser.Model.csproj
- MediaBrowser.Providers/MediaBrowser.Providers.csproj
- tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
- tests/Jellyfin.Common.Tests/Jellyfin.Common.Tests.csproj
- tests/Jellyfin.Controller.Tests/Jellyfin.Controller.Tests.csproj
- tests/Jellyfin.Dlna.Tests/Jellyfin.Dlna.Tests.csproj
- tests/Jellyfin.Extensions.Tests/Jellyfin.Extensions.Tests.csproj
- tests/Jellyfin.MediaEncoding.Hls.Tests/Jellyfin.MediaEncoding.Hls.Tests.csproj
- tests/Jellyfin.MediaEncoding.Keyframes.Tests/Jellyfin.MediaEncoding.Keyframes.Tests.csproj
- tests/Jellyfin.MediaEncoding.Tests/Jellyfin.MediaEncoding.Tests.csproj
- tests/Jellyfin.Model.Tests/Jellyfin.Model.Tests.csproj
- tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj
- tests/Jellyfin.Networking.Tests/Jellyfin.Networking.Tests.csproj
- tests/Jellyfin.Providers.Tests/Jellyfin.Providers.Tests.csproj
- tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj
- tests/Jellyfin.Server.Integration.Tests/Jellyfin.Server.Integration.Tests.csproj
- tests/Jellyfin.Server.Tests/Jellyfin.Server.Tests.csproj
- tests/Jellyfin.XbmcMetadata.Tests/Jellyfin.XbmcMetadata.Tests.csproj
Ensures all dependencies are in line with what is currently in master, besides OptimizedPriorityQueue.
That PR was closed last year without comment, so unsure what the reason was (https://github.com/jellyfin/jellyfin/pull/5329)
Note that the following were not applied as they have breaking changes:
https://github.com/jellyfin/jellyfin/pull/7658
https://github.com/jellyfin/jellyfin/pull/7345
> Backport all dependency updates

- Jellyfin.Server/Program.cs
- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#unacceptable-pattern
Regex used:
```
await using \(.+\)
\W+await using
```
> IAsyncDisposable is one big pitfall

- Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
**Changes**
Fix the PNG image decoding issue in Skia by upgrading to 2.88.1-preview.1
**Issues**
Regression was introduced in 2.88.0: https://github.com/mono/SkiaSharp/issues/2095
> Fix the PNG image decoding issue in Skia

- MediaBrowser.Model/Configuration/EncodingOptions.cs
**Changes**
Enables on demand keyframe extraction for the mkv container. It's reasonably fast (completely metadata-based) and we'll get more feedback by enabling it by default
> chore: enable on demand keyframe extraction for mkv

- Emby.Dlna/Configuration/DlnaOptions.cs
- Jellyfin.Api/Attributes/DlnaEnabledAttribute.cs
- Jellyfin.Api/Controllers/DlnaServerController.cs
**Changes**
Disable DLNA by default. It does not support authentication, but it is LAN only, so the security implications aren't as big as UPnP, but it still seems unnecessary to enable by default.
Also added an ActionFilter to handle the "toggling" of the DLNA controller instead of the previous `if` mess.
> chore: disable DLNA by default

- MediaBrowser.Model/Session/GeneralCommand.cs
**Changes**
- Fix navigation buttons in web app. (API call in `jellyfin-web` currently returns a 400 error.)
This fix can be back-ported to the 10.8.x stable version and I have verified it works as such.
> Prevent 400 error when using navigation buttons.

- Jellyfin.Api/Controllers/SearchController.cs
- src/Jellyfin.Extensions/ReadOnlyListExtension.cs
Fixes https://github.com/jellyfin/jellyfin/issues/7883
Extension method was added because there is an analyzer to not use the Linq method
> Switch to FirstOrDefault extension

- Jellyfin.Api/Controllers/DynamicHlsController.cs
- src/Jellyfin.MediaEncoding.Hls/Playlist/CreateMainPlaylistRequest.cs
- src/Jellyfin.MediaEncoding.Hls/Playlist/DynamicHlsPlaylistGenerator.cs
**Changes**
The original keyframes were used for transcodes, but that is not valid.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/6957
> fix: only use keyframes when remuxing video

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Web**
- https://github.com/jellyfin/jellyfin-web/pull/3701
**Changes**
- Remove MPEG4 hwaccel from AMF, which is not supported by ffmpeg
**Issues**
Fixes: #7922
> Remove MPEG4 hwaccel from AMF

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Reduce memory copy-back on swdec + opencl tonemap + amf encoding pipeline.
4k AV1 to 4k HEVC transcoding: **48fps -> 56fps** on APU(Radeon Graphics 8CU)
- Set the target device of hwupload explicitly to avoid confusion.
Only minor changes, so this should be considered a backport?
> Improve AMF tonemap speed when using sw decoding

- MediaBrowser.Controller/Providers/ImageRefreshOptions.cs
- MediaBrowser.Providers/Manager/MetadataService.cs
**Changes**
Skip the image saving if `IsReplacingImage` is false. Also removed some unused code, which may or may not be re-introduced by #5884
**Issues**
Fixes #7836
> fix: respect the image refresh options when parsing remote images from NFO

- Jellyfin.Api/Helpers/DynamicHlsHelper.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Fix the int overflow issue in encoder bufsize,
cap the max target bitrate to int.MaxValue/2 = 1073741823, which is more than enough for any common videos.
- Fix the map index of external audio
**Issues**
Fixes https://github.com/jellyfin/jellyfin-plugin-tvheadend/issues/59
FIxes https://github.com/jellyfin/jellyfin/issues/7942
> Fix the int overflow issue and the wrong map index of external audio

- Emby.Server.Implementations/Library/MediaStreamSelector.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/MediaStreamSelectorTests.cs
Cherry-pick of #7682 into 10.8.z, already merged to master so intentionally not tagged for backport.
**Changes**
- Fix default audio stream selection ignoring type
**Issues**
- Fixes #7752
> Track selector fix

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
- MediaBrowser.Model/Configuration/EncodingOptions.cs
**Web**
https://github.com/jellyfin/jellyfin-web/pull/3714
**Changes**
- Brighter VPP tone-mapping on Intel
- Add two extra options for VPP TM: brightness and contrast
**Issues**
Fixes: https://github.com/jellyfin/jellyfin/issues/6624
> Brighter VPP tone-mapping on Intel

- MediaBrowser.MediaEncoding/Subtitles/AssWriter.cs
- MediaBrowser.MediaEncoding/Subtitles/SsaWriter.cs
- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
- MediaBrowser.Model/MediaInfo/SubtitleFormat.cs
**Changes**
Properly convert subtitles to subrip if requested.
**Issues**
Fixes #7958
Fixes https://github.com/jellyfin/Swiftfin/issues/417
> Fix subtitle encoder if subrip is requested

- MediaBrowser.Providers/MediaInfo/AudioResolver.cs
- MediaBrowser.Providers/MediaInfo/FFProbeProvider.cs
- MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs
- MediaBrowser.Providers/MediaInfo/SubtitleResolver.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/AudioResolverTests.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/MediaInfoResolverTests.cs
- tests/Jellyfin.Providers.Tests/MediaInfo/SubtitleResolverTests.cs
**Changes**
- Catch external streams exceptions (invalid or empty external streams will break the main video stream)
**Issues**
Closes #7710
> Catch external streams exceptions

- deployment/Dockerfile.fedora.amd64
- fedora/Makefile
- fedora/jellyfin.env
- fedora/jellyfin.spec
* Rewrite Fedora `Makefile` so we don't need to constantly update with every new Fedora release. This is especially useful when Fedora and Jellyfin release cycles don't line up. Version selection is as follows:
1. TARGET environment variable, which is currently used already
2. Currently running Fedora version
3. Hardcoded Fallback version that can be updated occasionally
* Use ~~`latest`~~ `36` Fedora image in Fedora Docker builds
* ~~Same reasoning as the Makefile, we don't need to constantly update ourselves when a base image tag can do that for us. The Fedora base image is maintained by the Fedora project (and from my understanding mostly automated), so we don't need to worry about this not being updated anytime soon.~~
* ~~`latest` always points to the current *released* Fedora …
> Rework Fedora build

- Jellyfin.Api/Controllers/DynamicHlsController.cs
- Jellyfin.Api/Controllers/VideosController.cs
- Jellyfin.Api/Helpers/TranscodingJobHelper.cs
- Jellyfin.Api/Models/StreamingDtos/StreamState.cs
- MediaBrowser.Controller/MediaEncoding/JobLogger.cs
We still need to modify ffmpeg itself for better implementation in the future.
Or utilize the `realtime` filter to limit the transcoding speed.
**Changes**
- Fix the broken transcoding throttler
- Re-enable it for HWA (tested on Intel/AMD/Nvidia)
**Issues**
HLS and progressive StreamStates are always disposed prematurely.
> Fix the broken transcoding throttler

- debian/conf/jellyfin-sudoers
- fedora/README.md
- fedora/jellyfin.sudoers
Fixes #8037
We no longer mount ISOs nor do we support plugins mounting them. All playback and probing related handling is done by ffmpeg or other tools directly accessing the ISO without the OS being involved.
> Remove mount and unmount permissions for jellyfin group from sudoers

- MediaBrowser.Controller/Entities/TV/Series.cs
- MediaBrowser.Model/Entities/MetadataProvider.cs
**Changes**
This is an universal solution for plugins to override how series are merged.
The reason to override is so we can set the same provider id on multiple items without merging them, while using another id for merging them. Having an (optional) provider id not tied to any online database allows plugins to use their own rules for merging series.
**Issues**
Follow up PR for #7497
> Add escape hatch for Series merging

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
Change allow higher opus, vorbis transcode bitrates.
**Issues**
Vorbis, Opus is always capped to the minimum 128kbit even for 6/8 channel audio, so just handle those codecs like all the other transcode audio formats.
> Change allow higher opus, vorbis transcode bitrates

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- fix copy&paste error for `requestedRangeTypes` preventing stream copy
- fix invalid _(-1)_ SubtitleStreamIndex preventing stream copy
Negative/invalid SubtitleStreamIndex values should also be ignored and allow stream copy.
fixes #8070 
fixes #7880 _(probably)_
> fix copy&paste error for requestedRangeTypes preventing stream copy

- MediaBrowser.Common/Configuration/EncodingConfigurationExtensions.cs
**Changes**
Move transcodes to be under CachePath instead of ProgramDataPath.
Since transcodes are ephemeral (they're cleaned up periodically and recreated if they don't exist), they're more like cache data than program data. Systems can (and oftentimes do) have the cache directory on a different disk, use a different type of file system, or have a different backup policy for the cache path because it contains ephemeral data.
**Issues**
This PR doesn't exactly solve the following issues, but it is related to them, as it changes jellyfin to use a more appropriate path for these temporary files which makes it more likely that the system will be configured to handle this data more appropriately avoiding these issues:
https://github.com/jellyfin/jellyfin/issues/4893 …
> Move transcodes to be under CachePath

- Emby.Naming/Emby.Naming.csproj
- Jellyfin.Data/Jellyfin.Data.csproj
- MediaBrowser.Common/MediaBrowser.Common.csproj
- MediaBrowser.Controller/MediaBrowser.Controller.csproj
- MediaBrowser.Model/MediaBrowser.Model.csproj
- SharedVersion.cs
- build.yaml
- debian/changelog
- debian/metapackage/jellyfin
- fedora/jellyfin.spec
- src/Jellyfin.Extensions/Jellyfin.Extensions.csproj
Bump version for next release to be 10.9.0
All I did was run `./bump-version 10.9.0`
> Jellyfin 10.9.0

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
Fixes the ffmpeg parameters for rtsp over tcp streams. The previous parameters caused udp streams to be the only ones supported. 
Related ffmpeg mailing list post: https://lists.ffmpeg.org/pipermail/ffmpeg-user/2017-January/034958.html
**Issues**
Fixes #7630
> Fix support for rtsp streams over tcp

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
Bind @userid only when it's in the statement
**Changes**
This commit fixes a case where SqliteItemRepository attempts to bind @userid even when such parameter may not appear in the query
**Issues**
https://github.com/jellyfin/jellyfin/issues/8141
> Bind @userid only when it's in the statement

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Fix intel dx11-ocl interop taking too long to initialize on windows
**Issues**
Without this, QSV+OpenCL filtering takes 10s or longer to initialize. With this, it will be reduced to 1~3s.
Newer iGPU such as Xe graphics is affected.
> Fix intel dx11-ocl interop taking too long to initialize on windows

- MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs
**Changes**
Change music album refresh to not refresh child playlists
Note: playlists created in Jellyfin containing songs from an album are not included in `items` and are not being refreshed. So this change should not affect custom playlists
**Issues**
Fixes #3088
> Don't refresh playlists on album refresh

- Emby.Server.Implementations/Library/LibraryManager.cs
- MediaBrowser.Controller/Library/ILibraryManager.cs
This was removed in https://github.com/jellyfin/jellyfin/pull/7326 but I think it should exist
> Add back library scan from library manager

- Emby.Photos/Emby.Photos.csproj
- Emby.Server.Implementations/Emby.Server.Implementations.csproj
- Jellyfin.Api/Jellyfin.Api.csproj
- Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj
- Jellyfin.Server/Jellyfin.Server.csproj
- deployment/Dockerfile.centos.amd64
- deployment/Dockerfile.fedora.amd64
- deployment/Dockerfile.ubuntu.amd64
- deployment/Dockerfile.ubuntu.arm64
- deployment/Dockerfile.ubuntu.armhf
- tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
- tests/Jellyfin.Server.Integration.Tests/Jellyfin.Server.Integration.Tests.csproj
- tests/Jellyfin.Server.Tests/Jellyfin.Server.Tests.csproj
https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.8/6.0.8.md
Also updates [TagLibSharp](https://github.com/mono/taglib-sharp/releases/tag/TaglibSharp-2.3.0.0) and [sharpcompress](https://github.com/jellyfin/jellyfin/pull/8196)
> update to dotnet 6.0.8

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.Controller/MediaEncoding/ISubtitleEncoder.cs
- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
Subtitle character set determination requires the subtitle to not be in a container. Timestamps should also not be reset to start at zero when extracting subtitles.
**Changes**
* Extract subtitle from external subtitle container (mks) before processing it
* Do not reset Subtitle start time to zero when extracting
Fixes #8157
> Extract external subs from container before determining characterset

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
- debian/rules
- deployment/Dockerfile.docker.amd64
- deployment/Dockerfile.docker.arm64
- deployment/Dockerfile.docker.armhf
- deployment/build.linux.amd64
- deployment/build.linux.amd64-musl
- deployment/build.linux.arm64
- deployment/build.linux.armhf
- deployment/build.macos
- deployment/build.portable
- deployment/build.windows.amd64
- fedora/jellyfin.spec
**Changes**
Instead of a single quoted `-p` argument set, specify each individually to avoid the problems with upstream `dotnet`.
**Issues**
Fixes #8245
> Use separate args for dotnet publish commands

- Emby.Server.Implementations/TV/TVSeriesManager.cs
- Jellyfin.Api/Controllers/TvShowsController.cs
- MediaBrowser.Model/Querying/NextUpQuery.cs
The seriesId parameter required an item id or null. Item ids are always guid.
**Changes**
- Use guid for seriesId API parameter
**Issues**
> Use guid for seriesId API parameter

- CONTRIBUTORS.md
- Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
Prevent a directory with a single video file to be detected as a movie directory when the library type is "Photos". Closes jellyfin/jellyfin#7825
Signed-off-by: Utku Ozdemir <uoz@protonmail.com>
**Changes**
With this change, directories will not be displayed as videos when they contain a single video files inside them - they will be displayed as directories. This makes the behavior for video files consistent with image files.
**Issues**
#7825
> fix: single video folder during photos lib scan

- CONTRIBUTORS.md
- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
**Changes**
The PR #7153 increases subtitle extraction operation timeout from 5 minutes to 30 minutes (to address long-running extractions due for example to a slow storage).
But such PR changes the timeout only in method that manage subtitle conversion and not in the method that manage subtitle extraction.
This PR completes the change.
**Issues**
Addresses #6672
Complete PR #7153
> Increase (really) timeout for subtitle extraction to 30min

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
**Changes**
This changes the order that analyze duration values are applied so media source values take precedence over the ffmpeg environment variable/setting.
**Issues**
Fixes the long delay when starting a live tv stream by honoring the analyze duration set at the media source level that has been ignored since 10.8.1.
Related discussion: https://github.com/jellyfin/jellyfin/issues/3930#issuecomment-1166172969
Related PR: https://github.com/jellyfin/jellyfin/pull/7828
> Fix ffmpeg analyze duration env var taking priority over media source

- Jellyfin.Api/Controllers/SearchController.cs
- MediaBrowser.Model/Search/SearchHint.cs
_Untested, I don't have a proper test environment_
**Changes**
- Fix operation name in SearchController
Operation names should be unique across the application. The search thingy used `get` as name which is not that unique of a name
- Correct nullability for SearchHint
- Basically looked at the nullability of BaseItemDto (which all info is copied from) and what's conditionally set in the controller to determine nullability
- Use BaseItemKind enum in SearchHint
- GetClientTypeName returns basically the same but as a string
**Issues**
> Fix operation name in SearchController and correct nullability for SearchHint

- Emby.Server.Implementations/LiveTv/TunerHosts/M3UTunerHost.cs
- MediaBrowser.Model/LiveTv/TunerHostInfo.cs
**Changes**
- Added IgnoreDts to TunerHostInfo
- Added IgnoreDts checkbox to M3U tuner configuration page: https://github.com/jellyfin/jellyfin-web/pull/3696
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/7267
Closes https://github.com/jellyfin/jellyfin/pull/7779 and https://github.com/jellyfin/jellyfin/pull/7776
> Make IgnoreDts configurable for M3U tuner

- Jellyfin.Api/Controllers/UniversalAudioController.cs
**Changes**
Use the userId from the authorizationInfo when the request doesn't have one. This makes the parameter actually optional (right now you get a bad request when there is no user id...)
**Issues**
```
System.ArgumentException: Guid can't be empty (Parameter 'id')
at Jellyfin.Server.Implementations.Users.UserManager.GetUserById(Guid id)
at Jellyfin.Api.Helpers.MediaInfoHelper.SetDeviceSpecificData(BaseItem item, MediaSourceInfo mediaSource, DeviceProfile profile, AuthorizationInfo auth, Nullable`1 maxBitrate, Int64 startTimeTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String playSessionId, Guid userId, Boolean enableDirectPlay, Boolean enableDirectStream, Boolean enableTranscoding, Boolean …
```
> Make userId truly optional in UniversalAudioController

- Emby.Dlna/PlayTo/DlnaHttpClient.cs
```
[18:53:50] [ERR] [25] Emby.Dlna.Main.DlnaEntryPoint: Error updating device info for 192.168.1.21 - Sonos Connect:Amp Berging
System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.StringContent'.
at System.Net.Http.HttpContent.CheckDisposed()
at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
--- …
```
> Fix regression in DlnaHttpClient

- Jellyfin.Api/Controllers/QuickConnectController.cs
Operation names should be unique for the generated OpenAPI document, they should also be somewhat descriptive of their function. Adding the "QuickConnect" name to all QC related operations fixes that.
This change only impacts the names of generated API functions in SDK's/apiclients, it does not break the API in any way.
**Changes**
- Fix QuickConnect operation names
**Issues**
> Fix QuickConnect operation names

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
- MediaBrowser.Model/Entities/MediaStreamType.cs
**Problem:**
Streams with CodecType "data" (like "epg" streams in DVB recordings) get ignored. This results in wrong stream specifiers for all subsequential streams. See isue #8284.
**Solution:**
This fix correctly handles "data" streams by setting a newly defined MediaStreamType for such stream. At the moment "data"streams are not processed any further.
> Added handling of streams of type "data"

- CONTRIBUTORS.md
- MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
**Changes**
Back-port PR #8259 changes in 10.8.z branch.
Such changes are not a new feature, but in effect a fix of the original PR #7153 (already included in 10.8.z branch), whose declared goal was really fulfilled only with my PR #8259 (already merged in master).
**Issues**
Addresses #6672
Complete PR #7153
Back-port PR #8259
> Increased (really) subtitle extraction timeout to 30 min (10.8.z back-port)

- CONTRIBUTORS.md
- src/Jellyfin.MediaEncoding.Keyframes/FfProbe/FfProbeKeyframeExtractor.cs
**Changes**
- Add TryParse to the ffprobe keyframe extraction to allow for unexpected values in the ffprobe output.
Some (or all, I haven't checked them all) of my mp4 files produce the following output:
```
packet,N/A,K_
packet,0.000000,K_
packet,0.041708,__
```
- Add the genpts flag to generate the timestamps for files which show N/A for everything.
- Allow additional flags after "K_". Some of my files (LiveTV recordings in ts files) have the following output:
```
packet,52786.322778,K_side_data,
packet,52786.302778,__side_data,
```
**Issues**
N/A
> Fixes for FFProbe Keyframe extraction

- Jellyfin.Api/Helpers/TranscodingJobHelper.cs
- Jellyfin.Api/Models/PlaybackDtos/TranscodingThrottler.cs
- MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
**Changes**
- Fix high single thread usage in throttler (this requires [jellyfin-ffmpeg >= 5.0.1-8](https://github.com/jellyfin/jellyfin-ffmpeg/pull/165))
> free single core usage from [c]. And it has a faster resume speed than other methods. vf_realtime filter has also been considered but it doesn't support remux. [p] to pause, [u] or any other key to resume.
> Fix high single thread usage in throttler

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Pass referer parameter to ffmpeg.
**Changes**
As of https://trac.ffmpeg.org/ticket/2179, ffmpeg supports referer parameter which injects Referer header to the HTTP request for remote content. Have EncodingHelper pass this in if it's included in RemoteHttpHeaders.
**Issues**
https://github.com/jellyfin/jellyfin/issues/8143
> Pass referer parameter to ffmpeg

- CONTRIBUTORS.md
- Jellyfin.Api/Controllers/UserLibraryController.cs
- MediaBrowser.Controller/Entities/BaseItem.cs
**Changes**
Make the `GetSpecialFeatures` function consistent with the rest of the file by using `GetExtras()` and filtering down to what is needed. The overloaded `GetExtras(BaseItem.DisplayExtraTypes)` was only used for `GetSpecialFeature`, so I opted to delete it as it is no longer needed. 
**Issues**
[8387](https://github.com/jellyfin/jellyfin/issues/8387)
> Fix special features not being sorted

- Dockerfile.arm
I believe this isn't needed anymore since https://github.com/jellyfin/jellyfin-ffmpeg/pull/77 got merged
> Remove libraspberrypi0 package from arm Dockerfile

- Jellyfin.Server/Middleware/BaseUrlRedirectionMiddleware.cs
Based on the code from #4546 but uses `System.Uri` to generate the proper redirect path.
**Changes**
Fix redirect failures by redirecting back to the index page.
----
Supersedes #4546
> Redirect natively if no baseurl is set

- Emby.Naming/Common/NamingOptions.cs
- Emby.Server.Implementations/Library/Resolvers/Audio/MusicAlbumResolver.cs
- Emby.Server.Implementations/Library/Resolvers/Audio/MusicArtistResolver.cs
- MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs
- MediaBrowser.Controller/Providers/ICustomMetadataProvider.cs
- MediaBrowser.Providers/MediaBrowser.Providers.csproj
- MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
- MediaBrowser.Providers/MediaInfo/FFProbeAudioInfo.cs
- MediaBrowser.Providers/MediaInfo/ProbeProvider.cs
- MediaBrowser.Providers/Music/AlbumMetadataService.cs
- MediaBrowser.Providers/Music/AudioMetadataService.cs
Our music parser is notoriously inflexible, so I tried making it better.
**Changes**
* use TagLibSharp to properly read tags from files (preference in this order):
1. ID3v2
2. APE
3. FLAC
4. Audible
5. ID3v1
* properly read multiple artists and album artist tags (ffprobe did not provide this)
* properly create and associate persons with tracks
* enable people association on albums
* add all artists from tracks as persons to album
* add album artists from tracks to the album
* add composers to tracks and albums
* add MusicBrainz releasegroup and album Ids to album
* allow subfolders named as the plural of [MusicBrain ReleaseGroups](https://musicbrainz.org/doc/Release_Group/Type)  to be present under an artist
* add proper replace logic to services (some may be duplicate)
* add xmldocs for …
> Extend music parsing

- MediaBrowser.Providers/MediaInfo/EmbeddedImageProvider.cs
Realized I never added `EmbeddedImageProvider` to [the docs](https://jellyfin.org/docs/general/server/media/movies.html#images), then when I did so I noticed I'd missed the type-specific image names ("movie" and "show") that are listed there. Seemed easier to add support for them to the code than explain an exception for them in the docs.
**Changes**
- Add missing documented image filenames to `EmbeddedImageProvider`
- Remove redundant "fanart" name (picked up by "art" since the matcher uses `String.Contains`)
> Update embedded image names to match docs

- src/Jellyfin.MediaEncoding.Keyframes/FfProbe/FfProbeKeyframeExtractor.cs
**Changes**
Kill the ffprobe process if the parsing crashes
**Issues**
Partially fixes https://github.com/jellyfin/jellyfin/issues/8513
> fix: kill ffprobe if keyframe parsing fails

- Emby.Naming/Common/NamingOptions.cs
**Changes**
Adds support for extras in a directory called "Other", or with the suffix "-other". This brings in behaviour that more closely matches Plex in "[Local Files for Movie Trailers and Extras](https://support.plex.tv/articles/local-files-for-trailers-and-extras/)".
**Issues**
Resolves a comment from a user post on Reddit: [Migrate from Plex to Jellyfin and specific naming](https://www.reddit.com/r/jellyfin/comments/vgtber/migrate_from_plex_to_jellyfin_and_specific_naming/)
> Add extras with "Other" as a label

- MediaBrowser.Model/Dlna/StreamBuilder.cs
If a video doesn't have an audio stream, it cannot direct play right now, since no supported audio stream can is available (`FirstOrDefault` always returns `null` on empty collections).
This commit ensures that any audio stream is available before matching the device profiles.
**Changes**
* Wraps the audio stream check in a `.Any()` if clause to ensure at least one audio stream is available.
* The unused variable `list` is removed.
* `videoSupported` and `audioSupported` checks optimized to return faster – `null` streams are always “supported”.
**Issues**
* [jellyfin/jellyfin-android#28](https://github.com/jellyfin/jellyfin-android/issues/28#issuecomment-1221328279)
> Allow direct play even if no audio stream is available

- Emby.Server.Implementations/Library/MediaStreamSelector.cs
**Changes**
Aligned the behaviour of the subtitle selection logic with the descriptions that are given on the front end. Currently the behaviour is not as the user would expect.
- "Default" should account for language preference when there are multiple options of equal priority, and should play subtitle tracks according to external, forced or default flag priority.
- "Smart" should respect forced tracks, then only attempt to play other subtitles if the user's subtitle language preference does not match the audio track language. If subtitles in the preferred language are not present then fall back on default behaviour.
- "Always Play" should always attempt to play subtitles matching the user's language preference, and fall back on default behaviour otherwise.
**Issues**
Fixes #8251
> Fix subtitle selection behaviour

- Emby.Server.Implementations/ApplicationHost.cs
Should fix the slowness reported in #8179 caused by #6486 for the master branch
**Changes**
Use the RemoteIpAddress of the HTTP request for getting the API URL.
**Issues**
Fixes #8179
> Prevent host lookup on GetSmartUrl for HTTP requests (master)

- Emby.Server.Implementations/ApplicationHost.cs
Should fix the slowness reported in #8179 caused by #6486 for 10.8.
#8147 already fixes this for master by removing the host lookup feature.
**Changes**
Use the RemoteIpAddress of the HTTP request for getting the API URL.
**Issues**
Fixes #8179
> Prevent host lookup on GetSmartUrl for HTTP requests

- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
- Jellyfin.Server/Filters/AdditionalModelFilter.cs
**Changes**
- Change TranscodingInfo.TranscodeReasons to an array instead of string
- Move enum definition for TranscodeReasons to it's own schema
**Issues**
Fixes #8514
> Fix TranscodeReasons type in OpenAPI output

- Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
I have not worked on the server in a long time. Please provide guidance on how I can improve this solution.
**Changes**
As per the API changes on October 1st (and possibly earlier), SchedulesDirect requires the token to be used to get the available image artwork index, and for image requests. This is part of an effort by them to curb abuse of the program artwork from their data provider.
References:
https://www.schedulesdirect.org/news/056/SD-JSON-images-now-require-tokens
**Issues**
Likely fixes #7528, may be related to #8502.
**Followup**
As per the [changes to the API page](https://github.com/SchedulesDirect/JSON-Service/wiki/API-20141201/_compare/b66fb95c6d167c968fc11311ac5e02cbb28b883a...b1bbfbcec39846623476a0f8b96d1f0d501bef7f), the token can either be provided as a header, or as a …
> Use Token for SchedulesDirect Images and Image Index

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Fix the DG2 HDR TM tearing issue on Windows
- Fix some encoding presets
**Issues**
Intel DG2/A380 on Windows may produces tearing and artifacts when mapping from D3D11VA to OpenCL.
> Fix the DG2 HDR TM tearing issue on Windows

- .ci/azure-pipelines-abi.yml
- .ci/azure-pipelines-main.yml
- .ci/azure-pipelines-package.yml
- .ci/azure-pipelines-test.yml
These dependency updates broke the pipeline... so downgrade while we wait for the migration to GHA
> Revert dependency updates to Azure Pipelines

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
The current Docker healthcheck command results in progress info being output, e.g.
```
$ docker inspect <jellyfin-container>
... snip ...
"Health": {
"Status": "healthy",
"FailingStreak": 0,
"Log": [
{
"Start": "2022-10-10T00:01:53.361633357-07:00",
"End": "2022-10-10T00:01:53.536249464-07:00",
"ExitCode": 0,
"Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100     7    0     7    0     0    194      0 --:--:-- --:--:-- --:--:--   194\nHealthy"
},
... snip ...
```
Fix this by adding the `-f/--fail`, `-s/--silent`, `-S/--show-error` options to avoid progress output, but still show error …
> Fix Docker healthcheck output

- Emby.Naming/Common/NamingOptions.cs
- MediaBrowser.Controller/Entities/BaseItem.cs
- MediaBrowser.Model/Entities/ExtraType.cs
- tests/Jellyfin.Naming.Tests/Video/ExtraTests.cs
Change extra parsing rules for Featurettes and Shorts so they don't both get classed as ExtraType.Clip.
Fix test broken by these changes.
**Changes**
Change parsing rules for extras labeled "short" and "featurette." Both were previously classed as type "Clip" 
Add two new Extra types (short, featurette)
Add parsing rule to allow "clip" extras in folder form. Now accommodates all supported extra types in either suffix or folder form.
**Issues**
Fixes [#4114](https://github.com/jellyfin/jellyfin-web/issues/4114)
**Other**
PR for user facing portion: [4115](https://github.com/jellyfin/jellyfin-web/pull/4115)
> Fix extra type differentiation

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
- MediaBrowser.Model/Entities/MediaStreamType.cs
Reverting the change wasn't necessary anymore and actually causes problems for users that have data streams because the database now contains an invalid value. Reverting the revert for 10.8.7.
In the future we should make sure no database/api changes are added to patch releases unless it's a critical bugfix so we don't end up ping-ponging like we did here.
Reverts jellyfin/jellyfin#8480
> Revert "Revert "Merge pull request #8298 from lomion0815/fix-data-stream""

- MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs
**Changes**
Re-enables OMDb plot data for non-english languages. This was used as a fallback if there was no localised plot in 10.7.z.
Simpler fix of #8633
**Issues**
Fixes #8064
> Enable OMDB plot for non-English languages as fallback

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
- Emby.Server.Implementations/TV/TVSeriesManager.cs
- MediaBrowser.Controller/Entities/InternalItemsQuery.cs
**Changes**
Using ParentIndexNumber and IndexNumber individually doesn't work when the next episode is in another season. This changes the query to look for higher episode numbers in the same season and episodes in higher seasons.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/8655
> fix: use a combination of ParentIndexNumber and IndexNumber to determine next up episodes

- Jellyfin.Server/Middleware/BaseUrlRedirectionMiddleware.cs
Redirection didn't work when connecting via `IP:Port`.
**Changes**
* Create relative redirect from full URI based on request
**Issues**
Fixes #8550
> Fix URI creation in redirection middleware

- Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs
Fixes exceptions generated from this (invalid) xml
```
<programme channel="3297" start="20221104130000 -0400" stop="20221105235959 -0400">
<category lang="en">sports</category>
<episode-num system="original-air-date">2022-11-04 13:00:00</episode-num>
<icon height="" src="https://domain.tld/image.png" width=""/>
<credits/>
<video/>
<date/>
</programme>
```
> Don't throw exception if program.Title is null

- MediaBrowser.Model/Entities/SeriesStatus.cs
**Changes**
Add new "Unreleased" status to SeriesStatus enum. To be used for series that have not started releasing yet. This PR does not change any of the core providers to make use of this new enum member.
Also make the descriptions slightly more useful.
**Rationale**
Currently we only have a continuing and ended state. But it's not uncommon to have the directories for new series made before they start releasing. For that particular case there is no way to indicate this "unreleased" state. With jellyfin-web (and possibly other clients) having a filter for series state it makes sense to put unreleased series in their own grouping.
**To consider**
Different providers have different states. Some examples:
- TheMovieDatabase: `Rumored, Planned, In Production, Post Production, Released, …
> Add SeriesStatus.Unreleased

- Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunManager.cs
CheckTunerAvailability creates a span from a buffer to pass to the validation function. It appears to be incorrectly using the length as the starting index which is causing the tuner initialization to fail. Fixing this resolved the issue I was having with my HDHR3-US.
Please let me if you would like any additional  changes  or testing done.
Fixes #7154
> HDHomeRun - Fix incorrect starting offset of buffer span in CheckTunerAvailability.

- Emby.Naming/Common/NamingOptions.cs
**Changes**
"Digital Media" is a common 'disk'-splitting prefix, more so with recent 'digital' music releases as physical cds/disks aren't used. In particular, it is part of Lidarr's `{Medium Format}` tag for automatic archive sorting. So it would be good to see this reflected into Jellyfin. I'm not familiar with the code-base, or whether a ' ' character is valid within this context.
> Add support for "Digital Media" album splits

- MediaBrowser.Model/Dlna/StreamBuilder.cs
- MediaBrowser.Model/Dto/MediaSourceInfo.cs
- tests/Jellyfin.Model.Tests/Dlna/StreamBuilderTests.cs
Browsers (Chrome, Firefox) can only play the first track, even if the second track is the default.
**Changes**
- Ignore default flag when testing on secondary audio.
- External audio tracks are not secondary.
**Issues**
Fixes https://github.com/jellyfin/jellyfin-web/issues/4044
Fixed #8673
Can be backported.
Not sure if this works with STRM.
> Fix secondary audio

- Emby.Server.Implementations/Plugins/PluginManager.cs
Fixes https://github.com/jellyfin/jellyfin/issues/8681
The update task already ignores plugins marked as Disabled, but when initially disabling a plugin it's status is set to Restart.
Alternatively we could ignore plugins with a status of Restart when checking for updates
> Don't auto-update if plugin is pending restart

- Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
Timers are getting added twice to the enabled list. This results in the second copy of the timer being detected as a duplicate of the showID and cancelled. Since both timers in the list are the same object, the original record is cancelled as a duplicate. 
I'm not sure exactly why it gets added twice in the first place, so I thought the easiest thing to do was to remove the duplicate timers (not duplicate shows)
Fixes #3523
> Don't cancel DVR recordings when adjusting settings

- Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
- Emby.Server.Implementations/LiveTv/EmbyTV/TimerManager.cs
Current behavior of the scheduler is undefined when handling duplicate showings. Order of timers is unknown. This PR sorts duplicate showings first by HD channels, then by earliest showing. Under the current behavior, my DVR could sometimes wait over a week to record a later episode for no discernable reason. 
Logs more details when scheduling DVR timers.
> DVR: Prefer HD channels then earliest showing when handling duplicate showings.

- MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs
This is mostly useful in order to have a deterministic display in the UI and your subtitles follow a clear naming scheme. I would for instance like to show preferred subtitle formats first in the list, which is enabled by this and a simple additional tag in the name just after the title.
**Changes**
Just turns on sorting for the two methods that get the actual external file names.
> Sort external files when scanning

- Jellyfin.Api/Controllers/DisplayPreferencesController.cs
- Jellyfin.Api/Helpers/StreamingHelpers.cs
- Jellyfin.Server/Program.cs
This resolves the following compilation errors (originally encountered whilst trying to build for Arch Linux using an [AUR package](https://aur.archlinux.org/packages/jellyfin), but can be reproduced using the repo's own build script with the dpkg check commented out):
> Jellyfin.Api/Controllers/DisplayPreferencesController.cs(181,29): error CA1305: The behavior of '{0}' could vary based on the current user's locale settings. Provide a value for the 'IFormatProvider' argument. [Jellyfin.Api/Jellyfin.Api.csproj]
> Jellyfin.Api/Helpers/StreamingHelpers.cs(354,24): error CA1305: The behavior of '{0}' could vary based on the current user's locale settings. Provide a value for the 'IFormatProvider' argument. [Jellyfin.Api/Jellyfin.Api.csproj]
> Jellyfin.Server/Program.cs(614,30): error CA1305: …
> Add missing format providers (fix CA1305 errors)

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
- MediaBrowser.Model/Querying/ItemSortBy.cs
Update to search - prioritise titles that match completely e.g.
search string "thing" will bring back title Thing first e.g.
Thing
Thing!
Thing Thing
**Changes**
Added additonal +10 search score for exact match with case insensitive.  Added sort by SearchScore DESC ( was previously ORDER BY SortName DESC, SortName ASC)
**Issues**
n/a
> Minor search update - full word titles matches first

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Debian is still on FFmpeg 4.3, without this patch HW acceleration doesn't work
> The -autoscale option was added in FFmpeg 4.4

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
Adds the `delay_moov` flag to the progressive mp4 transcoding options to fix an issue where some files fail to transcode currently
**Issues**
N/A
> Add delay_moov flag for progressive mp4 transcoding

- MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzAlbumProvider.cs
- MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzArtistProvider.cs
Fixes one of the outstanding kinks of the new MusicBrainz plugin implementation. Makes this compatible with the config value used in 10.8.
**Changes**
* Validate server URI
* Properly set query options
* Fallback to official server if no valid URI is specified
> Add MusicBrainz server validation and fallback

- Jellyfin.Api/Controllers/LibraryController.cs
Kestrel now supports non-ASCII characters in headers so we no longer need to urlencode the filenames. I've tested the filename 白蛇2：青蛇劫起 (2021).avi on a Mac and it works fine.
**Changes**
* Remove urlencoding
**Issues**
Fixes #8657
> Allow non-ASCII in downloaded filenames

- Emby.Photos/PhotoProvider.cs
Add support for avif and webp for the Photo libraries.
**Changes**
Added the two extensions in `Emby.Photos/PhotoProvider.cs`
> Add support for avif and webp for photos

- build.yaml
- deployment/Dockerfile.macos.amd64
- deployment/Dockerfile.macos.arm64
- deployment/build.macos.amd64
- deployment/build.macos.arm64
Signed-off-by: gnattu <gnattuoc@me.com>
**Changes**
This add building support for macOS arm64 target which is pretty stable now on dotnet 6. One thing to note is that the old build script is renamed from `build.macos` to `build.macos.amd64`, I did not find direct use of these scripts other than the build script itself, if it breaks anything please let me know.
Already tested with a ubuntu 22.04 amd64 buiding host using docker crossbuild. 
**Issues**
> feat: macOS arm64 build support

- Jellyfin.Api/Controllers/QuickConnectController.cs
**Changes**
- Change QC initiate to use HTTP POST, keep the old GET method for compat
- ~~Add QC revoke endpoint, requested by @thornbill~~
- Add userId parameter to QC authorize for jellyfin/jellyfin-web#3918
API changes are compatible with existing client implementations
**Issues**
API changes for https://github.com/jellyfin/jellyfin-web/issues/3918
> Add admin login to QuickConnect API

- Emby.Server.Implementations/Library/Resolvers/BaseVideoResolver.cs
Make sure that any subsequent requests to open the file for read will succeed. As per documentation, if this flag is not set, then any request to open the file for reading (by this process or another process) will fail until the file is closed.
**Changes**
Pass the flag FileShare.Read when opening the FileStream for UDF validation.
**Issues**
Fixes #8276
> Fix to make sure that UDF streams are opened with Share.Read (#8276)

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
**Changes**
This minor change permits users to search for items via tags.
**Issues**
* https://github.com/jellyfin/jellyfin/issues/7691
* https://features.jellyfin.org/posts/276/search-by-tag-genre
* https://features.jellyfin.org/posts/635/search-by-tag
* https://www.reddit.com/r/jellyfin/comments/paqi3t/is_there_a_way_of_searching_by_tag/
* https://www.reddit.com/r/jellyfin/comments/xp94po/am_i_doing_something_wrong_i_cannot_search_with/
**Commentary**
Seems to be a frequently requested feature. I considered searching with a join on the `ItemValues` table, but figured this direct approach would likely be sufficient.
> Augment search to consider tags

- Emby.Server.Implementations/Library/LibraryManager.cs
- MediaBrowser.Controller/Entities/BaseItem.cs
- MediaBrowser.Controller/Library/ILibraryManager.cs
- MediaBrowser.Model/Configuration/LibraryOptions.cs
- MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
I took the time to embed titles in my extras (including characters not valid for use in filenames) and was annoyed when Jellyfin ignored the embedded value. Finally got around to adding an option to enable it.
**Changes**
- Fix library search for owned items to look to their parent (so extras can use the options of the library their parent belongs to)
- Add an option to allow video extras to prefer their embedded title over the file name
**Issues**
Option exposed by jellyfin/jellyfin-web#3652
> Add option to allow extras to use embedded titles

- Jellyfin.Server/Middleware/ResponseTimeMiddleware.cs
The added log level check is there because Request.GetDisplayUrl() is a pretty expensive call, creating a StringBuilder and string which doesn't need to happen on most installs where debug logging is disabled
Fixes #7348
> Change log level for slow HTTP responses from WRN TO DBG

- MediaBrowser.Model/Dlna/StreamBuilder.cs
**Changes**
* Default to no maximum bitrate if none is specified instead of 1 mbps.
**Issues**
Fixes #3277
> Default to no bitrate limit if no maxBitrate is set

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
I found that my home videos are not getting a PremiereDate from the server despite ffprobeshowing one. Here is the output of ffprobe:
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'ellie_eating.MP4':
Metadata:
major_brand     : XAVC
minor_version   : 16785407
compatible_brands: XAVCmp42iso2
creation_time   : 2020-08-01T00:06:51.000000Z
Duration: 00:00:33.54, start: 0.000000, bitrate: 50032 kb/s
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 47904 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
Metadata:
creation_time   : 2020-08-01T00:06:51.000000Z
handler_name    : Video Media Handler
vendor_id       : [0][0][0][0]
encoder         : AVC Coding
Stream #0:1(und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, 2 channels, s16, …
> Adding "creation_time" as a tag lookup for FFProbe for premiere date

- README.md
**Changes**
- The installation guide link was broken. Updated it to the correct location.
- Updated other links to docs pages to not include the docs.jellyfin.org subdomain, and instead go through jellyfin.org/docs based on feedback received
**Issues**
> Correct path to installation guide

- MediaBrowser.Model/Extensions/EnumerableExtensions.cs
**Context**
In the current master branch of Jellyfin, image ordering with a non-English requested language orders like so:
1. Images that match the requested language
2. English images _or_ images with no language
3. All other images
Whereas image ordering with English as the requested language orders like so:
1. Images matching your requested language _or_ images with no language
2. All other images
**Changes**
This change proposes a consistent ordering of images irrespective of the specific requested language:
1. Images that match the requested language
2. Images with no language
3. English images
4. All other images
> Fix image searching to prioritize explicit language match if searching in English

- Emby.Naming/Common/NamingOptions.cs
- tests/Jellyfin.Naming.Tests/Video/CleanStringTests.cs
Right now, a movie Name `Iron Man Multi 1080p.mkv` will be searched as `Iron Man Multi` leading to no result.
The cleaning regex was containing multi but it looks like a typo joined `multi` and `subs` in the same term.
> Fix `multi` cleaning

- .github/workflows/openapi.yml
**Changes**
Find the common ancestor between the pull request and it's target branch so we can compare the OpenAPI changes properly. I tested this in my fork and it does seem to work after a bunch of trial and error.
This fixes the problem where once a API-changing PR is merged to master, the workflow would suddenly act like the API changes were reverted in all other PR's because it checked out the latest commit in master instead of the common ancestor.
**Issues**
> Checkout common ancestor for comparison in OpenAPI workflow

- MediaBrowser.Providers/Manager/MetadataService.cs
**Changes**
If there are no images to begin with, we are not replacing anything. So if there are no images of this ImageType, then don't skip over this image.
**Issues**
Fixes #8993 
I did also test that #7836 does not appear again.
> Use nfo provided remote images on initial scan

- Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
- MediaBrowser.Controller/Entities/TV/Episode.cs
- MediaBrowser.Model/LiveTv/LiveTvOptions.cs
- SaveRecordingNFO and SaveRecordingImages default to true. Maintains current behavior.
- Episode.FillMissingEpisodeNumbersFromPath for live tv so external metadata can be pulled when recording starts.
Fixes #5178
> DVR: Add options to disable NFO and image saving

- debian/postinst
- fedora/jellyfin.spec
Signed-off-by: nyanmisaka <nst799610810@gmail.com>
**Changes**
- Try to add jellyfin to the render and video groups for HWA during installation
**Issues**
Fixes the permission issue on VAAPI and QSV:
```
[AVHWDeviceContext @ 0x55b9b2a92200] No VA display found for any default device.
Device creation failed: -22.
Failed to set value 'vaapi=va:,driver=iHD,kernel_driver=i915' for option 'init_hw_device': Invalid argument
Error parsing global options: Invalid argument
```
> Add jellyfin to the render and video groups for HWA

- Emby.Server.Implementations/Session/SessionManager.cs
- Jellyfin.Server.Implementations/Users/UserManager.cs
- MediaBrowser.Controller/Session/ISessionManager.cs
The following events aren't currently firing:
Pending restart requires more work, plugin installed _should_ be working but haven't investigated.
> Use EventManager for AuthenticationSuccess, AuthenticationFailure

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
In the current master branch, movie similarity matches on identical parental rating strings. But this means CA-G and G are considered different, despite [us.csv](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Localization/Ratings/us.csv) and [ca.csv](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Localization/Ratings/ca.csv) defining them both as 1. The proposed fix matches on numeric parental rating and additionally provides a more gradual drop-off.
No known issues have been filed against this bug, but I suspect that's because item similarity is opaque to the end-user.
> Fixing similar parental rating calculation

- CONTRIBUTORS.md
- MediaBrowser.Controller/Entities/Folder.cs
Currently it is impossible to play/shuffle collection unless it directly contains audio tracks or video because albums/collections/etc. are not consider direct children.
**Changes**
- Add recursive lookup for linked children
- Prevent infinite recursive lookup
**Issues**
Fixes #6193
Fixes #7226
**Related reddit posts**
* [Help! Can't play a music collection](https://www.reddit.com/r/jellyfin/comments/vpvnxd/help_cant_play_a_music_collection/)
* [Error on Play or Shuffle Music Collection](https://www.reddit.com/r/jellyfin/comments/s6ltkw/error_on_play_or_shuffle_music_collection/)
* ['Playback Error' when playing Collection/Playlist](https://www.reddit.com/r/jellyfin/comments/qoxc9o/playback_error_when_playing_collectionplaylist/)
* [Problem with playing a collection with just Tv shows in …
> Fix recursive children lookup of folders

- CONTRIBUTORS.md
- Jellyfin.Api/Controllers/DynamicHlsController.cs
**Changes**
Adds dts to the list of audio codecs where ffmpeg will throw asking us to opt into experimental support. This is seen when the original content is based on dts and we don't acopy using ffmpeg.
Note: I haven't tested this locally, as my server is currently 200+ miles away from me with no way to remotely install a new version. Looking at my logs and the logs in the original this happens on DTS media that's transcoded, so it should be easy to test...
**Issues**
Fixes #8804
> Add dts to list of audio codecs which require ffmpeg strict -2

- CONTRIBUTORS.md
- Jellyfin.Api/Controllers/DynamicHlsController.cs
Backports #9029 and adds truehd additionally in a separate commit.
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/2396
> Add more codecs requiring ffmpeg strict -2

- MediaBrowser.Model/Branding/BrandingOptions.cs
**Changes**
Disables the splash screen image by default due to privacy concerns with the generated image exposing library contents.
**Issues**
Concerns reported via email and Reddit
> Disable splash screen image by default

- Jellyfin.Api/Controllers/DynamicHlsController.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.Model/Configuration/EncodingOptions.cs
- MediaBrowser.Model/Entities/DownMixStereoAlgorithms.cs
Implements different downmixing algorithms from https://superuser.com/questions/852400/properly-downmix-5-1-to-stereo-using-ffmpeg/1410620#1410620 which were discussed in https://github.com/jellyfin/jellyfin/issues/1986
**Changes**
* Add stereo downmixing algorithms
**Issues**
Fixes #1986
> Add stereo downmix algorithm selection.

- Jellyfin.Server/Jellyfin.Server.csproj
- Jellyfin.Server/Program.cs
- Jellyfin.Server/Startup.cs
- tests/Jellyfin.Server.Integration.Tests/JellyfinApplicationFactory.cs
Redo of #7347
Using `IHost` and `IHostBuilder` is the [recommended](https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?tabs=visual-studio#hostbuilder-replaces-webhostbuilder) way to configure the application host.
When using `IHost`, it is no longer possible to use DI in Startup.cs, except for `IConfiguration`, `IHostEnvironment`, and `IWebEnvironment`, so startup initialization is now done manually
This should decrease the startup time of Jellyfin since the ServiceProvider is no longer created twice, but I haven't measured it.
> Migrate to IHost

- Jellyfin.Api/Jellyfin.Api.csproj
Reverts jellyfin/jellyfin#8591
Version is broken with the following error:
```
[2023-01-13 15:43:41.302 -07:00] [ERR] [20] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/api-docs/openapi.json".
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - Jellyfin.Api.Controllers.ArtistsController.GetArtists (Jellyfin.Api). See inner exception
---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type - MediaBrowser.Model.Querying.QueryResult`1[MediaBrowser.Model.Dto.BaseItemDto]. See inner exception
---> System.NullReferenceException: Object reference not set to an instance of an object.
at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForMember(Type …
```
> Revert "chore(deps): update swashbuckle-aspnetcore monorepo to v6.5.0"

- Jellyfin.Api/Controllers/ImageController.cs
I recently noticed on the Android TV app that logos for TV shows with transparent backgrounds now had black backgrounds instead. I traced this to `GetClientSupportedFormats` short circuiting if the Accept header was missing.
These changes remove the short-circuit so that at least the jpg and png formats get added by default. Some code is adjusted so that it handles a missing Accept header.
> Fix client supported image formats

- Jellyfin.Api/Helpers/DynamicHlsHelper.cs
**Changes**
Don't add additional entries (_for HEVC_) if HEVC encoding is disabled.
**Issues**
Fixes #5576 (https://github.com/jellyfin/jellyfin/issues/5576#issuecomment-1373901085)
Fixes https://github.com/jellyfin/jellyfin/issues/8043
Fixes https://github.com/jellyfin/jellyfin-webos/issues/105
Fixes https://github.com/jellyfin/jellyfin-tizen/issues/163
> Don't add additional entries if HEVC encoding is disabled

- deployment/build.windows.amd64
**Changes**
- Backport #8901 into 10.8.z in case it breaks the next publish.
> Backport the ffmpeg link fix (#8901) to 10.8.z

- MediaBrowser.Model/Dlna/StreamBuilder.cs
- tests/Jellyfin.Model.Tests/Dlna/StreamBuilderTests.cs
**Changes**
- Don't trim failure reasons.
For example, we have HEVC+AC3, but neither the video codec nor the audio codec is supported. We have rank 1 (video) failure, but it should be mentioned that audio is also not supported.
- Skip profiles with `ContainerNotSupported` if it is actually supported by any profile.
**Issues**
Sometimes (if not in most cases) the reason for transoding is just `ContainerNotSupported`, but the real reason is something else.
This may be due to the existence of profiles with an empty list of codecs (ASF, WMV) - they only produce `ContainerNotSupported`, because an empty codec list means that any codec is supported.
**Notes**
`SecondaryAudioNotSupported` appears in the tests, but in fact, it is not really the cause of the transcoding.
> Fix transcode reasons

- .github/workflows/repo-stale.yaml
Stalebot currently does not work as intended, apparently we need to increase its operation contingent.
**Changes**
Increase stalebot `operations-per-run` from 30 to 75
> Increase stale bot operations per run

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
- tests/Jellyfin.MediaEncoding.Tests/Probing/ProbeResultNormalizerTests.cs
- tests/Jellyfin.MediaEncoding.Tests/Test Data/Probing/video_interlaced.json
- tests/Jellyfin.MediaEncoding.Tests/Test Data/Probing/video_progressive_no_field_order.json
- tests/Jellyfin.MediaEncoding.Tests/Test Data/Probing/video_progressive_no_field_order2.json
It's impossible to know if field_order isn't specified
https://github.com/jellyfin/jellyfin/pull/6222#issuecomment-1030159457
Fixes #8216
> Revert 'Fix interlace check for H.264 MBAFF coded MP4 files' (#6222)

- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
**Changes**
The user data object wasn't saved when modified after parsing an nfo, which made the watched, playcount and lastplayed tags functionally useless.  
I had to duplicate a few lines and move them in the switch in order to avoid trying to save new userData for every tag, but that shouldn't be a problem.  
Since it seems odd that this issue wasn't noticed for more than one year and the relevant tests were passing, this warrants a look by someone more experienced with the codebase, but that fixes #8415 for me.
I'm also not sure about the proper use of the "none" cancellation token sent during the data save, but I don't think there's an issue with not being able to cancel the save...
**Issues**
Fixes #8415
> Save modified userData after parsing an nfo

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
"Phantom/Ghost" is another legit band name that should not be split
> Add Phantom/Ghost to normalizer whitelist

- Jellyfin.Api/Controllers/DynamicHlsController.cs
- Jellyfin.Api/Jellyfin.Api.csproj
- MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
- MediaBrowser.MediaEncoding/Encoder/EncodingUtils.cs
**Changes**
Escape the path to pass as a command line argument.
**Issues**
1. Transcoding doesn't work when `datadir` contains quotes in the path.
2. Attachment extraction doesn't work when `datadir` contains spaces in the path.
~_It would be better to extract these `Replace`s into a function. Where?_~
Use `MediaBrowser.MediaEncoding.NormalizePath` (https://github.com/jellyfin/jellyfin/pull/9178#issuecomment-1404675829)
Tested with datadir `jellyfin "test` on Ubuntu 20.04.
> Escape the path to pass as a command line argument

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
This PR specifies the audio codec when creating the ffmpeg command line when streaming audio. Currently, Jellyfin doesn't specify this and therefore just falls back on whatever the default codec of the container is. For example, here is an ffmpeg log run from a call to `/Audio/{id}/universal?transcodingContainer=ogg&audioCodec=opus`. Note how Vorbis is used despite audioCodec being set to opus.
<details>
```
/Audio/0d811359188af113961e7d18b0085ca7/universal
{"Protocol":0,"Id":"0d811359188af113961e7d18b0085ca7","Path":"/media/Music/Casiopea/1982 - 4x4/01 - Mid-Manhattan.flac","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"flac","Size":31252924,"Name":"01 - Mid-Manhattan","IsRemote":false,"ETag":"5e9910bdcaf55a912ce4341f9a1e9d70","RunTimeTicks":2822000128,"ReadAt …
```
> Fix audio codec not being used in UniversalAudio

- Emby.Server.Implementations/ApplicationHost.cs
- Emby.Server.Implementations/Channels/ChannelManager.cs
- Jellyfin.Server/Helpers/StartupHelpers.cs
- Jellyfin.Server/Program.cs
- MediaBrowser.Controller/Channels/IChannelManager.cs
- MediaBrowser.Controller/Subtitles/ISubtitleManager.cs
- MediaBrowser.Providers/Subtitles/SubtitleManager.cs
**Changes**
- Move `LogEnvironmentInfo` to `StartupHelpers`
- Use DI for `IChannel` and `ISubtitleProvider`
- Minor cleanup
> ApplicationHost cleanup

- Dockerfile
**Changes**
- Swaps to building the Dockerfile with `jellyfin-ffmpeg5`
**Issues**
**Landmines**
Not sure about the state of arm support of JF-FFMPEG but might be worth a quick look if we update this on the amd64 build :)
> fix: swap to `jellyfin-ffmpeg5`

- CONTRIBUTORS.md
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
When the output container is [any valid MP4 extension](https://en.wikipedia.org/wiki/MP4_file_format#Filename_extensions), specify the same movflags that are also used in `GetProgressiveVideoAudioArguments`. I'm not 100% sure on the specifics, but this correctly returns an identical file to the one created in `/config/transcodes`.
(same as in the issue, `test` is what is returned from the API, `jellyfin` is what Jellyfin creates in `/config/transcodes`.
```
james@JamesPC-Linux ~/D/JellyfinExamples> sha256sum test-moov-fix.m4a jellyfin-moov-fix.m4a 
56059204973c1b52a3b1516ced84c52cd9a1204a4ef12352328a2ec77071ca64  test-moov-fix.m4a
56059204973c1b52a3b1516ced84c52cd9a1204a4ef12352328a2ec77071ca64  jellyfin-moov-fix.m4a
```
As expected, `test-moov-fix.m4a` can now be played …
> Specify required movflags when encoding M4A audio

- MediaBrowser.Providers/Manager/ItemImageProvider.cs
#8946 accidentally introduced a side effect of all backdrop images preferring the explicit language of the library. The purpose of backdrop images should actually deprioritize language.
We could additionally modify `OrderByLanguageDescending`, but how this gets used with both manual image searches and during metadata refresh makes it a little slippery to refactor properly. The proposed solution here is fairly simple and gets us the behaviour we're looking for.
Image sorting prioritizes non-language images for backdrop metadata refreshes.
> Fix backdrop image fetching to prioritize non-language images

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
This PR implements the hardware filters for videotoolbox introduced in ffmpeg 5.0, this will reduce CPU usage on macOS host
This PR also prefers Apple's AAC encoder in the coreaudio framework when available, because it provides even better quality than fdk_aac.
**Issues**
> Implement hardware filters for videotoolbox, use Apple AAC encoder when available

- Emby.Server.Implementations/Plugins/PluginManager.cs
**Changes**
Uses a separate `AssemblyLoadContext` per plugin instead of one per DLL
> Use one AssemblyLoadContext per plugin

- CONTRIBUTORS.md
- Emby.Server.Implementations/Data/SqliteItemRepository.cs
- Jellyfin.Data/Enums/PreferenceKind.cs
- Jellyfin.Server.Implementations/Users/UserManager.cs
- Jellyfin.Server/Migrations/Routines/MigrateUserDb.cs
- MediaBrowser.Controller/Entities/BaseItem.cs
- MediaBrowser.Controller/Entities/InternalItemsQuery.cs
- MediaBrowser.Model/Users/UserPolicy.cs
**Changes**
Parental Controls  can now block all the media that do not have a specified tag, similar to the already existing "Block items with tags" but with a whitelist instead. By default, as long as no tags are configured for the whitelist, no shows will be blocked.
**Issues**
Implements #928
> Add "Allowed Tags" to Parental Controls

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
- Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs
- tests/Jellyfin.Server.Implementations.Tests/LiveTv/Listings/XmlTvListingsProviderTests.cs
- tests/Jellyfin.Server.Implementations.Tests/Test Data/LiveTv/Listings/XmlTv/emptycategory.xml
- Filter out empty categories
- Filter out empty item values
The following exception is thrown in `InsertItemValues` if `values` contains an empty string.
```
[2023-02-11 07:13:16.900 -07:00] [ERR] [22] Emby.Server.Implementations.LiveTv.LiveTvManager: Error getting programs for channel "ABC EAST"
Constraint: SQLitePCL.pretty.SQLiteException: NOT NULL constraint failed: ItemValues.Type
at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
at SQLitePCL.pretty.StatementImpl.MoveNext()
at Emby.Server.Implementations.Data.SqliteItemRepository.InsertItemValues(Byte[] idBlob, List`1 values, IDatabaseConnection db) in …
```
> LiveTV fixes

- MediaBrowser.Providers/Manager/MetadataService.cs
- MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
- MediaBrowser.Providers/Music/AlbumMetadataService.cs
**Changes**
- Fix a couple cases where metadata could be updated on locked items
- Change `ItemUpdateType` for `RunTimeTicks` updating to `MetadataImport` to be consistent with other file attribute updates
**Issues**
Fixes #8888
> Fix locked item metadata updates

- Jellyfin.Api/Auth/UserPermissionPolicy/UserPermissionHandler.cs
- Jellyfin.Api/Auth/UserPermissionPolicy/UserPermissionRequirement.cs
- Jellyfin.Api/Constants/Policies.cs
- Jellyfin.Api/Controllers/CollectionController.cs
- Jellyfin.Data/Entities/User.cs
- Jellyfin.Data/Enums/PermissionKind.cs
- Jellyfin.Server.Implementations/Users/UserManager.cs
- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
- Jellyfin.Server/Migrations/Routines/MigrateUserDb.cs
- MediaBrowser.Controller/Entities/Movies/BoxSet.cs
- MediaBrowser.Model/Users/UserPolicy.cs
**Changes**
* Adds a permission to manage collections (add, remove and delete)
* Enforce permission on the collection endpoints
Will require changes to jellyfin-web (https://github.com/jellyfin/jellyfin-web/pull/4199) to take the new permission into account when displaying the elements in the item dropdown and collection screens. Additionally requires a setting in jellyfin-web to be available to set it.
**Issues**
Fixes #7179
> Add permissions for collection management

- Jellyfin.Api/Auth/LocalAccessOrRequiresElevationPolicy/LocalAccessOrRequiresElevationHandler.cs
- Jellyfin.Api/Auth/LocalAccessOrRequiresElevationPolicy/LocalAccessOrRequiresElevationRequirement.cs
- Jellyfin.Api/Constants/Policies.cs
- Jellyfin.Api/Controllers/LiveTvController.cs
- Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Backports #9130 to master and refactors the changes to match the behavior introduced in #9282
**Changes**
* Add policy for accessing LiveTV management endpoints
* Add policy for accessing LiveTV endpoints
* Re-Add missing `LocalAccessOrRequiresElevationPolicy`
> Backport #9130

- Jellyfin.Api/Auth/LocalAccessOrRequiresElevationPolicy/LocalAccessOrRequiresElevationHandler.cs
In its current state the handler will alwas fail.
> Fix LocalAccessOrRequiresElevationHandler

- Emby.Server.Implementations/ApplicationHost.cs
**Changes**
Fixes NRE in DisposeAsyncCore when _sessionManager is null (appears to be possible, happens when a broken plugin prevents startup)
```
An unhandled exception of type 'System.NullReferenceException' occurred in System.Private.CoreLib.dll: 'Object reference not set to an instance of an object.'
at Emby.Server.Implementations.ApplicationHost.<DisposeAsyncCore>d__126.MoveNext() in /home/mbr/Desktop/projects/jellfyin/new-develop/jellyfin/Emby.Server.Implementations/ApplicationHost.cs:line 1190
at Emby.Server.Implementations.ApplicationHost.<DisposeAsync>d__125.MoveNext() in /home/mbr/Desktop/projects/jellfyin/new-develop/jellyfin/Emby.Server.Implementations/ApplicationHost.cs:line 1152
at Jellyfin.Server.Program.<StartServer>d__11.MoveNext() in …
```
> Fix NRE in DisposeAsyncCore

- MediaBrowser.Providers/Plugins/MusicBrainz/Configuration/PluginConfiguration.cs
I forgot to add back the protocol here too which broke URL generation for external IDs. This should fix it.
> Fix MusicBrainz default server

- Emby.Naming/Common/NamingOptions.cs
- tests/Jellyfin.Naming.Tests/TV/EpisodeNumberTests.cs
- tests/Jellyfin.Naming.Tests/TV/EpisodePathParserTest.cs
Add an additional `EpisodeExpression` that matches
`Series title Season 3 Episode 9 - Episode title.avi` correctly.
Fixes #9341
> Add rule and tests to fix  #9341

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Increase pool size for VAAPI VPP (the hardcoded size 10 is way too small)
- Use CL_MAP_READ on OCL to reduce bandwidth overhead
**Issues**
- Fixes https://github.com/jellyfin/jellyfin-ffmpeg/issues/209
> Some VAAPI VPP and OpenCL fixes

- MediaBrowser.Model/Dlna/ConditionProcessor.cs
Currently `EqualsAny` is not implemented for `double` and the implementation for `int` does not work as it should (see #9350)
**Changes**
Split the conditional string value, parse the substrings into a int/double and check if one of them is equal to the current value.
**Issues**
Fixes #9350
> Fix EqualsAny condition check for int and double

- Emby.Naming/Audio/AlbumParser.cs
- Emby.Server.Implementations/Data/SqliteItemRepository.cs
- Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
- Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs
- Jellyfin.Api/Extensions/ClaimsPrincipalExtensions.cs
- Jellyfin.Api/Helpers/StreamingHelpers.cs
- Jellyfin.Api/Helpers/TranscodingJobHelper.cs
- Jellyfin.Networking/Manager/NetworkManager.cs
- Jellyfin.Server/Migrations/Routines/MigrateDisplayPreferencesDb.cs
- MediaBrowser.Common/Net/IPHost.cs
- MediaBrowser.Controller/LiveTv/LiveTvChannel.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
- MediaBrowser.Controller/MediaEncoding/JobLogger.cs
- MediaBrowser.LocalMetadata/Parsers/BaseItemXmlParser.cs
- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
- MediaBrowser.Model/Dlna/ConditionProcessor.cs
- MediaBrowser.Model/Dlna/SortCriteria.cs
- MediaBrowser.Model/Dlna/StreamBuilder.cs
- MediaBrowser.Model/Dlna/StreamInfo.cs
- MediaBrowser.Providers/Manager/MetadataService.cs
- MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs
- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
* Don't check for null before
* Don't try different formats when not needed (`NumberStyles.Integer` is the fast path)
> Optimize tryparse

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.Model/Configuration/EncodingOptions.cs
**Changes**
- Fix H.264 baseline profile hwaccel on D3D11VA and VA-API
- Enable enhanced Nvdec by default for using DoVi tone-mapping
**Issues**
- https://www.reddit.com/r/jellyfin/comments/119wo9z/cant_load_media_info_from_server_on_jellyfin/
- One has to manually enable "Enhanced Nvdec decoder" on Nvidia GPU to use DoVi tone-mapping.
> Fix H.264 baseline hwaccel and enable enhanced Nvdec by default

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Currently Mesa [RADV does not support a dedicated transfer queue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/850),
which uses compute engine to handle the data transferring instead of using the async DMA.
1080p SSA subtitle burn-in on Vega dGPU: 170 fps -> 230 fps
**Changes**
- Improve the Vulkan based subtitle burn-in performance
> Improve the Vulkan based subtitle burn-in performance

- Jellyfin.Api/Auth/DefaultAuthorizationPolicy/DefaultAuthorizationHandler.cs
- tests/Jellyfin.Api.Tests/Auth/DefaultAuthorizationPolicy/DefaultAuthorizationHandlerTests.cs
Api keys aren't tied to a user so succeed the requirement before checking for user permissions.
Fixes the following exception:
```
[20:13:22] [ERR] [143] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /Library/VirtualFolders.
System.ArgumentException: Guid can't be empty (Parameter 'id')
at Jellyfin.Server.Implementations.Users.UserManager.GetUserById(Guid id)
at Jellyfin.Api.Auth.DefaultAuthorizationPolicy.DefaultAuthorizationHandler.HandleRequirementAsync(AuthorizationHandlerContext context, DefaultAuthorizationRequirement requirement)
at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object …
```
> Fix auth endpoints using api key

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Fix Live TV hardware decoding
**Issues**
- HW decoder is disabled for Live TV, only HW encoder is allowed, which results in higher CPU usage.
- https://www.reddit.com/r/jellyfin/comments/11i2lno/live_tv_transcoding_instead_of_direct_streaming/
> Fix Live TV hardware decoding

- Jellyfin.Api/Controllers/DynamicHlsController.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTests.cs
- tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTestsData.cs
Its not a breaking change in FFmpeg 6.0 itself, we should have left blank or negative map the video stream map when using -filter_complex with unlabeled output.
http://ffmpeg.org/ffmpeg-all.html#Complex-filtergraphs-1
```
@subsection Complex filtergraphs
If there are any complex filtergraph output streams with unlabeled pads, they will be added
to the first output file. This will lead to a fatal error if the stream type is not supported
by the output format. In the absence of the map option, the inclusion of these streams leads
to the automatic stream selection of their types being skipped. If map options are present,
these filtergraph streams are included in addition to the mapped streams.
```
**Changes**
- Fix stream map when using filter_complex with unlabeled output
- Tiny …
> Fix stream map when using filter_complex with unlabeled output

- Emby.Server.Implementations/Library/LibraryManager.cs
- Emby.Server.Implementations/Library/Resolvers/Audio/AudioResolver.cs
- Emby.Server.Implementations/Library/Resolvers/Audio/MusicAlbumResolver.cs
- Emby.Server.Implementations/Library/Resolvers/Audio/MusicArtistResolver.cs
- Emby.Server.Implementations/Library/Resolvers/BaseVideoResolver.cs
- Emby.Server.Implementations/Library/Resolvers/ExtraResolver.cs
- Emby.Server.Implementations/Library/Resolvers/GenericVideoResolver.cs
- Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
- Emby.Server.Implementations/Library/Resolvers/PhotoResolver.cs
- Emby.Server.Implementations/Library/Resolvers/TV/EpisodeResolver.cs
- MediaBrowser.Controller/Entities/AggregateFolder.cs
- MediaBrowser.Controller/Entities/CollectionFolder.cs
- MediaBrowser.Controller/Library/ItemResolveArgs.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/AudioResolverTests.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/EpisodeResolverTest.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/MovieResolverTests.cs
There's logic in place to stack individual audio book files as chapters/parts of a single book. Unfortunately there's not yet any way to actually browse stacked files, so in most cases the file stack is ignored in favor of the directory view.
This PR adds tests and fixes a couple corner cases that should currently be ignored but weren't. There should be fewer cases where file names unexpectedly cause a folder of audio book files to collapse to a single accessible file.
**Changes**
- Clean up ItemResolveArgs:
- remove some BaseItem references
- refactor IDirectoryService to be injected where used instead of passed around in ItemResolveArgs
- Add audiobook tests for AudioResolver
- Fix cases where multiple files unexpectedly resolved into a single file representing the book
**Issues**
Fixes …
> Audiobook grouping fixes

- Jellyfin.Api/Controllers/ItemUpdateController.cs
**Changes**
Saves a height value if set for `LiveTVChannel` items. This allows an admin to specify the video height(ex. 480, 720, 1080) for channels when it is not automatically provided. This will then determine if the channel `isHD` or not.
**Issues**
Useful in conjunction with #8768
> Save TVChannel Height if set

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
**Changes**
Since we are removing the current build on install script from web, we need to manually call a production build anywhere it was assumed to already be ran. This should probably be merged before the web PR... it will double the web build time in that case, but if web is merged first, the builds will fail since the `dist` folder will not exist. EDIT: A third option would be to temporarily add the `SKIP_PREPARE` environment variable until the web PR is merged.
Related to: https://github.com/jellyfin/jellyfin-web/pull/3800
**Issues**
N/A
> Add manual web builds

- Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs
**Changes**
If attribute "tvg-logo" is not found when m3u is parsed, look for attribut "logo" instead.
**Issues**
Jellyfin uses only "tvg-logo" attribute from m3u for live tv channel icons. In conjunction with tvhead headend this wont work as tvheadend uses "logo" attribute. This PR adds looking for "logo" as fall back, so following examples will both work:
#EXTINF:-1 tvg-logo="http://tvheadendserver:9981/imagecache/8"
#EXTINF:-1 logo="http://tvheadendserver:9981/imagecache/8"
-> See https://features.jellyfin.org/posts/2065/livetv-m3u-tuner-fallback-for-channellogo
> Fall back to using "logo" attrib if "tvg-logo" is mssing in M3U-tuner

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
- Fix the bitrate scale factor for h264-to-hevc transcoding.
Don't scale the real bitrate lower than the requested bitrate.
**Issues**
- Fixes #9481
> Fix the bitrate scale factor for h264-to-hevc transcoding

- MediaBrowser.Model/Configuration/ServerConfiguration.cs
- MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
Some people don't want dummy chapters.
This makes dummy chapter generation configurable and disables it by default.
It additionally remove the dummy chapter count setting. Either you want dummy chapters or you don't.
> Add config option to disable dummy chapter generation

- debian/postinst
- fedora/jellyfin.spec
**Changes**
- Backport HWA permissions fix (#9006) to 10.8.z
**Issues**
- Fixes the permission issue on VAAPI and QSV **when install on host**:
```
[AVHWDeviceContext @ 0x55b9b2a92200] No VA display found for any default device.
Device creation failed: -22.
Failed to set value 'vaapi=va:,driver=iHD,kernel_driver=i915' for option 'init_hw_device': Invalid argument
Error parsing global options: Invalid argument
```
> Backport HWA permissions fix (#9006) to 10.8.z

- Emby.Server.Implementations/Localization/LocalizationManager.cs
- MediaBrowser.Model/Globalization/ILocalizationManager.cs
- tests/Jellyfin.Server.Implementations.Tests/Localization/LocalizationManagerTests.cs
This changes take the country code from rating strings into account instead of dropping it and falling back to the server country code when calculating rating levels.
> Extend country code rating matching

- .github/workflows/codeql-analysis.yml
- .github/workflows/commands.yml
- .github/workflows/openapi.yml
- .github/workflows/repo-stale.yaml
Because #8905 `update cirrus-actions/rebase action to v1.8` actually provides changelog information and is more meaningful than #9501 `Update actions/checkout digest to 24cb908`.
**Changes**
- Specify full version on workflow actions
> Update workflow actions to specify full version

- Emby.Server.Implementations/MediaEncoder/EncodingManager.cs
- Emby.Server.Implementations/ScheduledTasks/Tasks/ChapterImagesTask.cs
**Changes**
Change `ChapterImagesTask` to query for videos with _and_ without pre-existing chapter images, rather than just those _without_ them. This makes sure that videos with pre-existing chapter images are sent downstream where they will be deleted if the client has disabled the "Enable chapter image extraction" setting in the dashboard.
**Issues**
Fixes #9102
> Fix pre-existing chapter images not being deleted

- Emby.Naming/Common/NamingOptions.cs
- tests/Jellyfin.Naming.Tests/Video/StackTests.cs
- tests/Jellyfin.Naming.Tests/Video/VideoListResolverTests.cs
As discussed with @Shadowghost in #8004, there is a stacking rule (`VideoFileStackingRules`) in the file `Emby.Naming/Common/NamingOptions.cs` that makes no sense. It leads to a behavior that is not documented.
For example the files
- `300a.mkv`,
- `300b.mkv` and
- `300c.mkv`
will be treated as parts of the same movie. But according to the Shows documentation (https://jellyfin.org/docs/general/server/media/shows/#episodes-split-across-multiple-parts) _- don't know why this isn't also documented in the movie section -_ a `<parttype>` is required.
So normally the files should to be named like this:
- `300 parta.mkv`,
- `300 partb.mkv` and
- `300 partc.mkv`
I removed the corresponding rule and adjusted the affected test cases. Now the above naming (`300a`, ...) does no longer work. Instead …
> Fix file stacking

- MediaBrowser.Controller/Providers/ImageRefreshOptions.cs
- MediaBrowser.Providers/Manager/ItemImageProvider.cs
- MediaBrowser.Providers/Manager/MetadataService.cs
Track what ImageTypes have been provided by local NFO. Remove those from the list of all ImageTypes so they will not be overwritten by subsequent providers.
Fixes #9000
> Don't overwrite NFO images

- Emby.Naming/Common/NamingOptions.cs
- Emby.Naming/Video/VideoResolver.cs
- Emby.Server.Implementations/Library/Resolvers/ExtraResolver.cs
- MediaBrowser.Providers/Manager/ProviderManager.cs
- MediaBrowser.XbmcMetadata/Savers/MovieNfoSaver.cs
- tests/Jellyfin.Providers.Tests/Manager/ProviderManagerTests.cs
- tests/Jellyfin.Server.Implementations.Tests/Library/LibraryManager/FindExtrasTests.cs
**Changes**
- Filenames are cleaned using CleanStrings regex
- new regex to remove extra suffixes
- NFOs for extras are now read
A file named `Interview with director-interview.mkv` will now be named `Interview with director` in JF.
NFO files named the same as extra file will be read for metadata.
> Extras: Clean filename and process NFOs

- Jellyfin.Api/Controllers/DynamicHlsController.cs
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Pass encoder name, not codec.
I fixed this in my previous PR https://github.com/jellyfin/jellyfin/pull/8703 when rebasing, but forgot to notify @Shadowghost to pull it into his own https://github.com/jellyfin/jellyfin/pull/9388
> Fix audio VBR calculation

- .github/workflows/automation.yml
**Changes**
Adds a comment when a PR is labeled with a merge conflict for visibility
**Issues**
Related to point 2 in this meta discussion: https://github.com/jellyfin/jellyfin-meta/discussions/40
> Add merge conflict comment

- CONTRIBUTORS.md
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
**Changes**
Changed the ordering of the "slow" and "slower" presets in the transcoding helper, so they are aligned with the order in the settings dropdown.
Did the same to a switch-case where there is no change in behavior right now (but might prevent a bug like this in the future).
**Issues**
First raised in https://github.com/jellyfin/jellyfin/issues/9537 thanks nyanmisaka for giving it a look so incredibly quickly (and also for all the other work you do on Jellyfin)
> Fix nvenc preset order

- .github/workflows/repo-stale.yaml
**Changes**
Adds a stale action configuration to automatically close PRs with the merge conflict label after 90 days. (This matches the configuration being used in jellyfin-web now.)
**Issues**
Related to point 2 of https://github.com/jellyfin/jellyfin-meta/discussions/40
> Add action to close PRs with merge conflicts

- Jellyfin.Server/Migrations/PreStartupRoutines/MigrateMusicBrainzTimeout.cs
**Changes**
Extracted the read of old XML and write of new XML into separate methods so the `using` can fire and Dispose/Close the XML file. This prevents the inability to write the updated XML file because the file is still open (would throw on line 61 before)
**Issues**
Fixes #9558
> Fix migration for MusicBrainz

- Emby.Server.Implementations/Library/LibraryManager.cs
**Changes**
Implement the same check used at other `GetTopParentIdsForQuery` call sites so a user without any library access cannot bypass it by searching for media
**Issues**
Fixes [#1946](https://github.com/jellyfin/jellyfin/issues/1946)
> Implement check to hide all libraries when user has no access

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
The code comment says "genres, tags, studios, _person_, year?", but does no matching on common people between films. This PR augments similarity score treating people similar to tags.
> Augment similarity with person matches

- MediaBrowser.Model/Dlna/StreamBuilder.cs
**Changes**
- Fix codec checking in CodecProfiles conditions
**Issues**
- The CodeProfiles should only be applied to the matched codecs or it fails to satisfy the HEVC conditions on H.264 sources and vise versa, which breaks the fMP4 playback.
> Fix codec checking in CodecProfiles conditions

- Emby.Server.Implementations/Data/BaseSqliteRepository.cs
- Emby.Server.Implementations/Data/SqliteItemRepository.cs
Makes sure all prepared statements get properly disposed.
Also don't allocate 2 arrays to do `PrepareAll` when they can be prepared individually.
> Properly dispose prepared statements

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
- MediaBrowser.Model/Configuration/EncodingOptions.cs
**Web changes**
- https://github.com/jellyfin/jellyfin-web/pull/4492
**Changes**
- Fix the brightness of VPP tonemap
- Add the tonemap mode option RGB (requires jellyfin-ffmpeg 5.1.3+)
- Drop the deprecated `Threshold` option
**Issues**
- The VPP tonemap crushes the details of dark areas (right)
- The default tonemap mode MAX may causes the brightest areas [blown out to white](https://www.reddit.com/r/jellyfin/comments/120vc05/cant_get_tone_mapping_looking_right/) (left)
> Fix the brightness of VPP tonemap and add the tonemap mode

- Emby.Server.Implementations/Data/SqliteItemRepository.cs
In some instances, InheritedParentalRatingValue is null, which results in a guaranteed similarity score of null.
The side effect this causes is that the "More like this" section is entirely random for movies with a null InheritedParentalRatingValue.
> Fix null parental rating comparison

- Jellyfin.Api/Auth/FirstTimeSetupPolicy/FirstTimeSetupHandler.cs
- Jellyfin.Api/Controllers/SystemController.cs
`FirstTimeSetupHandler` did not prevent unauthed access after checking if the server is in setup mode.
This PR fixes that and adds 401 response annotations to applicable `SystemController` endpoints.
> Fix FirstTimeSetupHandler not failing on invalid user if not in setup mode

- MediaBrowser.Providers/Manager/ItemImageProvider.cs
- MediaBrowser.Providers/Manager/MetadataService.cs
- tests/Jellyfin.Providers.Tests/Manager/ItemImageProviderTests.cs
Builds on PR #9452 to fix screen grabber overwriting local JPGs for video primary images.
> Fix local JPG primary image for video being overwritten by screen grabber

- Emby.Server.Implementations/Library/Resolvers/PlaylistResolver.cs
- Emby.Server.Implementations/Playlists/PlaylistManager.cs
- Jellyfin.Api/Controllers/PlaylistsController.cs
- Jellyfin.Server/Migrations/Routines/FixPlaylistOwner.cs
- MediaBrowser.Controller/Playlists/Playlist.cs
**Changes**
* Introduce a new property `OpenAccess` to allow read access to the playlist for all users
* Automatically set `OpenAccess` to `true` if the playlist originates from the file system and was not created by any user
* Adopt playlist migration to handle those cases
* Add `403` response code documentation to the `PlaylistController` endpoints
> Fix access to playlists not created by a user

- Emby.Server.Implementations/Library/UserViewManager.cs
- Emby.Server.Implementations/Playlists/PlaylistManager.cs
- Emby.Server.Implementations/Playlists/PlaylistsFolder.cs
- Jellyfin.Api/Controllers/ItemsController.cs
- Jellyfin.Api/Controllers/PlaylistsController.cs
- Jellyfin.Server/Migrations/Routines/FixPlaylistOwner.cs
- MediaBrowser.Controller/Playlists/IPlaylistManager.cs
Here we go again. One last time hopefully.
**Changes**
* Remove custom annotations for `401` and `403` responses on `PlaylistsController` - They are added automatically
* `Playlists` library display is now dependant on if any user or global playlist exists, before it required at least one user playlist
* `TotalRecordCount` response from the `ItemsController` is now based off the accessible items (might have only been a problem for playlists)
* Only update user playlists files in the `FixPlaylistOwner` migration
Fixes #9569
> Fix playlists library and migration

- Emby.Dlna/PlayTo/DlnaHttpClient.cs
Not all devices (TVs/Receivers/Tuners) appear to provide well-formed Xml responses when using the 'remote control' / 'PlayTo' functionality. Currently, in such cases Jellyfin becomes unable to provide remote control or song progress, behaving like nothing happened (while the remote device starts playing), and throws an exception in the log. 
In this PR, when the XmlException is caught, it tries to escape unescaped & characters and then retries to read the Xml. If the Xml is now correct, Jellyfin will operate normally - if it is still not correct it will log the XmlException after all.
**Changes**
Add regex expression to the exception handler in DlnaHttpClient's SendRequestAsync function. Adding it there avoids interrupting the normal flow, but provides a rescue scenario for communicating …
> Rescue malformed Xml response in DLNA PlayTo

- Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
This fails to build with prerelease dotnet sdk (currently installed 7.0.300-preview.23179.2)
> Fix readonlyspan usage
