jellyfin/jellyfin

Jellyfin.Api/Controllers/ItemUpdateController.cs

Implements setting tags recurisvely.
This change only takes changed tags into account.
Added tags are added to all children, removed tags are removed from all children. Existing tags in the parent are not passed on to the children.

Set removed and added tags recursively

---

Jellyfin.Api/Controllers/StartupController.cs
Jellyfin.Server.Implementations/Users/UserManager.cs

**Changes**
It's annoying if your setup is strictly on LAN, but for the greater good, admin users must have a non-empty password

refactor: admin users must have a non-empty password

---

Emby.Server.Implementations/Data/BaseSqliteRepository.cs

**Changes**
Per the [documentation](https://www.sqlite.org/pragma.html#pragma_journal_size_limit) for `journal_size_limit`, when set to `0`, SQLite will "always truncate rollback journals and WAL files to their minimum size".
This pr changes Jelly's defaults from `0` to `134_217_728` (aka, 128MiB).
While I have no performance tests, a value of `0` seems problematic given we are currently using the `journal_mode = WAL` option (since one of the purposes of using WAL is to prevent needing to remove/truncate the journal after each operation).
**Issues**
Related: #9044

Increase journal_size_limit Defaults

---

Emby.Server.Implementations/ConfigurationOptions.cs
Emby.Server.Implementations/Data/SqliteItemRepository.cs
MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs

**Changes**
This pr adds support for an operator to modify the [`cache_size` PRAGMA option](https://www.sqlite.org/pragma.html#pragma_cache_size) dynamically. This allows an operator to increase the `cache_size` (currently hardcoded to about 82MiB) to troubleshoot performance or to decrease this if they are running in a memory constrained environment (the SQLite default value is about 2MiB).
I would propose this option as officially unsupported by Jellyfin project for now - e.g. "Here be dragons".
**Issues**
Resolves #9646.

Source SQLite cache_size from an Environment Variable

---

tests/Jellyfin.Server.Implementations.Tests/Data/SqliteItemRepositoryTests.cs

Fix breaking test from https://github.com/jellyfin/jellyfin/pull/9666

Mock configuration to get SqliteCacheSizeKey during test

---

MediaBrowser.Model/Dto/BaseItemDto.cs

This fixes a regression from #9222 where the LUFS field in the OpenAPI spec was not nullable. This will cause issues with the Kotlin SDK.
**Changes**
- Make LUFS property nullable in BaseItemDto
**Issues**

Make LUFS property nullable in BaseItemDto

---

Emby.Server.Implementations/Library/Resolvers/TV/SeasonResolver.cs
MediaBrowser.Controller/Entities/TV/Series.cs
MediaBrowser.Providers/Manager/MetadataService.cs
MediaBrowser.Providers/TV/SeriesMetadataService.cs
MediaBrowser.XbmcMetadata/Parsers/SeasonNfoParser.cs
MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs

I'm not sure if I've done this correctly. The main problem is that season names are within the series NFO, so we need to process this data before the seasons themself are processed.
Fixes #8489

Implement NFO named season parsing

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Rearrage the Amd vaapi-vulkan pipeline for synchronization
**Issues**
The [vaSyncSurface()](https://gitlab.freedesktop.org/mesa/mesa/-/blob/23.1/src/gallium/frontends/va/surface.c?ref_type=heads#L123-L127) in radeonsi_drv_video only works for decoder or encoder entries, which means vpp frames never get synchronized in [vaapi->drm/vulkan "reverse" mapping](https://github.com/FFmpeg/FFmpeg/blob/ea3d24bbe3c58b171e55fe2151fc7ffaca3ab3d2/libavutil/hwcontext_vulkan.c#L2963-L2964). Use [vulkan_map_to_drm](https://github.com/FFmpeg/FFmpeg/blob/ea3d24bbe3c58b171e55fe2151fc7ffaca3ab3d2/libavutil/hwcontext_vulkan.c#L3306) instead.
- Fix tearing and artifacts when using vulkan subtitle burn-in

Rearrage the Amd vaapi-vulkan pipeline for synchronization

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Fix #9642 backport
- Removed unused lines
**Issues**
- Fixes 4c8d3827
```
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
at System.String.Format(IFormatProvider provider, String format, Object arg0, Object arg1, Object arg2)
at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetHwTonemapFilter(EncodingOptions options, String hwTonemapSuffix, String videoFormat)
```

Fix #9642 backport

---

Jellyfin.Api/Controllers/LibraryController.cs
MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs
MediaBrowser.Controller/BaseItemManager/IBaseItemManager.cs
MediaBrowser.Controller/Entities/Audio/MusicArtist.cs
MediaBrowser.Controller/Entities/BaseItem.cs
MediaBrowser.Controller/Entities/Folder.cs
MediaBrowser.Controller/Library/MetadataConfigurationExtensions.cs
MediaBrowser.Controller/Providers/IProviderManager.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
MediaBrowser.Model/Configuration/ServerConfiguration.cs
MediaBrowser.Providers/Manager/ProviderManager.cs
MediaBrowser.Providers/Plugins/StudioImages/StudiosImageProvider.cs
src/Jellyfin.Drawing/ImageProcessor.cs

* Removes MetadataThrottler, we already limit the amount of directories to start scanning (this PR multiplies this limit by 2) in and the number of ffprobe instances, this extra throttling doesn't seem necessary.
* Increases the amount of thumbnail extraction processes from 2 to 2 * the number of threads

Reduce bottlenecks scan code

---

Directory.Packages.props
src/Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
src/Jellyfin.Drawing.Skia/StripCollageBuilder.cs

Building upon the work of #8050 and discussion in chat, using several character groups to evaluate if the text drawn on library images should be handled LTR or RTL
**Changes**
- Added RTL detection for following text cultures: 
- Arabic
- Armenian
- Hebrew
- Syriac
- Thaana
**Issues**
#9610

Fixed RTL text not beeing rendered properly on Lib images

---

Jellyfin.Api/Controllers/DynamicHlsController.cs
Jellyfin.Api/Helpers/DynamicHlsHelper.cs
Jellyfin.Data/Enums/VideoRange.cs
Jellyfin.Data/Enums/VideoRangeType.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
MediaBrowser.Model/Dlna/ConditionProcessor.cs
MediaBrowser.Model/Dlna/ContentFeatureBuilder.cs
MediaBrowser.Model/Dlna/DeviceProfile.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs
MediaBrowser.Model/Dlna/StreamInfo.cs
MediaBrowser.Model/Entities/MediaStream.cs

**Changes**
Migrates `VideoRange` and `VideoRangeType` to enum and implements additional profile operators.
**Issues**
Fixes #9313

Migrate VideoRange and VideoRangeType to Enum

---

Emby.Server.Implementations/Collections/CollectionManager.cs
Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionPathsTask.cs
MediaBrowser.Controller/Collections/ICollectionManager.cs

**Changes**
Added Task to run at startup to cleanup collection items that are not longer physical present.
Updated interface of ICollectionManager to get reference to the Boxsets location to prevent duplicate magic strings.
**Issues**
#1907

Added CleanupCollection task

---

Emby.Server.Implementations/Data/SqliteItemRepository.cs

**Changes**
This change improves tag searching. Previously, `(Tags not null and Tags like @SearchTermContains)` searched against the composed `tag1|tag2|tag3` value. That approach had no good way of differentiating between `str1` and `prefix...str1...suffix` which might have entirely different meaning (e.g. searching `cia` would turn up content from `artifiCIAl intelligence`).
This PR provides bias towards startswith and equals, additionally biasing content with multiple matching tags.

Augment tag searching to consider individual ItemValues instead of the delimited tags field

---

Jellyfin.Server/Migrations/MigrationRunner.cs
Jellyfin.Server/Migrations/PreStartupRoutines/MigrateNetworkConfiguration.cs

fix #9983: [Issue]: Starting freshly installed Jellyfin server for the second time fails with MigrateNetworkConfiguration error
**Changes**
migration.xml now is written also when  migrations are skipped during a fresh install of Jellyfin server
**Issues**
fixes #9983

fix #9983 MigrateNetworkConfiguration error

---

Emby.Dlna/PlayTo/DlnaHttpClient.cs

**Issues**
CopyToAsync doesn't rewind the stream

fix: set memorystream position after copying

---

Emby.Server.Implementations/Localization/Ratings/de.csv
tests/Jellyfin.Server.Implementations.Tests/Localization/LocalizationManagerTests.cs

**Changes**
This PR adds the format which gets written by
the tool TinyMediaManager which can be used to
manage large media databases comfortably.
TMM writes wither multiple Codes and/or space
divided german FSK codes, but can't be configured
to only use the number or the slash delimited variant.
After this change the parental control for Libraries
managed with TMM and presented/loaded into Jellyfin
should work again.

Change: Add TinyMediaManager compatibility for german parental rating

---

MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs

Seems like FFprobe can return a list of formats.
**Changes**
* Split format input before running normalization and run normalization on all input formats
**Issues**
Fixes #10046

Fix format normalizer for multiple input formats

---

Jellyfin.Api/Controllers/SubtitleController.cs
Jellyfin.Api/Models/SubtitleDtos/UploadSubtitleDto.cs
MediaBrowser.Controller/Subtitles/SubtitleResponse.cs
MediaBrowser.Providers/Subtitles/SubtitleManager.cs

**Changes**
Added `IsHearingImpaired` flag to both `UploadSubtitleDto` and `SubtitleResponse` which then adds a `.sdh` suffix to filename when saving (This should work with opensubtitles (pr soon™️))
Also made subtitle deletion async, this fixes a bug on the frontend where after deleting a subtitle it would refresh the subtitle list before the deletion was actually finished. This resulted in user seeing the deleted sub track, attempting to delete it again would actually delete the subtitle track below it since they are ID-based
**Issues**
None
UI: https://github.com/jellyfin/jellyfin-web/pull/4728

Add ability to upload (and save) SDH subtitles

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Only disable the `global_header` for AMD HEVC encoder
**Issues**
- Fixes VA-API AV1 encoder on AMD https://github.com/jellyfin/jellyfin-ffmpeg/issues/264#issuecomment-1640566294

Only disable the global_header for AMD HEVC encoder

---

Jellyfin.Api/Controllers/UserController.cs

**Changes**
This fixes the check whether a warning should be logged when resetting the password from outside the local network.
**Issues**
Fixes #10059

Fix the is-local check when resetting the password

---

Emby.Server.Implementations/HttpServer/WebSocketConnection.cs
Emby.Server.Implementations/HttpServer/WebSocketManager.cs
Emby.Server.Implementations/Session/SessionManager.cs
Jellyfin.Api/WebSocketListeners/ActivityLogWebSocketListener.cs
Jellyfin.Api/WebSocketListeners/SessionInfoWebSocketListener.cs
Jellyfin.Networking/Extensions/NetworkExtensions.cs
Jellyfin.Server.Implementations/Events/Consumers/Security/AuthenticationFailedLogger.cs
Jellyfin.Server.Implementations/Events/Consumers/Security/AuthenticationSucceededLogger.cs
Jellyfin.Server.Implementations/Events/Consumers/Session/PlaybackStartLogger.cs
Jellyfin.Server.Implementations/Events/Consumers/Session/PlaybackStopLogger.cs
Jellyfin.Server.Implementations/Events/EventingServiceCollectionExtensions.cs
MediaBrowser.Controller/Events/Authentication/AuthenticationRequestEventArgs.cs
MediaBrowser.Controller/Events/Authentication/AuthenticationResultEventArgs.cs
MediaBrowser.Controller/Net/BasePeriodicWebSocketListener.cs
MediaBrowser.Controller/Net/IWebSocketConnection.cs
tests/Jellyfin.Server.Implementations.Tests/HttpServer/WebSocketConnectionTests.cs

**Changes**
* Add wrapper object for authentication events, removing stuff like API tokens from event messages (prevents leaking them to e.g. plugins)
* Add corresponding item id tp start/stop playback events
* Enforce access permissions on WebSocketListeners
Note: The now secured listeners aren't working in any meaningful way. The WebSockets handling really requrires an overhaul....
Fixes #9975

Various improvements

---

MediaBrowser.Model/Providers/RemoteSubtitleInfo.cs

**Changes**
Added `Forced`, `HearingImpaired`, `MachineTranslated`, `AiTranslated` and `FrameRate` properties to RemoteSubtitleInfo, all this info is provided by opensubtitles but we don't display it
UI in https://github.com/jellyfin/jellyfin-web/pull/4727
**Issues**
Fixes: https://github.com/jellyfin/jellyfin/issues/10027

Add support for more remote subtitle info

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

**Changes**
The composer is not set in some of my m4a files. For some reason TagLibSharp returns the composer as an empty string in this case. This causes an exception in PeopleHelper.AddPerson, and thus probing fails.
IMHO we can simply ignore empty values.
**Issues**
Fixes: #10061

Fix the probing of m4a metadata with missing composer

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

**ROCm OpenCL runtime is not needed anymore when using HDR tone-mapping on Polaris/gfx8.**
This change requires [jellyfin-ffmpeg5 5.1.3-4](https://github.com/jellyfin/jellyfin-ffmpeg/pull/268) or [jellyfin-ffmpeg6 6.0-5](https://github.com/jellyfin/jellyfin-ffmpeg/pull/267) or newer versions.
**Changes**
- Expand AMD VA-API Vulkan filtering support to Polaris/gfx8
(Older cards don't benefit as much because they don't support 10-bit HEVC decoding)
**Issues**
- ROCm runtime is the biggest issue 😅

Expand AMD VA-API Vulkan filtering support to Polaris/gfx8

---

Emby.Naming/Common/NamingOptions.cs
tests/Jellyfin.Naming.Tests/TV/DailyEpisodeTests.cs

**Changes**
I've encountered titles with the date formatted using spaces between the numbers recently ("2023 07 28"). This adds that as a date format.
**Issues**
None

Add parsing for dates with spaces

---

Emby.Server.Implementations/Localization/Ratings/fr.csv

**Changes**
I've added "TP" as a rating (French equivalent of U) meaning "Tous publics".
**Issues**
Some "universal" public movies are classified "U", and some are "TP" (meaning the same thing) in French UI. Without "TP" in this file, if you add a parental control, "TP" movies are not available.

Fix French parental rating system

---

Emby.Server.Implementations/Dto/DtoService.cs
MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs
MediaBrowser.Model/Dto/BaseItemDto.cs

Add album gain. This will use the smallest gain from the album the track is from instead of the individual track gain. This keeps the volume range between tracks in an album.
**Changes**
Add album gain dto
Frontend: https://github.com/jellyfin/jellyfin-web/pull/4741

Album gain

---

Emby.Server.Implementations/Library/LibraryManager.cs
Emby.Server.Implementations/LiveTv/TunerHosts/BaseTunerHost.cs
Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
Emby.Server.Implementations/LiveTv/TunerHosts/M3UTunerHost.cs

**Changes**
MemoryCache uses a concurrentdictionary under the hood, so there's really no benefit to using it in singleton classes.

refactor: use ConcurrentDictionary when IMemoryCache isn't needed

---

Jellyfin.Api/Helpers/TranscodingJobHelper.cs
MediaBrowser.Controller/MediaEncoding/JobLogger.cs
MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
src/Jellyfin.MediaEncoding.Keyframes/FfProbe/FfProbeKeyframeExtractor.cs

**Changes**
Seems like we must dispose the streamreaders manually to avoid (temporarily) leaking SafeFileHandles: https://source.dot.net/#System.Diagnostics.Process/System/Diagnostics/Process.cs,894

fix: accessing Standard* of a Process requires manually disposing them afterwards

---

Emby.Server.Implementations/Data/SqliteItemRepository.cs
jellyfin.ruleset

Reuse 1 StringBuilder to generate multiple clauses instead of creating Lists of strings to join

Reduce the amount of allocations in GetWhereClauses

---

debian/rules

I tried to compile on Rock 5B, but it`s fail
log:
```bash
make[1]: Entering directory '/root/jellyfin'
dotnet publish -maxcpucount:1 --configuration Release --output='/root/jellyfin/usr/lib/jellyfin/bin' --self-contained --runtime  \
-p:DebugSymbols=false -p:DebugType=none Jellyfin.Server
Required argument missing for option: --runtime
```
I checked the build script and found that it used arch to obtain the architecture. However, on the Armbian system, he returned aarch64 instead of the existing arm64 in the script, which resulted in the runtime missing parameters
```bash
root@rock-5b:~/jellyfin# arch
aarch64
root@rock-5b:~/jellyfin# neofetch
root@rock-5b
------------
█ █ █ █ █ █ █ █ █ █ █      OS: Armbian (23.08.0-trunk) aarch64
███████████████████████     Host: Radxa ROCK 5B
▄▄██ …
```

Fix debian/ubuntu arm64 build error,runtime argument missing

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Fix performance loss of QSV HDR tone-mapping on Windows
(The VPP passthrough cannot completely avoid the problem, but brings visible performance loss.
jellyfin-ffmpeg 5.1.3-5, 6.0-6 or newer contains a potent fix than this one.)
**Issues**
- See also https://github.com/jellyfin/jellyfin-ffmpeg/pull/275

Fix performance loss of QSV HDR tone-mapping on Windows

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

`EncodingOptions.TranscodingTempPath` can be empty (and is by default), the correct way to get the trancode path is
`EncodingConfigurationExtensions.GetTranscodePath` which falls back to `$CACHEPATH/transcodes` when `EncodingOptions.TranscodingTempPath` is null or empty.

Use the correct trancode path

---

Jellyfin.Api/Controllers/DynamicHlsController.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Fix AV1 playback in LiveTV
- Fix transcoding when the bitrate is too low
**Issues**
- [h264_qsv @ 000001df5372ddc0] Error initializing the encoder: invalid video parameters (-15)

Fix AV1 playback in LiveTV

---

Emby.Server.Implementations/Session/SessionManager.cs

**Changes**
Removes the limitation of only allowing one active auth token per device id. This removes the need for clients to implement hacks to enable users to switch logins without entering a password every time.
**Issues**
It's been mentioned in chat many times, but I don't see an issue or discussion for this :eyes:

Remove one session per device id limitation

---

Emby.Server.Implementations/TV/TVSeriesManager.cs
Jellyfin.Api/Controllers/TvShowsController.cs
MediaBrowser.Model/Querying/NextUpQuery.cs

**Changes**
Adds an option to enable resumable items to be included in next up requests. This defaults to true to enable the original behavior of finding the next episode of a series that should be played.
Clients will probably want to add the new request parameter to prevent the duplication on the home screen between next up and continue watching. ~~Once this is merged I plan to add a new home screen section type that uses this to present a single row for next up + continue watching (as has been requested [here](https://features.jellyfin.org/posts/1055/give-the-option-to-combine-next-up-and-continue-watching)).~~ Actually this still won't fully meet the needs for a combined up next + continue watching home screen section since it does not include movies. :thinking: 
PR that introduced …

Add option to include resumable items in next up requests

---

fedora/jellyfin-selinux-launcher.sh
fedora/jellyfin.spec

Fix the Jellyfin launcher on SELinux-enabled systems. Replace /usr/bin/jellyfin symlink with a 2-line shell script, which itself calls the target of the symlink.
- The symlink causes a problem with SELinux because it understands symlinks.
- This shell script automatically inherits the correct SELinux context.
**Changes**
- Add 2-line shell script that calls the Jellyfin executable
- Update Fedora spec file to use new launcher script.
**Issues**
Fixes [Issue 8114](https://github.com/jellyfin/jellyfin/issues/8114)

Add a small Bash script to launch Jellyfin, instead of a symlink.

---

fedora/jellyfin-selinux-launcher.sh

**Changes**
Per https://www.shellcheck.net/wiki/SC2068:
Double quotes around $@ (and similarly, ${array[@]}) prevents globbing and word splitting of individual elements, while still expanding to multiple separate arguments.

Avoid shell expansion issues

---

.ci/azure-pipelines-package.yml

**Changes**
Still run the collect script on build on failures, so build failures on a specific platform (*cough fedora*) does not prevent all builds from being published.
**Issues**
N/A

Run collect script on failures

---

.github/workflows/auto-bump_version.yml
.github/workflows/repo-bump-version.yaml

This PR adds a basic GH Action workflow to automatically run the [bump_version](https://github.com/jellyfin/jellyfin/blob/master/bump_version) script on a `release-x.y.z` branch as soon as a release gets published and commit its changes to that branch.
I made the assumption that the CI triggered to publish a release propergates its results back via the GH Checks API, terefor the workflow will wait until all checks of the tagged commit are successful or will time out after 1h.
* for this to work on 10.7.x we would have to 'backport' this workflow into that branch (as it will only work if it exists in the branch associated to the release)
* for RC versions the auto bump wont trigger as I cannot predict the future and say if the next release will be a `rc` too. However, this action can be …

add auto-bump_version workflow

---

Emby.Server.Implementations/ApplicationHost.cs
Emby.Server.Implementations/IO/FileRefresher.cs
Emby.Server.Implementations/IO/LibraryMonitor.cs
Emby.Server.Implementations/IO/ManagedFileSystem.cs
Emby.Server.Implementations/IO/MbLinkShortcutHandler.cs
Emby.Server.Implementations/Library/LibraryManager.cs
MediaBrowser.Model/IO/IFileSystem.cs
jellyfin.ruleset

* Enable nullable
* Add a fast return to ReportFileSystemChanged when path should be ignored
* Use Span overloads of Path.* functions where possible
* IFileSystem: remove NormalizePath as Path.TrimEndingDirectorySeparator already checks if it's a root path

Minor LibraryMonitor improvements

---

Directory.Packages.props

```
Thread 16 ".NET ThreadPool" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fbeae7fc6c0 (LWP 15740)]
0x00007fbead7b33e0 in ?? ()
from /.../dev/jellyfin/Jellyfin.Server/bin/Release/net7.0/runtimes/linux-x64/native/libSkiaSharp.so
```

Downgrade SkiaSharp.NativeAssets.Linux to prevent segfault

---

.github/workflows/repo-bump-version.yaml

**Changes**
Fix version tagging in repo-bump-version workflow so renovate will update all actions/checkout versions together.
**Related**
To be in sync this depends on #10260
Supersedes #10258

Fully specify version tags for renovate

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Fix A53 CC SEI breaking H26x_VAAPI hardware encode
**Issues**
- Fixes https://github.com/jellyfin/jellyfin/issues/9687

Fix A53 CC SEI breaking H26x_VAAPI hardware encode

---

fedora/jellyfin.spec

**Changes**
Switch the sed separator from '/' to '|', this makes it far clearer to parse a POSIX path, and resolves the build issues
with the CentOS and Fedora docker builds where we can't easily escape the '/' chars from the buildroot var
**Testing**
This is based on a failing CI job:
```
docker build -f deployment/Dockerfile.fedora.amd64 -t jellyfin-server-fedora.amd64 --label "org.opencontainers.image.url=https://github.com/jellyfin/jellyfin" --label "org.opencontainers.image.revision=2ae2145192e47887d4168ad383e021e50de70ef7"  deployment
docker image ls -a && docker run -v $(pwd)/deployment/dist:/dist -v $(pwd):/jellyfin -e IS_UNSTABLE="yes" -e BUILD_ID=20230926.1 jellyfin-server-fedora.amd64
```
Sed still fires, but can handle the '/' char without any problems:
```
+ /usr/bin/install …
```

Fix sed failing on Docker builds for CentOS/Fedora

---

Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs

Fixes issue #6527
Removed the the condition that checks if a channel has an id (tv guide id), it uses it as an unique id with md5 hash.
This was kinda wrong since :
1. We can have multiple channels lines in a m3u which uses same tv guide (SD and HD version of same broadcast for example)
2. The behavior of the code was not explicit, all the code flow kept all channels until we write them down to the database , then since they have same unique generated id , the first channel is written to the db and then the following channel with same id overwrites it.
I Thought of adding a checkbox to keep old behavior at m3u tuner level but I am quite sure the condition/old behavior is not needed and was wrong/not intended.

Allow repeated same tv guide channels on M3U tuner

---

debian/jellyfin.init

**Changes**
Add a shebang to the init script used in non-systemd distros.
**Issues**
#10317

Add shebang to jellyfin.init

---

Emby.Server.Implementations/Library/Resolvers/PhotoResolver.cs
MediaBrowser.Controller/Resolvers/IItemResolver.cs
MediaBrowser.Controller/Resolvers/ItemResolver.cs

Backdrops/fanart are generated as (backdrop)|(fanart)[0-9]*.extension
Fixes #7830

PhotoResolver: change how generated images are detected

---

.github/workflows/repo-stale.yaml

GitHub actions are difficult to test locally, so I'm making some educated guesses about why the stale action was not running correctly. It looks like the primary culprit is that the action is not caching state and is subsequently starting with the most recent issue/PR and never getting past the first 75 as described in [this issue](https://github.com/actions/stale/issues/1090#issuecomment-1710940734). A view of the action logs corroberates this.
**Changes**
- Adds the `actions: write` permission to enable writing to the cache to maintain state
- Updates the `cron` to run twice daily instead of once
- Updates the verbiage on the `stale-issue-message` to be more concise
- Updates the link for getting help
- Adds a `close-issue-message`
**Issues**
#10333

#10333 Updates issue stale action to fix issues with not running

---

Jellyfin.Api/Helpers/StreamingHelpers.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Support transcoding audio to PCM format; this allows the client to play directly through the I2S bus without decoding. This feature is particularly useful when playing with MCUs.
**Changes**
Add support for transcode audio file to PCM format
1. set file ext name to pcm when audiocodec is pcm_*
2. add pcm params for ffmpegs

Add support for transcode audio file to PCM format

---

.github/workflows/repo-stale.yaml

I haven't been able to keep up with notifications lately (not that I'm complaining about the recent increase in activity) and noticed this too late to chime in.
This file ended up with renovate comment tags for "v8" and "v8.0.0" with the same hash. This will result in two renovate pull requests whenever there is a new release because it doesn't see them as being the same thing.
Fully tagging the version is preferable because it causes renovate to link to the release notes instead of just the diff between hashes.
**Changes**
- Fix renovate version tag to be consistent within the file
**Issues**

Add full version tag for renovate

---

Emby.Server.Implementations/Library/LibraryManager.cs
tests/Jellyfin.Server.Integration.Tests/Controllers/PersonsControllerTests.cs

return null instead.
GetStudio, GetGenre, GetMusicGenre, GetYear, GetArtist still create a new one when the requested one doesn't exist
Fixes #3901

Don't create non existent persons in LibraryManager.GetPerson

---

Jellyfin.Api/Controllers/ImageController.cs
Jellyfin.Api/Controllers/SubtitleController.cs
MediaBrowser.Providers/Manager/ImageSaver.cs

Is way more efficient
Tested with a 185676 byte base64 encoded png (size before base64 encode was 137446 bytes)
```
| Method | Mean     | Error    | StdDev   | Gen0     | Gen1     | Gen2     | Allocated |
|------- |---------:|---------:|---------:|---------:|---------:|---------:|----------:|
| Old    | 905.3 us | 17.81 us | 17.50 us | 154.2969 | 153.3203 | 153.3203 | 891.25 KB |
| New    | 349.4 us |  2.44 us |  2.29 us |   2.4414 |        - |        - |   7.18 KB |
```
Bench code:
```cs
[MemoryDiagnoser]
public class FromBase64Benches
{
private Stream InputStream()
=> File.OpenRead("Test Data/image.base64");
private Stream OutPutStream()
=> File.OpenWrite("/dev/null");
[Benchmark]
public async Task Old()
{
using var input = new StreamReader(InputStream());
var str = await …
```

Use CryptoStream to convert stream from base64

---

MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs
tests/Jellyfin.XbmcMetadata.Tests/Parsers/EpisodeNfoProviderTests.cs

Now multi-episodes file show all episodes titles and overviews instead of only just the first episode's title and overview.
**Changes**
- Iterates through each episodedetails block. Grabs the title and plot and concats them together with a " / " delimiting each other.
**Issues**
Partially fixes #2980

Combine Title and Overview for multi-episodes files for NFO file

---

MediaBrowser.XbmcMetadata/Savers/MovieNfoSaver.cs

`<filename>.nfo` is used for store custom information of movie uploader on some private tracker bittorrent website, which is not a valid movie metadata nfo file. Overwrite `<filename>.nfo` will lead errors with file sharing. Therefor using `movie.nfo` first may be better when `<filename>.nfo` also exists.
**Changes**
Use `movie.nfo` first when `<filename>.nfo` also exists.
**Issues**
Fixes #1558

Fix using movie.nfo first when <filename>.nfo also exists

---

MediaBrowser.Providers/Manager/ProviderManager.cs

```
System.ArgumentException: Guid can't be empty (Parameter 'id')
at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Guid id) in /home/loma/dev/jellyfin/Emby.Server.Implementations/Library/LibraryManager.cs:line 1224
at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue() in /home/loma/dev/jellyfin/MediaBrowser.Providers/Manager/ProviderManager.cs:line 983
```
This doesn't fix the cause, but at least they won't make it into the queue

Empty Guids shouldn't make it into the refresh queue

---

Directory.Packages.props

Many distros seem to be behind on SDK updates, which causes issues. Temporarily downgrade the package.

chore(deps): downgrade IDisposableAnalyzers to 4.0.4

---

.github/workflows/repo-stale.yaml

Attempts to work around the issues described in #10333. The stale action is not caching state between runs. This workaround is an attempt to increase the operations per run so that every issue can be looked at in every run -- no need to maintain state.
NOTE: There is a chance that running 500 operations this quickly will result in GitHub throttling our bot and/or blocking it for up to 1 hour. If that happens, we'll reduce the value again.
**Changes**
- Returns the cron schedule to once a day instead of twice daily since we are now processing every issue in every run
- Adds the `ascending: true` property to process the older items first
- Increases the `operations-per-run` to 500 to process the entire list of open issues
**Issues**
#10333

#10333 Increases operations per run of GitHub 'stale' action

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Usually the iGPU is considered the first device `/dev/dri/renderD128`,
but in rare cases the iGPU can become the second `/dev/dri/renderD129`.
**Changes**
- Fix mismatch between intel VAAPI UMD/KMD in rare cases
**Issues**
- Fixes #8740

Fix mismatch between intel VAAPI UMD/KMD in rare cases

---

Jellyfin.Api/Constants/Policies.cs
Jellyfin.Api/Controllers/SubtitleController.cs
Jellyfin.Data/Entities/User.cs
Jellyfin.Data/Enums/PermissionKind.cs
Jellyfin.Server.Implementations/Users/UserManager.cs
Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
MediaBrowser.Model/Users/UserPolicy.cs

Add new feature: ability for a user to "Edit subtitles" without administrator rights
**Changes**
Create a new Jellyfin.Data/Enums/PermissionKind: EnableSubtitleManagement
Add that permission to the UserPolicy
Related PR
- Front-end: [jellyfin-web](https://github.com/jellyfin/jellyfin-web/pull/4883)
TODO
- Fix [permissions issue](https://github.com/jellyfin/jellyfin-plugin-opensubtitles/issues/131#issuecomment-1677299539) in opensubtitle plugin
**Issues**
https://features.jellyfin.org/posts/185/non-admin-users-download-subtitles

add EnableSubtitleManagement permission

---

Jellyfin.Api/Controllers/ItemsController.cs

This reverts commit 98c6c34fbbcdb556873bdcdb577fbc55a296b650.
**Changes**
It doesn't seem like playlists currently have parent ids, so including parent ids in requests cause no playlists to be displayed. I think reverting this is the best course of action for 10.8.
**Issues**
Fixes #10272

Fix playlist listings

---

Directory.Packages.props
src/Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
src/Jellyfin.Drawing.Skia/SkiaEncoder.cs

**Changes**
According to https://github.com/mono/SkiaSharp.Extended/issues/83#issuecomment-674318895 we never should've used SkiaSharp.Svg and according to [Svg.Skia README](https://github.com/wieslawsoltes/Svg.Skia), it should be a drop-in replacement:
> The Svg.Skia can be used in same way as the SkiaSharp.Extended.Svg (load svg files as SKPicture).
I do not have any SVGs to test with.

chore(deps): use Svg.Skia instead of the deprecated SkiaSharp.Svg

---

src/Jellyfin.Drawing.Skia/SkiaEncoder.cs

**Changes**
Judging by https://github.com/mono/SkiaSharp/issues/829#issuecomment-504835148, it's safe to cache SKImageFilter. We could also cache SKPaint but we would need an object pool since it isn't thread safe.

refactor: cache the resize image filter

---

.github/workflows/repo-stale.yaml

The changes (workaround) to increase the operations per run for stale issues is working. This will do the same thing for the stale PR check.
**Changes**
- Increases the operations per run to `150` for stale PR checks
- Adds `ascending: true` to process PRs from oldest first
**Issues**
#10333

#10333 Fix for stale PRs check: increase operations, process ascending

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
Changed the scaleFactor limit from max 1 to min 1.
**Issues**
Fixes bad transcode picture quality (e.g. from hevc to h264), as maximum transcoding bitrate is limited to the input bitrate now.
(introduced by pull request  https://github.com/jellyfin/jellyfin/pull/9485)

Fix scaleFactor limit - Backport #9738

---

Emby.Server.Implementations/Session/SessionManager.cs
tests/Jellyfin.Server.Implementations.Tests/SessionManager/SessionManagerTests.cs

Fixes https://github.com/jellyfin/jellyfin/issues/10309

Don't remove all tokens if invalid header is provided

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
tests/Jellyfin.MediaEncoding.Tests/Probing/ProbeExternalSourcesTests.cs

**Changes**
Adds the user_agent source config in the ffprobe MediaEncode command.
**Issues**
ex. Fixes #10175

Forward user_agent config to ffprobe

---

Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj

Should fix crashes on M1 machines and fixes the webp CVEs

Update SkiaSharp (v2.88.6) and BlurHashSharp (v1.3.1)

---

Jellyfin.Api/Controllers/TvShowsController.cs

The docstring for /Upcoming looks very similar to /NextUp, also including the same return value, when it should be slightly different, correct it.

Correct docstring for /Upcoming

---

debian/conf/jellyfin
fedora/jellyfin.env

**Changes**
* Add `MALLOC_TRIM_THRESHOLD_=131072` to fix Skia memory issues
**Issues**
Partially fixes #6306

 Add MALLOC_TRIM_THRESHOLD_ to default ENV

---

CONTRIBUTORS.md
MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeProvider.cs

Now multi-episodes file show all episodes titles and overviews instead of only just the first episode's title and overview.
**Changes**
- Checks if there is an IndexNumberEnd. If it exist, do multiple request for all episodes between IndexNumber and IndexNumber end. Concats the name and overviews with a " / " delimiting each other.
**Issues**
Partially fixes  #2980

 Combine Title and Overview for multi-episodes files for the TMDB provider

---

Directory.Packages.props

**Changes**
This resolves the segfaults on library scan by reverting the recent upgrades related to SkiaSharp 2.88.6.  Upstream defect here: https://github.com/mono/SkiaSharp/issues/2645
The problem is most likely [this line in BlurHashEncoder's resize/encode method](https://github.com/Bond-009/BlurHashSharp/blob/5befb4f383d9f5270897076af4427cf47e2838a6/src/BlurHashSharp.SkiaSharp/BlurHashEncoder.cs#L84) called by Jellyfin [here](https://github.com/jellyfin/jellyfin/blob/9d4352789d6ff7a59cdda37e3bbb02aa740ed99f/src/Jellyfin.Drawing.Skia/SkiaEncoder.cs#L198).
**Issues**
Fixes #10532

Revert SkiaSharp upgrade, fix library scan crashes

---

CONTRIBUTORS.md
Emby.Server.Implementations/Updates/InstallationManager.cs

**Changes**
Ternary operator in the PublishAsync method was causing plugin installed event not raised. Logic changed with simple if/else statement.  
(Screenshot)
**Issues**
Fixes #10620

Fix: Plugin Installed Alerts missing from Admin Dashboard #10620

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

The previous behavior using `eof_action=endall` and `shortest=1` would end the video stream if one of the input stream (video, subtitle) ends. In some cases the duration of the overlayed subtitles is shorter than the video stream, causing the output to end when the subtitles end and dropping the remaining video stream.
This commit changes this behavior so `eof_action=pass` is used instead, which continues passing the video stream through even if the subtitles end earlier [1]. `shortest=1` is also removed, as this option implies `eof_action=endall`.
If the subtitle stream has a higher duration than the video stream, the output will also end with the video stream without `shortest=1`, as the video stream is the primary input to the `overlay` filter.
Fix #10698
[1] …

Use `eof_action=pass` when overlaying subtitles

---

.github/workflows/ci-tests.yml

We already have dedicated OpenAPI actions to upload those artifacts. No idea why the tests uploaded it. This should also fix the CI issue related to GH Actions. (not the build issues on Azure)
**Changes**
- Remove OpenAPI artifact upload from test workflow 
**Issues**

Remove OpenAPI artifact upload from test workflow

---

.github/workflows/ci-tests.yml

The `ci-tests.yml` workflow only specified the first number of the version for used actions, while all the other workflows fully-specify the version. Renovate plays nicer with full version numbers and as seen in #10727 having a mix works but shows it as multiple updates even though they're all the same hash.
**Changes**
- change ci-tests.yml to fully specify action versions

Fully specify github action versions

---

Jellyfin.Server.Implementations/Devices/DeviceManager.cs
MediaBrowser.Model/Devices/DeviceInfo.cs

**Changes**
Adds CustomName to /Devices API endpoint
Related to https://github.com/jellyfin/jellyfin-web/pull/4887
**Issues**

Update /Device endpoint to return CustomName

---

deployment/build.centos.amd64
deployment/build.debian.amd64
deployment/build.debian.arm64
deployment/build.debian.armhf
deployment/build.fedora.amd64
deployment/build.linux.amd64
deployment/build.linux.amd64-musl
deployment/build.linux.arm64
deployment/build.linux.armhf
deployment/build.linux.musl-linux-arm64
deployment/build.macos.amd64
deployment/build.macos.arm64
deployment/build.portable
deployment/build.ubuntu.amd64
deployment/build.ubuntu.arm64
deployment/build.ubuntu.armhf
deployment/build.windows.amd64

This PR makes a modification to the bash build scripts to quote variables that could contain directories with spaces. This prevents bash from word splitting the arguments, and will allow those unholy souls who use spaces in their path names to run these scripts.
I restricted this to `SOURCE_DIR` and  `ARTIFACT_DIR`, as it looked like the other paths were guaranteed to not have spaces in them.
Note, did automate this change using regex search / replace, and while I did check the diff to make sure I didn't introduce anything silly, reviewers should double check that I didn't make a mistake. 
**Changes**
Add quotes to bash names to allow directories with spaces for native builds.

Quote bash paths to prevent word splitting

---

Emby.Server.Implementations/Library/ExclusiveLiveStream.cs
Emby.Server.Implementations/LiveTv/EmbyTV/DirectRecorder.cs
Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
Emby.Server.Implementations/LiveTv/EmbyTV/EncodedRecorder.cs
Emby.Server.Implementations/LiveTv/EmbyTV/IRecorder.cs
Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs
Emby.Server.Implementations/LiveTv/LiveTvManager.cs
Emby.Server.Implementations/LiveTv/TunerHosts/BaseTunerHost.cs
Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/DiscoverResponse.cs
Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
Emby.Server.Implementations/LiveTv/TunerHosts/LiveStream.cs
Emby.Server.Implementations/LiveTv/TunerHosts/M3UTunerHost.cs
Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs
Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs
MediaBrowser.Controller/Library/ILiveStream.cs
MediaBrowser.Controller/LiveTv/ITunerHost.cs

Fixes some warnings in LiveTV, mostly relating to `ConfigureAwait` and the new disposable analyzers.

Fix some warnings in LiveTV

---

Emby.Server.Implementations/Localization/countries.json

**Changes**
Somalia's current display name is in Somali (Soomaaliya), this change will display the English name instead (Somalia).
Reference: https://en.wikipedia.org/wiki/Somalia

Fix Somalia's display name

---

MediaBrowser.Providers/Plugins/Tmdb/BoxSets/TmdbBoxSetProvider.cs
MediaBrowser.Providers/Plugins/Tmdb/Configuration/PluginConfiguration.cs
MediaBrowser.Providers/Plugins/Tmdb/Configuration/config.html
MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs

The API key is added to the config file but not the user-facing plugin page. Most users should not mess with the key, but as discussed in #10529 some users like tracking their own API usage or dislike that using the Jellyfin key includes their statistics where someone else could possibly see.
To change the key open the TMDb plugin settings and hit save, then open `Jellyfin.Plugin.Tmdb.xml` (at `~/.local/share/jellyfin/plugins/configurations/Jellyfin.Plugin.Tmdb.xml` in my dev environment), set the `TmdbApiKey` value, and restart Jellyfin to pick up changes.
An empty or missing `TmdbApiKey` value will cause Jellyfin to use the Jellyfin key, which will not be saved to the xml file.
**Changes**
- Add API key to configuration file, as well as error handling for the plugin config page in case …

Make TMDb api key configurable, fix missing/wrong image urls

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

`-auto{scale,rotate} 0` has been dropped in upstream FFmpeg.
**Changes**
- Use -noauto{scale,rotate} for disabling auto filters
**Issues**
- Fixes #10809

Use -noauto{scale,rotate} for disabling auto filters

---

Emby.Server.Implementations/Dto/DtoService.cs
Emby.Server.Implementations/LiveTv/LiveTvManager.cs
Emby.Server.Implementations/Session/SessionManager.cs
Jellyfin.Api/Controllers/DevicesController.cs
Jellyfin.Api/Controllers/SessionController.cs
Jellyfin.Api/Controllers/UserViewsController.cs
Jellyfin.Api/Models/SessionDtos/ClientCapabilitiesDto.cs
Jellyfin.Server.Implementations/Devices/DeviceManager.cs
MediaBrowser.Controller/Devices/IDeviceManager.cs
MediaBrowser.Controller/Entities/BaseItem.cs
MediaBrowser.Model/Dto/BaseItemDto.cs
MediaBrowser.Model/Querying/ItemFields.cs
MediaBrowser.Model/Session/ClientCapabilities.cs

Remove some legacy stuff that clutters the API.
**Changes**
- Remove unused stuff from client capabilities
- Remove left over sync code from various places
**Issues**

Remove some unused client capabilities and sync code

---

Jellyfin.Server.Implementations/Users/UserManager.cs
Jellyfin.Server/CoreAppHost.cs

**Changes**
- Removes the UserManager cache, as queries are already cached by the EFSecondLevelCache. 
This saved roughly ~1s on startup in my testing
- Uses DI for `IAuthenticationProvider` and `IPasswordResetProvider`

Remove UserManager Cache

---

MediaBrowser.Model/Configuration/LibraryOptions.cs
MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

Adds option to enable/disable scanning for replaygain tags. This is means that existing replaygain tags can be used instead of jellyfin scanning each track again. This may cause problems with consistency. If replaygain tags are enabled then they will override scanning for LUFS reducing computation, if they are not found and LUFS scan is still enabled then it will scan them tracks.
Frontend: https://github.com/jellyfin/jellyfin-web/pull/4984

Add option to use replaygain tags for audio

---

CONTRIBUTORS.md
Jellyfin.Data/Enums/AudioSpatialFormat.cs
MediaBrowser.Model/Entities/MediaStream.cs
tests/Jellyfin.MediaEncoding.Tests/Probing/ProbeResultNormalizerTests.cs
tests/Jellyfin.MediaEncoding.Tests/Test Data/Probing/video_metadata.json

Support was [added](https://github.com/FFmpeg/FFmpeg/compare/814178f...98a4699) to FFmpeg.
**Changes**
Add `AudioSpatialFormat` property to `MediaStream`.

Detect audio spatial format

---

.ci/azure-pipelines-package.yml

From the latest ci run:
> ##[warning]Task 'NuGet authenticate' version 0 (NuGetAuthenticate@0) is deprecated. This task will be removed. From January 31, 2024, onwards it may no longer be available. Please see https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/nuget-authenticate-v0 for more information about this task.

Use NuGetAuthenticate@1

---

deployment/Dockerfile.centos.amd64
deployment/build.centos.amd64
deployment/build.debian.amd64
deployment/build.debian.arm64
deployment/build.debian.armhf
deployment/build.fedora.amd64
deployment/build.ubuntu.amd64
deployment/build.ubuntu.arm64
deployment/build.ubuntu.armhf

Since we now have a docker image from microsoft with .NET built-in, this PR would finally fix the problem.
- Added ```make, systemd, @buildsys-build``` to CentOS Dockerfile
- Rename fedora to centos for CentOS Build
- Rename minimum version of Ubuntu and Debian
- Remove command that remove build-dep

Fix action building

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs

**Changes**
- Fix the display aspect ratio of PGSSUB subtitle burn-in
- Use video framerate for ASS subtitle HW burn-in
**Issues**
- Subtitles were squashed vertically when the aspect ratio of the video is 21:9 but the PGSSUB/DVDSUB is 16:9.
- The framerate of ASS subtitles was hardcoded. ASS subtitles are now rendered based on the video frame rate.

Fixed some issues in PGSSUB and ASS subtitle burn-in

---

Emby.Server.Implementations/Library/LiveStreamHelper.cs

Second attempt at fixing this issue, this time i actually read the logs! Adds an extra test to check that the cached media info file can be read. This allows the rest of the function to run if the file doesn't exist.
**Changes**
Add extra try/catch to stop errors if trying to read cached media info file that doesn't exist
**Issues**
Fixes #10761

Fix long live tv load times, Fixes #10761

---

CONTRIBUTORS.md
MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs

**Changes**
Extracting a subtitle stream is a disk I/O bottlenecked operation as `ffmpeg` has to read through the whole file, but usually there is nothing CPU intensive to do.
If a file has multiple subtitle streams, and we want to extract more of them, extracting them one-by-one results in reading the whole file again and again.
However `ffmpeg` can extract multiple streams at once.
We can optimize this by extracting the subtitle streams all at once when only one of them gets queried, then we will have all of them cached for later use.
It is useful for people switching subtitles during playback.
It is even more useful for people who extract all the subtitle streams in advance, for example with the "Subtitle Extract" plugin.
In this case we reduce the extraction time significantly based …

Extract all subtitle streams simultaneously 

---

Emby.Server.Implementations/ApplicationHost.cs
MediaBrowser.Controller/LiveTv/ILiveTvManager.cs
src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs
src/Jellyfin.LiveTv/Extensions/LiveTvServiceCollectionExtensions.cs
src/Jellyfin.LiveTv/LiveTvManager.cs

**Changes**
Uses DI for `ILiveTvService` and `IListingsProvider`

Live TV DI

---

README.md

**Changes**
I noticed there was nothing in the README about accessing the hosted Web Client or Swagger docs after the Server has been started. I thought it might be useful to include this information to assist new contributors. 
Most users might not need this information because the Web Client is opened automatically when launching in Visual Studio or vscode, however those who like to start the project via `dotnet run` won't have the web client opened automatically and would need find the urls by searching the command output, finding the launchSettings.json, or looking through the code.
This pull request adds information to the Server Development section of the README to list the default urls where the hosted Web Client and Swagger docs can be found.
**Issues**
None

Update README to include default web client urls

---

Jellyfin.Api/Controllers/SystemController.cs
tests/Jellyfin.Api.Tests/Controllers/SystemControllerTests.cs

**Changes**
API route `System/Logs/Log` currently throws an InvalidOperationException and returns a 500 if the requested log file does not exist. 
I updated this method to handle this edge case and reutrn a 404.  
I also added unit tests to check that NotFound is returned if the file does not exist. I was going to add more unit tests for this method, but testing it is slightly difficult due to the lack of abstraction and using FileStream directly.  
**Issues**
None

Fix InvalidOperationException if log file not found

---

Jellyfin.Api/Models/SessionDtos/ClientCapabilitiesDto.cs
MediaBrowser.Model/Session/ClientCapabilities.cs
MediaBrowser.Model/System/SystemInfo.cs

Some small changes to make the current Android TV release work with unstable. There might be more, I'll hunt for all of them once the initial release candidate is out.
**Changes**
- Add back `SupportsContentUploading` and `SupportsSync` to client capabilities, but mark them as nullable and set a default value. Will propagate through the Kotlin SDK to the app with 10.9 so we can remove the properties in 10.10 (as the SDK no longer requires them).
- In SystemInfo specify some default values so we can remove those properties in the future
- In SystemInfo remove some types (Architecture and ffmpeglocation) so they generate as simple strings. this is just to reduce the amount of models in the OpenAPI spec, nothing fancy.
**Issues**

Fix some incompatible API deprecations

---

MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs

Properly escape subtitle extraction input path with parenthesis
**Changes**
Adds parenthesis to properly escape spaces
**Issues**
Fixes #10991

Escape subtitle extraction input path

---

tests/Jellyfin.Model.Tests/Dlna/StreamBuilderTests.cs
tests/Jellyfin.Model.Tests/Test Data/MediaSourceInfo-mkv-av1-aac-srt-2600k.json
tests/Jellyfin.Model.Tests/Test Data/MediaSourceInfo-mkv-vp9-aac-srt-2600k.json
tests/Jellyfin.Model.Tests/Test Data/MediaSourceInfo-mkv-vp9-ac3-srt-2600k.json

Overlooked in #10772
**Changes**
Discard WebM from test MKVs if there is an unsupported codec to comply #10772

Fix tests: discard webm from test mkvs if there is an unsupported codec

---

Jellyfin.Api/Helpers/DynamicHlsHelper.cs

_Alternative to #10751_
In addition to #9092
If HEVC encoding is enabled, we may still encounter unnecessary transcoding issue.
:warning: This PR is a hack/trick. It works on my Tizen 4 TV and Tizen 5 emulator (with `AllowHevcEncoding` condition removed).
I am for removing the problematic block, since we have `VideoRange` and probably no longer need a fallback stream. But this requires testing the Apple devices that require this fallback stream.
**Changes**
Make the bitrate of the fallback stream the same as the original, so that the client can choose by other attributes, such as color range.
**Issues**
Possible unnecessary transcoding (+tone mapping) in the same way as described [here](https://github.com/jellyfin/jellyfin/pull/9016#issue-1521365292).
> All streams in the master playlist …

Make the bitrate of the fallback stream the same as the original

---

Jellyfin.Api/Controllers/VideosController.cs
Jellyfin.Api/Helpers/StreamingHelpers.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
MediaBrowser.MediaEncoding/Transcoding/TranscodeManager.cs

**Changes**
* Use concat config for attachment extraction
* Sort files before generating concat config
* FFmpeg infers the format from the output file extension - this sometimes does not work (e.g. `mpegts` as extension crashes the transcode, file extension needs to be `ts`)
**Issues**
Fixes #10975
Possibly fixes #10815

BDMV fixes

---

Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs

Paths were not relative to the .m3u8 file causing video players that support trickplay playlists to generate an incorrect absolute URL for the images.

Fix tiles playlist not using relative paths

---

Emby.Server.Implementations/Session/SessionManager.cs
MediaBrowser.Model/Session/GeneralCommandType.cs
MediaBrowser.Model/Session/PlaybackOrder.cs
MediaBrowser.Model/Session/PlaybackProgressInfo.cs
MediaBrowser.Model/Session/PlayerStateInfo.cs

Changes
~~Add ShuffleMode to Session state.~~
Add OrderMode to Session state.
SetShuffleQueue command is already listed as one of the supported commands by Session, but without the value of ShuffleMode it is not possible to send a valid request from jellyfin-web client.
Issues
Partially fixes https://github.com/jellyfin/jellyfin-web/issues/5012 (small changes in jellyfin-web client are required to fully fix this issue)

Add PlaybackOrder to Session state

---

Jellyfin.Api/Controllers/LiveTvController.cs
Jellyfin.Api/Models/LiveTvDtos/GetProgramsDto.cs

Similar to #11024 but updates the request models instead of query parameters. Only thing left now is routes which is a bit more of a challenge...
**Changes**
- Make userId optional in GetProgramsDto
**Issues**

Make userId optional in GetProgramsDto

---

Jellyfin.Api/Controllers/DisplayPreferencesController.cs
Jellyfin.Api/Controllers/MediaInfoController.cs
Jellyfin.Api/Controllers/PlaylistsController.cs

This changes a few API endpoints that currently require a user id as query parameter.
This is both a nice-to-have change for client devs and a potential security fix. I haven't verified but it looks like before this change any authenticated user could get/post the display preferences of all users.
**Changes**
- Make userId optional in various operations from the DisplayPreferences, MediaInfo and Playlists API's
**Issues**

Always make userId query parameter optional

---

MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs

Fixes https://github.com/jellyfin/jellyfin/issues/10975
I also have this ugly patch which mapped pretty much every property over... but turns out only codec was required.
```patch
Subject: [PATCH] Changes
---
Index: MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs b/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
--- a/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs	
+++ b/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs	
@@ -324,20 +324,7 @@
return;
}
-            // Use BD Info if it has multiple m2ts. Otherwise, treat it like a video file and rely …
```

Always use ffmpeg codec for bluray

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
MediaBrowser.Model/Configuration/EncodingOptions.cs

**Changes**
The upstream ffmpeg 6.1 released with a new `scale_vt` filter which provides support for scaling and tone mapping using VideoToolBox's native method.  This PR:
- Enables hardware scale filter if possible
- Enables hardware tone mapping is possible
One thing to note is that the VideoToolBox's tone mapping method has to use hard-coded Apple's parameters and does not have any tunable like other filters, but Apple's settings looks good enough to me.
Currently the WebUI does not have the options for enabling Tone Mapping for VideoToolBox, which need to be implemented separately as it does not have the tunable options available to other implementations.
**Issues**

feat: Fully support hardware filters on Apple VideoToolbox

---

Emby.Photos/PhotoProvider.cs

Cleanup PhotoProvider.cs using new .NET 8 features
**Changes**
Changed to scoped namespace
Used Pattern Matching when casting types

Cleanup PhotoProvider.cs using new .NET 8 features

---

src/Jellyfin.Drawing.Skia/SkiaEncoder.cs

~I wasn't able to hit this code with any svgs from scanning, only from manually setting a media image, so just converting in-place should be fine?~
~Alternative is to just return an empty string instead of attempting conversion~
Ensure blurhash calculation isn't attempted for svg
Fixes #11128

Don't attempt to calculate blurhash for svg

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

**Changes**
- Ensure that the track title is read from a tag, if it exists.
Before: 
\>  On the first scan of a music library, every track title is set to the file name, ignoring the `TITLE` tag, even if the tag is set. "Replace all metadata" always reads it from the tag, even if it is not set.
After:  
\> If the tag exists, set the name to it. When it doesn't, keep the file name as a track title. Same logic when using "Replace all metadata". `options.ReplaceAllMetadata` doesn't do anything here.
**Issues**
Potentially, partially fixes  #9359?

Change parsing logic of audio track title

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

**Changes**
- Retrieve the release date from a ffmpeg probe, instead of hard-coding it.
While parsing the music library, PremiereDate was written incorrectly, only getting the year properly, which resulted in it having a format of YYYY-01-01. This commit #7514 introduced `TagLibSharp` library, which, looks like, despite reading full raw metadata from a file, unfortunately, doesn't provide a method to retrieve a full date from it. That behavior is incorrect for some tag formats.
**Issues**
fixes #7667

Fix parsing of audio PremiereDate property

---

CONTRIBUTORS.md
MediaBrowser.Controller/Entities/CollectionFolder.cs
MediaBrowser.Model/Configuration/LibraryOptions.cs

This change addresses users desires to have the option to disable particular libraries for all users at certain times. This is handy for seasonal libraries (like christmas movies/music/tv shows).
I added a "Disabled" option to LibraryOptions.cs and a check to see if a library is disabled in CollectionFolder.cs (it overrides Folder's IsVisible function).
I chose "disabled" over "enabled" because the default value for booleans loaded into the LibraryOptions class by the JsonDeserializer is false, so by default, existing libraries will remain enabled.
I also made a corresponding checkbox in the jellyfin-web repository.
This commit addresses the issue described here:
https://features.jellyfin.org/posts/2530/hide-a-library-from-all-users-disable-library …

Add ability to enable/disable libraries

---

MediaBrowser.MediaEncoding/Transcoding/TranscodeManager.cs

**Changes**
- Catch delete encoded media file exceptions
```
Mar 16 07:54:33 archlinux jellyfin[11977]: System.UnauthorizedAccessException: Access to the path '/tmp/.X0-lock' is denied.
Mar 16 07:54:33 archlinux jellyfin[11977]:  ---> System.IO.IOException: Operation not permitted
Mar 16 07:54:33 archlinux jellyfin[11977]:    --- End of inner exception stack trace ---
Mar 16 07:54:33 archlinux jellyfin[11977]:    at System.IO.FileSystem.DeleteFile(String fullPath)
Mar 16 07:54:33 archlinux jellyfin[11977]:    at System.IO.File.Delete(String path)
Mar 16 07:54:33 archlinux jellyfin[11977]:    at Emby.Server.Implementations.IO.ManagedFileSystem.DeleteFile(String path)
Mar 16 07:54:33 archlinux jellyfin[11977]:    at Jellyfin.Api.Helpers.TranscodingJobHelper.DeleteEncodedMediaCache()
Mar 16 …
```

Catch delete encoded media file exceptions

---

Emby.Server.Implementations/IO/ManagedFileSystem.cs
MediaBrowser.Controller/Entities/Folder.cs
MediaBrowser.Controller/Providers/DirectoryService.cs
MediaBrowser.Controller/Providers/IDirectoryService.cs

**Changes**
- Skip `Folder` where `IsTopParent == true` if the filesystem path is inaccessible or empty
- Don't remove anything when `IsRoot` is true (AggregateFolder and UserRootFolder will have this condition and they directly point to library folders)
I have only tested it on Windows with SMB mount and an empty folder. It needs to be tested more, especially Linux network shares, symlinks etc.
**Issues**

fix: skip library folders that are inaccessible or empty

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

zscale filter has an assertion that image dimensions must be divisible by subsampling factor, and for most yuv formats, this means the dimension has to be divisible by two. Our current logic recalculating dimensions may yield an odd number, especially for anamorphic videos, which fails the thumbnail generation.
**Changes**
- Modify the filter logic for image extraction to use DAR instead of SAR, as SAR could be different from DAR for anamorphic videos, and DAR is what the video is expecting.
- Use `scale=round(iw*dar/2)*2:round(ih/2)*2` to generate an always even dimension. This would cause a side effect where 1x1 inputs being upscaled to 2x2, but this case is very unlikely.
**Issues**
Fixes #11183

fix: make sure the dimension is divisible by two for zscale

---

Directory.Packages.props
MediaBrowser.Controller/Entities/BaseItem.cs
src/Jellyfin.Extensions/Jellyfin.Extensions.csproj
src/Jellyfin.Extensions/StringExtensions.cs

**Changes**
Since Jellyfin assume user will use a latin-based language as media title, it will be a problem for CJK language users. This patch attempted to use a `Transliterator` to transliterate the title if the `SortName` still contains non-ascii characters at the end of `ModifySortChunks()`.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/3202
**Note**
Library will need to be re-scanned to make the existing items uses the new SortName working.
**Screenshot when the patch gets applied**
Showcase the sort issue is gone: (Note: 赌博默示录 `du bo mo shi lu` < 前目的地 `qian mu di di` < 子弹列车 `zi dan lie che`)
Showcase of the `NameStartsWith` filter on the right side: (Note: `D` is selected, 赌博默示录 `du bo mo shi lu` is shown)

feat(i18n): transliterate item name before sorting and filtering

---

CONTRIBUTORS.md
Jellyfin.Api/Controllers/DynamicHlsController.cs
Jellyfin.Data/Enums/VideoRangeType.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Model/Entities/MediaStream.cs

This commit adds two new values to the VideoRangeType enum to talk about media that have both DOVI and HDR10 or HLG data (DoVi Profile 8) to enable Dolby Vision playback on those browsers.
**Changes**
Introduced `DOVI_with_HDR10_Fallback` and `DOVI_with_HLG_Fallback` VideoRangeType enums, and added references to these new types wherever I found `VideoRangeType.HDR10 / HLG`.
MediaStream.cs will now test both of it's HDR10/HLG and DOVI conditions before returning the video range type.
**Issues**
Addresses #10468

Add new VideoRangeTypes to fully support DoVi on webOS

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
This maps the encoder presets to VideoToolbox encoder quality settings. Use prefer speed as default like other encoders.
This is a quick fix that takes minimal changes, but VideoToolbox is using a tuning logic that is very different from other encoders to control its behavior, so a more specialized config panel is needed for it, but it will be a 10.10 thing.
10.10 notes below
----
VideoToolbox utilizes hints, unlike explicitly set levels, to control its behavior. These hints only inform the framework what to optimize for, and the final determination of speed, quality, and power constraints is still made by the framework's internal logic. For instance, when you instruct it to run faster, it may not always comply, but rather speeds up when it deems it necessary. The hints we are …

fix: map encoder preset to quality setting for VideoToolbox

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs

**Changes**
As discussed in jellyfin/jellyfin-ffmpeg#357, the current OpenCL kernel runs extremely slow on Apple Silicon. This change updates the filter chain to use the Metal implementation of the tone map filter to handle Dolby Vision Profile 5 videos introduced by jellyfin/jellyfin-ffmpeg#369.
For Intel Macs, the OpenCL kernel is not compatible with certain GPUs and we will have the following error:
```
[AVHWDeviceContext @ 0x7faa2510e200] OpenCL error: [CL_IMAGE_FORMAT_NOT_SUPPORTED] : OpenCL Error : clCreateImage failed: The specified format is not supported for the specified image type.
[Parsed_tonemap_opencl_5 @ 0x7faa2510b940] Failed to create image for dither matrix: -10.
```
We need the Metal kernel to properly support Intel Macs.
**Issues**

fix: use Metal tonemap instead of OpenCL

---

.github/workflows/ci-openapi.yml

**Changes**
Seems scp-action didn't work how I expected, and will seemingly always create a directory on the target even if given a filename on both sides. Work around this to ensure the file ends up in the right format.
**Issues**
N/A

Handle OpenAPI spec uploads properly

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
These legacy codecs are not implemented with hardware-accelerated decoding in VideoToolbox and were using VideoToolbox's software fallback decoding before. Since ffmpeg now only allows software fallback for HEVC, enabling those codecs will cause VT session creation to fail. Remove them now.
This also added missing VP8 config to VideoToolbox, fixed hardware decoding for VP8 videos. It was using software decoding even enabled by user.
**Issues**

fix: remove legacy codecs for VideoToolbox

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

**Changes**
This PR changed the order which path is used. Previously we use the ffmpeg path in the config file at first, but the config file entry is no longer editable with a GUI, and most of our packaging will use the CLI to set the ffmpeg path, where the leftover config could cause our new server to use the incorrect ffmpeg. This order is also easier to work with, as the CLI is easier to modify than the XML config file and can help users fix the ffmpeg path more easily.
One side effect of this would be that it could be hard for our users to change the ffmpeg in our Docker images, as our Docker entrypoint has a hard-coded path. To support the custom ffmpeg use case in Docker, we need to modify that hardcoded path into an environment variable-based path.
This behavior change should be …

fix: prefer cli ffmpeg path over config file

---

Jellyfin.Api/Models/SessionDtos/ClientCapabilitiesDto.cs
MediaBrowser.Model/Session/ClientCapabilities.cs

We emit the DefaultValue in OpenAPI spec so a 10.9 based SDK can automatically fill in a default, but we didn't actually send a default value causing a 10.8 based SDK to fail.
**Changes**
Updated the ClientCapabilities to send default values for SupportsContentUploading and SupportsSync to fix sign in in the ATV app.
**Issues**

Fix default values missing in ClientCapabilities(Dto)

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

The removed should be `audio/videoCodecs[0]`, not `shiftVideoCodecs[0]`.
**Changes**
- Fix the broken codecs shifting
**Issues**
- Fixes https://github.com/jellyfin/jellyfin-web/issues/5337

Fix the broken codecs shifting

---

Jellyfin.Api/Controllers/ConfigurationController.cs

**Changes**
This PR ports the security fix for [GHSA-rr9h-w522-cvmr](https://github.com/jellyfin/jellyfin/security/advisories/GHSA-rr9h-w522-cvmr) and disabled the ffmpeg path setting API.
**Issues**

fix: disable api endpoint for ffmpeg path for security

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
We are using bitrate-based control, but VT will target qmax first, potentially making the video bitrate much higher than the limit when the limit is very low and the video resolution is very high. Unset it so that the bitrate is close to the target.
In this case, even the `-maxrate` setting will have no effect on the bitrate. It only reduces the performance, but the result bitrate is still much higher than the limit. 
Other encoders potentially have same issue, but most of them is already patched in some other way, like very high qmax or using CBR.
Ideally, we should perform a video resolution downscale when the bitrate limit is too low for the resolution to preserve better visual quality. However, this use case could be very edgey, such as attempting to stream 4K60 video over …

fix: unset qmin and qmax for vt

---

Emby.Naming/Common/NamingOptions.cs

In my library structure I've always used the folder "extra" for extra content, when I migrated to Jellyfin (years ago) I never imported all this media. Figured I should do something about that so I can develop support for theme songs/video in the ATV app. 
**Changes**
- Add an extra rule for the "extra" folder
**Issues**

Support "extra" folder for extras content

---

src/Jellyfin.Drawing.Skia/SkiaEncoder.cs

**Changes**
This check will prevent the splash screen generation from running if we have no posters or no backdrops/thumbnails to generate a splash screen from. Since even if it ran it would just err out when it tried to retrieve the missing poster/backdrop/thumbnail.
I added the check inside `SkiaEncoder.CreateSplashscreen` to stop it from running if somebody tried to create a splash screen regardless of where the `IImageEncoder.CreateSplashscreen` might be called from. If you want me to move the check to the `SplashscreenPostScanTask` instead, to prevent it from running even if we change the underlying implementation of the `IImageEncoder` in the future, then just say the word.
**Issues**

fix: add image count check to splash screen generation

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
A hwupload without any filter to actually consume the frame would cause VideoToolbox's encoder to produce frames with artifacts. Check if the filter chain actually has a valid filter before adding hwupload.
**Issues**

 fix: don't do empty hwupload for VT

---

Emby.Server.Implementations/HttpServer/WebSocketManager.cs
MediaBrowser.Controller/Net/BasePeriodicWebSocketListener.cs

**Changes**
Use a re-entrant lock
**Issues**
Fixes #11218

fix: use a reentrant lock when accessing active connections

---

MediaBrowser.Providers/Manager/ProviderManager.cs

Fix "Error refreshing folder" for the items of type "MusicArtist".
**Changes**
Visit each artist folder only once.
**Issues**
partly fixes #6340 (for the MusicArtist case)

fix metadata refresh for artists

---

src/Jellyfin.Networking/AutoDiscoveryHost.cs

The exception was found when attempting to debug in-process restart issues
```
System.Net.Sockets.SocketException (98): Address already in use
at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.Sockets.Socket.Bind(EndPoint localEP)
at Jellyfin.Networking.AutoDiscoveryHost.ListenForAutoDiscoveryMessage(IPAddress address, CancellationToken cancellationToken) in /home/crobibero/Code/jellyfin/src/Jellyfin.Networking/AutoDiscoveryHost.cs:line 83
```

Catch exceptions in auto discovery

---

MediaBrowser.Controller/Session/SessionInfo.cs

I guess this is regression from when we moved over to ASP.NET. Seems to be available starting from our first OpenAPI schema.
There are two properties in SessionInfo:
- NowPlayingItem (BaseItemDto)
- FullNowPlayingItem (BaseItem)
The second one is the only place in the API that "exposes" BaseItem (the non-dto one). All other places use BaseItemDto. Fortunately, the property is nullable and an org-wide search shows none of our clients use FullNowPlayingItem. So removing it should not have any impact.
**Changes**
- Remove SessionInfo.FullNowPlayingItem from API responses
**Issues**
Partial fix for #11244, other exposed types like ClientCapabilities need a proper SessionInfoDto.

Remove SessionInfo.FullNowPlayingItem from API responses

---

Emby.Server.Implementations/Dto/DtoService.cs
MediaBrowser.Model/Dto/BaseItemDto.cs

Easy change, too late for 10.9 though :p
**Changes**
- Use enum for BaseItemDto.ExtraType
**Issues**

Use enum for BaseItemDto.ExtraType

---

Emby.Server.Implementations/Library/LibraryManager.cs

The scanner will always overwrite all extras it found with new data. It doesn't really care about the existing database entry. In some cases this can change the type of an extra. This is a fix for that case by checking if the new type to set is not "unknown".
**Changes**
- Only update extra type if it is more specific then the currently known extra type
**Issues**

Fix FindExtras overwriting current extra type

---

Jellyfin.Api/Helpers/HlsCodecStringHelpers.cs

**Changes**
Browsers are very picky about this string. The profile level has to be padded to double digits otherwise the stream is going to be rejected and the playback would not continue.
This is confirmed to work with latest Chromium 122 and Firefox 124, but Chromium used to be more picky about this string so additional hacks to lying about the level to it may be needed.
**Issues**
Fixes jellyfin/jellyfin-web#5364

fix: av1 codecs string

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

**Changes**
Reference #8152, ffmpeg using "-rtsp_transport tcp+udp -rtsp_flags prefer_tcp" arguments to process RTSP transcode, but ffprobe arguments is missing, without those arguments, tcp only protocol maybe probe timeout.
This PR will fix the issue.
Before:
After:
**Issues**
Fixes #7630

fix: rtsp live stream ffprobe timeout

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs

**Changes**
We already have a lot of code referencing alac encoder but it is not added to the support list. Adding this will make audio transcoding working in this format.
This PR also removed the 6 channel limit for `aac_at` as this encoder does support 8 channel audios.
**Issues**

Fix apple audio codecs

---

MediaBrowser.LocalMetadata/Images/LocalImageProvider.cs

**Changes**
This adds "jacket" to the list of paths searched for the default image of music media types. This is a very common name for the cover art of albums that is often found even in official digital releases of albums. Without this change, users often need to either use an online metadata provider or rename the file, even though their copy of the album already contained a proper cover art. This is also supported by other media clients.
I'm not sure if an issue / feature request was needed for such a small change, if so I'll gladly make one if asked to.
An update to the docs at https://github.com/jellyfin/jellyfin.org/blob/master/docs/general/server/media/music.md must also be made if this change is merged.

Add jacket to the list of music images

---

Jellyfin.Api/Controllers/LibraryController.cs

**Changes**
While testing https://github.com/jellyfin/jellyfin-web/pull/5215 I found that disabled libraries were still being listed in the metadata editor and selecting a disabled library crashes the web client. I believe this will fix the issue by excluding disabled libraries from the results.
**Issues**
N/A

Fix disabled libraries being returned in MediaFolders api

---

MediaBrowser.Model/Entities/MediaStream.cs

As described in the linked issue, there are media that are identified by mediainfo as Dolby Vision Profile 8 CCid 6. Since BluRay spec guarantees, as far as I could tell, that all HDR containing BluRays have at least an HDR10 layer acting as the base layer, and more specifically in this case, since the above must stem from a DoVi BluRay (which is the only case that uses CCid 6, see Profile 7), Dolby Spec requires that a "BluRay compatible" HDR base/fallback layer exists, which should be HDR10 as described above.
Hence, given that FFmpeg supports profile 8, the above cases should be tagged as DOVIWithHDR10.
Any corrections are encouraged and appreciated!
**Changes**
Add an extra switch case, so as to tag Profile 8 CCid 6 as DOVIWithHDR10
**Issues**
Fixes #11330

Add support for out-of-spec but existent, Dolby Vision Profile 8 CCid 6 media.

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

**Changes**
Fall back to ffprobe to get a correct value for track MBID.
**Issues**
Fixes #11020

Fix track MBID in audio metadata

---

Emby.Server.Implementations/Library/LibraryManager.cs

It is not possible to delete items associated to files because we are throwing before removing the item from the database.
**Changes**
* Do not throw if file or folder does not exist
**Issues**
Fixes #8493

Don't throw if file was already removed

---

MediaBrowser.Controller/Entities/Folder.cs
MediaBrowser.Providers/Manager/ProviderManager.cs

Fixes https://github.com/jellyfin/jellyfin/issues/11264
`.AddOrUpdate()` is doing essentially the same thing internally, this just removes the exception

Only update if actively refreshing

---

src/Jellyfin.Drawing.Skia/SkiaEncoder.cs

Apparently animated WebP images are a thing
https://github.com/jellyfin/jellyfin/issues/5501#issuecomment-1977428971
This change makes it so an an image has any frames (is animated) we won't attempt to convert it from the original format

Don't decode animated images

---

Emby.Server.Implementations/Serialization/MyXmlSerializer.cs

Fixes https://github.com/jellyfin/jellyfin/issues/11349
Other option is to clear the dictionary when a new `MyXmlSerializer` is created, but this is cleaner and essentially just as performant

fix: use new serializer cache per IXmlSerializer

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

Fixes https://github.com/jellyfin/jellyfin/issues/10974
Same as https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L1298-L1302

fix: fallback to artist if album artist not provided

---

MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs

**Changes**
Current subtitle extraction will attempt to map the external text subtitles as well during the extraction, which would obviously fail as that stream is not in the original video file. Ignore external streams during the extraction.
**Issues**
Fixes #11242

fix: don't extract external sub

---

Emby.Server.Implementations/Localization/LocalizationManager.cs
tests/Jellyfin.Server.Implementations.Tests/Localization/LocalizationManagerTests.cs

I've recently added a PG-13 content only limit to the screensaver in the Android TV app. I'm planning to make this configurable but I want to store the chosen rating as integer (age) instead of the rating name, which is dependent on the server localization.
One problem I ran into is that I can't filter items based on age, this PR adds a small change to the LocalizationManager to always try parsing the requested rating level as integer first before using its mapping files. This way it is possible to request items with `maxOfficialRating=13` instead of `maxOfficialRating=PG-13`.
**Changes**
- Support age (as integer) in LocalizationManager.GetRatingLevel, skipping the mappings
**Issues**

Support age in LocalizationManager.GetRatingLevel

---

Emby.Server.Implementations/HttpServer/WebSocketConnection.cs
Emby.Server.Implementations/Session/SessionWebSocketListener.cs

Check if there are any websockets left in the remove method.
Fixes `Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 0 WebSockets.`

Changes SessionWebSocketListener to (re)use a timer

---

Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs

**Changes**
- Check for an extension present in the checked path, if not check if the directory still exists, otherwise check for file presence
**Issues**
Fixes #11289

#11289 Fixed cleanup task not checking for folders

---

Emby.Server.Implementations/Library/LibraryManager.cs
MediaBrowser.Controller/Entities/AggregateFolder.cs
MediaBrowser.Controller/Entities/Audio/MusicArtist.cs
MediaBrowser.Controller/Entities/CollectionFolder.cs
MediaBrowser.Controller/Entities/Folder.cs
MediaBrowser.Controller/Entities/UserRootFolder.cs
MediaBrowser.Controller/Entities/UserView.cs
MediaBrowser.Controller/Playlists/Playlist.cs
MediaBrowser.Providers/Manager/ProviderManager.cs

**Changes**
This PR added a workaround to temporarily mark the UserRoot as non-root during library validation for VirtualFolder removal. This is probably not the best solution but I'd like to see any suggestions.
The RootFolder protection is to not accidentally remove the whole library when the path is temporarily unavailable, and is a valid use case. But when the user explicitly asked for removal, we should not protect it. So perhaps `IsRoot` can be renamed to something like `DeleteProtect`? 
**Issues**
Fixes #11269

fix: explicitly allow remove root when performing library removal

---

Emby.Server.Implementations/HttpServer/WebSocketConnection.cs

A WebSocket connection should not (forcefully) be closed when an incoming message fails to process. In the specific issue I encountered it was due to new authorization requirements, which we should just NO-OP to.
```
[2024-04-21 14:53:52.405 +02:00] [INF] [113] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.1" request
[2024-04-21 14:53:52.417 +02:00] [ERR] [46] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.1" WebSocketRequestHandler error
MediaBrowser.Controller.Authentication.AuthenticationException: Only admin users can subscribe to session information.
at Jellyfin.Api.WebSocketListeners.SessionInfoWebSocketListener.Start(WebSocketMessageInfo message) in jellyfin\Jellyfin.Api\WebSocketListeners\SessionInfoWebSocketListener.cs:line 84
at …
```

Fix WebSocket disconnecting when exception is thrown during processing

---

Jellyfin.Api/Controllers/SessionController.cs
tests/Jellyfin.Server.Integration.Tests/Controllers/SessionControllerTests.cs

Partially fixes https://github.com/jellyfin/jellyfin/issues/11366
I tried adding a test for this but having the logic directly in the controller make it very difficult

Limit sessions per user

---

MediaBrowser.Controller/Entities/BaseItem.cs

**Changes**
The way the whitelist tag currently works is weird. It requires the entire library to have that tag to be shown, and if the library has the tag, all items inside it inherit that tag, making all items visible. This change aims to make it more sensible by allowing the whitelist to work on a per-item basis, ensuring that the allowed libraries are always shown and the whitelist tag only applies to the items inside the library, not the library itself.
**Issues**
Fixes #11375

fix: don't apply whitelist tags to libraries

---

Jellyfin.Api/Controllers/ItemUpdateController.cs

Regression from #8526.
**Changes**
- Don't cast without checking type in ItemUpdateController, as library structures are not always what we expect.
**Issues**
Fixes #11277

Fix InvalidCastException in ItemUpdateController

---

Jellyfin.Api/Controllers/DynamicHlsController.cs
Jellyfin.Api/Helpers/StreamingHelpers.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
The current implementation of custom downmixing algorithm is flawed and caused multiple issues:
- The algorithm is designed for 5.1 channel audios but will also apply to 7.1 audio, resulting in very wrong outputs.
- The channel check only applies ffmpeg's native downmixing when channels >5, causing regressions on output channel limit control for inputs with fewer channels.
- The channel count is not set before calculating bitrate, resulting in the wrong bitrate being applied to the output.
P.S. The ffmpeg's `-ac` switch actually performs downmixing defined in ATSC A/52:2012 with the method described in section 7.8. So "None" is not an accurate name or ffmpeg's native downmixing. 
**Issues**
Fixes #11397

Only apply custom downmix to 5.1 audios

---

MediaBrowser.Controller/Entities/BaseItem.cs
MediaBrowser.Model/Configuration/LibraryOptions.cs
MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

* Removes the UseReplayGainTags option from the LibraryOptions
* Removes extra ffrobe instance when option was enabled
* Makes LUFS value nullable
cc @TelepathicWalrus

Always scan ReplayGain tag

---

Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
The current method of rounding to an integer for calculating output size may suffer from accuracy loss, resulting in the output size not being exact. This used to be a non-issue until we introduced trickplay, which requires the generated images to have an exact width to make tiles.
For example, for a video with a width of 1432 pixels and a required output width of 480 pixels, the calculated `scale * inputWidth` will become `479.99999999999994`, which is smaller than the requested `480`. Our logic will then pick the smaller value, which is cast into an integer. The casting simply discards all decimal parts, making it `479`. Then, in the next part of rounding, we round it to an even number, which makes it smaller and the produced width becomes `478`.
This PR also forces the …

Use more accurate rounding in GetFixedOutputSize

---

Jellyfin.Api/Controllers/DashboardController.cs
Jellyfin.Api/Controllers/PackageController.cs
Jellyfin.Api/Controllers/PluginsController.cs

This came up in chat yesterday. We allow reading of installed/available plugins and repositories in addition to allowing both read and write for plugin configuration. This is **unsafe** and something we never encouraged (plugins should only be available in the dashboard).
In case this breaks a plugin (although that is unlikely) it should be fixed in the plugin by adding additional endpoints.
The only plugin related APIs left as open-access are:
- The endpoint to get a plugin image.
- The endpoint to get the HTML of a plugin page
**Changes**
- Require elevation for plugin related endpoints
**Issues**

Require elevation for plugin related endpoints

---

Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs
Emby.Server.Implementations/Data/SqliteItemRepository.cs
Emby.Server.Implementations/Library/IgnorePatterns.cs
Emby.Server.Implementations/Library/LibraryManager.cs
Emby.Server.Implementations/Library/UserViewManager.cs
Emby.Server.Implementations/Playlists/PlaylistManager.cs
Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs
Emby.Server.Implementations/Session/SessionManager.cs
Jellyfin.Api/Controllers/ItemUpdateController.cs
Jellyfin.Api/Controllers/LibraryController.cs
Jellyfin.Api/Controllers/LibraryStructureController.cs
Jellyfin.Api/Controllers/UserViewsController.cs
Jellyfin.Api/Extensions/DtoExtensions.cs
MediaBrowser.Controller/Entities/BaseItem.cs
MediaBrowser.Controller/Entities/Extensions.cs
MediaBrowser.Controller/Entities/TagExtensions.cs
MediaBrowser.Controller/Library/ItemResolveArgs.cs
MediaBrowser.Controller/Net/BasePeriodicWebSocketListener.cs
MediaBrowser.Controller/Session/SessionInfo.cs
MediaBrowser.XbmcMetadata/Parsers/MovieNfoParser.cs
src/Jellyfin.LiveTv/Channels/ChannelManager.cs
src/Jellyfin.LiveTv/Listings/ListingsManager.cs
src/Jellyfin.LiveTv/LiveTvManager.cs
src/Jellyfin.LiveTv/Timers/ItemDataProvider.cs
src/Jellyfin.LiveTv/TunerHosts/TunerHostManager.cs

* Use new collection expressions to concat to existing arrays
* Use Array.ConvertAll where possible
* Replace .ToArray with .ToList where possible
(And yes, collection expressions are as fast/faster than manually creating and copying)
```
| Method | N    | Mean       | Error     | StdDev    | Gen0   | Allocated |
|------- |----- |-----------:|----------:|----------:|-------:|----------:|
| Magic  | 0    |   9.943 ns | 0.0780 ns | 0.0692 ns | 0.0004 |      32 B |
| Manual | 0    |  14.550 ns | 0.0883 ns | 0.0826 ns | 0.0004 |      32 B |
| Magic  | 1    |  10.365 ns | 0.0529 ns | 0.0494 ns | 0.0004 |      32 B |
| Manual | 1    |  15.433 ns | 0.1458 ns | 0.1364 ns | 0.0004 |      32 B |
| Magic  | 4    |  11.119 ns | 0.0906 ns | 0.0803 ns | 0.0004 |      32 B |
| Manual | 4    |  15.586 ns …
```

More efficient array creation

---

Emby.Server.Implementations/Library/LibraryManager.cs
MediaBrowser.Controller/Entities/AggregateFolder.cs
MediaBrowser.Controller/Entities/Folder.cs

**Changes**
This PR validates the collection folder on addition and removal. This folder is very special and is hard to follow the common virtual folder validation. It needs to skip the accessible validation on addition to be successfully added, and it will require the accessible validation to actually remove this virtual folder. The current approach is to use the `allowRemoveRoot` parameter to determine if the path accessible check is needed, because when `allowRemoveRoot == true`, it means the user explicitly requires a deletion.
**Issues**
Fixes #11258
Fixes #11385

Validate Collection Folders on adding and removal

---

MediaBrowser.Providers/Subtitles/SubtitleManager.cs

Subs currently fail to download if another subtitle with the same name (usually previously downloaded) exists. This change now modifies the saving filename before saving so it does not fail anymore.
**Issues**
Fixes #10696

Fix subtitle saving if file already exists

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

**Changes**
The external LRC should be added to the current stream first; otherwise, the initial scan will always overwrite the external LRC if that audio file also has an embedded lyric.
Now, such overwrite will no longer happen even if the user requested full replacement metadata.
If users want to get rid of the current external lrc and use the embedded version instead, they should manually remove that lrc file and do a find missing metadata library scan.
**Issues**
Fixes #11454

Fix external LRC files being incorrectly overwritten during the initial scan

---

MediaBrowser.Model/Configuration/ServerConfiguration.cs

This option does not have any GUI to configure it yet and causes a major behavior change that most users may not expect. Disable this behavior on default and the user want to use this feature should manually edit the config/system.xml
Ideally, we should add some documentation for this option on our website.
**Changes**
Change the default value of `InactiveSessionThreshold` from 10 to 0
**Issues**
See jellyfin/jellyfin-web#5118

Don't close inactive session on default

---

MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs

Fixes an issue where if the cancellationToken is cancelled, a semaphore could be left in the dictionary.

Clean up synchronization

---

Emby.Server.Implementations/Playlists/PlaylistManager.cs
Jellyfin.Api/Controllers/PlaylistsController.cs
MediaBrowser.Controller/Playlists/IPlaylistManager.cs
MediaBrowser.Providers/Playlists/PlaylistItemsProvider.cs

**Changes**
* Fix ACL checks for scanned playlists
* Fix ACL checks for admins
* Properly construct full path from scanned playlist item paths if it is a relative path
**Issues**
Fixes #11443

Playlist fixes

---

src/Jellyfin.LiveTv/TunerHosts/M3UTunerHost.cs

Fallback to the old behavior of checking path extension when 405 occurs on HEAD request. Required as the TV Tuner's http sever is not always properly implemented.
**Changes**
- Check path extension when HEAD request got 405
**Issues**
Fixes #11493

Workarounds TV tuners rejecting HEAD method

---

Jellyfin.Api/Controllers/PlaystateController.cs
Jellyfin.Api/Helpers/RequestHelpers.cs

Only derive the userId from HttpContext may not work for api keys because there will be no userId for such HttpContext.
PlayedItems might not be the only one has this issue though, need to do a thorough check when we have time.
**Changes**
**Issues**
Fixes #11501

Allow explicitly set userId for RequestHelpers.GetSession

---

src/Jellyfin.LiveTv/TunerHosts/M3UTunerHost.cs

Complements #11495 . Some M3UTuners will respond with a 501 instead of a 405 code. This PR addresses that case.
Relevant logs:
```
[09:26:53] [INF] [10] Jellyfin.LiveTv.DefaultLiveTvService: Streaming Channel m3u_64c4f0be7c72228e1b290faadf903396c5a4a90c0b075383574e42769cc4efa1
[09:26:53] [ERR] [10] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Error opening tuner
System.Net.Http.HttpRequestException: Response status code does not indicate success: 501 (Not Implemented).
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
```
**Changes**
- Add 501 HTTP response code (Not implemented) handler to M3UTunerHost
**Issues**
Complements #11495 
Fixes #11493

Add Not Implemented response check to m3u tuner HEAD request

---

Jellyfin.Server/Migrations/Routines/AddDefaultCastReceivers.cs

Might prevent https://github.com/jellyfin/jellyfin/issues/11502 though I haven't been able to reproduce the issue

Always set cast receivers during migration

---

MediaBrowser.Model/Configuration/LibraryOptions.cs

Such operations require filesystem write permissions and should not be set as default. Users should be required to explicitly enable them.
**Changes**
Default value for  `SaveLyricsWithMedia` is now`false`
The `SaveSubtitlesWithMedia` should also default to `false`, but this change is postponed to 10.10
**Issues**

Default to not extract lyrics

---

MediaBrowser.Controller/Entities/Folder.cs

The library will also be updated when the number of children remains the same before and after scanning. For example, if one video file is removed and replaced with another version, we still need to remove the old one in this case.
**Changes**
Always check if there is mismatching children
**Issues**
Fixes #11255
Fixes #11524

Use actual item removal count for library change determination

---

Emby.Server.Implementations/ApplicationHost.cs
Jellyfin.Server/Program.cs

Fixes following exception (and infinite startup loop):
```
[15:50:33] [FTL] [14] Main: Error while starting server
System.InvalidOperationException: .NET runtime metrics are already being collected. Dispose() of your previous collector before calling this method again.
at Prometheus.DotNetRuntime.DotNetRuntimeStatsCollector..ctor(ServiceProvider serviceProvider, CollectorRegistry metricRegistry, Options options)
at Prometheus.DotNetRuntime.DotNetRuntimeStatsBuilder.Builder.StartCollecting(CollectorRegistry registry)
at Prometheus.DotNetRuntime.DotNetRuntimeStatsBuilder.Builder.StartCollecting()
at Emby.Server.Implementations.ApplicationHost.Init(IServiceCollection serviceCollection) in /home/crobibero/Code/jellyfin/Emby.Server.Implementations/ApplicationHost.cs:line 425
at …
```

Add metrics collector to disposable parts

---

Emby.Server.Implementations/IO/ManagedFileSystem.cs
tests/Jellyfin.Server.Implementations.Tests/IO/ManagedFileSystemTests.cs

The fragile path matching no longer works with dotnet 8, causing Windows users to lose collection items because the item path is incorrectly validated, then the server will remove all items due to file not found.
**Changes**
**Issues**
See forum https://forum.jellyfin.org/t-items-in-collections-all-gone-after-10-9-0-upgrade?pid=22471#pid22471

Fix absolute path checking on windows

---

src/Jellyfin.Extensions/Jellyfin.Extensions.csproj

Already applied to 10.9 https://github.com/jellyfin/jellyfin/commit/7d271547c6eeb0112f876c5028f73f7d0f7990d9

Disable nuget warning in Jellyfin.Extensions

---

Emby.Server.Implementations/Localization/Core/en-US.json

Changes the US English translation of `FailedLoginAttemptWithUserName`. Personally I have never heard or read `try` being used in this way. I always have seen `attempt` being used in this context.
**Changes**
This changes "Failed login try from {0}" to "Failed login attempt from {0}" which is a more usual way of writing such sentence.
**Issues**
N/ A

Change "try" to "attempt" english translation

---

.github/workflows/ci-openapi.yml

**Changes**
Adds a stable publish action which runs on new tags and pushes the spec to the repository server. Uses all the same logic as Unstable specs but with the correct paths.
Now, I'm not 100% sure if this being on master will let it run on the stable branch. I think it does but not 100%. If not we can forward-port cherry-pick it into the release branch.
**Issues**
N/A

Add OpenAPI spec generator for stable releases

---

Directory.Packages.props
MediaBrowser.Model/MediaBrowser.Model.csproj

Found when verifying 10.9 nuget packages
https://www.nuget.org/packages/Microsoft.AspNetCore.HttpOverrides/
According to `dotnet list package --deprecated` this was the only deprecated package

Fix reference to deprecated package

---

src/Jellyfin.LiveTv/TunerHosts/M3UTunerHost.cs

TV Tuners have basically unpredictable behaviors on HEAD requests, and we cannot fail and try all potential code it returns. Just fallback to check for extension for all HEAD request that appears to be failed.
**Changes**
**Issues**
Fixes #11661, and some reports in #11554

Always fallback for failed HEAD request

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

Hardware encoders have different expectations about quality input. VAAPI's mjpeg encoder excepts JPEG quality divided by QP2LAMBDA as input.
**Changes**
Maps the ffmpeg qscale to the QP2LAMBDA divided mjpeg quality value that vaapi_mjpeg expects.
**Issues**
See issue comment: https://github.com/jellyfin/jellyfin/issues/11556#issuecomment-2113327889

Fix quality parameter for vaapi_mjpeg

---

Emby.Naming/TV/TvParserHelpers.cs
MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs
MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs
tests/Jellyfin.Naming.Tests/TV/TvParserHelpersTest.cs

NFOs can include more than our three status descriptions: https://www.themoviedb.org/bible/tv
**Changes**
* Add helper function to properly transform different strings into our enum values

Fix series status parsing

---

Emby.Server.Implementations/Images/BaseFolderImageProvider.cs
Emby.Server.Implementations/Images/MusicAlbumImageProvider.cs
MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs
MediaBrowser.Providers/Manager/MetadataService.cs
MediaBrowser.Providers/Playlists/PlaylistItemsProvider.cs

#8163 removed scanning of local playlists. Since they are now always excluded, only a manual refresh actually populates the playlist.
**Changes**
* Essentially revert the mentioned PR
* Some other small fixes
* Properly fix infinite collage duplication if playlist is in album without picture
**Issues**
Fixes #11625
Fixes #3088

Fix local playlist scanning

---

Emby.Server.Implementations/Data/SqliteItemRepository.cs

Whitespace values weren't being filtered out in advance.
Remove the possibility of this happening again by always binding
Should fix #11605

Fix not binding to SQL parameters

---

src/Jellyfin.LiveTv/TunerHosts/M3UTunerHost.cs

**Changes**
Added text/plain and text/html to disallowed mime types as they will most likely be m3u8 playlists, which is not compatible with SharedHttpStream. Also had to change to ContentType.MediaType instead of ContentType.ToString as the latter includes the charset.
**Issues**
Fixes #11679

Use MediaType instead of ToString and add text/ as disallowed mimetypes

---

Emby.Server.Implementations/Library/Resolvers/TV/SeasonResolver.cs
MediaBrowser.Controller/Entities/TV/Series.cs
MediaBrowser.Providers/TV/SeriesMetadataService.cs
MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs

Season names got lost when not scanning the base NFO, so they got reset on any subsequent scan.
**Changes**
Fetch them from the internal dict if it was filled while scanning, otherwise fetch from child seasons.

Fix season names

---

MediaBrowser.Providers/Playlists/PlaylistItemsProvider.cs

Currently we resolved any valid paths denoted in the playlist, possibly also to files outside of libraries
**Changes**
* Restrict referenced items in playlists to be within any library

Secure local playlist path handling

---

Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs

Turns out it's the same
`[WRN] [53] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Media source "17a76092102691425e94624a69247057" not found at "/mnt/USBshare/Movies/Top Gun (1986)/extras/Top Gun_t04.mkv" for item 17a76092-1026-9142-5e94-624a69247057`

Only log item id in trickplay warning

---

Jellyfin.Api/Helpers/RequestHelpers.cs

Fixes https://forum.jellyfin.org/t-problems-with-the-api-since-version-10-9-x

Don't require user when getting current session

---

MediaBrowser.Providers/Trickplay/TrickplayProvider.cs

On a normal scan `IsAutomated` is always false, therefore triggering trickplay generation.
**Changes**
* Remove the condition. If it is disabled for the library on scan it should always skip it.
**Issues**
Fixes #11730

Do not run trickplay on scan if disabled

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Like a lot of other encoders they need an underscore between two words.
**Changes**
**Issues**

Fix VideoToolbox H264 constrained profile option

---

.github/workflows/ci-openapi.yml

**Changes**
- Replace deprecated `::set-output` usage
- Write OpenAPI diff to workflow summary
- Write OpenAPI diff comment to a file and instruct the create-or-update-comment action to read from that file
- This fixes an issue where large diffs would cause the action to fail
**Issues**

Improve OpenAPI diff workflow

---

MediaBrowser.Model/Entities/MediaStream.cs

FFmpeg 6.1 and newer can recognize Dolby Atmos and DTS:X. This change makes it possible to see if a track has one of these technologies if the used FFmpeg supports it.

Prefer profile over codec for display title

---

Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs

**Changes**
Some users may set this value too low, causing the trickplay generation to fail. Reset this interval to the minimum valid value of 1 second when the user-configured value is too small to prevent generation failures.
**Issues**
Fixes #11784

Override too small trickplay image interval

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Disable VA-VK interop on not supported kernel versions
**Issues**
https://forum.jellyfin.org/t-subtitle-burn-in-with-hardware-decoding-error-v10-9?pid=24176

Disable VA-VK interop on not supported kernel versions

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

This might still be not exactly accurate but should not be tell from human eyes on most videos.
The most problematic ones would be the 3D Videos where the aspect ratio stored in the container might be per eye instead of per frame, which will lead to an incorrect height being calculated. But we can really do little about that for current pipeline.
**Changes**
- Re-calculate frame height for hardware mjpeg encoders
- Use SAR to recalculate aspect ratio for software mjpeg encoder
**Issues**
Fixes #11785

Recalculate trickplay image height for anamorphic videos

---

MediaBrowser.Providers/Manager/MetadataService.cs

Virtual items such as missing episodes should not be taken into account when calculting `DateLastMediaAdded `
**Changes**
* Exclude virtual items from DateLastMediaAdded calculation
**Issues**
Fixes #11786 (potentially)

Exclude virtual items from DateLastMediaAdded calculation

---

Jellyfin.Api/Helpers/MediaInfoHelper.cs

Live TV streams are unlikely to use modern features like HEVC and HDR, and the bitrate is also unlikely to be very high.
This sets a hard limit of 20 Mbps for Live TV transcoding and forces the use of the MPEG-TS container to solve compatibility issues with certain providers/tuners.
**Changes**
**Issues**
Fixes #11742
Fixes #11723

Force more compatible transcoding profile for LiveTV

---

MediaBrowser.Providers/MediaInfo/ProbeProvider.cs

Before we write the Paths to the item we check for distinction. This should be done on the comparison too. I threw in ordering to prevent issues of potential FS inconsistent return values.
**Issues**
Potentially #11783

Improve reliability of HasChanged check

---

CONTRIBUTORS.md
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

**Changes**
Kill ffmpeg process when trickplay scheduled task is stopped.
**Issues**
Fixes #11787

Trickplay: kill ffmpeg when task is cancelled

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

ffmpeg6 and ffmpeg5 work a little differently.
**Changes**
- Fix the IOSurf error in QSV transcoding
**Issues**
- Fixes #11819
`Error querying (IOSurf) the encoding parameters: invalid video parameters (-15)`

Fix the IOSurf error in QSV transcoding

---

src/Jellyfin.LiveTv/TunerHosts/M3UTunerHost.cs

**Changes**
Only use `SharedHttpStream` for streams that appear to be MPEG-TS streams, and only use a HEAD request when there is no extension in the URL. This is the only solution I can think of without making API changes. `SharedHttpStream` is really uncommon for M3U Tuners where most of them is using HLS, and the ones not using HLS almost uses MPEG-TS streams exclusively. Any other weird Tuners that lies in the mime type and does not provide valid file extension, just treat that stream as normal livestream. If that does not work the only way to make that work is to add an option to the Tuner config to force the stream type, but that would not be feasible for 10.9.
**Issues**
Potentially: 
#11679 #11554

Use SharedStream for LiveTV more restrictively

---

MediaBrowser.Common/Net/NetworkConstants.cs
src/Jellyfin.Networking/Manager/NetworkManager.cs

Currently, we are assuming all IPs not in user-set subnet are external IPs, but this is not accurate enough:
- IPv4 addresses are not in IPv6 subnets and vice versa, and we will be returning IPv4 binding address as IPv6 external IP
- Link Local Addresses are not considered as LAN address in most cases, but we are treating them as external address if available and that is wrong because such addresses are not route-able.
**Changes**
**Issues**

Filter invalid IPs on external interface matching

---

MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs

**Changes**
FFmpeg's built-in batch extraction will have trouble writing correct files if the filename appears to be a path. Instead, use the stream index name as the file name in such cases and extract those attachments one by one. This method is slower but works around problematic files that have a path as the filename.
**Issues**
Fixes #11692

Extract media attachment one by one if the filename appears to be a path

---

Jellyfin.Api/Controllers/LibraryStructureController.cs

The access check also checks if the library is enabled, this makes it impossible to enable disabled libraries.
Regression from  #11171
Fixes #11875 and #11829

Don't check if admin has access to library when updating

---

Emby.Server.Implementations/Session/SessionManager.cs
Jellyfin.Api/Controllers/TvShowsController.cs
MediaBrowser.Controller/Entities/TV/Season.cs
MediaBrowser.Controller/Entities/TV/Series.cs
MediaBrowser.Providers/TV/SeriesMetadataService.cs

The removal logic filters for virtual episodes but the query for getting all episodes of a series filtered out any missing episodes (which are the virtual episodes), so we only checked against file system episodes, rendering the function useless.
**Changes**
* Return missing items when getting episodes of a series without a user specified
**Issues**
Fixes #7207

Return missing episodes for series when no user defined

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

TagLib has its own limitations, which cause it to fail on certain audio files or extract incomplete information from the tags. Use the information from ffprobe when TagLib fails to extract data.
**Changes**
- Use ffprobe's data when taglib fails.
**Issues**
Fixes #11678
Also forum: https://forum.jellyfin.org/t-mka-tags-recognized-by-jellyfin

Use music metadata from ffprobe when TagLib fails

---

Emby.Server.Implementations/Library/Resolvers/Audio/MusicArtistResolver.cs

In rare cases, such as when an artist only has multi-part albums, the multi-part album folder might be incorrectly detected as an artist folder, causing the album discs to be split.
Caveat 1: For some artists with names indistinguishable from an album part (for example, "Volume 10"), the folder name for the artist needs to be escaped, like `[Volume 10]`.
Caveat 2: Users already affected by this might see multiple duplicated albums, both the wrongly split ones and the correctly grouped ones, after a library-specific scan. This can be fixed by performing a global validation in the scheduled task -> scan media library. Only the valid albums will remain after that is completed.
**Changes**
- Don't mark folder as artist folder when the folder appears to be a multi-part album.
**Issues**

Fix multi-part album folder being detected as artist folder

---

Jellyfin.Api/Helpers/MediaInfoHelper.cs
Jellyfin.Api/Helpers/StreamingHelpers.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Yet another attempt to cover more use case without an API change.
**Changes**
- Moved profile enforcement to StreamingHelper because not all LiveTV requests call OpenMediaSource
- Raised bitrate limit from 20M to 30M
- When LiveTV input source has no valid bitrate, still try copy stream when other constraints are satisfied
**Issues**
Fixes #11847

Relax remuxing requirement for LiveTV

---

Emby.Server.Implementations/ScheduledTasks/Tasks/AudioNormalizationTask.cs
src/Jellyfin.Extensions/StreamExtensions.cs

Should prevent OOM error
Also optimized the regex so it can bail out earlier
Should fix #11909

Audio normalization: parse ffmpeg output line by line

---

Jellyfin.Api/Auth/FirstTimeSetupPolicy/FirstTimeSetupHandler.cs
tests/Jellyfin.Api.Tests/Auth/FirstTimeSetupPolicy/FirstTimeSetupHandlerTests.cs

**Changes**
Instead of explicitly succeeding or failing, we should defer to DefaultAuthorizationHandler to handle user validation based on examples I could find. This seems to fix the issue when testing locally.
**Issues**
Fixes #11620

Fix FirstTimeSetupHandler allowing public access

---

Emby.Server.Implementations/Data/SqliteItemRepository.cs
Jellyfin.Server/Migrations/MigrationRunner.cs
Jellyfin.Server/Migrations/Routines/FixAudioData.cs
MediaBrowser.Controller/Entities/InternalItemsQuery.cs

The provider checks for lyric changes rely on the content of `LyricFiles` within `Audio`. But `Audio` did not require serialization into the database, dropping any non-`BaseItem` data on save. Therefore on every scan the check would fail and the provider would run.
**Changes**
* Declare `Audio` as `RequiresDeserialization`
* Backfill serializable data for all `Audio` objects

Mark Audio as RequiresDeserialization and backfill data

---

Emby.Server.Implementations/ConfigurationOptions.cs
Jellyfin.Server.Implementations/Extensions/ServiceCollectionExtensions.cs
Jellyfin.Server/Extensions/WebHostBuilderExtensions.cs
Jellyfin.Server/Startup.cs
MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs

**Changes**
This is an attempt to track down possible causes of remaining database lockups. Add an environment variable to disable the second-level cache entirely to see if it works better on systems that still experience lockups.
For example (note the double underscore `__`  between `SQLITE` and `disableSecondLevelCache` is required):
```
export  JELLYFIN_SQLITE__disableSecondLevelCache=true
```
This is not a guaranteed fix, just an option for (advanced) users to test if it improves the situation. So it may be removed in future version.
**Issues**
See #11589 #11813 #11834
Probably also others I'm not aware of.

Add Env Var to disable second level cache

---

MediaBrowser.Providers/Manager/MetadataService.cs

Distinct on trailers should only check URL distinction.
**Changes**
* Use distinct by URL
**Issues**
Fixes #11924

Check trailer distinction by URL

---

Emby.Server.Implementations/Library/Resolvers/TV/SeasonResolver.cs

**Changes**
* Only set season path if `IsSeasonFolder` is true
**Issues**
Fixes #11916
Fixes #11945
Fixes #11920

Only set season path if season folder parsing was successful

---

Emby.Server.Implementations/TV/TVSeriesManager.cs

**Changes**
Currently Nextup query does not use the limit defined in the query. It just gets ignored halfway through and defaults to "null". This means that no limit is placed and the sqlite query just pulls everything. This fix uses the query to define a limit X. This should also massively speed up nextup from pulling everything to only pulling X number of items.
Originally PR https://github.com/jellyfin/jellyfin/pull/11955 - but redid it against 10.9 as recommeneded.
**Issues**
Resolves slow homescreen loading due to slow nextup query. - https://github.com/jellyfin/jellyfin/issues/11888 https://github.com/jellyfin/jellyfin/issues/11316

NextUp query respects Limit

---

MediaBrowser.Providers/TV/SeriesMetadataService.cs

These options should never be true since this will delete any folders and files if the virtual season has a path associtated.
**Changes**
* Only remove internal metadata path on virtual episode/season removal
**Issues**
* Someone on forum reported losing a full series when a virtual season was removed

Do not delete file locations for virtual episodes and seasons

---

MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs

We were saving trailer URIs in the old Kodi format and then complained on import about it...
**Changes**
* Export as new trailer URI format

Export trailer URLs in new format

---

MediaBrowser.Controller/Entities/Movies/BoxSet.cs

- default sort is still Release Date Ascending
- choosing sort by Release Date will change it to sort by Release Date Descending
This is because most people go to collections to browse new movies to watch, and recently released movies should be on top.
I could also add a new sort order option instead, "PremiereDateDesc" if that's more suitable.
**Changes**
Currently collections default to sort order "Release Date Ascending"
This change allows to sort by Release Date Descending when sort order "Release Date" is chosen
**Issues**

Allow collection sort by Release Date Descending

---

README.md

Removes Azure and Reddit shields
Links to the matrix space instead of general chat

Update shields in README

---

MediaBrowser.Controller/Providers/DirectoryService.cs
MediaBrowser.Controller/Providers/IDirectoryService.cs
MediaBrowser.LocalMetadata/Images/EpisodeLocalImageProvider.cs
MediaBrowser.Providers/Manager/ImageSaver.cs
MediaBrowser.Providers/Manager/ItemImageProvider.cs

For some reason episode images were saved into a `metadata` subdirectory instead of main directory with `-thumb` suffix. The provider only checked for the latter, therefore never picking up the images we saved.
**Changes**
* Make provider recognize episode pictures within `metadata` subdirectory
* Change saving logic to not save into `metadata` subdirectory, but instead use `-thumb` suffix and save next to episode file
* Add empty folder deletion when removing images
**Issues**
Fixes #11862

Fix local image saving

---

MediaBrowser.Controller/Providers/IProviderManager.cs
MediaBrowser.Providers/Manager/ItemImageProvider.cs
MediaBrowser.Providers/Manager/MetadataService.cs
MediaBrowser.Providers/Manager/ProviderManager.cs
tests/Jellyfin.Providers.Tests/Manager/ItemImageProviderTests.cs

When identifying and having local NFO, the local NFO data overrides the identification.
**Changes**
* Do not run local metadata providers when identifying manually
* Do not run local metadata providers when replaceing all and saving NFOs
* Do not use local images if replacing and saving
**Issues**
Fixes #11619

Fix identify over NFO and replace all when NFO saving enabled

---

Emby.Server.Implementations/Library/LibraryManager.cs
Jellyfin.Api/Controllers/LibraryStructureController.cs
MediaBrowser.Controller/Library/ILibraryManager.cs

This handler should not just spawn a normal library validation task because our new logic will prevent the removal of library root folder unless explicitly required, which will cause the old lib still "ghosting" in the db.
**Changes**
- Validate top folder with explicit requirement to remove invalid libraries during library renaming
- Attempt to refresh the new lib only when possible
**Issues**
Fixes #11937
Fixes #11885
If you already have duplicated libs ghosting, just upgrade to a version contains this PR won't fix your issue. 
A mitigation to this is to rename your lib one more time after you updated to a version contains this PR. This will remove the ghosting one.
Alternatively, you can remove the renamed library, which will also remove the ghosting one, then you can add it back with …

Fix Library renaming

---

MediaBrowser.Providers/Manager/ImageSaver.cs

We should never write to the media dir if not configured.
**Changes**
**Issues**

Fallback to local dir when saving to media dir fails

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

When TagLib fails, artists are empty arrays instead of null
Don't back-port this one as we are going to move away from taglib in 10.10
**Changes**
**Issues**
Fixes #11899

Fix fallback artist when taglib fails

---

MediaBrowser.Controller/Entities/Folder.cs

Got an error when an item was moved and even after a library validation it reappeared, even though the folder was removed. Checked the code and found this.
**Changes**
* do not stop validation if no children are returned, instead continue and cleanup all children
**Issues**

Do not stop validation if folder was removed

---

MediaBrowser.Controller/Entities/Movies/BoxSet.cs

Reverts jellyfin/jellyfin#11615
Items in boxsets show up in reverse order by default
https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Controller/Entities/Movies/BoxSet.cs#L23

Revert "Allow collection sort by Release Date Descending"

---

MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs

When the container name is `mpeg`, it means it is MPEG-PS, while the TS container should have the explicit name `mpegts`.
**Changes**
**Issues**
Fixes https://forum.jellyfin.org/t-transcoding-fails-for-mpeg1-mpeg2-videos-with-mp2-audio?pid=26210#pid26210

Fix mpeg-ts detection

---

Jellyfin.Api/Controllers/ItemRefreshController.cs
MediaBrowser.Providers/Manager/MetadataService.cs

Metadata fields are not cleared on replace if the newly fetched metadata does not include it.
Additionally, previously set language options for metadata are also replaced which should not be the case.
**Changes**
* Clear existing fields on replace all
* Respect previously set metadata language options on replace all
**Issues**
Fixes #5236
Fixes #12015
Fixes #12021
Possibly fixes #11923

Fix replace all and respect metadata settings

---

MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs

**Changes**
- Fix video embedded image detection.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/commit/debbfaa502cae91212f2386d237616ad2a671a88. Embedded images also exist in video.
Fixes [#10637](https://github.com/jellyfin/jellyfin/issues/10637)

Fix video embedded image detection

---

MediaBrowser.LocalMetadata/Images/EpisodeLocalImageProvider.cs

Function already checks for `-thumb`. Regression from #11934
**Changes**
* Remove `-thumb` from initial input to episode thumb check
* Simplify `metadata` subdir check
**Issues**

Fix local episode image thumb recognition

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

**Changes**
files extension returned by GetDiscInfo() are always uppercase(.M2TS). It causes issue when original filenames are in lowercase. This fixes it by ignoring the case while keeping the order.
**Issues**
Fixes #12060

Make m2ts extension case-insensitive

---

MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs

`<year>` is the  tag for production year. The date in `<releasedate>` can be different due to locale, so we should only use it if it is unset.
**Changes**
* Do not override already set `ProductionYear`
**Issues**
Fixes #12111

Do not override <year> if <releasedate> is set

---

src/Jellyfin.Networking/Manager/NetworkManager.cs

Kestrel in dual-socket mode will always serve IPv4 addresses as IPv6 mapped, making our checks fail.
**Changes**
* Check if address is IPv6 mapped IPv4 and map back to IPv4
* Use `IsLoopback` for more reliable loopback checks
**Issues**
Fixes #11968

Map IPv6 mapped IPv4 addresses back to IPv4 before running checks

---

Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs

We only save to the database, not to the file system. This leads to the bad data being re-read on scan. Therefore just run save item and save metadata without running a metadata scan.
**Changes**
* Only run metadata savers, don't run metadata update

Fix Cleanup Task metadata saving

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
MediaBrowser.Model/Entities/MediaStream.cs

MicroDVD is a text-based subtitle but it shares the same file extension ".sub" with DVDSUB/VOBSUB bitmap subtitle.
**Changes**
- Fix MicroDVD being recognized as DVDSUB subtitles
**Issues**
- Fixes #8036

Fix MicroDVD being recognized as DVDSUB subtitles

---

MediaBrowser.Controller/Entities/Folder.cs

**Changes**
* Only cleanup children if we received an `IOException` or `SecurityException` and don't clean up on any other exceptions

Only cleanup children on specific exceptions

---

MediaBrowser.Providers/Playlists/PlaylistItemsProvider.cs

The XML provider would override the results of the item provider because the item provider wrote to the original item which is replaced by the results of the provider.
**Changes**
* Rewrite `PlaylistItemsProvider` as `ILocalMetadataProvider`

Rewrite PlaylistItemsProvider as ILocalMetadataProvider

---

Emby.Server.Implementations/IO/ManagedFileSystem.cs
Emby.Server.Implementations/Library/LibraryManager.cs
Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteCacheFileTask.cs
Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteTranscodeFileTask.cs
MediaBrowser.Controller/Entities/BaseItem.cs
MediaBrowser.Controller/IO/FileSystemHelper.cs
MediaBrowser.Providers/Manager/ImageSaver.cs
MediaBrowser.Providers/Manager/ItemImageProvider.cs
MediaBrowser.Providers/Manager/MetadataService.cs

Regression from #11934
Recursive removal is too wide scoped, so limit it to remove the legacy `metadata` directory for episodes
**Changes**
* Limit scope of empty directory removal after image removal
* Add helper class for recursive empty folder removal
* Do not remove images from items if they could not be removed from the file system
**Issues**
Fixes #12023 (potentially)

Fix empty image folder removal for legacy locations

---

Emby.Server.Implementations/Library/ResolverHelper.cs
MediaBrowser.Controller/Providers/DirectoryService.cs
MediaBrowser.Controller/Providers/IDirectoryService.cs
tests/Jellyfin.Controller.Tests/DirectoryServiceTests.cs

**Changes**
This fix is mainly so I can mass-add series _and_ movie entries using a `IMultiItemResolver` without having to resort to complicated logic using _both_ a `IItemResolver` and a `IMultiItemResolver` by splitting up what gets added where.
I've also added three new interface methods to the `IDirectoryService`, one of which is used in the modified
`ResolverHelper.SetInitialItemValues(…)` to get the file system entry info for the item regardless of which type the file system entry is.
In my local testing so far I haven't found any issues introduced by this change.
**Issues**

Don't expect `BaseItem` to be a movie/video file.

---

MediaBrowser.Controller/LiveTv/LiveTvConflictException.cs
src/Jellyfin.LiveTv/TunerHosts/BaseTunerHost.cs
src/Jellyfin.LiveTv/TunerHosts/HdHomerun/HdHomerunManager.cs

Different error messages are welcome.
Current:
```
[2024-06-27 22:54:12.993 -04:00] [ERR] [18] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Items/b26b7fddc7b41a49f7d45f13b0db7dc5/PlaybackInfo".
MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.
at Jellyfin.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, IList`1 currentLiveStreams, CancellationToken cancellationToken)
at Jellyfin.LiveTv.DefaultLiveTvService.GetChannelStreamWithDirectStreamProvider(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
at Jellyfin.LiveTv.LiveTvMediaSourceProvider.GetChannelStream(String id, String …
```

Add messages to LiveTvConflict exception

---

CONTRIBUTORS.md
tests/Jellyfin.Server.Implementations.Tests/Sorting/PremiereDateComparerTests.cs

**Changes**
Add unit tests for PremiereDateComparer
**Issues**
_Does not fix_ #12101, but helps to clarify whether this behavior is expected in this scenario

Add unit tests for PremiereDateComparer

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

This adds a fast SIMD optimized software tonemap filter support to the server. This filter currently does not support dolby vision reshaping and only support HDR10 and HLG inputs. With current veryfast libx264 settings we can expect 4K60 transcoding+tone mapping on a modern processor with 8 cores equivalent to Zen3/Golden Cove/Firestorm level performance. 
**Changes**
- Add tonemapx filter support to software transcode pipeline
- Add tonemapx filter support to thumbnail generation pipeline
**Issues**
Depends on ffmpeg pr https://github.com/jellyfin/jellyfin-ffmpeg/pull/407
The perf figures in the original post only reflects the initial implementation. The finalized perf figures are here: https://github.com/jellyfin/jellyfin-ffmpeg/pull/407#issuecomment-2198303178

Add software tonemap filter support

---

MediaBrowser.Controller/Entities/TV/Series.cs

Reverts a part of #12050.
**Changes**
Starting with 10.9.7, when refreshing metadata or scanning a series it would reset the virtual season to "Season Unknown". Reverting a part of the 10.9.7 related to season lookups fixed this.
~~Probably needs more testing for non-virtual season usages.~~
**Issues**
Fixes #12208 (confirmed via forum)

Fix season handling ("Season Unknown" / unneccesary empty seasons)

---

.github/ISSUE_TEMPLATE/issue report.yml

Introduced a checkbox section at the start where a user needs to walk through before proceeding with the creation of the issue.
Added an "additional information" field where users can include additional information to the issue. This is useful for information that does not fit in with other fields but that still might be useful to the issue at hand.
Made the reproduction steps section more clear with an actual example in the placeholder.
Added an "expected result/ behavior" field of the reproduction steps. Here users should fill in what is the correct and expected behavior when following the reproduction steps.
Added an "actual result/ behavior" field of the reproduction steps. Here users should fill in what is actually happening when following the reproduction steps.
Removed older …

Refactor bug report issue template

---

Emby.Server.Implementations/AppBase/BaseApplicationPaths.cs
Emby.Server.Implementations/IO/ManagedFileSystem.cs
Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs
Emby.Server.Implementations/ScheduledTasks/Tasks/AudioNormalizationTask.cs
Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
Jellyfin.Server/Helpers/StartupHelpers.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
MediaBrowser.MediaEncoding/Transcoding/TranscodeManager.cs
src/Jellyfin.Drawing.Skia/SkiaEncoder.cs

This way we take advantage of systems where the temp directory is backed by RAM.
* Clean up temp files right after use where possible
* Prefer temp dir over cache/trancode dir for short lived one time use files
* Add more identifiable information to some temp files/directories
* Cache DVD/Blu-Ray concat file to improve subsequent playback start times

Use real temp dir instead of cache dir for temp files

---

Emby.Server.Implementations/Data/SqliteItemRepository.cs
MediaBrowser.Model/Entities/ProviderIdsExtensions.cs
tests/Jellyfin.Model.Tests/Entities/ProviderIdsExtensionsTests.cs

**Changes**
So this prevents the deserialization code from breaking if there are `=` characters in the key or value of the provider id.
Also adds some documentation to the functions themselves.
This also add a set of `Remove*` functions and made the input checking stricter for the `Set*` functions.
**Issues**
Reference: https://github.com/ShokoAnime/Shokofin/issues/62
Custom ProviderIds were disappearing on a normal (non "replace") scan due to them not being deserialized (quietly)
When this is in, I'll manually backport it to the 10.9 branch but without the breaking behavior changes.

Add check for ProviderIds to prevent '=' from appearing in keys, also support '=' in the values.

---

Emby.Server.Implementations/Library/MediaSourceManager.cs
MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
MediaBrowser.Model/Entities/MediaStream.cs

**Changes**
This PR adds support for streaming raw PGS subtitles (graphical subtitles) if requested by the client. PGS subtitles can be loaded from external `.sub` / `.sup` files or extracted from an `.mkv` container.
This removed the need for video transcoding just for the PGS subtitle.
**Related Pull Request (web):** https://github.com/jellyfin/jellyfin-web/pull/5688
**Related Pull Request (vue):** https://github.com/jellyfin/jellyfin-vue/pull/2404
**Discussion points:**
- Extracting subtitles from large `.mkv` can take multiple minutes for ffmpeg to process the whole file. This is only be done once per media file. The subtitles are cached afterwards.
- PGS subtitles are large (multiple megabytes) and may take a while to load.

Allow streaming of raw PGS subtitles without transcoding

---

Emby.Server.Implementations/Data/SqliteItemRepository.cs
MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
tests/Jellyfin.MediaEncoding.Tests/Probing/ProbeResultNormalizerTests.cs

Maybe passing ILocalizationManager into the ctor of MediaStream is a better solution for master?
Fixes #12276

Fix localization of audio title

---

MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs

```
[2024-07-16 18:00:20.517 +02:00] [ERR] [65] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
at MediaBrowser.Model.Entities.ProviderIdsExtensions.SetProviderId(IHasProviderIds instance, String name, String value) in /home/loma/dev/jellyfin/MediaBrowser.Model/Entities/ProviderIdsExtensions.cs:line 121
at MediaBrowser.Model.Entities.ProviderIdsExtensions.SetProviderId(IHasProviderIds instance, MetadataProvider provider, String value) in …
```

Fix ArgumentNullException while scanning music

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

```
[2024-07-17 14:31:18.202 +02:00] [ERR] [19] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
at MediaBrowser.Model.Entities.ProviderIdsExtensions.SetProviderId(IHasProviderIds instance, String name, String value) in /home/loma/dev/jellyfin/MediaBrowser.Model/Entities/ProviderIdsExtensions.cs:line 121
at MediaBrowser.Model.Entities.ProviderIdsExtensions.SetProviderId(IHasProviderIds instance, MetadataProvider provider, String value) in …
```

Fix (another) ArgumentNullException while scanning music

---

Emby.Server.Implementations/ApplicationHost.cs
MediaBrowser.Controller/Entities/BaseItem.cs
MediaBrowser.Controller/Entities/Movies/Movie.cs
MediaBrowser.Controller/Entities/TV/Episode.cs
MediaBrowser.Controller/Entities/TV/Series.cs
MediaBrowser.Controller/Entities/Trailer.cs
MediaBrowser.Controller/LiveTv/LiveTvProgram.cs
MediaBrowser.Controller/Providers/IExternalId.cs
MediaBrowser.Controller/Providers/IExternalUrlProvider.cs
MediaBrowser.Controller/Providers/IProviderManager.cs
MediaBrowser.Model/Providers/ExternalIdInfo.cs
MediaBrowser.Providers/Manager/ProviderManager.cs
tests/Jellyfin.Providers.Tests/Manager/ProviderManagerTests.cs

**Changes**
Moves the `GetRelatedUrls()` out from `BaseItem` to a dedicated provider so plugins can add dynamic urls.
See linked plugin PRs for sample implementations.

Move external url listing to provider for plugin use

---

Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
MediaBrowser.Model/Configuration/TrickplayOptions.cs

This would be significantly faster than decoding every frame, but it does have compatibility issues. Not all decoders support this mode, notably the VP9 decoder, CUVID decoders, and QSV decoders.
Some videos with very long key-frame intervals may also perform poorly with this mode, as the image timing could become too inaccurate to reflect the actual frame.
**Changes**
- Add `EnableKeyFrameOnlyExtraction` option to `TrickplayOptions`
**Issues**
Fixes #11336
Web: https://github.com/jellyfin/jellyfin-web/pull/5800

Add option to extract keyframe only during trickplay image generation

---

Jellyfin.Api/Helpers/DynamicHlsHelper.cs
Jellyfin.Api/Helpers/HlsCodecStringHelpers.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs

**Changes**
Add VP9 as a valid HLS format to enable remuxing. This is useful when audio processing is required, but the VP9 video can be passed as-is to avoid unnecessary video transcoding.
No VP9 encoder is enabled and should not be enabled. AV1 and HEVC should be preferred over VP9 if video transcoding is required.
**Issues**

Add remuxing support for VP9

---

Jellyfin.Api/Controllers/DynamicHlsController.cs
MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs

**Changes**
Add ac4 to supported decoders. Tested with dolby official mp4 samples and confirmed AC-4 audio tracks are transcoding.
Depends on jellyfin/jellyfin-ffmpeg#387
**Issues**

Enable Dolby AC-4 decoder

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

**Changes**
- Enable `mjpeg_videotoolbox` encoder
- Adapt the trickplay processing pipeline for VideoToolbox
**Issues**
Requires jellyfin/jellyfin-ffmpeg#388

Enable hardware Trickplay processing pipeline for VideoToolbox

---

Jellyfin.Api/Controllers/UniversalAudioController.cs
Jellyfin.Api/Helpers/DynamicHlsHelper.cs
MediaBrowser.MediaEncoding/Transcoding/TranscodeManager.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs

**Changes**
This PR adds audio remuxing (copying audio into another container without transcoding) support to the UniversalAudioController, allowing the client to request the audio to be in a specific container. When remuxing with HLS, the HLS container's constraint applies, and it will fallback to transcoding when the original audio codec is not supported by the chosen HLS container. When remuxing with HTTP, this assumes that the client-provided container supports the audio codec. If it does not, ffmpeg would fail.
To workaround the complex codec+container support situation in HLS, an HLS container override feature has been added. The client can explicitly require a container+codec combination supported by HLS. For example, `ts|mp3` and `mp4|flac`. When combinations like these are …

Add audio remux to UniversalAudioController

---

Directory.Packages.props
Emby.Server.Implementations/ConfigurationOptions.cs
Emby.Server.Implementations/Session/SessionManager.cs
Jellyfin.Api/Controllers/DevicesController.cs
Jellyfin.Server.Implementations/Devices/DeviceManager.cs
Jellyfin.Server.Implementations/Extensions/ServiceCollectionExtensions.cs
Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj
Jellyfin.Server.Implementations/Security/AuthorizationContext.cs
Jellyfin.Server.Implementations/Users/DeviceAccessHost.cs
Jellyfin.Server/Extensions/WebHostBuilderExtensions.cs
Jellyfin.Server/Startup.cs
MediaBrowser.Controller/Devices/IDeviceManager.cs
MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs

The EFCoreSecondLevelCacheInterceptor will place a huge lock even for reading. Implement a ConcurrentDictionary cache to replace it.
**Changes**
**Issues**
Closes #11823

Implement Device Cache to replace EFCoreSecondLevelCacheInterceptor

---

Jellyfin.Api/Controllers/AudioController.cs
Jellyfin.Api/Controllers/DynamicHlsController.cs
Jellyfin.Api/Controllers/UniversalAudioController.cs
Jellyfin.Api/Controllers/VideosController.cs
MediaBrowser.Controller/MediaEncoding/BaseEncodingJobOptions.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs
MediaBrowser.Model/Dlna/StreamInfo.cs
MediaBrowser.Model/Dlna/TranscodingProfile.cs

LAME's VBR mode only has advantage over a certain bitrate range. For very low and very high bitrate, use the ABR mode instead.
aac_at's CVBR mode produces very good quality and is not worse than its TVBR mode in blind testing. Use this mode for convenience.
The ffmpeg native aac encoder will have quality regression with its VBR mode. Always use CBR mode for ffmpeg's native aac encoder.
This also adds `EnableAudioVbrEncoding` to TranscodingProfile, enables the client to selectively disable VBR transcoding when it causes playback problems.
**Changes**
- Use ABR for libmp3lame when VBR mode has its limitation
- Supports aac_at's CVBR mode
- Adds `EnableAudioVbrEncoding` to TranscodingProfile
**Issues**

Add better audio VBR settings

---

.github/ISSUE_TEMPLATE/issue report.yml

Jellyfin has updated to 10.9.8. This change updates the issue template to update the server version selector from 10.9.7 to 10.9.8.
**Changes**
The version selector for server has been updated to 10.9.8.
**Issues**
N/A

Update issue report.yml to use 10.9.8 version

---

Jellyfin.Api/Controllers/LiveTvController.cs
Jellyfin.Api/Models/LiveTvDtos/GetProgramsDto.cs

Functionally no different on the API side, but the api spec doesn't correctly reflect that the property is optional.
Requested here: https://github.com/jellyfin/jellyfin-sdk-kotlin/pull/960#issuecomment-2176198249

Fix up getting livetv programs api docs

---

MediaBrowser.Model/Dlna/StreamBuilder.cs
tests/Jellyfin.Model.Tests/Dlna/StreamBuilderTests.cs

The current stream builder logic does not check the channel limit when determining if the audio stream can be directly used, and this can cause some undesired effects:
- A high channel count surround sound stream might be picked even if a stereo one exists when the user requires stereo audio.
- The user's preferred audio codec might not be respected during the downmix because the requested codec is now forced to be the same as the original source.
**Changes**
- Check TranscodingMaxAudioChannels for directAudioStream candidates
- Update test cases to reflect this change
**Issues**

Check MaxAudioChannels for directAudioStream candidates

---

MediaBrowser.Model/Entities/MediaStream.cs

This displays the Dolby Vision Profile when available instead of just "HDR" in the display title.
**Changes**
- Use full name "Dolby Vision" in `VideoDoViTitle` as we are using full name in other fields like the audio title. 
- Add fallback description for compat id 6
- Prefer `VideoDoViTitle` in display title when available, otherwise keep using `VideoRange`
**Issues**
The feature request: https://features.jellyfin.org/posts/2314/add-dolby-vision-tag-whenever-applicable

Display DOVI title in DisplayTitle when available

---

MediaBrowser.Model/Querying/QueryResult.cs

All (internal) callers populate the list, so we can enable nullability

Enable nullability for QueryResult

---

Emby.Server.Implementations/Data/SqliteUserDataRepository.cs
Emby.Server.Implementations/EntryPoints/UserDataChangeNotifier.cs
Emby.Server.Implementations/Library/MediaSourceManager.cs
MediaBrowser.Controller/Entities/UserItemData.cs
MediaBrowser.Controller/Providers/MetadataResult.cs
MediaBrowser.Model/Dto/UserItemDataDto.cs
MediaBrowser.Model/Session/UserDataChangeInfo.cs
MediaBrowser.XbmcMetadata/Providers/BaseVideoNfoProvider.cs
tests/Jellyfin.XbmcMetadata.Tests/Parsers/MovieNfoParserTests.cs

MetadataResult.GetOrAddUserData doesn't ever get used and is probably broken since the migration to .NET Core as it still expects a Guid for userId

Enable nullable for UserItemData

---

Directory.Packages.props
MediaBrowser.Providers/MediaBrowser.Providers.csproj
MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

The ATL lib provides a lot of advantages to the TagLib we are currently using.
Notably:
- auto-detect the format of the audio data, even if the file extension has the wrong label, and provides unified API for different file types.
- supports more audio formats than TagLib
- supports lyrics natively
- supports playlists and cuesheets
- provides relatively simple and controllable way for non-standard fields, enable us to implement compatibility features instead of waiting for lib updates
- is actually maintained
**Changes**
**Issues**

Migrate to z440.atl from TagLib-Sharp

---

CONTRIBUTORS.md
MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs
tests/Jellyfin.XbmcMetadata.Tests/Parsers/EpisodeNfoProviderTests.cs
tests/Jellyfin.XbmcMetadata.Tests/Test Data/Rising.nfo
tests/Jellyfin.XbmcMetadata.Tests/Test Data/Stargate Atlantis S01E01-E04.nfo

Fixing the `EpisodeNfoParser` so it no longer picks up fields of sub elements (like actor/name) and appending it to the title of the combined Episode object, if a xbmc style multi episode nfo file (multiple `<episodedetails>` blocks) is parsed.
The old implementation iterated over all elements searching for specific tag names without checking the level or parent element.
I didn't test the code in a productive environment but simply extended the test file and fixed the code so the test passes again.
**Changes**
- replaced the current parser implementation that was used for all blocks but the first with the standard episode xml parser
- extracted the parser code to it's own method to prevent code duplication
- extended the test file to include actors so this case is covered by a test in the …

Fix: parsing of xbmc style multi episode nfo files

---

MediaBrowser.Controller/MediaEncoding/DownMixAlgorithmsHelper.cs
MediaBrowser.Model/Entities/DownMixStereoAlgorithms.cs

This adds the AC-4 spec-defined downmix algorithm, which supports 3.0, 5.0, 5.1, 7.0 and 7.1 inputs. The downmix method is defined in [ETSI TS 103 190-1](https://www.etsi.org/deliver/etsi_ts/103100_103199/10319001/01.03.01_60/ts_10319001v010301p.pdf), Section 6.2.17.
This implementation uses the LoRo downmix mode (`preferred_dmx_method == 1`) as we do not need LtRt to support Dolby Pro Logic systems.
The channel mode for 7.1 inputs is always `3/4/0.x` because the channel layout of this mode matches the ffmpeg definition of 7.1.
All AC-4 stream-specific fields used in the downmixing formula are initialized with the spec-defined default values, which means:
- -3dB gain for `loro_cmg` and `loro_smg`, as defined in Table 148.
- -∞dB gain for `lfe_mg` (discard LFE), as defined in Section …

Add AC-4 downmix algorithm

---

MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
MediaBrowser.MediaEncoding/Transcoding/TranscodeManager.cs
tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTests.cs
tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTestsData.cs

Preliminarily tested with https://github.com/jellyfin/jellyfin-ffmpeg/pull/424
- With multi-threaded cli support, FFmpeg 7 is less sensitive to keyboard input
- Vanilla FFmpeg 7 no longer supports using the `c` key to pause
**Changes**
- Fix compatibility between TranscodingThrottler and FFmpeg 7.0
- Add tests for FFmpeg 7.0.1

Fix compatibility between TranscodingThrottler and FFmpeg 7.0

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Jellyfin-ffmpeg 7.0 fixed the hardware surface and the frame ordering issue, which means we can now safely use the hardware surface. The old chain is still kept to support older ffmpeg.
The usage of `derive_device` in `hwupload` is dropped because we no longer interop with OpenCL in videotoolbox pipeline.
**Changes**
**Issues**
Depends on the WIP https://github.com/jellyfin/jellyfin-ffmpeg/pull/424
But is mergeable as this PR maintains compatibility with jellyfin-ffmpeg6

Update VideoToolbox pipeline for jellyfin-ffmpeg7

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Fixed transcoding errors when using software decoders and hardware VideoToolbox filters
- Fixed H264 Hi10P hardware decoding not enabled on supported macOS systems.
**Issues**

Fix VideoToolbox Hi10P

---

MediaBrowser.Providers/Plugins/StudioImages/Plugin.cs
MediaBrowser.Providers/Plugins/StudioImages/StudiosImageProvider.cs

**Changes**
Point the default repository server to the `raw.githubusercontent.com` domain instead of the old `raw.github.com` domain.
**Issues**
Fixes #10538

Update the default repository URL for the StudioImages plugin

---

MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs

This one is particularly nasty because the `Path` is not supposed to be nullable. However, fixing it in the parser and type constructor is beyond the scope of the 10.9 release. For now, just check with `IsNullOrEmpty`.
**Changes**
**Issues**
Fixes #12441

Check attachment path for null before use

---

MediaBrowser.Providers/TV/SeriesMetadataService.cs

**Changes**
Virtual seasons created by Missing Episode Provider are being forced to be non-virtual, which results in ghost seasons when when "Display missing episodes within their series" is unchecked. This change prevents conversion to non-virtual if all episodes for the season have isMissing=true.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/12208 caused by Missing Episode Provider (Requires recreation of the season)

Don't force non-virtual when all episodes in season are isMissing=true

---

MediaBrowser.Model/Plugins/PluginPageInfo.cs

**Description**
A small addition to the summary of the plugin’s Name and DisplayName, making it much easier to understand what the getters and setters actually mean.
**Changes**
i added a bit more explanation to the summary of Name and DisplayName.
Mainly, I explained that they are the names of the plugin.

Update PluginPageInfo.cs summary.

---

src/Jellyfin.LiveTv/Listings/XmlTvListingsProvider.cs

Fixes a bug where certain programs like the "Good Morning America" no longer have the record series button.
**Changes**
Assume that if the program has an EpisodeNumber then it is part of a series. 
**Issues**
The record series button is not displaying on many programs that are generated by zaptoxml.pl perl script.    
https://github.com/jef/zap2xml

Update XmlTvListingsProvider.cs to fix the record series button missing on many programs

---

Jellyfin.Api/Controllers/ImageController.cs
Jellyfin.Api/Controllers/PluginsController.cs
Jellyfin.Api/Controllers/TrickplayController.cs

The server serves images in various endpoints, those are meant to be displayed in the various clients and not for sharing. Setting the content disposition header to `attachment` will force a browser to download the images when opened directly instead of displaying them in the browser.
**Changes**
- Update item image endpoints
- Update plugin image endpoint
- Update user image endpoints
- Update splashscreen image endpoint
**Issues**

Set Content-Disposition header to attachment for image endpoints

---

src/Jellyfin.Drawing/ImageProcessor.cs

Jellyfin will currently process avif files (as demonstrated by renaming a valid `.avif` file to `.jpg`, and jellyfin indexing and displaying it perfectly) but currently does not try processing for some reason.
**Changes**
Adds the AVIF extension to the list of supported image types.
**Issues**
Close #12412

Include AVIF extension for support images

---

Emby.Server.Implementations/TV/TVSeriesManager.cs

This reverts commit 484aea1cdb93804b8388cdf3dfa3344942ad9119.
Turns out this fix from PR #11956 leads to unexpected behaviour as described in issue #12367.
Fixes: #12367
**Changes**
Setting the limit here limits how many series is considered watching; not how many items to return to the client. For a proper fix of the original performance issue I think either the query needs to be redesigned or the [post-processing](https://github.com/jellyfin/jellyfin/blob/d4eeafe53ff8ae2f287f5dca49a873cd71f4c3da/Emby.Server.Implementations/TV/TVSeriesManager.cs#L187C79-L187C88) of the result from this query needs to be smarter somehow...
Note that this PR is against 10.9.z (as that was where the original PR was), but it looks like the original commit was backported to master as well, so it should …

Revert "NextUp query respects Limit (#11956)"

---

MediaBrowser.Model/Dlna/StreamBuilder.cs

We use all codec conditions to test for DirectPlay, but only apply those from the first codec profile.
To maintain backward compatibility with clients, we reverse the codec profiles so that the last (actually the first) codec profile sets the final values for non-numeric attributes.
**Changes**
Apply all codec conditions.
**Issues**
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/2516
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/3388

Apply all codec conditions

---

MediaBrowser.Controller/Entities/Movies/BoxSet.cs

GetChildren and GetRecursiveChildren on the BoxSet class now support all values from ItemSortBy.
This opens up the possibility to add more sorting options for collections in the web ui. (if a sorting comparer exists for it)
for my usercase i want the sorting to be the original insert order.
I settled on using the Default enum for this. Could call it different in the ui if needed.

Add support for ItemSortBy values in BoxSet

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs

**Changes**
- Fix CodecProfiles not taking effect during transcoding
Fixed the issue where only `CodecProfiles` **matching the source** video codec were applied during transcoding.
The target codec of the transcoding is not necessarily the same as the source codec.
Partically reverts #9723,
because [this line](https://github.com/jellyfin/jellyfin/pull/9723/files#diff-bde118dfa6110f699ead01698c41be0bb9b4b7690a4a0adaf62ad0697ef61d69R749) already fixed the issue described in #9411
---
- Only apply known video encoder profiles
To avoid passing invalid profiles to ffmpeg.
**Issues**
- https://github.com/jellyfin/jellyfin-androidtv/pull/3933

Fix CodecProfiles and video encoder profiles

---

Emby.Server.Implementations/ApplicationHost.cs
Emby.Server.Implementations/ConfigurationOptions.cs
MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs
MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
tests/Jellyfin.Server.Integration.Tests/JellyfinApplicationFactory.cs

We've received numerous reports from users that Jellyfin is failing to play certain files, and it turns out that many of these issues are due to invalid FFmpeg configurations, such as incorrect installation, stale configuration values, or an unsupported FFmpeg version. The server currently still starts in this situation, leading users to mistakenly believe it's a server bug rather than a configuration error.
This PR makes the server be prevented from starting and print a helper text to help the user fix the installation if the FFmpeg path is not found, not supported, or not executable.
This also removed the internal logic to update the config file's ffmpeg path as we are no longer using that.
For debug purposes that want to run jellyfin without ffmpeg, set the env var …

Prevent server from starting if the ffmpeg path is invalid

---

MediaBrowser.MediaEncoding/Encoder/EncodingUtils.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

The exception will get logged higher up the call stack.

Improve error message when image extraction times out

---

Jellyfin.Api/Controllers/DynamicHlsController.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Some options that are too performance-intensive are disabled, while others are left enabled to trade-off between real-time playback and quality. Now the encoding fps of `libx265` under the veryfast preset is about half that of `libx264` when tonemapping 4k video in software.
**Changes**
- Tune x264/5 encoding params for realtime playback

Tune x264/5 encoding params for realtime playback

---

MediaBrowser.Controller/Entities/BaseItem.cs
tests/Jellyfin.Controller.Tests/Entities/BaseItemTests.cs

**Changes**
Instead of replacing all occurrences of the containing folder name, just check the start of the string. This matches what happens in VideoListResolver.IsEligibleForMultiVersion 
**Issues**
Fixes #12555

Fix alt version name generation

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

This applies software tonemapx filter for dolby vision videos that have no compatability fallback.
Due to the complexity of the reshaping process, this is quite CPU-intensive. For real-time transcoding and tonemapping of 4K 60fps content, a CPU with 16 cores of Zen3-level performance is recommended.
**Changes**
**Issues**
Relies on https://github.com/jellyfin/jellyfin-ffmpeg/pull/447
Fixes #9877

Enable software tonemap for dolby vision

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

**Changes**
- Adapting AMD VAAPI-Vulkan pipeline to FFmpeg 7.0
And keep backward compatibility with jellyfin-ffmpeg6

Adapting AMD VAAPI-Vulkan pipeline to FFmpeg 7.0

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Model/Configuration/EncodingOptions.cs

When using QSV, there was no way to tell it to prioritize a different render device.
This allows passing in the renderNodePath into the device args so it is prioritized correctly.
**Changes**
- Update QSV device args  to use the renderNodePath
**Issues**

Update QSV device args  to use the renderNodePath

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs

**Changes**
- Enable the new BWDIF CUDA deint filter when available (This requires jellyfin-ffmpeg7)
Conflict with #12561

Enable the new BWDIF CUDA deint filter when available

---

.github/workflows/ci-compat.yml

Turns out it was a skill issue and the workflow was running twice.

Only run on pull_request_target, use jellyfin-bot

---

Jellyfin.Server.Implementations/Users/DefaultAuthenticationProvider.cs
MediaBrowser.Model/Cryptography/Constants.cs

It has been a while since this was last updated: https://github.com/jellyfin/jellyfin/pull/6818
Recommendations have changed since: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2

Increase password hash iterations

---

MediaBrowser.Model/Dlna/CodecProfile.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs

Currently, when specifying codec profiles, the client can only specify profiles applied to direct containers, with no way to apply a profile specifically to HLS or a specific HLS container. This limitation is not suitable for more complex client codec support scenarios.
To address this, a SubContainer field is added to CodecProfile. The client can now specify the main container as "hls" to apply the profile exclusively to HLS streams. Additionally, the SubContainer field allows the profile to be applied to a specific HLS container.
Currently, this is only used in StreamBuilder for HLS streams. Further changes may be required to extend its usage.
**Changes**
**Issues**

Add SubContainer support to CodecProfile

---

Jellyfin.Api/Helpers/DynamicHlsHelper.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs
MediaBrowser.Model/Dlna/StreamInfo.cs
MediaBrowser.Model/Entities/MediaStream.cs
MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs

FFmpeg cannot reliably detect the average framerate of certain files and may report an unrealistic 1000fps. However, in many such cases, the RealFrameRate field remains accurate and reflects the actual playback framerate. Add a new ReferenceFrameRate field for use cases where AverageFrameRate is preferred but allows a fallback to RealFrameRate when necessary. This PR has replaced all current usages that rely on AverageFrameRate but also does a fallback with this new field.
**Changes**
**Issues**
A followup of #12602, where some files will be rejected to remux for wrongly detected 1k fps.

Add MediaStream.ReferenceFrameRate for problematic video files

---

Jellyfin.Api/Helpers/DynamicHlsHelper.cs

This is a more correct way to supply Dolby Vision videos with PQ/HLG fallbacks. The `CODECS` is used to describe the base layer and this `SUPPLEMENTAL-CODECS` attribute will be used to describe the enhanced codec. Supported clients will use this field to check if the enhancement layer is available, and this attribute will simply be ignored when the client does not support that field.
One thing to note is that for Dolby Vision videos without a fallback layer, the HLS attributes generated by our current implementation are not entirely correct. If the Dolby Vision video lacks a fallback layer, the `CODECS` attribute should directly describe the Dolby Vision profile, such as `dvh1.05.09`, rather than the HEVC codec profile. However, I'm a bit concerned about compatibility if we decide to make …

Add SUPPLEMENTAL-CODECS for Dolby Vision video with fallbacks

---

MediaBrowser.Model/Entities/MediaStream.cs

Added compatibility for AV1 DoVi Profile 10 based on dolby documentation
**Changes**
Dolby Vision profile 10 detection added for movies and series encoded with AV1 codec with Dolby Vision HDR layer.
Sources : https://professionalsupport.dolby.com/s/article/What-is-Dolby-Vision-Profile
**Issues**
I'm starting to get movies and series encoded in AV1 with DV but I can't see whether or not they are Dolby Vision compatible in the media information.

Add support DoVi Profile 10

---

Jellyfin.Api/Controllers/DynamicHlsController.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Together with #11559 and jellyfin-ffmpeg7, we can enable DoVi Profile 10.
**Changes**
- Enable hardware tone-mapping for DoVi Profile 10
- Add HLS remuxing support for DoVi Profile 10

Enable tone-mapping and HLS remuxing for DoVi Profile 10 in AV1

---

Emby.Server.Implementations/Library/LibraryManager.cs
MediaBrowser.Model/Configuration/MediaPathInfo.cs
MediaBrowser.Model/Configuration/ServerConfiguration.cs

Although removed in 10.9 we forgot to remove some references to the old network path support. This caused the server to still send these paths in specific cases.
**Changes**
- Remove left-over network path references
**Issues**

Remove left-over network path references

---

MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs

**Changes**
- [Use `IMediaEncoder.GetInputArgument`](https://github.com/jellyfin/jellyfin/blob/8c4d23435e6e0206e36e2120029697bb92714ec3/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs#L504) to escape input path, as in [`ExtractTextSubtitle`](https://github.com/jellyfin/jellyfin/blob/b3efae71c0c5b01c762695156aa3bd61a7e8afb9/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs#L647).
- Remove extra quotes from command (https://github.com/jellyfin/jellyfin/pull/10992).
[`inputPath` in `ExtractTextSubtitleInternal`](https://github.com/jellyfin/jellyfin/blob/b3efae71c0c5b01c762695156aa3bd61a7e8afb9/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs#L680) is already [escaped](https://github.com/jellyfin/jellyfin/blob/b3efae71c0c5b01c762695156aa3bd61a7e8afb9/MediaBrowser.MediaEnco …

Fix subtitle and attachment extraction when input path contains quotes

---

Jellyfin.Api/Helpers/StreamingHelpers.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs
MediaBrowser.Model/Dto/MediaSourceInfo.cs
MediaBrowser.Model/LiveTv/TunerHostInfo.cs
src/Jellyfin.LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
src/Jellyfin.LiveTv/TunerHosts/M3UTunerHost.cs

This allows the previously hard-coded compatibility profiles for Live TV to be customizable on a per-tuner basis. Notably:
- Selective enabling of the fMP4 transcoding container to support HEVC and HDR content if the tuner is compatible and will not cause playback issues like A/V out of sync.
- Option to enable or disable HTTP shared streaming (one stream from Jellyfin to the tuner, with multiple clients from Jellyfin). This is useful when the tuner has a stream count limit, but it also caused a lot of playback issues as not all tuners/streams are happy with this.
- User-customizable fallback streaming bitrate. This is particularly helpful when `ffprobe` cannot reliably determine the source stream bitrate, making the client request an excessively high transcoding bitrate that could …

Make Live TV compatibility profiles customizable

---

MediaBrowser.Model/Configuration/LibraryOptions.cs
MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

This adds support for widely used non-standard methods of recording multiple values in audio tags. Notably:
- The non-standard ARTISTS tag used by Kodi and Picard
- The use of a custom character (e.g., `;`) as a delimiter for tag values.
A user-customizable whitelist to exclude certain items from tag splitting is also added, as some artists may have special characters in their names.
Enabling this feature is a per-library setting and is disabled by default.
**Changes**
- Adds customizable tag splitting in library options
**Issues**
Fixes #11871
Fixes #12256
Fixes #10730
Fixes #10794
Fixes #11411

Add non-standard multi-value audio tag support

---

Jellyfin.Server/Migrations/Routines/MoveTrickplayFiles.cs

The auto import generated by IDE used wrong namespace
The CI is expected to fail until rebase on #12607 
**Changes**
**Issues**

Fix trickplay migration

---

src/Jellyfin.Extensions/StringExtensions.cs

**Changes**
After https://github.com/jellyfin/jellyfin/pull/11172, this gives user the ability to finetune the behavior of the existing transliterator to fit their own need. All they need to do is set the `JELLYFIN_TRANSLITERATOR_ID` environment variable to a preferred value, which is explained in [this page](https://unicode-org.github.io/icu/userguide/transforms/general/rules.html#script-transliterators) and [this page](https://unicode-org.github.io/icu/userguide/transforms/general/).
This approach is more flexible than only offers an option to disable the ICU transliterator, users can then:
1. Only transliterate specified curtain languages instead of "Any", for example, use `Hangul-Latin; Hiragana-Latin;` instead of `Any-Latin;` so only Hangul and Hiragana characters will get …

feat(i18n): able to finetune transliterator

---

CONTRIBUTORS.md
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Controller/MediaEncoding/ISubtitleEncoder.cs
MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs

**Changes**
This PR is based off of #12373.
*From the original PR*
This PR adds a method to MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder to get the path of the extracted subtitle. MediaBrowser.Controller.MediaEncoding.EncodingHelper is modified to call this method instead of getting the subtitle directly from the media file itself.
**Issues**
Fixes #11938. If the subtitles are already extracted (by a previous extraction done by a user, or by SubtitleExtract) they will be used. If not, they will be extracted and added to the cache, which will take almost the same time as the previous solution, though it will only need to be done once (this is because `GetReadableFile` already does the extraction automatically).

Use subtitle cache when burning subtitles in

---

Jellyfin.Api/Controllers/MediaInfoController.cs
Jellyfin.Api/Controllers/UniversalAudioController.cs
Jellyfin.Api/Helpers/MediaInfoHelper.cs
Jellyfin.Api/Models/MediaInfoDtos/OpenLiveStreamDto.cs
Jellyfin.Api/Models/MediaInfoDtos/PlaybackInfoDto.cs
MediaBrowser.Model/Dlna/MediaOptions.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs
MediaBrowser.Model/MediaInfo/LiveStreamRequest.cs
MediaBrowser.Model/Session/TranscodeReason.cs

**Changes**
Subtitles often have synchronization issues after video transcoding. This option allows the client to opt-in to always burn in all subtitles, preventing out-of-sync subtitles at the cost of transcoding performance.
To support this feature, the `TranscodeReason` has been extended to accurately determine if a stream can be remuxed.
Notably:
- `VideoCodecTag` now has its own transcode reason instead of sharing one with `VideoCodec`. The former can be fixed by remuxing, while the latter always triggers a full transcode.
- The `VideoReasons` have been updated to check for profile mismatches, as these will also require transcoding.
- `DirectStreamingReasons` now includes the new `VideoCodecTagNotSupported` reason.
**Issues**

Add option to always burn in subtitles if transcoding is triggered

---

Emby.Server.Implementations/MediaEncoder/EncodingManager.cs

Some DVD/Blu-ray extras are just streams of images with 1 chapter for each image

Don't extract chapter images if chapters are <1s long on average

---

MediaBrowser.Providers/Manager/ItemImageProvider.cs
tests/Jellyfin.Providers.Tests/Manager/ItemImageProviderTests.cs

**Changes**
Currently, images in the media folder are being removed during replace all images scan without verifying if they were saved by jellyfin. This PR changes the default behavior to only remove images in the metadata folder, unless the user explicitly enables the option to save metadata with media files.
**Issues**
Fixes #12629

Only remove images in metadata folder by default

---

Emby.Server.Implementations/Library/IgnorePatterns.cs
Emby.Server.Implementations/Library/LibraryManager.cs

The trickplay file folder is now scanned for media after moving to media folder, but those should be ignored.
**Changes**
**Issues**

Don't resolve trickplay folder during media scanning

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Due to precision issue the dar value should be same might not be exactly equal. Lower the precision requirement to allow more subtitles not be padded.
**Changes**
**Issues**

Fix subtitle dar comparison when number not exact

---

Emby.Naming/Video/VideoListResolver.cs
tests/Jellyfin.Naming.Tests/Video/MultiVersionTests.cs

**Changes**
We need to sort by resolution in descending order so that higher resolutions are listed first in the alternate version menu. However, we currently do not consider sorting when the resolutions are the same, leading to unwanted descending order for supplemental titles. This sorts the titles additionally after the resolution, providing a more natural listing.
**Issues**
Closes #12620
Fixes #12618

Sort by version name before resolution sorting

---

MediaBrowser.Controller/Entities/BaseItem.cs
MediaBrowser.Controller/Entities/MediaSourceWidthComparator.cs

Since emby era we are re-ordering all media sources by its width when reading from database. However, that would break the sorting made by the media prober when resolving multiple versions from different files. Only do such sorting when media streams share the same path to respect the filename based sorting done by the multi version resolver.
This should have little to no impact for most cases are most of the files will only have strictly one video stream.
**Changes**
**Issues**
Fixes #12129

Only sort item by width when they have the same path

---

Emby.Server.Implementations/IO/LibraryMonitor.cs

**Changes**
Continue to watch library directories if a subdirectory has invalid permissions.
An error message is printed but the watcher is not stopped so other subdirectories can still be monitored.
Error message:
```
[23:03:24] [ERR] [8] Emby.Server.Implementations.IO.LibraryMonitor: Permission error for Directory watcher: /tmp/jf-test2
System.UnauthorizedAccessException: Access to the path '/tmp/jf-test2' is denied.
---> System.IO.IOException: Permission denied
--- End of inner exception stack trace ---
```
**Issues**
Fixes #7130

Watch library directories with perm errors

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Model/Configuration/EncodingOptions.cs

**Changes**
- Enable HEVC RExt HW decoding for 4:2:2/4:4:4 content
**Issues**
- Fixes https://github.com/jellyfin/jellyfin/issues/12657

Enable HEVC RExt HW decoding for 4:2:2/4:4:4 content

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

**Changes**
- Enable key-frame only decoding for RKMPP trickplay
(https://github.com/jellyfin/jellyfin-ffmpeg/pull/461)
- Also fixed the timestamp passthrough, otherwise `More than 1000 frames duplicated`

Enable key-frame only decoding for RKMPP trickplay

---

MediaBrowser.Providers/BoxSets/BoxSetMetadataService.cs

When updating BoxSets, we don't merge but replace the `LinkedChildren`.
**Changes**
* Actually merge and not replace `LinkedChildren` on BoxSets.
**Issues**
Fixes #12155

Fix metadata merge for BoxSets

---

Jellyfin.Api/Controllers/DynamicHlsController.cs
Jellyfin.Api/Helpers/MediaInfoHelper.cs
MediaBrowser.Controller/MediaEncoding/BaseEncodingJobOptions.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs
MediaBrowser.Model/Dlna/StreamInfo.cs

Previously, we predicted whether the subtitle should be burned in with transcode reasons, but that was not accurate because the actual transcoding codec is only determined after the client has requested the stream. This pass through the option to the `DynamicHlsController` to handle the subtitle burn-in during the actual transcoding process. Now the client should be responsible to conditionally load the subtitle when this option is enabled.
**Changes**
**Issues**

Let HLS Controller decide if subtitle should be burn in

---

Jellyfin.Api/Helpers/StreamingHelpers.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Model/Dlna/ResolutionNormalizer.cs

Previously we don't cap how much we want to scale the bitrate when transcoding to a less efficient codec like h264, resulting in extremely undesired high bitrate from high bitrate original videos, for example 80M AV1 will produce 120M H.264 file which overloads the server encoder, the client decoder and probably also the network. This set a scaling cap at 30Mbit, which means we don't scale up bitrate after 30M anymore, so that the bitrate will not be significantly larger than original if the original video has a high enough bitrate. For videos at such high bitrate the result is hardly noticeable (or not noticeable at all) with our current prefer speed encoding presets.
The previous resolution normalization is also outdated and not well-suited for modern advanced codecs and UHD videos. It …

Better bitrate and resolution normalization

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Fix the diff between requested and actual resolution in RKMPP
- Fix HW decoder may be disabled by Trickplay scanning
- Fix more about 2pass downscaling
**Issues**
- The `force_original_aspect_ratio=decrease` option is enabled by default in `scale_rkrga` filter.
But Trickplay doesn't like this. Switch to using `vpp_rkrga` filter instead.
```
[ERR] [36] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Error creating trickplay images.
System.InvalidOperationException: Image width does not match provided width.
...
```
- If the hardware decoder is not available, it should do nothing instead of unchecking that decoder.

Fix the diff between requested and actual resolution in RKMPP

---

MediaBrowser.Model/Dlna/DeviceProfile.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs

Previously (10.9<=) the id of a device profile was a nullable string. This was changed to a GUID during the 10.10 development but with this change the nullability was removed. A lot of clients (Android TV included) do not set a id so this is was a breaking change. The only 2 usages of the id still accept null so I've made the id nullable to keep compatibility.
**Changes**
- Fix DeviceProfile.Id should be nullable
**Issues**

Fix DeviceProfile.Id should be nullable

---

Jellyfin.Api/Controllers/MediaSegmentsController.cs

Similar to #12681 
**Changes**
- Rename newly added `GetSegmentsAsync` operation to more descriptive `GetItemSegments`
**Issues**

Fix media segment operation name

---

Jellyfin.Api/Controllers/TrickplayController.cs

The method names in controllers are directly used as operation id unless specified otherwise. In 10.10 the name of the `GetTrickplayTileImage` operation was changed to `GetTrickplayTileImageAsync`. While not really a breaking change, it's not a proper operation name as the "async" part has no meaning in the API.
**Changes**
- Fix GetTrickplayTileImage operation name
**Issues**

Fix GetTrickplayTileImage operation name

---

CONTRIBUTORS.md
MediaBrowser.Controller/Entities/BaseItem.cs

The current logic prevents "Playlists" user view from being accessed by a user with allowed tags. It tries to check if the view has the tag and fails as a result.
**Changes**
Avoids checking allowed tags on UserView items. 
**Issues**
Fixes #12685

Allow Playlists access for users with allowed tags configured

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

Quick fix. Ideally, we should probably only escape quotes where value is [quoted](https://github.com/jellyfin/jellyfin/blob/aed00733f88fb9a50fc51816fd05a4438c9d5c42/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L5841-L5851).
**Changes**
Escape quotes in the subtitle path.
**Issues**
N/A
**Tests**
```
.../html"<br>/html"<br>.mp4
.../html"<br>/html"<br>.en.ass
.../html"<br>/html'<br>.mp4
.../html"<br>/html'<br>.en.ass
```

Escape quotes in the subtitle path

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

We need to normalize auto to veryfast instead of convert it so string directly. `auto` is not a valid preset.
In my opinion just using the enum `ToString` failed for all our use cases now and all code path requires extra normalization. I plan to add an extension to have our own `ToString` method to turn this into CLI parameters. But that would break the ABI so not for now.
**Changes**
- Fix software transcoding with auto preset.
**Issues**

Fix libx264/libx265 auto preset

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Fix MJPEG hwenc may be incorrectly enabled on AMDGPU
**Issues**
- AMD GPU has no MJPEG hw encoder

Fix MJPEG hwenc may be incorrectly enabled on AMDGPU

---

MediaBrowser.Model/Configuration/LibraryOptions.cs
MediaBrowser.Model/Extensions/LibraryOptionsExtension.cs
MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

The API requires an array type and does not support runtime generated default value. Use server side helper function to sanitize it into char.
**Changes**
**Issues**

Sanitize CustomTagDelimiters server side

---

Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs

Some users report such behavior is more straightforward and will fit more use cases. In my opinion if this task is intended to be run multiple times it should not move files like its old behavior which moves everything back to metadata.
**Changes**
**Issues**
Fixes #12703

Only move trickplay file should not be saved with media to metadata dir

---

Emby.Server.Implementations/Data/SqliteItemRepository.cs

The current logic for querying items with allowed tags prevents even the user that created the playlist from seeing it.
**Changes**
In addition to allowed tags, expand the where clause to include playlists owned by the current user.
**Issues**
Fixes #12699

Ensure user's own playlists are accessible regardless of allowed tags

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

Current version of ATL will separate some ID3v2.3/2.2 tag fields with its internally defined separator `/`, but this is not desired as we are providing a more customizable separating behavior.  Because the spec of ID3v2.3/2.2 does not have official separator, the separated string will have no ambiguity, which means we can replace the `InternalValueSeparator` back to `/` as a workaround. Ideally we can wait for ATL to add an option to disable such behavior: https://github.com/Zeugma440/atldotnet/issues/281
This also disabled the ATL automatic filename fallback with options instead of checking metadata type, which is a less hacky way to prefer the ffprobe result.
**Changes**
**Issues**

Workaround ATL tag parsing

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Handle full range output in tonemap filter for Trickplay
**Issues**
- The full range output produced by the tonemap filter is more accurate than the scale filter for HDR videos.

Handle full range output in tonemap filter for Trickplay

---

Emby.Server.Implementations/ConfigurationOptions.cs
MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

On low-end CPUs, image extraction can be quite slow because the CPU has to decode and analyze 24 frames to pick the best one. If the input is an HDR image, it also needs to perform tone mapping. On a Raspberry Pi 4 level of performance, this usually means more than 10 seconds per image extracted, and for 4K HDR inputs, it may even timeout. This PR adds a tradeoff mode where the extracted image is the single frame that was picked. Ideally it would come from one of the key frame which is very fast to extract, but if that failed it will fallback to extract the slower normal frame. The frame picked by this mode is worse and less representative, but the process is significantly faster.
Another benefit of this mode is that there is no longer the need to pool and cache lots of frames in the …

Add perf tradeoff mode to image extractor

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Fix full range in SW decoder & HW encoder for Trickplay (previous PR only fixed the HW+HW case)
**Issues**
- If decoding in SW but encoding MJPEG in HW, the full range filter needs to be added manually.

Fix full range in SW decoder & HW encoder for Trickplay

---

Jellyfin.Api/Controllers/DynamicHlsController.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
src/Jellyfin.LiveTv/IO/EncodedRecorder.cs

**Changes**
- Clean up deprecated `-vsync` option
**Issues**
- `-vsync` is deprecated in FFmpeg 5.1 and will be removed in the future.
ref: https://ffmpeg.org/ffmpeg-all.html#toc-Advanced-options

Clean up deprecated -vsync option

---

MediaBrowser.Model/Dlna/StreamBuilder.cs

**Changes**
The refactoring for https://github.com/jellyfin/jellyfin/pull/9374 did not allow for a null inputContainer. When Live TV is the source, the inputContainer will be null until the initial connection happens.

Fix allow inputContainer to be null for Live TV

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

DoVi videos without fallback layers are usually mastered at 4000nit and the default 1000nit extract may result in too bright thumbnail.
**Changes**
**Issues**

Extract DoVi thumbnail at 4000nit

---

Jellyfin.Server/Helpers/StartupHelpers.cs

Environment.GetFolderPath returns an empty string when the SpecialFolder does not yet exists. This causes the locations to be determined relative to the current working directory. By passing the DoNotVerify option the correct path is determined and the parent directories will be created when Directory.CreateDirectory is called.
@Bond-009 ptal.

StartupHelper: fix app paths when SpecialFolder does not yet exists.

---

src/Jellyfin.Networking/Manager/NetworkManager.cs

Added in .NET 5, [this attribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.membernotnullattribute) allows for the compiler to recognize that InitializeLan (and by extension, UpdateSettings) will initialize the specified fields to non-null values.
**Changes**
The `#pragma warning disable` is replaced with the appropriate `MemberNotNull` attributes. If the methods are changed in the future to not initialize the fields, then the compiler will issue a [`CS8774`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#code-doesnt-match-attribute-declaration) error.

NetworkManager: Use MemberNotNull attribute

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

This is mainly for some broken legacy clients that will unlikely to receive proper fix for audio transcoding profile and migrate to our new universal audio controller anytime soon. These legacy clients used an outdated Emby-era audio transcoding pipeline, where the client neither explicitly specifies the desired transcoding formats nor properly indicates the supported audio codecs in its request. Instead, they rely on just providing a container name in the request URL, hoping the server can guess the correct audio codec. However, this guessing is often inaccurate as the container-to-codec mapping has been hard-coded and outdated for six years. When the server cannot guess it will just return "copy" which will obviously fail because the client is requesting transcoding. This PR makes the …

Infer more audio codec from containers

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Fix seeking beyond EOF in HWA transcoding
**Issues**
- Seeking beyond EOF makes no sense in transcoding. Clamp the seekTick value to
[0, RuntimeTicks - 0.5s], so that the muxer gets packets and avoid error codes.

Fix seeking beyond EOF in HWA transcoding

---

MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs

In this way we can use the upstream scale_cuda filter.
**Changes**
- Fix check for format option in scale_cuda filter
**Issues**
- The upstream option description is different from our customized one

Fix check for format option in scale_cuda filter

---

bump_version

**Changes**
Extend the existing `bump_version` script to also update the jellyfin version in the github issue template file so if is no longer necessary to manually update it on every new release.
I tested that the script does behave as expected with the issue template file that contains a space character in its filename.
**Issues**
Context/motivation: https://github.com/jellyfin/jellyfin/pull/12613#pullrequestreview-2288536359

Auto update issue template version on new release

---

CONTRIBUTORS.md
MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs

**Changes**
Makes use of the new TrySetProvider method to safeguard against cases in which the TMDB API returns null for the IMDB ID. 
This should ensure that the rest of the metadata setting proceeds as desired. 
**Issues**
Fixes #12884

Fix TMDB import failing when no IMDB ID is set for a movie

---

CONTRIBUTORS.md
MediaBrowser.Providers/Manager/ItemImageProvider.cs

**Changes**
Don't try to prune images for virtual episodes, since they don't have a containing folder path to look for metadata in. This was causing issues when attempting to refresh a library, series or episode with replace all and replace images enabled.
I also added myself to the contributors file since I've forgotten to do that in previous PRs.
**Issues**
Didn't make one, but it will prevent these kinds of stack traces from stopping a refresh or library scan when it tries to prune images for a virtual episode;
```log
[XX:XX:XX] [ERR] [XX] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
at System.IO.Path.Combine(String path1, String …
```

Don't try to prune images for virtual episodes.

---

MediaBrowser.Model/Dlna/StreamBuilder.cs

This was not set at least since 10.9 and the transcoding behavior is close to "undefined" and in 10.10 this will not work at all. This will make the returned transcoding url from PlayBackInfo to correctly specify the desired transcoding codec. If the client wants to use the HLS controller directly it should be responsible to provide valid container and codec in the parameters.
**Changes**
**Issues**
Fixes #12926 , still requires the client to provide a valid transcoding profile.

Set AudioCodec when building stream

---

Emby.Naming/Common/NamingOptions.cs
tests/Jellyfin.Naming.Tests/TV/EpisodeNumberTests.cs

**Changes**
Add an EpisodeExpression to extract episode number from anime style file names like `[VCB-Studio] Re Zero kara Hajimeru Isekai Seikatsu [21][Ma10p_1080p][x265_flac]` and `[CASO&Sumisora][Oda_Nobuna_no_Yabou][04][BDRIP][1920x1080][x264_AAC][7620E503]`.
**Issues**
fixes issue #9332

Add EpisodeExpression for anime file names

---

Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs
MediaBrowser.Controller/Providers/IProviderManager.cs
MediaBrowser.Providers/Manager/ItemImageProvider.cs
MediaBrowser.Providers/Manager/ProviderManager.cs
tests/Jellyfin.Providers.Tests/Manager/ItemImageProviderTests.cs

**Changes**
Previously, local images provided by DynamicImageResponse were never cleaned up until the server was restarted. This issue has become more severe in 10.10, as the default is now set to use the system's native temp folder, which might be a RAM backed tmpfs. This behavior could lead to resource starvation for long-running servers performing multiple library scans.
Metadata plugins prefer the old behavior should do its own backup.
**Issues**
Fixes #12937

Remove DynamicImageResponse local image after saved to metadata folder

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Some videos have a recorded FPS that is slightly higher than the intended FPS. If this intended FPS is the maximum value requested by the device, it can cause the server to trigger transcoding. However, such minor statistical error do not affect remux playback, add a slight tolerance to enable remux for this case.
**Changes**
**Issues**

Add a small tolerance value to remux fps check

---

src/Jellyfin.Extensions/Json/Converters/JsonDelimitedArrayConverter.cs

The `Utf8JsonWriter.WriteStringValue` method writes the provided string as an element of a JSON array, so we shouldn't manually add delimiters. If we do, the delimiters will be treated as separate array elements.
**Changes**
**Issues**
Fixes #12948

Fix json array string writer in JsonDelimitedArrayConverter

---

MediaBrowser.Model/Extensions/LibraryOptionsExtension.cs

This behavior is explicitly defined in ID3v2.4, but some ID3 taggers seem to apply it to ID3v2.3 as well. Hardcode this as a custom delimiter, as it is primarily used for this purpose; players like VLC also use it to split artist names on ID3v2.3.
**Changes**
**Issues**
Fixes #12957

Always consider null char as delimiter for ID3v2

---

Jellyfin.Api/Controllers/ItemRefreshController.cs

The Refresh API controller did not pass the query parameter from the client to MetadataRefreshOptions and the old trickplay files never got replaced.
**Changes**
**Issues**

Fix trickplay images never being replaced

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

The original implementation required the caller to perform cleanup, but this approach fails when ffmpeg encounters specific issues, such as timing out on slower systems or failing with an error code of -1. In these cases, the temp folder path is not returned, preventing the caller from cleaning it up. While ffmpeg typically doesn't write to this folder when failed, specific errors like a timeout could leave files there.
**Changes**
**Issues**

Always cleanup trickplay temp for ffmpeg failures

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

**Changes**
Those MusicBrainz specific extensions tagged by Picard can store multiple values, and the actual way splitting those values depends on the Picard settings. However, our metadata provider can only have one unique ID, this PR first split the value depends on the library settings, and then pick the first MusicBrainz ID as the provider ID, basically restore the 10.9 and before behavior.
**Issues**
Fixes #13002

Only set first MusicBrainz ID for audio tags

---

Emby.Server.Implementations/ConfigurationOptions.cs
Emby.Server.Implementations/Playlists/PlaylistManager.cs
Jellyfin.Api/Controllers/PlaylistsController.cs
Jellyfin.Server/Migrations/MigrationRunner.cs
Jellyfin.Server/Migrations/Routines/RemoveDuplicatePlaylistChildren.cs
MediaBrowser.Controller/Entities/LinkedChild.cs
MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs
MediaBrowser.Controller/Playlists/IPlaylistManager.cs

There is for sure a cleaner solution than this one.
**Issue:** For some reason the `Id` of `LinkedItem` is different every time they are read.
**Changes**
* Use `LinkedItem.ItemId` instead of `LinkedItem.Id` since the latter seems to be non-static
* Remove `LinkedItem.Id` alltogether
* Calculate new Index on moved item based on accessible items
* Fully remove option for duplicate playlist entries and cleanup duplicates from playlists
**Issues**
Fixes #12892

Fix playlists

---

MediaBrowser.Model/Playlists/PlaylistCreationRequest.cs

@nielsvanvelzen you requested the current behavior but it would change the status quo for existing clients.
**Changes**
Invert public boolean for backwards compatibility on clients that don't currently support this attribute. Currently untested so don't merge this unless it looks correct.
**Issues**
#12835

make playlist creation private by default

---

Emby.Server.Implementations/Library/Resolvers/PlaylistResolver.cs
Jellyfin.Server/Migrations/Routines/RemoveDuplicatePlaylistChildren.cs

We can't update file system sourced playlists because they might be read only.
**Changes**
* Exclude file system based library playlists from migration
* They are `OpenAccess` and have the default GUID as owner ID
**Issues**
#13057
#13048

Exclude file system based library playlists from migration

---

global.json

https://github.com/jellyfin/jellyfin/pull/13038#issuecomment-2481505391
We avoided updating global.json in the past for exactly this reason but attempted to fix codeql ci issues.

Downgrade minimum sdk version

---

Jellyfin.Server.Implementations/MediaSegments/MediaSegmentManager.cs
MediaBrowser.Model/Configuration/LibraryOptions.cs

This option is not implemented in any of our clients in 10.10 so no migrations required. By default this value is empty which basically means no-op.
**Changes**
- Fix typo in LibraryOptions
- `MediaSegmentProvideOrder` -> `MediaSegmentProviderOrder`
**Issues**

Fix typo in LibraryOptions

---

Jellyfin.Api/Controllers/LiveTvController.cs

**Changes**
Changes the word "guid" to "guide" in the API documentation for GetGuideInfo: https://api.jellyfin.org/#tag/LiveTv/operation/GetGuideInfo

Fix typo in guide info endpoint comment

---

Jellyfin.Api/Controllers/DynamicHlsController.cs

In 10.10 clients that can only play the fallback layer like the Samsung TVs will report `DOVIWithHDR10` as supported video range, but the server should not do remux in DoVi as the client can only play the fallback layer. This changes the server to only do DoVi remux when the client can play DoVi videos without a fallback layer.
**Changes**
**Issues**
Forum report: https://forum.jellyfin.org/t-issue-with-playback-of-hevc-files-in-jellyfin-dolby-vision-tag-misconfiguration?pid=43992

Only do DoVi remux when the client supports profiles without fallbacks

---

Jellyfin.Api/Helpers/StreamingHelpers.cs

When the stream is bitrate limited, and we’re not directly coping the audio stream, we should use the first supported lossy codec reported by the client to apply the bitrate to the encoder instead of transcoding using the lossless encoder without bitrate limit.
**Changes**
**Issues**
Fixes #13126

Fallback to lossy audio codec for bitrate limit

---

Jellyfin.Api/Helpers/StreamingHelpers.cs

This would break transcoding for videos without an audio track as the codec checking would be null referencing
**Changes**
**Issues**

Check if the video has an audio track before codec fallback

---

MediaBrowser.Providers/Manager/ProviderManager.cs

**Changes**
Added logic to determine the TV image type based on the file extension if the Content-Type header is null or empty.
**Issues**
Fixes #13075 #11703 #11824

Determine tv image type by extension if content-type is unavailable

---

src/Jellyfin.Networking/Manager/NetworkManager.cs

We cannot simply use the subnet list to check if the IP is in LAN as it does not handle special cases like IPv4MappedToIPv6 and IPv6 loopback addresses.
**Changes**
**Issues**
Fixes #13054

Properly check LAN IP in HasRemoteAccess

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

**Changes**
The intention behind using ffprobe as a fallback for the ATL library was to obtain information when ATL failed due to errors, hoping that ffprobe would be more robust. However, for multi-value tags, the old ffprobe normalizer still incorporates a lot of Emby-era logic. Such logic includes multi-level fallbacks and splits tags using delimiters that are not user-customizable. For instance, the normalizer might prefer the ARTISTS tag even if the user has disabled it in the library settings, or use delimiters that the user has excluded. If ATL fails to retrieve any data for those multi-value fields, the tag should be considered empty to avoid wrong data be filled.
**Issues**
Fixes #12981

Don't fall back to ffprobe results for multi-value audio tags

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Our custom parameters are slower than the ultrafast preset, but users would expect encoding to be as fast as possible when selecting ultrafast. Only apply those parameters to superfast and slower presets.
**Changes**
**Issues**

Don't use custom params on ultrafast x265 preset

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Enable software tone-mapping by default
(Web https://github.com/jellyfin/jellyfin-web/pull/6362)
**Issues**
- Transcoding HDR video without tonemapping results in an unacceptable viewing experience.
Many users are not even aware of the option and therefore we should always enable the software tonemapx filter.

Always do tone-mapping for HDR transcoding when software pipeline is used

---

src/Jellyfin.LiveTv/Guide/GuideManager.cs
src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs

**Changes**
* Only return cachable images to the `ListingManager` so we don't save any image URLs with API key in the database
* Run pre-caching on all existing programs, not only updated/new ones
**Issues**
Fixes #13147
**ToDo**
* Potentially write migration to remove all existing images referencing schedules direct, otherwise it will take 12 days for them to be removed from the database and the issue to be actually fixed.
**Note**
This is a workaround since the proper fix would require quite some database changes which we currently can't do in a point release due to the ongoing EFCore migration. The proper fix would entail something along these lines:
* Extend `ItemImageInfo` with new fields `ProviderName` and `RequiresToken`
* Write migration for existing data
* Add interface for …

Fix EPG image caching

---

MediaBrowser.XbmcMetadata/Parsers/MovieNfoParser.cs
MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs

For some reason we assume that the `id` tag of an NFO always includes the TVDB id for series and IMDB id for movies.
According to the [Kodi Wiki](https://kodi.wiki/view/NFO_files/Movies) this is false. The `id` tag usually includes the value of the `uniqueId` tag which is set as `default`. This can be any kind of provider ID.
**Changes**
* Do not assume the extracted id is associated to a specific provider
* Only use the extracted ID if we're somewhat sure it is for a specific provider
**Issues**
* Id extracted from unreliable `id` tag overrides correct id extracted from `uniqueId` tag

Fix NFO ID parsing

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs

`DTS` should usually have codec name `dts` and encoder `dca`. We're currently only adding `dca` to the codec list which prevents remuxing of DTS when streaming via fMP4.
**Changes**
* Replace `dca` with `dts` in supported HLS audio codecs and shift logic

Fix DTS in HLS

---

MediaBrowser.Model/Dlna/StreamBuilder.cs
MediaBrowser.Model/Dlna/TranscodingProfile.cs

Some clients may have specific requirements for audio codec support. For instance, WebOS only supports flac in stereo, while Safari only supports opus in stereo. When attempting to check the validity for remuxing fails for such clients, we should instead fallback to alternative codecs that support other transcoding conditions, instead of forcing a downmix in the source codec.
If this change is considered too much for a bug fix release, I will rebase this to target master.
**Changes**
**Issues**

Transcode to audio codec satisfied other conditions when copy check failed.

---

Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs

Trickplay images should not be generated for backdrops as backdrops are not seekable at all.
**Changes**
**Issues**
Fixes #13099

Don't generate trickplay for backdrops

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

It seems like RKRGA is expecting no zero padding bits during 2 pass scaling which distorts P010 frames after scale. This breaks trickplay image generation for HDR videos. Workaround this by specifying nv15 frame format.
This might cause issues with other ffmpeg implementations, as NV15 is not supported everywhere. However, rockchip users should use jellyfin-ffmpeg for proper hardware acceleration anyway.
**Changes**
**Issues**
Fixes this:

Use nv15 as intermediate format for 2-pass rkrga scaling

---

Jellyfin.Api/Controllers/SubtitleController.cs
Jellyfin.Api/Helpers/DynamicHlsHelper.cs
Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
MediaBrowser.Model/Dlna/StreamInfo.cs

See #13306 and [this gist](https://gist.github.com/nielsvanvelzen/ea047d9028f676185832e51ffaf12a6f) for context.
**Changes**
- Use `ApiKey` instead of `api_key` in all URL's returned by the server to clients. Ideally we wouldn't include an API key at all and require the client to set the Authorization header but that's a breaking change for another time.
**Issues**

Prefer ApiKey over api_key in generated URL's

---

Jellyfin.Server.Implementations/Security/AuthorizationContext.cs
MediaBrowser.Model/Configuration/ServerConfiguration.cs

**Changes**
Adds a new `EnableLegacyAuthorization` configuration option to `system.xml`. It defaults to `true` (keep legacy methods working) but we will add a migration to change it to `false` in the future before entirely removing the old authorization methods.
For now the option can be used by (client-)developers to find network requests using a wrong authorization method.
The only method we'll allow is the `Authorization` header with `MediaBrowser` scheme and the `ApiKey` query parameter. The other headers (`X-Emby-Authorization`, `X-Emby-Token`, `X-MediaBrowser-Token`), query parameter (`api_key`) and authorization scheme (`Emby`) are all deprecated.
We've warned for these changes for almost 2 years using [this gist](https://gist.github.com/nielsvanvelzen/ea047d9028f676185832e51ffaf12a …

Add option to disable deprecated legacy authorization options

---

src/Jellyfin.LiveTv/Listings/XmlTvListingsProvider.cs

**Changes**
Added support for handling .gzip compressed XML files in addition to .gz files. Updated the GetXml method to follow URL redirections and use the final redirected URL for processing.
**Issues**
Fixes #13249 & #12413

Fix .gzip handling and URL redirection for XML TV guide parsing

---

CONTRIBUTORS.md
MediaBrowser.Model/Extensions/ContainerHelper.cs

**Changes**
Applied the following to each `ContainsContainer` method documentation of the `ContainerHelper` class:
- added a sentence which states that all `inputContainer` values will be accepted in case `profileContainers` has a value of null or empty. 
Also added myself to the contributors list 😄 
**Issues**
addresses https://github.com/jellyfin/jellyfin/issues/13357

improve documentation for ContainerHelper class

---

Emby.Server.Implementations/IO/ManagedFileSystem.cs

Our `GetFileSystemEntries` method will throw when enumerating the file system, but its callers might consider the unhandled exceptions as the whole path is not available. This would cause a single problematic file to fail the enumeration, and could lead to unexpected side effects.
HandleIOException gracefully by marking the files throwing as not exist to let the caller skip that file.
Note that the dotnet's method `EnumerateFileSystemInfos` may also throw and failed to build the file list. We can do little in this case. See #13093 for more info for this kind of issue.
**Changes**
**Issues**
Fixes #13389

Catch IOExceptions for GetFileSystemMetadata

---

MediaBrowser.Providers/Manager/ImageSaver.cs

When writing an image to the disk, we use the completion of the async task as a signal indicating the completion of a write operation. However, this approach may not be entirely accurate, as the operating system can optimize IO operations by writing data to an intermediate cache instead of directly to the disk before completing the operation. This optimization can lead to a data race for our scanner, as subsequent tasks such as blurhash computation may attempt to read a file that has not yet been flushed from the volatile cache. Consequently, the data within the file becomes invalid, causing the blurhash computation task to fail.
Use WriteThrough mode to ensure the data is actual on disk before return to resolve this issue.
**Changes**
**Issues**
Fixes #3687
If …

Use WriteThrough for ImageSaver

---

MediaBrowser.Model/Dlna/StreamBuilder.cs

Stream copy cannot be guaranteed when bitrate limit is exceeded, and the actual transcoding or copy is at best effort. The explicit selection may result in a wrong fallback codec being picked up when a transcode has to happen.
**Changes**
**Issues**
Fixes #13416
Though I don't understand the reason why mp3 cannot be played on Android TV as the stream looks normal. This PR will make the fallback to pick AAC which should be played fine as verified by user.

Don't select audio stream and codec explicitly for copy when bitrate exceeds limit

---

Emby.Naming/TV/SeriesResolver.cs
Jellyfin.Api/Controllers/AudioController.cs
Jellyfin.Api/Helpers/StreamingHelpers.cs
Jellyfin.Data/Entities/BaseItemMetadataField.cs
Jellyfin.Data/Entities/BaseItemTrailerType.cs
Jellyfin.Data/Entities/ItemValue.cs
Jellyfin.Data/Entities/PeopleBaseItemMap.cs
Jellyfin.Server.Implementations/Item/BaseItemRepository.cs
MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Controller/Session/ISessionManager.cs
MediaBrowser.Controller/Session/SessionInfo.cs
MediaBrowser.LocalMetadata/Savers/BaseXmlSaver.cs
MediaBrowser.Model/Dto/SessionInfoDto.cs
MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
src/Jellyfin.Drawing.Skia/SplashscreenBuilder.cs
src/Jellyfin.LiveTv/Listings/SchedulesDirectDtos/LineupDto.cs
src/Jellyfin.LiveTv/Listings/SchedulesDirectDtos/MetadataDto.cs
src/Jellyfin.LiveTv/TunerHosts/M3uParser.cs

**Changes**
Fixes misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/jellyfin/actions/runs/12979401882#summary-36195047679
The action will report that the changes in this PR would make it happy: https://github.com/jsoref/jellyfin/actions/runs/12979402012#summary-36195047936 -- Note that there are a number of tests that appear to be consistently failing. In order to get CI not not fail miserably, I included 0c236225278edacc5f9c93467d628ced8a960660 in my test PR (but they aren't included in this PR).
---
As before, if people are happy with the changes, I'll squash them.
There's one change that I omitted which was `BluRay` to `Bluray` (for everything except file names) …

Fix spelling

---

.github/workflows/ci-tests.yml

**Changes**
Let each platform's CI run to completion (or failure) independently.
**Issues**
- This makes it easier to see that multiple platforms are unhappy in #13445

chore(ci): Let CI fail independently on each platform

---

Jellyfin.Data/Entities/BaseItemEntity.cs
Jellyfin.Server.Implementations/Item/BaseItemRepository.cs
Jellyfin.Server.Implementations/Migrations/20250204092455_MakeStartEndDateNullable.Designer.cs
Jellyfin.Server.Implementations/Migrations/20250204092455_MakeStartEndDateNullable.cs

These dates are used as birth date and death date for person (ask Luke for why) and a non-nullable column would cause the null date become 1901-01-01, making all living people dead.
**Changes**
**Issues**
Fixes #13157

Make StartDate/EndDate nullable

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

Although the number type is nullable from the type definition of ATL, the lib might still normalize all unknown values to 0 which makes doing null check only not enough. Fallback to ffprobe results when the number is 0 as well.
**Changes**
**Issues**
Fixes #13484 without upstream changes so that the limited tags are falling back to ffprobe results. The complete fix is awaiting upstream release.

Correctly handle audio number tag fallbacks

---

src/Jellyfin.LiveTv/Guide/GuideManager.cs

If the guide data changes any other image, the Backdrop image would not be updated.
This error was unintentionally introduced in PR https://github.com/jellyfin/jellyfin/pull/13227 [here](https://github.com/jellyfin/jellyfin/pull/13227/files#diff-68cbfbf495bc9462524e5e837822194c426c5008491dfccdbc8773ef784aea50R682)
Replace the short-circuiting || operator with a normal | OR operator to ensure that the call for UpdateImage for the Backdrop image still happens even if other images were also updated.
```csharp
// Backdrop
return updated || UpdateImage(ImageType.Backdrop, item, info);
```
Fixes https://github.com/jellyfin/jellyfin/issues/13496

Fix LiveTV Guide Backdrop image not updating

---

src/Jellyfin.LiveTv/Guide/GuideManager.cs

**Changes**
* Only pre-cache images for new and updated programs.
* Fix `forceUpdate` calculation to always fetch images if necessary
**Issues**
* Currently we are hammering the SD API because we always re-fetch all images.
As always, I do not use any kind of LiveTV, so someone else needs to test this.

Fix SchedulesDirect image prefetching

---

MediaBrowser.Controller/Channels/Channel.cs
MediaBrowser.Controller/Entities/BaseItem.cs
MediaBrowser.Controller/Entities/CollectionFolder.cs
MediaBrowser.Controller/Entities/Folder.cs
MediaBrowser.Controller/Entities/Movies/BoxSet.cs
MediaBrowser.Controller/Playlists/Playlist.cs

The current logic is described in [this comment](https://github.com/jellyfin/jellyfin/issues/11869#issuecomment-2332871326). In short, the allowed tags check traverses the hierarchy of an item and checks all parents. This is usually desirable for blocked tags since an item shouldn't be visible if it or any of its parents are blocked. However, similar logic makes it cumbersome/impractical to use allowed tags because they would have to be applied to all parents of an item in addition to the item.
**Changes**
The changes skip checking allowed tags on parents of an item. The item itself is still checked. No changes are made to blocked tags or parental ratings logic.
**Issues**
Fixes #11869

Skip allowed tags check for parents of an item

---

Emby.Server.Implementations/Library/LibraryManager.cs
MediaBrowser.Controller/Entities/Folder.cs
MediaBrowser.Controller/Library/ILibraryManager.cs

Reverts the name change of this function made in the EFCore PR. This hopefully reduces the amount of merge conflicts while backporting and makes it consistent with the CreateItem function.

Rename CreateOrUpdateItems back to CreateItems

---

Jellyfin.Server.Implementations/Item/PeopleRepository.cs

The search for people is currently case-sensitive (#13510).
**Changes**
The SQL query has been modified to make the search case-insensitive.
**Issues**
Fixes #13510

Fix Search results are case-sensitive for people

---

src/Jellyfin.Networking/Manager/NetworkManager.cs

We are still using `Subnet.Contains` a lot but that does not handle IPv4 mapped to IPv6 addresses at all. It was partially fixed by #12094 in local network checking, but it may not always happen on LAN.
Also make all local network checking to use IsInLocalNetwork method instead of just performing `Subnet.Contains` which is not accurate.
Filter out all link-local addresses for external interface matching.
**Changes**
**Issues**

Fix subnet contains check

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
src/Jellyfin.Drawing/ImageProcessor.cs

The current FFmpeg image extractor is configured to use a resource pool size that always equals 2 times the number of CPU cores, which is somewhat excessive. Make the default equal to the core count instead of twice, and respect the `ParallelImageEncodingLimit` option.
**Changes**
**Issues**
Fixes #13531

Fix image encoding concurrency limit

---

Jellyfin.Server.Implementations/Item/BaseItemRepository.cs

We currently don't write the columns that do not exist on the BaseItem class definition in db. However, columns like `CleanName` is still useful and being used by internal queries and current behavior would cause such query to return nothing.
The only exception is the UserDataKey which is not even being used for internal query that can be omitted.
Alternatively we can dynamically compute those columns use the correcponsfing method every time during query so that we don't need those columns to be written. I'm not sure which approach is better, but for this PR I choose to match the old behavior.
**Changes**
**Issues**
Fixes #13541

Write only for query columns to EFCore db

---

Jellyfin.Data/Entities/BaseItemEntity.cs
Jellyfin.Server.Implementations/Item/BaseItemRepository.cs
Jellyfin.Server.Implementations/Migrations/20250214031148_ChannelIdGuid.Designer.cs
Jellyfin.Server.Implementations/Migrations/20250214031148_ChannelIdGuid.cs
Jellyfin.Server/Migrations/Routines/MigrateLibraryDb.cs

Part of https://github.com/jellyfin/jellyfin/issues/13047
Fixes: https://github.com/jellyfin/jellyfin/issues/13164
BaseItem.ChannelId has been a Guid since Jellyfin's inception, should be safe to change the db model to reflect that.

Change BaseItemEntity ChannelId to nullable Guid

---

Jellyfin.Server.Implementations/Migrations/.gitattributes

From https://jkdev.me/handling-ef-core-migrations/
This disallows incremental updates in git, so developers will be forced to fully regenerate the migration if upstream has changed

Disallow incremental updates to JellyfinDbModelSnapshot

---

MediaBrowser.Controller/Entities/Folder.cs

**Changes**
Filtering 4K does not work when Group Movies into Collections is enabled because the box set needs to be collapsed. This change adds a check for the `Is4K` property to ensure that 4K filtering functions correctly when collections are enabled in a library.
**Issues**
Reported in comments: 
https://github.com/jellyfin/jellyfin/issues/13413#issuecomment-2611456177

Fix 4K filtering when grouping movies into collections

---

Emby.Server.Implementations/Library/LibraryManager.cs

This seems like a simple and safe (small) win.
Automatically invalidating cache entries after a while would be even better (or not having a cache at all) but such changes are too big for a point release IMO.

Delete children from cache on parent delete

---

Emby.Server.Implementations/Collections/CollectionManager.cs

Emit the not-found Id in the exception for easier diagnosis
**Changes**
Add the ID guid to the thrown exception
**Issues**
N/A (useful when debugging something else)

Better exception message when folders or folder items are missing

---

MediaBrowser.Providers/Manager/MetadataService.cs
tests/Jellyfin.Providers.Tests/Manager/MetadataServiceTests.cs

When a update-metadata is processed and the information from one provider gives a full date (e.g. 2025-02-20) and another provider gives only the year (e.g. 2025-01-01), don't overwrite the date unless it's currently a year-only.
This comes up when (for example) The Audio DB has only the year, but MusicBrainz has a full date for the release date. With this change prefer the full date.
**Changes**
Add a test for IsYearOnlyDate, and use that in MetadataService.MergeBaseItemData to ensure we don't replace more-specific dates with less-specific ones.
**Issues**
Fixes #13596

Fix overwrite of PremierDate with a year-only value

---

Jellyfin.Server.Implementations/JellyfinDbContext.cs

The RETURNING clause helps with performance and is now default of EFCore. However, EFCore cannot automatically perform retry when the table was locked/busy. Disable it as a workaround for the locking issues of very huge databases.
**Changes**
**Issues**
Fixes #13234
I'm not confident that this would work 100% though, need the user to verify that.

Don't use RETURNING clause with EFCore

---

Emby.Server.Implementations/Playlists/PlaylistManager.cs

**Changes**
If item is not found, `item.ItemId` would trigger a NullReferenceException. Log `entryId` from the function arguments instead.
**Issues**

Fix possible NullReferenceException in playlist warning

---

Emby.Server.Implementations/Localization/LocalizationManager.cs
tests/Jellyfin.Server.Implementations.Tests/Localization/LocalizationManagerTests.cs

Add support for `"Rated:"` and also trim blanks.
Updated unit tests.

Support more rating formats

---

Jellyfin.Server/Migrations/Routines/MigrateLibraryDb.cs

**Changes**
Include `SortName` in LibraryDb migration so sort title is respected after migration.
**Issues**
Fixes #13642

Include SortName in LibraryDb migration query

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

The setter of the `Track` class is not intended for such use cases and will have unwanted side effects to change valid values. We should never use it and use all fields from `ATL.Track` class read-only.
**Changes**
**Issues**
Fixes #13692

Clone fallback audio tags instead of use ATL.Track.set

---

Jellyfin.Api/Controllers/LiveTvController.cs

Targeting master as this parameter also didn't exist in any earlier JF version AFAIK.
Fixes #13681

Add start index to /Programs/Recommended endpoint

---

Emby.Server.Implementations/Library/LibraryManager.cs
Emby.Server.Implementations/TV/TVSeriesManager.cs
Jellyfin.Api/Controllers/TvShowsController.cs
Jellyfin.Server.Implementations/Item/BaseItemRepository.cs
MediaBrowser.Controller/Library/ILibraryManager.cs
MediaBrowser.Controller/Persistence/IItemRepository.cs
MediaBrowser.Model/Querying/NextUpQuery.cs

Part of https://github.com/jellyfin/jellyfin/issues/13047
Alternate to https://github.com/jellyfin/jellyfin/pull/13679
This change makes the next up call take ~1.5s (0.1s in get series keys)
It's possible that this query is missing some of the functionality but it returns the correct set of next up series for the account I tested with

Add fast-path to getting just the SeriesPresentationUniqueKey for NextUp

---

Emby.Server.Implementations/Library/MediaStreamSelector.cs

Changes:
This PR addresses an issue where forced subtitles in non-preferred languages were being selected. I adjusted the subtitle selection logic for the SubtitlePlaybackMode "Smart" and "OnlyForced" to ensure that forced subtitles are only chosen if they match the user's preferred language.
Issues:
Fixes one of two issues mentioned in #10829
Fixes #11776

Fix subtitle selection to respect preferred language for forced subtitles

---

MediaBrowser.Providers/Movies/ImdbExternalUrlProvider.cs

**Changes**
Updated the IMDb external URL provider to correctly handle both media (movies, series, etc.) and person URLs. The URL generation now uses :
baseURL + name/{externalId} for people 
baseURL + title/{externalId} for all other types
**Issues**
Regression from #13175

Fix IMDb URL for People

---

MediaBrowser.Providers/Manager/MetadataService.cs

**Changes**
Fix regression from #13618 where it doesn't handle cast having multiple roles, as this it give the values from the first occurrence to everything else, and as null values are valid for sortOrder it overwrites the sortOrder of those roles which shouldn't have any.
This is done by grouping the target by name and then looping through the name groupings. 
**Issues**

Fix regression where "Search for missing metadata" not handling cast having multiple roles

---

Emby.Server.Implementations/Library/MediaSourceManager.cs
Emby.Server.Implementations/Session/SessionManager.cs

This PR solves an issue where the OnPlaybackStopped task inside the SessionManager errors out as described in Issue #13225.
Changes:
This is done by adding a try-catch-block around the problematic function call. This should not result in any other issues when the task runs without this call succeeding. 
Issues:
Fixes #13225

Fix OnPlaybackStopped task erroring out when closing a browser tab with a livestream that is transcoding

---

Emby.Server.Implementations/Data/CleanDatabaseScheduledTask.cs
Emby.Server.Implementations/Library/LibraryManager.cs
Emby.Server.Implementations/Library/PathManager.cs
Jellyfin.Server.Implementations/Item/BaseItemRepository.cs
Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
MediaBrowser.Controller/IO/IPathManager.cs

**Changes**
* Cleanup additional DB tables on item removal
**Issues**
* Images and subtitles can't reliably be cleaned up because their save folder depends on the media files's modifcaition date
**Still not cleaned up**
- keyframe JSONs
- subtitles (we are not able to clean them up because the path depends on the modification date of the already not existing media file...)
- attachments

Remove all DB data on item removal, delete internal trickplay files

---

tests/Jellyfin.Server.Integration.Tests/Controllers/UserLibraryControllerTests.cs

Disabled tests for beeing flaky after the EFCore factor.
Needs to be fixed when somebody finds the reason they usually only fail on the pipeline

Disabled flaky tests

---

Emby.Server.Implementations/IO/ManagedFileSystem.cs
MediaBrowser.Model/IO/IFileSystem.cs

**Changes**
Add new override to provide `searchPattern` for GetFiles call. This will allow to perform more optimized searches using prefix matches

Add ability to provide search pattern to GetFiles

---

MediaBrowser.Model/Dlna/StreamBuilder.cs

This is kind of a start point for https://github.com/jellyfin/jellyfin/pull/10756
Later, we can properly [filter the direct audio stream](https://github.com/jellyfin/jellyfin/blob/38f80edc8011783d6544a9c1bd6401e3fe13ff57/MediaBrowser.Model/Dlna/StreamBuilder.cs#L967-L977):
```cs
var directAudioStream = candidateAudioStreams.FirstOrDefault(stream => ContainerHelper.ContainsContainer(audioCodecs, false, stream.Codec)
&& (transcodingProfile is null || GetCompatibilityAudioCodec(playlistItem.MediaSource!, container!, stream, options.Profile, true, false) == 0));
```
**Changes**
Extract container, video and audio compatibility checks.
**Issues**
N/A

Extract container, video and audio compatibility checks

---

Emby.Server.Implementations/Localization/iso6392.txt
tests/Jellyfin.Server.Implementations.Tests/Localization/LocalizationManagerTests.cs

Now the ISO 639-2/T (terminological) comes first (which is the same as the ISO 639-3 code) and the second column is for the ISO 639-2/B (bibliograpihc) code.
The terminological code is derived from the native name for the language while the bibliographic code is more of a "legacy feature" (see https://en.wikipedia.org/wiki/ISO_639-2#B_and_T_codes) where the code is derived from the English name for the language.
The format of the file is now
``ISO 639-2/T (or ISO 639-3) | ISO 639-2/B (where applicable) | ISO 639-1 (two-letter code) | English name | French name``
**Changes**
There are no functional changes, but the unit test for the German language needed to be changed.

Change the order of the iso6392.txt file

---

Emby.Server.Implementations/Library/LibraryManager.cs
Emby.Server.Implementations/Library/UserViewManager.cs
Jellyfin.Server.Implementations/Item/BaseItemRepository.cs
MediaBrowser.Controller/Library/ILibraryManager.cs
MediaBrowser.Controller/Persistence/IItemRepository.cs

**Changes**
Adds an extra function to the SqliteItemRepository to do a sub query to get the top N number of unique series/albums names sorted by datecreated. The min value of the datecreated from the subquery is then used to retrieve the rows for use for the /item/latest api. 
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/10993
Fixes https://github.com/jellyfin/jellyfin/issues/1880

Fix only returning one item from /Item/Latest api.

---

Emby.Server.Implementations/Session/SessionManager.cs
MediaBrowser.Controller/Session/ISessionManager.cs
MediaBrowser.MediaEncoding/Transcoding/TranscodeManager.cs

This PR solves an issue where the consumer count is off by one when closing a browser tab with a livestream that is transcoding as described in Issue #13219. The task "CloseLivestream" is called twice in this case.
I resolved this issue by modifying the if-statement in the "CloseIfNeededAsync" task that determines if the "CloseLivestream" task is run or not. In my updated version it is not run if the livestream is transcoded, which resolves the aforementioned issue.
The consumer ount is then reduced by one when PlaybackStopped is reported, which is the expected behavior that is also seen by quitting the stream via the back button instead of closing the browser tab.
Issues:
Fixes #13219 
Fixes #13721 
Fixes #13684

Fix consumer count off by one when closing a browser tab with a livestream that is transcoding

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Fix validation of VAAPI/QSV render node path
**Issues**
- Check whether the device file is available before using it with FFmpeg

Fix validation of VAAPI/QSV render node path

---

Jellyfin.Server.Implementations/Item/BaseItemRepository.cs
Jellyfin.Server.Implementations/Item/OrderMapper.cs
tests/Jellyfin.Server.Implementations.Tests/Item/OrderMapperTests.cs

**Changes**
Broke out sort order mapping into a static testable file.
Added default behavior for when sorting is used on a null Premier Date.
Added unit tests for the Sort Order case of Premier Date.
**Issues**
Fixes #12101

Fix Sort by Year Bug (#12101)

---

MediaBrowser.Controller/Entities/BaseItem.cs
MediaBrowser.Controller/Entities/TV/Season.cs
MediaBrowser.Controller/Entities/TV/Series.cs

Currently, the IChannel interface can deliver channel result folders which are interpreted as series and seasons. However, Jellyfin does not query for the contents of these folders when viewing said serie of season. This results in empty series in the API.
The parsing of series and seasons is implemented in the [ChannelManager](https://github.com/jellyfin/jellyfin/blob/v10.10.3/src/Jellyfin.LiveTv/Channels/ChannelManager.cs#L973). The `IChannel` implementation is never queried for the contents of said series and seasons.
Looking at the implementation of channel [Folders](https://github.com/jellyfin/jellyfin/blob/v10.10.3/MediaBrowser.Controller/Entities/Folder.cs#L951), this implementation for series and seasons seems to fit in the structure of Jellyfin and works with my testing. …

Add channel queries to series

---

src/Jellyfin.Drawing.Skia/SkiaEncoder.cs
src/Jellyfin.Drawing.Skia/StripCollageBuilder.cs

Our previous approach didn’t work with some complex library names, even when the required fonts were present, because the font handling logic was too simplistic. Modern Unicode and the fonts have become quite complex, making it challenging to implement it correctly. This improved implementation still isn’t the most correct way, but it’s better than it used to be. It now falls back to multiple fonts to find the best one and also handles extended grapheme clusters that were incorrectly processed before.
**Changes**
**Issues**
Fixes #10848
Fixes #13281

Improve SkiaEncoder's font handling

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
MediaBrowser.MediaEncoding/Encoder/ApplePlatformHelper.cs
MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

This decoder differs from others provided by VideoToolbox in that it lacks any software fallback. To achieve consistent behavior with other VideoToolbox decoders, this PR implemented additional checking on the server to simulate the software fallback provided by VideoToolbox.
The current fallback checking mechanism is a temporary solution. In the long term, it should be replaced with a more capable hardware capability checking system.
**Changes**
**Issues**
Required ffmpeg change is already backported here: https://github.com/jellyfin/jellyfin-ffmpeg/pull/500
The upstream has not released tagged version with VideoToolbox AV1 yet. Jellyfin-ffmpeg is required for now.

Enable VideoToolbox AV1 decode

---

Jellyfin.Server/Migrations/MigrationRunner.cs
Jellyfin.Server/Migrations/Routines/MoveTrickplayFiles.cs
Jellyfin.Server/Migrations/Routines/RemoveDuplicatePlaylistChildren.cs

**Changes**
Run `MoveTrickplayFiles` after the EFcore migration, otherwise no data is fetched.
Fixes #13801

Fix MoveTrickplayFiles migration

---

MediaBrowser.Model/Dto/BaseItemDto.cs
MediaBrowser.Model/Dto/BaseItemPerson.cs
MediaBrowser.Model/Entities/MediaStream.cs
MediaBrowser.Model/MediaSegments/MediaSegmentDto.cs
MediaBrowser.Model/Search/SearchHint.cs

Enums in response model with no nullability or default value will make the API very fragile as each extension to the enum will break the API for some clients, but a lot of enums actually do have an unknown value which should be used as a default. This set all model properties that are non-nullable using an enum that has an Unknown member in 10.10, except MediaStream.VideoRangeType which is refactored in #13277
**Changes**
**Issues**

Explicitly set default value for enums used in API models

---

src/Jellyfin.Drawing.Skia/SkiaEncoder.cs
src/Jellyfin.Drawing.Skia/StripCollageBuilder.cs

Includes the warnings fixes from #5360 
* The resizing process involved multiple SKImage to SKBitmap conversions. Reduced those conversions and using the native methods that Skia provides for drawing each Canvas
* Use High quality filter on all the canvas.

Reduce Skia conversions

---

Jellyfin.Api/Controllers/BrandingController.cs
Jellyfin.Api/Controllers/ConfigurationController.cs
Jellyfin.Server/Filters/AdditionalModelFilter.cs
MediaBrowser.Model/Branding/BrandOptionsDto.cs
MediaBrowser.Model/Branding/BrandingOptionsDto.cs

Changes
This PR adds handling for BrandingOptions to preserve SplashscreenLocation when updating configuration.
_sorry accidentally closed the last_
Moved logic from to the ConfigurationController to BaseConfigurationManager.cs and now target master
Issues
Fixes: #13744

Preserve SplashscreenLocation when updating branding config

---

Jellyfin.Api/Controllers/ImageController.cs

**Changes**
allows admins to see Splashscreen even when disabled
background:
https://github.com/jellyfin/jellyfin-web/pull/6616#issuecomment-2768521400
i dont think it makes much sense to prevent an admin from viewing the Splashscreen when they are not prevented from deleting or updating it even when disabled.
**Issues**
none

allow admin users to get Splashscreen even when it's disabled

---

Emby.Server.Implementations/Library/LibraryManager.cs

Remove leading and tailing spaces from library names as they are used for on-disk storage which can cause issues.
#13429

Trim library names

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Model/LiveTv/TunerHostInfo.cs
src/Jellyfin.LiveTv/TunerHosts/M3UTunerHost.cs

This PR makes ReadInputAtNativeFramerate configurable for the M3U Tuner and works very similar to PR #7903 that added IgnoreDts as a configurable option.
Changes
Added ReadInputAtNativeFramerate to TunerHostInfo
Added ReadInputAtNativeFramerate checkbox to M3U tuner configuration page: https://github.com/jellyfin/jellyfin-web/pull/6659
Fixes #13772

Make ReadInputAtNativeFramerate configurable for M3U tuner

---

MediaBrowser.Model/Dto/BaseItemDto.cs
MediaBrowser.Model/Dto/BaseItemPerson.cs
MediaBrowser.Model/Entities/MediaStream.cs
MediaBrowser.Model/MediaSegments/MediaSegmentDto.cs
MediaBrowser.Model/Search/SearchHint.cs

**Changes**
This PR backports #13821 and part of #13277 to use the "Unknown" enum member as default value for all non-nullable properties in the API using an enum that has an Unknown member.
This is specifically needed in a 10.10 backport so a client build with the 10.10.7 API can still read responses from a 10.11 server now with the breaking API changes from #13277.
**Issues**

Backport 10.11 API enum changes

---

Jellyfin.Api/Controllers/DynamicHlsController.cs
src/Jellyfin.MediaEncoding.Hls/Playlist/CreateMainPlaylistRequest.cs
src/Jellyfin.MediaEncoding.Hls/Playlist/DynamicHlsPlaylistGenerator.cs

`mediaSourceId` can be `null`, the IDE doesn't know this as nullable is disabled for `BaseEncodingJobOptions`
```[00:00:12] [ERR] [10] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /Audio/9c5674da42b832621124effaacd189bf/main.m3u8.
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
at System.Guid.Parse(String input)
at Jellyfin.Api.Controllers.DynamicHlsController.GetVariantPlaylistInternal(StreamingRequestDto streamingRequest, CancellationTokenSource cancellationTokenSource) in /home/loma/dev/jellyfin/Jellyfin.Api/Controllers/DynamicHlsController.cs:line 1423
at Jellyfin.Api.Controllers.DynamicHlsController.GetVariantHlsAudioPlaylist(Guid itemId, Nullable`1 static, String params, …
```

Fix ArgumentNullException on playlist creation

---

Emby.Server.Implementations/Library/PathManager.cs

**Changes**
Use subdirectories based off the first two chars of the ID to better structure data (same as we do for internal metadata)
**Issues**
* Depending on filesystem, having thousands of subfolders in one directory might be a performance issue

Use subdirectories to organize extracted data

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Fix seeking beyond EOF again
It turns out that adding an offset of 0.5s does not cover all cases, thus increasing it to 5.0s covers more, especially to offset the effect of using `-noaccurate_seek` with MPEG-TS container.
**Issues**
- Fixes #13849
Tested with some affected video clips in web client using MPEG-TS and fMP4, the issue no longer occurs.

Fix seeking beyond EOF again

---

MediaBrowser.Common/Net/NetworkUtils.cs
tests/Jellyfin.Networking.Tests/NetworkParseTests.cs

This PR fixes that IP addresses without subnet mask were not being parsed correctly with the `bool negated` argument of the `NetworkUtils.TryParseToSubnet` function set to `true`, which leads to IP addresses from the "LAN networks" setting being classified as excluded in the `NetworkManager._excludedSubnets` variable, which in turn leads to these IP addresses not being considered local.
**Changes**
* Change `NetworkUtils.TryParseToSubnet` function to also respect the ! character for IP address without subnet
* Update `NetworkParseTests.TryParseValidIPStringsTrue` to test with both `true` and `false` for the `negated` parameter of the `TryParseToSubnet` function
**Issue details**
This PR fixes an issue which I encountered with the following setup:
* Jellyfin installed from the debian …

Fix negated IP addresses without subnet mask not being parsed correctly

---

Emby.Server.Implementations/Library/MediaSourceManager.cs
Jellyfin.Api/Helpers/MediaInfoHelper.cs
MediaBrowser.Model/Dlna/StreamBuilder.cs
MediaBrowser.Model/Dto/MediaSourceInfo.cs
MediaBrowser.Model/MediaInfo/AudioIndexSource.cs

The old logic will prefer the stream don't need transcoding with a very high priority. That behavior will mistakenly pick an audio stream in a language that is not preferred. We need to respect user preference in the StreamBuilder to limit the audio stream candidates.
**Changes**
~~A new `DefaultAudioIndexSource` field is added to `MediaSourceInfo`. This is exposed to the API as the server-side clone is done by json serialization and deserialization which will reset all `JsonIgnore` fields. If there are any better way to survive a deep clone and keep this field server side only, please let me know.~~
This field is now copied explicitly and is marked with `JsonIgnore`.
**Issues**
Closes #13813
Fixes #13774

Only reselect audio streams when user preference is respected

---

Jellyfin.Api/Controllers/StartupController.cs
tests/Jellyfin.Server.Integration.Tests/Controllers/StartupControllerTests.cs

**Changes**
* Don't include the (hashed) password in the response of the `/Startup/User` API
**Issues**
N/A

Remove the hashed password from startup users response

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

MediaInfo values can be null and then the `Trim()` throws
**Changes**
* Safeguard against trimming `null`

Safeguard against null value trimming in tag results

---

Emby.Server.Implementations/Library/Validators/GenresValidator.cs
MediaBrowser.Controller/Entities/BaseItem.cs

**Changes**
* Include `MusicGenre` items in the Genre cleanup
* Fetch real filesystem metadata on delete because the current synthetic one fails to handle names that include a `.`

Fix Genre cleanup

---

src/Jellyfin.Database/Jellyfin.Database.Providers.Sqlite/SqliteDatabaseProvider.cs

These warnings were introduced after BaseItem was migrated to EFcore. I already submitted a PR to fix upstream, but until it's merged, it's better to have those warnings disabled so users doesn't get crazy when they do see them on their first 10.11.z startup

Remove 10.11.z EFcore migration warnings

---

Jellyfin.Api/Controllers/PlaystateController.cs

They are pretty much the same except that:
- ReportPlaybackXXX endpoints use a POST body
- OnPlaybackXXX endpoints use query parameters
- ReportPlaybackXXX supports more data
We'll probably have to support the old endpoints for a while though as a lot of clients use it.
**Changes**
- Deprecate OnPlaybackXXX API operations in favor of ReportPlaybackXXX
**Issues**

Deprecate OnPlaybackXXX API operations in favor of ReportPlaybackXXX

---

.github/workflows/pull-request-conflict.yml

Currently, looking at the actions log of this repo, the merge conflict labeler is run on all comments, including issues. Changes the GHA file to only run it on PRs.
**Changes**
Add a condition to only run the GHA on pull requests
**Issues**
None

Only run merge conflict labler action on pull requests

---

Emby.Server.Implementations/Library/LibraryManager.cs

**Changes**
Changed FindExtras() and GetExtra() to identify if there are more than one file in the directory. If this is the case, the files will receive "IsInMixedFolder=true" to avoid issues for subsequent steps like deleting a single Extra.
**Issues**
#13250

Fix IsInMixedFolder not being set for Extras

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

ffmpeg now does not accept limited range yuv as mjpeg encoder directly and will error out as that is not compliant with the standard, which will fail the image extractor silently when the tonemap is happening as our tonemap filter defaults to output in a range same as the input, and for most of the video files, the input would be in limited range yuv.
This PR now explicitly requires the tonemapx and zscale filters to output in full range to comply with the standard.
This PR also fixed spacing problems due to unnecessary trimming and a logic error to prevent the image extractor to be reran when I frame only mode failed. The new added mpegts workaround currently overwrites the `useIFrame` parameter which prevents the image extractor to be rerun in fallback mode to do the fallback …

Fix image extractor with more strict ffmpeg requirement

---

Jellyfin.Server/ServerSetupApp/SetupServer.cs

**Changes**
Changed the log file sorting from `OrderBy` to `OrderByDescending`
**Issues**
The startup logger was showing the oldest log file instead of the newest.

Fix startup logger log file order

---

Emby.Server.Implementations/Library/PathManager.cs

**Changes**
Get filename using `Path.GetFileName()` before changing extension. 
Reverted to using `Path.Combine()` instead of` Path.Join()`
**Issues**
Fixes: #14035

Fix trickplay directory path construction

---

Emby.Naming/Common/NamingOptions.cs

**Changes**
Sometimes different parts of an album are split up into folders labelled "part". Allow these to stack in albums instead of splitting into separate ones. Simply add the string "part" to the list of allowed album prefixes.
**Issues**
I was having issues with my albums showing as multiple different ones, despite the tags being correct. It was because of folder naming.

Add "part" as possible album prefix for stacking

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
MediaBrowser.Controller/MediaEncoding/FilterOptionType.cs
MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

**Changes**
- Detect alpha_format from vf_overlay_{cuda,opencl} options
- Fix the transparency issue of ASS subtitle rendering in HWA
- Enable AFBC for RKMPP AV1 decoder to save mem bandwidth
**Issues**
- For details https://github.com/jellyfin/jellyfin-ffmpeg/pull/562

Fix the transparency issue of ASS subtitle rendering in HWA

---

Emby.Server.Implementations/AppBase/BaseApplicationPaths.cs
Emby.Server.Implementations/IO/ManagedFileSystem.cs
Emby.Server.Implementations/Library/DotIgnoreIgnoreRule.cs
Emby.Server.Implementations/Library/LibraryManager.cs
Emby.Server.Implementations/Library/MediaSourceManager.cs
Emby.Server.Implementations/Localization/LocalizationManager.cs
Jellyfin.Api/Controllers/SyncPlayController.cs
Jellyfin.Server.Implementations/StorageHelpers/StorageHelper.cs
Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
MediaBrowser.Model/IO/AsyncFile.cs
src/Jellyfin.Extensions/FileHelper.cs
src/Jellyfin.LiveTv/Channels/ChannelManager.cs
tests/Jellyfin.Extensions.Tests/FileHelperTests.cs
tests/Jellyfin.Server.Implementations.Tests/Plugins/PluginManagerTests.cs
tests/Jellyfin.Server.Integration.Tests/OpenApiSpecTests.cs

* Add a helper function to efficiently create empty files
* Use enumeration methods to gets files where possible
* Don't check for directory existence before calling Directory.Create
* Add AsyncFile.Create helper function
Benchmark results for the different file creation options:
```
| Method                | Mean     | Error     | StdDev    | Gen0   | Allocated |
|---------------------- |---------:|----------:|----------:|-------:|----------:|
| FileCreate            | 2.544 us | 0.0026 us | 0.0021 us | 0.0038 |     232 B |
| FileCreateEmptyBuffer | 2.511 us | 0.0050 us | 0.0046 us |      - |     160 B |
| FileWriteAllBytes     | 2.744 us | 0.0030 us | 0.0028 us |      - |      64 B |
| FileOpenHandle        | 2.448 us | 0.0071 us | 0.0066 us |      - |      64 B |
```

Cleanup file related code

---

Jellyfin.Server/Migrations/JellyfinMigrationAttribute.cs
Jellyfin.Server/Migrations/JellyfinMigrationService.cs
Jellyfin.Server/Migrations/PreStartupRoutines/CreateNetworkConfiguration.cs
Jellyfin.Server/Migrations/PreStartupRoutines/MigrateEncodingOptions.cs
Jellyfin.Server/Migrations/PreStartupRoutines/MigrateMusicBrainzTimeout.cs
Jellyfin.Server/Migrations/PreStartupRoutines/RenameEnableGroupingIntoCollections.cs
Jellyfin.Server/Migrations/Routines/AddDefaultCastReceivers.cs
Jellyfin.Server/Migrations/Routines/AddDefaultPluginRepository.cs
Jellyfin.Server/Migrations/Routines/CreateUserLoggingConfigFile.cs
Jellyfin.Server/Migrations/Routines/DisableTranscodingThrottling.cs
Jellyfin.Server/Migrations/Routines/FixAudioData.cs
Jellyfin.Server/Migrations/Routines/FixPlaylistOwner.cs
Jellyfin.Server/Migrations/Routines/MigrateActivityLogDb.cs
Jellyfin.Server/Migrations/Routines/MigrateAuthenticationDb.cs
Jellyfin.Server/Migrations/Routines/MigrateDisplayPreferencesDb.cs
Jellyfin.Server/Migrations/Routines/MigrateKeyframeData.cs
Jellyfin.Server/Migrations/Routines/MigrateLibraryDb.cs
Jellyfin.Server/Migrations/Routines/MigrateRatingLevels.cs
Jellyfin.Server/Migrations/Routines/MigrateUserDb.cs
Jellyfin.Server/Migrations/Routines/MoveExtractedFiles.cs
Jellyfin.Server/Migrations/Routines/MoveTrickplayFiles.cs
Jellyfin.Server/Migrations/Routines/ReaddDefaultPluginRepository.cs
Jellyfin.Server/Migrations/Routines/RefreshInternalDateModified.cs
Jellyfin.Server/Migrations/Routines/RemoveDownloadImagesInAdvance.cs
Jellyfin.Server/Migrations/Routines/RemoveDuplicateExtras.cs
Jellyfin.Server/Migrations/Routines/RemoveDuplicatePlaylistChildren.cs
Jellyfin.Server/Migrations/Routines/UpdateDefaultPluginRepository.cs

MigrateKeyframeData and MigrateRatingLevels has a new key set which is a workaround to reexecute the migration on next run so we get the same result by removing the legacy key.
MigrateLibraryDb, MoveExtractedFiles, MoveTrickplayFiles and RefreshInternalDateModified dont not need a key as they never been executed.

Only consider migrations that have key set for migration.xml migration

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Use VBR and MBBRC in QSV encoders for better quality
Use VBR for better bitrate allocation. Enable MacroBlock level bitrate control for better subjective visual quality.

Use VBR and MBBRC in QSV encoders for better quality

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

In .NET, `float.TryParse("NaN", NumberStyles.Float, CultureInfo.InvariantCulture, out var value)` returns `true` and value will be `float.NaN`.
Only accept finite values for replaygain tag.
**Changes**
**Issues**
Fixes #13290

Reject invalid replaygain tag value

---

Jellyfin.Server.Implementations/Item/BaseItemRepository.cs
MediaBrowser.Providers/Plugins/Tmdb/TmdbExternalUrlProvider.cs

**Changes**
- Added null checks for `episode.Series` and `season.Series`
- Changed `Imdb `to `Tmdb`
- Fixed the comparison operator for `maxWidth `and `MinPremiereDate`
**Issues**
<details>
<summary>Log Error</summary>
```
System.ArgumentNullException: Value cannot be null. (Parameter 'instance')
at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
at MediaBrowser.Model.Entities.ProviderIdsExtensions.TryGetProviderId(IHasProviderIds instance, String name, String& id) in C:\git\jellyfin\MediaBrowser.Model\Entities\ProviderIdsExtensions.cs:line 50
at MediaBrowser.Model.Entities.ProviderIdsExtensions.TryGetProviderId(IHasProviderIds instance, MetadataProvider provider, String& id) in …
```

Fix ArgumentNullException in TmdbExternalUrlProvider

---

src/Jellyfin.Drawing/ImageProcessor.cs

**Changes**
SVG files were not included in the` _transparentImageTypes` list, which caused them to be rendered with an opaque background. This change adds `.svg `to that list to preserve transparency when processed.
Before:
With Fix:
**Issues**
Fixes: #13956
Fixes: [#3941](https://github.com/jellyfin/jellyfin-androidtv/issues/3941)
Other clients have already implemented workarounds for this issue, ex: [#301](https://github.com/jellyfin/jellyfin-roku/issues/301)

Add SVG to transparent image types

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Offload 1080p+ subtitle scaling to RKRGA (perf ~4k60 => ~4k75, PGS + tonemap)
- Fix RKRGA 2pass scaling issue caused by auto AR reduction (only cover common values, not extreme values ​​like 1x1)
**Issues**
- Fixes #14073

Offload 1080p+ subtitle scaling to RKRGA

---

MediaBrowser.Model/Extensions/EnumerableExtensions.cs

Some Movies/series images on TMDB have very close ratings (differing by hundredths) but the JF UI only displays rating to the tenths. This results in seemingly out of order images. 
**Changes**
Community Rating is rounded to nearest tenths when sorting, hundredths are not significant IMO. This results in a more intuitive display. Now number of votes has the proper weight when rating is so close.
**Before**
**After**

Round RemoteImage CommunityRating to nearest tenths when sorting

---

Emby.Server.Implementations/Localization/iso6392.txt

``pob`` and ``pop`` are not valid iso 639 codes for Portuguese. Wikipedia says ``pop`` is Pwapwâ (https://en.wikipedia.org/w/index.php?title=ISO_639:pop) and ``pob`` is Poqomchiʼ (https://en.wikipedia.org/w/index.php?title=ISO_639:pob).
For testing, it was needed to rescan the specific files. Just renaming/adding subtitle files was not enough, but the movie had to be new.
**Changes**
Changed the values to ``por`` which is the valid ISO 639-2 code for Portuguese.
Before this PR subtitle files like ``movie.pt-br.srt`` would be scanned as ``pob``:
After this PR they are read as ``por``:
**Issues**
Should fix the problem referenced by @webysther in #6302.

Localization/iso6392.txt: Correct the Portuguese entries

---

tests/Jellyfin.LiveTv.Tests/Listings/XmlTvListingsProviderTests.cs

Fix failing unit tests on machines where the local timezone offset is far enough away from the test data day to be off by a day.
**Changes**
Change the test startdate to specifically be utc instead of local machine timezone.

Fix unittests

---

Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
MediaBrowser.Providers/Trickplay/TrickplayImagesTask.cs

**Changes**
* If trickplay is disabled for library all trickplay data is pruned
* If we refresh, all trickplay data will be removed and then for the current widths recreated
* If we just run, all trickplay data which is not matching the current configuration is removed
* When running the scheduled task we also prune any data for libraries where trickplay was disabled
**Issues**
Fixes #13918

Prune trickplay data on regenerate and scan

---

MediaBrowser.Providers/Manager/MetadataService.cs

Jellyfin fails to fetch metadata for new items during regular library scans when running in negative UTC timezones on initial scan. The timezone offset is incorrectly applied to `DateTime.MinValue,` causing `== default(DateTime) `comparisons to fail.
**Changes**
Replace timezone-sensitive default DateTime comparisons with date-only comparisons
**Issues**
Fixes #13114

Fix metadata not refreshing in negative UTC timezones

---

Emby.Server.Implementations/Session/SessionManager.cs

This PR addresses a thread safety issue in SessionManager.GetSessionInfo where concurrent access could lead to a race condition.
Fixes #14132

Fix race condition in SessionManager.GetSessionInfo

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Such videos cannot be played properly without dovi metadata anyway, and we should abort the copy check before metadata removal check to force a transcoding on clients without dovi capabilities.
**Changes**
**Issues**
Fixes this: https://github.com/jellyfin/jellyfin/pull/13277#discussion_r2134461415

Don't attempt to do metadata removal for dovi without fallback

---

CONTRIBUTORS.md
Emby.Server.Implementations/Library/Validators/CollectionPostScanTask.cs

From discussion in  #14237 : 
Fixes #12862 by not locking newly created collections. Once collections are locked, the remote metadata providers are no longer run, which leads to collection information (metadata as well as thumbnails) not being collected since TmdB is a RemoteMetadataProvider.
Existing collections need to be deleted manually after this fix has been merged / shipped.

fix(collection): Do not lock newly created collections

---

CONTRIBUTORS.md
Jellyfin.Server.Implementations/MediaSegments/MediaSegmentManager.cs
MediaBrowser.Controller/MediaSegments/IMediaSegmentManager.cs
MediaBrowser.Model/MediaSegments/MediaSegmentGenerationRequest.cs

**Changes**
With this PR, media segment providers now can decide for each existing segment if they want to keep it or generate new ones.
--- 
**Original Description**
**Changes**
With this PR, media segment providers can now determine whether segments generated by them should be deleted and re-generated on each scan.
**Why not just re-generate the segments of all providers on scan?**
That was my first idea, but I do think it was intentional that the original implementation did not do that. E.g., if a provider grabs data over the network, refreshing them every 24h would not be optimal.
**Remaining issue**
While this resolves the original issue #14117 for all providers that set `DeleteOnScan = true`, segments generated by other providers still have no way of being deleted.
Maybe it would be …

Fix existing media segments not being handled on scan

---

Emby.Server.Implementations/Library/LibraryManager.cs
MediaBrowser.Providers/Manager/MetadataService.cs
MediaBrowser.Providers/Music/AlbumMetadataService.cs

People need to be associated AFTER the item is created, otherwise foreign key issues happen.
**Changes**
* Extract `SetPeople` to be run after saving instead of when updating metadata from children
* Skip People creation if local metadata path creation fails
**Issues**
Fixes #14245
Fixes #14283

Fix People Issues

---

MediaBrowser.Controller/Entities/BaseItem.cs

If image files are manually removed, deleting the image entry fails if the file path is empty.
**Changes**
* Check if path is null empty or whitespace and only remove from file system if it is not
**Issues**
Fixes #14301

Only remove image file if it exists

---

MediaBrowser.Model/Dlna/ResolutionNormalizer.cs

The previous linear scaling model is inefficient for modern codecs for high frame rate(>30fps) videos. It may force an extremely low resolution like 540p, under poor network conditions(<5Mbps). High frame rates benefit from H264’s temporal inter-frame compression, and human perception of quality diminishes with increasing frame rates. Square root scaling for high framerate videos fits the use case better.
**Changes**
**Issues**
Fixes #14238

Use square root scaling for high framerate videos' bitrate requirements

---

Emby.Server.Implementations/Session/SessionManager.cs

When a sync play group is created it is checking the sessions `FullNowPlayingItem` property to determine if it should start playback. This property wasn't being set when playback stopped for the session. Newly created groups would then automatically start playback on items that were no longer being played on the session.
**Changes**
Set `FullNowPlayingItem` to null in `RemoveNowPlayingItem` method to ensure `FullNowPlayingItem` and `NowPlayingItem` are kept in sync on item removal and groups don't see a stale value

Fix issue with syncplay group incorrectly playing content on creation

---

Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Jellyfin.Server/Filters/RetryOnTemporarilyUnavailableFilter.cs

Nothing too big of a change, but noticed a typo in the API 503 response while contributing to another project. `Temporarly` is now `Temporarily` in the 503 response. Didn't create an issue for this as it didn't seem to fit into any issue type, and the change is more of a 'might as well' instead of a breaking issue.
- Fix typo in class name 
> `RetryOnTemporarlyUnavailableFilter` -> `RetryOnTemporarilyUnavailableFilter`
- Fix typo in API 503 response description
> `temporarly` -> `temporarily`
- Fix typo in file name 
> `.../Filters/RetryOnTemporarlyUnavailableFilter.cs` -> `.../Filters/RetryOnTemporarilyUnavailableFilter.cs`

Fix typo in 503 response for API

---

Jellyfin.Server/Migrations/Stages/CodeMigration.cs

The StartupLogger<TCategory> already implements IStartupLogger<TCategory> and there is no explicit implementation of the interface in NestedStartupLogger. Remove the redundant type declaration to silence complier warning.
**Changes**
**Issues**

Fix compiler warning for CodeMigration.cs

---

MediaBrowser.Controller/Entities/Folder.cs
MediaBrowser.Controller/Entities/TV/Season.cs
MediaBrowser.Controller/Entities/UserRootFolder.cs
MediaBrowser.Controller/Entities/UserViewBuilder.cs

Sorting was always enabled so removed the `enableSorting` parameter in QueryResult method.
**Changes**
To correctly answer the query we need to enable sorting. As no other call is done without enabling sorting, I rework the thing to get rid of this parameter.
**Issues**
Fixes #13224

Fix seasons random (#13224)

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs

Prefer ALBUMARTISTS to ALBUMARTIST when PreferNonstandardArtistsTag set
**Changes**
Jellyfin implemented ARTISTS multivalue tag but did not implement the equivalent ALBUMARTISTS multivalue tag.  This change adds ALBUMARTISTS support.  If present and PreferNonstandardArtistsTag is set, ALBUMARTISTS will be used in preference to ALBUMARTIST.  As with ARTISTS, the intent is to offer support for multiple album artists without affecting software that does not read ALBUMARTIST as a multivalued tag.  Jellyfin supports multiple album artists.
Example album before/after:
ALBUM           : Amici e Rivali
ARTIST          : Lawrence Brownlee / Michael Spyres
album_artist    : Lawrence Brownlee
ARTISTS         : Lawrence Brownlee;Michael Spyres
ALBUMARTISTS    : Lawrence Brownlee;Michael Spyres
Before …

Prefer ALBUMARTISTS to ALBUMARTIST when PreferNonstandardArtistsTag set

---

MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
MediaBrowser.Providers/Music/AlbumMetadataService.cs

Fix PeopleHelper.AddPerson ArgumentException.ThrowIfNullOrEmpty(person.Name) due to bad meta-data extracts.
Ignore metadata extracts with blank names.

Fix PeopleHelper.AddPerson Exceptions due to bad meta-data extracts.

---

Emby.Server.Implementations/Library/LibraryManager.cs
Jellyfin.Server.Implementations/Item/BaseItemRepository.cs

fixes https://github.com/jellyfin/jellyfin/issues/14412
fixes https://github.com/jellyfin/jellyfin/issues/14384
fixes https://github.com/jellyfin/jellyfin/issues/14331
Introduces new bug, manually saved images might not bust the internal cache and need to be refreshed during a scan. This is however better then just failing to scan overall.

Only save images when changed

---

MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

**Changes**
- Only enable VAAPI MJPEG encoder on Intel iHD driver
iHD should always be used, as it covers all platforms that support the MJPEG encoder.
**Issues**
- Fixes #14432

Only enable VAAPI MJPEG encoder on Intel iHD driver

---

Jellyfin.Server.Implementations/Extensions/ServiceCollectionExtensions.cs
src/Jellyfin.Database/Jellyfin.Database.Implementations/IJellyfinDatabaseProvider.cs
src/Jellyfin.Database/Jellyfin.Database.Providers.Sqlite/SqliteDatabaseProvider.cs

Allow DatabaseProvider access to the DatabaseConfigurationOptions from the settings file to better handle custom configuration
For Sqlite its now supported to set the folowing options via the database.xml
```xml
<CustomProviderOptions>
<Options>
<CustomDatabaseOption>
<Key>Cache</Key>
<Value>Shared</Value>
</CustomDatabaseOption>
<CustomDatabaseOption>
<Key>Pooling</Key>
<Value>True</Value>
</CustomDatabaseOption>
</Options>
</CustomProviderOptions>
```

Allow loading of Database options for DB provider

---

Emby.Server.Implementations/Localization/iso6392.txt

The correct ISO 639-2/T for Serbia is srp, scc was deprecated in 2008: https://www.loc.gov/standards/iso639-2/php/code_changes.php
**Issues**
Fixes #14473

Fix Serbian ISO 639-2 codes

---

MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

If ffmpeg runs to completion, i.e. isn't killed due to being unresponsive, its exit code is >0 in case of an error. However, the current logic only throws an exception in case the exit code is -1, which is the virtual exit code assigned in case ffmpeg has been killed prematurely.
This commit simplifies the logic to throw an exception if ffmpeg didn't run to completion (as before) or exited with a non-zero exit code (new).
This change is especially important for #14467, as the fallback will not be triggered if ffmpeg errors are not recognized properly.

Fix trickplay extraction ffmpeg error-handling

---

CONTRIBUTORS.md
MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs

Keyframe-only trickplay image extraction can fail for some media files. The current behavior is to skip the media file and try again on the next run, which will fail again.
This adds a fallback to regular non-keyframe-only extraction for failed runs, so the extraction can complete.
I implemented it in `MediaEncoder.ExtractVideoImagesOnIntervalAccelerated` analogously to `MediaEncoder.ExtractImage`, which already has a similar fallback:
https://github.com/jellyfin/jellyfin/blob/982e0c9370da3d940799c9292423edeca71b7b71/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs#L630-L644
`MediaEncoder.ExtractVideoImagesOnIntervalAccelerated` is called by `TrickplayManager.RefreshTrickplayDataInternal`, so alternatively is could also be implemented there: …

Add fallback for keyframe-only trickplay extraction

---

Jellyfin.Server.Implementations/Item/BaseItemRepository.cs

I know it's a hack but this currently prevents my scans from completing and I was unable to find the root cause. This at least doesn't break the scans

Don't fail image saving on missing BaseItem

---

Emby.Naming/ExternalFiles/ExternalPathParser.cs
Emby.Server.Implementations/Library/MediaSourceManager.cs
Emby.Server.Implementations/Localization/LocalizationManager.cs
Emby.Server.Implementations/Localization/iso6392.txt
Jellyfin.Api/Controllers/ItemUpdateController.cs
Jellyfin.Api/Controllers/LocalizationController.cs
MediaBrowser.Model/Entities/MediaStream.cs
tests/Jellyfin.Server.Implementations.Tests/Localization/LocalizationManagerTests.cs

Current support for BCP 47 language tags is still very much lacking, with some languages not being recognized and displayed correctly.
They are correctly supported through regionalized language code recognition in `.NET`.
Refer https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.getcultures?view=net-9.0
Before:
After:
**Changes**
Based on #14407
Further refinement of BCP 47 language labeling support
**Issues**
Fixes #6302

Further refinement of BCP 47 language labeling support

---

MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs

The current implementation only extracts from the main container. This makes SRT/ASS subtitles from MKS files unusable (except when burning them in), because the server expects to retrieve them from the subtitles directory.
This change also extracts subtitles from MKS files that are associated with the video file and stores them in their appropriate location, so the client can request and render them.
**Changes**
Adds additional subtitle extractor logic for MKS file(s).
**Issues**
https://github.com/jellyfin/jellyfin/issues/12236

Extract subtitles of MKS aux files if they're extractable.

---

Emby.Server.Implementations/Library/LibraryManager.cs

Because this operate son the updated base item which already has non-existing images removed, without saving those non-existing get never removed from the database and we re-run scans because of it on every scan.
**Changes**
* always save image infos of base item
**Issues**

Always save images

---

Jellyfin.Server.Implementations/Item/BaseItemRepository.cs

**Changes**
This change refactors a critical query used by APIs like /Artists to replace nested EXISTS with explicit JOINs. This enables index usage and eliminates timeouts when querying large libraries.
A client like Manet requesting /Artists with limit = 200 could not complete library sync due to SQL command timeout because the query could not use indexes.  With this change, a SQL query simulating /Artists retrieving all artists ran on my system in 0.173 ms, and Manet is able to complete full library sync successfully. /Artists performs OK overall even with limit = 0 following this change, while other APIs remain slow due to DTO overhead but at least all API used by Manet complete execution now where they previously could not.
My library is approximately 3200 artists, 2500 albums, 41.5k …

Refactor query from EXISTS to JOIN to avoid API timeouts with large libraries

---

Emby.Server.Implementations/Dto/DtoService.cs
MediaBrowser.Controller/Entities/Audio/MusicArtist.cs
MediaBrowser.Controller/Entities/Audio/MusicGenre.cs
MediaBrowser.Controller/Entities/Genre.cs
MediaBrowser.Controller/Entities/IItemByName.cs
MediaBrowser.Controller/Entities/Person.cs
MediaBrowser.Controller/Entities/Studio.cs
MediaBrowser.Controller/Entities/TaggedItemCounts.cs
MediaBrowser.Controller/Entities/Year.cs

**Changes**
For API call /Items/{item id} GetBaseItemDto will return the counts of related items e.g. artists, albums, songs.  GetBaseItemDto currently does this by calling GetTaggedItems which retrieves the objects into memory to count them.  Replace with SQL count.
**Issues**
No known open bugs.
This should be an improvement for any large libraries, but especially large music libraries.  Example:
Request Library -> Genres -> any very popular genre in your large library, e.g. Classical Number of albums = 1552, songs = 23515, ...
- Before change: Try to retrieve 1552 albums, 23515 songs, ... in memory, API never returns, database on fire
- After change: API returns in 367ms and Genre view opens with 200 albums in 2 seconds
I verified the numbers returned are correct but note that there is …

Fix GetBaseItemDto to return related item counts via SQL count

---

Jellyfin.Server.Implementations/Item/BaseItemRepository.cs

**Changes**
Use ItemValueType.AlbumArtist instead of ItemValueType.Artist when filtering by AlbumArtistIds to ensure the correct items are returned.
**Issues**
No issue raised

Fix AlbumArtistIds filter to use correct ItemValueType

---

CONTRIBUTORS.md
MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs

**Changes**
Previously, `IsAnamorphic` was set to `true` only when Sample Aspect Ratio (SAR) was `"0:1"`, causing incorrect detection for valid anamorphic videos. Updated the detection logic to handle common SAR/DAR edge cases, following the approach described https://stackoverflow.com/questions/17353387/how-to-detect-anamorphic-video-with-ffprobe.
**Issues**
Fixes #14640

Fix anamorphic video detection (#14640)

---

Jellyfin.Server/Migrations/Stages/CodeMigration.cs

**Changes**
Delay initialization of singleton services during migration CoreInitialisation stage
**Issues**
Jellyfin code migrations that run during EF Core migrations generate:
```
[07:35:34] [ERR] [7] InternalCodeMigration: Migration 20250814000002_RemoveDuplicatePeopleStage2 failed System.NullReferenceException: Object reference not set to an instance of an object.
at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager..ctor(IMemoryCache memoryCache) in /src/MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs:line 40
```
due to TmdbClientManager being initialized too early.
Credit: JPVenson

Delay initialization of singleton services during migration CoreInitialisation stage

---

MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs

In PR #14648 new analysis for isAnamorphic was added. The string comparisons there were added as StringComparison.OrdinalIgnoreCase, but the actual strings are always digits:digits (e.g. 3:4) so there's no alphabetic values to ignore case of... since StringComparision.Ordinal is much faster, switch to that.
Also, morphed all the private methods that should be to static since that eliminates a null-ref check on the this (at call-sites) and also makes the JIT happy.

Normalizer cleanup

---

MediaBrowser.Providers/Manager/MetadataService.cs
MediaBrowser.Providers/Music/AlbumMetadataService.cs

**Changes**
Correct Album Artists merge logic in MetadataService that causes empty
metadata sources to overwrite populated Album Artists arrays. This impacted
People-to-BaseItem relationships and caused orphaned records in Peoples.
Correct equality checks to be case-sensitive so Jelly metadata exactly
matches file metadata.
**Issues**
This impacted People-to-BaseItem relationships and caused orphaned records in Peoples.
File metadata changes that varied only in case were not updated in Jellyfin, causing Firstname Lastname and firstname lastname to be 2 separate records because the metadata update was case-insensitive but people record names are case-sensitive.

Correct Album Artists merge logic

---

README.md

This updates the mention of .Net Core to say .Net instead. 
It also solves a slight grammatical issue. 
Additionally, I let the text have a bit more space to breathe. :)

Update .Net Core to .Net

---

Emby.Server.Implementations/ScheduledTasks/Tasks/AudioNormalizationTask.cs

Change db updating in AudioNormalizationTask to save in 5 min intervals of work to make sure progress is saved regularly so if the task is cancelled progress is not lost.
As requested by https://github.com/jellyfin/jellyfin/pull/14306.
**Changes**
Break up the SaveItems into roughly 5 min intervals of work.
**Issues**
https://github.com/jellyfin/jellyfin/pull/14306

AudioNormalizationTask db progress saving

---

MediaBrowser.Providers/Manager/MetadataService.cs
tests/Jellyfin.Providers.Tests/Manager/MetadataServiceTests.cs

**Changes**
3D format is filename-based and not included in metadata providers. This change prevents it from being cleared during a full metadata refresh unless a new value is available.
**Issues**
Fixes #13864

Preserve 3D format on metadata refresh

---

Emby.Server.Implementations/Library/LibraryManager.cs

It can happen that `item.ValidateImage()` which removes inaccessible images was not run before this method is run, so non-existing images could be probed here, leading to a lot of unneccessary log spam about not found images.
**Changes**
* check for file existence and skip if unavailable
**Remarks**
It might make sense to additionally call `item.ValidateImage()` at the end of the method just to be sure that images are in a clean state when returning.

Skip removed images when updating images

---

Jellyfin.Server.Implementations/Item/BaseItemRepository.cs

**Changes**
Follow up for #14249, adding back the missing behavior to query items with any value for a provider id set.
I noticed while testing the 10.11 RC 5 that the `HasAnyProviderId` usage with an empty value was broken compared to 10.10, where it previously allowed you to query for all base items with the the given providers set regardless of the actual ID. Tested that it works locally.
**Issues / PRs**
https://github.com/jellyfin/jellyfin/issues/14108
https://github.com/jellyfin/jellyfin/pull/14249

fix: add back missing behavior for HasAnyProviderId

---

src/Jellyfin.Database/Jellyfin.Database.Providers.Sqlite/Migrations/20250913211637_AddProperParentChildRelationBaseItemWithCascade.cs

**Changes**
The WHERE clause was selecting the ParentId from the parent item, not the actual item we wanted to check.
**Issues**
Fixes #14888
Fixes #14894

Fix AddProperParentChildRelationBaseItemWithCascade migration deleting all items

---

Jellyfin.Server.Implementations/Item/BaseItemRepository.cs

**Changes**
- Changed min/max parental rating filters from `>=`/`<=` to `>`/`<` for score comparison
- Added subscore as a tie-breaker when main scores are equal
- Used `InheritedParentalRatingSubValue` field to properly compare subscores
**Issues**
Fixes filtering issues. For example, filtering by a parental rating of "R" only displayed "PG" items. Tested with various ratings and filtering now works correctly.

Fix parental ratings

---

Jellyfin.Server.Implementations/Item/BaseItemRepository.cs

Currently the total record count for getitems is populated before grouping. Which results in the wrong count if grouping is applied.
This fixes the issue by getting the total count after grouping

fix: get total count after grouping

---

Emby.Server.Implementations/Library/LibraryManager.cs

**Changes**
Changed the AddVirtualFolder method so that ValidateTopLibraryFolders is always called, regardless of whether the refreshLibrary argument was passed into AddVirtualFolder. This ensures that the new libraries are loaded after completing the startup wizard without triggering a full re-scan. 
**Issues**
Fixes #14868

Fix libraries not loading after startup wizard, Change AddVirtualFolder to validate folders

---

MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs
MediaBrowser.Providers/Plugins/Tmdb/TmdbUtils.cs
tests/Jellyfin.Providers.Tests/Tmdb/TmdbUtilsTests.cs

**Changes**
TMDb now returns `xx` for images that don't have a language, so this change only sets the image type to Thumb if the language is something other than that.
**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/14922

Handle xx as TMDb no language for backdrops

---

Jellyfin.Server.Implementations/Item/BaseItemRepository.cs

**Changes**
Replaced nested subqueries with a direct join between `BaseItems` and` Peoples` on `Name`, then filtered `PeopleBaseItemMap` using the resulting `People.Id`.
Individual cast and crew queries now take less than half a second compared to 2-5 seconds. 
**Issues**

Improve performance on people query
